### ISSUE TITLE
`raise-syntax-error` fails when called on cyclic s-expressions

### ISSUE THREAD

**Issue by samth** [racket/racket#1016]
```
> (define v (vector #f))
> (vector-set! v 0 v)
> (raise-syntax-error #f "" v)
datum->syntax: cannot create syntax from cyclic datum
  datum: #0='#(#0#)
```

The documentation for `raise-syntax-error` says that it accepts `any/c` in that position.

This is the cause of the DrDr failure here: http://drdr.racket-lang.org/30895/racket/share/pkgs/errortrace-test/tests/errortrace/simple.rkt (a `datum-case` pattern match is failing and leading to this error).

**Comment by Paul-C-Anagnostopoulos** [comment]
This behavior is still present. If it is considered a bug in `raise-syntax-error`, then I'll leave it to the pros. If it simply needs a sentence in the documentation, I'm happy to add that. Note that `datum->syntax` already talks about cyclic data.
