### ISSUE TITLE
raco pkg catalog-archive should be robust to errors in individual packages

### ISSUE THREAD

**Issue by tonyg** [racket/racket#1032]
If a package source is malformed (e.g. contains an invalid path, or simply contains bogus content), catalog-archive not only fails for that package, but for all remaining packages. This can be used as a DoS vector by adding a bogus package named "aaaaaa", for example.

Instead, catalog-archive should catch exceptions from processing individual packages, log the error, and continue processing the remainder of the packages. The final exit code should reflect the success of the operation as a whole, of course. (Perhaps this suggests that the Racket routine implementing the process should raise an exception at the end if any of the packages had exceptions.)

**Comment by mflatt** [comment]
At the `pkg-archive-pkgs` level, there's a `#:package-exn-handler` argument that provides control over failure. The `pkg-build` package uses that, for example.

For `raco pkg catalog-archive`, I think it makes sense to add a flag to specify how to handle a package failure: `fail` (as currently), `ignore` (log error but succeed), or `continue` (log error, continue archiving, and report failure at the end through a specific non-zero result).

I can make the default `ignore` or `continue`, but I'm not really sure that' would be better as the default. Maybe it's enough to offer options but keep the current default?
