### ISSUE TITLE
`raco make` fails with "require: identifier's binding is ambiguous", while `racket` succeeds

### ISSUE THREAD

**Issue by tonyg** [racket/racket#1033]
## To reproduce

1. `raco pkg install send-exp`.
2. Find the file `example.rkt` in the root directory of that package.
3. Run `racket example.rkt`. You will see a few lines of output about `hello`, a `balance`, `foo` and `zot`.
4. Run `raco make example.rkt`.

You will see the following error:

	send-exp/lang/reader.rkt:5:14: require: identifier's binding is ambiguous
	  context...:
	   #(-1114302456578077033 module) #(-1114302456578077032 module reader 0)
	   #(3461 module) #(3462 module example 0)
	  matching binding...:
	   #<module-path-index:(syntax/module-reader)>
	   #(-1114302456578077033 module) #(-1114302456578077032 module reader 0)
	  matching binding...:
	   #<module-path-index:(racket)>
	   #(3461 module) #(3462 module example 0)
	  in: require
	  compilation context...:
	   /home/tonyg/src/racket-send-exp/example.rkt
	  context...:
	   /home/tonyg/src/racket/racket/collects/syntax/wrap-modbeg.rkt:46:4
	   /home/tonyg/src/racket/racket/collects/compiler/cm.rkt:346:0: compile-zo*
	   /home/tonyg/src/racket/racket/collects/compiler/cm.rkt:561:26
	   /home/tonyg/src/racket/racket/collects/compiler/cm.rkt:553:42
	   /home/tonyg/src/racket/racket/collects/compiler/cm.rkt:518:0: maybe-compile-zo
	   /home/tonyg/src/racket/racket/collects/compiler/cm.rkt:633:2: do-check
	   /home/tonyg/src/racket/racket/collects/compiler/cm.rkt:713:4
	   /home/tonyg/src/racket/racket/share/pkgs/compiler-lib/compiler/commands/make.rkt:81:8: for-loop
	   /home/tonyg/src/racket/racket/share/pkgs/compiler-lib/compiler/commands/make.rkt: [running body]
	   /home/tonyg/src/racket/racket/collects/raco/raco.rkt: [running body]

## Expected

In step 4, the compilation should succeed. (And running the result should be identical to `racket example.rkt`.)

**Comment by mflatt** [comment]
The reader in `send-exp` is not right for the new macro system. See the discussion at
 https://groups.google.com/d/msg/racket-dev/6khgHKygmS4/bWHpC04v8HwJ
and the example
 https://github.com/AlexKnauth/afl/commit/b0207da998a81c83af3f4ba1124339dbf4026da7
or
 https://github.com/greghendershott/rackjure/commit/58a9c87d00ea0927d5a73ad29867bf255fad9fbb

That "example.rkt" runs in plain `racket` is a bug that comes from trying to make the top level work, and I should be able to fix that.

**Comment by tonyg** [comment]
Thanks, Matthew; I'm closing this issue now, because I fixed this (in tonyg/racket-send-exp@94a8101bc410101327b0e65722512e5e8d0b1599) a couple of months ago.
