### ISSUE TITLE
There is no way to check validity of DrRacket downloads

### ISSUE THREAD

**Issue by magicgoose** [racket/racket#1054]
- The archives are served only through http (not https);  
- There are no published checksums;  
- And (in the OS X case) the .app bundle is not digitally signed.

<img width="420" alt="screen shot 2015-09-12 at 5 09 09 pm" src="https://cloud.githubusercontent.com/assets/1442206/9831968/4ebd8e6a-5974-11e5-9f5e-8fbc17722c56.png">

Therefore, there is no way to tell if the file was maliciously modified while being downloaded.

That means, everyone who run a DrRacket build downloaded from the official site make themselves **vulnerable to arbitrary code execution.**

Some of possible ways to mitigate the issue, from easier to harder:
- host DrRacket packages on the GitHub (GitHub works through HTTPS, so MitM attacks are next to impossible), or
- host SHA-2 checksums of the packages in a place which is accessible through a secure channel — for example, on GitHub, or
- make the whole site work through HTTPS (not all certificates are paid — StartSSL offers free certificates with validation via email, and also [Let's Encrypt](https://letsencrypt.org/) will be functioning soon), or
- sign the .dmg packages (but it solves the problem only for OS X and requires paying money to Apple).

Solution no.1 is presumably the best of them, since it doesn't require a lot of additional work and the users don't need to manually verify checksums.

**Comment by eu90h** [comment]
Oh, good eye! I like these suggestions. HTTPS and checksums would be a nice start.

**Comment by mflatt** [comment]
We've now set up HTTPS for the web pages and the main distribution mirror. There's also a link  from the download page to a page (on the main mirror, via HTTPS) with SHA1 checksums. And we fixed the signing of executables on OS X and added signined for the Windows installer as part of the v6.3 release.

**Comment by stamourv** [comment]
AFAICT, this issue is resolved, correct? If so, let's close it.

**Comment by samth** [comment]
It might still be nice to 
 * have SHA2 checksums
 * have signed linux builds

**Comment by magicgoose** [comment]
Great news!  :+1: 
Then why not also change the site URL (in the repo short description) to https://racket-lang.org/? (was http://racket-lang.org/)
Also, plain-http version does not redirect to https (it might be useful for less security-aware users, and even better would be to also do https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security)

**Comment by mflatt** [comment]
I've adjusted the URL in the repo description.
As you might imagine, there have been various wrinkles in the switch to HTTPS, and I think it makes sense to let this first step settle for a few days before turning on HSTS.

**Comment by magicgoose** [comment]
Of course, it may be reasonable to wait. I simply wrote it here because I noticed it might be good to do, not necessarily right now.

**Comment by magicgoose** [comment]
is it time to close the issue?

**Comment by bunsim** [comment]
#1475 @mflatt It's been quite more than a "few" days and the website still doesn't use HSTS or redirect to HTTPS.

**Comment by einsteinsfool** [comment]
Ping.

There are SHA1 checksums on the [download page](https://download.racket-lang.org/releases/6.12) but SHA1 has been breaked as you can read [here](https://en.wikipedia.org/wiki/SHA-1#SHAttered_%E2%80%93_first_public_collision).

Ideally, SHA256 and SHA512 would be provided in plaintext (or .txt extension) both on the download page and on GitHub in the `releases` section.

For now, after I download an installer an attacker can theoretically intercept it and swap it with a modified malicious version that gives the same SHA1.

**Comment by magicgoose** [comment]
@einsteinsfool No you can't. There's no known attack on SHA1 that allows one to construct a file with a specific hash. The known attack allows one to generate 2 files with the same but unknown hash. So it won't apply for this case.

**Comment by einsteinsfool** [comment]
@magicgoose Correct. That's why I writed "theoretically". Because since the attack you described is possible, it's also possible that in the future "my" attack will be possible. The same happened to MD5, if I remember correctly. First way your attack and than mine. I think using SHA1 is irresponsible. NSA might have already breaked it. I'd go with the safe SHA256 and SHA512.

**Comment by magicgoose** [comment]
> The same happened to MD5, if I remember correctly.

If I remember correctly, the preimage attack was not invented for MD5 yet. It just got the collision attack much earlier than SHA-1, and it's generally faster and has smaller output size, so it's seen as more likely to eventually get a preimage attack.

SHA-256 still seems like a safer choice.

**Comment by einsteinsfool** [comment]
Well, this is embarassing. I was sure I saw a program that given file X and malicious file Y could append Y to produce the same MD5 as X. Did some googling and couldn't find it until I stumbled upon [evilize](https://www.mscs.dal.ca/~selinger/md5collision) which appears to be what I thinked was preimage attack (and it appends both files).

I spreaded so much false news. :'-( At least now I know better. Thanks!

**Comment by mflatt** [comment]
We've long since moved to HTTPs everywhere and enabled HSTS long ago. I've now switched the build checksum to SHA256 as demonstrated by https://www.cs.utah.edu/plt/snapshots/), although that won't take effect for normal distribrutions until v6.2.
