### ISSUE TITLE
Can't build the source (6.2.1) on OS X (unix-style) — version mismatch for dependency

### ISSUE THREAD

**Issue by magicgoose** [racket/racket#1058]
I tried `make unix-style PREFIX=/Applications/racket &> install_log.txt`
And here's the log: https://gist.github.com/magicgoose/8f086869b398f7892f15

    …
    raco pkg install: version mismatch for dependency
      for package: drracket
      mismatch packages:
       base (have 6.2.1, need 6.2.900.15)
    make[1]: *** [plain-unix-style] Error 1
    make: *** [unix-style] Error 2

**Comment by mflatt** [comment]
To build a version other than the current development version out of the Git repo's top-level `make`, you'll need to supply the corresponding release's catalog:

`make SRC_CATALOG=http://download.racket-lang.org/releases/6.2/catalog/`

I'll adjust "INSTALL.txt" to explain (but, as the start of "INSTALL.txt" tries to suggest, it's better to use the source distribution from the download page).
