### ISSUE TITLE
Possible to get `raco setup` stuck

### ISSUE THREAD

**Issue by samth** [racket/racket#1063]
I managed to get my package installation in a bad way, by removing a relevant directory from the installed location.

It now errors with:

```
[samth@huor:~/.../extra-pkgs/gui-lib/gui-doc (master) plt] raco setup -l setup
raco setup: directory: #<path:/home/samth/sw/plt/racket/share/pkgs/unstable-doc> does not exist for collection: "unstable"
  context...:
   /home/samth/sw/plt/racket/collects/setup/setup-core.rkt:317:2: collection-cc!20
   /home/samth/sw/plt/racket/collects/setup/setup-core.rkt:435:6: for-loop
   /home/samth/sw/plt/racket/collects/setup/setup-core.rkt:432:4: for-loop
   /home/samth/sw/plt/racket/collects/setup/setup-core.rkt:70:0: setup-core
   /home/samth/sw/plt/racket/collects/setup/setup-go.rkt: [running body]
   /home/samth/sw/plt/racket/collects/setup/main.rkt: [running body]
```

**Comment by samth** [comment]
Running with `raco setup -c` (which triggers bootstrapping) produces the same error. As does `raco pkg remove --force unstable-doc`.

**Comment by mflatt** [comment]
I don't think `raco setup` should try to fix that kind of state. It should be able to deal with arbitrarily out-of-date bytecode or other files that it's supposed to build, but I don't think it should try to patch up things like collection links.

**Comment by samth** [comment]
I wasn't thinking that it should fix the situation, just not be unable to continue. Do you think `raco pkg` should work? Should anything?

**Comment by mflatt** [comment]
I see the distinct you're making between "fix" and "continue", but I'm reluctant to commit `raco setup` to even continuing in this situation, because it seems more difficult to maintain than it's worth.

**Comment by samth** [comment]
Do you have a suggestion for what I should do to fix this installation?

**Comment by mflatt** [comment]
Does it help to create the directory that the error message complains about?

**Comment by samth** [comment]
Yes, that worked.
