### ISSUE TITLE
unix-style build failures

### ISSUE THREAD

**Issue by Giels** [racket/racket#1069]
It seems that make unix-style does not work currently. First, the make process attempts to use racket utilities such as racket and raco from the install prefix without first installing these utilities. Second, the palin-unix-style target fails with "raco pkg install: package is already installed (package: racket-lib)" when executing "<path>/raco pkg install -j <#> --catalog build/local/catalog --auto -i racket-lib main-distribution main-distribution-test". There may be additional problems but I haven't gotten further yet.

**Comment by mflatt** [comment]
Are you using a checkout where you previous ran `make in-place` or just `make`? I think you'd get the reported error in that case. Using `make unix-style` will work only with a fresh checkout.

**Comment by Giels** [comment]
I can confirm that starting from a clean clone works.

**Comment by Phlosioneer** [comment]
@mflatt This should be closed.
