### ISSUE TITLE
Ellipse escaping not possible in synax-case

### ISSUE THREAD

**Issue by samvv** [racket/racket#1080]
Not sure if this is right (maybe it is meant to be this way) but it seems that escaping ellipses is only possible in the much more simple `define-syntax-rule` whilst not possible in `syntax-case`.

This runs fine:

````racket
(define-syntax-rule (make-some-syntax-rule id)
    (define-syntax-rule (id expr (... ...))
      (display "it works!")))
````

This does not work:

````racket
(define-syntax-rule (make-some-syntax-rule id)
    (define-syntax (id stx)
      (syntax-case stx ()
        (_ expr (... ...))
        #'(display "it works!"))))
```

Test with:

````racket
(make-some-syntax-rule test)
(test)
> it works!
````

The second one fails with the following error:

    syntax: no pattern variables before ellipsis in template in: ...

It is debatable how useful this is, but I just wanted to point this out.

**Comment by soegaard** [comment]
You missed a set of parentheses:

#lang racket
(define-syntax-rule (make-some-syntax-rule id)
  (define-syntax (id stx)
    (syntax-case stx ()
      [(_ expr (... ...))
       #'(display "it works!")])))

(make-some-syntax-rule test)
(test)


2015-10-03 21:22 GMT+02:00 Sam Vervaeck <notifications@github.com>:

> Not sure if this is right (maybe it is meant to be this way) but it seems
> that escaping ellipses is only possible in the much more simple
> define-syntax-rule whilst not possible in syntax-case.
>
> This runs fine:
>
> (define-syntax-rule (make-some-syntax-rule id)
>     (define-syntax-rule (id expr (... ...))
>       (display "it works!")))
>
> This does not work:
>
> (define-syntax-rule (make-some-syntax-rule id)
>     (define-syntax (id stx)
>       (syntax-case stx ()
>         (_ expr (... ...))
>         #'(display "it works!"))))
>
> Test with:
>
> (make-some-syntax-rule test)
> (test)
> > it works!
>
> The second one fails with the following error:
>
> syntax: no pattern variables before ellipsis in template in: ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/racket/racket/issues/1080>.
>



-- 
-- 
Jens Axel Søgaard

**Comment by samvv** [comment]
Ok, never mind, silly me! Thanks.
