### ISSUE TITLE
string-prefix? change argument order

### ISSUE THREAD

**Issue by bennn** [racket/racket#1083]
@stchang just pointed out that  `string-prefix?` in `racket/base` has the signature:
```
(string-prefix? str prefix)
```
but [srfi/13](http://docs.racket-lang.org/srfi/srfi-std/srfi-13.html#string-prefix-p) implements
```
(string-prefix? prefix str)
```

Same goes for `string-suffix?`. I personally like giving the prefix 2nd, but we should probably change this to match the srfi. Also `list-prefix?` in `racket/base` takes its prefix first.

**Comment by samth** [comment]
I don't think there's any need to change to match the SRFI. Consistency with `list-prefix?` is more important, but not necessarily definitive.
