### ISSUE TITLE
`check-duplicates` is ambiguous when returning `#f`

### ISSUE THREAD

**Issue by philnguyen** [racket/racket#1092]
Function `check-duplicates` was added lately from `unstable/list` (used to be named `check-duplicate`). It's behavior is ambiguous: a result of `#f` either means the list has no duplicate, or the duplicate value is `#f`. In fact, the contract's range is `(or/c any/c #f)`, which is essentially `any/c`.

As I see no optional argument to help disambiguating these situations, I guess this was overlooked rather than intended?

**Comment by rfindler** [comment]
member gets around this by returning the tail of the list containing the searched for element, but that's ugly. 

Maybe an optional argument (defaulting to `#false`) that indicates what the "no duplicates" result is supposed to be?

**Comment by samth** [comment]
Another possibility is providing a continuation defaulting to `(lambda (x) #f)` which is passed the duplicate element.

**Comment by jackfirth** [comment]
It could also return a wrapper value in the manner of Haskell's Maybe. That makes less sense in untyped Racket however.

**Comment by rfindler** [comment]
How about something like `hash-ref` 's optional argument?

**Comment by samth** [comment]
Right, that's what I was suggesting, and I think it's the simplest solution.
