### ISSUE TITLE
Fuzzing infinite loop

### ISSUE THREAD

**Issue by samth** [racket/racket#1098]
```
r -l tests/racket/stress/fuzz -- -s 1019821227 -f ~/sw/plt/racket/collects/racket/private/compiled/list_rkt.zo 
```

**Comment by samth** [comment]
http://drdr.racket-lang.org/32247/pkgs/racket-test/tests/racket/stress/fuzz.rkt

**Comment by samth** [comment]
Maybe also http://drdr.racket-lang.org/32282/pkgs/racket-test/tests/racket/stress/fuzz.rkt

**Comment by samth** [comment]
This looks like it's a result of `list_to_scope_set` getting passed a circular list, but I can't quite tell. @mflatt: what should happen in that case/is there a way to check for circular lists/is that possible here?

**Comment by samth** [comment]
http://drdr.racket-lang.org/32354/pkgs/racket-test/tests/racket/stress/fuzz.rkt

**Comment by samth** [comment]
http://drdr.racket-lang.org/32369/pkgs/racket-test/tests/racket/stress/fuzz.rkt

**Comment by mflatt** [comment]
@samth: The `scheme_proper_list_length` function returns -1 for cyclic lists; I'll add a guard

**Comment by samth** [comment]
I'm happy to do that, especially since I'm not yet convinced that's the underlying bug.
