### ISSUE TITLE
Fuzzing crash

### ISSUE THREAD

**Issue by samth** [racket/racket#1108]
http://drdr.racket-lang.org/32286/pkgs/racket-test/tests/racket/stress/fuzz.rkt

What happens is that we get [here](https://github.com/racket/racket/blob/master/racket/src/racket/src/validate.c#L359) and `data->num_params` is very large, causing a call to `scheme_boxmap_get(..., large number here, ...)`, which crashes.

However, I haven't found any places that checked this data previously, or an invariant about what `num_params` is allowed to be, so I'm not sure what dynamic check to add.

**Comment by samth** [comment]
@mflatt any thoughts you have here about how I should continue would be great.

**Comment by mflatt** [comment]
I think that `read_compiled_closure()` in "marshal.c" should check that `num_params` is consistent with the size of the vector used for `closure_map` when the `CLOS_HAS_TYPED_ARGS` flag is present.

**Comment by samth** [comment]
Were you thinking of a test like this?

```
  if ((SCHEME_CLOSURE_DATA_FLAGS(data) & CLOS_HAS_TYPED_ARGS))
    if (data->num_params != (SCHEME_SVEC_LEN(v))) {
      printf("wrong! %d %d \n", data->num_params, SCHEME_SVEC_LEN(v));
      //return NULL;
    }
```

Because that fails repeatedly on existing bytecode (with either side sometimes larger). Or is there some other consistency check I should try?

**Comment by samth** [comment]
Ok, trying to understand `Scheme_Closure_Data` more, that's the wrong invariant. The right invariant is something like:

```
(data->num_params + data->closure_size) * CLOS_TYPE_BITS_PER_ARG == SCHEME_SVEC_LEN(v)
```

But that isn't right either, nor is dividing by `sizeof mzshort`.

**Comment by samth** [comment]
Ok, now I think (from looking a `boxmap_size`) that the correct invariant is:

```
    int needed_bytes = ((CLOS_TYPE_BITS_PER_ARG * (data->closure_size + data->num_params)) + (BITS_PER_MZSHORT - 1)) / BITS_PER_MZSHORT;
    int actual_size = (SCHEME_SVEC_LEN(v));
    if (needed_bytes != actual_size) {
      printf("wrong! %d %d\n", needed_bytes, actual_size);
      //return NULL;
    }
```

However, this is occasionally violated, usually with the vector one bigger than the computed size, but a few times with it much bigger (ie, 2 vs 12 or 9 vs 80).

**Comment by samth** [comment]
Well, at least I have an invariant that fixes the crash and seems to work in general.

**Comment by mflatt** [comment]
That looks right to me.
