### ISSUE TITLE
tests/pkg/test exits with 0 even when there's an error

### ISSUE THREAD

**Issue by samth** [racket/racket#1109]
Example here: https://travis-ci.org/racket/racket/racket/jobs/87703589#L1730-L1776

**Comment by Phlosioneer** [comment]
The URL is malformed. The correct URL is: https://travis-ci.org/racket/racket/jobs/87703589#L1730-L1776

**Comment by jeapostrophe** [comment]
I just pushed something that seems to do it.

**Comment by mflatt** [comment]
Looks like this was fixed by bfc2611ff24293aa1f7442acd4ef087a89ddd2b6
