### ISSUE TITLE
Regression with submodules in drracket (but not in cli racket)

### ISSUE THREAD

**Issue by samth** [racket/racket#1113]
_From @jsmaniac on October 28, 2015 19:11_

I defined a file with two submodules, the second requires and uses some value provided by the first.

```racket
#lang typed/racket

(module ma typed/racket
  (define foo 7)
  (provide foo))
(module mb typed/racket
  (require (submod ".." ma))
  (displayln foo))
```

Running this in command-like racket works fine, but it fails in drracket with this error:

```
link: module mismatch;
 possibly, bytecode file needs re-compile because dependencies changed
  importing module: (submod 'mb mb)
  exporting module: (submod "/tmp/file.rkt" ma)
  exporting phase level: 0
  internal explanation: variable not provided (directly or indirectly) in: foo
```

The bug is not present in version `20151016-6199f9a-racket-test-6.3.0.1-i386-linux-precise.sh`, but is present in `20151028-c868c7b--racket-test-6.3.0.2-i386-linux-precise.sh`. I always tested after removing ~/.racket, and checking there were no `compiled` directory beside the file.

_Copied from original issue: racket/typed-racket#228_

**Comment by samth** [comment]
This doesn't seem to be related to errortrace (turning it off doesn't help), which was my first guess, or to compilation (`raco make` on the file works). It does succeed in compiling in background expansion. I tried using `enter!` on the file, and that worked too.

@rfindler Any suggestions for how to try something smaller than DrRacket that might fail?

**Comment by samth** [comment]
_From @rfindler on October 28, 2015 19:54_

I don't see anything obvious. A smaller program might help.

**Comment by samth** [comment]
_From @jsmaniac on October 28, 2015 20:15_

Interestingly, if I create a file `second.rkt` which requires a `file.rkt` containing the bug above, the bug does not occur in `second.rkt`.

```
#lang typed/racket
(require "file.rkt")
```

**Comment by samth** [comment]
_From @takikawa on October 28, 2015 21:19_

It looks like you can get the same error if you run the macro stepper on that file and step to the end.

**Comment by samth** [comment]
Here's a further reduction:

```
(require macro-debugger/model/trace)

(define-values (a d)
  (parameterize ([current-expand-observe void])
    (expand/compile-time-evals #'(module x typed/racket
                                   
                                   (module ma typed/racket
                                     (define foo 7)
                                     (provide foo))
                                   (module mb typed/racket
                                     (require (submod ".." ma))
                                     (displayln foo))))))
```

**Comment by samth** [comment]
Here's an even smaller version:

```
(eval (expand
       #'(module x typed/racket        
           (module ma typed/racket
             (define foo 7)
             (provide foo))
           (module mb typed/racket
             (require (submod ".." ma))
             (displayln foo)))))
```

This is presumably a macro expander bug for @mflatt. Let me know if I should try to reduce it further.

**Comment by samth** [comment]
Here's a much smaller version, with almost all of TR removed:

```
(eval
 (expand
  #'(module x racket
      (module ma racket
        (#%module-begin
         (define x 1)
         (require (for-syntax typed-racket/typecheck/renamer))
         (define-syntax foo (make-typed-renaming #'lambda #'x))
         (provide foo)))
      (module mb '#%kernel
         (#%require (submod ".." ma))
         foo))))
```

**Comment by samth** [comment]
And here's one that's just core racket:

```
#lang racket/base

(eval
 (expand
  #'(module x racket/base
      (module ma racket/base
        (#%module-begin
         (require (for-syntax racket))
         (define-values (x) 1)
         (define-syntaxes (foo)  (make-rename-transformer (syntax-property #'x 'not-free-identifier=? #t)))
         (provide foo)))
      (module mb '#%kernel
         (#%require (submod ".." ma))
         foo))))
```

**Comment by samth** [comment]
This is the smallest I can do. In particular, changing `racket/private/pre-base` to `'#%kernel` causes the bug to go away.

```
(eval
 (expand
  #'(module x '#%kernel
      (module ma racket/private/pre-base
        (#%module-begin
         (#%require (for-syntax '#%kernel))
         (define-values (x) 1)
         (define-syntaxes (foo)
           (make-rename-transformer
            (syntax-property (quote-syntax x) 'not-free-identifier=? #t)))
         (#%provide foo)))
      (module mb '#%kernel
         (#%require (submod ".." ma))
         foo))))
```

**Comment by mflatt** [comment]
Thanks for narrowing down the problem! I'm still investigating. (I've fixed the broken module path in the error message, but that turns out to be unrelated to the main error.)
