### ISSUE TITLE
`read` doesn't skip BOM

### ISSUE THREAD

**Issue by Blaisorblade** [racket/racket#1114]
Many plain-text editors on Windows, including Notepad, like to prepend [byte order marks](https://en.wikipedia.org/wiki/Byte_order_mark) (BOM) to UTF-8 files when saving them.

Today I learned that `read` will happily skip comments, but will not skip BOMs. That seems hard to justify — arguably, even `read-char` should skip it, while `read-byte` should return the underlying bytes, so this probably should be handled by the [UTF-8 decoder](http://docs.racket-lang.org/reference/encodings.html).

**Comment by Blaisorblade** [comment]
Also:
- that's current with Racket 6.2.1.
- @Toxaris verified this bug also affects creating `.rkt` files — a file created with modern Notepad isn't loaded correctly by DrRacket.
- correct code for working around this bug will keep working after a fix, it will only become unnecessary. BOMs are optional in UTF-8, hence clients already need to handle the lack of BOMs.

**Comment by samdphillips** [comment]
It appears that `read` skips the BOM.  I checked in 7.5, 7.6, 7.7, and 7.8.

```
#lang racket/base

(define BOM-utf8 (bytes #xEF #xBB #xBF))

(define test-data
  (string->bytes/utf-8 "it-works"))

(define test-bytes
  (bytes-append BOM-utf8 test-data))

(read (open-input-bytes test-bytes))
```

**Comment by samdphillips** [comment]
`read-language` errors if there is a BOM before `#lang`

```
#lang racket/base

(define BOM-utf8 (bytes #xEF #xBB #xBF))

(define test-data
  (string->bytes/utf-8 "#lang racket\n"))

(define test-bytes
  (bytes-append BOM-utf8 test-data))

(read-language (open-input-bytes test-bytes))
```

Error:
```
string::3: read-language: expected (after whitespace and comments) `#lang ` or `#!` followed immediately by a language name, found `﻿`
```

**Comment by gus-massa** [comment]
This has bitten me a few times. I have a custom `read` function for this.

**Comment by Blaisorblade** [comment]
Cool that this is (partially) fixed. I don't have testing code anymore; all my "notes" are https://github.com/ps-tuebingen/handin/commit/8662f8100f2c8920048c3b453d2a45a775a05460, so I guess we had 1st-semester students submitting solutions from DrRacket on Windows (using our fork of the `handin` server).

**Comment by gus-massa** [comment]
It is only fixed in my machine, it is only a band aid, not an official real fix.

Thinking about this, perhaps the BOM is more a property of the port than a property of the `read` operation, because it affects all the content of the file. So the correct fix is to add a new option to `open.input-file` instead, something like

    (open-input-file <path> #:mode: 'text/in-case-there-is-a-BOM-eat-it-and-remember-for-future-operations)

**Comment by Blaisorblade** [comment]
> It is only fixed in my machine, it is only a band aid, not an official real fix.

I was referring to @samdphillips's message.

> It appears that `read` skips the BOM. I checked in 7.5, 7.6, 7.7, and 7.8.

**Comment by mflatt** [comment]
I don't think anything has changed. The "it works" example above produces a symbol whose string form is `"\uFEFFit-works"`.

I worry about trying to handle a BOM specially at the beginning of a stream, and file modes like `'text` versus `'binary` have not worked out well for code. What if the reader treated BOM (anywhere) like whitespace?

**Comment by samdphillips** [comment]
> I don't think anything has changed. The "it works" example above produces a symbol whose string form is `"\uFEFFit-works"`.

Oh, I see.  Of course an invisible character wouldn't be "visible" in the symbol.

> What if the reader treated BOM (anywhere) like whitespace?

As I understand it that is a perfectly fine way to deal with it.
