### ISSUE TITLE
`raco pkg install --skip-installed P` errors if P is installed in a wider scope

### ISSUE THREAD

**Issue by samth** [racket/racket#1115]
If you have package P installed in installation scope, and then you do:

```
$ raco pkg install --skip-installed P
```

This will error, even though P is of course installed.

**Comment by samth** [comment]
This was discovered by @sabauma

**Comment by vimniky** [comment]
I have the same problem . thanks @samth

**Comment by mflatt** [comment]
This appears to have been fixed by the merged PR, although there's a related question in a newer issue.
