### ISSUE TITLE
`syntax-local-infer-name` now misses some names

### ISSUE THREAD

**Issue by samth** [racket/racket#1117]
The following program:

```
#lang racket
(module m1 racket/base                                                                                                                  
  (require mzlib/contract)
  (define (f x) x)
  (provide/contract [f (any/c . -> . any/c)]))

(require 'm1)
f
```

previously printed `#<procedure:f>` but now produces a source-location based name. This started happening in 09a2b630bc4020effbc3efabf7d3b78efb8828ee by @gus-massa. 

I think what's going on is that sometimes `simplify-infer-name` doesn't produce a symbol (because it produces a pair, or something else) and so `syntax-local-infer-name` now discards the inferred name, where it didn't before. 

One possibility is to fix clients (such as the contract library) to look at the `'inferred-name` property directly when it's there, but that seems like it ruins the value of `syntax-local-infer-name`.

**Comment by samth** [comment]
This is what causes most of these failures: http://drdr.racket-lang.org/32402/racket/share/pkgs/compatibility-test/tests/mzlib/test.rkt

**Comment by rfindler** [comment]
FWIW, I should be getting those emails too.

Robby

**Comment by mflatt** [comment]
Thanks for tracking down the issue. I have a repair (more generally reverting backward incompatibility) that I'm testing.
