### ISSUE TITLE
Floating point literal parsed incorrectly

### ISSUE THREAD

**Issue by leppie** [racket/racket#1140]
```
> 0e400
0.0
> 0e401
+inf.0
> (system-type)
'unix
> (system-type 'word)
64
> (version)
"6.1" 
```
Tested on 6.2.1 as well. 

Works fine on Windows however, tried both 32/64 bit on 6.2.1.

**Comment by cky** [comment]
I found where the bug is. I'll prepare a pull request for it soon. :-)

**Comment by cky** [comment]
Posted the pull request now: #1145.
