### ISSUE TITLE
make install DESTDIR should not change paths in binaries/config/desktop and any other files

### ISSUE THREAD

**Issue by atorkhov** [racket/racket#1143]
When doing make install with DESTDIR option unixstyle-install.rkt changes paths in binaries, desktop launchers and config files. But it should not do this. Common usage of DESTDIR is package creating.

For example, when creating package it should write files in temporary root dir, but when package is installed all files appear at their locations as specified by configure params. So, make install should not "fix" paths in all files. If user needs to install somewhere else, he should use --prefix configure param, not DESTDIR.

Also see here - https://www.gnu.org/prep/standards/html_node/DESTDIR.html 
```
However, installed files maintain their relative directory structure and any embedded file names will not be modified. 
```

**Comment by mflatt** [comment]
I don't yet understand the issue. The process should be that the first step of `make install DESTDIR=...` puts bytecode, executables, desktop file, etc., into place. But that step of the process will create references to DESTDIR. The step that runs "unixstyle-install.rkt" should fix the references by removing DESTDIR, leaving just the intended prefix in place.
Are you seeing something different?

**Comment by atorkhov** [comment]
Oh, I thought it is adding prefix, not removing.

Yes, I have DESTDIR non-removed in .desktop files.

**Comment by mflatt** [comment]
I see that the ".desktop" file fixup is broken for DESTDIR mode, and I'll push a repair. Thanks!

**Comment by atorkhov** [comment]
In 6.3 there is new problem. I opened bug #1150.
