### ISSUE TITLE
`expt` with negative float base and +inf.0 as exponent produces complex number

### ISSUE THREAD

**Issue by samth** [racket/racket#1148]
```
> (expt -4.0 +inf.)
+nan.0+nan.0i
```

============================

I think the first interaction here is wrong.

```
[samth@huor:~/.../typed-racket/typed-racket-lib/typed-racket (master) plt] r
Welcome to Racket v6.3.0.5.
->  (expt -4.f+0 1797693134862315109393000000000000000000)
+nan.f+nan.fi
->  (expt -4.f+0 179769313486231510939300000000000000000)
+inf.f
-> (fixnum? 179769313486231510939300000000000000000)
#f
-> (fixnum? 1797693134862315109393000000000000000000)
#f
```

Issue discovered by @stamourv's TR random tester.

**Comment by stamourv** [comment]
FWIW, the issue arises with double as well, just with larger bignums:
-> (expt -4.e+0 179769313486231510939300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)
+nan.0+nan.0i

**Comment by stamourv** [comment]
Essentially, if the second argument converts to infinity, then we get complex numbers.

**Comment by stamourv** [comment]
Oh, and that's the same result as `(expt -4.0e0 +inf.0)`, so at least it's consistent. Maybe it even makes sense?

**Comment by samth** [comment]
`(expt -5.0 10000)` is `+inf.0`, so I don't yet see how this makes sense.

**Comment by stamourv** [comment]
`(expt -5.0 10001)` is `-inf.0`. It doesn't converge, so there's no sensible limit for an infinite exponent.

**Comment by samth** [comment]
I agree there's no sensible limit, which I think would be an argument for `nan.0` as the answer, but not a complex number.

Guile does the same thing as Racket for the examples producing infinity, with the correct sign, but produces `+inf.0` for the infinite ones.

**Comment by samth** [comment]
Gambit has identical behavior to Racket, including the complex NaN, which suggests that this is intentional, but I still don't get it.

**Comment by stamourv** [comment]
Right, I believe we based our behavior on Gambit's.

**Comment by samth** [comment]
Maybe @gambiteer can shed light on this then?

**Comment by gambiteer** [comment]
> On Nov 24, 2015, at 5:11 PM, Sam Tobin-Hochstadt <notifications@github.com> wrote:
> 
> Maybe @gambiteer can shed light on this then?
> 

I think about +inf.0 appearing as an argument as a sequence of inexact real numbers -> infinity, which may have nonzero fractional parts.

If you have (expt -4. +inf.0), then for those elements of the sequence -> infinity with nonzero fractional parts, the result of (expt -4. number-with-nonzero-fractional-part) will be complex.

That’s the result that this naive code in lib/_num.scm gives, and I think we were happy with it:


(define (complex-expt x y)
  (##exp (##* (##log x) y)))

For flexpt, Gambit just uses whatever the libc (or whatever) floating-point function gives as a result.

[Bradley-Luciers-MacBook-Pro:~/text/papers] lucier% gsi
Gambit v4.8.0

> (flexpt -4. +inf.0)
+inf.0
> (expt -4. +inf.0)
+nan.0+nan.0i
;;; do the different steps of the computation separately
> (log -4.0)
1.3862943611198906+3.141592653589793i
> (* (log -4.0) +inf.0)
+inf.0+inf.0i
> (exp +inf.0+inf.0i) 
+nan.0+nan.0i


Brad

**Comment by stamourv** [comment]
Ah, yes, if you consider nonzero fractional parts, that behavior makes complete sense. Thanks for the explanation!

It does give rise to confusing behavior when bignums get converted to infinity, since bignums don't have fractional parts, but that's probably not worth special-casing.

**Comment by gambiteer** [comment]
In Gambit we do special-case flonum x bignum:

(cond ((##flnan? x)
x)
((##flnegative? x)
;; we do this because (##exact-int->flonum y) is always
;; even for large enough y
(let ((abs-result
(##flexpt (##fl- x) (##exact-int->flonum y))))
(if (##odd? y)
(##fl- abs-result)
abs-result)))
(else
(##flexpt x (##exact-int->flonum y))))

**Comment by stamourv** [comment]
Looks simple enough. I'll look into fixing Racket to do the same thing. Thanks again!
