### ISSUE TITLE
make install DESTDIR does not remove all references

### ISSUE THREAD

**Issue by atorkhov** [racket/racket#1150]
With full build of version 6.3, there are destdir references in:
.../usr/share/doc/racket/math/matrix_row-alg.html (<span class="RktOut">\- : #(struct:#&lt;syntax:/home/alex/rpmbuild/BUILDROOT/racket-6.3-1.fc21.x86_64/usr/share/racket/pkgs/math-lib/math/
private/array/typed-array-struct.rkt:49:13 Array&gt;</span>)

and in all *.zo files under /usr/share/racket/pkgs.

**Comment by samth** [comment]
The first part of this issue is a typed racket printing bug, but it isn't actually going to cause any problems.

**Comment by samth** [comment]
The bug has been fixed in the most recent snapshots, and the fix will be in the next release.

**Comment by mflatt** [comment]
There were many problems here, but probably the main one was that a test intended to catch this problem wasn't properly updated for packages (and it was still checking only the main "collects" tree).

I think the problems are fixed, but I'll double-check after the next snapshot build.

**Comment by mflatt** [comment]
@samth: I've just fixed a few more problems with tests. I think that leaves us now with just the paths in "Typed_Units.html" and "Typed_Classes.html" to fix.

**Comment by mflatt** [comment]
There are still some relative paths in "Typed_Units.html" that reflect the local structure of `distro-build` (i.e.., a `build` directory with the version number, etc.). But we've purged all of the absolute paths, and I think we're probably not going to manage more without radically changing the representation of module paths.

**Comment by samth** [comment]
Fortunately the last path in Typed_Units.html was just a sign of a bad source location in the error message, so it was easy to fix.
