### ISSUE TITLE
version<? has an internal error on some malformed inputs

### ISSUE THREAD

**Issue by takikawa** [racket/racket#1152]
Example:

````
-> (version<? "1.2" "1.")
; <: contract violation
;   expected: real?
;   given: #f
;   argument position: 2nd
; [,bt for context]
````

when it should raise an error saying the second string is not a version string.

**Comment by rfindler** [comment]
I'll take a look.

**Comment by rfindler** [comment]
`version->list` appears to do something other than crash in the case it gets certain kinds of invalid inputs. I'll change it to error, but that may expose other issues.....
