### ISSUE TITLE
dynamic-place doesn't seem to be able to start a place with its main in a submodule

### ISSUE THREAD

**Issue by tonyg** [racket/racket#1154]
To reproduce:

```racket
#lang racket

(module worker racket
  (provide worker-place-main)
  (define (worker-place-main)
    (printf "Worker starting\n")))

(dynamic-place '(submod "." worker) 'worker-place-main)
```

Expected: A place that prints a message should start

Actual: the place starts (and a place descriptor is returned from dynamic-place), but the new place fails to find the relevant module and main routine, thus crashing.

**Comment by mflatt** [comment]
Right – there's no runtime notion of "the current module" to resolve "." against.

You probably want `(quote-module-path worker)`.

**Comment by tonyg** [comment]
Thank you! This works well:

```racket
#lang racket

(require (only-in syntax/location quote-module-path))

(module worker racket
  (provide worker-place-main)
  (define (worker-place-main self-ch)
    (printf "Worker starting\n")))

(dynamic-place (quote-module-path worker) 'worker-place-main)
(sleep 1)
```
