### ISSUE TITLE
call-with-atomic-output-file fails on names without folders on Linux

### ISSUE THREAD

**Issue by Blaisorblade** [racket/racket#1156]
`(call-with-atomic-output-file "foo" ...)` can fail because the argument has no path component — it's *pathless*, as opposed to "./foo".

Worse, it will always fail on the right kind of system — one where the temp folder (`(find-system-path 'temp-dir)`, here `/var/tmp`) is not on the same filesystem as the file to create, and where renaming from there actually fails.

That's because, unlike documented, with pathless arguments the temporary file is never created in the same directory (but in `(find-system-path 'temp-dir)`) — and I'd recommend to add a test for this, since this test would fail on any system.

```
$ pwd
/home/pgiarrusso/server-admin/Docker/Handin-Server
$ racket
Welcome to Racket v6.2.1.
> (call-with-atomic-output-file "foo" (lambda args 0))
rename-file-or-directory: cannot rename file or directory
  source path: /var/tmp/tmp14491481551449148155116
  dest path: /home/pgiarrusso/server-admin/Docker/Handin-Server/foo
  system error: Invalid cross-device link; errno=18
  context...:
   /usr/share/racket/collects/racket/private/misc.rkt:87:7
> (call-with-atomic-output-file "/home/pgiarrusso/server-admin/Docker/Handin-Server/foo"  (lambda args 0))
0
> (call-with-atomic-output-file "./foo" (lambda args 0))
0
```

My current analysis is as follows.

1. `rename-file-or-directory` is documented to fails across filesystems (though the docs say "across disks", which is not the right concept on Unix *or* modern Windows), and here it does.

2. `call-with-atomic-output-file` calls `make-temporary-file`, which here somehow it decides to create the file in the temporary folder.

`call-with-atomic-output-file` *tries* to avoid it through `(make-temporary-file "tmp~a" #f (path-only path))`; so `make-temporary-file` will use `/var/tmp` iff `(path-only path)` if `#f`. `path-only` docs promise that "If path has no directory part #f is returned". So `call-with-atomic-output-file` won't work correctly on pathless filenames.

**Comment by mflatt** [comment]
Thanks for the report! I will push a repair soon.
