### ISSUE TITLE
Error building on ppc64le

### ISSUE THREAD

**Issue by atorkhov** [racket/racket#1157]
When building racket 6.3 on ppc64le arch, I've got following error:

```
make sysinfercgc
make[4]: Entering directory '/builddir/build/BUILD/racket-6.3/src/racket'
./racketcgc -cqu ./mksystem.rkt system.rktd "gcc -E -I. -I./include -I./src   -DUSE_SENORA_GC    ./src/systype.c" "" "./racketcgc" "./racketcgc"
Makefile:170: recipe for target 'sysinfercgc' failed
make[4]: Leaving directory '/builddir/build/BUILD/racket-6.3/src/racket'
make[4]: *** [sysinfercgc] Segmentation fault (core dumped)
```

**Comment by mflatt** [comment]
I think the problem is that the PPC JIT is not disabled correctly in v6.3 for 64-bit PowerPC. This patch fixes that problem; unfortunately, the patch didn't make it into the v6.3 release:

https://github.com/racket/racket/commit/e957a7d6557f9718ba8493c20675b75a1145084a

**Comment by mflatt** [comment]
Yes, let's close – thanks for checking!
