### ISSUE TITLE
`rename-file-or-directory` gives surprising error message when exists-ok? = #f

### ISSUE THREAD

**Issue by Blaisorblade** [racket/racket#1158]
After #1156, today I was confused by `rename-file-or-directory` error message. I'm not sure this is *wrong*, but I could have used more help.

```
rename-file-or-directory: cannot rename file or directory
  source path: /full-path-to/a
  dest path: /full-path-to/b
  system error: File exists; errno=17
```

When reading this, I thought the underlying `rename` syscall was returning 17 (EEXIST) and started immediately investigating that depth-first, getting more and more confused — that *is* possible under certain circumstances, but in the end I guessed not mine.

I should instead have rechecked the docs and learned exists-ok?, which is by default `#f`. What would have helped, beyond some sleep, would be a message mentioning that exists-ok? was false, something like `"destination existing when exists-ok? #f"`. The above message should then be reserved for when EEXIST is actually returned by the underlying system call.

The offending code is in racket/src/racket/src/file.c:
```
  if (!exists_ok && (scheme_file_exists(dest) || scheme_directory_exists(dest))) {
    exists_ok = -1;
    errno = EEXIST;
    goto failed;
  }
```

**Comment by bennn** [comment]
I've hit this message too, but I thought it was helpful. Seeing `File exists` led me to check my filesystem. When I saw the destination existed on the filesystem, I went back to the docs. 

(Okay, I might've used `(system (format "mv ~a ~a" ...))` in the meantime, but I eventually went back to the docs.)

**Comment by Blaisorblade** [comment]
> Seeing File exists led me to check my filesystem. When I saw the destination existed on the filesystem, I went back to the docs.

Well, it's always hard to decide whether a message is confusing or whether it was just me being confused.

But I believe "system error" and "errno=17" are hardly appropriate — unless you claim that "rename-file-or-directory" is part of the "system" — the operating system?

Anyway, I'm sure Racket developers have more pressing needs, so I should probably propose a fix.
