### ISSUE TITLE
`place` fails in submodule

### ISSUE THREAD

**Issue by samth** [racket/racket#1173]
This program fails when run from the command line:

```
#lang racket
(module main racket
  (place ch 1))
```

Error message: 

```
place: contract violation
  expected: (or/c module-path? path?)
  given: '(submod (#<path:/home/samth/tmp/p.rkt> main) place-body-1)
  context...:
   /home/samth/sw/plt/racket/collects/racket/place.rkt:109:0: start-place
   (submod /home/samth/tmp/p.rkt main): [running body]
```

I think the `place` implementation is missing a use of `(file ...)`.

**Comment by takikawa** [comment]
I think this is the same issue as this old bug tracker PR: http://bugs.racket-lang.org/query/?cmd=view audit-trail&database=default&pr=12934
