### ISSUE TITLE
Symlink to racket script breaks local requires

### ISSUE THREAD

**Issue by spelufo** [racket/racket#1179]
Say I have a script `hello.rkt`:

```racket
#!/usr/bin/env racket
#lang racket/base
(require "libhello.rkt")
(hello)
```
and `libhello.rkt`:
```racket
#lang racket/base
(provide hello)
(define (hello) (println "Hello"))
```

both in a directory `~/src/hello/`.

Now I want to add the `hello` script to my path with `ln -s ~/src/hello/hello.rkt /bin/hello`.

Trying to run the script will attempt to find `libhello.rkt` in `/bin/` instead of `~/src/hello/`, and produce an error `cannot open module file`. Is this intended?

Is there a standard way for packages to provide command line tools other than under `raco`?

**Comment by mflatt** [comment]
A package can provide executables via `racket-launcher-names` plus `racket-launcker-libraries`. For a package installed in user scope, the executable is written to `(build-path (find-system-path 'addon-dir) (version) "bin")`. It can be symlinked.

**Comment by spelufo** [comment]
What about the example above without installing or linking anything, with just those files, should that work?

**Comment by mflatt** [comment]
You could use `raco exe -l` to create a launcher script of the same sort created by `racket-launcher-libraries` (but without installing anything). Is that what you mean?

**Comment by spelufo** [comment]
Thanks, that works.  I was used to symlinks because that is the way nodejs does it, but apparently symlinking can break imports in other languages as well.
