### ISSUE TITLE
Installing the drracket package does not produce a launcher for DrRacket

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#1180]
Given a minimal distribution, running `raco pkg install --auto drracket` does not produce a `bin/drracket` executable, nor does it produce a `DrRacket.app` application bundle on OS X. This behavior is present in 6.3 and the latest snapshot, and I’m not sure if it occurs in other versions, too.

This is a problem for people trying to install DrRacket on a minimal distribution, which is what the Homebrew installation of Racket advises people to do. Note that DrRacket *is* installed: running `racket -l drracket/drracket` launches it fine. It just doesn’t seem to generate any of the launchers.

I’m not sure if this happens with all packages that produce launchers or if it’s just an issue with DrRacket.

**Comment by juanfra684** [comment]
Run this command `racket -e '(require setup/dirs) (displayln (path->string (find-user-gui-bin-dir))) (for-each displayln (directory-list (find-user-gui-bin-dir)))'`. It will show where is the launcher.

**Comment by doppioslash** [comment]
@juanfra684 this is what happens when I do that on Mac 10.10.5, Racket 6.3 from latest `brew`, and `raco pkg install --auto drracket`:

```
$ racket -e '(require setup/dirs) (displayln (path->string (find-user-gui-bin-dir))) (for-each displayln (directory-list (find-user-gui-bin-dir)))'
/Users/doppioslash/Library/Racket/6.3/
directory-list: could not open directory
  path: /Users/doppioslash/Library/Racket/6.3/
  system error: No such file or directory; errno=2
  context...:
   /usr/local/Cellar/racket/6.3/share/racket/collects/racket/private/kw-file.rkt:137:4: directory-list
```

**Comment by juanfra684** [comment]
@doppioslash try this: `racket -e '(require setup/dirs) (displayln (path->string (find-gui-bin-dir))) (for-each displayln (directory-list (find-gui-bin-dir)))'`.

**Comment by doppioslash** [comment]
tried, it lists everything in my `/usr/local/bin/` but there is no Racket IDE in there.

**Comment by mflatt** [comment]
The problem is that the OS X build can't handle the combination of `configure` arguments used for the Homebrew formula. Some flags force a "unix-style" layout, while parts of the Racket build for OS X currently rely on an "in-place" layout.

I have a repair, I think, but I'm still testing it.
