### ISSUE TITLE
GTK error in DrRacket on armv7l

### ISSUE THREAD

**Issue by joshuata** [racket/racket#1186]
I build racket from source on a Raspberry Pi B v2. The build succeeded and the racket repl runs perfectly, but attempting to launch DrRacket throws the following error:
```
Gtk: gtk_style_context_get_property: assertion 'priv->widget != NULL || priv->widget_path != NULL' failed
SIGSERV MAPPER si_code 1 fault on addr 0x18
Aborted
```
I am running raspbian kernel 3.18.11-v7+, with the racket-6.3-src-builtpkgs.tgz source

**Comment by mflatt** [comment]
Does setting the `PLT_GTK2` environment variable allow DrRacket to start?

**Comment by joshuata** [comment]
I will check as soon as I have a minute, hopefully tomorrow (Jan 2)

**Comment by mflatt** [comment]
I finally got a chance to try on a Raspbian installation. I get the same error without setting `PLT_GTK2`, but setting `PLT_GTK2` lets DrRacket start.
I'll work on fixing the Gtk3 binding – hopefully soon.

**Comment by mflatt** [comment]
I've pushed a repair for this bug: racket/gui@55d0d96dbe073906ca3c77e0d127eba2cd1778d5
If you're interested in patching your build and it's not obvious how to do that, I can provide more information. Or you could try a snapshot build (to be dated 20160113 or later) from http://www.cs.utah.edu/plt/snapshots/
Thanks for the report!

**Comment by joshuata** [comment]
Thank you very much!
