### ISSUE TITLE
High Performance Graphics On Mac OS X 10.11

### ISSUE THREAD

**Issue by sfpqi** [racket/racket#1193]
The previous version 6.2.1 of Dr. Racket did not require the use of dedicated AMD graphics on my Early 2011 15-inch MacBook Pro. The new 6.3 release forced the use of that graphics card instead of integrated Intel HD 3000 and drains battery a lot quicker than before.

**Comment by mflatt** [comment]
Version 6.3 includes a regression specific to El Capitan, and that problem has been fixed for the next release.
Does a snapshot build from http://pre.racket-lang.org behave better on your machine than v6.3?

**Comment by sfpqi** [comment]
Not really, I kinda remembered seeing a plist edit associated to the graphics card use on mac, I cannot remember which one and it probably was broken in the release.

**Comment by sfpqi** [comment]
I found this https://developer.apple.com/library/mac/qa/qa1734/_index.html. It might be the Open-GL part that has been broken.

**Comment by mflatt** [comment]
I see – thanks. DrRacket uses OpenGL for the GC icon on El Capitan (which is a change from previous versions), so that's probably why this now matters. I'll investigate more.

**Comment by mflatt** [comment]
I've added the plist entry. Does that make the latest snapshot build (from https://pre.racket-lang.org ) behave better?

**Comment by sfpqi** [comment]
It still requires the graphics card, build 6.4.0.1.

**Comment by lexi-lambda** [comment]
It looks like you need to add `NSOpenGLPFAAllowOfflineRenderers` to the list of `NSOpenGLPixelFormatAttribute`s, as documented here: https://developer.apple.com/library/mac/technotes/tn2229/_index.html

**Comment by mflatt** [comment]
@lexi-lambda: thanks!
That change is in the latest snapshot build.
@sfpqi Any better?

**Comment by lexi-lambda** [comment]
For me, at least, that seems to have worked—DrRacket is no longer requiring the high-perf graphics card. Thanks a lot!

**Comment by sfpqi** [comment]
It WORKED! Thank you!
