### ISSUE TITLE
Unnecesary #%check in define-values

### ISSUE THREAD

**Issue by gus-massa** [racket/racket#1200]
After decompiling, this code:

```
#lang racket/base

(define-values (x y) (quotient/reminder (random 10) 2))
(list x y)
```

It expands to something equivalent to:

```
(module x ...
   (require racket/base)

  (define-values (x y) (quotient/reminder (random 10) 2))
  (print-values (list (#%checked x) y)))))
```

I think that the `#%cheked` in `x` is unnecessary.

(With more variables, all but the last variable are checked.)

**Comment by Paul-C-Anagnostopoulos** [comment]
As far as I can see, `#%checked is only used once in the code, in decompile.rkt. Do we want to eliminate it?

**Comment by sorawee** [comment]
@gus-massa how did you obtain the expanded code? The expanded code also doesn't look _fully_ expanded, because it misses `#%app` in several places.

In any case, currently, `raco expand` shows:

```
(module test racket/base
  (#%module-begin
   (module configure-runtime '#%kernel
     (#%module-begin (#%require racket/runtime-config) (#%app configure '#f)))
   (define-values (x y) (#%app quotient/remainder (#%app random '10) '2))
   (#%app call-with-values (lambda () (#%app list x y)) print-values)))
```

which has no `#%checked`. Perhaps this was improved in the new expander?

**Comment by shhyou** [comment]
Through `raco decompile` with Racket BC, I guess.

**Comment by sorawee** [comment]
Ah, I see. Thanks! 

Here's the result from `raco decompile`:

```
(module test ....
  (require (lib "racket/base.rkt"))
  (provide)
  (define-values (x y) (quotient/remainder (random '10) '2))
  (#%apply-values print-values (list x y))
  (void)
  (module (test configure-runtime) ....
    (require '#%kernel (lib "racket/runtime-config.rkt"))
    (provide)
    (print-as-expression '#t)
    (void)))
```

There's no `#%checked` either.

**Comment by gus-massa** [comment]
Looking at the date of the initial post, it was probably with version 6.3BC. I installed the old version an with `raco make` and `raco decompile` I get

    (begin
      (quote inspector insp0)
      (module old ....
        (quote self {#%modidx #f #f})
        (quote internal-context #t)
        (quote bindings #0=#hasheq())
        (quote language-info #f)
        (require (lib "racket/base.rkt"))
        (provide)
        (quote inspector insp0)
        (module configure-runtime ....
          (quote self {#%modidx #f #f})
          (quote internal-context #t)
          (quote bindings #0#)
          (quote language-info #f)
          (require '#%kernel (lib "racket/runtime-config.rkt"))
          (provide)
          (quote inspector insp0)
          (print-as-expression '#t))
        (define-values (_x _y) (quotient/remainder (random '10) '2))
        (#%apply-values
         |_print-values:p@(lib "racket/private/modbeg.rkt")|
         (list (#%checked _x) _y))))

With a new version 7.9BC I don't see the `#%checked` so someone must have fixed that. So I'm closing this issue.
