### ISSUE TITLE
Caching in raco pkg install can cause (= #<eof> 31) ?

### ISSUE THREAD

**Issue by AlexKnauth** [racket/racket#1204]
I was trying to install some packages with raco pkg install, but it failed, so I tried again with one of the dependencies to see if that worked. When I did, I got this weird error. The error goes away when I use `--no-cache`.

It looks like the error is coming from this line here: https://github.com/racket/racket/blob/master/racket/collects/file/untgz.rkt#L33
```racket
       (cond
        [(and (= (peek-byte in 0) #o037) ; #o037 is 31 written in octal
              (= (peek-byte in 1) #o213))
```

Here is the error:
```
=: contract violation
  expected: number?
  given: #<eof>
  argument position: 1st
  other arguments...:
   31
  context...:
   /home/alexknauth/racket/2016-01-11/racket-6.4.0.1/collects/file/untgz.rkt:30:3
   /home/alexknauth/racket/2016-01-11/racket-6.4.0.1/collects/racket/contract/private/arrow-val-first.rkt:335:3
   /home/alexknauth/racket/2016-01-11/racket-6.4.0.1/collects/pkg/private/download.rkt:93:0: download-repo!24
   /home/alexknauth/racket/2016-01-11/racket-6.4.0.1/collects/pkg/private/stage.rkt:299:11
   /home/alexknauth/racket/2016-01-11/racket-6.4.0.1/collects/pkg/private/stage.rkt:106:0: stage-package/info46
   /home/alexknauth/racket/2016-01-11/racket-6.4.0.1/collects/pkg/private/stage.rkt:106:0: stage-package/info46
   /home/alexknauth/racket/2016-01-11/racket-6.4.0.1/collects/pkg/private/install.rkt:641:4: for-loop
   /home/alexknauth/racket/2016-01-11/racket-6.4.0.1/collects/pkg/private/install.rkt:141:0: install-packages74
   /home/alexknauth/racket/2016-01-11/racket-6.4.0.1/collects/pkg/private/../../racket/private/more-scheme.rkt:261:28
   /home/alexknauth/racket/2016-01-11/racket-6.4.0.1/collects/racket/contract/private/arrow-val-first.rkt:335:3
   /home/alexknauth/racket/2016-01-11/racket-6.4.0.1/collects/racket/file.rkt:378:8
   /home/alexknauth/racket/2016-01-11/racket-6.4.0.1/collects/racket/file.rkt:367:0: call-with-file-lock42
   /home/alexknauth/racket/2016-01-11/racket-6.4.0.1/collects/pkg/main.rkt:201:16
   (submod /home/alexknauth/racket/2016-01-11/racket-6.4.0.1/collects/pkg/main.rkt main): [running body]
```

**Comment by mflatt** [comment]
Do you know which cache file (and its corresponding URL) was creating trouble? If so, can you save a copy of that file?

**Comment by AlexKnauth** [comment]
The first one that gave me the error was `pict3d-die-cut`, `reprovide-lang`, and `jack-scribble-example`, all did this. Here's what it looked like for `pict3d-die-cut`:
```
bash-4.3$ raco pkg install pict3d-die-cut
Resolving "pict3d-die-cut" via http://plt.eecs.northwestern.edu/snapshots/20160111-417d9b0/catalog/
Resolving "pict3d-die-cut" via https://pkgs.racket-lang.org
Using cached14526289971452628997805 for git://github.com/mflatt/pict3d-die-cut
=: contract violation
  expected: number?
  given: #<eof>
  argument position: 1st
  other arguments...:
   31
  context...:
```
Are you talking about `cached14526289971452628997805` ?

**Comment by mflatt** [comment]
Yes. Can you put a copy of that file somewhere where I can look at it?

**Comment by AlexKnauth** [comment]
Where are those cache files?

**Comment by mflatt** [comment]
You can get the path from `raco pkg config download-cache-dir`

**Comment by AlexKnauth** [comment]
Ok I found it, and it was completely empty, with zero bytes.

**Comment by mflatt** [comment]
Do you have other zero-byte cache files, or is it just that one?

**Comment by AlexKnauth** [comment]
About half of them are empty. There are 15 non-empty ones, and 16 empty ones.

**Comment by mflatt** [comment]
If you try installing something from some new Github repo, you should get a new cache file. Is it created ok, or does it also end up as 0 bytes?

**Comment by AlexKnauth** [comment]
I tried two more, and they both ended up as 0 bytes. The `raco pkg install` command also showed this error:
```
bash-4.3$ raco pkg install git://github.com/AlexKnauth/seq-no-order
error reading collection links file #<path:/home/alexknauth/.racket/snapshot/links.rktd>: ill-formed content
Querying Git references for seq-no-order at git://github.com/AlexKnauth/seq-no-order
Downloading repository git://github.com/AlexKnauth/seq-no-order
pkg: failure getting info
  error: "get-info: info file does not contain a module of the right shape in /home/alexknauth/.racket/snapshot/pkgs/seq-no-order/info.rkt"
links: error reading from link file: #<path:/home/alexknauth/.racket/snapshot/links.rktd>: links: content is not a list: #<eof>
  context...:
   /home/alexknauth/racket/2016-01-11/racket-6.4.0.1/collects/racket/private/more-scheme.rkt:163:2: select-handler/no-breaks
   /home/alexknauth/racket/2016-01-11/racket-6.4.0.1/collects/setup/link.rkt:9:0: links25
   /home/alexknauth/racket/2016-01-11/racket-6.4.0.1/collects/pkg/private/install.rkt:592:8
   /home/alexknauth/racket/2016-01-11/racket-6.4.0.1/collects/pkg/private/install.rkt:141:0: install-packages74
   /home/alexknauth/racket/2016-01-11/racket-6.4.0.1/collects/pkg/private/../../racket/private/more-scheme.rkt:261:28
   /home/alexknauth/racket/2016-01-11/racket-6.4.0.1/collects/racket/contract/private/arrow-val-first.rkt:335:3
   (submod /home/alexknauth/racket/2016-01-11/racket-6.4.0.1/collects/pkg/main.rkt main): [running body]
```

**Comment by AlexKnauth** [comment]
Also, `.racket/snapshot/links.rktd` is zero bytes, and so is `.racket/snapshot/pkgs/seq-no-order/info.rkt`.

**Comment by mflatt** [comment]
Hm... It's not that your filesystem is full or otherwise unwilling to write file content in "~/.racket"? File-writing failures should turn into exceptions, of course, but maybe a failure is being masked somehow.

**Comment by AlexKnauth** [comment]
No, because other things in that directory work fine. For example when I tried installing `exact-decimal-lang`, it worked fine, and now that's in `.racket/snapshot/pkgs/exact-decimal-lang` with the correct files.

**Comment by AlexKnauth** [comment]
Hm, now I'm getting that `error reading collection links file` when running `raco setup` as well, where before `raco setup` worked. So that got messed up while I was trying to install those pkgs to look at the cache files.

**Comment by mflatt** [comment]
@AlexKnauth Have you seen anything like this again? If not, I'm inclined to chalk it up to mysterious filesystem failure and close the issue.

**Comment by AlexKnauth** [comment]
No, but this issue was on one of the Northeastern computers, and I haven't tried on one of them since.

**Comment by AlexKnauth** [comment]
It would probably be good to at least fail with a better error message though, right?

**Comment by mflatt** [comment]
That's a fair point. I'll make untgz and gunzip report unexpected end-of-file errors.
