### ISSUE TITLE
Make srfi-19 easily found in the documentation

### ISSUE THREAD

**Issue by linusbergl** [racket/racket#1212]
Hi there!

I have spent some time looking through the documentation trying to find a "configurable" date->string procedure. I was surprised to not find it in the racket time library since it is not something you want to write yourself, and racket in many ways is "ammunition included". 

Now, I knew that I could just use srfi-19, but that is not clear in the documentation which might be confusing to racket beginners. 

My suggestion would be to somehow clarify that there is such a procedure included in the racket distribution, or even make the SRFI-19 one part of racket/date.

Best regards
Linus

**Comment by takikawa** [comment]
You may want to look at the [gregor](https://github.com/97jaz/gregor) package instead of srfi/19 BTW. The srfi/19 library is not very Rackety.

**Comment by linusbergl** [comment]
Well. There is one procedure to convert date structs to strings with control of how the output should look included. Depending on a third party library should not be necessary.

I just think it might be a good idea to make the date->string from srfi-19 a bit more discoverable, or at least provide something as powerful in the standard Racket/date.

**Comment by rfindler** [comment]
I think the future is the gregor library too and so we try to make it more discoverable, perhaps by pointing people to it from racket/date or other things like that.

**Comment by linusbergl** [comment]
Well... I don't doubt you, but currently there is no working documentation for gregor online (403, permission denied) and installing it through raco also does not give a working documentation. 

And isn't it a bit overkill to demand that you install a completely new library (with no less than 7 other deps) to be able to date->string any non-standard string representation of a date? The syntax of gregor for that specific function isn't particularly more clear (from what I gather reading the tests on github) than srfi19 date->string.

Installing an extra 7 packages for just one procedure that is already included seems a bit off to me. I'm just a hobby dev, so what do I know.

**Comment by jackfirth** [comment]
@linusbergl srfi/19 is itself a third party dependency as well, it just happens to have been written before Racket's new package system was created and thus was included with the full distribution by default. So it "already being included" is much more an accident of history than a conscious design decision.
