### ISSUE TITLE
The version of DrRacket in Ubuntu 14.04 LTS repositories is ancient

### ISSUE THREAD

**Issue by magicgoose** [racket/racket#1221]
The version of DrRacket in Ubuntu 14.04 LTS repositories is ancient.
(I don't recall exactly, I looked at it yesterday on my friend's machine and it was `5.x`)

Does DrRacket have its own Debian/Ubuntu repository? Or is it possible to make the official repo update faster?

**Comment by takikawa** [comment]
Your best bet is to use the PPA that is managed by us: https://launchpad.net/~plt/+archive/ubuntu/racket

None of the Racket devs are involved in managing the package in Ubuntu's official repo, so you'd have to ask the Ubuntu folks about that.
