### ISSUE TITLE
Installer ignores $PATH, can't install on nixos

### ISSUE THREAD

**Issue by jsmaniac** [racket/racket#1223]
The installer (from `https://mirror.racket-lang.org/installers/6.3/racket-6.3-x86_64-linux-debian-squeeze.sh`), line 105, contains:

    PATH=/usr/bin:/bin

It therefore does not look for the utilities `rm`, `ls`, `ln` etc. in the user's `$PATH`. 

The [NixOs distribution](https://nixos.org/) doesn't have the binutils in `/bin` or `/usr/bin`, but instead in `/run/current-system/sw/bin` (which is listed in the `$PATH`), and therefore racket fails to install with the error message `Error: could not find "rm".`.

Is there any reason for ignoring the user's `$PATH`?

**Comment by elibarzilay** [comment]
The original intention behind that is to make the installer robust
against all kinds of possible junk that might be on your path, and
therefore make its behavior more predictable.  This is especially
important for utilities like `tar` that have several slightly different
variants that can be installed on a single system.  So the installer
assumes the standard FHS directories `/usr/bin` and `/bin` exist and
have what it needs.

A quick search got me to [this
page](https://nixos.org/wiki/FHS_environments) which might be what you
need to do, or if there some other way to know what are the standard
directories to find the utilities it needs then maybe that can be used.

**Comment by jsmaniac** [comment]
That solution (FHS environments) seems to be for making a package, and seems rather cumbersome to use when you just want to run `./installer.sh`.

The `$PATH` issue doesn't arise when compiling from source. I'm in the process of fixing a problem with the official package, and adding a package for the nightlies, so that means installing from the racket-*.sh will be less needed.

Still, it seems a bit of a drastic measure, it would be nice if it could be disabled. If you're okay with that, I can submit a PR to add a `--no-reset-path` option to the installer.

**Comment by elibarzilay** [comment]
Well, TBH, I'm not maintaining that code anymore -- I just explained where that decision came from.  Also, it was pretty common for such sh-based home-cooked installers to set their own PATH, so their behavior is more predictable.

Adding a `--no-reset-path` thing sounds to me like it would be very inconvenient.  One option is to extend the path instead of setting it, as in

    PATH=/usr/bin:/bin:$PATH

which might be OK since it will pick the stable utilities if they're there or whatever you have on your `$PATH` if not.  A possibly more involved tweak would be to look for the utilities in these places in advance, and if one is not found, ask the user where they are, with a default value that comes from the pre-existing PATH (but this sounds like an overkill, so maybe the simpler thing above is better).

**Comment by jsmaniac** [comment]
@elibarzilay Maybe then we could use `/usr/bin:/bin:$PATH` but print a warning if the utility wasn't found in `/usr/bin` or `/bin` ?

**Comment by elibarzilay** [comment]
Yeah, that would be roughly equivalent from a UI point of view.  Below is a patch for the actual installer script --- it does two things: (1) save the original PATH in `origPATH`, (2) add another loop that looks through that if the previous search failed and warns if an executable is found there.  This handles all of the utilities that are found via `lookfor`, which still means that random things that people might add to this script is "safe" (but ultimately should go through the same).  This patch should be translated to the Racket code that generates this script though.

    --- 1	2016-01-25 11:13:18.474793948 -0500
    +++ 2	2016-01-25 11:12:59.375962051 -0500
    @@ -102,6 +102,7 @@
     ###############################################################################
     ## Utilities
     
    +origPATH="$PATH"
     PATH=/usr/bin:/bin
     
     if test "x`echo -n`" = "x-n"; then
    @@ -137,6 +138,14 @@
           eval "$1=$dir/$1"
           IFS="$saved_IFS"
           return
    +    fi
    +  done
    +  for dir in $origPATH; do
    +    if test -x "$dir/$1"; then
    +      echo "Warning: $1 found in a non-standrad place: $dir/$1"
    +      eval "$1=$dir/$1"
    +      IFS="$saved_IFS"
    +      return
         fi
       done
       IFS="$saved_IFS"

**Comment by jsmaniac** [comment]
@elibarzilay Thanks a lot, I updated [the racket file in the distro-build repo](https://github.com/racket/distro-build/blob/master/distro-build-client/unix-installer/installer-header) and will submit a PR in a few minutes. I'll also move the issue there.

I thought the issue belonged to this repo because the file `racket/collects/launcher/launcher.rkt` also contains `PATH=\"/usr/bin:/bin\"`. I guess that's probably one of the reasons why [executables created by raco exe don't work with nix-os](https://github.com/NixOS/nixpkgs/issues/11698), I'll cross-post that there.

**Comment by jsmaniac** [comment]
This issue was moved to racket/distro-build#1
