### ISSUE TITLE
Printing a string in `call-as-atomic`

### ISSUE THREAD

**Issue by LeifAndersen** [racket/racket#1228]
I am not sure if this is an error or not. But the documentation says to be careful about printing unknown values to atomic mode. However, it seems like DrRacket segfaults even when printing out things that are known to be strings in atomic mode.

For example, the following program seems to cause DrRacket to crash pretty regularly:

```
#lang racket

(require ffi/unsafe/atomic)

(call-as-atomic
  (lambda ()
    (displayln "Hello World!")))
```

**Comment by mflatt** [comment]
That's expected, and I'll try again at improving the docs. (I'm not sure why I ended up with such a weak warning the last time I tried.)
