### ISSUE TITLE
non-terminating regexp-match

### ISSUE THREAD

**Issue by luminousfennell** [racket/racket#1230]
Hi,
When trying to `regexp-match` the expression
`  #px"(?:[[:alnum:]_.]+|[[:alnum:]_.]+, )* [{] $"`
and the string
`"java.io.Serializable, CharSequence /*,  Comparable*/ { "`
racket does not seem to terminate.

I tested this with 6.3 on 64bit linux (Nixos and Xubuntu).

I have attached a racket and a perl script to illustrate the issue. Both should print `"No match"` twice. The perl script does this but the racket program only prints the first line.
[racket-rx-loop-bug.zip](https://github.com/racket/racket/files/112597/racket-rx-loop-bug.zip)

**Comment by samth** [comment]
I think this is actually exponential runtime, and not an infinite loop. If you change it to `java.lang.S` and then slowly add back the characters in `Serializable`, you'll see increaisng run times.

**Comment by luminousfennell** [comment]
I see. Then it is probably an instance of the worst case behavior for
backtracking regexp algorithms that is described on the Wikipedia page
on regexp matching (https://en.wikipedia.org/wiki/Regular_expression#Implementations_and_running_times). 

Perl seems to be able to cope with the given case, but python has the same problem (cf attachments.. also the previous perl version was bogus). It seems like I just have to be more careful when writing regexes. I'm closing the issue.
[racket-rx-loop-bug.zip](https://github.com/racket/racket/files/114258/racket-rx-loop-bug.zip)
