### ISSUE TITLE
Strange error message/behavior when prop:rename-transformer gets a bad value

### ISSUE THREAD

**Issue by samth** [racket/racket#1236]
This program:

```
#lang racket
(begin-for-syntax
  (struct definition (renamer) 
    #:property prop:rename-transformer (struct-field-index renamer)))
(define-syntax add-two (definition #f))

(define x (add-two 3))
```

Produces a very strange error message:

```
[samth@huor:~/sw plt] r /tmp/x.rkt
/tmp/x.rkt:6:11: add-two: unbound identifier in module
  context...:
   #(2095 module) #(2096 module x 0)
  matching binding...:
   #f
   #(2095 module) #(2096 module x 0)
   free-identifier=? to ?
  in: add-two
  context...:
   standard-module-name-resolver
```

If we change the last line to `(add-two 3)`, the error message is:

```
/tmp/x.rkt:7:1: ?: unbound identifier;
 also, no #%top syntax transformer is bound
  in: ?
  context...:
   standard-module-name-resolver
```

which is also very odd.

(This is with 6.4.0.7)

**Comment by samth** [comment]
Originally discovered with @david-christiansen.

**Comment by samth** [comment]
This behavior appears to date from the introduction of `prop:rename-transformer`, in this commit: https://github.com/racket/racket/commit/2109cec2f4d89f820647ae75e81b0d7b6a70f4a1#diff-23bb48bf312b57d2acf00f748a5bfd50R1290 and to be intentional at the time. I suppose there's a sense in which erroring on that line instead of doing what it currently does would be backwards incompatible, but it's hard for me to imagine a real program that would break.

**Comment by takikawa** [comment]
This behavior is actually documented (though I also thought it was a strange behavior when I first read these docs):

> [Reference](http://docs.racket-lang.org/reference/stxtrans.html#%28def._%28%28quote._~23~25kernel%29._prop~3arename-transformer%29%29)
> If the property value is an identifier, the identifier serves as the target for renaming, just like the first argument to make-rename-transformer. If the property value is an integer, the target identifier is extracted from the structure instance; if the field value is not an identifier, then an identifier ? with an empty context is used, instead.
