### ISSUE TITLE
Infinite loop in the contract library with `define-opt/c`

### ISSUE THREAD

**Issue by samth** [racket/racket#1238]
This program is an infinite loop on Racket HEAD (it allocates, so don't run it too long). It works correctly on 6.4.

```
#lang racket/base

(require racket/contract)

(define-opt/c (heap-ordered/desc/scon)
  (or/c #f
        (cons/c any/c
                (heap-ordered/desc/scon))))

(define-opt/c (binomial-trees/asc/scon)
  (or/c #f
        (cons/c any/c
                (binomial-trees/asc/scon)))) ;; this contract is wrong

(define binomial-heap/scon (time (binomial-trees/asc/scon)))
```

**Comment by samth** [comment]
Bug found by @sabauma, and taken from the OOPSLA '12 chaperone benchmarks.

**Comment by rfindler** [comment]
Looking at this, the last two lines look to me like:

```
(define-opt/c (f) (begin <do-some-stuff> (f))
(f)
```

Why should this terminate?

**Comment by rfindler** [comment]
(I agree it terminates in 6.3 (and I believe you about 6.4), but that seems like the bug?)

**Comment by samth** [comment]
On the backwards-compatibility front, the chaperone benchmarks from our OOPSLA paper no longer run correctly. 

Here's a direct copy-and-paste from the code accompanying that paper (the "binomial-heap-contract.rkt" file). It has the same infinite loop (and the comment about the contract being wrong is in the original).

```racket
#lang racket

(define-struct h:kons (hd tl) #:transparent)
(define-struct h:node (rank val obj children) #:transparent)

(define-opt/c (binomial-tree-rank=/scon r v)
  (or/c #f
        (struct/dc h:node
                   [rank (=/c r)]
                   [val (>=/c v)]
                   [children (rank val) #:lazy (heap-ordered/desc/scon (- rank 1) val)])))
(define-opt/c (binomial-tree-rank>/scon r)
  (or/c #f
        (struct/dc h:node
                   [rank (>=/c r)]
                   [val any/c]
                   [children (rank val) #:lazy (heap-ordered/desc/scon (- rank 1) val)])))
(define-opt/c (heap-ordered/desc/scon rank val)
  (or/c #f
        (cons/c (binomial-tree-rank=/scon rank val)
                (heap-ordered/desc/scon (- rank 1) val))))
(define-opt/c (binomial-trees/asc/scon rank)
  (or/c #f
        (cons/c (binomial-tree-rank>/scon rank)
                (binomial-trees/asc/scon -inf.0)))) ;; this contract is wrong

(define binomial-heap/scon (binomial-trees/asc/scon -inf.0))
```

**Comment by samth** [comment]
I guess the question is whether we screwed this up in the paper, or if there's now a bug.

**Comment by samth** [comment]
Note that we didn't actually include the numbers from this variant in the results we presented.

**Comment by rfindler** [comment]
Which paper are you talking about?

**Comment by samth** [comment]
The OOPSLA 2012 paper on chaperones. The file I mention is in the zip file you can download here: https://www.cs.umd.edu/~sstrickl/chaperones/index.html

**Comment by rfindler** [comment]
Ah. I think it is safe to say that I agree with that comment. Here's a shorter program that behaves differently in 6.3 and git head:

```
#lang racket/base
(require racket/contract)
(define-opt/c (binomial-trees/asc/scon)
  (cons/c any/c (binomial-trees/asc/scon)))
(void (binomial-trees/asc/scon))
```

I'll keep poking around to get more clarity.

**Comment by rfindler** [comment]
It appears that the change was because `opt/c` believes it cannot tell that something is going to be a chaperone contract, so it generates some code to check and that code triggers the infinite loop in the program.

This program is still incorrect (in that it doesn't loop):

```
#lang racket/base
(require racket/contract)
(define-opt/c (binomial-trees/asc/scon)
  (binomial-trees/asc/scon))
(void (binomial-trees/asc/scon))
```

and `opt/c` seems to have decided that it knows that it is a chaperone contract.

**Comment by rfindler** [comment]
I have thought about this some more and I am not seeing how to implement `define-opt/c` in a way that correctly handles programs that loop like this (in the sense that `define-opt/c` behaves like `define`, except it improves performance for functions that return contracts). I could just be missing something, but for now I'm inclined to say that this code is buggy and we now have a better response to it and to update the documentation for `define-opt/c`.

Does that seem ok?

**Comment by samth** [comment]
Are you proposing to change my examples to not loop, your latest example to loop, or leaving everything as is? 

What do you think we should do about the code for the paper? Ask @sstrickl to update that zip file to take out the now-infinite loop?

**Comment by rfindler** [comment]
I am proposing to change the implementation not at all (at least until I figure out a way to change it) but to document this flaw in the current implementation.

As for the code in the paper, I could try looking into providing a revised version of it that actually checks that contract correctly. Would you like me to do that?

**Comment by samth** [comment]
Since that code isn't really relevant to the paper, just taking it out seems like the right choice. Do we still have that paper etc in version control somewhere?

**Comment by rfindler** [comment]
I can't recall!

**Comment by rfindler** [comment]
Well, let me know if you find the code and I'll try to take a look at making a version that works properly.

**Comment by samth** [comment]
The code is all in the zip file here: https://www.cs.umd.edu/~sstrickl/chaperones/index.html

I'll let you know if I find the version control.

**Comment by sstrickl** [comment]
```
sstrickl@liverpool:~/papers/chaperones {➋➀} $ git remote -v
origin	git-plt:sstrickl/papers/chaperones (fetch)
origin	git-plt:sstrickl/papers/chaperones (push)
```

So it's on the old internal git server.

**Comment by rfindler** [comment]
Thanks. I went and looked at the code and sure enough, it says right there:

```
;; this doesn't work because the cons/c aren't lazy
```

And yes, I think I agree with that comment.

So I don't know what else we should do. Remove it, I suppose.

In any case, this is now officially off of my "TODO" list. :)

**Comment by samth** [comment]
Right, I think we should just remove all traces of that case in the benchmark, and then update the .zip file.
