### ISSUE TITLE
Reorganize split with `racket/net`, moving tests into this repo

### ISSUE THREAD

**Issue by Blaisorblade** [racket/racket#1245]
Continuing from another discussion:

I [wrote](https://github.com/racket/racket/pull/1243#issuecomment-184745005):
> > As an outsider fellow user, unfamiliar with the codebase: it feels bad that tests are in another repo, but I'm not familiar enough with the codebase to judge this. But that's certainly not your responsibility.

@samth [answered](https://github.com/racket/racket/pull/1243#issuecomment-184800390):
> @Blaisorblade Yes, it's unfortunate that some of net is in this repo, and some in racket/net, and that therefore either the tests have to be split up, or some of the implementation is separate from the tests.

> Perhaps there's a better compromise here to be found -- I'm open to suggestions.

Well, you're more familiar with this, but I'll offer my opinion.

For context: I'm not sure of the boundary between this repo and `racket/net`, but I'll assume that `racket/net` is a mixture of "stuff not needed in core "more specialized applications go out". Or sth. like that. I did check [docs](http://docs.racket-lang.org/net/index.html?q=net) a bit, and found no info (which is probably fine since this is internal anyway — or maybe not, 

Still, it seems unit tests should live close to their unit — grouping them into a "test" library, nowadays with `module+ test`, doesn't serve a purpose obvious to me.

In this case: https://github.com/racket/net/blob/master/net-test/tests/net/url-string.rkt only depends on this repo, so could be here together with other tests for `racket/racket`. I don't expect this to be immediate, but certainly possible; some of those tests even seem candidates for `module+ test`. I expect some other files to be handled similarly.

Some other files are just for `racket/net`, though they'll end up being somewhat of an "integration test". If errors here are only caught in `racket/net`s test, one should (in theory) consider adding unit tests for the error if possible.

I'm sure there's some disadvantage to splitting the tests that I'm missing — but in principle that matches with splitting `net`.
Another potential issue is that `net-tests` depends on [`eli-tester`](https://github.com/racket/net/blob/master/net-test/info.rkt) and `compatibility-lib`, but they're both already used in `racket/racket`, so that should be fine.

**Comment by samth** [comment]
First, it continues to be important to have test packages, so that code using `net/url` doesn't need `rackunit`. However, that doesn't meant that we couldn't have the tests for the part of `net` in this repository couldn't be in the `racket-test` package, which is in this repository (and has the same dependencies).

I'd like to have @mflatt's perspective, since he originally created the split between the core and `net-lib`, which led to this.

**Comment by Blaisorblade** [comment]
> First, it continues to be important to have test packages, so that code using net/url doesn't need rackunit

Makes sense, I see. Other systems deal with this by having separate *test* dependencies — but that's yet another discussion, and even if you liked that it's a nontrivial infrastructure change.

Agree on everything else :+1:

**Comment by mflatt** [comment]
This problem happens with "net" and "compiler" packages (including "zo-lib"), and it's a persistent hassle.
I think that moving those packages back to the main repo is probably a good idea, but the hassle of moving them has always been much greater than the immediate hassle of dealing with multiple repos...

**Comment by samth** [comment]
Yes, I think we split too much, and the compiler and net repositories should move back. I'll look into it. Are there any others where this is an issue?

**Comment by mflatt** [comment]
I think it's just the "compiler" and "net" repos.

**Comment by samth** [comment]
We moved these repositories back in.

**Comment by Blaisorblade** [comment]
Thanks! I just found details in #1332.

* So the racket/net and racket/compiler repos should be ideally... marked as deprecated or closed?
* Should sth. happen on the the open PRs there? There's a few. You might want to take a look and migrate/close/merge them somehow.
The one which triggered this issue (tests for https://github.com/racket/racket/pull/1243) is still open as https://github.com/racket/net/pull/8, was never merged, but it seems it was taken care of. Dunno about the other open PRs at https://github.com/racket/net/pulls and https://github.com/racket/compiler/pulls.

Afraid I won't be able to contribute anything here for now—my current projects are not in Racket. 😢

**Comment by samth** [comment]
@Blaisorblade thanks for reminding me to do that. I've dealt with everything except https://github.com/racket/compiler/pull/7 and marked those repositories as obsolete.

**Comment by samth** [comment]
This is now done.
