### ISSUE TITLE
internal terminology should be improved

### ISSUE THREAD

**Issue by mflatt** [racket/racket#1249]
@gus-massa and anyone else interested:

I'd like to improve many of the gratuitously poor naming choices in the vicinity of the bytecode compiler. Here are the ones I have in mind, so far:

 * `unclosed_procedure` -> `lambda`
 * `procedure_compilation` -> `lambda`
 * `Closure_Data` -> `Lambda`
 * `..._compiled_...` -> `..._ir_...` (where "ir" is "intermediate representation")
 * `..._Compiled_...` -> `..._IR_...` (e.g., `Scheme_Compiled_Let_Value`)

I don't think any of these changes would affect the public API.

Are there other names we should fix?

**Comment by mflatt** [comment]
More:

 * `make_syntax_compiler` -> `make_primitive_syntax`
 * `scheme_syntax_compiler_type` -> `scheme_primitive_syntax_type`

**Comment by stamourv** [comment]
Would we lose information by collapsing the first three to `lambda`? As in, are the current distinctions useful?

**Comment by mflatt** [comment]
More:
 * `Scheme_Let_Header` -> `Scheme_IR_Let_Header` (since it's IR-only)
 * `SCHEME_COMPILED_CLOS_CODE` -> `SCHEME_CLOSURE_CODE`
 * `SCHEME_COMPILED_CLOS_ENV` -> `SCHEME_CLOSURE_ENV`
 * `..._CLOSURE_DATA_FLAGS` -> `..._CLOSURE_FLAGS`

**Comment by mflatt** [comment]
@stamourv No, they're all synonyms for "lambda" in different namespaces (type tag, function name, and data structure)

**Comment by stamourv** [comment]
Sounds good then!

**Comment by mflatt** [comment]
More:
 * `CLOS_...` -> `LAMBDA_...` (e.g., `CLOS_IS_METHOD`)

**Comment by mflatt** [comment]
* `Closure_Info` -> `Scheme_IR_Lambda_Info`

Also change the `closure_map` field of `Scheme_Lambda` to be a union with a new `ir_info`, which points to a `Scheme_IR_Lambda_Info`.

**Comment by gus-massa** [comment]
I have to think about this, now I only have a no-example. One that always bothers me is:

* `scheme_eq_prim` ->  `scheme_eq_proc`
* `scheme_eqv_prim` ->  `scheme_eqv_proc`
* `scheme_equal_prim` ->  `scheme_equal_proc`

I think they are named in this way since historic time and are in the public API. Is it possible to define an alias for internal use? Something like

    #define scheme_eq_proc scheme_eq_prim

in schpriv.h

**Comment by mflatt** [comment]
Good idea – and `scheme_values_func` -> `scheme_values_proc`. These are not in the public API, and changing them should be fine.

**Comment by mflatt** [comment]
Oops – I didn't meant to push that just yet. I guess it was ready enough, anyway.
