### ISSUE TITLE
raco pkg show --full-checksum doesn't show the full checksum

### ISSUE THREAD

**Issue by takikawa** [racket/racket#1252]
Example:

```
$ raco pkg show --full-checksum typed-racket
Installation-wide:
 Package       Checksum               Source
 typed-racket  79ccd77c6d3307b49c...  clone...=typed-racket
typed-racket $ git show HEAD
commit 79ccd77c6d3307b49cb370fb2f90da3076466847
```

The table formatting code seems to abbreviate the checksum separately from the main `raco pkg show` code which passes it the full string.

**Comment by jeapostrophe** [comment]
Fixed.

**Comment by samth** [comment]
Unfortunately, this fix changes the behavior of the source column as well. Looks like larger changes to the `table-display` function are needed to fix this correctly.

**Comment by jeapostrophe** [comment]
The table limits the display to 80 in long mode. The checksum is 41 characters. That gives 39 for everything else, including spacing and all that. I think the output is ridiculously un-useful. If you have such strong feelings about it, do whatever you'd like.

**Comment by samth** [comment]
In that case, we should take out the `--full-checksum` option, instead of making it just an alias for `--long`.

**Comment by jeapostrophe** [comment]
Long doesn't show it all either

Jay

On Monday, February 22, 2016, Sam Tobin-Hochstadt <notifications@github.com>
wrote:

> In that case, we should take out the --full-checksum option, instead of
> making it just an alias for --long.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/racket/racket/issues/1252#issuecomment-187214781>.
>


-- 
Jay McCarthy
Associate Professor
PLT @ CS @ UMass Lowell
http://jeapostrophe.github.io

           "Wherefore, be not weary in well-doing,
      for ye are laying the foundation of a great work.
And out of small things proceedeth that which is great."
                          - D&C 64:33

**Comment by samth** [comment]
So should the documentation for `--full-checksum` say that it implies `--long`?

**Comment by jeapostrophe** [comment]
It could

On Mon, Feb 22, 2016 at 9:53 AM, Sam Tobin-Hochstadt <
notifications@github.com> wrote:

> So should the documentation for --full-checksum say that it implies --long
> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/racket/racket/issues/1252#issuecomment-187216665>.
>



-- 
Jay McCarthy
Associate Professor
PLT @ CS @ UMass Lowell
http://jeapostrophe.github.io

           "Wherefore, be not weary in well-doing,
      for ye are laying the foundation of a great work.
And out of small things proceedeth that which is great."
                          - D&C 64:33
