### ISSUE TITLE
in-immutable-hash-values doesn't error when the hash is muttable

### ISSUE THREAD

**Issue by gus-massa** [racket/racket#1256]
I made a bad cut&paste while writing the tests of  https://github.com/racket/racket/pull/1248 and discovered that this doesn't error:

    #lang racket 
    (in-immutable-hash-values (make-hash '(1 . 2)))

All the other combinations/variations have the same problem. And it produces a segfault when used in `for` with certain hashes.

The problem is that all the versions use the same fallback that doesn't check the im/mutability of the hash [for.rkt#L724](https://github.com/racket/racket/blob/048c4b4a7338027994d81dd77785b44fb8bceaa2/racket/collects/racket/private/for.rkt#L724)

In a `for`the outher check ckecks the immutability [for.rkt#L792](https://github.com/racket/racket/blob/048c4b4a7338027994d81dd77785b44fb8bceaa2/racket/collects/racket/private/for.rkt#L792) but if it fails it calls the fallback to produce the error. As the fallback doesn't get an error, the execution continues and may get a segfault. This will be fixed automatically after splitting the fallback.

**Comment by stchang** [comment]
Thanks. I'll fix it. I probably introduced the bug when I tried to abstract all the definitions into a macro.

**Comment by stchang** [comment]
Hmm, actually I'm confused. 

The fallback is the same for all the sequences because it falls back to the generic `hash-iterate-` functions. 

I guess the behavior is still wrong, since `in-immutable-hash-` suggests that it should error when given a non-immutable hash, but I'm not seeing where it could segfault. Do you have an example?

**Comment by gus-massa** [comment]
With the outer check of the `for`, this code:

    (define h (make-hash '(1 . 2)))
    (for ([v (in-immutable-hash-values h)])
      (display v))

is effectively equivalent to 

    (define h (make-hash '(1 . 2)))
    (unless (and (hash? h) (immutable? h))
      ;let the default version generate the error
      (default-in-immutable-hash-values h))
    (for ([v (unsafe-in-immutable-hash-values h)])
      (display v))

With some hashes, the code runs anyway. I got error using the wrong combination of hash and iterator in [PR/hash.rktl#L221](https://github.com/gus-massa/racket/blob/548de61c85bcecd63a6dfeb6894a18457bb2a0ad/pkgs/racket-test-core/tests/racket/hash.rktl#L221)

**Comment by stchang** [comment]
Ok, I didnt realize the sequence continues when the outer check fails. I thought it was wrapped around everything. The right thing to do then is to throw the exception immediately when the outer check fails. I'll push a fix.

**Comment by gus-massa** [comment]
I think it' better the current behaviour because it get consistent error messages for free. Probably most of the other sequence use this method.

**Comment by stchang** [comment]
Sorry, I didnt fully understand. You think we should not throw the exception immediately, but continue to let the fallback generate the exception?

**Comment by gus-massa** [comment]
Yes, I think it's better that only the fallback generate the exception. For example `in-vector` does that [for.rkt#L906](https://github.com/racket/racket/blob/master/racket/collects/racket/private/for.rkt#L906).

**Comment by stchang** [comment]
Ok I see. `in-range` does this as well. I will make the modification.

**Comment by stchang** [comment]
Ok finally fixed this. It took longer than expected because I had to refactor the macros to get the err msgs right (and ran into some macro-defining-macro debugging fun). But I think the code is cleaner as a result.
