### ISSUE TITLE
Odd update behavior after installing with a bogus git url

### ISSUE THREAD

**Issue by takikawa** [racket/racket#1257]
I mis-typed this URL and the package seemed to install successfully:

```
$ raco pkg install git://github.com:takikawa/taglib-racket.git
Querying Git references for taglib-racket at git://github.com:takikawa/taglib-racket.git
Downloading repository git://github.comtakikawa/taglib-racket.git
....
```

But later when I tried to do a `raco pkg update --clone` it produced some odd output:

```
$ raco pkg update --clone taglib-racket
Inferred package name from given `--clone' path
  package: taglib-racket
  given path: taglib-racket
Querying Git references for taglib-racket at git://github.com:takikawa/taglib-racket.git
Updating:
  taglib-racket
Querying Git references for taglib-racket at git://github.com:takikawa/taglib-racket.git
Cloning remote repository git://github.comtakikawa/taglib-racket.git
 to /home/asumu/plt/racket-git/extra-pkgs/taglib-racket
git clone -b master git://github.comtakikawa/taglib-racket.git .
Cloning into '.'...
fatal: unable to connect to github.comtakikawa:
github.comtakikawa: Name or service not known

raco pkg update: Git command failed
```

**Comment by mflatt** [comment]
I think this is an issue with `string->url`:
```
> (url->string (string->url "git://github.com:takikawa/taglib-racket.git"))
"git://github.comtakikawa/taglib-racket.git"
```
At a minimum, I think the URL regexp mistakenly allows zero digits for a port number, instead of requiring 1 or more digits. It's possible that clients of `string->url` also need to be more careful about accepting a result URL that has #f for the `path-absolute?` field.

**Comment by mflatt** [comment]
Zero digits for a port number is apparently ok (e.g., Firefox and Chrome are happy with "http://github.com:/takikawa/taglib-racket"), but not a relative path combined with an authority (i.e, host plus optional user and port). I'll adjust `string->url` and `url->string` to reject that case.
