### ISSUE TITLE
Removing IRIX and OSF/1 support

### ISSUE THREAD

**Issue by mmcco** [racket/racket#1259]
These operating systems are long gone, but there are still many preprocessor conditions in Racket used to support them. Do the maintainers agree that this should be removed for the sake of safety and simplicity? I've started, although doing so completely is a pretty big task and may take multiple passes.

**Comment by mflatt** [comment]
Removing the configurations from "sconfig.h" would be ok with me. I don't think the configuration is particularly in the way, though, and it's at least possible that a record of things that worked in the past would be useful to someone in the future.

Or maybe you originally had in mind some code in "gc" and/or "libffi", which we concluded (in #1261) should be left alone.

**Comment by mmcco** [comment]
Sounds good. Probably easiest to leave it as-is for now.
