### ISSUE TITLE
Question: will read-line handle "\r\n" and "\r"?

### ISSUE THREAD

**Issue by quartzli** [racket/racket#1267]
This is a simple test (using Racket v6.1):
```racket
#lang racket

(when (file-exists? "test.txt")
  (delete-file "test.txt"))

(define out (open-output-file "test.txt"))
(display "abc\rdef" out)
(close-output-port out)

(define in (open-input-file "test.txt"))
(read-line in)
(read-line in)
(close-input-port in)

(delete-file "test.txt")
```

It returns:
```
"abc\r"
"def"
```

If change `(display "abc\r\ndef" out)` to `(display "abc\rdef" out)`, it returns:
```
"abc\rdef"
#<eof>
```

**Comment by jeapostrophe** [comment]
Hi Quartz,

You want to look at the second argument to read-line:

http://docs.racket-lang.org/reference/Byte_and_String_Input.html?q=read-line#%28def._%28%28quote._~23~25kernel%29._read-line%29%29

There are lots of examples including ones directly about your kind of
workload.

Jay

On Fri, Feb 26, 2016 at 4:26 AM, Quartz Li <notifications@github.com> wrote:

> This is a simple test (using Racket v6.1):
>
> #lang racket
>
> (when (file-exists? "test.txt")
>   (delete-file "test.txt"))
>
> (define out (open-output-file "test.txt"))
> (display "abc\rdef" out)
> (close-output-port out)
>
> (define in (open-input-file "test.txt"))
> (read-line in)
> (read-line in)
> (close-input-port in)
>
> (delete-file "test.txt")
>
> It returns:
>
> "abc\r"
> "def"
>
> If change (display "abc\r\ndef" out) to (display "abc\rdef" out), it
> returns:
>
> "abc\rdef"
> #<eof>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/racket/racket/issues/1267>.
>



-- 
Jay McCarthy
Associate Professor
PLT @ CS @ UMass Lowell
http://jeapostrophe.github.io

           "Wherefore, be not weary in well-doing,
      for ye are laying the foundation of a great work.
And out of small things proceedeth that which is great."
                          - D&C 64:33

**Comment by quartzli** [comment]
Sorry, I should read the documentation before open an issue.
