### ISSUE TITLE
Nearly-empty scribble file causes contract violation

### ISSUE THREAD

**Issue by howell** [racket/racket#1275]
I have a scribble file containing

``` racket
#lang scribble/manual

@defmodule[scrib_test/mod]
```

(Inside a package named scrib_test containing a module named mod).

Running this file produces a contract error:

```
../racket/racket/share/pkgs/scribble-lib/scribble/doclang.rkt:22:36: make-paragraph: contract violation
  expected: content?
  given: (list (part-tag-decl '(mod-path "scrib_test/mod")))
  in: the 2nd argument of
      (-> style? content? paragraph?)
  contract from: 
      <pkgs>/scribble-lib/scribble/core.rkt
  blaming: <pkgs>/scribble-lib/scribble/decode.rkt
   (assuming the contract is correct)
  at: <pkgs>/scribble-lib/scribble/core.rkt:222.2
```

**Comment by mflatt** [comment]
Thanks for the report, but I haven't been able to replicate this problem – even when I set up "scrib_test" and "mod.rkt".

I wonder if the program above is the one you were running, or maybe you meant to paste a different program?

**Comment by howell** [comment]
hmm, I double checked and don't see any discrepancies (it really is just two lines). I'm using racket 6.4.0.12 FWIW.

**Comment by bennn** [comment]
I don't see the problem either, as a standalone file or inside a `scrib_test` package.

**Comment by pmatos** [comment]
Can't reproduce either. Will close. Open with more information if the problem still occurs.
