### ISSUE TITLE
standard-module-name-resolver: collection not found with raco exe/dynamic-require/Typed Racket

### ISSUE THREAD

**Issue by e45lee** [racket/racket#1277]
This error comes up when using dynamic-require on a Typed Racket module that uses match which has
been included in a raco exe generated executable with ++lib.

```
standard-module-name-resolver: collection not found
  for module path: racket/match/gen-match
  collection: "racket/match"
  in collection directories:
  context...:
   show-collection-err
   standard-module-name-resolver
   #%embedded:g8870:class-prims: [running expand-time body]
   #%mzc:b: [running body]
```

I've attached a small example which produces this error:
[foo.tar.gz](https://github.com/racket/racket/files/163101/foo.tar.gz)

**Comment by mflatt** [comment]
This bug appears to have been fixed somewhere along the way, since the example works. It turns out that Racket CS did not handle a relative-path `-S` argument correctly, though, and that's now also fixed for the next release.
