### ISSUE TITLE
Redex alpha-equivalent? requires language name

### ISSUE THREAD

**Issue by schuster** [racket/racket#1279]
The prose in the docs imply that Redex's `alpha-equivalent?` should get the language from `default-language`, but in reality it requires a separate `lang` parameter. Either the docs or the code should be fixed (preferably the code - using `default-language` would match `substitute`).

**Comment by rfindler** [comment]
I think this belongs on this repo? https://github.com/racket/redex

**Comment by schuster** [comment]
You're right, my mistake. I'll move it over.

**Comment by rfindler** [comment]
Thanks!
