### ISSUE TITLE
Wrong definition of SCHEME_LISTP in scheme.h?

### ISSUE THREAD

**Issue by gus-massa** [racket/racket#1283]
It's defined in [scheme.h#L529](https://github.com/racket/racket/blob/3d484cf5605e3f1d14e791fd35564efeb1704bde/racket/src/racket/include/scheme.h#L529 ) as 

    #define SCHEME_LISTP(obj)    (SCHEME_NULLP(obj) || SCHEME_PAIRP(obj))

It's not used anywhere [Search:q=SCHEME_LISTP](https://github.com/racket/racket/search?utf8=%E2%9C%93&q=SCHEME_LISTP).

Is it posible to change it without breaking backward compatibility?

**Comment by stamourv** [comment]
That definition looks correct to me. Am I missing something?

**Comment by rfindler** [comment]
It should recur, no?​ That definition is okay for BSL. But maybe it is just
not well-named instead of being wrong? Is there a problematic use?

**Comment by gus-massa** [comment]
As fas as I know, it's unused, so there are no bugs here.

I wanted to use it, but I was not sure if it existed, and I found this definition.

The problem is that it doesn't distinguish between proper and improper lists.

    (SCHEME_LISTP (cons 1 2)) ;==> #t

 but I expect it to be `#f`

 The actual C code is somemething like this (I didn't test this, so it may not compile!!!)

     Scheme_Object* test()
     {
       if (SCHEME_LISTP(scheme_make_pair(scheme_make_integer(1),
                                         scheme_make_integer(2))) {
         return scheme_true;
       } else {
         return scheme_false;
       }
     }

I think that the correct definition is 

    #define SCHEME_LISTP(obj)     scheme_is_list(obj)

This function is used in all the other places. But I'm worry that it's not posible to change this because this definition may be backward compatible with the old times when pairs were mutable. (Perhaps we can add a comment.)

**Comment by stamourv** [comment]
@robby: Ah, yes. I knew I was missing something. :)

**Comment by mflatt** [comment]
I think it's fine to change the `SCHEME_LISTP` macro. The current macro is misleading, and it's unlikely that any code uses it, much less uses it and expects the bad behavior.
