### ISSUE TITLE
lifted.0.0 undefined when using dict-ref! in racket-mode.

### ISSUE THREAD

**Issue by LeifAndersen** [racket/racket#1284]
I have the following module:

```
#lang racket
dict-ref!
```

When I run this module in emacs mode, and then type `dict-ref!` in the repl, I get an error:

```
test.rkt﻿> dict-ref!
; lifted.0.0: undefined;
;  cannot reference an identifier before its definition
;   in module: "/Users/leif/src/racket-compiler2/test.rkt"
```

However, the next time I type it in everything is fine:

```
test.rkt﻿> dict-ref!
#<procedure:dict-ref!>
```

If I take `dict-ref!` out of the file, it also works fine. Also, this same issue also occurs for many other functions in the dict library.

This problem doesn't seem to happen when I'm using DrRacket, so I'm not sure if this is a bug in the contract that `dict-ref!` is using, or in `racket-mode` itself.

**Comment by LeifAndersen** [comment]
Writing programs that use `syntax-local-lift-expression` don't seem to have this problem, which makes me think it's likely a bug in the contract `dict` is using, rather than a bug with `racket-mode`.

Namely, the following program does not seem to have the same behavior:

```
#lang racket

(define-for-syntax lifted-value #f)

(define-syntax (foo stx)
  (syntax-case stx ()
    [_ (begin
         (unless lifted-value
           (set! lifted-value (syntax-local-lift-expression #'42)))
         lifted-value)]))

foo
```

**Comment by harrisi** [comment]
I have no justification for this, but I believe this is related to #1282, and going deeper with one or the other will solve both.
