### ISSUE TITLE
compile-file doesn't like #lang in source files.

### ISSUE THREAD

**Issue by endobson** [racket/racket#1291]
http://docs.racket-lang.org/raco/make.html?q=compile-file#%28def._%28%28lib._compiler%2Fcompile-file..rkt%29._compile-file%29%29

This is the api for simple bytecode creation and so I would assume it should accept `#lang` in the source file but it does not. I think this is actually a bug because it doesn't change the readtable at all which I would expect it to do as I wouldn't it expect it to use the context's readtable.

**Comment by mflatt** [comment]
This is an old function, and changing its behavior will likely break things. I think the documentation should explain and wrapping a call in `with-module-reading-parameterization`, so I'll do that.
