### ISSUE TITLE
Providing other forms with unicode lambda 

### ISSUE THREAD

**Issue by jasonhemann** [racket/racket#1295]
Racket helpfully provides unicode lambda (`λ`) as a synonym for `lambda`. This is especially helpful in emacs when the input-method is set to racket-unicode. But for similar forms, we're restricted to those that use  `lambda`. As an example: 

```
> ((lambda (x) x) 5)
5
> ((λ (x) x) 5)
5
> ((match-lambda (x x)) 5)
5
> ((match-λ (x x)) 5)
; match-λ: undefined;
;  cannot reference an identifier before its definition
```

One could obviously create one's own version of these identifiers. Or change input methods. But I think it might be helpful to have them available by default. It would keep folk that would want them from needing to roll their own versions, and make it less likely that folk would take these identifiers for some other purpose, and what have you.

**Comment by stamourv** [comment]
Sounds reasonable to me. Want to give it a shot?

**Comment by jasonhemann** [comment]
Sure.

**Comment by sorawee** [comment]
Closing, per #1301.
