### ISSUE TITLE
`for-module?` parameter of open-input-file is confusing and unnecessary

### ISSUE THREAD

**Issue by gasche** [racket/racket#1298]
The [documentation for open-input-file](http://docs.racket-lang.org/reference/file-ports.html#%28def._%28%28lib._racket%2Fprivate%2Fbase..rkt%29._open-input-file%29%29) does not clearly indicate the possible failure modes of the function. This makes writing robust code using it more difficult than it should be. ( @maxsnew was wondering about that just now. )

The `for-module?` parameter is only there to change this failure mode in a rather obscure case (when the user opens a port with the intent of loading a Racket module). The API would be simpler if this parameter was not present, and the users actually intending to open a file as a module were to simply catch the appropriate file-not-found failure and reraise the appropriate module-not-found error themselves. (But this require documenting the file-not-found failure mode(s) precisely.)

While trying to make sense of the for-module parameter I looked at the `port.c` implementation and there is something rather odd, possibly a bug, in its handling of for-module in lines [4658 to 4663](https://github.com/racket/racket/blob/0fb11e6/racket/src/racket/src/port.c#L4658-L4663) of the current implementation: `for_module` is set to 1 if either the `'module` or `'none` symbols are passed as arguments. I suspect this is a bug and it should be set to `0` when `'none` is passed.

**Comment by mflatt** [comment]
The handling of `'none` is indeed a bug, and I'll push a repair.

I also agree that `open-input-file` should be more clear about failure modes, and in particular that `exn:fail:filesystem` is raised for errors from the filesystem. A complication is that a security guard might get called and that security guard can raise other sorts of exceptions – but that can be documented, too.

Finally, I agree that the `for-module?` argument is ad hoc, but catching exceptions to report a derived error is distressingly tricky. For example, if a security guard has a bug and raises a `exn:fail:filesystem` error, it could be misinterpreted as the originally requested file being missing. That's a general problem, and it would be great to have a general solution. In this case, I was especially worried about misinterpreting exceptions, and (lacking a general solution) I opted for a reliable but highly specialized solution; maybe it wasn't the right choice.
