### ISSUE TITLE
`filename-extension` mishandles hidden files

### ISSUE THREAD

**Issue by mbutterick** [racket/racket#1307]
A hidden file starts with a dot, but `filename-extension` will treat its name as an extension: 

```racket
#lang racket
(filename-extension (string->path ".foo"))
> #"foo"
```

I would argue this is incorrect: that a filename extension is not merely a substring that starts with a dot, but a substring that starts with a dot **and** has some kind of filename in front of it (for which it serves as the extension).

Therefore, the fix would be to change the regexp pattern in the current `filename-extension`:

```racket
(define (filename-extension name)
  (let* ([name (file-name 'filename-extension name)]
         [name (and name (path->bytes name))])
    (cond [(and name (regexp-match #rx#"[.]([^.]+)$" name)) => cadr]
          [else #f])))
```

To have a dot pattern at the front, like so:

```racket
(define (filename-extension name)
  (let* ([name (file-name 'filename-extension name)]
         [name (and name (path->bytes name))])
    (cond [(and name (regexp-match #rx#".[.]([^.]+)$" name)) => cadr]
          [else #f])))
```

Because then:

```racket
#lang racket
(filename-extension (string->path ".foo"))
> #f
```

**Comment by mflatt** [comment]
I agree that `filename-extension` should not treat a leading "." as an extension separator, but I worry about backward compatibility. There's also `path-replace-suffix` and `path-add-suffix`, which have the same problem and same compatibility issues.

(Aside: why "extension" versus "suffix"? The root of this mismatch is ancient history and reflected in the function name `add-extension-suffix`. Outside of Racket, he term "extension" seems clearly to be the preferred one.)

One possibility is to introduce `path-replace-extension`, path-add-extension`, and `path-extension` that do the right thing, and then document the old functions as deprecated. How does that sound?

**Comment by mbutterick** [comment]
Very good, thank you.

BTW not to induce mission creep, but why do these functions treat the extension/suffix as a byte string? It seems peculiar when everything else is geared toward Unicode. 

```racket
#lang racket
(path->string (string->path "foo.λ"))
(filename-extension (string->path "foo.λ"))
> "foo.λ"
> #"\316\273"
```

**Comment by mflatt** [comment]
Unfortunately, paths are not composed of characters in general. On Unix variants, paths are composed of bytes. On Windows, they're composed of UTF-16 code units. Using a byte string accommodates both of those.

**Comment by mflatt** [comment]
Unfortunately, the name `path-extension` created conflicts for the "grip" package. I've renamed it to `path-get-extension`.
