### ISSUE TITLE
FFI | More examples for _bitmask and _enum

### ISSUE THREAD

**Issue by stonecauldron** [racket/racket#1317]
It was not immediately obvious to me on how to actually call a ffi procedure with a bitmask or enum parameter; it was only when I found this [stackoverflow question](http://stackoverflow.com/questions/1890853/using-bitmask-from-pltscheme-ffi) that I understood how to use them.

Maybe adding an example of a procedure call with an enum or bitmask in the documentation would help?

I would also gladly provide a patch for this if you deem it useful.

**Comment by stamourv** [comment]
A patch would be great!
The relevant docs are at `pkgs/racket-doc/scribblings/foreign/types.scrbl`.
