### ISSUE TITLE
Multiple test submodules retain more state than expected

### ISSUE THREAD

**Issue by david-christiansen** [racket/racket#1338]
I'm using the `-s` option to `raco test` to run multiple test submodules to test some code that relies on side effects that occur when a module is loaded.

I would expect that each test submodule that is loaded based on `-s` to be run in a fresh state, but this does not occur. As an example, take the following program (which I call `mod-effects.rkt` on disk):

```
#lang racket
(module A racket
  (displayln "A"))

(module B racket
  (require (submod ".." A))
  (displayln "B"))

(module C racket
  (require (submod ".." A))
  (displayln "C"))

(module D racket
  (require (submod ".." B)
           (submod ".." C))
  (displayln "D"))

(module E racket
  (require (submod ".." C)
           (submod ".." B))
  (displayln "E"))
```

When I run `raco test -s D -s E mod-effects.rkt`, the output is:

```
raco test: (submod "mod-effects.rkt" D)
A
B
C
D
raco test: (submod "mod-effects.rkt" E)
E
```

while I would expect that it is:

```
raco test: (submod "mod-effects.rkt" D)
A
B
C
D
raco test: (submod "mod-effects.rkt" E)
A
B
C
E
```

I didn't see any specific module initialization semantics for multiple `-s` arguments in the docs, but this behavior did surprise me. It also makes it more difficult to add tests for module initialization ordering.

**Comment by SimonLSchlee** [comment]
When I run your example with the provided input and command I get the same result.
However I looked at `raco test --help` and it revealed these options:
```
/ --direct : Run tests directly (default for a single file)
| --process : Run tests in separate processes (default for multiple files)
\ --place : Run tests in places
```
This explains that the default behavior for a single file is to use this direct mode.
When I change the command to `raco test -s D -s E --process mod-effects.rkt` I get this output:
```
raco test: (submod "mod-effects.rkt" D)
A
B
C
D
raco test: (submod "mod-effects.rkt" E)
A
C
B
E
```
So this behavior seems consistent to me. Maybe direct shouldn't be the default for a single file, but I don't have the knowledge (insufficient knowledge about the intentions etc.) to argue for or against that.

From my point of view using the `--process` command line option solves this issue.
