### ISSUE TITLE
Segfault when dynamic-requiring something where a macro expanded to a definition at a higher phase

### ISSUE THREAD

**Issue by AlexKnauth** [racket/racket#1339]
In one file, there is a `(dynamic-require "lib2.rkt" 'x)`, where `lib2.rkt` requires and re-provides `(for-meta -2 "lib.rkt")`. So the `dynamic-require` is trying to reference something at phase 2 of `lib.rkt`. And `lib.rkt` defines `x` at phase 2 using a macro that expands to a nested `begin-for-syntax` containing the definition.

This crashes DrRacket and results in a `Segmentation fault: 11` message on the command line.

```racket
;; user.rkt
#lang racket
(dynamic-require "lib2.rkt" 'x)
```
```racket
;; lib2.rkt
#lang racket
(require (for-meta -2 "lib.rkt"))
(provide (for-meta -2 (all-from-out "lib.rkt")))
```
```racket
;; lib.rkt
#lang racket
(define-syntax-rule (macro)
  (begin-for-syntax
    (require (for-syntax racket/base))
    (begin-for-syntax
      (provide x)
      (define x 5))))
(macro)
```

**Comment by AlexKnauth** [comment]
So the macro expanding to a nested `begin-for-syntax` doesn't change the problem?

**Comment by AlexKnauth** [comment]
Ok. I originally came across this problem wondering if macros could expand to definitions at higher phases than themselves. So if you add the macro bit back in, it still works? Does the dynamic-require of a phase 2 `x` also run the macro code (which is at phase 1) first?

**Comment by mflatt** [comment]
Really – it still works after the repair. :)

A `dynamic-require` of a variable export will never run a macro implementation. It's working in terms of expanded (and compiled) modules. If the export accessed by `dynamic-require` is a variable in some module, then that module will have the definition already expanded.

In your example, "lib.rkt" is compiled to have a definition at phase level 2, then "lib2.rkt" is compiled to re-export the defined variable, and then `dynamic-require` instantiates the module (with a phase shift of -2) and accesses the variable (at phase 0, which is phase level 2 shifted by -2).

**Comment by AlexKnauth** [comment]
Ok. So does that mean the macro code at phase 1 has to run before phase 2 is finished? I had thought phase 2 always had to happen before phase 1. Also, thanks!

**Comment by mflatt** [comment]
Evaluation of phases can certainly be interleaved at compile time.

If you haven't already, you might want to take a look at the mflatt/expander repo, especially the "exand/module.rkt" module: https://github.com/mflatt/expander/blob/master/expand/module.rkt

You'll see the interleaving that I think you're asking about in the `phase-1-and-2-loop` part, where `begin-for-syntax` can move the recursive expansion process to an arbitrarily deep phase, and that can happen both before and after `define-syntaxes` or `begin-for-syntax` triggers evaluation at some other phase (> 0).

FWIW, this new implementation of the expander worked right on your example in the first place.
