### ISSUE TITLE
using external font files (rather than installed fonts) with the `racket/draw` PDF renderer?

### ISSUE THREAD

**Issue by mbutterick** [racket/racket#1348]
Is there a way to instantiate a `font%` from a path to a font (rather than from the installed system fonts)?

I am rewriting [Quad](https://github.com/mbutterick/quad) with some new & improved ideas.

Rather than use `get-text-extent` to measure text, I’m using the FFI to call into FreeType directly (because it’s faster and allows use of local font files).

But AFAICT the `racket/draw` PDF renderer only works with fonts already installed on the system (via the `font%` object). So by using FreeType, I lose my route to PDF.

**Comment by takikawa** [comment]
My understanding is that Racket uses [Pango](http://www.pango.org/) for its text rendering, which uses platform-specific backends and doesn't offer a general way to install fonts. I ran into this issue with portable slideshow presentations as well so have looked into it a bit.

On Linux and similar unix systems, you can use fontconfig to temporarily load external font files for an application. (I have FFI bindings for it here: https://github.com/takikawa/racket-fontconfig) On Windows, it is also possible (and I have some code that I'm planning to put somewhere which does the same). I'm not sure if there is a good solution for OS X.

**Comment by mbutterick** [comment]
But the `fontconfig` library is part of the OS X Racket distribution, right? What is different about OS X?

**Comment by takikawa** [comment]
Oh, so it is. I hadn't actually tried using fontconfig on OS X since I don't have a Mac. Unfortunately when I just asked @bennn to try it, it seems to segfault (possibly a bug in the FFI lib?). If you want to try it, there's a test file here that will display a pict when run: https://github.com/takikawa/racket-fontconfig/blob/master/test.rkt (you will want to change the font file path appropriately)

**Comment by mbutterick** [comment]
Hmm yes, I got a segfault too. 

But see [`cairo-lib.rkt`](https://github.com/racket/draw/blob/master/draw-lib/racket/draw/unsafe/cairo-lib.rkt), which contains both 

1) cross-platform code for loading `fontconfig` and 

2) a “Racket-specific patch to Fontconfig” that seems to specify the location of the font directories. 

I will investigate this more later, but perhaps this could be adapted so that Fontconfig “boots” into the source directory, rather than the shared system fonts directory?

**Comment by mbutterick** [comment]
@mflatt: are the functions in your [patch to FontConfig](https://github.com/racket/racket/blob/master/racket/src/native-libs/patches/fcdirs.patch) used to change the default directory from which `racket/draw` loads its fonts? (FWIW I have been fiddling with it but not succeeded in doing this.) If so, can this capability be exposed in the `racket/draw` interface? (e.g., with a `current-font-directory` parameter)

**Comment by mflatt** [comment]
@mbutterick I think I added that specifically for the "natipkg" Linux builds Those builds bundle fontconfig, Pango, etc., similar to the OS X and Windows builds, but even more configuration is needed in an environment that doesn't provide fonts at all. So, that patch won't be present on typical Linux environments.

Meanwhile, on OS X and Windows (where the OS always provides font support), probably platform-specific calls are needed. Something like the second answer here may be needed on OS X: http://stackoverflow.com/questions/5283572/custom-font-in-a-cocoa-application

**Comment by mbutterick** [comment]
What about the technique [you used in `gui-lib`](https://github.com/racket/gui/blob/master/gui-lib/mred/private/wx/cocoa/font.rkt#L55) to “register a family manually”? Is that technique adaptable here, or is that a distinct situation?

**Comment by mflatt** [comment]
That's a distinct situation.

**Comment by mbutterick** [comment]
OK, so what I’m gathering is that even though `fontconfig` is bundled with Racket on all platforms, it’s not actually involved in the font-loading machinery on each platform in a consistent way. 

@takikawa: maybe we should try to shave this yak and PR it, so future generations will regard us as heroes, etc. Since you have the Linux and Windows pieces, I will look into the OS X angle.

**Comment by mbutterick** [comment]
I’ve figured out how to translate the [technique suggested by @mflatt](http://stackoverflow.com/questions/5283572/custom-font-in-a-cocoa-application) into the FFI. 

I can successfully add local fonts, which show up in the Cocoa `NSFontManager`. 

But they don’t show up in `get-face-list` from `racket/draw`. (i.e, they apparently remain inaccessible to Cairo/Pango, and thereby `racket/draw`). 

Is there a simple way of forcing a refresh of the Cairo/Pango font database from Cocoa? Or is it more elaborate surgery? It’s not obvious to me how, under the hood, Cocoa & Cairo/Pango cooperate.

**Comment by mbutterick** [comment]
Perhaps this only bears on Linux, but  [“How to use custom application fonts with Pango”](http://mces.blogspot.com/2015/05/how-to-use-custom-application-fonts.html)

**Comment by mbutterick** [comment]
Following the [suggestion here](https://bugzilla.gnome.org/show_bug.cgi?id=347237#c25), I tried using `pango_cairo_font_map_new_for_font_type` with `pango_cairo_font_map_set_default` to update the font list seen by `racket/draw` (because `get-face-list` relies on `pango_cairo_font_map_get_default`). But that didn’t work.

A workaround I hadn’t considered before is to just bypass `racket/draw` entirely and instead rely on Quartz in OS X for font management, text measurement, and PDF generation. Not my first choice. But for `quad`, it seems that Pango/Cairo has now revealed itself to have two major shortcomings (= dynamic font loading, and PDF generation).

Closing this issue as impracticable.

**Comment by mbutterick** [comment]
Maybe it would be more useful to think of these as separate targets: 1) generating PDFs of Racket docs without LaTeX and 2) having a generally useful PDF typesetting engine in Racket. Target (1) is less flexible, but relies only on `racket/draw` (and is thus cross-platform) and target (2) has more capability, but also depends more on platform-specific services.
