### ISSUE TITLE
Abort trap: 6 on Racket 6.5.0.5

### ISSUE THREAD

**Issue by bennn** [racket/racket#1351]
@takikawa told me to run a strange program and it raised a trap 6. Then he told me to submit this minimal example. I have no idea what's happening.

```
#lang racket/base

(require ffi/unsafe)

(define-cpointer-type _FcCharSet)

(define-cstruct _FcMatrix ([xx _double] [xy _double]
                           [yx _double] [yy _double]))

(define-cstruct _FcValue ([u (_union _bytes _int _bool _double
                                     _FcMatrix-pointer
                                     _FcCharSet)]))
```

Running:

```
bash-3.2$ racket ../mystery-segfault.rkt 
Abort trap: 6
```

**Comment by mflatt** [comment]
libffi doesn't actually support union types, and there's a problem with the hack that Racket uses to try to make it work, anyway. I may have a repair, but I'll have to test it more.

**Comment by samth** [comment]
Potentially relevant: https://github.com/libffi/libffi/issues/33

**Comment by juszczakn** [comment]
Has any progress been made on this? I just spent the last couple of days digging into trying decipher how unions worked, so this is disappointing. 
Maybe the docs on unions should be updated to notify users of the current state of the feature?

**Comment by mflatt** [comment]
I don't remember what happened here, but think it just fell through the cracks. I'll push a new approach to `_union` that I think will work more often.

**Comment by juszczakn** [comment]
This is probably just my inexperience with racket/ffi in general, and probably outside of the scope of this issue, but:

It seems like _union is meant to be used in conjunction with union-ref and union-set!. However, these two functions are private to the ffi package? See https://github.com/racket/racket/blob/4c5f66ff4a0ad2714f835a0f6551e4080b1f690a/racket/collects/ffi/unsafe.rkt#L1163

If these functions are protected, it seems unclear to me how one would go about unwrapping a union. For reference, I'm trying to figure out how best to represent SDL_PollEvent (https://wiki.libsdl.org/SDL_PollEvent), which takes an SDL_Event as a in-out param.

**Comment by mflatt** [comment]
`protected` does't mean "private". It means "protect against use by untrusted code".

**Comment by juszczakn** [comment]
Ok, sorry, this is probably not the place for this, but I'm not sure what I'm missing as to why the following snippet doesnt work. 
If I stay at the top level module and don't use `enter!`, everything works fine.
I've read over the doc for code inspectors, however I don't really understand how they tie into why this is prevented.
```
:~$ racket
Welcome to Racket v6.9.
> (module asdf racket)
> (enter! 'asdf)
'asdf> (require ffi/unsafe)
'asdf> _union
#<procedure:_union>
'asdf> union-ref
; ?: access disallowed by code inspector to protected variable from module:
;   "/opt/racket/collects/ffi/unsafe.rkt"
;   in: union-ref
; [,bt for context]
'asdf> ,bt
; ?: access disallowed by code inspector to protected variable from module: "/opt/racket/collects/ffi/unsafe.rkt"
;   in: union-ref
;   context...:
;    /opt/racket/share/pkgs/xrepl-lib/xrepl/xrepl.rkt:1448:0
;    /opt/racket/collects/racket/private/misc.rkt:88:7
'asdf> 
```

**Comment by mflatt** [comment]
That doesn't look like the right behavior, and it's likely a problem in the macro expander related to `enter!`. (A newer implementation of the expander appears to not have this problem.)

I'll investigate more, but it looks like using `(require ffi/unsafe)` within the `asdf` module – before `enter!` – works around the problem.

**Comment by bennn** [comment]
My original example doesn't abort on HEAD, so I'm going to close this.
