### ISSUE TITLE
make-fsemaphore sometimes called with bad values

### ISSUE THREAD

**Issue by florence** [racket/racket#1356]
This has come up twice:

http://pasterack.org/pastes/84408
https://botbot.me/freenode/racket/2016-05-09/?msg=65750495&page=4

And:
https://twitter.com/olgeni/status/747411004074692608

It might be a problem when futures are disabled.

**Comment by olgeni** [comment]
How do I find out if futures are disabled? (I'm using racket-6.5-src-builtpkgs.tgz)

**Comment by samth** [comment]
You can run this program to check:

```racket
#lang racket
(require racket/future)
(futures-enabled?)
```

**Comment by samth** [comment]
Also, can you report the result of running this program?

```racket
#lang racket
(require typed-racket/utils/any-wrap rackunit)
(contract any-wrap/c '(def) 'a 'b)
(require/expose typed-racket/utils/any-wrap [base-val?])
(base-val? 'def)
```

**Comment by olgeni** [comment]
`(futures-enabled?)` gives `#f`

The other program stops at

    (contract any-wrap/c '(def) 'a 'b)

and says:

     make-fsemaphore: contract violation
      expected: exact-nonnegative-integer?
      given: '(def)

which looks a lot like the original exception...

**Comment by samth** [comment]
Indeed it does. What if you comment out that line, so that the next one runs?

**Comment by olgeni** [comment]
That gives me a `#t` for `(base-val? 'def)`.

**Comment by samth** [comment]
Ok, what about `(base-val? '(def))` (which is what I intended to write in the first place, sadly)?

**Comment by olgeni** [comment]
Trying this:

    #lang racket
    (require typed-racket/utils/any-wrap rackunit)
    (require/expose typed-racket/utils/any-wrap [base-val?])
    (base-val? '(def))

->

    make-fsemaphore: contract violation
      expected: exact-nonnegative-integer?
      given: '(def)

But then I forced futures with --enable-futures, and I have this:

    #lang racket
    (require racket/future)
    (futures-enabled?)

->

    #f

And

    #lang racket
    (require typed-racket/utils/any-wrap rackunit)
    (require/expose typed-racket/utils/any-wrap [base-val?])
    (base-val? '(def))

->

    #f

I also get the doc arrow in the upper right corner, which was what I hoped.

It looks like the FreeBSD build is not picking up futures by default?

**Comment by samth** [comment]
Can you try one more thing on your original (broken) install?

```racket
#lang racket
(define (base-val? e)
  (or (number? e) (string? e) (char? e) (symbol? e) (semaphore? e) (fsemaphore? e)))
(base-val? '(def))
```

**Comment by samth** [comment]
Also, can you try compiling that file (with `raco make`) and then decompiling it with `raco decompile file.rkt` and pasting the output somewhere?

Thanks a bunch for all the testing!

**Comment by olgeni** [comment]
Checking...

    #lang racket
    (fsemaphore? '(def))
    (define (base-val? e)
      (or (number? e) (string? e) (char? e) (symbol? e) (semaphore? e) (fsemaphore? e)))
    (base-val? '(def))

->

    #f 
    #f 

Then I got a dump here: https://gist.github.com/olgeni/ef3d068680cb8d077f9cfbc1f8e82f2e

**Comment by samth** [comment]
Oh, interesting, that didn't error. What if you try the whole implementation of `base-val?` from [here](https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/utils/any-wrap.rkt#L16-L34) (copied below)?

```
(define (base-val? e)
  (or (number? e) (string? e) (char? e) (symbol? e)
      (null? e) (eq? undefined e) (path? e) (eof-object? e)
      (regexp? e) (pregexp? e) (byte-regexp? e) (byte-pregexp? e)
      (keyword? e) (bytes? e) (boolean? e) (void? e)
      (bytes-converter? e)
      (impersonator-property? e)
      (inspector? e)
      (logger? e)
      (module-path? e) (resolved-module-path? e)
      (pretty-print-style-table? e)
      (pseudo-random-generator? e)
      (semaphore? e) (fsemaphore? e)
      (thread-group? e)
      (udp? e)
      ;; Base values because you can only store flonums/fixnums in these
      ;; and not any higher-order values. This isn't sound if we ever
      ;; introduce bounded polymorphism for Flvector/Fxvector.
      (flvector? e) (fxvector? e) (extflvector? e) (extflonum? e)))
```

**Comment by olgeni** [comment]
I got the missing `require`s:

    #lang racket
    
    (require racket/match racket/contract/combinator
             racket/class racket/unit
             racket/fixnum racket/flonum racket/extflonum
             racket/set
             racket/undefined
             (only-in racket/async-channel async-channel?)
             (only-in racket/future future? fsemaphore?)
             (only-in racket/pretty pretty-print-style-table?)
             (only-in racket/udp udp?)
             (only-in (combine-in racket/private/promise)
                      promise?
    prop:force promise-forcer))
    
    (define (base-val? e)
      (or (number? e) (string? e) (char? e) (symbol? e)
          (null? e) (eq? undefined e) (path? e) (eof-object? e)
          (regexp? e) (pregexp? e) (byte-regexp? e) (byte-pregexp? e)
          (keyword? e) (bytes? e) (boolean? e) (void? e)
          (bytes-converter? e)
          (impersonator-property? e)
          (inspector? e)
          (logger? e)
          (module-path? e) (resolved-module-path? e)
          (pretty-print-style-table? e)
          (pseudo-random-generator? e)
          (semaphore? e) (fsemaphore? e)
          (thread-group? e)
          (udp? e)
          ;; Base values because you can only store flonums/fixnums in these
          ;; and not any higher-order values. This isn't sound if we ever
          ;; introduce bounded polymorphism for Flvector/Fxvector.
          (flvector? e) (fxvector? e) (extflvector? e) (extflonum? e)))

Which compiles to https://gist.github.com/olgeni/f2e7584722a01239af407614f3e61c31 (!)

**Comment by samth** [comment]
@olgeni does that produce `#f` for you with `(base-val? '(def))`, or give an error?

**Comment by olgeni** [comment]
I tried from the IDE and got an `#f`.

By default I have the precompiled any-wrap.rkt - could it be related somehow?

**Comment by samth** [comment]
I think it's related to it being in a separate file.
