### ISSUE TITLE
syntax-parse changes break several packages

### ISSUE THREAD

**Issue by samth** [racket/racket#1359]
Changes to `syntax-parse` since 6.5 have broken several packages:

https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/seq-no-order.txt
https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/cKanren.txt

as well as https://github.com/dented42/scribble-latex-utils. 

We should address this before the release of 6.6: is it an unavoidable incompatibility, or can this be fixed, or should the original change be reverts.

**Comment by wilbowma** [comment]
From what I understand talking to @rmculpepper, this change is *necessary* and packages broken by the change only worked by chance.

However, those packages did work, and making a backward incompatible change without much announcement/prep time seems like bad idea.

Can we disable the optimization that makes this error necessary, and change the error to a warning for this release?

**Comment by rfindler** [comment]
What do you mean by "by chance"? Is there a use of `random` in `syntax/parse`?

**Comment by wilbowma** [comment]
My understanding is that they only worked because the implementation did not perform an optimization that ought to have been valid. "Empty-ellipsis head patterns" could result in an infinite search dependeing on how the search is performed, so it ought not to have been allowed from the start. "It just so happens" that the old implementation didn't infinitely search when someone used such a pattern.

**Comment by samth** [comment]
My feeling is that there are two possible cases here:

1. the semantics of `syntax-parse` relies on not searching in these cases (for example, if you wrote this, then it would behave differently in different places, and do the wrong thing sometimes). Then it seems like there's a hard question about what to do.

2. the semantics of "old `syntax-parse`" allowed these things, but wasn't intended to, and gave them a reasonable meaning. But since that wasn't intended, it breaks an equality that @rmculpepper wanted to use for optimization. In that case, I think we should just stick with the old semantics and skip the optimization.

**Comment by rfindler** [comment]
@wilbowma I'm not sure if this is where you're going with that, but that is not a suitable rationale to declare the problem in the pkgs (as opposed to being in syntax-parse). The change in syntax-parse broke these packages. If we had the "go back in time" capability, then we could use a rationale like that to decide to change the original syntax-parse.

As for how we proceed with the release, I think that unless Ryan (or someone) comes up with a fix that makes these programs continue to work while supporting the new features, we should revert this change to syntax-parse. We technically have a week before we have to make this decision, so there is time to avoid reverting the change if someone figures something out.

**Comment by rfindler** [comment]
To put this another way: there is a specification that syntax-parse was supposed to be living up to, but that spec wasn't checked. So that means it is NOT FAIR to expect clients of syntax-parse to live up to that specification, as the authors of those clients had no help in knowing that they didn't abide by the specification.

**Comment by wilbowma** [comment]
That's a good point. I'll wait for Ryan to weigh in; maybe I misunderstood, or maybe I mis-explained what I understood.

**Comment by rmculpepper** [comment]
Details and clarifications: The change concerns the behavior of patterns like `(a (~seq) ...)`. syntax-parse is a backtracking parser, and ellipses are greedy, so parsing this pattern "should" diverge ("ok, I was able to parse one iteration of no elements, let's try to parse another... ok, that worked too!...").

Previously, there was a bug (an unsound optimization) that made some bad programs parse successfully instead of diverging.

Now syntax-parse does a dynamic check and raises an error if an ellipsis head pattern matches zero elements instead of diverging. (If it can detect that the ellipsis head pattern is nullable, it issues a static warning. I plan to turn that into a static error sometime after the next release.)

**Comment by rfindler** [comment]
@rmculpepper is there a change that would allow some small set of such programs to continue to parse successfully for now? If so, is this a change that would be reasonable to maintain for the forseeable future? If not to the latter, but yes to the former, do you think you can do something that you'd be okay with for a little while to give the pkg authors whose code is currently broken time to respond?

**Comment by samth** [comment]
Are there programs that this unsound optimization broke? As in, some syntax-parse pattern that's parsed incorrectly before but correctly now?

**Comment by AlexKnauth** [comment]
What if the EH-pattern has a `~once` pattern or something similar, and that matched an empty sequence? Would this display an error then too?

**Comment by rfindler** [comment]
Just to be clear, this isn't an abstract backwards compatibility problem
and if we cannot get those package authors to unbreak their packages, that
seems problematic for the release.

We do NOT want to break cKanren!

**Comment by stamourv** [comment]
Branch day is today. We need to resolve this issue.
Otherwise, I'll revert the commits that introduced the regression.

**Comment by samth** [comment]
@stamourv We definitely need to resolve the issue before the release, but it doesn't seem like it has to be today.

**Comment by rfindler** [comment]
Well, we need to do something with the branch, right? I think making the branch be before those commits (are they are the latest ones?) is a good starting point.

**Comment by samth** [comment]
No, the problematic commits are quite a while ago. In particular, fb5c1310d8a28d058f16eae969965169ae7204a7 from May introduces the dynamic error.

**Comment by stamourv** [comment]
@samth: I'd rather avoid having regressions (that we know about) on the release branch, that we'd have to fix before the actual release. Fail safe, and all that.

**Comment by samth** [comment]
@stamourv but reverting commits (which might break other packages) and the un-reverting them again later along with the fix seems like a more-dangerous solution.

**Comment by rfindler** [comment]
It sounds like we need some help from @rmculpepper here. It has been two days since his last comment.

**Comment by stamourv** [comment]
After discussion with @rmculpepper, here's the plan.
* @rmculpepper will undo the problematic changes (but not by reverting commits) for this release. This does not block release branch creation.
* Between 6.6 and 6.6, @rmculpepper will fix the packages that were broken by the changes, then reintroduce the changes.

**Comment by wilbowma** [comment]
Might be worth mentioning in this release, so people who have potentially buggy code that is not on the pacakge server or public GitHub know about it.

**Comment by stamourv** [comment]
Good idea.

**Comment by rmculpepper** [comment]
Update: The issue I had expected to work around was already worked around (for the `generic-bind` package). The regressions in `cKanren` and `seq-no-order` appear to be fixable by avoiding the empty match check if the pattern is already bounded (eg by `~once`, as @AlexKnauth pointed out).

**Comment by stamourv** [comment]
Thanks @ryanc!
IIUC, this means we're all set for the release as far is this issue is concerned. Is this correct?

**Comment by rmculpepper** [comment]
Yes, I think so. (BTW, ryanc is someone else on github.)
