### ISSUE TITLE
module+ interleaving breaks sibling module requires

### ISSUE THREAD

**Issue by jackfirth** [racket/racket#1363]
On racket 6.5 in DrRacket, this works fine:

```racket
#lang racket

(module+ foo
  (define x 10)
  (provide x))

(module+ main
  (require (submod ".." foo)))
```

But adding anything to the main submodule via module+ *above* the definition of the foo module breaks the require:

```racket
#lang racket

(module+ main
  "blah")

(module+ foo
  (define x 10)
  (provide x))

(module+ main
  (require (submod ".." foo)))
```

This results in the error:

```
require: unknown module
  module name: #<resolved-module-path:(submod 'anonymous-module foo)>
```

This error is also thrown if the entire main submodule is defined before the `foo` submodule, but that is expected behavior (to me, anyways).

**Comment by mflatt** [comment]
The `module+` form collects module bodies and assembles them one a single `module*` form for a given submodule name. (The `module+` form also promises to order the generated `module*` forms based on the initial use of each submodule name with `module+`.) The `module+` form can't expand the submodules piecewise, so putting a use of `foo` later than the initial `(module+ main ....)` doesn't help.

**Comment by jackfirth** [comment]
That makes sense, and thinking about this more I'm not sure how else the submodule system could work. Closing as intended behavior.
