### ISSUE TITLE
read-syntax returns syntax with negative column position

### ISSUE THREAD

**Issue by dfeltey** [racket/racket#1371]
The following program seems to return -1, which breaks the documented contract of `syntax-column`, and it seems like `set-port-next-location!` should cause the next column to be `#f` rather than `-1`, but I'm not sure what the correct behavior should be.

```
#lang racket

(define p (open-input-string "foo"))
(port-count-lines! p)
(set-port-next-location! p #f #f #f)
(define stx (read-syntax 'dummy p))
(syntax-column stx)
```

**Comment by Paul-C-Anagnostopoulos** [comment]
Now `(syntax-column stx)` returns #f, so this appears to be fixed. However, `stx` has the value

```#<syntax:dummy::-1 foo>```

Does that matter?

**Comment by sorawee** [comment]
In Racket CS, `stx` is printed as `#<syntax:dummy::#f foo>`, and `(syntax-column stx)` returns `#f`.

In Racket BC, `stx` is still printed as `#<syntax:dummy::-1 foo>`, but `(syntax-column stx)` returns `#f` as mentioned above.
