### ISSUE TITLE
segfault using `in-immutable-hash`

### ISSUE THREAD

**Issue by bennn** [racket/racket#1376]
On Racket 6.5 and the 6.6 release candidate, this program segfaults when _compiled_ and run.
```
#lang racket/base
(for/list (((k v) (in-immutable-hash #hash((a . 1) (b . 2)))))
  (cons k v))
```

If only interpreted, it returns `'((b . 2) (a . 1))`.
I get the same "backwards list" result if I make the hashtable with `make-immutable-hash` instead of `#hash`.

**Comment by bennn** [comment]
(`in-mutable-hash` and `in-weak-hash` seem fine)

**Comment by mflatt** [comment]
@bennn Thanks for the report!
