### ISSUE TITLE
(~or a (a b c)) … gives the error "syntax-parse: duplicate attribute"

### ISSUE THREAD

**Issue by jsmaniac** [racket/racket#1390]
Racket version: 6.6.0.1

``` racket
#lang racket
(require syntax/parse)
(syntax-parse #'(x y z) [((~or a (a b c)) ...) #'(a ...)])
```

The code above gives this error message (the `a` in `(a b c)` is highlighted):

```
syntax-parse: duplicate attribute in: a
```

This error occurs only when the `~or` is nested under an ellipsis `…`, so this works fine:

``` racket
#lang racket
(require syntax/parse)
(syntax-parse #'(x) [((~or a (a b c))) #'(a)])
```

Furthermore, if there is another operator between the ellipsis `…` and the `~or`, it seems to work too:

``` racket
#lang racket
(require syntax/parse)
(syntax-parse #'(x y z) [((~and dummy (~or a (a b c))) ...) #'(a ...)])
```

If instead one uses `~parse` to split the `~or` in a separate invocation of the parser, it works too (but it might be just because of the `~and` between the ellipsis `…` and the `~or` too):
the error

``` racket
#lang racket
(require syntax/parse)
(syntax-parse #'(x y z)
  [((~and tmp (~parse (~or a (a b c)) #'tmp)) ...)
   #'(a ...)])
```

**Comment by rmculpepper** [comment]
Yes, `~or` is interpreted differently in front of ellipses, and it currently requires the attributes of the disjuncts to be distinct. I could imagine relaxing that in some cases, but it gets tricky with patterns like

    ((~or (~once (#:a x)) (~optional #:b x)) ...)

If you want the single-term version of `~or` in front of ellipses, you can wrap an `~and` pattern around it, like you mention above.

**Comment by jsmaniac** [comment]
Maybe it would be sensible to add a `(~either a b c)` pattern, which would be equivalent to `(~and (~or a b c))`? Or maybe name it `~xor`?

Even if it's not part of the library, I'm open to naming suggestions as it is already in my `phc-toolkit` library (albeit undocumented for now) under the sub-optimal name `~or-bug` :)

**Comment by sorawee** [comment]
`~or` is now indicated in the doc as discouraged. `~or*` and `~alt` should be used instead. For this case, `~or*` works as expected. Closing.
