### ISSUE TITLE
Syntax classes that include the #:opaque option ignore error messages from #:fail-when and #:fail-unless

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#1394]
When a syntax class is defined with the `#:opaque` option, error messages produced by `#:fail-when` or `#:fail-unless` are ignored:

```racket
(define-syntax-class always-fail
  #:opaque
  [pattern _ #:fail-when #t "failure message"])

(syntax-parse #'something
  [_:always-fail (void)])
```
```
something: expected always-fail in: something
```

I think that, intuitively, the `#:opaque` modifier should only hide errors generated by the patterns themselves, but errors produced by `#:fail-when` or `#:fail-unless` should still be propagated. I recognize that classes that fail using `~fail` are probably a more ambiguous case, since ideally I think they should probably *also* be reported, and `#:opaque` should only hide errors produced by *child syntax classes*, but I wouldn’t mind if `~fail` still didn’t work.

Since there is no situation in which someone would specify `#:opaque` and one of the `#:fail-*` options within a pattern if those options will always be silenced, I think the messages should be propagated, given that sometimes it can provide more nuanced error reporting even if the internal syntax class structure should not be exposed.

**Comment by rmculpepper** [comment]
The `#:opaque` option is intended to hide all internal information about the causes of failures.

You can get something closer to the behavior you describe by wrapping the patterns (but not the side-clauses) with `(~describe #:opaque #f [ ])`. Note the `#f` is the description argument, not an argument to the `#:opaque` keyword.

**Comment by lexi-lambda** [comment]
Ah, that’s a decent solution—I didn’t realize `~describe` could be marked `#:opaque`. I think I still wish the behavior were different, but I’m willing to consider that a reasonable workaround.
