### ISSUE TITLE
Allow regexp values in compile-omit-paths

### ISSUE THREAD

**Issue by jackfirth** [racket/racket#1400]
With `test-omit-paths` I can omit files from testing by regexp. It would be nice to do this in compile-omit-paths as well. For example, I'd like to omit all files that have the word "test" in their name from normal setup compilation to avoid having test dependencies at runtime.

**Comment by spdegabrielle** [comment]
is this still an issue?  Please consider adding the label `good first issue` so it is findable: 

[Issues labeled `good first issue` in in Racket GitHub repositories](https://github.com/search?q=type:issue+org:racket+state:open+label:%22good+first+issue%22)

**Comment by jessealama** [comment]
@jackfirth just to confirm: is this still an issue? I imagine it is, but I thought I'd double check. Sometimes a backlog can contain items that have been taken care of, especially older stuff like this (from 2016).

**Comment by sorawee** [comment]
Yes, currently Racket still doesn't support regex for `compile-omit-path`.

I attempted to implement this a few months ago. It was not as easy as it looks, so I quitted.

**Comment by jessealama** [comment]
@spdegabrielle given what @sorawee says, I wonder if this is really a good first issue. Perhaps this issue easier said than done, requiring one to dig in deeper than an initial impression would suggest.
