### ISSUE TITLE
Request: IRacket

### ISSUE THREAD

**Issue by act65** [racket/racket#1407]
hey,
Dont know how easy this is, but those jupyter notebooks are pretty awesome. Any chance of being able to use racket as a kernel?
If it bugs me enough, ill look into it.
alex

**Comment by rmculpepper** [comment]
There's a preliminary version at https://github.com/rmculpepper/iracket. See the README for installation instructions. It is not quite ready as a package because it needs some changes to the zeromq library, and I haven't had a chance to deal with those yet.

**Comment by act65** [comment]
sick. thanks
