### ISSUE TITLE
Failed to embed racket in a program

### ISSUE THREAD

**Issue by Ninlives** [racket/racket#1417]
Finally get racket built, then I followed the documention https://docs.racket-lang.org/inside/embedding.html?q=embed trying to embed Racket CGC in a program. I created exact the same code as shown in the example except adding `#include "scheme.h"` at the beginning of `base.c`.Compilation passed but while debugging it shows:
```
Exception thrown at 0x00007FF9DA65025D (libracket3m_a0solc.dll) in rac.exe: 0xC0000005: Access violation writing location 0x000001B05BC404F8.
```

**Comment by mflatt** [comment]
Just to make sure, does your program include the `scheme_register_tls_space()` that's needed specifically on Windows?

**Comment by Ninlives** [comment]
I have to admit the I missed that...sorry for my impatience.I changed the main function to:
```
int main(int argc, char *argv[])
{
	static __declspec(thread) void *tls_space;
	scheme_register_tls_space(&tls_space, 0);
	return scheme_main_setup(1, run, argc, argv);
}
```
But similar exception thrown when I add a commandline arguments `"(display "123")"`,

**Comment by Ninlives** [comment]
I have to admit the I missed that...sorry for my impatience.I changed the main function to:

int main(int argc, char *argv[])
{
    static __declspec(thread) void *tls_space;
    scheme_register_tls_space(&tls_space, 0);
    return scheme_main_setup(1, run, argc, argv);
}

But similar exception thrown when I add a commandline arguments "(display \"123\")",

**Comment by mflatt** [comment]
Looking again at the error message, I see that it says "libracket3m", but you meant to link to the CGC variant of Racket, which is the one without "3m" in its name. Does changing your program's linking help?

**Comment by Ninlives** [comment]
that's it :) what a fool I am. Sorry for bothering you with such a stupid problem.

**Comment by mflatt** [comment]
No problem – glad it's working!
