### ISSUE TITLE
codeblock-pict incorrect rendering with \r\n newlines

### ISSUE THREAD

**Issue by BenChung** [racket/racket#1419]
I'm trying to render code on Windows using pict/code's codeblock-pict, but when \r characters are left in the source, the rendering seems to randomly not show some characters.

As an example (not tested on Linux/Mac), the following code:

     #lang racket

     (require pict pict/code)
     (define example "#lang racket\r\n(define x 2)\r\nx")

     (codeblock-pict example)

Produces the following image

![Badly rendered](http://i.imgur.com/UcHCB6k.png)

whereas if I remove the carriage returns, I get

![Correctly rendered](http://imgur.com/p7x8G9L.png)

This was with Racket 6.6 running on Windows 7 x64. I have also experienced the same problem on Windows 10 x64, though have not tried adding carriage returns on Linux.

**Comment by stamourv** [comment]
Pushed a fix to the `pict` repo. If you update your installation of the `pict` package, the problem should go away.
