### ISSUE TITLE
Documentation bug in "Continue: Web Applications in Racket" (https://docs.racket-lang.org/continue/)

### ISSUE THREAD

**Issue by vlgajic** [racket/racket#1441]
Version: 6.6
Platform: MacIntel / Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
Severity: Non-critical
Class: Documentation bug

DESCRIPTION OF THE PROBLEM:

At the end of 
https://docs.racket-lang.org/continue/index.html#%28part._.Using_an_.S.Q.L_database%29
where it says:

And our application is:

#lang web-server/insta
 
(require "model-3.rkt")
 
....

it should include a note that the string on line 12 of the application should be "the-blog-data.sqlite" and not "the-blog-data.db" in case one interprets .... as invitation to copy and paste the application code from the end of the previous chapter, https://docs.racket-lang.org/continue/index.html#%28part._.A_.Persistent_.Model%29

Copy and paste of the application code without this change produces following exception:
Servlet (@ /servlets/standalone.rkt) exception:
table-exists?: file opened that is not a database file
  error code: 26
  database: #<path:/Applications/Racket v6.6/share/pkgs/web-server-lib/web-server/default-web-root/htdocs/the-blog-data.db>
  mode: 'create
  file permissions: (write read)

SEQUENCE OF STEPS TO REPRODUCE THE PROBLEM:

1) Copy and paste model code from the end of https://docs.racket-lang.org/continue/index.html#%28part._.Using_an_.S.Q.L_database%29
and save it as model-3.rkt

2) Copy and paste application code from the end of https://docs.racket-lang.org/continue/index.html#%28part._.A_.Persistent_.Model%29
and save it as app.rkt

3) Modify line 3 of app.rkt to be 
(require "model-3.rkt")
and save it

4) Run app.rkt

**Comment by vlgajic** [comment]
[racket-bug] all/15343

**Comment by jeapostrophe** [comment]
Thanks, fixed.

**Comment by Dongreen** [comment]
There was no need to change the name of the database file.
A sqlite database file can be named anything.  What is important to realize is that the sqlite file must be pre-built by the sqlite program. The sqlite database file that is generated is a binary file, not a text file which was the case in the case in Continue: Web Applications in Racket, Chapter 14, A Persistent Model.  In Chapter 14, Using an SQL database, the data file can have any name but it must be a binary sqlite binary data file.  Don.
