### ISSUE TITLE
Is `read-cdot` supposed to be left- or right- associative?

### ISSUE THREAD

**Issue by AlexKnauth** [racket/racket#1443]
@jeapostrophe 

With `read-cdot` turned on, should `a.b.c` read as `(#%dot (#%dot a b) c)` or `(#%dot a (#%dot b c))`? I would have expected `(#%dot (#%dot a b) c)`, because that's how field references normally behave. 

In a language where parens mean grouping, `a.b.c` would be `(a.b).c`.

However with the current implementation, it's the other one.

**Comment by bennn** [comment]
+1 for `(a.b).c`

**Comment by jeapostrophe** [comment]
The interpretation is on purpose. You can see that in the default implementation of `#%dot` --- https://github.com/jeapostrophe/remix --- the `a` binding is a "dot-transformer" that looks over the rest of the binding and interprets it. In fact, the default binding flattens any sequences of dots into `(#%dot a b c)` so that `a` can see the whole context and expand appropriately.

**Comment by AlexKnauth** [comment]
So this is okay because remix flattens it? But what about other languages that would want to use this?

For example languages that define `#%dot` to transform `a.f` into `(f a)` or something would want `a.string->number.factorial.write` to transform into `(write (factorial (string->number a)))`. Other languages that define `#%dot` to transform `a.x` into `(hash-ref a 'x)` would want `a.x.y.z` to transform into `(hash-ref (hash-ref (hash-ref a 'x) 'y) 'z)`. 

And `remix`'s `#%dot` form would just need a rule where `(#%dot (#%dot a x) y)` would recognize that `(#%dot a x)` isn't a dot-transformer, so it would flatten it to `(#%dot a x y)`, which it would have ended up doing anyway.

**Comment by bennn** [comment]
If it is on purpose, then it should be documented. C-style is left-to-right associativity.
(e.g. Table 2-1 on p51 of [K&R](https://hassanolity.files.wordpress.com/2013/11/the_c_programming_language_2.pdf))

**Comment by jeapostrophe** [comment]
It just so happens to flatten it for struct accessors. Other languages can expand it however they want.

It is documented.

http://docs.racket-lang.org/reference/reader.html?q=cdot#%28part._parse-cdot%29

**Comment by AlexKnauth** [comment]
That doesn't specify whether it's left- or right- associative, it only gives a low-level process that may or may not produce something that makes sense. *Other* language implementors will be expecting left-associativity, and that low-level explanation won't undo that expectation for them.

**Comment by jeapostrophe** [comment]
It clearly says that it reads X then DOT then reads Y and turns it into `(#%dot X Y)`.

So if you read "X.Y.Z" then you get X, then DOT, then you read "Y.Z" so you get `(#%dot Y Z)`, so you get `(#%dot X (#%dot Y Z))`

If you think you can make it more clear, submit a pull request.

cdot follows the racket principle of things on the left/above determining the interpretation of things to the right/below. `(#%dot X (#%dot Y Z))` lets `X` control what the inner `#%dot` means.

**Comment by AlexKnauth** [comment]
> It clearly says...

Someone with a left-associative bias in their heads (from every other language, and from their hopes as a language implementor) would interpret that as meaning it reads X then DOT then Y and turns it into `(#%dot X Y)`, then DOT then Z, and turning that into `(#%dot (#%dot X Y) Z)`. So it doesn't clearly say * **THIS IS RIGHT-ASSOCIATIVE WHICH IS PROBABLY NOT WHAT YOU EXPECTED** *.

> The racket principle of things on the left/above determining the implementation of things to the right/below

If I'm a language implementor whose never heard of your `remix`, I won't be thinking of dot-transformers. I'll be thinking of the value of the `X` controlling what the `Y` means (through dynamic dispatch or something similar), and then of the value of `X.Y` controlling what the `Z` means.

```racket
(define-syntax-rule (#%dot obj (method-id arg ...))
  (send obj method-id arg ...))
```
This seems to work perfectly fine...
```racket
my-object.(m x y)
```
Yay!!! The value of `my-object` determined what the `m` meant, and the combination of the two determined what `my-object.(m x y)` meant.
```racket
my-object.(m1 x y)
  .(m2 x y)
  .(m3 x y)
```
```
. m1: unbound identifier in module in: m1
```

Um... What? 
```racket
(define m1 #f)
(define m2 #f)
(define m3 #f)
...
my-object.(m1 x y)
  .(m2 x y)
  .(m3 x y)
```
```
. . ../../Applications/Racket/2016-08-30/Racket v6.6.0.4/collects/racket/private/class-internal.rkt:4610:0: send: no such method
  method name: #%dot
```
Again, I've never heard of remix, I'm just a language implementor. All I wanted a simple rule for converting `o.(m x ...)` into `(send o m x ...)`, and the documentation *never told me* that it was going to behave differently from how it always does in every other language.

**Comment by jeapostrophe** [comment]
This talk of `associativity` makes no sense to me. There is no operator parsing, precedence, associativity, etc. `read-cdot` enables the following behavior of `read`: After `read`ing a datum, call it X, if the next non-whitespace character is `.`, then call `read` again and call it Y, then return `(#%dot X Y)`. This recursive specification clearly implies that any additional dots would be found during the `read` of Y.

**Comment by rfindler** [comment]
I think "clearly implies" is the only thing that's being disagreed with
here. Why not write the docs for people (and all their baggage) instead of
machines (or "clean slate" people)?

**Comment by jeapostrophe** [comment]
A) Alex can propose a change.

B) Read the rest of that page and see if my docs don't fit the style:

"Racket’s reader is a recursive-descent parser that can be configured through a readtable and various other parameters. This section describes the reader’s parsing when using the default readtable." 

1.3.8 - "When the reader encounters ', it recursively reads one datum and forms a new list containing the symbol 'quote and the following datum."

1.3.9 - "A #| starts a nestable block comment. When the reader encounters #|, it skips past all characters until a closing |#. Pairs of matching #| and |# can be nested."

The documentation for the reader doesn't give a grammar, precedence rules, etc; it describes the reading algorithm. One improvement to match the style would be to use the word "datum" rather than "value".

**Comment by jeapostrophe** [comment]
Alex. I think I am blinded by having written it. Can you suggest a few tweaks to the text to improve how it reads?

**Comment by AlexKnauth** [comment]
Some examples would go a long way. If you just give an example that `x.y` reads equal to `(#%dot x y)`, and that `x.y.z` reads equal to `(#%dot x (#%dot y z))` that would help a lot.

**Comment by AlexKnauth** [comment]
Would it be a bad idea to change the implementation to match expectations though?

**Comment by rfindler** [comment]
@AlexKnauth maybe you have time to add some examples yourself? Or try to experiment with the implementation to see how the various things that Jay has built on top of #%cdot go wrong or don't go wrong with the change you have in mind?

**Comment by AlexKnauth** [comment]
Where should I put tests for the `read-cdot` option?
