### ISSUE TITLE
dynamic-require segfault

### ISSUE THREAD

**Issue by andmkent** [racket/racket#1445]
file1.rkt:
```racket
#lang racket

(provide is-equal?)

(define-syntax is-equal? (make-rename-transformer #'eq?))
```

file2.rkt:
```racket
#lang racket/base

(define is-equal? (dynamic-require "file1.rkt" 'is-equal?))

(is-equal? 42 43)
```

```racket file2.rkt``` produces a segfault on my machine w/ these files (Racket v6.6.0.4, OS X 10.11.6).

**Comment by andmkent** [comment]
Here's the OS X error info (running/crashing 'file2.rkt' from DrRacket) in case it's useful:
https://gist.github.com/andmkent/718a02b2eaffea031b139f836eec4dc8

**Comment by samth** [comment]
Here's a single-file version that crashes:

#lang racket/load

(module m1 racket/base
  (require (for-syntax racket/base))
  (provide f)
  (define-syntax f (make-rename-transformer #'values)))

(module m2 racket/base
  (define f (dynamic-require ''m1 'f))
  (f))

(require 'm2)

Adding the `'not-free-identifier=?` syntax property makes the crash go away.

And here's the line that does, in module.c, line 1283:

```
	                      if (SCHEME_FALSEP(srcm2->me->rt->provide_srcs[j])
```

**Comment by samth** [comment]
This patch fixes the immediate problem, and follows the pattern from earlier in the same function, but I don't know what's going on well enough to know if it's the right thing:

```
diff --git a/racket/src/racket/src/module.c b/racket/src/racket/src/module.c
index 3d67114..2e2e5c3 100644
--- a/racket/src/racket/src/module.c
+++ b/racket/src/racket/src/module.c
@@ -1280,7 +1280,8 @@ static Scheme_Object *_dynamic_require(int argc, Scheme_Object *argv[],
                     srcm2 = module_load(srcmname, env, errname);
 
                     for (j = srcm2->me->rt->num_var_provides; j--; ) {
-                      if (SCHEME_FALSEP(srcm2->me->rt->provide_srcs[j])
+                      if (srcm2->me->rt->provide_srcs
+                          && SCHEME_FALSEP(srcm2->me->rt->provide_srcs[j])
                           && SAME_OBJ(srcname, srcm2->me->rt->provide_src_names[j])) {
                         /* simple re-export applies: */
                         srcm = srcm2;
```

**Comment by mflatt** [comment]
Thanks for the report!
