### ISSUE TITLE
read-cdot consumes whitespace after everything even when there is no dot

### ISSUE THREAD

**Issue by AlexKnauth** [racket/racket#1454]
I would expect this program to return `#\newline` just as it does without `read-cdot` turned on.

``` racket
#lang racket
(parameterize ([read-cdot #true])
  (define in (open-input-string "a\n    b"))
  (read in)
  (read-char in))
```

But instead it returns `#\b`. Should the `read-cdot`-true reader be changed to peek through whitespace instead of consuming it?

**Comment by samdphillips** [comment]
This is the documented behavior.
https://docs.racket-lang.org/reference/reader.html?q=read-cdot#%28part._parse-cdot%29

> Finally, after reading any datum x, the reader will seek through whitespace and comments and look for zero or more sequences of a . followed by another datum y.

**Comment by jackfirth** [comment]
The "seek through whitespace" bit doesn't imply to me that the input is consumed even if no dots are found. I would expect it to do what Alex is suggesting: peek ahead and only consume if it actually finds dots.

**Comment by samdphillips** [comment]
Peeking through the history @AlexKnauth is the one who wrote the doc (17db8e57f0f38) so they have a better grasp on this than me :)

**Comment by mflatt** [comment]
I'm going to improve the documentation to replace "seek through" with "consume". Peeking arbitrarily far in a stream is not a great property for a parser, and I don't think we should introduce that behavior.
