### ISSUE TITLE
Should `jsexpr?` return `#f` for bad json? 

### ISSUE THREAD

**Issue by ntdef** [racket/racket#1455]
I was using the `json` library and noticed that `(jsexpr? "gibberish")` returns `#t`. I realize that this would break behavior for some, but shouldn't it return false if the data provided is not valid json? Currently, there's no way to check that a piece of data is valid json, and `jsexpr?` doesn't guarantee that data will behave like json correctly. 

Is it worth writing a PR for this?

**Comment by jbclements** [comment]
My reading of the docs is that "gibberish" is a perfectly valid jsexpr. Perhaps I'm misunderstanding you?

**Comment by ntdef** [comment]
Certainly it's clear from the docs since any string is a valid jsexpr. I'm
just questioning whether that's optimal behavior.

Then again I am very new to Racket so I may not be familiar with how
predicates are supposed to work.

**Comment by jbclements** [comment]
Let me take a guess... are you looking for a predicate that tells you whether 'string->jsexpr' will signal an error on some input? In that case, the best I've got for you is

```racket
#lang racket

(require json)


(define (valid-json-string? s)
  (with-handlers ([exn:fail? (λ (exn) #f)])
    (string->jsexpr s)
    #t))


(valid-json-string? "gibberish")
```

**Comment by jbclements** [comment]
I think you're confusing the jsexprs with their json encodings?

Specifically, 

"gibberish"

is a jsexpr whose json encoding is 

"\"gibberish\""

Let me know if I'm still not understanding you.

**Comment by ntdef** [comment]
Ah, I think I understand now: a `jsexpr` enumerates the possible Racket datatypes that can be encoded into json values, and `jsexpr?` asks whether such a thing can be encoded as json. 

As for `valid-json-string`, yes I was aware of the `with-handlers` function, and that's what I've been using. I was just puzzled by the purpose of `jsexpr?`.

**Comment by jbclements** [comment]
Probably the most common use for `jsexpr?` would be as a contract. So, for instance, I'm writing a function that accepts a number and produces a piece of data that's going to be sent over the wire as json. The most reasonable contract for this thing would probably have `jsexpr?` in the positive position, like this:

```racket
(-> number? jsexpr?)
```

**Comment by jbclements** [comment]
okay if I close this?

**Comment by ntdef** [comment]
Makes sense! Yes go ahead and close.
