### ISSUE TITLE
help doesn't goto the specific anchor on Mac OS X 10.11

### ISSUE THREAD

**Issue by xuchunyang** [racket/racket#1459]
Hello! I am new to Racket. 

I find that `(help for/list)` open the correct page but doesn't jump to the `for/list` section.

```
~ $ racket
Welcome to Racket v6.6.
-> (help for/list)
Loading help index...
Sending to web browser...
  file: /Applications/Racket v6.6/doc/reference/for.html
  anchor: (form._((lib._racket/private/base..rkt)._for/list))
```

The web browser (it's Chrome in my case) opens

```
file:///Applications/Racket%20v6.6/doc/reference/for.html 
```

but I expect

```
file:///Applications/Racket%20v6.6/doc/reference/for.html#(form._((lib._racket/private/base..rkt)._for/list))
```

**Comment by ntdef** [comment]
Hm. I just tested this on OSX 10.11 with Chrome and it works for me, jumping straight to the `for/list` documentation. Maybe try a racket session on another computer if possible to double check your setup?

**Comment by xuchunyang** [comment]
I just notice it works if web browser is not already opened, otherwise, the anchor part will not be passed to the web browser.

**Comment by sorawee** [comment]
On my computer (Mac 10.15.4), `(help for/list)` now links to the correct anchor whether or not web browser is already opened. Can you still reproduce the bug, @xuchunyang?

**Comment by xuchunyang** [comment]
> Can you still reproduce the bug

No, I can't reproduce with Racket 7.6 and macOS 10.15.
