### ISSUE TITLE
syntax/loc and friends should accept non-syntax object source locations

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#1463]
The `syntax/loc` and `quasisyntax/loc` forms should accept the same sorts of arguments that `datum->syntax` does for the source location, including lists and vectors. Currently, it only accepts syntax objects.

**Comment by AlexKnauth** [comment]
I believe this is the code that would have to change:
https://github.com/racket/racket/blob/master/racket/collects/racket/private/stxloc.rkt#L38-L45
```racket
(-define (relocate loc stx)
  (if (or (syntax-source loc)
          (syntax-position loc))
      (datum->syntax stx
                     (syntax-e stx)
                     loc
                     stx)
      stx))
```
The only thing that would have to change would be the `(or (syntax-source loc) (syntax-position loc))` condition. I'm guessing it's purpose is something analogous to the [`source-location-known?`][source-location-known?] function in `syntax/srcloc`. 

  [source-location-known?]: http://docs.racket-lang.org/syntax/Source_Locations.html#%28def._%28%28lib._syntax%2Fsrcloc..rkt%29._source-location-known~3f%29%29

**Comment by spdegabrielle** [comment]
is this still an issue?  Please consider adding the label `good first issue` so it is findable: 

[Issues labeled `good first issue` in in Racket GitHub repositories](https://github.com/search?q=type:issue+org:racket+state:open+label:%22good+first+issue%22)
