### ISSUE TITLE
Racket on PowerPC (FreeBSD)?

### ISSUE THREAD

**Issue by alehed** [racket/racket#1471]
Is there a reason why Racket currently doesn't support the PowerPC architecture on FreeBSD? 
I noticed that PowerPC is supported on other operating systems. If it's simply a matter of configuration I can also try to fix it myself.

I know that FreeBSD doesn't have that many users so I understand if porting is not a priority.

**Comment by jcmdln** [comment]
There is a Unix variant on the downloads page, did you attempt to install it? If so, what errors did you get?

**Comment by alehed** [comment]
Actually I installed it directly from freebsd ports (compiled it from source).
As you can see in sconfig.h freebsd on ppc gives a "Unported platform" error.

On 30 Sep 2016, at 00:03, jcmdln <notifications@github.com<mailto:notifications@github.com>> wrote:


There is a Unix variant on the downloads page, did you attempt to install it? If so, what errors did you get?

**Comment by juanfra684** [comment]
Probably, you want also to add the line: `#define MZ_USE_JIT_PPC`.

Did you try to run DrRacket? Everything works fine?.

If possible, can you run the tests and to copy/paste the output?:
```
$ racket -e '(eval-jit-enabled)'
$ raco pkg install --auto -u racket-test-core
$ cd ~/.racket/$(racket -e '(display (version))')/pkgs/racket-test-core/tests/racket/
$ racket -f quiet.rktl
```
