### ISSUE TITLE
Force HTTPS on the racket-lang.org website

### ISSUE THREAD

**Issue by nullchinchilla** [racket/racket#1475]
HTTPS should probably be forced on on the racket-lang.org website, as it does seem to support HTTPS, though through CloudFlare, which doesn't actually give you end-to-end security. Currently, there's no way to be sure that I'm visiting the real racket-lang.org, and this is pretty bad especially for a language runtime, where a hidden rootkit can possibly plant hard-to-detect backdoors in everything that `raco` compiles.

The link to download.racket-lang.org does have HTTPS, but it can easily (and automatically with tools like SSLStrip) be replaced to link to the HTTP version by an attacker.

Of course, there are things like Linux distribution repositories that have strong security, and I do use them, but it would be nice if downloading from racket-lang.org were to be trustworthy. Sorry if this sounds paranoid, but I do use Racket to develop some rather security-sensitive software, and making sure dependencies are trustworthy is very important.

**Comment by pmatos** [comment]
It seems like `racket-lang.org` redirects always to `https`, which seems to be what this is about so I would say this is fixed.
