### ISSUE TITLE
Contract errors should include the line number of the error itself

### ISSUE THREAD

**Issue by jgarvin** [racket/racket#1476]
Racket strangely appears to only give line numbers for "context" around the contract error and not a line number for the error itself.

Take this snippet from the beautiful racket tutorial, in which I have deliberately changed the call to first inside handle-args to mistakenly act on arg instead of stack-acc:

```
#lang br/quicklang

(define (handle-args . args)
  (for/fold ([stack-acc empty])
            ([arg (filter-not void? args)]) ;; why would any be void?
    (cond
      [(number? arg) (cons arg stack-acc)]
      [(or (equal? + arg) (equal? * arg))
       (cons (arg (first arg) (second stack-acc)) (drop stack-acc 2))])))
(provide handle-args)

(define (read-syntax path port)
  (define args (port->lines port))
  (define args-datums (format-datums '~a args))
  (define module-datum `(module stacker-mod "funstacker.rkt"
                          (handle-args ,@args-datums)))
  (datum->syntax #f module-datum))

(provide read-syntax)

(define-macro (stacker-module-begin HANDLE-EXPRESSION)
  #'(#%module-begin
     (display (first HANDLE-EXPRESSION))))

(provide (rename-out [stacker-module-begin #%module-begin]))

(provide + *)
```

Which functions as a language for this file:

```
#lang reader "funstacker.rkt"
4
8
+
3
*
```

This is the error you get:

```
first: contract violation
  expected: (and/c list? (not/c empty?))
  given: #<procedure:+>
  context...:
   /home/prophet/work/editor/funstacker.rkt:4:2: for-loop
   /home/prophet/work/editor/funstacker-test.rkt: [running body]
```

The line number of the for loop is not particularly helpful, especially if there were more than one call to first. This also means that if you want to use emacs or another editor to jump to the line that is the problem based on the output from the compiler that it will jump to the wrong line.

**Comment by stamourv** [comment]
The stack trace you're seeing is the result of the runtime's best effort at reconstructing a stack trace from optimized code.
If you want better stack traces, you can run your programs using `racket -l errortrace -t my-program.rkt` or by enabling "debugging and profiling" in DrRacket. Errortrace adds annotations to the compiled code that make it possible to have better stack traces, but at the cost of performance.

**Comment by rfindler** [comment]
Probably you want "debugging" not "debugging and profiling" (that setting is the default in DrRacket).
