### ISSUE TITLE
'file-or-directory-permissions' throws system error when the target is mounted as read-only

### ISSUE THREAD

**Issue by iyzsong** [racket/racket#1478]
Run in shell:

``` sh
mkdir /tmp/test
sudo mount -t tmpfs -o ro _ /tmp/test
racket -e '(file-or-directory-permissions "/tmp/test")'
```

Give:

``` sh
file-or-directory-permissions: access failed
  path: /tmp/test
  system error: Read-only file system; errno=30
```

I except it should be:

``` sh
'(execute read)
```

And sometimes a normal user can get the desired result while root won't.
For example, see `/gnu/store` in this screenshot:
![file-or-directory-permissions](https://cloud.githubusercontent.com/assets/22543694/19029763/a17caeb4-897b-11e6-8faa-42e3dcdda6f5.png)

**Comment by mflatt** [comment]
Thanks for the report!
