### ISSUE TITLE
Documentation for identifier-binding does not reflect behavior

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#1485]
The documentation for `identifier-binding` states the following:

> If `'lexical` is produced for any _`phase-level`_ value, then it is produced for all _`phase-level`_ values.

This seemed wrong to me—why should the above be the case?—so I tried it out. Indeed, the actual behavior of `identifier-binding` does not reflect that at all. Is the documentation incorrect or outdated, or is the implementation wrong in some way?

(I’d actually be sort of interested to know why that line is in the documentation at all, since I’m sure there’s _some_ reason it was written, but that’s more a curiosity than anything else.)

**Comment by mflatt** [comment]
That claim was true for the old macro system, but it isn't true anymore. I'll fix the docs.
