### ISSUE TITLE
with-intercepted-logging only intercepts logs sent to current-logger

### ISSUE THREAD

**Issue by bennn** [racket/racket#1486]
Because of [L45](https://github.com/racket/racket/blob/master/racket/collects/racket/logging.rkt#L45) in `racket/logging.rkt`, the function `with-intercepted-logging` can only intercept logs sent to the `(current-logger)` parameter.

And so the following program (adapted from the [docs](http://docs.racket-lang.org/reference/logging.html#%28def._%28%28lib._racket%2Flogging..rkt%29._with-intercepted-logging%29%29)) returns 0, but I was expecting 2.

```
#lang racket
(require racket/logging)

(let ([warning-counter 0]
      [l (current-logger)])
 (with-intercepted-logging
  (lambda (l)
   (when (eq? (vector-ref l 0)
          'warning)
    (set! warning-counter (add1 warning-counter))))
  (lambda ()
   (log-message l 'warning "Warning!" (current-continuation-marks))
   (log-message l 'warning "Warning again!" (current-continuation-marks))
   (+ 2 2))
  'warning)
 warning-counter)
;; 0
```

Also, this means `with-intercepted-logging` won't intercept any logs from functions created by `define-logger`.

Is it possible to change the implementation of `with-intercepted-logging` to intercept any log event that would be received by a `(make-log-receiver (current-logger) ....)` declared _outside_ the dynamic extent of `proc`?

**Comment by stamourv** [comment]
I don't have the details of the logging system paged in, but I remember there being a lot of subtlety there.
The solution you're suggesting seems to conflict the design goal of `with-intercepted-logging`, which is to catch log messages from the thunk passed to it only, and would break backwards compatibility, I believe.
It looks like your use case would be satisfied by adding a keyword argument to specify which logger to listen to. Would that satisfy the actual use case you have (presumably in some larger program)?

**Comment by bennn** [comment]
Just read the commit --yeah that's perfect.

I wanted a program like this to print "intercepted"
```
#lang racket/base
(require racket/logging)

(define-logger custom)

(with-intercepted-logging
  (λ (l) (displayln "intercepted"))
  (λ () (log-custom-warning "hello"))
  'warning)
```
