### ISSUE TITLE
free-id-table-ref! with procedure "failure" argument stores the procedure, not its result

### ISSUE THREAD

**Issue by jsmaniac** [racket/racket#1497]
Racket version: 6.7.0.1

The documentation states that `free-id-table-ref!` works like `hash-ref!` and that `free-id-table-map` works like `hash-map`. However, when given a proc `failure` argument, `free-id-table-ref!` calls the procedure and returns its result, but incorrectly stores the procedure itself in the table, instead of storing the value returned by the procedure.

`bound-id-table-ref!` has the same incorrect behaviour.

```
#lang racket
(require syntax/id-table syntax/id-set)
(define tbl1 (make-free-id-table))
(free-id-table-ref! tbl1 #'id (λ () 42)) ;; Prints 42
(free-id-table-map tbl1 cons) ;; Prints '((#<syntax id> #<procedure>))

(require syntax/id-table)
(define tbl2 (make-bound-id-table))
(bound-id-table-ref! tbl2 #'id (λ () 42)) ;; Prints 42
(bound-id-table-map tbl2 cons) ;; Prints '((#<syntax id> #<procedure>))

(require syntax/id-table)
(define tbl3 (make-hash))
(hash-ref! tbl3 #'id (λ () 43)) ;; Prints 43
(hash-map tbl3 cons) ;; Prints '((#<syntax id> 43))
```

**Comment by AlexKnauth** [comment]
This is the relevant code:
https://github.com/racket/racket/commit/456a72a36c37a474e47d1b1c72df37b8167886ac#diff-140cdb4821379213ccc46e0f6054bd7bR163

```racket
(define missing (gensym 'missing))
(define (id-table-ref! who d id default identifier->symbol identifier=?)
  (define entry (id-table-ref who d id missing identifier->symbol identifier=?))
  (cond [(eq? entry missing)
         (id-table-set! who d id default identifier->symbol identifier=?)
         (if (procedure? default) (default) default)]
        [else entry]))
```

**Comment by jsmaniac** [comment]
@AlexKnauth Thanks! I pushed a patch, will open a PR in a minute.
