### ISSUE TITLE
Dr Racket - Non-integer numbers in student languages show up as one character

### ISSUE THREAD

**Issue by Calvinp** [racket/racket#1507]
**Dr. Racket version** - 6.7
**OS** - Reproduced on Windows and Fedora Linux
**Language** - Any student language (This does not occur in Racket, only the student languages)
**Issue** - When I type a non-integer number into Dr. Racket interactions in one of the student languages, and press enter, the number returned is formatted as one character.
I can copy/paste it, and pasting it into anything that isn't Dr. Racket results in a normal string. However, I can't move the cursor inside it, pressing backspace deletes the entire number, and individual digits cannot be changed. It also shows up black when regular numbers show up green. Finally, when selected it shows up as a blank white box (screenshot at the bottom). All mathematical operations still work as expected on these numbers.

In this screenshot, I typed 43.2424244 on line 3 and on the right in the check-expect. On the left in the check-expect and in line 2, I copy-pasted the number from interactions. The check-expect passes.
![racket-weirdness](https://cloud.githubusercontent.com/assets/3210505/19995171/3a633248-a22b-11e6-9bd2-842caddcb136.png)

Screenshot of them selected:
![racketweirdnessselected](https://cloud.githubusercontent.com/assets/3210505/19995246/c85e63a6-a22b-11e6-9bbb-c7861f56180f.png)

**Comment by rfindler** [comment]
A few comments:

0) this does happen in all of the languages, but perhaps it is easier to come across in the teaching languages. In general, DrRacket uses special, non-textual handling for any number that is exact and isn't an integer, I believe.

1) the current strategy for implementing number printing in DrRacket is such that most of these issues aren't really fixable (without trying a new strategy). Fixable ones include the selection strangeness and the color, I believe, but probably not the others. Of course, we could experiment with alternative strategies.

2) the implementation of this is in a different repo. Here's a link to the file that contains most of it: https://github.com/racket/gui/blob/master/gui-lib/framework/private/number-snip.rkt

**Comment by rfindler** [comment]
Okay, I've fixed those two problems and I'm going to close this issue now, as I don't think that I'll make any attempts on a new strategy.

Feel free to reopen and/or discuss further if you'd like. Maybe something useful will come of it. I don't mean to end the conversation, just closing as I (currently) have no plans to do more with this.
