### ISSUE TITLE
F1 documentation always opens in new tab

### ISSUE THREAD

**Issue by BenChung** [racket/racket#1509]
The search-help-desk keybinding in DrRacket is very useful, searching the documentation for the identifier around the current cursor location. However, it opens the documentation in a new tab, which tends to cause a tab explosion. I would prefer if DrRacket would open the documentation in the same tab, and open a new tab if a different keyboard shortcut was used, allowing some measure of control over documentation tabs.

**Comment by rfindler** [comment]
This isn't the right repo. DrRacket is elsewhere, but DrRacket uses a library, found here: https://github.com/racket/scribble/blob/master/scribble-lib/help/search.rkt

That library uses another one to open an web page via `open` on the mac (are you using a mac?) which opens the new tab by default, IIUC. So I'm not sure of the right place to configure this, but it may be that you can do it via your OS. That other library, however, is here:

  https://github.com/racket/net/blob/master/net-lib/net/sendurl.rkt

Probably you want to open an issue on that repo. Or maybe submit a pull request there?
