### ISSUE TITLE
DrRacket not working in macOs 10.12.1

### ISSUE THREAD

**Issue by madhurakhal** [racket/racket#1512]
After updating my mac to latest version of macOs . DrRacket stops working. I try to solve by installing new version but it doesn't help.

I got this message while opening the application

> The application “DrRacket” can’t be opened.

Here is the log of the application

> default 16:39:20.861132 +0100 lsd SecTranslocateCreateSecureDirectoryForURL: created /private/var/folders/jf/d33vvzdd3gn47byqg3p41h740000gn/T/AppTranslocation/FA3FEA3F-13E9-4237-88C6-586214C253A2/d/DrRacket.app
default 16:39:26.998537 +0100 lsd SecTranslocate: problem deleting translocation after app death: /private/var/folders/jf/d33vvzdd3gn47byqg3p41h740000gn/T/AppTranslocation/FA3FEA3F-13E9-4237-88C6-586214C253A2/d/DrRacket.app
default 16:40:50.822935 +0100 lsd SecTranslocateCreateSecureDirectoryForURL: created /private/var/folders/jf/d33vvzdd3gn47byqg3p41h740000gn/T/AppTranslocation/DAA40117-6B16-425B-9F6C-0252EA4226FC/d/DrRacket.app
default 16:40:56.209748 +0100 lsd SecTranslocate: problem deleting translocation after app death: /private/var/folders/jf/d33vvzdd3gn47byqg3p41h740000gn/T/AppTranslocation/DAA40117-6B16-425B-9F6C-0252EA4226FC/d/DrRacket.app

![errorlog](https://cloud.githubusercontent.com/assets/839882/20144272/61e334ce-a69c-11e6-887d-86d0260181a5.png)

**Comment by shankm** [comment]
Try installing the 32-bit version instead of the 64-bit. It worked for me.

**Comment by mflatt** [comment]
Problems related to v10.12.1 are fixed in v6.8.
