### ISSUE TITLE
require/typed #opaque -> contract violation

### ISSUE THREAD

**Issue by acarrico** [racket/racket#1516]
As detailed in test case: https://gist.github.com/acarrico/850f9d7112104afd3e5a6dd916edf1ae
```
(require/typed "untyped.rkt"
  (#:opaque XPointer x-pointer?)
  (make-x (-> XPointer))
  (take-x (-> XPointer Void)))
```
Succeeds in Racket 6.2, fails with contract violation in 6.6, 6.7.

**Comment by AlexKnauth** [comment]
Could you move this issue to the [typed-racket](https://github.com/racket/typed-racket) repository?

**Comment by acarrico** [comment]
Moved to https://github.com/racket/typed-racket/issues/456
