### ISSUE TITLE
Can't link libracket3m.a?

### ISSUE THREAD

**Issue by ramadss** [racket/racket#1526]
I'm new to linux and gcc so I don't know what is the problem,sorry.
Tried to embed racket in C, so I followed this tutorial https://docs.racket-lang.org/inside/embedding.html ,generated `base.c` by running `raco ctool --c-mods base.c ++lib racket/base` and the code in the following `re.c` was copied from section `3m Embedding`. When I ran
```
gcc re.c -I /usr/include/racket -l racket3m -o re
```
I got
```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libracket3m.a(jitcommon.o): unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
```

I have no idea how to fix it. Could you please help me?

**Comment by mflatt** [comment]
Hi - I don't recognize that error. Pasting into into a web search suggests an issue with mixing versions of GCC or linking tools. Can you say more about how your distribution (e.g., some version of Debian) and how you compiled or installed Racket to get "libracket3m.a"?

**Comment by ramadss** [comment]
oh,thanks for the reply. I'm using Debian 8.6 and Racket was installed by apt-get. Now I have downloaded the source file then compiled it and that works. So actually I have solved the problem but forgot to close the issue, sorry :P
