### ISSUE TITLE
error msg from `->` less than helpful with `lambda` predicate

### ISSUE THREAD

**Issue by mbutterick** [racket/racket#1528]
This seems like a fiddly quibble. OTOH the whole point of contracts is fiddly quibbling. So here goes.

This function will produce an error report as shown below:

```racket
(define/contract (f arg)
  (zero? . -> . any/c)
  arg)
(f 42)
``` 

```
git/racket/racket/collects/racket/contract/private/blame.rkt:159:0: f: contract violation
  expected: zero?
  given: 42
  in: the 1st argument of
      (-> zero? any/c)
  contract from: (function f)
  blaming: anonymous-module
   (assuming the contract is correct)
  at: unsaved editor:2.18
``` 

But if we replace `zero?` with an equivalent `lambda` (and [the docs say](http://docs.racket-lang.org/reference/contracts.html?q=contract) “any procedure of arity 1” is a legitimate predicate):

```racket
(define/contract (g arg)
  ((λ (x) (zero? x)) . -> . any/c)
  arg)
(g 42)
``` 

In this case, the `lambda` predicate becomes `temp3` in the error:

```
git/racket/racket/collects/racket/contract/private/blame.rkt:159:0: g: contract violation
  expected: temp3
  given: 42
  in: the 1st argument of
      (-> temp3 any/c)
  contract from: (function g)
  blaming: anonymous-module
   (assuming the contract is correct)
  at: unsaved-editor:2.18
``` 

This is particularly confusing when there are multiple `lambda` predicates, because they all get `temp` names.

It seems like this would be improved by simply using the literal code for the `lambda` in the error message, for instance:

```
git/racket/racket/collects/racket/contract/private/blame.rkt:159:0: g: contract violation
  expected: (λ (x) (zero? x))
  given: 42
  in: the 1st argument of
      (-> (λ (x) (zero? x)) any/c)
  contract from: (function g)
  blaming: anonymous-module
   (assuming the contract is correct)
  at: unsaved-editor:2.18
```

**Comment by rfindler** [comment]
This is, in some sense, the same problem as with this program:

```
#lang racket
(define-syntax (m stx)
  (syntax-case stx ()
    [(_ e)
     (with-syntax ([(tmp) (generate-temporaries '(tmp))])
       #'(let ([tmp e]) tmp))]))

((m (λ (x) (zero? x))) 1 2)
```

What's happening is that the lambda expression is picking up the name from the binder that's hiding inside the macro definition. 

If there is a way to fix that macro (without removing the `let`), then I can fix the expansion of `->`.

**Comment by rfindler** [comment]
I guess that probably the inferred name process needs to be extended so that it can be told that some `let` that got introduced "doesn't count" so it can look for an outer one (or use the source location of the procedure like it does when there are no `let`s).

I would imagine a property on the `let` or on the variable in the `let`? 

Does this seem to be on the right track?

**Comment by samth** [comment]
I think this is already available, by using `(void)` as the `'inferred-name` property:

```
#lang racket
(define-syntax (m stx)
  (syntax-case stx ()
    [(_ e)
     (with-syntax ([(tmp) (generate-temporaries '(tmp))])
       #`(let ([tmp #,(syntax-property #'e 'inferred-name (void))]) tmp))]))

((m (λ (x) (zero? x))) 1 2)
```

**Comment by mbutterick** [comment]
I defer to @samth. This was my thought:

```racket
#lang racket
(define-syntax (m stx)
  (syntax-case stx ()
    [(_ e)
     (with-syntax ([(tmp) (generate-temporaries '(tmp))]
                   [name (syntax-case #'e ()
                           [(λ . body) #`'#,(string->symbol
                                             (format "~a" (syntax->datum #'e)))]
                           [else #''e])])
       #'(let ([tmp (procedure-rename e name)]) tmp))]))

((m (λ (x) (zero? x))) 1 2)
```

BTW I came across this problem in an attempt to demonstrate how [wonderful and helpful](http://beautifulracket.com/explainer/contracts.html) the contract system is :wink:

**Comment by mbutterick** [comment]
PS While we're here, I've never understood the perma-caveat `(assuming the contract is correct)`. Is it possible for the contract system to have some different inference about the correctness of the contract (which would alter this caveat)? Or is it just a general warning that faulty contracts lead to faulty results? (If so, this seems true of all code, all the time, and thus unnecessary to mention)

**Comment by rfindler** [comment]
No, that doesn't work. This program should produce `x` in the error message, not just `#<procedure>`

```
#lang racket
(define-syntax (m stx)
  (syntax-case stx ()
    [(_ e)
     (with-syntax ([(tmp) (generate-temporaries '(tmp))])
       #`(let ([tmp #,(syntax-property #'e 'inferred-name (void))])
           tmp))]))

((let ([x (m (λ (x) (zero? x)))]) x) 1 2)
```

and similarly, this program should print a lambda expression with a source location in it:


```
#lang racket
(define-syntax (m stx)
  (syntax-case stx ()
    [(_ e)
     (with-syntax ([(tmp) (generate-temporaries '(tmp))])
       #`(let ([tmp #,(syntax-property #'e 'inferred-name (void))])
           tmp))]))

((m (λ (x) (zero? x))) 1 2)
```

(This latter one is the closer equivalent to MB's original program.)

**Comment by samth** [comment]
I agree that the first example isn't as good as it could be, but the second one works for me the way I think @mbutterick wanted:

```
[samth@huor:~ plt] cat /tmp/zzz.rkt 
#lang racket
(define-syntax (m stx)
  (syntax-case stx ()
    [(_ e)
     (with-syntax ([(tmp) (generate-temporaries '(tmp))])
       #`(let ([tmp #,(syntax-property #'e 'inferred-name (void))])
           tmp))]))

((m (λ (x) (zero? x))) 1 2)
[samth@huor:~ plt] r /tmp/zzz.rkt 
/tmp/zzz.rkt:9:4: arity mismatch;
 the expected number of arguments does not match the given number
  expected: 1
  given: 2
  arguments...:
   1
   2
  context...:
   /tmp/zzz.rkt: [running body]
```

Note that in DrRacket, I had to save the definitions window to get the source location.

**Comment by stamourv** [comment]
@mbutterick: Re perma-caveat: I read it as the latter, as a reminder that when there's a mismatch between specification and implementation, it may be the specification that's wrong. You're right that this is true of all code, but a helpful reminder that specifications are code, too, can't hurt. :)

**Comment by mflatt** [comment]
@rfindler The existing way to handle those examples is to use `syntax-local-name` or `syntax-local-infer-name` explicitly in the macro implementation.

Something more automatic from the macro expander seems tricky, if I understand, since the expander would have to inspect the body of the `let` and perform a kind of copy propagation before expanding the right-hand side (so that it sets up a name for reference via `syntax-local-name`, for example). Maybe it's related to the general problem of fusing the compiler, optimizer, and expander.

**Comment by mbutterick** [comment]
>  but the second one works for me the way I think @mbutterick wanted:

Not that “what I want” matters. But your error prints the function as

```/tmp/zzz.rkt:9:4: arity mismatch;```

This is more specific than `temp4`. But still different than my suggestion, which is to print`(λ (x) (zero? x))`. IMO this would be the behavior most closely analogous to what happens when you use a self-contained predicate like `zero?`.

**Comment by samth** [comment]
@mbutterick Racket doesn't hold on to the source code at run time for functions, so printing that would be a much bigger change. The printer uses `object-name` on the function, which uses the source location if no name is available. `zero?` is the name of a function, not the source code you're using, in this example.

**Comment by rfindler** [comment]
@mflatt: ah, okay. I should have thought of that other approach!

**Comment by rfindler** [comment]
@samth, thanks! I'll push that fix.

**Comment by rfindler** [comment]
I've found a bunch of places where the contract system does this wrong and fixed them, but if there are more that I'm missing that you come across, please let me know.
