### ISSUE TITLE
compilation hangs and can't be killed (when extracting body of fully-expanded #%module-begin)

### ISSUE THREAD

**Issue by jsmaniac** [racket/racket#1538]
When compiling the file below using `raco make file.rkt` or just `racket file.rkt`, the process hangs, consuming 100% CPU. It can't be terminated with <kbd>Ctrl</kbd>+<kbd>C</kbd>, and has to be killed with `killall -KILL raco` or `killall -KILL racket`.

The code works fine if the language of `a-submod` is changed from `racket/base` to `typed/racket/base` (leaving the outer `foo` module's language and meta-language intact). It also fails with `typed/racket/base` for the submodule when the value of `x` is not used.

This code comes from [@mflatt's answer to my question on the mailing list](https://groups.google.com/d/msg/racket-users/zpe27qAdHG0/iWWdxpuZEAAJ). I believe this is a bug, as the compilation should not hang, and instead should succeed or produce an error message.

Racket version: v6.7.0.3 (I'll try with a newer version soon).

```
#lang racket

;; The language definition
(module mylang racket
  (provide (rename-out [-#%module-begin #%module-begin]))
  (define-syntax (-#%module-begin stx)
    (syntax-case stx ()
      [(_ lng . rest)
       (with-syntax ([#%module-begin (datum->syntax #'lng '#%module-begin)])
         #`(#%plain-module-begin
            (require lng)
            (continue #%module-begin . rest)))]))
  (define-syntax (continue stx)
    (syntax-case stx ()
      [(_ lang-module-begin . rest)
       (let ([body-stx (local-expand
                        #'(lang-module-begin . rest)
                        'module-begin
                        (list))])
       ;; pattern-match on the #%plain-module-begin form to insert a require
       (syntax-case body-stx (#%plain-module-begin)
         [(#%plain-module-begin . mod-body)
          #`(begin
              .
              #,((make-syntax-introducer) #'mod-body))]))])))

;; A module using that language
(module foo (submod ".." mylang) racket/base
  (module a-submod racket/base
    (define x 1)
    (provide x))
  (require 'a-submod)
  (+ x 1))
(require 'foo)
```

**Comment by mflatt** [comment]
This is a crashing bug in the expander. I'll push a repair soon. Meanwhile, I don't see an easy workaround, but I can look harder if you need one.

**Comment by jsmaniac** [comment]
@mflatt I can wait for the repair, this is not an urgent change on my side :). Thanks!
