### ISSUE TITLE
Changes to ->i changed behavior with contracts on optional arguments; broke gregor

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#1539]
This program works on Racket 6.7:

```racket
#lang racket

(define/contract (foo [x #f] [y #f])
  (->i ()
       ([x integer?]
        [y (x) (>=/c x)])
       [result any/c])
  (void))

(foo)
```

However, it no longer works on HEAD. Instead, it produces the following error:

```
>=/c: contract violation
  expected: real?
  given: #<unsupplied-arg>
```

Specifically, the old behavior for `->i` was to not evaluate contracts at all for arguments not supplied. This seems like the right behavior, especially for by-position arguments, since it saves work, and contracts will be able to rely on the by-position arguments before them existing. The new behavior evaluates *all* contracts whether the argument was provided or not, and it supplies `the-unsupplied-arg` for unprovided optional arguments.

The documentation does not seem to specify the behavior here, but the `gregor` package relies on the old behavior, and it no longer works on HEAD. It seems like the right thing to do here is to preserve the old behavior, since this change seems likely unintentional.

**Comment by rfindler** [comment]
Yes, definitely a bug. Thank you for pointing it out! I should have a fix before too long.

**Comment by rfindler** [comment]
FWIW, I am beginning to doubt that the behavior that you describe about contracts that depend on unsupplied arguments/results. I see also that, although this case worked before (and now works again), there are others that don't (and didn't before). I guess we're committed to this path now, tho.

**Comment by rfindler** [comment]
(And I should say that the behavior you describe is also the behavior I intended!)

**Comment by rfindler** [comment]
Oh, wait! No, I am confused. You explained it right, but I was thinking wrong. I'll update the docs.

**Comment by lexi-lambda** [comment]
Thanks for the quick fix! And also thank you for the documentation clarification. :)
