### ISSUE TITLE
Can not debug Typed Racket

### ISSUE THREAD

**Issue by EFanZh** [racket/racket#1546]
OS: Windows 10 64-bit
Version: 6.7 64-bit

When I click Debug button in DrRacket, I got the following error:

    ..\..\Program Files\Racket\collects\racket\private\pre-base.rkt:191:39: module: cannot use identifier tainted by macro transformation in: module

As long as the first line of the source file is `#lang typed/racket`, I can not execute the debug command successfully.

Not sure if this issue belongs to [this project](https://github.com/racket/racket), [DrRacket project](https://github.com/racket/drracket) or [Typed Racket](https://github.com/racket/typed-racket) project.

**Comment by sorawee** [comment]
@EFanZh Is this still an issue? With Racket 7.6, I tried a simple program:

```
#lang typed/racket

(+ 1 1)
```

and it works fine with the debug command.

**Comment by EFanZh** [comment]
I can confirm that debugging works for Typed Racket in DrRacket now.
