### ISSUE TITLE
drracket is not working on wayland

### ISSUE THREAD

**Issue by soulomoon** [racket/racket#1547]
I upgrade my system to fedora 25 from fedora 24, and now it is wayland default, and I try to open drracket and it gaves me an error
`(drracket:2986): Gdk-WARNING **: gdkwindow-x11.c:5573 drawable is not a native X11 window
Window->C: argument is not non-null `Window' pointer
  argument: #f
  context...:
   /home/soulomoon/Downloads/racket/collects/ffi/unsafe.rkt:1246:12
   /home/soulomoon/Downloads/racket/share/pkgs/gui-lib/mred/private/wx/gtk/dc.rkt:55:2
   /home/soulomoon/Downloads/racket/collects/racket/private/class-internal.rkt:3553:0: continue-make-object
   /home/soulomoon/Downloads/racket/collects/racket/private/class-internal.rkt:3507:0: do-make-object
   /home/soulomoon/Downloads/racket/share/pkgs/gui-lib/framework/splash.rkt:196:3
   /home/soulomoon/Downloads/racket/share/pkgs/gui-lib/framework/splash.rkt:76:5
   /home/soulomoon/Downloads/racket/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:454:6'

**Comment by Mrnumbers9** [comment]
Now we seem to get
```
    Gdk-Message: Unable to load arrow from the cursor theme
GdkCursor->C: argument is not non-null 'GdkCursor' pointer
  argument: #f
  context...:
   /usr/racket/collects/ffi/unsafe.rkt:1246:12
   /usr/racket/share/pkgs/gui-lib/mred/private/wx/gtk/cursor.rkt:61:2: set-standard method in cursor-driver%
   ...ivate/syntax.rkt:234:25
   ...ivate/syntax.rkt:24:6
   /usr/racket/collects/racket/private/class-internal.rkt:3553:0: continue-make-object
   /usr/racket/collects/racket/private/class-internal.rkt:3507:0: do-make-object
   /usr/racket/share/pkgs/gui-lib/mred/private/wxme/text.rkt: [running body]
   /usr/racket/share/pkgs/gui-lib/mred/private/mred.rkt: [traversing imports]
   /usr/racket/share/pkgs/gui-lib/mred/mred.rkt: [traversing imports]
   /usr/racket/share/pkgs/gui-lib/mred/main.rkt: [traversing imports]
   /usr/racket/share/pkgs/gui-lib/racket/gui/base.rkt: [traversing imports]
   /usr/racket/share/pkgs/drracket/drracket/drracket.rkt: [traversing imports]

```

**Comment by emliunix** [comment]
I had the same issue as you did. And after a series of hard debugging, I found I had an illegal cursor setting in dconf which caused this issue and it works now.

**Comment by Mrnumbers9** [comment]
Thanks

**Comment by jcmdln** [comment]
DrRacket works in Fedora 32 when using Wayland.  Is this ticket resolved?

**Comment by hashimmm** [comment]
I do think so

**Comment by pmatos** [comment]
Thanks for the feedback - closing.
