### ISSUE TITLE
Non-Mac OS systems access /System/Library/Frameworks/…/Foundation.so

### ISSUE THREAD

**Issue by jsmaniac** [racket/racket#1549]
Some scribble files fail to build on non-Mac OS platforms with error below, as can be seen in [the docs for scribble-code-examples](https://docs.racket-lang.org/scribble-code-examples/index.html#%28def._%28%28lib._scribble-code-examples%2Fmain..rkt%29._make-code-eval%29%29) and in [this travis log](https://travis-ci.org/jsmaniac/aful/jobs/187035912#L545):

```
raco setup: error: during building docs for <pkgs>/aful/aful/docs/aful.scrbl
raco setup:   file-exists?: `exists' access denied for /System/Library/Frameworks/Foundation.framework/Foundation.so
raco setup:     context...:
raco setup:      /home/travis/racket/collects/ffi/../racket/private/map.rkt:128:23: loop
raco setup:      /home/travis/racket/collects/ffi/unsafe.rkt:117:0: get-ffi-lib10
raco setup:      /home/travis/racket/collects/ffi/unsafe/nsalloc.rkt: [running body]
raco setup:      /home/travis/racket/collects/ffi/unsafe/nsstring.rkt: [traversing imports]
raco setup:      /home/travis/racket/collects/net/osx-ssl.rkt: [traversing imports]
raco setup:      /home/travis/racket/collects/net/http-client.rkt: [traversing imports]
raco setup:      /home/travis/racket/collects/net/url.rkt: [traversing imports]
raco setup:      /home/travis/racket/collects/planet/private/resolver.rkt: [traversing imports]
raco setup:      /home/travis/racket/collects/planet/resolver.rkt: [traversing imports]
raco setup:      /home/travis/racket/share/pkgs/scribble-lib/scribble/tag.rkt: [traversing imports]
raco setup:      /home/travis/racket/share/pkgs/scribble-lib/scribble/base.rkt: [traversing imports]
raco setup:      /home/travis/racket/share/pkgs/scribble-lib/scribble/manual.rkt: [traversing imports]
raco setup:      /home/travis/.racket/snapshot/pkgs/scribble-enhanced/with-manual.rkt: [traversing imports]
raco setup:      /home/travis/build/jsmaniac/aful/aful/scribble-enhanced.rkt: [traversing imports]
raco setup:      /home/travis/build/jsmaniac/aful/aful/reader.rkt: [traversing imports]
raco setup:      /home/travis/build/jsmaniac/aful/aful/lang/reader.rkt: [traversing imports]
raco setup:      ...
```

A quick `grep` turned up [`racket/pkgs/racket-doc/scribblings/foreign/objc.scrbl`](https://docs.racket-lang.org/scribble-code-examples/index.html#%28def._%28%28lib._scribble-code-examples%2Fmain..rkt%29._make-code-eval%29%29), which was edited by @mflatt 4 days ago along with many other files. I skimmed over the diff, but didn't see anything obvious.

**Comment by jsmaniac** [comment]
My bad, I can reproduce the issue with an older version from 2016-12-15, so I guess it must be something else than the commit I pointed to.

**Comment by jsmaniac** [comment]
I managed to narrow the issue a bit on my project. [This build works](https://travis-ci.org/jsmaniac/aful/jobs/188093842#L430), while [this build fails](https://travis-ci.org/jsmaniac/aful/jobs/188093969#L430). The [diff](https://github.com/jsmaniac/aful/compare/93660ec4b84e...95bdc806de65) shows that the only difference is that `(require (only-in scribble/base))` was added, i.e. the module is loaded but nothing in it is used.

I noticed one potential trouble-makers here: the module which contains `(require (only-in scribble/base))` is a reader module.

**Comment by mflatt** [comment]
Ok, I take it back. There's a straightforward problem on non-Mac OSes, and I'll push a repair for that.

There's a second, unrelated issue when running from a Racket build as a Git checkout. In that setting,
```
#lang racket/base
(require racket/sandbox)

(define e (make-module-evaluator (string-append "#lang racket/base\n")))
(e '(require racket/sandbox))
(e '(make-module-evaluator (string-append "#lang racket/base\n")))
```
fails, because a sandbox doesn't include enough filesystem-access permissions to create a nested sandbox. The problem is specifically due to following relative links with up-directory indicators in a collection links file, such as "../../pkgs" to get to the "racket-doc" package. I have an idea how to fix that one, too.
