### ISSUE TITLE
"take" and "drop" report misleading error in case of bad first argument

### ISSUE THREAD

**Issue by hashimmm** [racket/racket#1556]
For example: 

> (take 123 2)
. . take: index reaches a non-pair
  index: 2
  in: 123

and:

> (drop "asdf" 2)
. . drop: index reaches a non-pair
  index: 2
  in: "asdf"

Something like the usual contract violation message, showing what was provided and what was expected, would be much nicer.

**Comment by bennn** [comment]
#1582
