### ISSUE TITLE
Error pretty-printing a module with a struct after compilation

### ISSUE THREAD

**Issue by gus-massa** [racket/racket#1568]
I'm was triying to add some reductions for operations with `structs`, so I added some test cases in optimize.rktl. But when the reduction was wrong I got a weird error:

Minimized version of code: [gus-massa/.../optize.rktl](https://github.com/gus-massa/racket/commit/1936d15d8d5574dd425ace33e857e3bf02453d7d)

Error:

    > racket -f ..\pkgs\racket-test-core\tests\racket\optimize.rktl

    file-position: contract violation
      expected: exact-positive-integer?
      received: -2993
      context...:
       C:\Users\[...]\collects\racket\pretty.rkt: 1005:4: indent
       C:\Users\[...]\collects\racket\pretty.rkt: 1275:6: loop
       C:\Users\[...]\collects\racket\pretty.rkt: 1013:4: pr
       [...]
       C:\Users\[...]\collects\racket\pretty.rkt: 414:0: generic-write17
       ...

I coudn't reproduce it in Travis or Appveyor. I'm compilling with MSVS Express 2008 (64 bits). (Apveyor use 32 bits.) I'm still triying to make a stand alone version of this code, but `test-comp` makes a few strange transformations to the code.

**Comment by mflatt** [comment]
I haven't been able to provoke the error, even on Windows. Maybe I need to be using some of your changes?

**Comment by gus-massa** [comment]
I can reproduce this in Appveyor now. The secret was to redirect stdout to a file 

    > racket -f ..\pkgs\racket-test-core\tests\racket\optimize.rktl > hello.txt

I usually run the tests in that way, but I still can't belive it is important.

Test results: [appveyor/gus-massa/racket/1.0.644](https://ci.appveyor.com/project/gus-massa/racket/build/1.0.644#L2921)

New code to test get the error in Appveyor: [gus-massa/.../appveyor.yml](https://github.com/gus-massa/racket/commit/d074a1fc6f21ebc7999c2860313f88fae82f94b3)

**Comment by mflatt** [comment]
It appears that when you redirect to a file in the Windows command line, then the file is opened in a way that doesn't work with SetFilePointer() to get the output position. So, `file-position*` actually reports just the number of bytes in the output buffer, which goes down when the buffer is flushed. But `transplant-output-port` assumes that the position always increments.

You can avoid the immediate problem by changing `(+ delta v)` to `(max 1 (+ delta v))` on line 108 of "racket/private/port.rkt". I'm working on a more complete repair.

**Comment by mflatt** [comment]
I've pushed a repair for the real problem, and I'll also push the change to `transplant-output-port` to avoid an internal error due to a oddly behaved port.
