### ISSUE TITLE
packers.rkt test fails occasionally

### ISSUE THREAD

**Issue by samth** [racket/racket#1576]
[This DrDr run](http://drdr.racket-lang.org/38439/pkgs/racket-test/tests/file/packers.rkt) includes an example. Happens maybe 1 in 50 times.

**Comment by sorawee** [comment]
@samth Since https://github.com/racket/racket/commit/dbaf9a88604310b00ef0f38ce5678e8b19383667, the test doesn't seem to fail anymore (or if it did, it's very rare). OK to close?
