### ISSUE TITLE
syntax-parse: template metafunctions’ expansions are not expanded

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#1583]
This program demonstrates that template metafunctions do not behave as other expanders (such as match expanders and pattern expanders) do:

```racket
#lang racket/base

(require syntax/parse
         syntax/parse/experimental/template)

(define-template-metafunction ?seq
  (syntax-parser
    [(_ x ...)
     #'{?@ x ...}]))

(define/syntax-parse [x ...] #'(1 2 3))
(define/syntax-parse [y ...] #'(a b c))
(template ({?seq x y} ...))
```

I would expect the output to be `#'(1 a 2 b 3 c)`, but it is `#'((?@ 1 a) (?@ 2 b) (?@ 3 c))` because the `?@` forms are not recursively expanded. I would consider this a bug, since it is inconsistent with other expanders’ behavior and was not what I expected.

**Comment by rmculpepper** [comment]
That's intentional; they are metafunctions, not metamacros. They receive the actual terms bound to the pattern variables (see the join example in the docs).

Should I take this as a feature request for template-expanders?

**Comment by lexi-lambda** [comment]
I did recognize that behavior in the docs, but I was unsure why template metafunctions could not do both. I am ok with the behavior of what they receive, but I had expected that if a metafunction produced output that itself contained metafunctions (or `??` / `?@`), that result would be expanded.

Thinking on it a little bit more, though, I think I understand a bit better. The only thing this makes sense for is `?@`, since otherwise you could just use `template` to produce the resulting syntax. I just what I want is a “splicing metafunction” a la splicing syntax classes, though template expanders could probably generalize that.
