### ISSUE TITLE
raco pkg install --link should not modify files/directories

### ISSUE THREAD

**Issue by sorawee** [racket/racket#1588]
I installed the package `cond-strict` at `~/cond-strict/` (it in fact can be any package -- they experience the same problem) using the root account (`raco pkg install --clone cond-strict`), and grant permission 775 to everything in it. Then, with my normal account:

```
$ raco pkg install --link ~/cond-strict/
raco setup: version: 6.6
raco setup: platform: x86_64-linux [3m]
raco setup: installation name: 6.6
raco setup: variants: 3m
raco setup: main collects: /local/projects/racket/recent/x86_64/collects
raco setup: collects paths: 
raco setup:   /home/sorawee/.racket/6.6/collects
raco setup:   /local/projects/racket/recent/x86_64/collects
raco setup: main pkgs: /local/projects/racket/recent/x86_64/share/pkgs
raco setup: pkgs paths: 
raco setup:   /local/projects/racket/recent/x86_64/share/pkgs
raco setup:   /home/sorawee/.racket/6.6/pkgs
raco setup: links files: 
raco setup:   /local/projects/racket/recent/x86_64/share/links.rktd
raco setup:   /home/sorawee/.racket/6.6/links.rktd
raco setup: main docs: /local/projects/racket/recent/x86_64/doc
raco setup: --- updating info-domain tables ---
raco setup: updating: /home/sorawee/.racket/6.6/share/info-cache.rktd
raco setup: --- pre-installing collections ---
raco setup: --- installing foreign libraries ---
raco setup: --- installing shared files ---
raco setup: --- compiling collections ---
raco setup: --- parallel build using 4 jobs ---
raco setup: 3 making: <pkgs>/cond-strict
raco setup: 3 making: <pkgs>/cond-strict/scribblings
raco setup: --- creating launchers ---
raco setup: --- installing man pages ---
raco setup: --- building documentation ---
raco setup: syncing: <pkgs>/cond-strict/doc/cond-strict
error moving documentation: open-output-file: cannot open output file
  path: /home/sorawee/cond-strict/doc/cond-strict/index.html
  system error: Permission denied; errno=13
raco setup: 3 rendering: <pkgs>/racket-index/scribblings/main/user/local-redirect.scrbl
raco setup: 2 rendering: <pkgs>/racket-index/scribblings/main/user/release.scrbl
raco setup: 1 rendering: <pkgs>/racket-index/scribblings/main/user/search.scrbl
raco setup: 0 rendering: <pkgs>/racket-index/scribblings/main/user/start.scrbl
raco setup: --- installing collections ---
raco setup: --- post-installing collections ---
```

Everything in fact works fine. It's just annoying to see the error.

In principle, I do not think that `--link` should modify the source files/directories. To tell my story: I'm a TA and need to provide packages to students. Students can't install packages themselves because files are large and they have disk quota limit, so we need to instruct them to use `--link`. However, this issue happens. We cannot just modify the permission either, because we do not want students to edit any shared files.

See also #1084 (might be related).

**Comment by mflatt** [comment]
When `raco pkg install --link` installs a package as in "user" scope, it needs to modify the  documentation to point back to the user's documentation space. For example, if a student goes to "cond-strict" documentation and tries to use the search box at the top left, I believe the search will point back to the documentation index of the user that set up that package.

So, that's kind of a corner, and there may be some other similar corner that I've forgotten. They reflect the intent that user-scope packages belong to a user.

Can you install the package for everyone as an installation-scope package (using `raco pkg install -i ...`)? That would require permission to modify the installation, but doing so lines up with the intent.

There are also intermediate layers of installation, where it's possible to have a notion of site installations that chain to a more global installation. I don't think that currently works in the direction for that you'd want, though.

**Comment by sorawee** [comment]
Unfortunately, I'm just a little TA and don't have a permission to install a package systemwide. I will try to talk to those people with the permission, but if that doesn't work, I guess just ignoring the error is fine as well. Thank you!
