### ISSUE TITLE
Errortrace profiler should yield information even if user halts the program

### ISSUE THREAD

**Issue by schuster** [racket/racket#1592]
Currently, if I Ctrl-C at the command line (in Linux) when running `raco profile --errortrace my-program.rkt`, the profile information is effectively empty when the program returns, presumably because of some interaction with the errortrace mechanisms with break exceptions. I can workaround this by installing a top-level exception handler for break exceptions, but the profiler should probably catch those exceptions by default.

In case it's not obvious, the motivation behind this scenario is to profile long-running programs without having to wait for them to terminate.

cc @stamourv

**Comment by schuster** [comment]
Update: the top-level exception handler works only sometimes, and I haven't figured out what criteria determine whether it works or not.

**Comment by stamourv** [comment]
I tried interrupting the profiling of a simple infinite loop (in errortrace profiling mode), and I do get profiling info printed out.

Do you still see the problem, and if so, could you share a program that exhibits it?

**Comment by schuster** [comment]
I did see it again the other day, but I haven't yet found a way to shrink it down to a reasonable example that exhibits the error (the current program is on the order of 10k LOC).

I'll spend a little more time on that and see if I can find a better example.

**Comment by schuster** [comment]
P.S. I still see the issue in Racket 6.8.

**Comment by stamourv** [comment]
If you could share the 10kloc program, I can try to have a look.

**Comment by schuster** [comment]
I made a branch here that exhibits the behavior: https://github.com/schuster/aps-conformance-checker

In the root directory of that project, run `raco profile --total --use-errortrace examples/raft.rkt`. When I let that run for 30 seconds or so then halt with Ctrl-C, I get this at the end of my output:

```
profiled thunk error: user break
Profiling results
-----------------
  Total cpu time observed: 30701ms (out of 30982ms)
  Number of samples taken: 516 (once every 59ms)

====================================
                        Caller
Idx  Total    Self    Name+srcLocal%
     ms(pct)  ms(pct)   Callee
====================================
```

You may want to run `raco make examples/raft.rkt` before profiling just to avoid the initial start-up time.

**Comment by stamourv** [comment]
Update.
Good news: if you use an explicit call to `profile` in your program (as opposed to using `raco profile`) you can get profile info after interrupting the program.
Bad news: `raco profile --use-errortrace` is just broken, with or without interruption. I'm investigating.

**Comment by stamourv** [comment]
Re explicit call to `profile`: You'll need `#:use-errortrace? #t`, and to run your program with `racket -l errortrace -t raft.rkt`.

**Comment by stamourv** [comment]
Ok, fix pushed. Thanks for the report, and sorry for the wait!

**Comment by schuster** [comment]
Great, thanks!
