### ISSUE TITLE
Under some circumstances, setting syntax-property to be preserved causes segfault

### ISSUE THREAD

**Issue by wilbowma** [racket/racket#1594]
Reproduced in 420330fef00cc7200fa3d625b2072607ef013c5f

Unfortauntely, the smallest example I have so far includes the entire Cur code base + a 600 line macro for Cur that isn't yet public code.

I have a macro generating 
```racket
#'(lambda (newvar) 
      (let-syntax ([var (make-rename-transformer (syntax-property #'var 'type #'(Type 0)))])
         body)
```

The code runs. When I change `(syntax-property #'var 'type #'(Type 0))` to `(syntax-property #'var 'type #'(Type 0) #t)`, I get a segfault: `SIGSEGV MAPERR si_code 1 fault on addr 0xfffffffffffff250`

I will try to come up with a test, but maybe someone who knows how these things works can generate a test faster than I can.

**Comment by stchang** [comment]
I independently started getting seg faults in what seems like a similar situation.

I dont know if it's the same as this bug but I think my seg faults are triggered when using preserved syntax properties with a non-serializable key:

```
$ racket
Welcome to Racket v6.7.0.4.
> (syntax-property #'+ (lambda (x) x) #'-)
#<syntax:1:19 +>
> (syntax-property #'+ (lambda (x) x) #'- #t)
SIGSEGV MAPERR si_code 1 fault on addr (nil)
Aborted
```

William, are you sure that you are using a symbol key? In my situation, I thought I was using a symbol but I made a typo and was actually using a function as the key.

I confirmed the seg fault in 6.8 as well.

**Comment by wilbowma** [comment]
Testing now, but I'm getting the segfault with the following use of `syntax-property` with definitely I think for sure uses a symbol key, so I suspect this is a different issue:
```racket
       (local-expand #`(#%plain-lambda (n)                                                                                                                                                                         
                                       (let-syntax ([var (make-rename-transformer                                                                                                                                  
                                                          (syntax-property #'n 'type #'type #t))])                                                                                                                 
                                         (cps-obj& body #,(answer-type))))                                                                                                                                         
                     'expression                                                                                                                                                                                   
                     null)          
```

**Comment by wilbowma** [comment]
OOHhh maybe you're right. the `'type` is probably turning into `'(Type 0)`, because I've used the name `type` as a pattern variable.

**Comment by wilbowma** [comment]
Yup, this solves it.
