### ISSUE TITLE
unsyntax-splicing looses lexical context of everything except the first element

### ISSUE THREAD

**Issue by jsmaniac** [racket/racket#1598]
Racket version: 20170128-aa130df

```
#lang racket
(define (nest before -v)
    #`(#,@before #,-v))
(nest #'(add1) #'add1)
```

If I click on the first `add1` in DrRacket's REPL, I can see it has an `identifier-binding` and an `identifier-transformer-binding`. The second `add1` lacks both.

If I change the code to the following, only the first `list` has a context, the `add1` and the `+` both lack it.

```
#lang racket
(define (nest before -v)
  #`(list #,@before +))
(nest #'(add1) #'add1)
```

**Comment by rmculpepper** [comment]
The problem appears to be in DrRacket's syntax snips, not in quasisyntax etc. It also occurs in the following example:

    #'(add1 . (add1))

I would guess that the bug has to do with displaying identifiers in syntax pairs that are not syntax lists, but strangely it handles `#'(add1 . add1)` just fine.

BTW, if you use the macro stepper's syntax browser, you should see the correct information:

    (require macro-debugger/syntax-browser)
    (browse-syntaxes (list #'(add1 . (add1))))

**Comment by jsmaniac** [comment]
@rmculpepper Indeed, the info is still here. I had a problem with an unbound identifier, and thought through debugging that this was the cause, but it's only a display issue. Thanks!
