### ISSUE TITLE
SSL certificate verification fails for Google on Mac OS

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#1606]
Using Racket v6.8 and Mac OS 10.11.6, the follow program fails:

```racket
#lang racket
(require net/url net/url-connect)
(parameterize ([current-https-protocol 'secure])
  (port->string (get-pure-port (string->url "https://www.google.com/"))))
```
```
ssl-connect: connect failed (error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed)
```

It seems to work fine for non-Google domains that use TLS, but for some reason Racket doesn’t pick up the certificate information for Google. I don’t really know enough about how this process works to investigate, but it seems like a bug in Racket, since other programs seem to accept the certificate just fine.

**Comment by rmculpepper** [comment]
I tried that program on an older version of Mac OS and different versions of Racket, and it failed on every version of Racket that I tried since 6.4 (when `'secure` was added).

I also tried the following program

    (ssl-connect "www.google.com" 443 (ssl-secure-client-context))

and it succeeded in Racket 6.3 and failed since 6.4.

**Comment by samth** [comment]
Google just changed their certificate, I think, to use their new
certificate authority, so that might be the problem.

**Comment by lexi-lambda** [comment]
Given that `ssl-default-verify-sources` just uses the default Mac OS keychain, why would my web browsers and `curl` all accept the certificate but Racket would not?

**Comment by rmculpepper** [comment]
If I move `/Applications/Racket v6.8/lib/libssl-1.0.0.dylib` out of the way and restart racket (so it uses `/usr/lib/libssl.dylib` instead, I think), both examples succeed.

I found a stackoverflow page that suggests that openssl < 1.0.2 has problems with cross-signed certificates (which might be part of the transition plan for Google's CA, which Sam mentioned). Why does it work with the system libssl (0.9.8zg for me)? Maybe Google sends a different (compatible) certificate for non-SNI requests.

References:
- http://stackoverflow.com/questions/34646942/ssl3-get-server-certificate-certificate-verify-failed-on-python-when-requesting
- https://github.com/certifi/python-certifi/issues/26 (see the second message)

**Comment by mflatt** [comment]
@rmculpepper Thanks for investigating. Building v1.0.2k does solve the problem for me, so I'll update the relevant package.

**Comment by mflatt** [comment]
`raco pkg update racket-x86_64-macosx-2` should now fix the problem.

**Comment by mflatt** [comment]
Well, that fixes the problem for the development build. I don't immediately know the right answer for v6.8.

**Comment by lexi-lambda** [comment]
Thanks to the three of you for your help and immediate fix. Given that @rmculpepper’s investigation indicates that the issue is not 6.8-specific, it seems like something that might have to wait for a 6.9 or 6.8.1 to get released? I’d be alright with calling this closed, even if the timing is a little unfortunate since 6.8 was just released.

**Comment by samth** [comment]
Could we just update the pkg catalog for 6.8 so that people can fix it with
an update?

**Comment by lexi-lambda** [comment]
Another small thing: would it be possible to add version numbers to the libs packages so that I can depend on a version with the updated OpenSSL lib? I’d like to ensure my application doesn’t end up with an older version and blow up at runtime.

**Comment by mflatt** [comment]
Updating the package catalog is usually a problem, because changing ".zo" files means that other importing ".zo"s will try to rebuild. These packages don't supply any ".zo" files, though, so it seems possible on that front.

I think other things are likely to go wrong, such as someone trying to update a write-only installation and having that not fail before, since main-distribution packages have never changed for a release before. If the problem seems significant enough, we could experiment.

The problem doesn't seem to happen on Windows (which is the other platform where we provide a built OpenSSL), but I don't know why. If that's right, then we could at least limit the experiment to the Mac OS packages.

**Comment by rfindler** [comment]
Perhaps the right experiment is not to update the 6.8 catalog, but to
improve our "out of cycle release based on a patch" process.

**Comment by stamourv** [comment]
FWIW, we could do that with a bugfix 6.8.1 release.

**Comment by samth** [comment]
That would also allow us to fix the TR issue fixed [here](https://github.com/racket/typed-racket/commit/6334dfb9398f6ad34ac64a4dbdfa4d118ebd871b).

**Comment by sorawee** [comment]
The original issue is fixed. The discussion about how to 'improve our "out of cycle release based on a patch" process' remains unresolved, but I don't think this is a place for it. Closing the issue.
