### ISSUE TITLE
configure command line for racket

### ISSUE THREAD

**Issue by PurityControl** [racket/racket#1610]
I do not know whether this is a feature or a bug.
I am currently using DrRacket v 6.8.
The menu option "configure command line for racket" under "Help" is only present if the directory /etc/paths.d exists. If the directory hasn't been created yet then the menu option is not present.

**Comment by sorawee** [comment]
Maybe the "configure command line for racket" menu should always be available, but when `/etc/paths.d` doesn't exist, clicking it won't configure the command line, but instead display what actions should be taken.

**Comment by sorawee** [comment]
@rfindler is this fixed?

**Comment by rfindler** [comment]
No, @sorawee I don't think it is fixed.

What actions _should_ be taken in that case?

**Comment by sorawee** [comment]
Do you think my proposed solution above is reasonable?

**Comment by rfindler** [comment]
The proposed solution above says "but instead display what actions should be taken." but I don't know what the actions are!

**Comment by rfindler** [comment]
Google isn't helping me understand what it means for `/etc/paths.d` to not exist. Is that supposed to be a sign of  screwed up macos installation? Or is it something where there is some specific action to be taken to create it in a proper way?

**Comment by sorawee** [comment]
I agree that this is weird, and any more details from @PurityControl would be appreciated.

However, I do think that a feedback to users -- perhaps a message saying "`/etc/paths.d` unusually doesn't exist, so we can't proceed. Please configure the command line manually." -- would be better than silently not adding a menu item.

**Comment by PurityControl** [comment]
I think the confusion you're facing is that the context of the issue is over 4 years old now and the landscape has changed considerably in that time.

`/etc/paths.d` hasn't always been included in a default mac install, but has been now for some time.
The problem arose when people upgrade release on release rather than doing a clean install.

To give some context see [this thread](https://discussions.apple.com/thread/1301446) that talks about the issue.

This is why some sites still have instructions about creating the directory, even though by now, most installations probably have it.

See an excerpt from [the postgres app](https://postgresapp.com/documentation/cli-tools.html) docs for an example (excerpt below)

```
The easiest way to configure your PATH is to execute the following command:

sudo mkdir -p /etc/paths.d &&
echo /Applications/Postgres.app/Contents/Versions/latest/bin | sudo tee /etc/paths.d/postgresapp

Don’t forget to close the Terminal window and open a new one for changes to take effect.
```

**Comment by rfindler** [comment]
Ah, thanks for the help @PurityControl .  It looks like the current code can't work when the directory doesn't exist and I'm not seeing a way to get the authentication dialog open to create the directory so unelss I'm missing something our choices are to just leave this alone or to have the menu item give a message asking the user to create the directory. In particular, I'm not seeing how to use `authopen` to create the directory nor am I seeing that another command might do it.

**Comment by PurityControl** [comment]
I think a message explaining what the issue is and how to overcome it is perfectly acceptable.

It's not uncommon for people to restore to a new Mac from a time machine backup and looking at the timing of this, that is what happened in my case. So there are situations where the directory could be missing.

Having said that the prevalence of iCloud, Onedrive, Dropbox and Google drive, coupled with much wider adoption of git etc.  makes clean installs probably much more likely than in the past.
Given the transition to M1 chips this is even more likely as most people will perceive a fresh start a better option.

This is all purely conjecture but I would guess you are protecting against something that is a diminishing edge case.
By adding the message you ensure no one is left in the dark if they find themselves without the directory, but you haven't wasted time and resource on something that probably won't affect that many people now.

**Comment by rfindler** [comment]
This commit was also relevant, but I forgot to tag it in the commit message: https://github.com/racket/string-constants/commit/d10f2adca84fb77c96c72d1013cdaee6ff2c1d1a

**Comment by mflatt** [comment]
Looks like this has been resolved.
