### ISSUE TITLE
Type errors when building for i686

### ISSUE THREAD

**Issue by keenerd** [racket/racket#1612]
While packaging Racket for Arch Linux, the 32 bit (i686) compile failed with a bunch of type errors.

One class of errors looks like

    raco setup: error: during making for <pkgs>/plot-compat/plot
    raco setup:   /build/racket/pkg/racket/usr/share/racket/pkgs/plot-lib/plot/private/common/date-time.rkt:188:2: Type Checker: type mismatch
    raco setup:     expected: Real
    raco setup:     given: Void
    raco setup:     in: (cond ((plot-time? x) (plot-time->seconds x)) ((date*? x) (date*->utc-seconds x)) ((date? x) (date->utc-seconds x)) ((sql-date? x) (date*->utc-seconds (sql-date->date* x))) ((sql-time? x) (plot-time->seconds (sql-time->plot-time x))) ((sql-timestamp? x)...
    raco setup:     compiling: <pkgs>/plot-lib/plot/private/common/date-time.rkt

The other major class of errors looks like

    /build/racket/pkg/racket/usr/share/racket/pkgs/images-lib/images/private/deep-flomap-render.rkt:200:34: Type Checker: type mismatch
      expected: (U Real flomap)
      given: flomap
      in: (flomap-blur diffuse-fm diffuse-blur)
      context...:
       /build/racket/pkg/racket/usr/share/racket/pkgs/typed-racket-lib/typed-racket/utils/tc-utils.rkt:123:0: report-all-errors
       /build/racket/pkg/racket/usr/share/racket/pkgs/typed-racket-lib/typed-racket/typecheck/tc-toplevel.rkt:326:0: type-check
       /build/racket/pkg/racket/usr/share/racket/pkgs/typed-racket-lib/typed-racket/typecheck/tc-toplevel.rkt:569:0: tc-module
       /build/racket/pkg/racket/usr/share/racket/pkgs/typed-racket-lib/typed-racket/tc-setup.rkt:82:0: tc-module/full
       /build/racket/pkg/racket/usr/share/racket/pkgs/typed-racket-lib/typed-racket/typed-racket.rkt:23:4
       standard-module-name-resolver

Around 20 errors in all.

We are building with GCC 6.3, and Racket 6.7 builds correctly.  I had hoped to bisect what was going on, but it was getting unwieldy.  If you guys can't reproduce the errors then I'll take another go at bisecting.

**Comment by takikawa** [comment]
I had a similar problem with building the Ubuntu PPA for 32-bit platforms.

You likely need to backport the following commit (https://github.com/racket/typed-racket/commit/6334dfb9398f6ad34ac64a4dbdfa4d118ebd871b) to fix it. That's what I did for Ubuntu.

**Comment by keenerd** [comment]
That works.  Thanks.  And my apologies for digging around in the wrong repository.
