### ISSUE TITLE
compile time error when `match-lambda**` used without arguments

### ISSUE THREAD

**Issue by florence** [racket/racket#1615]
`(match-lambda**)` raises the syntax error:

```
racket/collects/syntax/parse/private/parse.rkt:995:13: car: contract violation
  expected: pair?
  given: '()
```

Expected behavior:

I think this should compile to a function that always errors when called, like `(match-lambda*)`.

**Comment by iitalics** [comment]
The reason for `car` is that it needs to look at the first clause to determine how many arguments to give the procedure. This is different from `match*` as the latter takes a variable number of argument so it is possible to generate a procedure without supplying clauses.

If you are generating a `match-lambda**` programmatically and running into this error, then I suggest generating `lambda` + `match*` instead. In the meantime, perhaps we could allow a keyword option to give the number of expected arguments? Although the use-case seems pretty rare.
