### ISSUE TITLE
Racket crashes on large, deeply nested recursive bindings

### ISSUE THREAD

**Issue by minad** [racket/racket#1621]
Racket is probably not meant for this, but I generated a racket file in an experimental compiler backend for testing purposes. Nevertheless I thought I report this.

I take crash.rkt from here https://gist.github.com/minad/ea56b25fda5d81b82bc7e557b2e166df

Racket crashes reproducibly after circa a minute

~~~
$ racket crash.rkt
SIGSEGV MAPERR si_code 1 fault on addr 0x9
~~~

I tested v6.7 and v6.8 on debian x86_64

I am also wondering why it takes so much time to load this file. Is it due to the recursive bindings in the init define? But independent of the content of the file you might be able to investigate the reason for the crash.

**Edit:** If I move the definitions out of the recursive binding racket doesn't crash anymore and loads the file quickly. So the problem is how racket handles recursive bindings. Another case where I found crashes was when I played with compiler output in ANF form, where the AST was basically a degenerate flat list of (let ... (let ... (let ... (let ...))

**Comment by mflatt** [comment]
Thanks for the report!

**Comment by minad** [comment]
cool thx for fixing :+1:
