### ISSUE TITLE
Docs for max / argmax should link to each other

### ISSUE THREAD

**Issue by jackfirth** [racket/racket#1622]
If one doesn't know about [`argmax`](http://docs.racket-lang.org/reference/pairs.html?q=argmax#%28def._%28%28lib._racket%2Flist..rkt%29._argmax%29%29), it's hard to find from the docs for [`max`](http://docs.racket-lang.org/reference/generic-numbers.html?q=max#%28def._%28%28quote._~23~25kernel%29._max%29%29) as they're in completely separate sections and don't mention each other. A few "see also" notes in the docs for max/min/argmax/argmin would improve discoverability.

**Comment by stamourv** [comment]
Excellent idea. Would you like to submit a PR?

**Comment by jackfirth** [comment]
When I get time :) I have to go through some internal bureaucracy for PRs to ensure I own the copyright instead of my employer. Makes it difficult to find the time for simple one-off changes like this.

**Comment by bennn** [comment]
Wow.
Would you be ok with someone submitting a PR for this on your behalf?

**Comment by jackfirth** [comment]
It is what it is. Go right ahead!

**Comment by bennn** [comment]
https://github.com/racket/racket/commit/10aaff692b55877952ece746b1fb2c05ef9c97dd
