### ISSUE TITLE
syntax->string documentation and implementation don't line up

### ISSUE THREAD

**Issue by endobson** [racket/racket#1627]
The implementation has the contract: `(and/c syntax? stx-list?)`
https://github.com/racket/racket/blob/master/racket/collects/syntax/to-string.rkt#L82
The documentation has the contract `stx-list?`
https://github.com/racket/racket/blob/master/pkgs/racket-doc/syntax/scribblings/to-string.scrbl#L10

**Comment by Paul-C-Anagnostopoulos** [comment]
This inconsistency is still present. I'm happy to fix it if someone tells me the correct contract. From looking at `syntax->string`, I believe that it has to be the first contract above.

**Comment by bennn** [comment]
Yes I think the first contract is the right one

**Comment by Paul-C-Anagnostopoulos** [comment]
Shall I correct the documentation?

**Comment by bennn** [comment]
No that's ok

**Comment by Paul-C-Anagnostopoulos** [comment]
The documentation shouldn't be consistent with the function?

If it doesn't matter, then this issue can be closed, I think.

**Comment by bennn** [comment]
I mean: no that's ok because when I saw your last comment I went ahead & opened #2351

**Comment by Paul-C-Anagnostopoulos** [comment]
Aha, got it. I didn't see that until after I made my comment above.
