### ISSUE TITLE
[R5RS] let-syntax not accessible in null-environment

### ISSUE THREAD

**Issue by esclear** [racket/racket#1631]
(Found by @mnieper.)

The following (valid) R5RS code
```scheme
(eval '(let-syntax ((foo (syntax-rules () ((foo) 'foo)))) (foo)) (null-environment 5))
```
results in the error
```plain
macro-transformer: only a `syntax-rules' form is allowed in: (syntax-rules () ((foo) (quote foo)))
```
when executed in `plt-r5rs`.

This works in scheme48 as expected, as well as in larceny with r5rs specified, yielding the expected output `foo`.

Racket's behaviour does not conform to the R5RS specification of the `null-environment` (Page 35):
> Null-environment returns a specifier for an environment that is empty except for the (syntactic) bindings  or all syntactic keywords defined in this report that are either required or both optional and supported by the implementation.

CC: @shak-mar

**Comment by bennn** [comment]
Can you move this issue to the r5rs repo?
https://github.com/racket/r5rs
