### ISSUE TITLE
Pattern matching reference link is not at top of page

### ISSUE THREAD

**Issue by endobson** [racket/racket#1639]
Normally the link to the reference in the guide is at the top of the page, but that is not the case for match.

https://docs.racket-lang.org/guide/match.html
![screen shot 2017-03-21 at 12 18 34 am](https://cloud.githubusercontent.com/assets/170008/24136457/180486a4-0dcc-11e7-915d-34e42f4f5378.png)

**Comment by Paul-C-Anagnostopoulos** [comment]
I cannot imagine that it is worth changing this convention at this point in time. I think we can close this issue.
