### ISSUE TITLE
`raco ctool --c-mods base.c ++lib racket/base` Fails on freshly built racket

### ISSUE THREAD

**Issue by TyOverby** [racket/racket#1646]
Following the instructions from https://docs.racket-lang.org/inside/embedding.html#%28part._3m_.Embedding%29

I run `raco ctool --c-mods base.c ++lib racket/base` on a freshly built racket install, but I get the message 

```
./bin/raco: Unrecognized command: ctool

Usage: raco <command> <option> ... <arg> ...

Frequently used commands:
  setup   install and build libraries and documentation
  pkg     manage packages

A command can be specified by an unambiguous prefix.
See `raco help' for a complete list of commands.
See `raco help <command>' for help on a command.
```

**Comment by mflatt** [comment]
It looks like you may have a minimal Racket installation. If so, try installing the `cext-lib` package with

 `raco pkg install cext-lib`

(maybe with `-i` before `cext-lib`), and then `raco ctool` should work.

I'll update the docs to mention that the "cext-lib" package provides `raco ctool`.

**Comment by TyOverby** [comment]
I built my racket installation from source.  `./configure && make && make install` and all that jazz.

**Comment by mflatt** [comment]
If you started with the Git repo checkout, be sure to see "INSTALL.txt" at the top level.
