### ISSUE TITLE
Specifications for conjoin and disjoin

### ISSUE THREAD

**Issue by gfbee** [racket/racket#1649]
The implementations of `conjoin` and `disjoin` allow arguments that:
- don't necessarily produce a boolean
- accept keyword arguments [and the implementations appear to make an effort to do so]

Should the specifications, shown here for `conjoin`, be changed to reflect that?
```
  ((conjoin f ...) x ...) → boolean?
  f : (-> A ... boolean?)
  x : A
```

**Comment by Paul-C-Anagnostopoulos** [comment]
I'm happy to update the documentation for these functions.

Question: What is the A in the contract? I cannot find any other contracts that use A.

**Comment by bennn** [comment]
The idea is that `A` would come from a `parametric->/c`, something like:

```
(provide
  (contract-out
    (conjoin
     (parametric->/c [A] (-> (-> A boolean?) (-> A boolean?))))))
```

**Comment by Paul-C-Anagnostopoulos** [comment]
Is it okay to replace `A` with something like _type_?

**Comment by sorawee** [comment]
There's a problematic case with `conjoin`, namely:

```
> ((conjoin (lambda (x) (values 1 2))) 0)
1
2
```

There should be a contract that only allows the input functions to return a single value.
