### ISSUE TITLE
Search for "app match" doesn't result in useful results

### ISSUE THREAD

**Issue by endobson** [racket/racket#1653]
I wanted documentation on the the `app` form of `match`. But the search results didn't have anything in it even relating to `match`.  This is likely because `app` is not indexed as it is entirely matched on symbolic name.

https://docs.racket-lang.org/search/index.html?q=app%20match

**Comment by spdegabrielle** [comment]
Potential "Good first bug"?
If so - please add label.
Was suggested at https://github.com/racket/racket/wiki/Racketeer-Office-Hours-2017-Task-Ideas

**Comment by spdegabrielle** [comment]
@endobson is this still an issue?

**Comment by spdegabrielle** [comment]
is this still an issue?  Please consider adding the label `good first issue` so it is findable: 

[Issues labeled `good first issue` in in Racket GitHub repositories](https://github.com/search?q=type:issue+org:racket+state:open+label:%22good+first+issue%22)

**Comment by otherjoel** [comment]
I think this ought to be closed; it’s not about `app match` specifically, so much as it’s about how doc search works in general. The doc search isn’t designed to locate every specific sub-form of a macro or function. If you want to know about some form of `match` you would do a search on `match` and read its documentation.

**Comment by capfredf** [comment]
Indexing `app` or other special symbols for `match` is a straightforward fix:
<img width="894" alt="image" src="https://user-images.githubusercontent.com/512906/112205802-93e89200-8beb-11eb-9d55-5f7f3b57aeca.png">
<img width="871" alt="Screen Shot 2021-03-23 at 3 24 31 PM" src="https://user-images.githubusercontent.com/512906/112206073-e5911c80-8beb-11eb-9ca9-1d50195cbd20.png">

But I don't know if making `match <special_symbol>` searchable is doable.

**Comment by otherjoel** [comment]
How are you getting those search results? They don’t match the results on my local copy or at `docs.racket-lang.org`, and  `racket/match` definitely does not `provide` a discrete macro or function named `app`.

**Comment by capfredf** [comment]
@otherjoel I built Racket on my machine with a tiny fix to the documentation. The screenshots above show the resulting changes.

**Comment by otherjoel** [comment]
OK, I understand. So what I’m saying is, that is actually not a fix. The screenshot shows `app` and `_` as being provided from `racket/match` and `racket/match` definitely does not provide any such thing.

From what I understand, the doc search results say “xyz provided from pkg/mod” they’re not just saying “here's where to read about xyz”. They’re actually telling you that you can `(require pkg/mod)` and get an identifier `xyz` bound to the thing described in those docs.

```racket
#lang racket/base

(require racket/match) ; Does this get you 'app'?

(define x app) ; Nope! unbound identifier error
```

**Comment by capfredf** [comment]
Oh, my bad, you are right. I think we can change the text "app provided from racket/match" to "app in racket/match" or something similar. What do you think?

**Comment by samth** [comment]
There are already some things recognized by symbol -- can we document app
similarly? An example would be only from #%require.

**Comment by otherjoel** [comment]
> An example would be only from #%require

`only` is a sub-form of `#%require` but if I search `only` in the docs it is not indexed in the search results. Maybe you’re thinking of [`only-in`][1] from `require`? I suspect that’s not quite the same thing... 

[1]: https://docs.racket-lang.org/reference/require.html?#(form._((lib._racket%2Fprivate%2Fbase..rkt)._only-in))

**Comment by otherjoel** [comment]
> 
> I think we can change the text "app provided from racket/match" to "app in racket/match" or something similar. What do you think?

Can you paste in the Scribble edit you made or propose to make?

**Comment by capfredf** [comment]
https://github.com/capfredf/racket/commit/9e96d6be32c4f2d2fce02f50f9ee6c9e7148c951
<img width="929" alt="image" src="https://user-images.githubusercontent.com/512906/112248608-915a5c80-8c2c-11eb-9a21-e01696c532f6.png">

As you can see,  we would want to change the name of the linked documentation from "reference"(the base part of the collection name) to "racket/match", but I haven't figured out how to do that. Seems like all indexed symbols have the same problem.

**Comment by otherjoel** [comment]
Are you by chance live-editing `plt-index.js` or some other component of the search results page directly to get this screenshot?

**Comment by capfredf** [comment]
No, I just changed the scribble code in my local copy of racket source code, then ran `raco setup -j 12 scribblings/reference --doc-index`, and opened the local doc using a browser.

**Comment by otherjoel** [comment]
Silly me, I missed the commit link above your screenshot.

**Comment by otherjoel** [comment]
Maybe what you want is [`defidentifier`][1]?

[1]: https://docs.racket-lang.org/scribble/doc-forms.html?q=indexed-racket#%28def._%28%28lib._scribble%2Fmanual..rkt%29._defidentifier%29%29

**Comment by samth** [comment]
`defidentifier` requires that the thing documented is a binding.

**Comment by otherjoel** [comment]
Yes OK. Scratch that idea.

I’m still leaning toward my original position; I don’t think there’s anything wrong with the docs for `match`.

**Comment by capfredf** [comment]
I think indexing symbols is a good way to go. In general, it would be better to make linked documents' names more specific, because the current search results of symbols is not very good.  For example,  suppose I am looking for the meaning 'write as in a result from `file-or-directory-permissions`, I can't tell which link I should click:

<img width="371" alt="image" src="https://user-images.githubusercontent.com/512906/112506366-0da38b80-8d64-11eb-83e5-76eaf2dac5d4.png">

**Comment by benknoble** [comment]
Apologies for necro'ing this, but perhaps the solution is to use `@index` à la `@indexed-racket`? The reference does this which causes those `'write in reference` blocks to appear.

https://docs.racket-lang.org/scribble/manual-indexing.html#%28form._%28%28lib._scribble%2Fmanual..rkt%29._indexed-racket%29%29
