### ISSUE TITLE
Racket doesn't allow creating files with specific permissions

### ISSUE THREAD

**Issue by endobson** [racket/racket#1654]
Use case:
Create a file that only I can read/write (unix style permissions `600`).

Racket seemingly doesn't let a user supply permissions with open-output-file and only supports changing the permissions after the fact with [file-or-directory-permissions](https://docs.racket-lang.org/reference/Filesystem.html?q=file-or-directory-permissions#%28def._%28%28quote._~23~25kernel%29._file-or-directory-permissions%29%29).

**Comment by bnoordhuis** [comment]
I think it should be possible to teach `scheme_do_open_output_file()` an additional `#:perm #o600` or `#:permissions #o600` keyword.  I volunteer to do the work if there is consensus.

It's something of an open question how (or if) it should work on Windows.  As a data point, libuv (the I/O library that node.js uses) creates the file with FILE_ATTRIBUTE_READONLY unless any writable bits are set.

As a workaround, you could temporarily change the umask when creating the file:
```racket
(require ffi/unsafe)

(define umask (get-ffi-obj "umask" (ffi-lib "libc") (_fun _int -> _int)))

(define-syntax with-umask
  (syntax-rules ()
    ((_ mode body ...)
     (let ((saved (umask mode)))
       (dynamic-wind void
                     (lambda () body ...)
                     (lambda () (umask saved)))))))

;;; Note: umask is subtractive: (666 & ~077) = 600
(define port
  (with-umask #o077
    (open-output-file "file.txt")))
```

**Comment by samth** [comment]
Adding that to `open-output-file` sounds like a good idea, but I might represent it as a list of symbols on the Racket side.

**Comment by bnoordhuis** [comment]
@samth What should it look like?

**Comment by samth** [comment]
@bnoordhuis something like `(open-output-file "file.txt" #:permissions '(read write))`.

Alternatively, `#:permissions 'read-write` or `#:permissions 'read`. Maybe @mflatt has thoughts on what would be most consistent with other APIs.

**Comment by mflatt** [comment]
For `file-or-directory-permissions`, I went with a numerical argument. I'm still not sure that it was the right choice, but it was straightforward and about as general as it could be.

**Comment by samth** [comment]
In that case, let's stick with the numeric argument for consistency.

**Comment by samth** [comment]
Looking at `file-or-directory-permissions` more, it by default uses the list-of-symbols approach, but also the number approach. Which is a bit confusing, so I'm not sure what the consistent choice would be.

**Comment by bnoordhuis** [comment]
`file-or-directory-permissions` accepts a number but not symbols when setting the permissions.<sup>1</sup> Barring objections I'll go with that approach.

<sup>1</sup> Reading permissions is configurable with the `'bits` argument.

**Comment by spdegabrielle** [comment]
Potential "Good first bug"?
If so - please add label.
Was suggested at https://github.com/racket/racket/wiki/Racketeer-Office-Hours-2017-Task-Ideas
