### ISSUE TITLE
System crash on running a particular file in racket

### ISSUE THREAD

**Issue by Vishesh-Gupta** [racket/racket#1655]
I would like to report a bug issue I have faced with the new version of Racket. I recently installed it and then have tried to open it multiple times but after every time I open my racket my windows crashes. Please have a look over it. Thank you

**Comment by mflatt** [comment]
Hi @Vishesh-Gupta — Did you mean to provide a file that we should try running?

**Comment by Vishesh-Gupta** [comment]
[Kenken.pdf](https://github.com/racket/racket/files/917718/Kenken.pdf)

Whenever I use the following text in .rkt format the system crashes.

**Comment by samth** [comment]
Can you upload this file not as a pdf?

**Comment by Vishesh-Gupta** [comment]
What format of file do you want I can't upload it in .rkt here?

**Comment by samth** [comment]
If you can paste the text of the file into a comment here, that would be perfect.

**Comment by Vishesh-Gupta** [comment]
;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-intermediate-lambda-reader.ss" "lang")((modname kenken-start) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #f)))
(require "kenken-draw.rkt")


(define-struct puzzle (size board constraints))
;; A Puzzle is a (make-puzzle 
;;                Nat 
;;                (listof (listof (anyof Sym Nat Guess)))
;;                (listof (list Sym Nat (anyof '+ '- '* '/ '=))))
;; requires: See Assignment Specifications

(define-struct guess (symbol number))
;; A Guess is a (make-guess Sym Nat)
;; requires: See Assignment Specifications

;; Some useful constants
;; from assignment specification
(define puzzle1
  (make-puzzle 
   4
   (list
    (list 'a 'b 'b 'c)
    (list 'a 'd 'e 'e)
    (list 'f 'd 'g 'g)
    (list 'f 'h 'i 'i))
   (list
    (list 'a 6 '*)
    (list 'b 3 '-)
    (list 'c 3 '=)
    (list 'd 5 '+)
    (list 'e 3 '-)
    (list 'f 3 '-)
    (list 'g 2 '/)
    (list 'h 4 '=)
    (list 'i 1 '-))))

;; a partial solution to puzzle1
(define puzzle1partial
  (make-puzzle 
   4
   (list
    (list 'a 'b 'b 'c)
    (list 'a 2 1 4)
    (list 'f 3 'g 'g)
    (list 'f 'h 'i 'i))
   (list
    (list 'a 6 '*)
    (list 'b 3 '-)
    (list 'c 3 '=)
    (list 'f 3 '-)
    (list 'g 2 '/)
    (list 'h 4 '=)
    (list 'i 1 '-))))

;; a partial solution to puzzle1 with a cage partially filled in
(define puzzle1partial2
  (make-puzzle 
   4
   (list
    (list (make-guess 'a 2) 'b 'b 'c)
    (list 'a 2 1 4)
    (list 'f 3 'g 'g)
    (list 'f 'h 'i 'i))
   (list
    (list 'a 6 '*)
    (list 'b 3 '-)
    (list 'c 3 '=)
    (list 'f 3 '-)
    (list 'g 2 '/)
    (list 'h 4 '=)
    (list 'i 1 '-))))

;; a partial solution to puzzle1 with a cage partially filled in
;; but not yet verified 
(define puzzle1partial3
  (make-puzzle 
   4
   (list
    (list (make-guess 'a 2) 'b 'b 'c)
    (list (make-guess 'a 3) 2 1 4)
    (list 'f 3 'g 'g)
    (list 'f 'h 'i 'i))
   (list
    (list 'a 6 '*)
    (list 'b 3 '-)
    (list 'c 3 '=)
    (list 'f 3 '-)
    (list 'g 2 '/)
    (list 'h 4 '=)
    (list 'i 1 '-))))

;; The solution to puzzle 1
(define puzzle1soln
  (make-puzzle
   4
   '((2 1 4 3)
     (3 2 1 4)
     (4 3 2 1)
     (1 4 3 2))
   empty))

;; wikipedia KenKen example
(define puzzle2
  (make-puzzle
   6
   '((a b b c d d)
     (a e e c f d)
     (h h i i f d)
     (h h j k l l)
     (m m j k k g)
     (o o o p p g))
   '((a 11 +)
     (b 2 /)
     (c 20 *)
     (d 6 *)
     (e 3 -)
     (f 3 /)
     (g 9 +)
     (h 240 *)
     (i 6 *)
     (j 6 *)
     (k 7 +)
     (l 30 *)
     (m 6 *)
     (o 8 +)
     (p 2 /))))

;; The solution to puzzle 2
(define puzzle2soln
  (make-puzzle
   6
   '((5 6 3 4 1 2)
     (6 1 4 5 2 3)
     (4 5 2 3 6 1)
     (3 4 1 2 5 6)
     (2 3 6 1 4 5)
     (1 2 5 6 3 4))
   empty))

;; Tiny board
(define puzzle3
  (make-puzzle 
   2 
   '((a b) 
     (c b)) 
   '((b 3 +) 
     (c 2 =)
     (a 1 =))))

(define puzzle3partial
  (make-puzzle
   2 
   (list
    (list 'a (make-guess 'b 1))
    (list 'c (make-guess 'b 2)))
   '((b 3 +) 
     (c 2 =)
     (a 1 =))))  

;; a big board:  will take a *long* time without trying the bonus
(define puzzle4
  (make-puzzle
   9
   '((a a b c d e e f f)
     (g h b c d i j k l)
     (g h m m i i j k l)
     (n o m p p q q r s)
     (n o t u p v v r s)
     (n w t u x x y z z)
     (A w B C C C y D D)
     (A B B E E F G H I)
     (J J K K F F G H I))
   '((a 2 /)
     (b 11 +)
     (c 1 -)
     (d 7 *)
     (e 4 -)
     (f 9 +)
     (g 1 -)
     (h 4 /)
     (i 108 *)
     (j 13 +)
     (k 2 -)
     (l 5 -)
     (m 84 *)
     (n 24 *)
     (o 40 *)
     (p 18 *)
     (q 2 /)
     (r 2 -)
     (s 13 +)
     (t 10 +)
     (u 13 +)
     (v 2 -)
     (w 63 *)
     (x 1 -)
     (y 3 /)
     (z 2 /)
     (A 7 +)
     (B 13 +)
     (C 336 *)
     (D 1 -)
     (E 15 +)
     (F 12 *)
     (G 9 +)
     (H 5 -)
     (I 18 *)
     (J 3 /)
     (K 40 *))))

;;==============================================================================
;; Part (a)

;; (find-blank puz) produces the position of the first blank
;; space in puz, or false if no cells are blank.  If the first constraint has
;; only guesses on the board, find-blank produces 'guess.  
;; find-blank: Puzzle -> (anyof Posn false 'guess)
;; Examples:
(check-expect (find-blank puzzle1) (make-posn 0 0))

(define (find-blank puz)
  (local
    [(define (find-blank/accumalator size board constraints posn/acc guess/bool)
       (cond
         [(empty? constraints) false]
         [(empty? board)
          (cond
            [guess/bool 'guess]
            [else (find-blank/accumalator size 
                                          (puzzle-board puz)
                                          (rest constraints)
                                          (make-posn 0 0)
                                          false)])]
         [(empty? (first board))
          (find-blank/accumalator size
                                  (rest board)
                                  constraints 
                                  (make-posn 0
                                             (add1 (posn-y posn/acc)))
                                  guess/bool)]
         [(and (guess? (first (first board)))
               (symbol=? (first (first constraints))
                         (guess-symbol (first (first board)))))
          (find-blank/accumalator size
                                  (cons (rest (first board))
                                        (rest board))
                                  constraints
                                  (make-posn (add1 (posn-x posn/acc))
                                             (posn-y posn/acc))
                                  true)]
         [(equal? (first (first constraints)) (first (first board)))
          posn/acc]
         [else (find-blank/accumalator size
                                       (cons (rest (first board))
                                             (rest board))
                                       constraints
                                       (make-posn (add1 (posn-x posn/acc))
                                                  (posn-y posn/acc))
                                       guess/bool)]))]
    (find-blank/accumalator (puzzle-size puz)
                            (puzzle-board puz)
                            (puzzle-constraints puz)
                            (make-posn 0 0)
                            false)))

;; Tests:
(check-expect (find-blank puzzle1soln) false)
(check-expect (find-blank puzzle1partial2) (make-posn 0 1))

;;==============================================================================
;; Part (b)

;; (used-in-row puz pos) produces a list of numbers used in the same 
;; row as (x,y) position, pos, in the given puz.  
;; used-in-row: Puzzle Posn -> (listof Nat)
;; Examples:
(check-expect (used-in-row puzzle1 (make-posn 1 1)) empty)

(define (used-in-row puz pos)
  (quicksort (map (lambda (x) (cond
                                [(guess? x) (guess-number x)]
                                [else x])) (filter (lambda (x)
                                                     (or (guess? x) (number? x)))
                                                   (list-ref (puzzle-board puz)
                                                             (posn-y pos)))) <))

;; Tests:
(check-expect (used-in-row puzzle1partial (make-posn 2 2)) (list 3))
(check-expect (used-in-row puzzle1partial2 (make-posn 0 1)) (list 1 2 4))

;; (used-in-column puz pos) produces a list of numbers used in the same
;; column as (x,y) position, pos, in the given puz.  
;; used-in-column: Puzzle Posn -> (listof Nat)
;; Examples:
(check-expect (used-in-column puzzle1 (make-posn 1 1)) empty)
(check-expect (used-in-column puzzle1partial (make-posn 2 2)) (list 1))
(check-expect (used-in-column puzzle1partial2 (make-posn 0 1)) (list 2))

(define (used-in-column puz pos)
  (local [(define new-puz (make-puzzle (puzzle-size puz)
                                       (apply map list (puzzle-board puz))
                                       (puzzle-constraints puz)))]
    (quicksort (map (lambda (x) (cond
                                  [(guess? x) (guess-number x)]
                                  [else x])) (filter (lambda (x)
                                                       (or (guess? x)
                                                           (number? x)))
                                                     (list-ref (puzzle-board new-puz)
                                                               (posn-x pos)))) <)))

;; Tests:

;;==============================================================================
;; Part (c)

;;This function may be useful as a helper for available-vals

;; (allvals n) produces a list of values from 1 to n
;; allvals: Nat -> (listof Nat)
;; Examples:
(check-expect (allvals 0) empty)
(check-expect (allvals 1) (list 1))

(define (allvals n) (build-list n (lambda (x) (add1 x))))

;; Tests:
(check-expect (allvals 3) (list 1 2 3))

;; (available-vals puz pos) produces a list of valid entries for the (x,y)  
;; position, pos, of the consumed puzzle, puz.  
;; available-vals: Puzzle Posn -> (listof Nat)
;; Examples:
(check-expect (available-vals puzzle1 (make-posn 2 3)) '(1 2 3 4))

(define (available-vals puz pos)
  (local [(define used-row (used-in-row puz pos))
          (define used-col (used-in-column puz pos))]
    (filter (lambda (x) (not (member? x used-row)))
            (filter (lambda (x) (not (member? x used-col))) (allvals (puzzle-size puz))))))

;; Tests:
(check-expect (available-vals puzzle1partial (make-posn 2 2)) '(2 4))
(check-expect (available-vals puzzle1partial2 (make-posn 0 1)) '(3))


;;==============================================================================
;; Part (d)

;; (place-guess brd pos val) fills in the (x,y) position, pos, of the board, brd, 
;; with the a guess with value, val
;; place-guess: (listof (listof (anyof Sym Nat Guess))) Posn Nat 
;;              -> (listof (listof (anyof Sym Nat Guess)))
;; Examples:
(check-expect (place-guess (puzzle-board puzzle1) (make-posn 3 2) 5)
              (list
               (list 'a 'b 'b 'c)
               (list 'a 'd 'e 'e)
               (list 'f 'd 'g (make-guess 'g 5))
               (list 'f 'h 'i 'i)))

(define (place-guess brd pos val)
  (local
    [(define (check-col col x val)
       (cond
         [(= 0 x)
          (cons (make-guess (first col) val) (rest col))]
         [else (cons (first col) 
                     (check-col (rest col) (sub1 x) val))]))]
    (cond
      [(= 0 (posn-y pos))
       (cons (check-col (first brd) (posn-x pos) val)
             (rest brd))]
      [else 
       (cons (first brd)
             (place-guess (rest brd)
                          (make-posn (posn-x pos) (sub1 (posn-y pos)))
                          val))])))

;; Tests:

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;DO NOT CHANGE THIS FUNCTION;;;;;;;;;;;;;;;;;;;;;;;

;; (fill-in-guess puz pos val) fills in the (x,y) position, pos, of puz's board
;; with a guess wtih value, val
;; fill-in-guess: Puzzle Posn Nat -> Puzzle
;; Examples:
(check-expect (fill-in-guess puzzle1 (make-posn 3 2) 5)
              (make-puzzle
               4
               (list
                (list 'a 'b 'b 'c)
                (list 'a 'd 'e 'e)
                (list 'f 'd 'g (make-guess 'g 5))
                (list 'f 'h 'i 'i))
               (puzzle-constraints puzzle1)))

(define (fill-in-guess puz pos val)
  (make-puzzle (puzzle-size puz) 
               (place-guess (puzzle-board puz) pos val) 
               (puzzle-constraints puz)))

;; Tests:
(check-expect (fill-in-guess puzzle3 (make-posn 0 0) 1)
              (make-puzzle
               2
               (list (list (make-guess 'a 1) 'b)
                     (list 'c 'b))
               '((b 3 +) 
                 (c 2 =)
                 (a 1 =))))

;;==============================================================================
;; Part (e)

;; (guess-valid? puz) determines if the guesses in puz satisfy their constraint
;; guess-valid?: Puzzle -> Bool
;; Examples:

(define (guess-valid? puz)
  (local
    [(define sym (first (first (puzzle-constraints puz))))
     (define op (third (first (puzzle-constraints puz))))
     (define cage-result (second (first (puzzle-constraints puz))))
     (define vlst (map guess-number 
                       (filter (lambda (x)
                                 (and (guess? x)
                                      (symbol=? sym
                                                (guess-symbol x))))
                               (foldr append empty (puzzle-board puz)))))]
    (cond
      [(symbol=? '+ op)
       (= cage-result (foldr + 0 vlst))]
      [(symbol=? '- op)
       (= cage-result (abs (- (first vlst) (second vlst))))]
      [(symbol=? '* op)
       (= cage-result (foldr * 1 vlst))]
      [(symbol=? '/ op)
       (or (= cage-result (/ (first vlst) (second vlst)))
           (= cage-result (/ (second vlst) (first vlst))))]
      [(symbol=? '= op)
       (= cage-result (first vlst))])))

;; Tests:
(check-expect (guess-valid? puzzle3partial) true)

;;==============================================================================
;; Part (f)

;; (apply-guess puz) converts all guesses in puz into their corresponding numbers
;; and removes the first contraint from puz's list of contraints
;; apply-guess:  Puzzle -> Puzzle
;; Examples:

(define (apply-guess puz)
  (local [(define apply-guess/helper (foldr (lambda (w x) (cons (foldr (lambda (y z) (cond
                                                                                       [(guess? y) (cons (guess-number y) z)]
                                                                                       [else (cons y z)]))
                                                                       empty
                                                                       w) x)) empty (puzzle-board puz)))]
    (make-puzzle (puzzle-size puz)
                 apply-guess/helper
                 (rest (puzzle-constraints puz)))))

;; Tests:
(check-expect (apply-guess puzzle3partial)
              (make-puzzle
               2 
               (list
                (list 'a 1)
                (list 'c 2))
               '((c 2 =)
                 (a 1 =))))  

;;==============================================================================
;; Part (g)

;; (neighbours puz) produces a list of next puzzles after puz in
;; the implicit graph
;; neighbours: Puzzle -> (listof Puzzle)
;; Examples:
(check-expect (neighbours puzzle3)
              (list 
               (make-puzzle 
                2 
                (list 
                 (list 'a (make-guess 'b 1)) 
                 (list 'c 'b)) 
                '((b 3 +) 
                  (c 2 =)
                  (a 1 =)))
               (make-puzzle 
                2 
                (list 
                 (list 'a (make-guess 'b 2)) 
                 (list 'c 'b)) 
                '((b 3 +) 
                  (c 2 =)
                  (a 1 =)))))

(define (neighbours puz)
  (cond
    [(false? (find-blank puz)) empty]
    [(and (equal? 'guess (find-blank puz))
          (guess-valid? puz)) (list (apply-guess puz))]
    [(and (equal? 'guess (find-blank puz))
          (not (guess-valid? puz))) empty]
    [else (map (lambda (val)
                 (make-puzzle (puzzle-size puz)
                              (place-guess (puzzle-board puz)
                                           (find-blank puz)
                                           val)
                              (puzzle-constraints puz)))
               (available-vals puz (find-blank puz)))]))

;; Tests:
(check-expect (neighbours puzzle2soln) empty)
(check-expect (neighbours puzzle3partial)
              (list 
               (make-puzzle
                2 
                (list
                 (list 'a 1)
                 (list 'c 2))
                '((c 2 =)
                  (a 1 =)))))  


;; This is just the find-route function from Module 12, slides
;; 31-37.  (Read a bit ahead if you want the deatils.) The explicit
;; graph G has been removed, and the termination condition (the desired
;; destination) is when the puzzle is complete (that is, find-blank
;; returns false).

;; (solve-kenken orig draw-option) finds the solution to a KenKen puzzle,
;; orig, or returns false if there is no solution.  A visual representiation
;; of the solution may be draw depending on the value of draw-option
;; solve-kenken: Puzzle Sym -> (anyof Puzzle false)
;; requires:  draw-option is one of 'off, 'norm, 'slow, 'fast
;; Examples:
(check-expect (solve-kenken puzzle1 'off) puzzle1soln)

(define (solve-kenken orig draw-option)
  (local
    [(define setup (puzzle-setup orig draw-option))
     (define (solve-kenken-helper to-visit visited)
       (cond
         [(empty? to-visit) false]
         [else (local
                 [(define draw (draw-board (first to-visit) draw-option))]
                 (cond
                   [(boolean? (find-blank (first to-visit))) (first to-visit)]
                   [(member (first to-visit) visited)
                    (solve-kenken-helper (rest to-visit) visited)]
                   [else
                    (local [(define nbrs (neighbours (first to-visit)))
                            (define new (filter (lambda (x) (not (member x visited))) nbrs))
                            (define new-to-visit (append new (rest to-visit)))
                            (define new-visited (cons (first to-visit) visited))]
                      (solve-kenken-helper new-to-visit new-visited))]))]))]
    (solve-kenken-helper (list orig) empty)))

;; Tests:
(check-expect (solve-kenken puzzle3partial 'off) false)
;; The time special form shows you the number of milliseconds spent
;; evaluating the given expression.  The first number (cpu time) is
;; the important one.
(check-expect (time (solve-kenken puzzle2 'norm)) puzzle2soln)

**Comment by samth** [comment]
Thanks!

**Comment by Vishesh-Gupta** [comment]
Your welcome. Also is it possible to know from your team about the reason why it was crashing as I really enjoy using racket and currently use it for studying in university.

**Comment by samth** [comment]
It looks like this needs another file called `kenken-draw.rkt`. Can you provide that as well?

**Comment by Vishesh-Gupta** [comment]
Sure.

(module a10 scheme
  (require racket/gui/base)
  (require racket/draw)
  
  (define (get-size puzz)
    (vector-ref (struct->vector puzz) 1))
  
  (define (get-board puzz)
    (vector-ref (struct->vector puzz) 2))
  
  (define (get-constraints puzz)
    (vector-ref (struct->vector puzz) 3))
  
  (define (get-guess-symbol gue)
    (vector-ref (struct->vector gue) 1))
  
  (define (get-guess-number gue)
    (vector-ref (struct->vector gue) 2))
  
  (define font-exp (make-object font% 5 'default))
  
  (define font-val (make-object font% 40 'default))
  
  (define square-size 50)
  
  (define blank-board false)
  
  (define blank-constraints false) 
  
  (define (first-occur ch lst)
    (cond
      [(empty? lst) false]
      [(symbol=? ch (first lst)) 0]
      [else (add1 (first-occur ch (rest lst)))]))
  
  (define (flatten list)
    (cond
      [(empty? list) empty]
      [else (append (first list) (flatten (rest list)))]))
  
  (define (get-grid-x sec grid)
    (remainder (first-occur sec (flatten grid))
               (length grid)))
  
  (define (get-grid-y sec grid)
    (quotient (first-occur sec (flatten grid))
              (length grid)))
  
  (define (gen-exp func total)
    (cond
      [(symbol=? '* func) (string-append (number->string total) "x")]
      [(symbol=? '= func) (number->string total)]
      [else (string-append (number->string total)
                           (symbol->string func))]))
  
  (define (invert-grid grid)
    (cond
      [(empty? (first grid)) empty]
      [else (cons (foldr (lambda (x y) (cons (first x) y)) empty grid)
                  (invert-grid (map rest grid)))]))
  
  
  (define board-frame (new frame% [label "Solve-KenKen"]
                           [width (* 8 square-size)]
                           [height (+ 22 (* 8 square-size))]
                           [x 50]
                           [y 50]))
  
  (define board-canvas (new canvas% [parent board-frame]))
  
  (define board-dc (send board-canvas get-dc))
  
  (define (resize-frame new-size)
    (begin (show-board false)
           (set! board-frame (new frame% [label "Solve-KenKen"]
                                  [width (* 2 new-size square-size)]
                                  [height (+ 22 (* 2 new-size square-size))]
                                  [x 50]
                                  [y 50]))
           (set! board-canvas (new canvas% [parent board-frame]))
           (set! board-dc (send board-canvas get-dc))
           (send board-dc set-scale 2 2)
           (show-board true)))
  
  (define (puzzle-setup puzz draw-option)
    (cond 
      [(not (symbol=? draw-option 'off))
       (begin
         ;create the best aproximation of an empty board
         (set! blank-board (map (lambda (x) (map (lambda (y)
                                                   (cond 
                                                     [(struct? y) (get-guess-symbol y)]
                                                     [(number? y) 'empty]
                                                     [else y])) x))
                                (get-board puzz)))
         (set! blank-constraints (get-constraints puzz))
         (resize-frame (get-size puzz)))]))
  
  
  (define (show-board bool)
    (send board-frame show bool))
  
  (define (draw-board puzz draw-option)
    (cond
      [(not (symbol=? draw-option 'off))
       (local
         [(define (draw puzz)
            (begin
              (send board-dc clear)
              (send board-dc set-pen "black" 6 'solid)
              (local
                ;draw the separating lines for a single row
                [(define (draw-row-vert row x-coord y-coord)
                   (cond
                     [(empty? (rest row)) (begin
                                            (send board-dc set-pen "black" 3 'solid)
                                            (send board-dc draw-line x-coord y-coord x-coord (+ square-size y-coord)))]
                     [(symbol=? (first row) (first (rest row))) (begin 
                                                                  (send board-dc set-pen "grey" 0.2 'solid)
                                                                  (send board-dc draw-line x-coord y-coord x-coord (+ square-size y-coord))
                                                                  (draw-row-vert (rest row) (+ square-size x-coord) y-coord))]
                     [else (begin
                             (send board-dc set-pen "black" 2 'solid)
                             (send board-dc draw-line x-coord y-coord x-coord (+ square-size y-coord))
                             (draw-row-vert (rest row) (+ square-size x-coord) y-coord))]))
                 
                 ;draw separating lines for each row
                 (define (draw-grid-vert grid y-coord)
                   (cond
                     [(empty? grid) (begin
                                      (send board-dc set-pen "black" 3 'solid)
                                      (send board-dc draw-line 0 (* (get-size puzz) square-size)
                                            (* (get-size puzz) square-size) (* (get-size puzz) square-size)))]
                     [else (begin
                             (draw-row-vert (first grid) square-size y-coord)
                             (draw-grid-vert (rest grid) (+ square-size y-coord)))]))]
                
                (draw-grid-vert blank-board 0))
              
              (local
                [;switch the rows and columns so that columns can be easilly worked with
                 (define invert-puzzle (invert-grid blank-board))
                 ;draw separating lines for a column
                 (define (draw-col-horz row x-coord y-coord)
                   (cond
                     [(empty? (rest row)) (begin
                                            (send board-dc set-pen "black" 3 'solid)
                                            (send board-dc draw-line x-coord y-coord (+ square-size x-coord)  y-coord))]
                     [(symbol=? (first row) (first (rest row))) (begin 
                                                                  (send board-dc set-pen "grey" 0.2 'solid)
                                                                  (send board-dc draw-line x-coord y-coord (+ square-size x-coord) y-coord)
                                                                  (draw-col-horz (rest row) x-coord (+ square-size y-coord)))]
                     [else (begin
                             (send board-dc set-pen "black" 2 'solid)
                             (send board-dc draw-line x-coord y-coord (+ square-size x-coord) y-coord)
                             (draw-col-horz (rest row) x-coord (+ square-size y-coord)))]))
                 
                 ;draw separating lines for each column
                 (define (draw-grid-horz grid x-coord)
                   (cond
                     [(empty? grid)]
                     [else (begin
                             (draw-col-horz (first grid)  x-coord square-size)
                             (draw-grid-horz (rest grid) (+ square-size x-coord)))]))]
                
                (draw-grid-horz invert-puzzle 0))
              
              (send board-dc set-font font-exp)
              
              ;fill in the expressions in the top left of squares
              (map (lambda (reg) 
                     (send board-dc draw-text (gen-exp (third reg) (second reg)) 
                           (+ 2 (* square-size (get-grid-x (first reg) blank-board)))
                           (+ 2 (* square-size (get-grid-y (first reg) blank-board))))) blank-constraints)
              
              (send board-dc set-font font-val)
              
              ;fill in a row with Numeric values
              (define (fill-grid-row row x-coord y-coord board-dc)
                (cond
                  [(empty? row)]
                  [(number? (first row)) (begin
                                           (send board-dc draw-text (number->string (first row)) x-coord y-coord)
                                           (fill-grid-row (rest row) (+ square-size x-coord) y-coord board-dc))]
                  [(struct? (first row)) (begin
                                           (send board-dc draw-text (number->string (get-guess-number (first row))) x-coord y-coord)
                                           (fill-grid-row (rest row) (+ square-size x-coord) y-coord board-dc))]
                  [else (fill-grid-row (rest row) (+ square-size x-coord) y-coord board-dc)]))
              
              ;fill in all Numeric values
              (define (fill-grid grid y-coord)
                (cond
                  [(empty? grid)]
                  [else (begin (fill-grid-row (first grid) 8 y-coord (send board-canvas get-dc))
                               (fill-grid (rest grid) (+ square-size y-coord)))]))
              
              ;add in a delay to make each step readable
              (fill-grid (get-board puzz) 0)
              (cond 
                [(symbol=? 'slow draw-option) (sleep 0.5)]
                [(symbol=? 'fast draw-option) (sleep 0.025)]
                [else (sleep 0.1)])
              true))]
         (draw puzz))]))
  
  (provide  draw-board puzzle-setup))

Also this code for kenken-draw is written by my university professor and the gui for this code is only working in MacOS as she said. Could you kindly look into that too?

**Comment by samth** [comment]
The issue seems to be somewhere in the drawing -- running the unmodified program locks up DrRacket on my Linux machine (and produces artifacts in the window that pops up). But changing the drawing mode in the final test to `'off` makes the whole thing run successfully.

**Comment by Vishesh-Gupta** [comment]
That also is correct but it is perfectly working on a MAC system (my friends). I have tried it myself with the same file. As soon as I shift it to a windows computer, the system crashes and when I run kenken-draw.rkt the grey draw gui window pops up and does nothing in windows.

**Comment by mflatt** [comment]
Changing the `sleep`s in "kenken-draw.rkt" to `sleep/yield` allows the output to show up for me on Windows and Linux. A plain `sleep` doesn't give the GUI a chance to refresh the screen. (The screen is refreshed, anyway, on Mac OS due to the way screen activity is handled there.)

Even without `sleep/yield`, the program should not lock up DrRacket, and I'm not seeing that. @samth, are you saying that you can't click the "Break"/"Kill" button in DrRacket to terminate the program?

@Vishesh-Gupta, can you say more about what you're seeing as a crash? Does DrRacket exit, or is it just that the window where you want to see drawing fails to draw or react to any mouse clicks (since it's not handling events)?

**Comment by Vishesh-Gupta** [comment]
@mflatt, The crash is my OS stops with a stop error. It only happens with this file and with some other files. It did not happen till I update the version to v6.8 for racket and after I updated it and the crash started to happen. Happens even now when I downgraded to v6.7 which I was previously using. Also in some cases, it has happened on other .rkt files too.

Also the thing you mentioned for ```sleep/yield``` should I try that?

**Comment by mflatt** [comment]
@Vishesh-Gupta Yes, use `sleep/yield` in place of `sleep` to make the drawing part work. It's possible that change will also solve crashes related to a too-full event queue, although I still don't really understand what you're seeing there.

**Comment by mookie-blaylocks** [comment]
@mflatt , I believe I'm seeing the same error. On a Windows 10 laptop with Racket 6.8 and 6.9, I've had my system crash giving this error 
![image](https://cloud.githubusercontent.com/assets/9343364/25704515/56c9bfd0-309f-11e7-894f-cac00142d2ee.png).

I do not have this error on my Windows 10 desktop pc, which I've been using instead. I'm not sure exactly what's causing the error, as it seems to be any time I'm using DrRacket. My system is otherwise stable and I've tried the Microsoft troubleshooting (updates, drivers, clean boot). The signs point to some application interference with DrRacket and Windows (or Firefox, which is the only other consistent application).

I'd be glad to dig into some crash logs if I can find them and you can tell me what to look for.

**Comment by mflatt** [comment]
@mookie-blaylocks Is your laptop running Windows 10 Creators Update? If so, see #1671 (but it isn't good news).

**Comment by mookie-blaylocks** [comment]
@mflatt Thanks for that! It does appear to be the same bug, as I can reproduce the problem with touchpad scrolling. Most other functions seem to work fine, and scrolling with a usb mouse is also fine. I also confirmed there is no problem with my Thinkpad on Linux, so the bug appears to be Windows specific, as suggested.

**Comment by mflatt** [comment]
I think this has all been resolved long ago.
