### ISSUE TITLE
Surprising lexical scope with for/fold

### ISSUE THREAD

**Issue by LiberalArtist** [racket/racket#1659]
In the expression
```
(for/fold ([x #f])
          ([x (in-value 1)])
  x)
```
I would have expected the second `x`  to shadow the first one (so that the result would be `1`), but in fact this evaluates to `#f`. Is this an error, or intended?

**Comment by stamourv** [comment]
FWIW, I agree that this is confusing, but I'd argue that this should raise a duplicate binding error.
Unfortunately, I can't think of any fix that wouldn't break backwards compatibility.

**Comment by LiberalArtist** [comment]
I would not have been surprised by a duplicate binding error, either.

I also can't think of a backwards-compatible way to fix this, though I wish I could. If programs are relying on the current scoping, I guess at a minimum it should be documented.

**Comment by AlexKnauth** [comment]
I think there's a case that `in-value`'s macro behavior is wrong because it's inconsistent with it's runtime value behavior. Lifting the sequence into a let changes the result:
```racket
> (for/fold ([x #f])
            ([x (in-value 1)])
    x)
#false
> (let ([seq (in-value 1)])
    (for/fold ([x #f])
              ([x seq])
      x))
1
```
The macro behavior is supposed to only be an optimization, and not to change the result from the runtime behavior.

**Comment by toddjonker** [comment]
It appears that the inline `in-value` is behaving differently from other cases, and that the documentation change in bb2f199 based on that behavior is wrong for most cases.
