### ISSUE TITLE
plt-r5rs executable seems broken

### ISSUE THREAD

**Issue by ylluminarious** [racket/racket#1662]
Trying to run the `plt-r5rs` executable with no arguments (which is supposed to make it enter a REPL) triggers the following error:

```
$ which plt-r5rs
/Applications/Racket v6.8/bin/plt-r5rs
$ plt-r5rs
Welcome to Racket v6.8.
R5RS legacy support loaded
null: undefined;
 cannot reference undefined identifier
  context...:
   /Applications/Racket v6.8/share/pkgs/r5rs-lib/r5rs/run.rkt: [running body]
$ 
```

I'm using Racket 6.8 (as seen above) and I installed Racket via [this `.dmg`](https://mirror.racket-lang.org/installers/6.8/racket-6.8-x86_64-macosx.dmg) from the download page. I'm also running on Mac OS X 10.12.5. Is this a bug or am I doing something wrong on my end?

**Comment by mflatt** [comment]
Do you have a "~/.racketrc" file?

I see that `plt-r5rs` was originally meant to load "~/.pltr5rs" instead, but the way it was implemented became broken when ".mzschemerc" was renamed to ".racketrc" (many years ago).

**Comment by ylluminarious** [comment]
@mflatt Ah, yes I do. I have following piece of code in it: `(define nil null)`. That makes things easier for me when I'm working with Racket plus other Lisps, since I get used to typing `nil`. I'll have to keep that in mind for `plt-r5rs`. Thanks a lot for the help and the info.
