### ISSUE TITLE
parser-tools/yacc: option to declare expected number of conflicts

### ISSUE THREAD

**Issue by bnoordhuis** [racket/racket#1669]
I'd like to request the Racket equivalent of GNU Bison's `%expect <n>` ([ref](https://www.gnu.org/software/bison/manual/html_node/Expect-Decl.html#Expect-Decl)).

I have a grammar with a benign 'dangling else' shift/reduce conflict.  It would be nice to be able to suppress the warning but still get alerted when other conflicts appear or disappear.

I volunteer to do the work if there is consensus that this is an acceptable feature.  Would it make sense to add separate options for shift/reduce and reduce/reduce conflicts?

EDIT: Please accept my apologies if I should have requested this over at https://github.com/racket/parser-tools/issues instead.

**Comment by mflatt** [comment]
I think we'd be happy to have that feature added. I don't have an opinion on separate shift/reduce and reduce/reduce expects.

Yes, https://github.com/racket/parser-tools/issues is a better place for the issue, but it doesn't matter that much. A pull request will only work over there, of course.
