### ISSUE TITLE
DrRacket stop button cannot stop printing quickly (when there are no newlines)

### ISSUE THREAD

**Issue by endobson** [racket/racket#1677]
The following programs have significantly different behavior when the stop and then kill button is pressed.
```
#lang racket
(for ([x 100000])
  (display x))
```

```
#lang racket
(for ([x 100000])
  (displayln x))
```

The first takes so long to quit that it seems like it never will. The second takes a while but much shorter but eventually stops with the expected 'User break' in the interaction window and pop up about the "Execution thread being killed.". I would expect that the output to stop soon after I stop the execution thread.

In addition the following program:
```
#lang racket
(read)
(for ([x 100000])
  (display x))
```
Under the following steps:
1. Run.
2. Enter input.
3. Let loop run for a bit.
4. Stop and kill.
5. Click run again.

One still sees input coming into the new version of the interactions window.

**Comment by sorawee** [comment]
Yep, I experienced all these three issues since I started using Racket too.
