### ISSUE TITLE
Installing DrRacket with raco throws countless errors

### ISSUE THREAD

**Issue by HiPhish** [racket/racket#1680]
Hello,

I have Racket installed on macOS via Homebrew Unix-style. Homebrew provides only a minimal Racket installation, so I ran `raco pkg install --auto drracket`, but I get countless errors along the way and in the end DrRacket does not work (and neither other packages presumably). I have attached the stdout and stderror:
[stdout.txt](https://github.com/racket/racket/files/981070/stdout.txt)
[stderr.txt](https://github.com/racket/racket/files/981062/stderr.txt)

A few things of note:
- The Homebrew forumula used to be called `racket`, but has been renamed to `minimal-racket`
- Racket is installed to `Cellar/minimal-racket/6.8`, but raco is not aware of the name `minimal-racket` and installs packages to `Cellar/racket/6.5` for example
- I thought that might be the issue, so I symlinked `Cellar/racket` to `Cellar/minimal-racket` *before* installing the packages, that way everything would be inside `Cellar/minimal-racket`. However, that did not fix any of the problems.

**Comment by leafac** [comment]
Isn’t it weird that the `minimal-racket` formula installs Racket 6.8, but the logs mention version 6.5 as well?

(Isn’t it weird that the `minimal-racket` formula doesn’t install Racket 6.9?)

**Comment by HiPhish** [comment]
Yes, it is. It's like raco thinks that some packages belong to Racket 6.5 and tries to install them there. I don't know much about raco, so no idea how that can be.

**Comment by leafac** [comment]
Sanity check: Does `racket --version` return 6.8?

Also, does `brew cask install racket` work as intended? Or do the versions get mixed up as well? (I know you don’t want to use the cask long-term, so after testing you can `brew cask zap racket`.)

**Comment by LeifAndersen** [comment]
Ya, this is very odd. When I do the same thing it tries to download the v6.8 binaries. I kind of wonder if you are running a different `raco` file (for a different version...)

**Comment by HiPhish** [comment]
> Sanity check: Does `racket --version` return 6.8?
Yes, it does.
> Also, does `brew cask install racket` work as intended?
Yes, it seems to work fine. I have switched to the cask so I can have a working installation for the time being.

> Ya, this is very odd. When I do the same thing it tries to download the v6.8 binaries. I kind of wonder if you are running a different `raco` file (for a different version...)
The odd thing is that some packages are installed for Racket 6.8 and others for Racket 6.5. I know that Homebrew renamed the formula from `racket` to `minimal-racket`, but `racket` as a formula still works. I might have something from before the rename left over, is there a way to wipe out any old aliases (or whatever the correct term is)?

**Comment by leafac** [comment]
> I might have something from before the rename left over, is there a way to wipe out any old aliases (or whatever the correct term is)?

Homebrew was supposed to do that on `brew update`, when it finds an installed package whose name changed. Maybe it messed up that process.

If you start with a fresh Homebrew installation—you can temporarily rename `/usr/local/Homebrew` so you don’t lose your current environment—does the version mismatch persist?

**Comment by HiPhish** [comment]
Update: the problem is gone, either the Homebrew formula got updated or it was because I removed the old name from `Homebrew/Library/Taps/homebrew/homebrew-core/formula_renames.json`.

However, I am getting another error:
```
raco setup: launcher: <gui-bin>/DrRacket.app
call-with-output-file: cannot open output file
  path: /usr/local/bin/DrRacket.app/Contents/PkgInfo
  system error: Permission denied; errno=13
  context...:
   /usr/local/Cellar/minimal-racket/6.9/share/racket/collects/compiler/embed.rkt:150:0: prepare-macosx-mred
   /usr/local/Cellar/minimal-racket/6.9/share/racket/collects/compiler/embed.rkt:1385:0: create-embedding-executable124
   /usr/local/Cellar/minimal-racket/6.9/share/racket/collects/compiler/../racket/contract/private/arrow-val-first.rkt:306:25
   /usr/local/Cellar/minimal-racket/6.9/share/racket/collects/setup/setup-core.rkt:1443:13: for-loop
   /usr/local/Cellar/minimal-racket/6.9/share/racket/collects/setup/setup-core.rkt:1420:8: make-launcher
   /usr/local/Cellar/minimal-racket/6.9/share/racket/collects/setup/setup-core.rkt:1532:8: for-loop
   /usr/local/Cellar/minimal-racket/6.9/share/racket/collects/setup/setup-core.rkt:172:50
   /usr/local/Cellar/minimal-racket/6.9/share/racket/collects/setup/setup-core.rkt:1417:4: for-loop
   /usr/local/Cellar/minimal-racket/6.9/share/racket/collects/setup/setup-core.rkt:71:0: setup-core
   /usr/local/Cellar/minimal-racket/6.9/share/racket/collects/setup/setup.rkt:65:3
   /usr/local/Cellar/minimal-racket/6.9/share/racket/collects/pkg/main.rkt:17:0: setup
   (submod /usr/local/Cellar/minimal-racket/6.9/share/racket/collects/pkg/main.rkt main): [running body]
   /usr/local/Cellar/minimal-racket/6.9/share/racket/collects/pkg/raco.rkt: [traversing imports]
   /usr/local/Cellar/minimal-racket/6.9/share/racket/collects/raco/raco.rkt: [running body]
   /usr/local/Cellar/minimal-racket/6.9/share/racket/collects/raco/main.rkt: [running body]
```
and
```
call-with-output-file: cannot open output file
  path: /usr/local/bin/Racket Documentation.app/Contents/PkgInfo
  system error: Permission denied; errno=13
  context...:
   /usr/local/Cellar/minimal-racket/6.9/share/racket/collects/compiler/embed.rkt:150:0: prepare-macosx-mred
   /usr/local/Cellar/minimal-racket/6.9/share/racket/collects/compiler/embed.rkt:1385:0: create-embedding-executable124
   /usr/local/Cellar/minimal-racket/6.9/share/racket/collects/compiler/../racket/contract/private/arrow-val-first.rkt:306:25
   /usr/local/Cellar/minimal-racket/6.9/share/racket/pkgs/racket-doc/help/installer.rkt:45:4: for-loop
   /usr/local/Cellar/minimal-racket/6.9/share/racket/pkgs/racket-doc/help/installer.rkt:22:2: for-loop
   /usr/local/Cellar/minimal-racket/6.9/share/racket/pkgs/racket-doc/help/installer.rkt:21:0: do-installer
   /usr/local/Cellar/minimal-racket/6.9/share/racket/pkgs/racket-doc/help/installer.rkt:12:0: installer
   /usr/local/Cellar/minimal-racket/6.9/share/racket/collects/setup/setup-core.rkt:863:6: for-loop
   /usr/local/Cellar/minimal-racket/6.9/share/racket/collects/setup/setup-core.rkt:856:2: do-install-part
   /usr/local/Cellar/minimal-racket/6.9/share/racket/collects/setup/setup-core.rkt:71:0: setup-core
   /usr/local/Cellar/minimal-racket/6.9/share/racket/collects/setup/setup.rkt:65:3
   /usr/local/Cellar/minimal-racket/6.9/share/racket/collects/pkg/main.rkt:17:0: setup
   (submod /usr/local/Cellar/minimal-racket/6.9/share/racket/collects/pkg/main.rkt main): [running body]
   /usr/local/Cellar/minimal-racket/6.9/share/racket/collects/pkg/raco.rkt: [traversing imports]
   /usr/local/Cellar/minimal-racket/6.9/share/racket/collects/raco/raco.rkt: [running body]
   /usr/local/Cellar/minimal-racket/6.9/share/racket/collects/raco/main.rkt: [running body]
```
I checked the file permissions and they are read-only for all three groups. Full output here: https://pastebin.com/wMnkPduB

**Comment by leafac** [comment]
Indeed, the Homebrew formula for `minimal-racket` [has been modified on 2017-05-20](https://github.com/Homebrew/homebrew-core/commit/6eaaf3851ea632c0a1e3ee5e68a24e4ae2e685df), to update it to Racket 6.9.

I think the part that is failing is not trying to **read** the files, but **write** to them, as part of the installation process. So read-only access is not enough. Can you try giving read+write access? You can try a setup similar to mine, `/usr/local` itself belongs to `root`, but all folders inside (`/usr/local/Cellar`, `/usr/local/bin`, and so forth) belong to my user. The command should be similar to `sudo chown <your-user>:admin -R /usr/local/*`.

**Comment by HiPhish** [comment]
All the directories belong to me already, and even the `DrRacket.app` directory has write permissions. It's only `PkgInfo`, the binary and the icon file that are read-only. Would it be possible that during the build process `DrRacket.app` copied `PkgInfo` with insufficient permissions?

> I think the part that is failing is not trying to **read** the files, but **write** to them, as part of the installation process. So read-only access is not enough.
Don't worry, I know my way around Unix :) I just don't know my way around Homebrew and Racket.

**Comment by leafac** [comment]
> Would it be possible that during the build process `DrRacket.app` copied `PkgInfo` with insufficient permissions?

What happens if you `chmod 644` the file in question and try the installation again?

**Comment by HiPhish** [comment]
I cannot run `raco pkg install --auto drracket`, `raco` complains that `drracket` is already installed. If I were to remove it I guess the same thing would happen again. Speaking of which, how do I remove all the packages? Running `raco pkg remove drracket` complains:

```
raco pkg remove: cannot remove packages that are dependencies of other packages
  dependencies:
   drracket (required by: (racket-doc))
```

**Comment by leafac** [comment]
> I cannot run `raco pkg install --auto drracket`, `raco` complains that `drracket` is already installed.

`raco pkg install` first installs the package—finds it in the catalog, downloads it and so forth—then it calls `raco setup` to do things like compiling the code, installing the documentation, and so on. From the error messages from your listings a few comments above, and `raco` complaining that `drracket` is already installed, I assume the installation went fine, and setup failed.

So, please try `raco setup drracket` after `chmod 644` the problematic file and let’s see how that goes.

> Speaking of which, how do I remove all the packages?

I don’t know if there’s a way to do that, but I believe `raco pkg remove --force drracket` would be a way to start—this command removes the package regardless of dependencies. **Don’t try this**, though, as it might break the installation even further. Try the `raco setup` I mentioned above.

**Comment by HiPhish** [comment]
`raco setup drracket` appears to trash my old `/usr/local/bin/DrRacket.app/` and create a new one which has the same permission problems. The creation date of `/usr/local/bin/DrRacket.app/` after `raco setup drracket` is the current time and the file permissions of `/usr/local/bin/DrRacket.app/Contents/PkgInfo` are back to read-only.

**Comment by mflatt** [comment]
The `PkgInfo` file and others are created as a copy of the ones in `Starter.app`, which is might be `/usr/local/Cellar/minimal-racket/6.9/lib/Starter.app`. Setting permissions there may avoid the error, although I'm not sure that's the right repair.

**Comment by HiPhish** [comment]
@mflatt That solved it. So does that mean the issue is in Racket itself? Should I file a new issue here on GitHub?

The other error I got was the same file `PkgInfo` but in `Racket Documentation.app`, which `raco install` should I run for that one?

**Comment by leafac** [comment]
> The other error I got was the same file `PkgInfo` but in `Racket Documentation.app`, which `raco install` should I run for that one?

I **think** that’d be `racket-doc`.

**Comment by HiPhish** [comment]
```
collection-path: collection not found
  collection: "racket-doc"
  in collection directories:
   /Users/hiphish/Library/Racket/6.9/collects
   /usr/local/Cellar/minimal-racket/6.9/share/racket/collects
   ... [108 additional linked and package directories]
```
`racket-doc` is listed as a dependency of `drracket`. Maybe it is not found because it was implicitly installed along `drracket` and not explicitly requested. I can live without it though.

**Comment by mflatt** [comment]
"racket-doc" is a package, but it's not a collection. You could use either `raco setup --pkgs racket-doc` or `raco setup help`, since "help" is the collection (provided in part by "racket-doc") that installs "Racket Documentation.app".

The normal Racket distribution for Mac OS has a "Starter.app/Contents/PkgInfo" that is writable by the owner, so we could consider this an issue with the homebrew formula. But I think it's better for the executable creator to adjust file permissions as needed, so I'll make that change.

**Comment by mflatt** [comment]
`raco pkg show` will show you explicitly-installed packages, and `raco pkg remove --auto <pkg> ...` will remove all of them (and dependencies) if you list them out as `<pkg> ...`. There's not currently shortcut for removing all installed packages, though.

On closing the issue: Sounds good. (I didn't make the commit above close, because I wasn't sure whether there are any other threads left here.)

**Comment by HiPhish** [comment]
> `raco pkg show` will show you explicitly-installed packages, and `raco pkg remove --auto <pkg> ...` will remove all of them (and dependencies) if you list them out as `<pkg> ...`. There's not currently shortcut for removing all installed packages, though.

That's good enough for me, I can list the packages by hand or if the list grows really large I can write a script that processes the output of `raco pkg show` into an appropriate list for `raco pkg remove`. Now that I think about it, if there was a sort of `--list` flag to `raco pkg show` that lists only the names one could remove all packages using a for-loop in the shell:
```sh
for pkg in `raco pkg show --list`
do
        raco pkg remove --auto "$pkg"
done

# or like this:
raco pkg remove --auto `raco pkg show --list`
```
I'm OK without it, I just think a list option would be more versatile than a "remove all packages" option which can only be used for one purpose.

**Comment by alehed** [comment]
The file `/usr/local/Cellar/minimal-racket/6.9/lib/Starter.app` including the `PkgInfo` is written in  `racket/racket/src/mac/osx_appl.rkt`. This might be the place to fix this issue.
