### ISSUE TITLE
invariant-assertion blames the wrong party

### ISSUE THREAD

**Issue by mfelleisen** [racket/racket#1681]
In  6.9.0.1--2017-04-15(-/f) [3m] running the following code

```
(define unsafe-factorial
  (invariant-assertion
   (-> (and/c integer? (>=/c 0)) (and/c integer? (>=/c 0)))
   (lambda (n)
     (if (zero? n) 
         1
         (* n (unsafe-factorial (- n 10)))))))

(unsafe-factorial 5)
```
yields this error message: 

```
unsafe-factorial: contract violation
  expected: (and/c real? (not/c negative?))
  given: -5
  in: an and/c case of
      the 1st argument of
      (->
       (and/c
        integer?
        (and/c real? (not/c negative?)))
       (and/c
        integer?
        (and/c real? (not/c negative?))))
  contract from: anonymous-module
  blaming: anonymous-module
   (assuming the contract is correct)
  at: unsaved-editor:21.3
```

blaming `anonymous-module` which suggests the surrounding region. I think this blame assignment misguides the developer into thinking that `(unsafe-factorial 5)` must be fixed -- even though the argument clearly satisfies the contract.

**Comment by rfindler** [comment]
The documentation seems pretty clear to me that that's not what this message means. Perhaps you can suggest an edit to it?

**Comment by mfelleisen** [comment]
@rfindler This isn’t about documentation but psychological context and conditioning. We tell people everywhere that blame information helps them discover the bug. When I blame party P via contract C, it is either P (or one of its server modules) or C that is wrong (or both). So I wouldn’t think of fixing P-opposite here. But as it turns out, that’s exactly what we want to fix when things go wrong with invariant-assertion. 

I fully understand that
 (1) the documentation says there is no boundary 
 (2) it also says that because you compile this construct into Racket machinery, you may end up seeing “blame messages” 
 (3) and that these blame messages always blame the surrounding context. 

If I were someone with an intuitive understanding of contracts (from Eiffel or Racket) I wouldn’t read that far. I’d read the name of the ’thing’, skip to the example, see the sentence above (which confirms that this is what I want) and be happily off. Indeed, as someone who knows Racket’s contract system :-) I read the paragraph, decided that it meant the expansion was what I had proposed to Prager and promptly forgot  about it (kind of). 

Does this clarify where I come from? I do not see this as a doc fix. The best I can think of right now is a name fix (invariant-assertion-do-not-read-blame-message). Sorry.

**Comment by rfindler** [comment]
The issue clearly reads as if it were written by someone with a deep knowledge of the contract system (even without looking at the name), so I responded in kind. 

In particular, I don't think that a casual user would jump to the conclusion "blaming `anonymous-module` which suggests the surrounding region". There are concepts there that they won't have internalized yet.

Indeed, I think a casual user would interpret "blaming `anonymous-module`" as "something is wrong with my module", which is exactly what the error message says.

But I also don't understand what you mean when you write " So I wouldn’t think of fixing P-opposite here. But as it turns out, that’s exactly what we want to fix when things go wrong with invariant-assertion." The message is telling you to fix "P". There is no "P-opposite" that I see to fix here.

All that said, it may be easier for us not to talk past each of if you were to provide an edited version of the contract violation message that would have clarified for you. I'll suggest one to start:

```
unsafe-factorial: assertion violation
  expected: (and/c real? (not/c negative?))
  given: -5
  in: an and/c case of
      the 1st argument of
      (->
       (and/c
        integer?
        (and/c real? (not/c negative?)))
       (and/c
        integer?
        (and/c real? (not/c negative?))))
  assertion from: anonymous-module
  at: unsaved-editor:21.3
```

**Comment by mfelleisen** [comment]
> On May 7, 2017, at 8:50 AM, Robby Findler <notifications@github.com> wrote:
> 
> The issue clearly reads as if it were written by someone with a deep knowledge of the contract system (even without looking at the name), so I responded in kind.
> 
> In particular, I don't think that a casual user would jump to the conclusion "blaming anonymous-module which suggests the surrounding region". There are concepts there that they won't have internalized yet.
> 
> Indeed, I think a casual user would interpret "blaming anonymous-module" as "something is wrong with my module", which is exactly what the error message says.
> 
> But I also don't understand what you mean when you write " So I wouldn’t think of fixing P-opposite here. But as it turns out, that’s exactly what we want to fix when things go wrong with invariant-assertion." The message is telling you to fix "P". There is no "P-opposite" that I see to fix here.
> 
> All that said, it may be easier for us not to talk past each of if you were to provide an edited version of the contract violation message that would have clarified for you. I'll suggest one to start:
> 
> 


I apologize for using language that implies I know what’s going on. I should have written it purely from the perspective of someone who (1) read posts on our mailing list (on boundaries and blame and such) and (2) reads ‘blaming . . . ‘ as what it means. 

Here is my suggested edit: 

> unsafe-factorial: assertion violation
>   expected: (and/c real? (not/c negative?))
>   given: -5
>   in: an and/c case of
>       the 1st argument of
>       (->
>        (and/c
>         integer?
>         (and/c real? (not/c negative?)))
>        (and/c
>         integer?
>         (and/c real? (not/c negative?))))
contract from: anonymous-module
  blaming: unsafe-factorial 
   (assuming the contract is correct)
  at: unsaved-editor:21.3

It is the internal function call that triggers the ‘unsafe-factorial’. 

Now I happen to know that the only way to get this with our contract machinery is by crossing a boundary. I also happen to know that this means ‘invariant-assertion’ has to place it outside of the definition of unsafe-factorial. But that’s not the impression that the function definition gives.

**Comment by rfindler** [comment]
I don't understand the paragraph "Now I happen ... function definition gives". Can you elaborate, please?

And maybe this is the same thing, but I'm also not seeing how, in the general case, to get the words that follow the "blaming:" in a way that would specialize to what you wrote. In this example, I could get them by asking what name is syntactically outside the `invariant-assertion` and `define` and other binding forms collaborate to supply that information (but I'm not sure if that is what you had mind for the contract system to get it).

**Comment by mfelleisen** [comment]
@rfindler What I am saying is that I understand how the contract system view forces you to assign blame to the module. (But I tested this on Shriram and Justin at SNAPL and they also see this as a failure of the function itself. FWIW, they are also studying psychological aspects of blame assignment.)

**Comment by rfindler** [comment]
The contract system view does not force me to assign blame to the module. It is a choice I made in the design of invariant-assertion and one I'm happy to change.

My question about how to get the content of the line following the "blaming" seems to still stand, however?

**Comment by mfelleisen** [comment]
Can you explain how to assign blame to the function with the contract system (w/o going to the lower level primitives)?

**Comment by rfindler** [comment]
No, I cannot explain how to assign blame to the function. I think that my inability to do that is what I have been saying all along here. 

I also don't see why my previous comment would lead you to write that question, so let me unpack my actual thinking a little bit?

1) I agree that it is natural to think that you should fix the function in this example

2) I have been saying for a long time that the "blaming" line (and blame in general) is trying to capture the idea "fix this code (or change the contract) to eliminate this error".

3) the current implementation of invariant assertion arbitrarily picks a module boundary and uses both parties the same. 

4) but this choice is clearly wrong because when an assertion fails, all we can say is "fix something in the program". We can't be more specific than that.

5) So I stand by my earlier suggestion and I still think we should just eliminate the blaming line because it has no useful information (it cannot say something more specific than "change your program" ala item 2)

**Comment by mfelleisen** [comment]
> On May 11, 2017, at 7:35 AM, Robby Findler <notifications@github.com> wrote:
> 
> No, I cannot explain how to assign blame to the function. I think that my inability to do that is what I have been saying all along here.
> 
> 

Because I want to name the function. 


> I also don't see why my previous comment would lead you to write that question, so let me unpack my actual thinking a little bit?
> 
> I agree that it is natural to think that you should fix the function in this example
> 
> I have been saying for a long time that the "blaming" line (and blame in general) is trying to capture the idea "fix this code (or change the contract) to eliminate this error".
> 
> 

We have both been saying this, and I directed an entire dissertation on this. Christos’s work confirms all this. 

> 
> the current implementation of invariant assertion arbitrarily picks a module boundary and uses both parties the same.
> 
> 

I am going further. I suspect you cannot pick any “correct pair of names.” 

> 
> but this choice is clearly wrong because when an assertion fails, all we can say is "fix something in the program". We can't be more specific than that.
> 
> So I stand by my earlier suggestion and I still think we should just eliminate the blaming line because it has no useful information (it cannot say something more specific than "change your program" ala item 2)
> 
> 

Are you saying “in general” or “for this specific example”?

**Comment by rfindler** [comment]
re "Are you saying ...": I am saying this in general for `invariant-assertion`. That is, I do not see that there are any natural boundaries to delimit blame assignment when using this construct. If that makes sense to you, then I think the only logical next step is to eliminate the "blaming" part of the error message. (It is essential to keep the source location of the assertion itself, of course.)

Put another way, I see `invariant-assertion` as a way to re-use the contract combinator library to do some useful checking in a context where you don't really have a natural boundary. You still want to know that, say, some expression always produces a function that does something good, but it is some internal part of your program and you just want the checking even though you don't have a boundary. (This is what I understood @dvanhorn 's argument when I first added this construct.)

**Comment by mfelleisen** [comment]
I think removing the "blaming" line from this construct (invariant-assertion) is a good solution here.
