### ISSUE TITLE
Help functions don't work in DrRacket

### ISSUE THREAD

**Issue by ylluminarious** [racket/racket#1685]
I just updated to Mac OS X Sierra 10.12.5 (16F71b) and Racket v.6.9. Unfortunately it seems that the `help` function no longer works from the `racket/help` library. I get this error when I try to get `help` for, say, `define`:

```
> (help define)

Sending to web browser...
  file: /Applications/Racket v6.9/doc/reference/define.html
  anchor: (form._((lib._racket/private/base..rkt)._define))
0:130: execution error: "file:///Applications/Racket%20v6.9/doc/reference/define.html#(form._((lib._racket%2Fprivate%2Fbase..rkt)._define))" doesn’t understand the “open location” message. (-1708)
browser-run: process execute failed: '(#<path:/usr/bin/osascript> "-e" "open location \"file:///Applications/Racket%20v6.9/doc/reference/define.html#(form._((lib._racket%2Fprivate%2Fbase..rkt)._define))\"")
```

This happens in both a normal REPL, the [Geiser](http://www.nongnu.org/geiser/) REPL, and the DrRacket REPL. Additionally, it seems that both Geiser's and DrRacket's documentation systems rely on this library because the documentation mechanisms for both of them no longer work. E.g., if I right-click `define` and click `Search in Help Desk for "define"`  in DrRacket:

![error](https://cloud.githubusercontent.com/assets/4912973/25825144/d5b47772-340f-11e7-9b92-a118d184bed4.png)

I'm not sure whether this is the result of upgrading OS X, Racket, or both. However, it seems that I get the same sort of error message when I try this simple AppleScript command:
```
$ osascript -e "open location \"google.com\""
0:17: execution error: "google.com" doesn’t understand the “open” message. (-1708)
```
[According to Apple](https://developer.apple.com/library/content/documentation/AppleScript/Conceptual/AppleScriptLangGuide/reference/ASLR_cmds.html#//apple_ref/doc/uid/TP40000983-CH216-SW54), this should work fine, but I'm on a beta build of Sierra so maybe they changed it and haven't updated their docs.

**Comment by eatobin** [comment]
I have had the same experience and have opened [jaor/geiser Issue #212](https://github.com/jaor/geiser/issues/212) to report it.

Thank you.

**Comment by stamourv** [comment]
We've changed how the help is opened, which should have fixed this.
If you'd like to try the fix, you can download a nightly build at: pre.racket-lang.org

**Comment by eatobin** [comment]
Thank you but I don't think the nightly build is working. I tried both the 64 bit Ubuntu and Mac versions and they failed. Attached is the error after trying to open DrRacket on my Mac. Thank you for checking on this...
![screen shot 2017-05-21 at 8 26 22 pm](https://cloud.githubusercontent.com/assets/870698/26289318/ae8b8ac8-3e64-11e7-996b-4adab750df3b.png)

**Comment by rfindler** [comment]
When you click on "Report" you should get another window with a huge amount of information. Can you copy and paste that here?

**Comment by eatobin** [comment]
![screen shot 2017-05-21 at 9 05 15 pm](https://cloud.githubusercontent.com/assets/870698/26289946/ab826e8c-3e69-11e7-96ed-15a87409118f.png)

**Comment by ylluminarious** [comment]
@rfindler @eatobin I initially had the same issue as well when I tried to open DrRacket from the nightly build, but the error disappeared after following the directions [found here](https://groups.google.com/d/msg/racket-users/4Bl5OcU6DOI/HmkAWtCVAgAJ). I've run into this before; it seems to be an issue with Sierra's security policy, as noted in the link.

Also, it appears that the new build has fixed help functions all across the board. Thanks!

**Comment by eatobin** [comment]
Thank you @ylluminarious for the fix! Opened DrRacket and `(help and)` from the REPL works as expected. But I think the help documentation in DrRacket in Linux was called from a small icon in the upper right corner of the lower panel that isn't in the attached screen shot from the Mac version?

![screen shot 2017-05-21 at 9 35 49 pm](https://cloud.githubusercontent.com/assets/870698/26290687/ecda2000-3e6e-11e7-8551-af21fb1a942e.png)

**Comment by ylluminarious** [comment]
@eatobin Sorry, I don't use DrRacket on Linux so I can't say.

**Comment by rfindler** [comment]
Are you talking about the blue semicircle with the arrow?

**Comment by eatobin** [comment]
Yes, that's it...

**Comment by rfindler** [comment]
I think that might be something else wrong. I noticed a problem but haven't
had time to investigate.

**Comment by eatobin** [comment]
Okay. Just an FYI. Thanks...

**Comment by ylluminarious** [comment]
@eatobin @rfindler Should I mark this ticket as closed then? It seems to me that the main issue here has been solved.

**Comment by rfindler** [comment]
Sure!

**Comment by eatobin** [comment]
Is there another open issue where I could track the return of the missing
documentation icon in the Mac DrRacket?

**Comment by stamourv** [comment]
FWIW, the issue you saw about opening DrRacket on Mac only applies to nightly builds, not to release builds. Not to say we shouldn't fix it, though. :)

As for the missing documentation icon, I don't think there's an issue for that yet. You're welcome to open one on the `scribble` repository (which is the likely culprit). Thanks for the report!

**Comment by stamourv** [comment]
Turns out this is related to a MacOS bug, and also affects python (c.f. http://bugs.python.org/issue30392). The next version of MacOS should have a fix.

In the meantime, if you can't use nightly builds, or are still seeing issues with nightly builds, here's a workaround.

* In DrRacket, press Cmd+Shift+o and open `net/sendurl`
* Add the line `(set! browser (or browser "Safari"))` after line 161 (on 6.9) 164 (on nightly). Feel free to replace `"Safari"` with the browser of your choice.
* Save and exit DrRacket
* In the shell, run `raco setup`
