### ISSUE TITLE
Incorrect srcloc for contract voilations when debugging is off

### ISSUE THREAD

**Issue by jsmaniac** [racket/racket#1686]
```
#lang racket
(define/contract (foo x) (-> integer? integer?) x)
(foo 'oops)
```

When running this program, in an unsaved new file in DrRacket, with debugging turned off (in the <kbd>Ctrl</kbd>+<kbd>L</kbd> "language options" dialog), the following error message is given:

```
../../nix/store/snxsqgqw89nar5rh4nxc68mgamfzbafx-racket-6.9.0.1/share/racket/collects/racket/contract/private/blame.rkt:159:0: foo: contract violation
  expected: integer?
  given: 'oops
  in: the 1st argument of
      (-> integer? integer?)
  contract from: (function foo)
  blaming: anonymous-module
   (assuming the contract is correct)
  at: unsaved editor:2.18
```

Clicking the red and white cross button opens `blame.rkt`, instead of highlighting the call to `foo` in the currently-opened file.

If the file is saved as `/tmp/file.rkt`, the following message is shown instead, but the red and white cross button disappears, only leaving the stacktrace button (which still points to `blame.rkt`).

```
foo: contract violation
  expected: integer?
  given: 'oops
  in: the 1st argument of
      (-> integer? integer?)
  contract from: (function foo)
  blaming: /tmp/file.rkt
   (assuming the contract is correct)
  at: /tmp/file.rkt:2.18
```

Since in both cases the `blaming: … at: …` part is correct, is there a way to make the error point to the correct location when `(current-continuation-marks)` does not have the right information?

**Comment by rfindler** [comment]
I don't think that there is an easy way. My best guess at a way would be if the runtime system opened up the stacktrace API that it uses so that macros could strategically place additional marks and then `define/contract` could place a mark at all call sites of the functions.

This doesn't seem like a very good idea to me, tho.

**Comment by jsmaniac** [comment]
Hm, I had looked too quickly, the blame information points to the definition of the contracted function (line 2, column 18), not the call.

Feel free to close this as there is no easy fix.

**Comment by jsmaniac** [comment]
I'm closing this for now (enabling debugging info is likely the best solution).
