### ISSUE TITLE
exact-negative-integer? and exact-nonpositive-integer? are missing (but docs mention them)

### ISSUE THREAD

**Issue by jsmaniac** [racket/racket#1688]
The documentation for [`negative-integer?`](http://docs.racket-lang.org/reference/generic-numbers.html#%28def._%28%28lib._racket%2Fmath..rkt%29._negative-integer~3f%29%29) and [`nonpositive-integer?`](http://docs.racket-lang.org/reference/generic-numbers.html#%28def._%28%28lib._racket%2Fmath..rkt%29._nonpositive-integer~3f%29%29) refer to `exact-negative-integer?` and `exact-nonpositive-integer?`, respectively, but neither of these identifiers exist.

I see two possible fixes: either changing the documentation for [`negative-integer?`](http://docs.racket-lang.org/reference/generic-numbers.html#%28def._%28%28lib._racket%2Fmath..rkt%29._negative-integer~3f%29%29) and [`nonpositive-integer?`](http://docs.racket-lang.org/reference/generic-numbers.html#%28def._%28%28lib._racket%2Fmath..rkt%29._nonpositive-integer~3f%29%29), or implement (and document) the two missing functions (and giving them a type in Typed Racket).

**Comment by stamourv** [comment]
On the one hand, it's kind of weird to have these functions be missing, while (1) their siblings exist and (2) their (less useful) inexact analogs exist. On the other, adding those may cause clashes, like adding `positive-integer?` and co did. It's not clear which is better.
Inexact integers just make me sad.

**Comment by Paul-C-Anagnostopoulos** [comment]
No documentation refers to those two nonexistent functions. I think this issue can be closed.
