### ISSUE TITLE
Add ‘match?’, a pattern-matching predicate

### ISSUE THREAD

**Issue by leafac** [racket/racket#1690]
**FEATURE PROPOSAL**

Add `match?` to `racket/match`. It is given a pattern and a subject expression, if the expression evaluates to a value that matches the pattern, then `match?` returns `#t`, otherwise it returns `#f`. Also, as an alternative form, `match?` could be given just a pattern, in which case it returns a predicate function.

Here’s a proposed implementation:

```racket
#lang racket
(require syntax/parse/define)

(define-syntax-parser match?
  [(match? pattern:expr subject:expr)
   #'(match subject
       [pattern #t]
       [_ #f])]
  [(match? pattern:expr)
   #'(match-lambda
       [pattern #t]
       [_ #f])])

(match? `(,c ,d) `(a b)) ; => #t

((match? `(,c ,d)) `(a b)) ; => #t
```

This design follows `redex-match?`.

-----

If you agree with this proposal, please let me know and I’ll send a pull request.

Thanks.

**Comment by samth** [comment]
This seems like a good idea, but I'm not sure about the name. What about
matches?

**Comment by lexi-lambda** [comment]
I thought `matches?` at first, too, but the `match?` name is actually more consistent with `regexp-match?` and `redex-match?`.

**Comment by leafac** [comment]
We need to consider [potential conflicts](https://docs.racket-lang.org/search/index.html?q=match%3F). Particularly interesting is that it seems [`match?` was a thing](https://docs.racket-lang.org/unstable/match.html?q=match%3F#(form._((lib._unstable%2Fmatch..rkt)._match~3f))) in the past.

**Comment by samth** [comment]
Well, that wasn't any more of thing in the past than now, but it suggests we should use that name. But we do need to make sure there aren't conflicts.

**Comment by winny-** [comment]
Any other conflicts? This would be a very handy syntax :)

**Comment by rfindler** [comment]
It is exported by redex:  http://docs.racket-lang.org/search/index.html?q=match%3F

**Comment by leafac** [comment]
1. Convenience.
2. [`unstable/match` “is deprecated; use racket/match, instead.”](https://docs.racket-lang.org/unstable/match.html?q=unstable%2Fmatch)

**Comment by samth** [comment]
Right, I think we should have a new package that provides the remaining components of `unstable/match`.

**Comment by stamourv** [comment]
Having to install and require a separate package would cancel out the small convenience that `match?` would give, IMO.

**Comment by rfindler** [comment]
I agree with Sam's sentiment about small packages (both that it would be nice and that perhaps we aren't there).

Is there another name to consider?

**Comment by stamourv** [comment]
`matches?` was suggested, and sounds fine to me, given the constraints.

**Comment by leafac** [comment]
I’d be happy if `matches?` was available when I `(require racket/match)` the same way that `hash-union` is available when I `(require racket/hash)`—meaning it wouldn’t be part of `racket/base` or `racket`.
