### ISSUE TITLE
`raco setup` deletes raco

### ISSUE THREAD

**Issue by alehed** [racket/racket#1706]
### Background

First of all I installed racket via Homebrew (so like `./configure && make && make install`). I did some work using racket 6.6 and had some packages installed via raco in addition to some of my own packages. Recently I upgraded to racket 6.9 and when I wanted to work with my code I got racket version mismatches. To solve that, I ran `raco setup -c && raco setup`. This seemed to rebuild a lot of 6.9 but also 6.6 packages and eventually failed with:

```
raco setup: error: during general install for <pkgs>/racket-doc/help
raco setup:   call-with-output-file: cannot open output file
raco setup:     path: /usr/local/bin/Racket Documentation.app/Contents/PkgInfo
raco setup:     system error: Permission denied; errno=13
```

### Problem

This part seems related to #1680. As suggested there I changed the permissions in the Starter.app ran `brew cleanup` and retried `raco setup -c && raco setup`. This time it failed with:
```
raco setup: error: during launcher setup for <collects>/raco
raco setup:   copy-file: cannot open source file
raco setup:     source path: /usr/local/Cellar/minimal-racket/6.6/lib/racket/starter-sh
raco setup:     destination path: /usr/local/bin/raco
raco setup:     system error: No such file or directory; errno=2
```

The problem seems to come from the fact that `brew cleanup` removed `/usr/local/Cellar/minimal-racket/6.6`.

This effectively uninstalls raco:
```
$ raco setup
-bash: /usr/local/bin/raco: No such file or directory
```

Why does raco setup rebuild old packages from old locations?

`racket --version` does print "Welcome to Racket v6.9".

**Comment by alehed** [comment]
I found out that this was caused by a stale `config.rktd` file. Is there a reason why `config.rktd` is preferred over `config.rktd.default`?

**Comment by mdtusz** [comment]
I'm running into this issue right now and am pretty unfamiliar with raco and racket in general - could you elaborate on how you resolved this?

**Comment by alehed** [comment]
Try to find the file called `config.rkt`. In that same directory ther is a `config.rktd.default` which contains the config you really want (but check it first). Delete the old config and replace it by the new one.

**Comment by mdtusz** [comment]
For future readers, this file likely will be at `/usr/local/etc/racket/`.
