### ISSUE TITLE
Failed expansion/odd error message

### ISSUE THREAD

**Issue by samth** [racket/racket#1717]
This program now fails:

```racket
#lang racket/base
(provide (except-out (all-from-out racket/base) #%module-begin))
(require r5rs)
(provide (except-out (all-from-out r5rs) #%module-begin))
```

with this error message:

```
[samth@huor:/tmp racket-6.9.0.5] r mcons.rkt 
mcons.rkt:2:21: except-out: identifier to remove `#%module-begin' not included in nested provide spec
  at: (all-from-out racket/base)
  in: (except-out (all-from-out racket/base) #%module-begin)
  context...:
   /tmp/racket-6.9.0.5/collects/racket/private/reqprov.rkt:930:5
   /tmp/racket-6.9.0.5/collects/racket/provide-transform.rkt:86:2: expand-export
   /tmp/racket-6.9.0.5/collects/racket/private/reqprov.rkt:733:17: transform-simple
   /tmp/racket-6.9.0.5/collects/racket/private/reqprov.rkt:729:2
   standard-module-name-resolver
```

It did not fail in 6.9. This may be due to https://github.com/racket/r5rs/pull/2 but I don't really see how.

**Comment by mflatt** [comment]
The change is indeed due to racket/r5rs#2.

In the body of the module, `#%module-begin` is the shadowing import from `r5rs`. Formerly, `r5rs` exported the same `#%module-begin` as `racket/base`, so it worked to remove it in that first `provide`. Now, it's a different `#%module-begin`, so it's not a binding that can be removed from the set of imports from `racket/base` in the context of that `provide` form.

**Comment by samth** [comment]
Do you think that's a sign that racket/r5rs#2 should be changed, or that this is just expected breakage?

**Comment by mflatt** [comment]
I think this has to be expected breakage. Changing the binding of an export is never completely backward-compatible, but I don't think the issue can be addressed without the change.

The change also left a gap in the documentation links, which I expect to fix today.

**Comment by lexi-lambda** [comment]
I was almost certain I had pushed those documentations with the original commit, but I just happened to notice yesterday that it got lost somehow. My guess is I forgot to `raco update --link r5rs-doc`, so the changes were to my catalog-installed copy and never made it into git.
