### ISSUE TITLE
"raco setup --tidy foo" tries to write into installation scope  

### ISSUE THREAD

**Issue by bremner** [racket/racket#1718]
not sure if this is a bug or a documentation flaw, but as a non-root user (using debian racket packages for 6.9)
e.g. "raco setup markdown" works fine but "racket setup --tidy markdown" fails

> raco setup: docs failure: start-transaction: attempt to write a readonly database
>  error code: 8
> SQL: "BEGIN IMMEDIATE TRANSACTION"
> database: #<path:/usr/share/doc/racket/docindex.sqlite>
>  mode: 'create
>  file permissions: (read)

**Comment by greghendershott** [comment]
I'm commenting here mainly so that I'll get notified about activity, and know what if anything to do in this regard for a few things:

- [Blog post with example using `--tidy`](http://www.greghendershott.com/2017/04/racket-makefiles.html)
- https://github.com/greghendershott/frog/blob/master/Makefile#L18
- https://github.com/greghendershott/frog/blob/master/Makefile#L18
- https://github.com/greghendershott/markdown/blob/master/Makefile#L23

It might turn out I should just delete the `--tidy` for compatibility with a range of Racket versions.

**Comment by mflatt** [comment]
The `--tidy` flag isn't specific to the named collections. So, if you want to tidy only in the user scope, `--tidy --avoid-main` should work.

When `raco pkg` subcommands call `raco setup`, they use `--tidy` in various situations, but they also add `--avoid-main` or `--no-user`, depending on whether the relevant packages were in user or installation scope.

**Comment by greghendershott** [comment]
Thank you for the explanation. I misunderstood the meaning and purpose of `--tidy`. I'll stop using it.

**Comment by sorawee** [comment]
@bremner does https://github.com/racket/racket/commit/31d82eb9a624b59d2d28f0206ef9ee8cfb84711c help with the problem you had?

**Comment by greghendershott** [comment]
By the way, I did eventually update my blog post that was setting a bad example: https://github.com/greghendershott/blog/commit/f487bda88e4cccad3585623a7e772ffc34f5d73e

**Comment by mflatt** [comment]
This is all resolved, right?

**Comment by bremner** [comment]
Matthew Flatt ***@***.***> writes:

> This is all resolved, right?
>

Apologies for the delay in replying. I think there still some issues,
perhaps specific to my configuration. I attach output from "raco setup
--tidy plait" and /etc/racket/config.rktd

**Comment by mflatt** [comment]
Thanks, @bremner, but that still looks like the intended behavior. Unlike other things, the action of `--tidy` is not constrained to the named collection. You'd need to use `--tidy --avoid-main` to avoid trying to modify the installation space.

**Comment by bremner** [comment]
I re-read the docs for setup --tidy and I see they mention --avoid-main. So, I'll close the issue.
