### ISSUE TITLE
Windows 10 crash

### ISSUE THREAD

**Issue by modac666** [racket/racket#1720]
Racket v6.9, both 32-bit and 64-bit versions cause my Windows 10 to crash. I get a stop code: UNEXPECTED_KERNEL_MODE_TRAP. This error started occurring right after I installed "Feature update to Windows 10, version 1703".

**Comment by mflatt** [comment]
Please see #1671. As noted at the end of the thread, the current snapshot build may work around the OS bug well enough for your machine.

**Comment by modac666** [comment]
Yes, thank you. The snapshot build worked for me.
