### ISSUE TITLE
read (compiled): ill-formed code

### ISSUE THREAD

**Issue by Syntacticlosure** [racket/racket#1722]
I am learning how to create a new language in racket,so i wrote the code below `：`
```
#lang racket
(require syntax/strip-context parser-tools/lex racket/port)
(provide (rename-out [lang-read-syntax read-syntax]
                     [lang-read read]))
(define (lang-read-syntax src in)
  (let ((con (port->string in)))
    (strip-context #`(module anything racket
                       (display "Initalizing language\n")
                       (display #,con)))))
(define (lang-read in)
  (syntax->datum (lang-read-syntax #f in)))

(define get-syntax-token
  (lexer [(union "this" "that" "is")
          (values lexeme 'string #f (position-offset start-pos) (position-offset end-pos))]
         [any-char
          (values lexeme 'other #f (position-offset start-pos) (position-offset end-pos))]
         [(eof)
          (values lexeme 'other #f (position-offset start-pos) (position-offset end-pos))]))
```
I tested the new language in another file 'test.rkt' : 
```
#lang reader "newlang.rkt"
test
```
but only got this : read (compiled): ill-formed code [../../../racket/gc2/../src/read.c:4905]
When i asked my friend to test the code,he found nothing wrong with the code.
But why?

**Comment by mflatt** [comment]
That's an unusual error, and it looks like some file has been corrupted.

Can you say more about the version and OS that you're using and how you're running the program (e.g., inside DrRacket)?

If you ran in DrRacket, was a "compiled" directory created alongside your files, and if so, does moving that directory out of the way change the result?

**Comment by Syntacticlosure** [comment]
Thanks for help.
When i restarted the computer, the error disappeared.I  remember that i ran the program in normal way.
So i can only provide the information about racket version(6.9) and OS (windows 10).
It is really a strange error,  and if similar errors appears next time, i will report how it happened.
