### ISSUE TITLE
"hasheqof" is mentioned in the docs but doesn't seem to exist

### ISSUE THREAD

**Issue by LewisAndrewCampbell** [racket/racket#1725]
A function "hasheqof" is described in racket/pkgs/racket-doc/json/json.scrbl, but doesn't seem to be defined anywhere in the repo.

I wanted it to write a validator for some JSON data, so here's what I came up with. 

```racket
(define (hasheqof k? v?) 
  (λ (h)
    (for/and ([(k v) h]) 
       (and (k? k) (v? v)))))
```

**Comment by bennn** [comment]
Can you use `jsexpr?` for your validator?

**Comment by LewisAndrewCampbell** [comment]
No can do. I was checking to see if something was a 'terminal' JSON object, ie `(hasheqof symbol? string?)`.

I think it has more applications than just the json module anyway.

**Comment by bennn** [comment]
How about using the [`hash/c`](http://docs.racket-lang.org/reference/data-structure-contracts.html#%28def._%28%28lib._racket%2Fcontract%2Fprivate%2Fhash..rkt%29._hash%2Fc%29%29)  contract?

```
> (define (hasheqof k v) (and/c hash-eq? (hash/c k v #:flat? #t)))
> ((hasheqof symbol? string?) (hasheq 'a "a" 'b "b"))
#t
```

**Comment by LewisAndrewCampbell** [comment]
That's a better implementation, sure.

But the core problem is that the docs mention a contract that doesn't exist. Shouldn't it exist?

**Comment by samth** [comment]
That, or the docs should be fixed.
