### ISSUE TITLE
Weird behavior with ffi-lib and dlsym.

### ISSUE THREAD

**Issue by elfprince13** [racket/racket#1731]
I'm debugging some code with the FFI library, on OS X.
This:
```racket
#racket
(require ffi/unsafe
         ffi/unsafe/define)


(define gpsm-ffi-lib (ffi-lib "libgpsm"
           #:get-lib-dirs (lambda () '("/full/path/elided"))))

(define makeDifference
  (get-ffi-obj "makeDifference" gpsm-ffi-lib (_cpointer 'void*)
    (lambda ()
      (error 'gpsm-ffi-lib
             "installed gpsm-ffi-lib does not provide \"makeDifference\""))))
```
Fails with the error thunk provided. If I go through the `define-ffi-definer` interface:
```racket
#racket
(require ffi/unsafe
         ffi/unsafe/define)
(define gpsm-ffi-lib (ffi-lib "libgpsm"
           #:get-lib-dirs (lambda () '("/full/path/elided"))))
(define-ffi-definer define-gpsm gpsm-ffi-lib)
(define-gpsm makeDifference (_cpointer 'void*))
```
Then I get the following error message showing a call to `dlsym`:
```
ffi-obj: couldn't get "makeDifference" from #<path:/full/path/elided/libgpsm.dylib> (dlsym(0x137548310, makeDifference): symbol not found)
```
On the other hand, this C++ code using `dlsym` directly, works fine, when the same `/full/path/elided` is provided on the command line as an argument.

```c++
#include <dlfcn.h>
#include <iostream>
#include <string>

int main(int argc, const char *argv[]){
	int ret = 0;
	if(argc != 2){ std::cerr << "Require a linking path on the command line" << std::endl; ret = 1; }
	else {
		std::string dir(argv[1]);
		std::string fname("libgpsm.dylib");
		std::string path = dir + fname;
		const char * c_path = path.c_str();
		std::cout << c_path << std::endl;

		void* handle = dlopen(c_path, RTLD_LAZY | RTLD_LOCAL);
		if(handle == nullptr){
			std::cerr << dlerror() << std::endl; ret = 1;
		} else {
			std::cout << "lib opened successfully" << std::endl;

			void* makeDifferenceLoc = dlsym(handle, "makeDifference");
			if(makeDifferenceLoc == nullptr) std::cerr << dlerror() << std::endl;
			else{ std::cout << "found makeDifference" << std::endl; }

			dlclose(handle);
		}
	}

	return ret;
}
```
Am I doing something obviously wrong, or is there perhaps a bug in the Racket FFI libraries?

**Comment by elfprince13** [comment]
Perhaps more strangely - it appears to depend on which Racket binary I use. If I compile my own, and run it from the command-line, it works without errors. If I use an official DrRacket download, it does not.

**Comment by mflatt** [comment]
Is it possible that you're compiling in 64-bit mode but downloading the 32-bit distribution, or vice versa?

**Comment by elfprince13** [comment]
That seems somewhat plausible. How can I check if the distribution is 32-bit? I don't see anything in the "About Dr Racket" window that seems relevant.

**Comment by mflatt** [comment]
There's probably a simpler way, but I'd use `(system-library-subpath)`.

**Comment by elfprince13** [comment]
Both return `#<path:x86_64-macosx/3m>`; however, I did notice that my built copy is 6.9, and the installed copy is 6.8.
