### ISSUE TITLE
match doesn't work

### ISSUE THREAD

**Issue by Syntacticlosure** [racket/racket#1734]
In some speical cases, match doesn't work properly, such as the code below : 
```
(match `(1 2 3)
  [`(,@(list (? number? x)) ...) x])
```
I expected it to return `(1 2 3), not an error.
I don't know whether it is an bug or a feature, but I hope this problem could be solved.

**Comment by mfelleisen** [comment]
> On Jun 27, 2017, at 9:50 AM, Syntacticlosure <notifications@github.com> wrote:
> 
> In some speical cases, match doesn't work properly, such as the code below :
> 
> (match `(1 2 3)
>   [`(,@(list (? number? x)) ...) x])
> 
> I expected it to return `(1 2 3), not an error.
> I don't know whether it is an bug or a feature, but I hope this problem could be solved.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


Think of match’s pattern language as a DSL that shares features with the surrounding language. Here is what you want: 

> (match `(1 2 3)
    [`(,(? number? x) ...) x])
'(1 2 3)

**Comment by Syntacticlosure** [comment]
What you mentioned is an approach to correct the program, but sometimes my way may be useful.
Consider this example, I want to match numbers in pairs of two : 
```
(match `(1 2 3 4 5 6)
  [`(,@(list (? number? x) (? number? y)) ...) x])
```
It is just like the ~seq pattern in syntax-parse.
``
(syntax-parse #'(1 2 3 4 5 6)
  [((~seq x:number y:number) ...) #'(x ...)])
```
The code returns #'(1 3 5) correctly.

**Comment by mfelleisen** [comment]
Not quite. What I am saying is two things: 

1. the DSL of match is distinct from the one for syntax-parse and does not allow the pattern you wrote down. 

2. and yes, to get the original example to work, I gave you a replacement expression. 

As Gerry Sussman used to say “I hate pattern matching. All pattern languages are distinct and none does what I want in all situations.”  Well, it’s not quite a quote but that’s what he said when we Indianans requested considering of extend-syntax for the follow-up discussion of R3RS in the 80s.

**Comment by Syntacticlosure** [comment]
Thank for help!

**Comment by samth** [comment]
Unfortunately, the semantics of the splicing/quasiquote behavior has never been documented to my knowledge, but I don't think this has ever worked in implementations of `match`.
