### ISSUE TITLE
racket-test-core file: "tcp-connect: connection failed; host not found"

### ISSUE THREAD

**Issue by juanfra684** [racket/racket#1738]
Racket 6.9.0.6 on OpenBSD -current:
```
Section(file)
ERROR: tcp-connect: connection failed;
 host not found
  address: ::1
  port number: 12325
  system error: no address associated with name; gai_err=-5
```
The host doesn't exists so the test fails. That's fine but "racket -f quiet.rktl" stops here and doesn't continue with the following tests.

**Comment by mflatt** [comment]
Is this a new problem? That is, does Racket 6.9 report a different error for `(tcp-connect "::1" 12325)`?

It looks like the test currently detects an absence of IPv6 by looking for an "Address family not supported by protocol" error message, which is not great, but would make sense if IPv6 is disabled for localhost but supported by getaddrinfo. The error you're getting suggests that numeric IPv6 addresses are not recognized by getaddrinfo.

**Comment by juanfra684** [comment]
I see a similar error with 6.9.

BTW, Racket only fails when `/etc/resolv.conf` includes the line `family inet4`.

**Comment by mflatt** [comment]
I'll fix the test. Thanks for the tip on configuring to provoke the problem!
