### ISSUE TITLE
Request: Support track pad/scroll wheel in panel%

### ISSUE THREAD

**Issue by LiberalArtist** [racket/racket#1743]
Currently, scrolling only can be done by explicitly clicking on the scroll bar. For example, see `DrRacket` > `Preferences` > `Colors` > `Color Schemes`.

**Comment by dfeltey** [comment]
I filed an issue on racket/gui about this a while ago: https://github.com/racket/gui/issues/68

It's not immediately clear how to fix this because I think the scrolling supported by canvas is implemented at a pretty low level.

**Comment by sorawee** [comment]
Close as dup of racket/gui#68.
