### ISSUE TITLE
Nondeterministic results from expander: "cannot find exports to restore imported renamings"

### ISSUE THREAD

**Issue by david-christiansen** [racket/racket#1746]
Here's the test file:
```
#lang racket

(module logic racket/base
  (struct >> (hypotheses goal))
  (provide (struct-out >>)))
(require 'logic)


(module+ test
  (module proof-module racket
    (require (submod ".."  ".." logic))
    (provide here)
    (define-namespace-anchor here))

  (require 'proof-module)
  (with-input-from-string "(>> '() (void))"
    (thunk (eval (read) (namespace-anchor->namespace here)))))
```

# Reproduction

1. Make a new directory
2. Paste the test file into "test.rkt"
3. Run `raco test .`
4. Run `raco make test.rkt`
5. Run `raco test .`

# Expected behavior

I expect that both runs of `raco test` will have the same output

# Observed behavior
```
$ raco test .
raco test: (submod "./test.rkt" test)
#<|>>|>
$ raco make test.rkt 
$ raco test .
raco test: (submod "./test.rkt" test)
compiled/expanded code out of context; cannot find exports to restore imported renamings for module: (submod 'expanded module logic)
  context...:
   (submod /home/davidchr/tmp/buggy/test.rkt test): [running body]
   (submod /usr/share/racket/pkgs/compiler-lib/compiler/commands/test.rkt process): [running body]
test.rkt: raco test: non-zero exit: 1
1/1 test failures
```

**Comment by david-christiansen** [comment]
I should add that this is using the Debian packages for Racket 6.9, but similar failures popped up in Travis for a project in 6.8 and HEAD.

**Comment by mflatt** [comment]
This seems definitely like a bug to me. The new expander (as used in "racket7") appears to work correctly. Just to make sure, is this bug an obstacle for your work – which would mean that ignoring it for 6 months is a very bad option?

**Comment by david-christiansen** [comment]
I have a workaround, which is to take some code that was in submodules and move it to the surrounding module, so it's not getting in my way immediately.

Thanks for the concern!

**Comment by mflatt** [comment]
Ignoring for 6 months (or somewhere between 6 months and 4 years) appears to have worked.
