### ISSUE TITLE
Change "except" to "accept" in docs

### ISSUE THREAD

**Issue by Borderliner** [racket/racket#1750]
On the ["Quick: An Introduction to Racket with Pictures"](https://docs.racket-lang.org/quick/index.html) page, part 6 (Functions are Values), right above this code:

```
(define (series mk)

(hc-append 4 (mk 5) (mk 10) (mk 20)))
```
The word "except" should be changed to "accept".
`...you can define functions that expect other functions as arguments:`
to
`...you can define functions that accept other functions as arguments:`

**Comment by bennn** [comment]
Thanks for the note; I think we will merge this after Racket v6.10 is released

**Comment by samth** [comment]
No reason not to merge now though.

**Comment by bennn** [comment]
Wouldn't a release manager need to cherry-pick it onto the branch?
(I know that's a tiny thing)

**Comment by samth** [comment]
No, releases are cut from the `release` branch. You can just click "Merge" on your PR without affecting the release.

**Comment by rfindler** [comment]
The word "except" does not appear?

But maybe this is easily misread so the change is a good idea regardless?

Robby

**Comment by Borderliner** [comment]
So why don't you work on a `dev` branch, and merge on `master`? Anyway thanks for the quick action.

**Comment by stamourv** [comment]
Just merged @bennn's fix. Thanks for the report!
