### ISSUE TITLE
Using 'integer->integer-bytes' with 8-bit integers?

### ISSUE THREAD

**Issue by HiPhish** [racket/racket#1754]
Hello everyone,

I am curious as to why the `integer->integer-bytes` function only works for integers of two, four or eight bytes length, but not those of one byte length. For positive integers
```racket
(integer->integer-bytes n 1 #t)
```
would be the same as
```racket
(bytes n)
```
but in order to account for negative integers I need to do bit-fiddling like this:
```racket
(bytes (if (< n 0) (bitwise-ior #b10000000 (abs n)) n))
```
On top of that I have to add all sorts of extra boilerplate to figure out whether the integer is eight or more bits long. It would be much simpler if `integer->integer-bytes` offered a unified interface for all integers up to a certain size (i.e. eight in this case).

Is there a technical reason for not supporting 8-bit integers?

**Comment by mflatt** [comment]
There was no good reason. Thanks to @rain-1 for the patch to add the missing functionality.

**Comment by HiPhish** [comment]
This didn't make it into 6.10, did it?

**Comment by mflatt** [comment]
Correct. The change went in well after the branch date for v6.10 (which was July 7).

**Comment by HiPhish** [comment]
OK, thanks. I guess I can expect 6.11 in about another three months then.
