### ISSUE TITLE
error when building the package

### ISSUE THREAD

**Issue by Syntacticlosure** [racket/racket#1761]
I created a package only included one file 'main.rkt' and tried to install it but an error occurred.

Here is the error info :
raco setup: version: 6.9
raco setup: platform: win32\i386 [3m]
raco setup: installation name: 6.9
raco setup: variants: 3m
raco setup: main collects: e:\Program Files (x86)\Racket\collects
raco setup: collects paths: 
raco setup:   C:\Users\jdj\AppData\Roaming\Racket\6.9\collects
raco setup:   e:\Program Files (x86)\Racket\collects
raco setup: main pkgs: e:\Program Files (x86)\Racket\share\pkgs
raco setup: pkgs paths: 
raco setup:   e:\Program Files (x86)\Racket\share\pkgs
raco setup:   C:\Users\jdj\AppData\Roaming\Racket\6.9\pkgs
raco setup: links files: 
raco setup:   e:\Program Files (x86)\Racket\share\links.rktd
raco setup:   C:\Users\jdj\AppData\Roaming\Racket\6.9\links.rktd
raco setup: main docs: e:\Program Files (x86)\Racket\doc
raco setup: --- updating info-domain tables ---
raco setup: --- pre-installing collections ---
raco setup: --- installing foreign libraries ---
raco setup: --- installing shared files ---
raco setup: --- compiling collections ---
raco setup: --- parallel build using 4 jobs ---
raco setup: 3 making: <pkgs>/testpkg
raco setup: 3 making: <pkgs>/testpkg/testpkg
compile-zo: date for newly created .zo file (C:\Users\jdj\AppData\Roaming\Racket\6.9\pkgs\testpkg\testpkg\compiled\tmp15016420581501642058025 @ 2017-8-2 10:47:38) is before source-file date (C:\Users\jdj\AppData\Roaming\Racket\6.9\pkgs\testpkg\testpkg\main.rkt @ 2017-8-2 18:31:50), which appears to be in the future
  context...:
   e:\Program Files (x86)\Racket\collects\compiler\cm.rkt:455:6
   e:\Program Files (x86)\Racket\collects\racket\private\more-scheme.rkt:148:2: call-with-break-parameterization
   e:\Program Files (x86)\Racket\collects\racket\file.rkt:220:5
   e:\Program Files (x86)\Racket\collects\compiler\cm.rkt:363:0: compile-zo*
   e:\Program Files (x86)\Racket\collects\compiler\cm.rkt:572:26
   e:\Program Files (x86)\Racket\collects\compiler\cm.rkt:564:42
   e:\Program Files (x86)\Racket\collects\compiler\cm.rkt:635:0: compile-root
   e:\Program Files (x86)\Racket\collects\compiler\cm.rkt:737:4
   e:\Program Files (x86)\Racket\collects\setup\..\racket\private\more-scheme.rkt:261:28
   [repeats 1 more time]
   e:\Program Files (x86)\Racket\collects\setup\parallel-do.rkt:435:20: loop
raco setup: --- creating launchers ---
raco setup: --- building documentation ---
raco setup: --- installing collections ---
raco setup: --- post-installing collections ---
raco setup: --- summary of errors ---
raco setup: error: during making for <pkgs>/testpkg/testpkg
raco setup:   compile-zo: date for newly created .zo file (C:\Users\jdj\AppData\Roaming\Racket\6.9\pkgs\testpkg\testpkg\compiled\tmp15016420581501642058025 @ 2017-8-2 10:47:38) is before source-file date (C:\Users\jdj\AppData\Roaming\Racket\6.9\pkgs\testpkg\testpkg\main.rkt @ 2017-8-2 18:31:50), which appears to be in the future
DrRacket install: packages installed, although setup reported errors

main.rkt:
`(define a 1) (provide a)`

**Comment by jackfirth** [comment]
Two questions:

- Did you have an `info.rkt` file in addition to the `main.rkt` file?
- Did you try to install this package in a Docker container by chance?

**Comment by Syntacticlosure** [comment]
1.No
2.No

**Comment by mflatt** [comment]
Since the error is about the file timestamp on "main.rkt" – a few hours in the future at the time of the error – can you say more about how you created the file, copied it from somewhere, and/or packed it in some way?

**Comment by Syntacticlosure** [comment]
What you said made me realized that made me realized it might be the way I packed files that caused this problem.
So I try to use the function which system provides instead of using winrar (a software) to build a `zip` file and it works.
Thanks for help.
