### ISSUE TITLE
with-intercepted-logging (and `with-logging-to-port` docs incorrect.

### ISSUE THREAD

**Issue by LeifAndersen** [racket/racket#1766]
The docs for `with-intercepted-logging` (as well as `with-logging-to-port`) claim that it is provided in both `racket` and `racket/logging`. However, as far as I can tell, they are only provided by `racket/logging`. I would be happy to fix this, but I do not know whether the docs here are incorrect, or the implementation is incorrect.

**Comment by stamourv** [comment]
I think the docs are just wrong.

**Comment by bennn** [comment]
I think the implementation is wrong, because the start page for "The Racket Reference" says the `racket` library includes `racket/logging`

http://docs.racket-lang.org/reference/index.html

**Comment by LeifAndersen** [comment]
Well, it certainly isn't re-exprted by racket/main.rkt. So one of them is wrong. Again, I am happy to fix them, I just need to know which way we want to go.

**Comment by mflatt** [comment]
I think the docs should change, instead of the implementation.
