### ISSUE TITLE
Error when copying error message to clipboard

### ISSUE THREAD

**Issue by oltolm** [racket/racket#1768]
I use DrRacket 6.10 on Windows 10 x64 1703. When there's an error in source code an error message is displayed at the bottom. When I click on it I can choose between "Copy Error Message" and "Jump to Error". When I click on "Copy Error Message" a console window with the title "DrRacket" opens and an error dialog with the title "DrRacket Internal Error". The error dialog says:
```
set-clipboard-string method of clipboard%: expects type <string> as 1st argument, given: '("fix-qdf.rkt:16:14: Type Checker: parse error in type; type name `Intger' is unbound in: Intger\n  #(325 6)"); other arguments were: 0
```
The console window says the same.

**Comment by winny-** [comment]
I can confirm on Linux with DrRacket 6.10.

**Comment by gus-massa** [comment]
Is this still happening? I tried in 8.0BC and 8.0CS and in got no error in neither. 

(I guess this has been fixed a long time ago, but nobody closed the bug report.)

**Comment by oltolm** [comment]
Does not happen in 8.0 any more. Closing.
