### ISSUE TITLE
rktio: needs to de-register fds from kqueue/epoll at close?

### ISSUE THREAD

**Issue by jamesbornholt** [racket/racket#1769]
Upgrading to 6.10 caused some of our multithreaded [MemSynth tests](https://github.com/uwplse/memsynth/blob/master/frameworks/alglave/test/unique-test.rkt) to deadlock. The tests spawn multiple threads, each of which spawns Z3 subprocesses through Rosette, to eke out some parallelism while Z3 is running. Once one of the threads returns SAT, the others and their subprocesses are shutdown via custodians (with 'kill mode).

On 6.10 on Linux, the tests sometimes get stuck waiting to read from a Z3 subprocess. (Repro instructions below)

After spelunking and `strace`ing, I think the cause is that [`fd_close_input`](https://github.com/racket/racket/blob/f88704858a844c62591f46944c36b90785633bf9/racket/src/racket/src/port.c#L4814) no longer de-registers fds from the long-term poll set, and so the ltps and its underlying epoll set get out of sync. What seems to happen is that a subprocess with stdout piped to fd 8 gets killed, closing that fd (and so automatically removing it from epoll), then a later new subprocess reuses that fd number as its stdout pipe. But because fd 8 was never de-registered, the second attempt to register it hits in the [ltps hash table](https://github.com/racket/racket/blob/f88704858a844c62591f46944c36b90785633bf9/racket/src/rktio/rktio_ltps.c#L245), and so (on Linux) is not added to the epoll set ([`v->read_handle` is not null](https://github.com/racket/racket/blob/f88704858a844c62591f46944c36b90785633bf9/racket/src/rktio/rktio_ltps.c#L314)).

In 6.9 `fd_close_input` [did de-register](https://github.com/racket/racket/blob/v6.9/racket/src/racket/src/port.c#L7040) fds from epoll, and this issue didn't happen on that version (the fd reuse still happens, but the second attempt to add it to epoll succeeds). A quick git bisect pointed at the rktio patch sequence.

This patch appears to fix the problem for my tests, but I'm not sure about other corner cases, and `fd_close_output` probably needs the same change:

```
diff --git a/racket/src/racket/src/port.c b/racket/src/racket/src/port.c
index 45e9068cd4..6479b42e2c 100644
--- a/racket/src/racket/src/port.c
+++ b/racket/src/racket/src/port.c
@@ -4819,8 +4819,10 @@ fd_close_input(Scheme_Input_Port *port)
   fip = (Scheme_FD *)port->port_data;
 
   rc = adj_refcount(fip->refcount, -1);
-  if (!rc)
+  if (!rc) {
+    (void)scheme_rktio_fd_to_semaphore(fip->fd, MZFD_REMOVE);
     rktio_close(scheme_rktio, fip->fd);
+  }
   else
     rktio_forget(scheme_rktio, fip->fd);
 }
```

---

Repro instructions:
* clone https://github.com/uwplse/memsynth
* `raco pkg install rosette ocelot`
* replace `frameworks/alglave/test/unique-test.rkt` with [this version](https://gist.github.com/jamesbornholt/21d976edee17f879f50aea9a49d8388d) to get to the multithreaded tests more quickly
* `raco test frameworks/alglave/test/unique-test.rkt`
  * will get stuck on a line ending "0 remaining jobs", meaning there's still a thread waiting for Z3 to return some output (and `ps` confirms a Z3 subprocess is still alive, but blocked waiting for input)

**Comment by mflatt** [comment]
Thanks very much for the detailed investigation and report! I think you are completely correct, and I'll add your repair and a test.
