### ISSUE TITLE
error messages get reversed when pict is involved

### ISSUE THREAD

**Issue by mfelleisen** [racket/racket#1774]
This program 

```
#lang racket
(require (only-in pict rectangle colorize))
(require test-engine/racket-tests)
(check-expect (colorize (rectangle 4 4) "blue") (colorize (rectangle 4 4) "red"))
(test)
```

yields this error message: 

```
Ran 1 check.
0 checks passed.
	Actual value differs from the expected value.
..  :eulav lautcA  :eulav detcepxE

 In /Users/matthias/svn/2HtDP/Images/bug-test.rkt at line 4 column 0
```

Note the reversal of the word "actual value". 

Note 1: I have not been able to produce the error with a smaller example, not involving Pict. 
Note 2: Otherwise I would have guessed that it has something to do with test-engine.

**Comment by stamourv** [comment]
FWIW, printing is fine at the command-line.

**Comment by rfindler** [comment]
test-engine is in the htdp repo.

**Comment by rfindler** [comment]
Oh, I see what Matthias means now. It is almost certainly a test-engine bug.

**Comment by samth** [comment]
In general I think we should be ok with managing issues in general on this repo, since lots of people won't know which repo things belong in. Of course, @mfelleisen isn't most people ... :)

**Comment by mfelleisen** [comment]
If you had read my submission, you would know that I know.
