### ISSUE TITLE
Mutable hash table that holds keys and values weakly.

### ISSUE THREAD

**Issue by zaoqi** [racket/racket#1789]
Mutable hash table that holds keys and values weakly.

**Comment by zaoqi** [comment]
@bennn Racket doesn't support it.

**Comment by rfindler** [comment]
It is supported. Please see the documentation on ephemerons.

**Comment by zaoqi** [comment]
@rfindler What's ephemerons?

**Comment by bennn** [comment]
https://docs.racket-lang.org/reference/ephemerons.html?q=ephemeron#%28tech._ephemeron%29
