### ISSUE TITLE
hash/c set/c

### ISSUE THREAD

**Issue by zaoqi** [racket/racket#1790]

**Comment by zaoqi** [comment]
https://docs.racket-lang.org/reference/data-structure-contracts.html#%28def._%28%28lib._racket%2Fcontract%2Fprivate%2Fmisc..rkt%29._promise%2Fc%29%29
@bennn Racket doesn't support set/c and hash/c.
```racket
(set/c c) → contract?
--
c : contract?

(hash/c k v) → contract?
--
k : contract?
v : contract?
```

**Comment by bennn** [comment]
`racket/contract` provides a `hash/c` 
<https://docs.racket-lang.org/reference/data-structure-contracts.html#%28def._%28%28lib._racket%2Fcontract%2Fprivate%2Fhash..rkt%29._hash%2Fc%29%29>

`racket/set` provides a `set/c`
<https://docs.racket-lang.org/reference/sets.html?q=set%2Fc#%28def._%28%28lib._racket%2Fset..rkt%29._set%2Fc%29%29>

**Comment by pnwamk** [comment]
@zaoqi I think you might be better served by using the [Racket users mailing list](https://groups.google.com/forum/#!forum/racket-users) for your questions. You're creating several github issues for things it seems you have done very little research on, or perhaps you just need a few pointers from someone more experience (and the mailing list would be an excellent place to ask for guidance if you are confused and/or cannot find something).

**Comment by zaoqi** [comment]
@pnwamk I can't use *.google.com

**Comment by pnwamk** [comment]
Ah -- my apologies for the oversight.

In my humble opinion, that's definitely something the Racket community should look into (i.e. if users cannot reasonably access the mailing list, where is the next best place to post questions? or is there a workaround? etc) -- and maybe someone else has some suggestions.

Obviously @zaoqi isn't the only person affected by this. I would hope there is something that works well for everyone that isn't the repository's issue tracker as a general forum for Q&A (at least that's my two cents worth on the matter).

**Comment by jackfirth** [comment]
There's the Slack channel [racket.slack.com](http://racket.slack.com/), but you'll need to join via [racket-slack.herokuapp.com](https://racket-slack.herokuapp.com/) first. There's also the #racket IRC channel on freenode.net. @zaoqi, are either of those available to you? Either would likely get you quicker answers to your questions.
