### ISSUE TITLE
immutable-weak-hash

### ISSUE THREAD

**Issue by zaoqi** [racket/racket#1793]

**Comment by bennn** [comment]
What is the problem?

(same for #1790 and #1789 , I'm not sure what the issue is)

**Comment by zaoqi** [comment]
@bennn https://docs.racket-lang.org/reference/hashtables.html:
Racket doesn't support immutable-weak-hash.

**Comment by jackfirth** [comment]
I'm not sure how a weak immutable hash could work. When a key is no longer reachable, it would have to be removed from the hash. But the hash is immutable, so removing it would violate the semantics of immutability.
