### ISSUE TITLE
Delaying large expression hangs when jit is used

### ISSUE THREAD

**Issue by minad** [racket/racket#1800]
Hi,

when delaying a large expression with jit enabled, racket takes a long time (hangs?). 
See https://gist.github.com/minad/a9e5de07ea76a4825c67d55b6e3306cf. I execute the programs as follows:

~~~
racket --no-jit large.rkt        # works
racket --no-jit large_delay.rkt  # works
racket large.rkt                 # works
racket large_delay.rkt           # hangs!
~~~

Running with "racket -W debug large_delay.rkt" shows that the GC is running alot. I am using Racket v6.9 on Linux x86_64.

**Comment by minad** [comment]
Ping! Does someone have an idea why this might happen? I had similar issues a few times with jit activated and large/deeply nested expressions.

**Comment by jpathy** [comment]
To narrow it down further, it fails with `more than 2043` elements in `Scheme_Vector`

From initial cursory look at the code, my guess is something to do with inline allocation failure. Maybe @mflatt could look into it.

**Comment by mflatt** [comment]
I'm working on a repair right now. Thanks @jpathy for investigating, and thanks @minad for the report and ping (because I had missed the report).

**Comment by minad** [comment]
Thanks for fixing the issue!
