### ISSUE TITLE
error message - cannot reference an identifier before its definition

### ISSUE THREAD

**Issue by zaoqi** [racket/racket#1806]
```racket

(s (cons a d) (cons a d))

(define-syntax-rule (s (f x ...) e) 0)
```

**Comment by gfbee** [comment]
If you are suggesting it is a misleading error message: I agree, it used to mislead me, and occasionally a student.
If you expected it to work: the problem is that `s` is used it before its definition. This works:
```
(define-syntax-rule (s (f x ...) e) 0)
(s (cons a d) (cons a d))
```

For reference in this discussion, the error for using a function before its definitions is:
```
s: undefined;
 cannot reference an identifier before its definition
```
which was generated by:
```
(s '(cons a d) '(cons a d))
(define (s x e) 0)
```

**Comment by j3pic** [comment]
I got this error also, with code that used to work in Racket 6.5. I tried entering each expression in the failing function at the REPL, and it worked. It only fails when I try compiling a function. 

I swear, every project I ever decided to write in Racket will eventually come back to bite me.

**Comment by samth** [comment]
@j3pic If you have code that used to work in Racket 6.5 and now doesn't, that's a bug, and I'm happy to take a look at your code and figure out where the bug is.

**Comment by j3pic** [comment]
I'll see if I can find time next week to distill it down to a compact test case.

**Comment by samth** [comment]
If you have a non-compact test case I'll look at that too.

**Comment by j3pic** [comment]
@samth Looks like the problem was I didn't have a macro defined in the Racket 7 REPL.

The stack trace was completely useless, which made it seem like the issue was coming from Racket itself. The problem was in an entirely different function from the one I originally suspected.

**Comment by samth** [comment]
Can you post what the stacktrace was?

**Comment by j3pic** [comment]
```
; let-values*: undefined;                                                                                                                                                                               
;  cannot reference an identifier before its definition                                                                                                                                                 
;   in module: top-level                                                                                                                                                                                
; [,bt for context]                                                                                                                                                                                     
> ,bt                                                                                                                                                                                                   
; let-values*: undefined;                                                                                                                                                                               
;  cannot reference an identifier before its definition                                                                                                                                                 
;   in module: top-level                                                                                                                                                                                
```

`let-values*` is my missing macro. The stack trace was two functions deep. Neither function name appears in the stack trace.

**Comment by j3pic** [comment]
In fact, it kind of looks like `,bt` caused the error to happen again instead of printing a stack trace.

**Comment by samth** [comment]
There are a few different things going on here:

1. At the REPL (unlike in a module) unbound variables are a runtime error. 
2. That runtime error doesn't specify a source location (although maybe it could).
3. When you have small functions plus tail calls, you often get very short or non-existent stack traces.
4. If you have an empty stack trace, xrepl's `,bt` command just re-prints the error message but doesn't say anything about the backtrace, which is potentially confusing.

- 1 is a fundamental feature of how the REPL works.
- 2 could potentially be improved, and I'll look into that.
- 3 is somewhat alleviated by using `errortrace`. Try starting the REPL with `racket -i -l errortrace` and a stack will appear.
- 4 can definitely be improved by printing something like `; (no backtrace)` at the end of that message.

**Comment by samth** [comment]
The above commit implements an improvement to (4). Would that have helped you?
