### ISSUE TITLE
Docs for delay/sync and delay/thread do not document synchronization result

### ISSUE THREAD

**Issue by endobson** [racket/racket#1820]
These events seem to return `(void)` when used with `sync` which is not documented. It seems like returning the actual 'value' would be expected at first glance. But exceptions make that not workable, and thus the result should probably be mentioned in the docs.

**Comment by samth** [comment]
Closed by https://github.com/racket/racket/commit/6ec6b39827760091d9f8f74465a7ebd57a93cc3e
