### ISSUE TITLE
Feature request: raco should have an option can compile all files into one single executable binary.

### ISSUE THREAD

**Issue by netroby** [racket/racket#1825]
Feature request: raco should have an option can compile all files into one single executable binary.

The current `raco distribute` will output a directory with `bin`, `lib` and other folders, can we make it into one  single executable binary  file?

Like golang, rust does. they compile result a single binary file. 
So we can easy to deploy this one single file to anywhere

**Comment by jackfirth** [comment]
The [`raco exe`](https://docs.racket-lang.org/raco/exe.html) command does this, although the executable it creates is essentially an embedding of the module bytecode into the `racket` executable rather than a traditional compiled binary.

**Comment by netroby** [comment]
It still need racket runtime? i see the document said .

`
A stand-alone executable is “stand-alone” in the sense that you can run it without starting racket, gracket, or DrRacket. However, the executable depends on Racket shared libraries, and possibly other run-time files declared via define-runtime-path. The executable can be packaged with support libraries to create a distribution using raco distribute, as described in raco distribute: Sharing Stand-Alone Executables.
`
I mean package all into one single file.
