### ISSUE TITLE
contract violation by collapse-module-path-index

### ISSUE THREAD

**Issue by samth** [racket/racket#1846]
I managed to get `collapse-module-path-index` to produce this contract error:

```
collapse-module-path-index: broke its own contract
  promised: (or/c #f module-path?)
  produced: ''(draw #%contract-defs)
  in: the range of
      (case-> ...)
```

Large contract snipped, and I don't know how to reproduce this in a small way.

**Comment by mflatt** [comment]
I haven't been able to trigger this. If you have a way to replicate the error in a large example, can you change `collapse-module-path-index` to log all of its arguments, and then maybe we'll see how to make an example?

**Comment by samth** [comment]
Here are the inputs for the case that fails:
 ```
cmpi: #<module-path-index:((quote (flonum-error typed-defs)))> #<procedure:...llapse-noctc.rkt:467:7>
```

**Comment by mflatt** [comment]
It looks like there's a bad mode path index there, which I think could only be created internally. That looks specifically like a bad conversion from a resolved module path.

Does using the `modpath` branch of https://github.com/mflatt/racket change the behavior? That adjusts one place that a module path index is created from a resolved module path, although in a place that I thought would only happen with primitive modules.

**Comment by samth** [comment]
That does seem to fix the problem.

**Comment by samth** [comment]
Oh, to replicate the problem yourself, you can probably put a call to `collapse-module-path-index` in the call to `add-mod!` in `typed-racket/env/env-req.rkt` and then recompile `plot`.

**Comment by mflatt** [comment]
I'll try that sometime (so leaving the issue open), but I've pushed the repair as dd585e7ff7db0647531e809477ef121ee3328b84.

**Comment by mflatt** [comment]
The bug is "unexpplained" in the sense that a smal test case was never created, but the bug was in the old expander, which is long gone.
