### ISSUE TITLE
racket-minimal repl do not return a value on wsl (Windows Subsystem for Linux)

### ISSUE THREAD

**Issue by connor2059** [racket/racket#1855]
>bash[enter]
user@computer1:~$ racket [enter]
Welcome to Racket v6.10.1
>(+ 1 2) [enter]
then it just block there with nothing!
why?

**Comment by jummy233** [comment]
Same problem. Maybe it should be regarded as WSL issue.

**Comment by elibarzilay** [comment]
@connor2059 This was probably a WSL issue -- I just tried it with the recent April update, and it works fine.

**Comment by connor2059** [comment]
@elibarzilay Yes, it works fine after I upgrade my os.Thanks!

**Comment by mflatt** [comment]
I saw this in WSL when working on Unicode input from the console (had not updated the OS in a long time), and I made changes as part of handling Unicode input that fixed this problem. So, I guess this one is fixed twice.
