### ISSUE TITLE
Can't open files in OneDrive folder after Windows Update

### ISSUE THREAD

**Issue by TheBeavster** [racket/racket#1856]
Hi, I have a very strange and specific issue. I can't open Racket files from my OneDrive folder after I updated to the Windows Creators Update version 1709 as a part of the Insiders program. Whenever I try to open a file, DrRacket starts loading but fails at the clock icon. Not sure what's going on, but the same file loads if it is stored in any other folder. 
Any help is appreciated. Thanks.

**Comment by CamLV** [comment]
I am having the same issue. Thank you, TheBeavster, I was able to work on my project by moving the folder to a local drive.

**Comment by ROGUE1138** [comment]
The workaround for me is to move my files to another folder. I'm still unsure why DrRacket won't open the files in my OneDrive.

**Comment by mflatt** [comment]
A problem with OneDrive files on Windows 10 Fall Creators Update has been fixed for the upcoming Racket release. If you'd like to try a pre-release version, see pre-release.racket-lang.org.
