### ISSUE TITLE
net/url should respect HTTP_PROXY and HTTPS_PROXY

### ISSUE THREAD

**Issue by bmastenbrook** [racket/racket#1859]
Currently `net/url` looks for the value of the environment variables `http_proxy` and `https_proxy` after looking for `plt_`-prefixed versions of these. `net/url` should also look at the uppercase version of these environment variables as well. Many tools on Linux (such as `curl`) respect `HTTPS_PROXY`, so for some users, their configuration may fail to work out-of-the-box for Racket. This may be particularly a problem for users behind corporate firewalls that mandate proxy usage; `raco pkg` operations might fail for these users even if the rest of their desktop environment appears to work, giving the impression that Racket does not support proxies correctly. (It probably wouldn't hurt to look for `GIT_PROXY` as well, though I'm unaware of any other tools which use this environment variable.)

Additionally, there is an `ALL_PROXY` environment variable which is respected by `curl` as a fallback for any protocol which does not have an explicit environment variable set; it might be worth using this as a fallback for all three protocols as well.

**Comment by lkuper** [comment]
+1.  I got bitten by this because I had only `HTTPS_PROXY` and not `https_proxy` set.

**Comment by jeapostrophe** [comment]
I just pushed a fix to this.

**Comment by samth** [comment]
@jeapostrophe what do you think about `ALL_PROXY`? Also, if you use #1859 in your commit messages it links automatically.

**Comment by jeapostrophe** [comment]
I implemented ALL_PROXY. I think it is best to do whatever is common on these tools to make it so users don't even need to know what Racket is doing if they are in a proxied environment. (It wrote PR1859, which is what has worked for a long time with gnats)

**Comment by samth** [comment]
Since the move to Github, nothing closes Gnats bugs, of course, and PR means something else here. And now I see the `all_proxy` code.

**Comment by lkuper** [comment]
Thanks for the quick fix!
