### ISSUE TITLE
Another Win10 issue?

### ISSUE THREAD

**Issue by blerner** [racket/racket#1863]
A student of mine encountered this today, on Windows 10 built 1703 (*not* FCU): she says, "Recently, when my computer sleeps (with racket open) and I turn it on, this happens which just closes the program... is there a way to fix this or is it normal?"

![image](https://user-images.githubusercontent.com/918464/31920449-08389858-b837-11e7-9f28-fd1b934538d2.png)

**Comment by mflatt** [comment]
We had a handful or reports like this a couple of years back, but we've fixed various things since, and I don't think there have been recent reports like this.
