### ISSUE TITLE
slider% min-value and max-value are -/+16960 on Windows systems

### ISSUE THREAD

**Issue by 7enderhead** [racket/racket#1865]
- (Dr)Racket 6.10.1 on Windows 7
- contracts and documentation say min-value and max-value to be -1000000 and 1000000 respectively
- but the following code makes the values min/max out at -/+16960:

```racket
(new slider%
     [label "minimal Longitude"]
     [parent main-frame]
     [min-value -1000000]
     [max-value 1000000])
```

**Comment by tumdum** [comment]
This does not reproduce on:
```
$ uname -a
Linux prb 4.10.0-37-generic #41-Ubuntu SMP Fri Oct 6 20:20:37 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ racket -v
Welcome to Racket v6.11.
```
This code:
```racket
(define f (new frame% [label "test"]))
(define s (new slider%
     [label "minimal Longitude"]
     [parent f]
     [min-value -1000000]
     [max-value 1000000]))
(send f show #t)
```
run in DrRacket produces window with slider that goes from `-1000000` to `1000000`. So it might be related to either windows or older version of racket.

**Comment by 7enderhead** [comment]
DrRacket 6.11 on Windows 7:

![image](https://user-images.githubusercontent.com/339726/32448807-3e51dc2c-c310-11e7-8319-b4846fe18958.png)

**Comment by 7enderhead** [comment]
- Racket 6.10.1 and 6.11 show correct behaviour on my Linux (Mint 17.1)
- so this seems to be a Windows-specific problem
