### ISSUE TITLE
No 'list-box-column control-event% from list-box% When Clicking Column on Linux

### ISSUE THREAD

**Issue by 7enderhead** [racket/racket#1873]
```racket
#lang racket
(require racket/gui/base)
(define main-frame (new frame% [label "Test"]
                        [width 400]
                        [height 800]))
(send/apply (new list-box%
           [label ""]
           [parent main-frame]
           [choices '()]
           [columns '("col1" "col2")]
           [style '(single column-headers)]
           [callback (lambda (list event) (displayln event))])
      set
      '(("a" "b" "c") ("1" "2" "3")))
(send main-frame show #t)
```
- Racket 6.10.1 on Linux Mint 17.1
  - no 'list-box-column event on column header click (e.g., for sorting)
- Windows 7
  - 'list-box-column event as expected

**Comment by mflatt** [comment]
Sorry for the *very* long delay!

In case an answer is still helpful: adding `'clickable-headers` to the `style` list should make the header clickable and make events reported on all platforms. I'd say it's a bug that you get the events without `'clickable-headers` on Windows.
