### ISSUE TITLE
Erroneous message on docs.r-l.org search page

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#1874]
Going to http://docs.racket-lang.org/search/index.html produces a page with the following message at the top:

> You are searching only your locally installed Racket packages. More results may be available by using the [global search](http://docs.racket-lang.org/search/) that inspects all available packages. [Click here to repeat your search globally.](http://docs.racket-lang.org/search/index.html?)

This is pretty confusing, since not only is it wrong, but the “Click here” message links to the exact same page, itself. I’m not sure why this happened on the global search page, but it looks like the relevant code was introduced in d325e037820542d52a508e2174b34ba873e97827.

@jeapostrophe, perhaps you are the person to look into this?

**Comment by mflatt** [comment]
I'm supposed to configure something to get rid of that, and I forgot...

**Comment by mflatt** [comment]
Fixed?

**Comment by lexi-lambda** [comment]
Yes, it seems fixed now, thanks.
