### ISSUE TITLE
syntax-parse binding arrow points to the wrong binding occurrence

### ISSUE THREAD

**Issue by shhyou** [racket/racket#1875]
In the following code, the binding arrow of `#'e` at B points to the `e` at A.
```
#lang racket/base

(require syntax/parse)

(syntax-parser
  [e #'e]  ; A
  [e #'e]  ; B
  )
```

![stxparse](https://user-images.githubusercontent.com/1910898/32400384-44dc4c7a-c0cd-11e7-969a-c7f04c47c616.jpg)

**Comment by mfelleisen** [comment]
Arguably, this is correct.

**Comment by rfindler** [comment]
I'm not sure what argument you have in mind, but the fact that this one does the more obvious thing seems like a counterargument:

```
(syntax-parser
  [e #'e]
  [f #'f])
```

**Comment by rfindler** [comment]
Also, I'll note that if I rename "f" to "e" (in my example) and then back I get different program, which also seems like a counterargument.

**Comment by shhyou** [comment]
I think I can see that if there is a common prefix, it's better that the implementation do not re-match the prefix and use the same bound variable. But I would against exposing this to the user because:

- Intuitively, the scope first pattern variable `e` should be bound only in its clause.
- Renaming does not work anymore. For example, I cannot rename `thn` and `els` correctly:

```
#lang racket/base

(require (for-syntax racket/base)
         syntax/parse)

(define-syntax (reversed-if _)
  (error 'reversed-if "bad syntax"))

(syntax-parser #:literals (quote reversed-if)
 [(reversed-if thn:expr els:expr '#t)
  #'thn]
 [(reversed-if thn:expr els:expr '#f)
  #'els]
 [(reversed-if thn:expr els:expr con:expr)
  #'(if con thn els)])
```

**Comment by shhyou** [comment]
Apparently this is fixed at some point (perhaps incidentally fixed by the new Syntax Parse interpreter). It'd be great to have a test case for this but that's not urgent.
