### ISSUE TITLE
eval !

### ISSUE THREAD

**Issue by zaoqi** [racket/racket#1881]
```racket
#lang racket
(eval '(λ (x) x) (make-base-empty-namespace))
```

```
λ: unbound identifier;
 also, no #%app syntax transformer is bound in: λ
```
!

```racket
((make-evaluator 'racket) '(file->string "zscm.rkt"))
```
```
. . ../../../../../../../home/zaoqi/bin/racket/collects/racket/file.rkt:720:0: file-size: `read' access denied for zscm.rkt
```
How can I eval it?

**Comment by mflatt** [comment]
An empty namespace really is empty: no `lambda` and no application form. Use `make-base-namespace` or use `namespace-require` to import bindings.

A sandbox created by `make-evaluator` is not allowed filesystem access by default. You could use `call-with-trusted-sandbox-configuration`, but my guess is that you don't want a sandbox.
