### ISSUE TITLE
Support Chrome OS as a release platform

### ISSUE THREAD

**Issue by deeglaze** [racket/racket#1884]
The NaCl SDK should make this a rather easy port. I got a chromebook for work and miss my graphical REPL from DrRacket (I currently have to develop over SSH to a linux box, but I don't get graphics). I'll start the development myself and see what comes out of it.

**Comment by LeifAndersen** [comment]
Oh cool, does GTK+ work with NaCl now?

**Comment by deeglaze** [comment]
There's a demo in webports, so I'm hoping.

**Comment by shhyou** [comment]
Chromebook offers Crostini (a.k.a. Linux (Beta)) since 2019. Except for documentation everything should work.
