### ISSUE TITLE
match

### ISSUE THREAD

**Issue by zaoqi** [racket/racket#1887]
`match` doesn't support
```
`(lambda (,@a . ,r) ,@s)
```

**Comment by soegaard** [comment]
2017-11-12 12:55 GMT+01:00 Zaoqi <notifications@github.com>:

> match doesn't support
>
> `(lambda (,@a . ,r) ,@s)
>
>
> Complete example?


It looks as if you are using not using the syntax from raket/match,
but rather the old syntax from mzlib/match


http://docs.racket-lang.org/mzlib/mzlib_match.html?q=match#%28form._%28%28lib._mzlib%2Fmatch..rkt%29._match%29%29


/Jens Axel

**Comment by AlexKnauth** [comment]
The right way to write that pattern in `racket/match` syntax is either `` `(lambda (,a ... . ,r) ,@s)`` or `` `(lambda (,@(list a ...) . ,r) ,@s)``.

The important difference is that if an `a` pattern restricts the elements in any way, the restrictions will apply to each element of the list separately, not the whole list at once:
```racket
`(lambda (,(? symbol? a) ... . ,r) ,@s)
```
vs. with the other syntax it would have been
```racket
`(lambda (,@(? (listof symbol?) a) ,r) ,@s)
```
Which is much harder for a matching algorithm to deal with.
