### ISSUE TITLE
View documentation doesn't work

### ISSUE THREAD

**Issue by sorawee** [racket/racket#1890]
Consider the code:

```
#lang racket

+
```

Right click on `+` and click "View documentation..."

A Racket internal error dialog pops up with the following message:

```
browser-run: process execute failed: '("vivaldi file:///usr/share/doc/racket/reference/generic-numbers.html#(def._((quote._~23~25kernel)._%2B))")
/bin/sh: 1: Syntax error: "(" unexpected
```

Version 6.10.1, Ubuntu 17.10

**Comment by sorawee** [comment]
(See also #1685 which is closely related)

**Comment by samth** [comment]
This looks like a quoting issue in `browser-run`. In particular, if I change the browser to `vivaldi ` (with an appropriate space I can see this error. The error doesn't happen if I choose one of the pre-existing browsers.

**Comment by mflatt** [comment]
I don't think this is a quoting issue in `browser-run`. The DrRacket preference has the form
```
                -----------------       ----------------
 Command line: |                 |<URL>|                |
                -----------------       ----------------
```
with the intent that it's configured with whatever quoting is needed. Putting just `vivaldi` plus a space and an empty ending string isn't a good setting, while `vivaldi "` and `"` could be a good setting.

I would agree that a configuration that involves string concatenation isn't a great idea, but that's how it's currently set up, and changing <URL> to <URL-with-quotes> can break existing settings.
