### ISSUE TITLE
Compilation target to WebAssembly

### ISSUE THREAD

**Issue by Calibre720** [racket/racket#1893]
With WebAssembly now incorporated as a standard in major browsers and other programming languages like C/C++, Rust, Javascript working to offer WebAssembly compilation target, racket can start working on it too?

I have just found out about racket a day ago (complete noob here), and am fascinated with it. I am learning as fast as I can. This thought arose while chosing whether to invest time in learning and playing with racket. There is a lot of exciting stuff happening on the web-side, and I couldn't see any reason for this lovely new language that I just found to not be making use of it. I am going to start a project and would really like to use racket as my choice....

**Comment by samth** [comment]
Currently, WebAssembly is very low-level, and not really a good target for Racket. It will need at least support for garbage collection and for proper tail calls before it's ready. Fortunately the WebAssembly folks are already working on those features.

Currently, there's an active project compiling Racket to JavaScript, which is a better fit at the moment. You can see that here: https://github.com/vishesh/racketscript
