### ISSUE TITLE
syntax-parse too eagerly checks syntax class

### ISSUE THREAD

**Issue by stchang** [racket/racket#1894]
Below is an example program. I would expect it to print hello once, but it prints it twice.

```racket
#lang racket
(require syntax/parse/define)

(begin-for-syntax
  (define-syntax-class ABC
    (pattern _ #:do[(displayln "hello")])))

(define-syntax-parser test
  [(_ [_:id _:ABC] ... last)
   #'(void)])

;; expect: hello printed once
;; actual: hello printed twice
(test (- 1) (+ 2 3))
```

**Comment by rmculpepper** [comment]
The actual behavior you get is intended. syntax-parse matches ellipses greedily, and it matches the head of a pair pattern before the tail. Here's one way to rewrite the pattern to print only once:

    (_ (~and [_ _] [_:id _:ABC]) ... last)

Alternatively, some support in syntax-parse for effect unwinding could help, but I haven't gotten to it yet.

**Comment by stchang** [comment]
Ok thanks. I tried some older versions and I see it's always been that way. It just feels unintuitive.
