### ISSUE TITLE
Win 10 DLL issue when using plot module and standalone exe

### ISSUE THREAD

**Issue by dougsaylor** [racket/racket#1895]
The following will fail on windows 10 when using a stand alone executable: 

#lang racket
(require plot)
(display "hello")

with 

C:\Users\dsayl\work>hello.exe
ffi-lib: couldn't open "C:\\Program Files\\Racket\\lib\\libintl-8.dll" (The specified module could not be found.; errid=126)

Commenting out plot will work of course. This has been reproduced on several machines. 
![plotfail](https://user-images.githubusercontent.com/33848441/33046217-aca654ae-ce15-11e7-9f14-7c3cdeb0c149.PNG)

**Comment by mflatt** [comment]
Repaired (finally) by the referencing commit in "racket/draw". Thanks for the report!
