### ISSUE TITLE
Build issue in Docker container from ubuntu:latest

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [racket/racket#1897]
My Docker version:

    Docker version 17.09.0-ce, build afdb6d4

My Dockerfile:

    FROM ubuntu:latest

    ###################
    # SYSTEM PACKAGES #
    ###################
    USER root
    RUN apt-get update\
     && apt-get --yes dist-upgrade\
     && apt-get install --yes --no-install-recommends\
        wget \
        bzip2 \
        ca-certificates \
        sudo \
        locales \
        build-essential \
        python-dev \
        unzip \
        libsm6 \
        pandoc \
        libxrender1 \
        inkscape \
        graphviz \
     && apt-get clean \
     && rm -rf /var/lib/apt/lists/*

    ##############
    # SET LOCALE #
    ##############
    RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
        echo 'LANG="en_US.UTF-8"' > /etc/default/locale && \
        dpkg-reconfigure --frontend=noninteractive locales && \
        update-locale LANG=en_US.UTF-8

    #########################
    # ENVIRONMENT VARIABLES #
    #########################
    ENV ROOT_USER root
    ENV DEBIAN_FRONTEND noninteractive
    ENV SHELL /bin/bash
    ENV NON_PRIVILEGED_USER app
    ENV NON_PRIVILEGED_USER_GROUP app
    ENV NON_PRIVILEGED_USER_PASSWORD "blogging-madness"
    ENV HOME "/home/app"
    ENV RACKET_VERSION "6.11"

    #################
    # ADDING A USER #
    #################
    # For more info please check useradd --help or man useradd.
    RUN groupadd -r $NON_PRIVILEGED_USER_GROUP -g 1000 \
     && useradd \
        --uid 1000 \
        --system \
        --gid $NON_PRIVILEGED_USER_GROUP \
        --create-home \
        --home-dir /home/$NON_PRIVILEGED_USER/ \
        --shell /bin/bash \
        --comment "non-privileged user" \
        $NON_PRIVILEGED_USER \
     && chmod 755 /home/$NON_PRIVILEGED_USER/ \
     && echo "$NON_PRIVILEGED_USER:$NON_PRIVILEGED_USER_PASSWORD" | chpasswd

    ##################
    # COMPILE RACKET #
    ##################
    WORKDIR $HOME
    RUN wget -O racket-v${RACKET_VERSION}.zip https://github.com/racket/racket/archive/v${RACKET_VERSION}.zip\
     && echo "96215372239adba522268a62e72422bde88a2d3484f0883154160be457f46915 racket-v${RACKET_VERSION}.zip" | sha256sum -c - \
     && unzip racket-v${RACKET_VERSION}.zip
    WORKDIR racket-${RACKET_VERSION}
    RUN make -j4

    ############
    # FINALIZE #
    ############
    USER $NON_PRIVILEGED_USER
    # ENTRYPOINT ["tini", "--"]

    CMD ["/usr/bin/bash"]

When I build this Dockerfile, I get the following error:

    Resolving "plot-compat" via https://pkgs.racket-lang.org
    Using cached15113857671511385767649 for git://github.com/racket/plot/?path=plot-compat
    raco pkg install: version mismatch for dependency
      for package: gui-lib
      mismatch packages:
       base (have 6.11, need 6.11.0.1)
    make[1]: *** [plain-in-place] Error 1
    Makefile:67: recipe for target 'plain-in-place' failed
    make[1]: Leaving directory '/home/app/racket-6.11'
    Makefile:48: recipe for target 'in-place' failed
    make: *** [in-place] Error 2
    The command '/bin/sh -c make -j4' returned a non-zero code: 2

Seems to be a versioning issue.

**Comment by jackfirth** [comment]
I'm not positive, but I think the Github Releases source for each racket version doesn't set the default package catalog to a release-version-specific catalog, so when the makefile attempts to install various main distribution packages it uses the _latest_ version of those packages from the `pkgs.racket-lang.org` catalog. The latest version of the `plot-compat` package requires a newer version of Racket than 6.11 so attempting to install it from `pkgs.racket-lang.org` fails.

The installers you'd get from `download.racket-lang.org` use a version-specific package catalog that locks the versions of all the main distribution packages so this kind of thing doesn't happen. You should use those instead.

Also, you might find the [`samth/docker-racket-build`](https://github.com/samth/docker-racket-build) repository and/or my [Racket docker images](https://github.com/jackfirth/racket-docker) repository interesting.

**Comment by mflatt** [comment]
This problem was corrected with the v7.0 release (July 2018, two releases after v6.11). For example, I am able to build a Dockerfile like the one provided, but updated for v7.0. Unlike a v6.11 attempt, the build output shows the right catalog consulted and right packages downloaded.
