### ISSUE TITLE
Error in tick speed for universe when using racket language. 

### ISSUE THREAD

**Issue by nicholasnelson522** [racket/racket#1899]
Below are two files one developed in the advance student language for HTDP, 
the other designed with base racket. both versions of the "game" are the same with one exception of a definition of the posn structure in the base racket file. 

so see this slowdown simply run the two files separately.  

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;IN RACKET;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

#lang racket
(require 2htdp/universe)
(require htdp/image)
(require test-engine/racket-tests)
(define img (circle 10 "solid" "red"))
(define WIDTH 800)
(define HEIGHT 500)
(define DELTA-X 5)
(define MT-SCENE (empty-scene WIDTH HEIGHT))
(define-struct world (racket dir))
(define-struct posn (x y))
(define INIT-WORLD (make-world (make-posn 100 100)"right"))

(define (draw-world a-world)
  (place-image img (posn-x(world-racket a-world))(posn-y(world-racket a-world))MT-SCENE))

(define (move-racket x dir)
  (cond [(string=? dir "right") (+ x DELTA-X)]
        [(string=? dir "left") (- x DELTA-X)]))

(define (new-direction x dir)
  (cond
    [(>= x WIDTH)"left"]
    [(<= x 0)"right"]
    [else dir]))

(define (create-new-world a-world)
  (make-world (make-posn
               (move-racket
                (posn-x(world-racket a-world))
                (world-dir a-world))
               (posn-y(world-racket a-world)))
              (new-direction(posn-x(world-racket a-world))(world-dir a-world))))

(define (run-game n)
  (big-bang INIT-WORLD
            (on-draw draw-world)
            (on-tick create-new-world)))

(run-game "")

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;IN ADVANCE STUDENT LANGUAGE ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define img (circle 10 "solid" "red"))
(define WIDTH 800)
(define HEIGHT 500)
(define DELTA-X 5)
(define MT-SCENE (empty-scene WIDTH HEIGHT))
(define-struct world (racket dir))
;(define-struct posn (x y))
(define INIT-WORLD (make-world (make-posn 100 100)"right"))

(define (draw-world a-world)
  (place-image img (posn-x(world-racket a-world))(posn-y(world-racket a-world))MT-SCENE))

(define (move-racket x dir)
  (cond [(string=? dir "right") (+ x DELTA-X)]
        [(string=? dir "left") (- x DELTA-X)]))

(define (new-direction x dir)
  (cond
    [(>= x WIDTH)"left"]
    [(<= x 0)"right"]
    [else dir]))

(define (create-new-world a-world)
  (make-world (make-posn
               (move-racket
                (posn-x(world-racket a-world))
                (world-dir a-world))
               (posn-y(world-racket a-world)))
              (new-direction(posn-x(world-racket a-world))(world-dir a-world))))

(define (run-game n)
  (big-bang INIT-WORLD
            (on-draw draw-world)
            (on-tick create-new-world)))
(run-game "")

**Comment by mfelleisen** [comment]
At first I could not see the difference, because I ran your *SL program with #lang htdp/asl. In the menu-based ASL, I had an accidental conflict with a teachpack setting (that I had used for other students). So I commented out your 

 (require htdp/image) 

and ran with my teachpack 2htdp/image. Lo and behold, it all ran fast. Then I made the same change to the #lang racket program, and weirdly enough it again ran at the same speed as the student program. Changing both requires back to htdp/image slowed down both to about the same speed. 

Can you confirm these observations? 
[[Make sure to clear your teachpack settings in drracket.]]

**Comment by nicholasnelson522** [comment]
I can confirm thank you for the timely response.

**Comment by mfelleisen** [comment]
@rfindler 

This is a rather odd example of how htdp/image is (much much) slower than 2htdp/image. Possibly worth checking out. I will leave it to you whether you want to re-open the issue or start a new one for http.

**Comment by rfindler** [comment]
Much of the reason why 2htdp/image exists is because it improves on the
performance of htdp/image. There are lots of little (that become big)
problems. Probably best to just never use it.

Robby
