### ISSUE TITLE
get-pure-port/headers differs from purify-port breaking extract-field

### ISSUE THREAD

**Issue by greghendershott** [racket/racket#1901]
```racket
#lang racket/base

(require net/head
         net/url)

(define u (string->url "https://www.racket-lang.org"))

;; purify-port returns the \r\n terminated headers including the final
;; \r\n (i.e. the blank line between the headers and the body
;;
;; extract-field expects this and can extract all the headers
;; including the final one -- in this case the CF-RAY header

(define h0 (purify-port (get-impure-port u)))
h0 ;"HTTP/1.1 200 OK\r\nDate: Fri, 01 Dec 2017 17:37:45 GMT\r\nContent-Type: text/html; charset=utf-8\r\nTransfer-Encoding: chunked\r\nConnection: keep-alive\r\nSet-Cookie: __cfduid=d157472d41d231e12d4881d2e765456f71512149865; expires=Sat, 01-Dec-18 17:37:45 GMT; path=/; domain=.racket-lang.org; HttpOnly\r\nx-amz-id-2: iKQuWfsvLZKqfAGiCDShxiw7nTT7kiGjJGJf0Q8nalPt0qRxxz4ccOyyrvhRckGo3f28UPpB+K0=\r\nx-amz-request-id: 0B5BAA0D0F1A4539\r\nCache-Control: max-age=0, no-cache\r\nLast-Modified: Mon, 06 Nov 2017 15:32:34 GMT\r\nx-amz-storage-class: REDUCED_REDUNDANCY\r\nServer: cloudflare-nginx\r\nCF-RAY: 3c67d0f2fa740ecd-EWR\r\n\r\n"
(extract-field "Date" h0)   ;"Fri, 01 Dec 2017 17:37:46 GMT"
(extract-field "CF-RAY" h0) ;"3c67d0f2fa740ecd-EWR"


;; get-pure-port/headers returns the \r\n terminated headers -- but
;; does NOT include the final \r\n
;;
;; extract-field doesn't expect this; although it will extract the
;; headers, the final header gets a spurious \r\n included in its
;; value

(define-values (_ h1) (get-pure-port/headers u #:status? #t))
h1 ;"HTTP/1.1 200 OK\r\nDate: Fri, 01 Dec 2017 17:37:46 GMT\r\nContent-Type: text/html; charset=utf-8\r\nTransfer-Encoding: chunked\r\nConnection: keep-alive\r\nSet-Cookie: __cfduid=d6f908755e154a2f9a02c18b8edb3b5d01512149865; expires=Sat, 01-Dec-18 17:37:45 GMT; path=/; domain=.racket-lang.org; HttpOnly\r\nx-amz-id-2: RR4uLE2k9Lf13jZ80vVAR5LPxq2wddoyBuWtQyWTOkHtIZMAoXTUVoJck9CAFevXLZB0CSZV2es=\r\nx-amz-request-id: ECD76869C640565A\r\nCache-Control: max-age=0, no-cache\r\nLast-Modified: Mon, 06 Nov 2017 15:32:34 GMT\r\nx-amz-storage-class: REDUCED_REDUNDANCY\r\nServer: cloudflare-nginx\r\nCF-RAY: 3c67d0f418c3219e-EWR\r\n"
(extract-field "Date" h1)   ;"Fri, 01 Dec 2017 17:37:46 GMT"
(extract-field "CF-RAY" h1) ;"3c67d0f418c3219e-EWR\r\n"
```

`extract-field` seems to get confused only on the _last_ header -- so, you might test and things work fine but another server happens to order headers differently and then you get bit. At least, that's what happened to me, where the header was `Content-Encoding` and I was matching on the value `"gzip"` but got `"gzip\r\n"`, and I didn't gunzip the bytes.

Probably `get-pure-port/headers` should change and append a final `\r\n`?

Or if we worry that would break existing code, then maybe its documentation should just get a new, "Tip: You should `string-append` a `"\r\n"` to the header string before using it with `extract-field`"?

**Comment by greghendershott** [comment]
As you'd expect `extract-all-fields` shows the same problem with a non CRLF terminated header string from `get-pure-port/headers`:

```racket
(extract-all-fields h1)
;; =>
'(("Date" . "Fri, 01 Dec 2017 17:56:01 GMT")
  ("Content-Type" . "text/html; charset=utf-8")
  ("Transfer-Encoding" . "chunked")
  ("Connection" . "keep-alive")
  ("Set-Cookie"
   .
   "__cfduid=d3a45dfe7abbf2d471243de7a14aef1bc1512150961; expires=Sat, 01-Dec-18 17:56:01 GMT; path=/; domain=.racket-lang.org; HttpOnly")
  ("x-amz-id-2"
   .
   "SKjB8eeb8EpJaIw3+LJVnBVLFkcaBz4DF3XmCSY22UkEP7y1L+88o9dzkAulIRUwt+RpJP3HRrc=")
  ("x-amz-request-id" . "04446203A0EA1534")
  ("Cache-Control" . "max-age=0, no-cache")
  ("Last-Modified" . "Mon, 06 Nov 2017 15:32:34 GMT")
  ("x-amz-storage-class" . "REDUCED_REDUNDANCY")
  ("Server" . "cloudflare-nginx")
  ("CF-RAY" . "3c67ebb70c821864-EWR\r\n"))
```

**Comment by jeapostrophe** [comment]
My opinion is that this is an error and `get-pure-port/headers` should change even though it is possible that existing code relies on that error. My logic is that the documentation says "This function is an alternative to calling `get-impure-port` and `purify-port` when needing to follow redirections." I believe this constrains the function to be equivalent to  `(purify-port (get-impure-port u))`

Thanks for catching this Greg. Do you have a fix or should I work on it?

**Comment by greghendershott** [comment]
I agree. Although... amusingly, this fix could break code that was attempting to work around the current bug with `get-pure-port/headers`. For example, as a quick hack, I'm appending a `"\r\n"` regardless. However if `get-pure-port/headers` is fixed to add this, and my hack adds another?  Then amusingly the original problem pops up again. Because `extract-field` is a little weird this way:

```racket
> (extract-field "k" "k: v\r\n")
"v\r\n"
﻿> (extract-field "k" "k: v\r\n\r\n")
"v"
﻿> (extract-field "k" "k: v\r\n\r\n\r\n")
"v\r\n"
```

Maybe `extract-field` should be less weird, this way? 

But... probably I'm over-thinking this. Instead I should just refine my hack to ensure the string ends with exactly `"\r\n\r\n"`.  That would work both now and later.

**Comment by jeapostrophe** [comment]
Yes, that's the right thing... don't add `"\r\n"` but "normalize" the string

**Comment by greghendershott** [comment]
I'm a little rusty at submitting pull requests to Racket, so please don't trust it too much, but I just submitted a PR for this.
