### ISSUE TITLE
The document translation

### ISSUE THREAD

**Issue by zaoqi-unsafe** [racket/racket#1902]
Chinese https://github.com/OnRoadZy/RackGuideInChinese

**Comment by Syntacticlosure** [comment]
It seems your translation don't have a good quality.

**Comment by pmatos** [comment]
I am not familiar with Chinese but it seems to me that this should not be an open issue. Maybe you can publicize it in the mailing list?

**Comment by spdegabrielle** [comment]
Added to wiki https://github.com/racket/racket/wiki

Will make a page fro translations but the front page is good to start with
