### ISSUE TITLE
Package conflict while attempting to install dracula

### ISSUE THREAD

**Issue by lambdacn** [racket/racket#1906]
Hi,

I ran into a few errors when installing dracula with raco (racket 6.11); 
<img width="821" alt="error" src="https://user-images.githubusercontent.com/22525327/33711043-7c8fec1a-db7d-11e7-9803-e517bb0fd8ca.png">
and this problem doesn't reproduce with racket 6.10.

Any suggestions?

**Comment by sorawee** [comment]
Dup of https://github.com/carl-eastlund/dracula/issues/5. Closing.
