### ISSUE TITLE
Cannot unquote in keys in hash literls.

### ISSUE THREAD

**Issue by LeifAndersen** [racket/racket#1908]
I can use `` ` `` and `,` to put evaluate variables in a literal vector:

```
> (define x 42)
> `#(,x 5)
#(42 5)
```

I can also do it for hash values:

```
> (define x 42)
> `#hash((a . ,x))
#hash((a . 42))
```

But I can't do it for hash keys:
```
> (define x 42)
> `#hash((,x . a))
#hash(((unquote x) . a))
```

Is this a bug in the reader or part of the design? If its part of the design, why does it make sense to be able to unquote in values but not keys?

**Comment by samth** [comment]
It's part of the design. It's that way because otherwise this could be confusing:

```
(define (f x y)
  `#hash((,x 1) (,y 2)))
(define h (f 0 0))
(hash-ref h 0)
```

**Comment by LeifAndersen** [comment]
I presume you meant `` `#hash((,x . 1) (,y . 2)) `` in that example. (Unless the literal `#hash` syntax is more flexible than I thought it was anyway).

As such, sure. Although this doesn't seem any more or less confusing to me than say:

```
(define (f x y)
  (make-immutable-hash `((,x . 1) (,y . 2)))
(define h (f 0 0)) ; => #hash((0 . 2))
(hash-ref h 0) ; => 2
```

So is your point just that when you have the literal `#hash` values you expect them to have the same structure as you gave it? (If so that's fine, I'm just trying to understand the design rational. :) )

If that is the case, I should point out that I can create a hash literal with duplicate keys, one of which will get dropped:

```
> #hash((0 . 1) (0 . 2))
#hash((0 . 2))
```

Anyway, thanks for the feedback. :)

**Comment by samth** [comment]
The bigger problem with my example is that there's a literal hash table being evaluated to produce the resulting hash table, and an assumption that it's got the right number of slots.

**Comment by samth** [comment]
I should say that I'm not a fan of this approach to literals (I prefer how Clojure works) but it's what we've got.

**Comment by LeifAndersen** [comment]
That makes sense. (Or at least, I should say I now at least understand the rational. In general I'm inclined to agree with you here.)

Thank you.
