### ISSUE TITLE
Documentation indirection fails

### ISSUE THREAD

**Issue by samth** [racket/racket#1914]
[This document](https://docs.racket-lang.org/reference/Reading.html?q=lexer#%28def._%28%28quote._~23~25kernel%29._read-language%29%29) links to [this page that's supposed to be part of the DrRacket docs](https://download.racket-lang.org/releases/6.11/doc/local-redirect/index.html?tag=%28part._%28.%27%28lib._scribblings%2Ftools%2Ftools..scrbl%29.%27._.%27_lang-based_.Languages_in_.Dr.Racket.%27%29%29&version=6.11&q=lexer) which fails and produces an error, reading:

> This page that is intended to redirect to the result of a search request. Since you’re reading this, it seems that the redirection did not work.

**Comment by mflatt** [comment]
It looks like the section changed, so I'll fix the link. (Yes, it would be nice to have a way to check these links.)
