### ISSUE TITLE
'make-web-cell' fails in 'web-server/lang/web-cells' implementation 

### ISSUE THREAD

**Issue by 7enderhead** [racket/racket#1918]
Racket 6.11 on Linux Mint 17.1

```
#lang racket
(require web-server/servlet/web-cells)
(make-web-cell 0)
```

output: `#<primitive-wc>`

```
#lang racket
(require web-server/lang/web-cells)
(make-web-cell 0)
```

output:

closure->deserialize-name: contract violation
  expected: serializable?
  given: #<procedure:...ng/web-cells.rkt:40:48>
  in: the 1st argument of
      (-> serializable? symbol?)
  contract from: 
      <pkgs>/web-server-lib/web-server/lang/serial-lambda.rkt
  blaming: anonymous-module
   (assuming the contract is correct)
  at: <pkgs>/web-server-lib/web-server/lang/serial-lambda.rkt:29.2

**Comment by jeapostrophe** [comment]
It can only be used in #lang web-server
