### ISSUE TITLE
Search on docs.racket-lang.org say it is only searching my locally installed packages

### ISSUE THREAD

**Issue by endobson** [racket/racket#1924]
http://docs.racket-lang.org/search/index.html

It looks like the logic to tell if it is on the global site is not working correctly, because it redirects to itself for searching the global packages.

**Comment by mflatt** [comment]
I had fixed this once, but in the wrong place, so the repair was overwritten. Fixed in the right place, this time, which is the daily pkg-build.

Thanks!
