### ISSUE TITLE
module path - Unicode support

### ISSUE THREAD

**Issue by zaoqi** [racket/racket#1929]
`string:1:12: module: initial import is not a well-formed module path at: "語.rkt" in: (module anonymous-module "語.rkt" (#%module-begin))`
`string:1:12: cannot open module file module path: #<path:/…/a.rkt> path: /…/a.rkt system error: 没有那个文件或目录; errno=2`

**Comment by mflatt** [comment]
You can use `(file "語.rkt")` to access a path that uses more characters than allowed in a plain string as a module path (which is restricted to a small set of characters to avoid portability problems).
