### ISSUE TITLE
Error in 6.11, GetCursorPos: call failed(5)

### ISSUE THREAD

**Issue by RolandLemmers** [racket/racket#1930]
![clipboard01](https://user-images.githubusercontent.com/35457487/34945994-6cd5b51a-fa05-11e7-8b28-23485e6b02ac.jpg)

Since I installed drracket 6.11 I ocassionally get this error. It apparently happens when drracket spent some time in the background. Windows 10, version 1703, build 15063.850.

**Comment by mflatt** [comment]
Thanks for the report! We've hopefully fixed this for the upcoming v6.12 release.

**Comment by mflatt** [comment]
Repaired in v6.12, now released.
