### ISSUE TITLE
ffi array of structure memory corruption?

### ISSUE THREAD

**Issue by NoCheroot** [racket/racket#1932]
I know this code is terrible for a lot of reasons.  Just trying to prove I can get a successful call to ```DsAddressToSiteNamesW``` with a list of ip addresses, and get a list of site names back.  For the moment, I'm only interested in issues directly preventing me from achieving that end.  I can try to write something which isn't so naive later.

I feel like I'm close, but I think I'm missing something fundamental.  The first element of the list (via ```SiteNames```) returned by ```DsAddressToSiteNamesW``` does contain the correct AD site name for the ip I'm entering.  But, accessing the second element always results in a crash (```Access violation - code c0000005```), even with a check for null pointer.  I think I've made some kind of memory corrupting mistake, but I'm not seeing it, and I'm still finding my way around Racket in WinDbg.

Am I using ```_list``` correctly?  Am I building my list of ```_SOCKET_ADDRESS``` structures improperly?  Have I made some kind of ridiculous pointer mistake? Am I completely off base?

I'm having quite a bit of trouble working through the [C types](https://docs.racket-lang.org/foreign/types.html) and [ffi](https://docs.racket-lang.org/foreign/index.html?q=ffi%2Funsafe) documentation when it comes to passing in/out parameters using structures and arrays of structures.  Any information that helps get me moving in the right direction will be appreciated.

The values ```ip1```, ```ip2```, and ```dc``` have been replaced with dummies to protect the guilty.

```racket
#lang racket

(require ffi/unsafe
         ffi/unsafe/define
         ffi/winapi)

(define ws2_32-dll (and (eq? (system-type) 'windows)
                        (ffi-lib "Ws2_32.dll")))

(define netapi32-dll (and (eq? (system-type) 'windows)
                          (ffi-lib "Netapi32.dll")))

(define-ffi-definer define-ws2_32 ws2_32-dll
  #:default-make-fail make-not-available)

(define-ffi-definer define-netapi32 netapi32-dll
  #:default-make-fail make-not-available)

(define _DWORD _int32)
(define _WORD _int16)
(define _INT _int)
(define _SHORT _short)
(define _USHORT _ushort)

(define _NO_ERROR 0)
(define _ERROR_INVALID_PARAMETER 87)
(define _ERROR_NOT_ENOUGH_MEMORY 8)

(define _WSADESCRIPTION_LEN 256)
(define _WSASYS_STATUS_LEN 128)

(define _WSABASEERR 10000)
(define _WSASYSNOTREADY (+ _WSABASEERR 91))
(define _WSAVERNOTSUPPORTED (+ _WSABASEERR 92))
(define _WSAEINPROGRESS (+ _WSABASEERR 36))
(define _WSAEPROCLIM (+ _WSABASEERR 67))
(define _WSAEFAULT (+ _WSABASEERR 14))

(define _WSAEINVAL (+ _WSABASEERR 22))
(define _WSANOTINITIALISED (+ _WSABASEERR 93))
(define _WSA_NOT_ENOUGH_MEMORY _ERROR_NOT_ENOUGH_MEMORY)

(define _SOCKET_ERROR -1)

(define _AF_INET 2)

(define wsasysnotready "The underlying network subsystem is not ready for network communication.")
(define wsavernotsupported "The version of Windows Sockets support requested is not provided by this particular Windows Sockets implementation.")
(define wsaeinprogress "A blocking Windows Sockets 1.1 operation is in progress.")
(define wsaeproclim "A limit on the number of tasks supported by the Windows Sockets implementation has been reached.")
(define wsaefault "The buffer pointed to by the lpAddress parameter is too small. Pass in a larger buffer.")

(define wsaeinval "The function was unable to translate the string into a sockaddr.")
(define wsanotinitialised "The WS2_32.DLL has not been initialized. The application must first call WSAStartup before calling any Windows Socket functions.")
(define wsa-not-enough-memory "There was insufficient memory to perform the operation.")

(define-cstruct _WSADATA ([wVersion _WORD]
                          [wHighVersion _WORD]
                          [szDescription (_array _string (+ _WSADESCRIPTION_LEN 1))]
                          [szSystemStatus (_array _string (+ _WSASYS_STATUS_LEN 1))]
                          [iMaxSockets _USHORT]
                          [iMaxUdpDg _USHORT]
                          [lpVendorInfo (_cpointer _string)]))

(define-cstruct _SOCKADDR ([sa_family _USHORT]
                           [sa_data (_array _string 14)]))

(define-cstruct _SOCKET_ADDRESS ([lpSockaddr _SOCKADDR-pointer]
                                 [iSockaddrLength _INT]))

(define-ws2_32 WSAGetLastError (_fun #:abi winapi -> _INT))

(define-ws2_32 WSACleanup (_fun #:abi winapi -> _void))

(define-ws2_32 WSAStartup (_fun #:abi winapi
                                _WORD
                                (wsadata : (_ptr o _WSADATA))
                                -> (result : _INT)
                                -> (with-handlers ([exn:fail? (lambda (exn) (cleanup exn))])
                                     (let ([fn 'WSAStartup])
                                       (cond
                                         [(zero? result) wsadata]
                                         [(equal? result _WSASYSNOTREADY) (raise-user-error fn wsasysnotready)]
                                         [(equal? result _WSAVERNOTSUPPORTED) (raise-user-error fn wsavernotsupported)]
                                         [(equal? result _WSAEINPROGRESS) (raise-user-error fn wsaeinprogress)]
                                         [(equal? _WSAEPROCLIM) (raise-user-error fn wsaeproclim)]
                                         [(equal? _WSAEFAULT) (raise-user-error fn wsaefault)]
                                         [else (raise-user-error fn (number->string result))])))))

(define-ws2_32 WSAStringToAddressW (_fun #:abi winapi
                                       _string/utf-16
                                       _INT
                                       _pointer
                                       (lpAddress : (_ptr o _SOCKADDR))
                                       (lpAddressLength : (_ptr io _INT))
                                       -> (result : _INT)
                                       -> (with-handlers ([exn:fail? (lambda (exn) (cleanup exn))])
                                            (let ([fn 'WSAStringToAddressW])
                                              (cond
                                                [(zero? result) lpAddress]
                                                [(equal? result _SOCKET_ERROR)
                                                 (let ([e (WSAGetLastError)])
                                                   (cond
                                                     [(equal? e _WSAEFAULT) (raise-user-error fn wsaefault)]
                                                     [(equal? e _WSAEINVAL) (raise-user-error fn wsaeinval)]
                                                     [(equal? e _WSANOTINITIALISED) (raise-user-error fn wsanotinitialised)]
                                                     [(equal? e _WSA_NOT_ENOUGH_MEMORY) (raise-user-error fn wsa-not-enough-memory)]
                                                     [else (raise-user-error fn (number->string result))]))]
                                                [else (raise-user-error fn (number->string result))])))))

(define-netapi32 DsAddressToSiteNamesW (_fun #:abi winapi
                                             _string/utf-16
                                             (len : _DWORD)
                                             (_list i _SOCKET_ADDRESS)
                                             (SiteNames : (_list o (_cpointer _string/utf-16) len))
                                             -> (result : _DWORD)
                                             -> (with-handlers ([exn:fail? (lambda (exn) (cleanup exn))])
                                                  (let ([fn 'DsAddressToSiteNamesW])
                                                    (cond
                                                      [(equal? result _NO_ERROR) SiteNames]
                                                      [(equal? result _ERROR_INVALID_PARAMETER) (raise-user-error fn "ERROR_INVALID_PARAMETER")]
                                                      [(equal? result _ERROR_NOT_ENOUGH_MEMORY) (raise-user-error fn "ERROR_NOT_ENOUGH_MEMORY")]
                                                      [else (raise-user-error fn (number->string result))])))))

(define (makeword low high)
  (bitwise-ior (arithmetic-shift high 8) low))

(define (cleanup e)
  (WSACleanup)
  (raise (exn-message e)))

(define ip1 "xx.xx.xx.xx")
(define ip2 "xx.xx.xx.xx")
(define dc "domaincontroller")

(define wsadata (WSAStartup (makeword 2 2)))
(define sockaddr1 (WSAStringToAddressW ip1 _AF_INET #f (ctype-sizeof _SOCKADDR)))
(define sockaddr2 (WSAStringToAddressW ip2 _AF_INET #f (ctype-sizeof _SOCKADDR)))

(define x (DsAddressToSiteNamesW
           dc
           2
           (list
            (ptr-ref (make-SOCKET_ADDRESS sockaddr1 (ctype-sizeof _SOCKADDR)) _SOCKET_ADDRESS)
            (ptr-ref (make-SOCKET_ADDRESS sockaddr2 (ctype-sizeof _SOCKADDR)) _SOCKET_ADDRESS))))

;; This outputs the site name I'm looking for successfully
(let ([s (car x)])
  (if (ptr-equal? s #f) #f (ptr-ref s _string/utf-16)))

;; This causes a crash
;;(let ([s (cadr x)])
;;  (if (ptr-equal? s #f) #f (ptr-ref s _string/utf-16)))

(WSACleanup)
```

Edited to add naive but working example in C for some context.  Again, ip addresses and domain controller have been replaced with dummy values.  This successfully outputs two site names.  Hopefully someone can look at this and tell me how I have mishandled array, structure, or pointer access above.

```c
#include <winsock2.h>
#include <windows.h>
#include <stdio.h>
#include <wchar.h>
#include <Lm.h>
#include <Dsgetdc.h>

int main() {

	WORD versionRequested;
	WSADATA wsadata;
	int err;
	SOCKADDR sockAddr1, sockAddr2;

	versionRequested = MAKEWORD(1, 1);

	int sockAddrSize = sizeof(SOCKADDR);

	err = WSAStartup(versionRequested, &wsadata);
	if (err != 0) {
		goto error;
	}

	err = WSAStringToAddressW(L"xx.xx.xx.xx", AF_INET, NULL, (PSOCKADDR)&sockAddr1, &sockAddrSize);
	if (err != 0) {
		goto error;
	}

	err = WSAStringToAddressW(L"xx.xx.xx.xx", AF_INET, NULL, (PSOCKADDR)&sockAddr2, &sockAddrSize);
	if (err != 0) {
		goto error;
	}

	SOCKET_ADDRESS address[2] = { {&sockAddr1, sockAddrSize}, {&sockAddr2, sockAddrSize} };

	PWSTR *siteNames = NULL;

	
	err = DsAddressToSiteNamesW(L"domaincontroller", 2, address, &siteNames);
	if (err != 0) {
		goto error;
	}
	
	wprintf(L"%ls\n", siteNames[0]);
	wprintf(L"%ls\n", siteNames[1]);

	NetApiBufferFree(siteNames);
	
error:
	WSACleanup();

	return 0;
}
```

**Comment by NoCheroot** [comment]
Looks like I figured it out for myself.  The crash, not the awful code.  I incorrectly assumed ```_list``` would automatically deal with the ```**SiteNames``` below.

```c
DWORD DsAddressToSiteNames(
  _In_opt_ LPCTSTR         ComputerName,
  _In_     DWORD           EntryCount,
  _In_     PSOCKET_ADDRESS SocketAddresses,
  _Out_    LPTSTR          **SiteNames
);
```

Maybe that is possible and I just have not found the proper use of ```_list``` yet.  A problem for another day.

Both site names were being returned all along.  In the list I was getting back, ```'(#<cpointer:#> #<cpointer:#>)```, the first element was the pointer to an array of pointers to the strings I wanted, but I was treating it as a pointer to a string.  That let me output the first string, and hid the second one from me.  Then ```ptr-ref``` on the second element leads to the access violation/crash.

I can access the strings by replacing ```(SiteNames : (_list o (_cpointer _string/utf-16) len))``` with ```(SiteNames : (_ptr o _gcpointer))```, and access the site names with 

```racket
(ptr-ref (ptr-add x 0 _gcpointer) _string/utf-16)
(ptr-ref (ptr-add x 1 _gcpointer) _string/utf-16)
```

Not sure if this is an appropriate use of ```_gcpointer``` but I need to sort out that, and all of the other problems with this code, on my own as a learning experience.

Sorry to create an issue and close it myself, but I was really stumped.  At the time I thought I would not be able to find what I did wrong.

**Comment by mflatt** [comment]
Late, but in case it helps: `(_ptr o _pointer)` is right. The `_gcpointer` alternative isn't helpful, although it's probably harmless in this case, since `DsAddressToSiteNames` isn't going to allocate GCable values! But `DsAddressToSiteNames` does allocate an array, so you just want to receive the array pointer (and then probably cast it).

Beware that `(_cpointer _string/utf-16)` isn't really useful in any context, since the `_string/utf-16` acts as a name for the new pointer type. In particular, that *doesn't* mean a pointer to a string. The type `_string/utf-16` corresponds directly to a `char*`. The type `(_ptr o _string/utf-16)` would be 

Unrelated, but something else I noticed: `(_array _string (+ _WSADESCRIPTION_LEN 1))` should be `(_array _byte  (+ _WSADESCRIPTION_LEN 1)`. That is, you want an string as an array of bytes in `_WSADATA`, not an array of pointers to strings.

**Comment by NoCheroot** [comment]
Thank you.  That is good information.  Clearly I need to spend more time reading the c types documentation and browsing other people’s code, but this does clear up a few things that were bothering me.

**Comment by NoCheroot** [comment]
@mflatt, your comment lead me to try this

```(SiteNames : (_ptr o (_list o _string/utf-16 len)))```

and it gives me exactly the output I want in the form I want.  A list containing the site names as strings instead of pointers.  I have not been able to find an example of anyone else using ```_ptr``` and ```_list``` in this way.  After spending more time with the documentation I can't really tell if this is an idiomatic or not.

Is this correct use?  Are there any serious drawbacks here which make working with the array a better choice?

**Comment by mflatt** [comment]
A drawback is that `(_ptr o (_list o _string/utf-16 len))` doesn't free the pointer that is returned by `DsAddressToSiteNames`. So, it's probably better to use `(_ptr o _pointer)` to get a pointer `p`, convert the data using `(cast p _pointer (_list o _string/utf-16 len))`, and then `(free p)`.

The documentation for `DsAddressToSiteNames` isn't clear on whether just the immediate array needs to be freed or the strings in the array, too.  If it's the latter, then `(free p)` isn't sufficient.

**Comment by NoCheroot** [comment]
My understanding is ```NetApiBufferFree``` should take care of the array and strings, and I've always treated it that way in the past.  There could be some assumptions there, so I'll try to confirm.

If ```NetApiBufferFree``` handles the array and strings, do I still need to worry about a ```cast``` and ```free```?

**Comment by mflatt** [comment]
Ah, I missed the second half of the sentence in the docs. So, use `NetApiBufferFree` instead of `free`, but you need the `cast` step so that you have a `p` to pass to `NetApiBufferFree`.

**Comment by NoCheroot** [comment]
Whoops.  Had I bothered to try ```NetApiBufferFree``` I might have caught that myself.  Thanks again.
