### ISSUE TITLE
http://pre-release.racket-lang.org/…current….sh points to 6.11.0.900, should point to 6.12

### ISSUE THREAD

**Issue by jsmaniac** [racket/racket#1940]
My apologies if this is not the right repo to report this, I'm not sure where this should go otherwise (feel free to close & point me to another repo).

The URL https://raw.githubusercontent.com/greghendershott/travis-racket/master/install-racket.sh points to Racket 6.11.0.900, but it should point to 6.12 now that it is "officially" out.

This means that Travis builds using @greghendershott 's `travis-racket` script with `RACKET_VERSION=RELEASE` still install the release candidate 6.11.0.900 instead of installing the actual latest release 6.12.

See here for example: https://travis-ci.org/jsmaniac/subtemplate/jobs/334079015#L445

**Comment by greghendershott** [comment]
`RELEASE` was added to travis-racket in [this PR](https://github.com/greghendershott/travis-racket/pull/10).

It is [an alias](https://github.com/greghendershott/travis-racket/blob/master/install-racket.sh#L26-L27) for whatever is at `http://pre-release.racket-lang.org/installers/racket-${MIN}current-x86_64-linux.sh`.

(In hindsight a better name might have been `RELEASE-CANDIDATE` OR `PRE-RELEASE`.)

As [this comment](https://github.com/greghendershott/travis-racket/blob/master/.travis.yml#L24) in the example .travis.yml says:

>  The RELEASE snapshot is only available during the release process.

---

So as far as I know, `RELEASE` has always only been useful temporarily -- for example when actively developing a package that you know depends on things changing in a pre-release. You can get feedback more quickly than waiting for and checking the daily Racket build -- that will also run your tests.

As I've never been in that situation, I've never used `RELEASE` myself. For my packages I've found it adequate to test against `HEAD` (plus whatever past and current Racket versions make sense for the package).  Of course that also means that, on each new Racket release, I have to go around and add that latest version to each `.travis.yml`.

**Comment by greghendershott** [comment]
p.s. In case it wasn't clear from the preceding. I think the intended use of `RELEASE` is:

1. Oh wow, my package uses something that's changing significantly during some specific prerelease cycle of Racket. I'd like to stay on top of this!
2. I add `RELEASE` to my `.travis.yml` matrix.
3. My package and the Racket prerelease evolve side by side for some days or weeks.
4. Racket is released.
5. I change my `.travis.yml` again, to remove `RELEASE` and to add the now-released Racket version.

**Comment by jsmaniac** [comment]
@greghendershott Thanks for the clarification. I had used it to build against the latest version of Racket (without having to manually update `RACKET_VERSION=6.9` to `RACKET_VERSION=6.10` and so on at every release). I guess it would make sense to have another "LATEST" or similar keyword, but that's an issue / feature request which belongs to travis-racket. I'll look into making a PR for that shortly.

Sorry about the noise here, closing this now.
