### ISSUE TITLE
Chinese version is inappropriate

### ISSUE THREAD

**Issue by MRNIU** [racket/racket#1944]
If I use a define without Run,IDE show me a message
`警告：定义视窗改变了。请单击运行`
I think it's inappropriate, maybe we can show as
`警告：请点击运行以更新定义`
or something better.

**Comment by rfindler** [comment]
Thank you for the comment. I cannot tell the difference between these two, can you elaborate a little bit please? 

Also, if you wish to submit a pull request with some better translations, the repo is here:

  https://github.com/racket/string-constants

**Comment by MRNIU** [comment]
Ok , I will be see what can I do.Thank you.

**Comment by bennn** [comment]
Closed by https://github.com/racket/string-constants/commit/600b173cfdd1a4bd6bad05912f4ed490ce139830
