### ISSUE TITLE
Documentation discrepancy for `print-hash-table`

### ISSUE THREAD

**Issue by rocketnia** [racket/racket#1954]
The current documentation for `print-hash-table` says "defaults to `#f`." However, a quick test with Racket 6.12 shows a value of `#t`.

It looks to me like the discrepancy dates back to [a 2007-or-so change to threads.c](https://github.com/racket/racket/commit/39cedb62edf9258b051a22a29a90be9c6841956f) which brought it out of line with the documentation. I don't know which one is the intended behavior.

**Comment by mflatt** [comment]
Will fix - thanks for the report!
