### ISSUE TITLE
xform error when compiling Racket on Guix

### ISSUE THREAD

**Issue by cwebber** [racket/racket#1962]
I'm working on patching 6.12 for Guix.  Unfortunately it seems that similar to #1222 and #464 there's some xform funkiness going on.  I get the following error when building:

```
Error [GCING] 1780 in ./../src/number.c: Function minus_zero_p declared __xform_nongcing__, but includes a function call at __signbitf128.
xform: Errors converting
  context...:
   /tmp/guix-build-racket-6.12.drv-0/racket-6.12/src/racket/gc2/xform-collects/compiler/private/xfor...:8:2: xform
   /tmp/guix-build-racket-6.12.drv-0/racket-6.12/src/racket/gc2/xform-collects/xform/xform-mod.rkt: [running body]
   /tmp/guix-build-racket-6.12.drv-0/racket-6.12/src/racket/gc2/xform.rkt: [running body]
make[4]: *** [Makefile:268: xsrc/number.c] Error 1
```

Fortunately there's a workaround:

``` diff
--- a/src/racket/src/number.c	2018-02-24 18:16:32.031698079 -0600
+++ b/src/racket/src/number.c	2018-02-24 18:15:41.055445301 -0600
@@ -1775,6 +1775,7 @@
 }
 
 XFORM_NONGCING static MZ_INLINE int minus_zero_p(double d)
+  XFORM_SKIP_PROC
 {
 #ifdef MZ_IS_NEG_ZERO
   return MZ_IS_NEG_ZERO(d);
```

I'm guessing not doing XFORM_SKIP_PROC would be better for Some Reason. :)  At the very least, would be nice to not have to patch ourselves!

**Comment by cwebber** [comment]
I [filed a bug about this in Guix](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=30603).  A couple of things:

- [Danny Milosavljevic](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=30603#11) points out that my patch probably broke GC.  Does it?  I dunno,  I was just (foolishly?) miming suggestions in #464 :)
- I had thought this was a change between Racket 6.12 and Racket 6.11.  However it seems that even 6.11 has stopped building... so I assume this must be a change in some dependency that was used to build Racket, but which change I'm not sure what it would be.

**Comment by mflatt** [comment]
Although the normal repair is to add `__signbitf128` to "racket/collects/compiler/private/xform.rkt" (near similar identifiers, like `__signbitl`), your repair is fine and in some way better. I'll make both changes.

**Comment by martindemello** [comment]
seeing this again when trying to build 7.5 from head on debian; blindly surrounding these functions with a `START|END_XFORM_SKIP` block fixed it:

bool.c: everything between `mz_long_double_eqv` and `is_fast_equal` (inclusive)
number.c: `double_is_integer`, `scheme_is_integer`
