### ISSUE TITLE
No implementation for syntax-local-make-delta-introducer in racket7 expander

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#1965]
Racket versions 6.3 through 6.12 provided a function named `syntax-local-make-delta-introducer` that did nothing but raise `exn:fail:unsupported`<sup>†</sup>, but the Racket 7 expander does not provide any such binding. It seems plausible that this binding should be outright removed in Racket 7, but it is still listed in the Scribble documentation. Either the documentation should be removed, or the compatibility binding should be reinstated.

<sup>† The documentation mistakenly claims it raises a nonexistent `exn:fail:supported`, but that typo is a separate issue.</sup>

**Comment by mflatt** [comment]
We practically never removing a binding, but if no code refers to `syntax-local-make-delta-introducer`, maybe we can leave it out and update the docs.

Did you notice the omission because a program didn't compile, or did you just sense a disturbance in the force?

**Comment by lexi-lambda** [comment]
> Did you notice the omission because a program didn't compile, or did you just sense a disturbance in the force?

I wish I were prescient enough to be able to claim the latter, but indeed, I was trying to install Carl Eastlund’s `mischief` package, which includes a reference to `syntax-local-make-delta-introducer`. Due to the way it is used, it would be trivial to remove the reference, but it *did* cause the package to fail to compile.
