### ISSUE TITLE
new expander breaks `#lang web-server/base`

### ISSUE THREAD

**Issue by mbutterick** [racket/racket#1972]
This source works <= v6.12:

```racket
#lang web-server/base

(require web-server/dispatch)

(define-values (x y)
  (dispatch-rules [("foo") 'bar]))
```

But with the current expander dies with this error:
```racket
 lifted/16.1: undefined;
 cannot reference an identifier before its definition
```

But I’m running the comparatively ancient 6757a202d59afc0e3324820b2c4358f2ac8de3d4, so I will also rebuild and see if the error persists.

**Comment by mflatt** [comment]
I think you'll find this repaired by e707d7decdb7d30adec4b960bd7ccfdef4115e4e, but ping if not.

**Comment by mbutterick** [comment]
Indeed, fixed. Thanks :metal:
