### ISSUE TITLE
map in Intermediate Student w/o lambda

### ISSUE THREAD

**Issue by schackbrian2012** [racket/racket#1975]
The documentation for the built-in map function in the Intermediate Student w/o lambda language says gives two examples that use lambda. These two examples do not work in the Intermediate Student w/o lambda language.

> (map (lambda (x) (list 'my-list (+ x 1))) '(3 -4.01 2/5))
lambda: found a lambda that is not a function definition

> (map (lambda (x y) (+ x (* x y))) '(3 -4 2/5) '(1 2 3))
lambda: found a lambda that is not a function definition

https://docs.racket-lang.org/htdp-langs/intermediate.html?q=map#%28def._htdp-intermediate._%28%28lib._lang%2Fhtdp-intermediate..rkt%29._map%29%29

**Comment by sorawee** [comment]
This seems to be fixed now. Can we close it?
