### ISSUE TITLE
The `kill` button can't kill the threads.

### ISSUE THREAD

**Issue by Syntacticlosure** [racket/racket#1981]
When debugging, this design is very inconvenient.
I think DrRacket should provide something to stop the sub threads,not only the main thread.

**Comment by rfindler** [comment]
When I run this program:

```
#lang racket
(thread (λ () (let loop () (displayln (random)) (sleep .1) (loop))))
```

and then choose the `Racket | Force the Program to Quit` menu item the thread is killed.

**Comment by Syntacticlosure** [comment]
Thanks!
