### ISSUE TITLE
propagation-tamper-accessor: contract violation

### ISSUE THREAD

**Issue by jsmaniac** [racket/racket#1984]
When compiling https://github.com/jsmaniac/stxparse-info/blob/bug-propagation-tamper-accessor/case/bug.rkt with `raco make case/bug.rkt`, I get the following internal error:

```
../../../../../../usr/local/racket-6.90.0.19/collects/compiler/private/cm-minimal.rkt:273:0: propagation-tamper-accessor: contract violation
  expected: propagation-tamper?
  given: (list (parsed-app #f ...))
```

In DrRacket, the error occurs if I disable debugging & profiling in the language settings, but goes away if I enable debugging.

@mflatt this popped up while replacing my `syntax-local-get-shadower` mess with a parameter + `syntax-local-expand-expression` as you suggested in our e-mail exchange.

I'm quite likely doing something wrong here which triggers this error, but there should be a proper error message (and I guess some associated docs, because I have no idea what needs fixing from my side).

**Comment by mflatt** [comment]
There's bug in the expander for dealing with the result of `syntax-local-expand-expression` in a definition context. I'll push a repair.

When the current context isn't an expression context, you may need to delay the `with-pvar2` expansion by wrapping with `#%expression`. Or maybe the delay is never needed, if the expression to expand never needs to refer to definitions in the same context.
