### ISSUE TITLE
prefab structure doesn't match

### ISSUE THREAD

**Issue by pmatos** [racket/racket#1994]
From the `match` documentation I could swear I could match prefab structs. But...
```racket
> (match #s(pos 1 2)
    [#s(pos x ...) (values ...)])
. match: syntax error in pattern in: #s(pos x ...)
```

Maybe it's the usage of `...`?
```racket
> (match #s(pos 1 2)
    [#s(pos x y) (values x y)])
. match: syntax error in pattern in: #s(pos x y)
```

Ok, maybe I need to write `prefab-key` since it shows up in green in the documentation:
```racket
> (match #s(pos 1 2)
    [#s(prefab-key x ...) (values x ...)])
. match: syntax error in pattern in: #s(prefab-key x ...)
```

This seems like a bug to me at the moment. Can we please also had an example to the guide/reference on matching prefab structs?

**Comment by dfeltey** [comment]
According to the docs, prefab struct patterns have to appear under a quasiquote. These slight variations on your code should work:

```
#lang racket

(match #s(pos 1 2)
  [`#s(pos ,x ...) x])

(match #s(pos 1 2)
  [`#s(pos ,x ,y) (+ x y)])
```

**Comment by pmatos** [comment]
You're right. I missed the fact the prefab struct was a `qp`. Thanks.
