### ISSUE TITLE
The form #%dot is not documented in section 3 "Syntactic forms"

### ISSUE THREAD

**Issue by soegaard** [racket/racket#1995]
The syntactic forms #%app, #%datum etc are all documented in section 3 "Syntactic forms".
The form  #%dot  is missing from this section.

**Comment by jeapostrophe** [comment]
@mflatt What do you think about this? There is no binding for `#%dot`, `#%brackets`, or `#%braces`, so there's not a syntactic form to specifically document. I think at least we should add index entries in 1.3.19 and 1.3.6 to help figure out where they come from, but I'm not sure they should be in section 3.

**Comment by soegaard** [comment]
Is there a suitable place to list all #%something forms?

**Comment by mflatt** [comment]
The `#%dot` identifier doesn't have a binding as a syntactic form in `racket/base` the same way that `#%app` or `#%datum` does. It's just a symbol that the reader can produce, similar to the way the reader can produce `quote`.

The `remix` language has a `%dot` form, so its documentation would put `#%dot` alongside other syntactic forms.

I suppose it might make sense to have a list of symbols that the reader can produce even when you don't write them textually. That list would include `#%dot`, `#%bracket`, `#%braces`, `quote`, `quasiquote`, `syntax`, `module`, and more — but it wouldn't include `#%app` or `#%datum`, so I don't think that's the list you had in mind.
