### ISSUE TITLE
bad error from ->* on duplicate keywords

### ISSUE THREAD

**Issue by rmculpepper** [racket/racket#1997]
The `->*` form gives an error from `car` or `lambda` if given duplicate keywords:

    > (->* [] [#:a any/c #:a any/c] void?)
    ; car: contract violation
    ;   expected: pair?
    ;   given:
    ;     #<syntax:/opt/racket-6.12/collects/racket/contract/private/arrow-val-first.rkt:772:23
    ;     (#:a a22)>
    > (->* [#:a any/c #:a any/c] [] void?)
    [similar]
    > (->* [#:a any/c] [#:a any/c] void?)
    ; readline-input:5:18: λ: duplicate keyword for argument
    ;   at: #:a
    ;   in: (λ (#:a a41 #:a (a42 arrow:unspecified-dom)) [....]

**Comment by rfindler** [comment]
Fixed by https://github.com/racket/racket/commit/c442e9707f8ac023723edc6e00a560978fc0c934
