### ISSUE TITLE
expr/c leaves build-time path references in compiled .zo files

### ISSUE THREAD

**Issue by dbenoit17** [racket/racket#2006]
While working on [this issue](https://github.com/racket/web-server/issues/36), `expr/c` was discovered to be the cause of references to build-time paths in compiled files.  The path references disappear when the `.c` attribute is commented out, as demonstrated in [this commit](https://github.com/dbenoit17/web-server/commit/6ebe00c9e82bb5afb4b44e2bde9d880a43109a3c).

Thanks to @jeapostrophe for pinpointing this issue here.

**Comment by jeapostrophe** [comment]
@rmculpepper Can you take a look?
