### ISSUE TITLE
building racket 6.12 from source generates version mismatch

### ISSUE THREAD

**Issue by pmatos** [racket/racket#2022]
It seems that compiling an old version from source causes problems.

After a `git checkout v6.12`, and:
```
make CONFIGURE_ARGS_qq='CFLAGS="-Og -Wall -g" --enable-gracket --enable-jit --enable-foreign --enable-places --enable-futures --enable-float --enable-racket=/home/pmatos/installs/racket-6.12/bin/racket --enable-backtrace --enable-pthread --disable-strip --enable-ubsan --enable-xonx' CPUS=16
```

I hit:
```
raco pkg install: version mismatch for dependency
  for package: 2d-lib
  mismatch packages:
    base (have 6.12, need 6.90.0.19)
```

i am surprised this happens because I am in tag `v6.12`, with no racket version in `PATH` so this should just work and not know about `6.90.0.19`.

**Comment by mflatt** [comment]
See #1987 for an explanation and the simplest way to point your checkout to a suitable catalog. (And the point of that PR is that we'll make this better in future tags.)

**Comment by pmatos** [comment]
That explains it. Thanks. If you don't need this PR as a reminder, feel free to close it.
