### ISSUE TITLE
Feature Request: Add rkt and scrbl file types to Quicklook

### ISSUE THREAD

**Issue by soegaard** [racket/racket#2026]
Adding rkt and scrbl to Quicklook would make it easier to find a file using Finder.
It might even be possible to use Finder to search for text inside source files.

https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/Quicklook_Programming_Guide/Introduction/Introduction.html

**Comment by ashwinpn** [comment]
Do we need to know the Quicklook architecture for this?

**Comment by soegaard** [comment]
The simplest solution is to display Racket source as a plain text file.
There must be other "show as text files" file formats out there, whose
solution can be imitated.

For a fancy display with source highlighting more work needs to be done,
but I am content with a plain text solution.

**Comment by sorawee** [comment]
Quicklook now displays Racket source as plain text file (Big Sur). Can you confirm, @soegaard?

**Comment by sorawee** [comment]
Confirmed by @soegaard. Also tested on a new laptop with default settings, and it works too. Closing.
