### ISSUE TITLE
unsafe-fxlshift doesn't seem to do what it is documented to do

### ISSUE THREAD

**Issue by endobson** [racket/racket#2034]
https://docs.racket-lang.org/reference/unsafe.html?q=unsafe-fxlshift#%28def._%28%28lib._racket%2Funsafe%2Fops..rkt%29._unsafe-fxlshift%29%29

The docs for unsafe-fxlshift make it seem like it works by doing arithmetic shifts over a 2's complement number with the number of bits in a fixnum (63 for me). Thus if I shift a number 63 bits I would expect to get 0 as all the bits have been shifted off and the sign bit is now 0. This doesn't seem to happen and instead the result is as if the math was done with infinite precision 2's complement arithmetic.

The important section of the docs
> In the case of unsafe-fxlshift, bits in the result beyond the number of bits used to represent a fixnum are effectively replaced with a copy of the high bit.

```
> (unsafe-fxlshift 1 63)
9223372036854775808
> (fxlshift 1 63)
; fxlshift: result is not a fixnum
;   result: 9223372036854775808
; [,bt for context]
```

**Comment by mflatt** [comment]
I think the problem is specific to constant folding – that is, it only happens when the compiler can infer literal arguments to `unsafe-fxlshift` – and I'll fix the optimizer.
