### ISSUE TITLE
Racket "vanishing" its own files

### ISSUE THREAD

**Issue by birrellwalsh** [racket/racket#2045]
I have been using Racket as a member of Dan Goodman's Programming Language B class.  All was fine until this morning.  Then Racket started saying that .rkt  files I could see with my windows File Explorer did not exist.  These are files that worked last night.

I am using  Racket 6.8 (Thanks for which)

**Comment by soegaard** [comment]
That sounds odd indeed. Are the files within a special folder of some kind (Dropbox, OneDrive, etc)?
I haven't got better idea than to restart the computer and see if it helps.

**Comment by birrellwalsh** [comment]
I have restarted the machine, and the problem (the missingness of the last several days' work) persists.  I have found other files from other weeks and they too have appeared in file explorer - one with 11 K - and then when I have tried to open them in Racket, I am told the file does not exist.   When I open the same file in Visual Studio Code, it loads and I see the (appropriate) Racket code that Racket said did not exist.  Puzzling, eh?

The files are int he same place they were when they opened just fine last night.

**Comment by samth** [comment]
@birrellwalsh A few questions: 

- Is the file in a OneDrive folder? There have been (now-fixed) problems with that.
- Can you say exactly what you mean by "I am told the file does not exist"? How are you trying to open the file? What error message do you get? If you can include a screenshot, that would be great.

**Comment by birrellwalsh** [comment]
I attach two jpgs.  One shows Racket saying that the file "ws52 - Copy.rkt" does not exist, while in the File Explorer  underneath you can see that it does.   I have tried to open this and other files in two ways: by clicking on them in the windows 10 File Explorer, and by opening Racket and using "File | Open" to attempt to load the file.

I also attach a jpg to show how VS Code sees the brief Racket file.

Yes, it is a file in One-Drive.  Up until April 15, the files were opening fine from One Drive.  Then yesterday this started.   I am running DrRacket 6.8 - do I need to upgrade or replace it?

Thanks for your help


![what racket says about ws52 copy](https://user-images.githubusercontent.com/1509366/38878085-05a17980-4215-11e8-896a-44abeb0d66ab.JPG)
![ws52 copy in vs code](https://user-images.githubusercontent.com/1509366/38878086-05b7ea26-4215-11e8-8c0f-528a53938514.JPG)

**Comment by birrellwalsh** [comment]
OK, I upgraded to 6.12.  It seems to have fixed the problem.  Thank you!
