### ISSUE TITLE
syntax-local-lift-require is permitted in a 'module-begin context in Racket 7, but does not actually work

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#2052]
The following program fails with an error:

```racket
#lang racket/base

(require (for-syntax racket/base
                     syntax/strip-context)
         syntax/parse/define)

(provide #%module-begin)

(define-syntax-parser #%module-begin
  [(_ . body)
   (syntax-local-lift-require
    'racket
    (datum->syntax #f (cons '#%module-begin (strip-context #'body))))])

(module* test (submod "..")
  (match-define _ #f))
```
```
expand: namespace mismatch; cannot locate module instance
  module: #<module-path-index:racket/match/match>
  use phase: 0
  definition phase: 0
  for identifier: #<syntax:bad.rkt:16:3 match-define>
```

It fails on Racket 6.12 as well, but much earlier and with a different (less confusing) error:

```racket
syntax-local-lift-requires: could not find target context
  context...:
   standard-module-name-resolver
```

I would actually very much appreciate it if `syntax-local-lift-require` was made to work properly in a `'module-begin` context, but if that doesn’t make any sense, it should signal an error like it does in Racket 6.12.

**Comment by mflatt** [comment]
I've pushed a repair to restore v6.12 behavior.

So far, trying to make `syntax-local-lift-require` work in a 'module-begin context doesn't sound like a good idea. For the purposes I can imagine, a trampoline to a macro within `#%plain-module-begin` seems better. However, you may have an example that I haven't imagined, so I'm open to the possibility that `syntax-local-lift-require` should work in a 'module-begin context.

**Comment by mflatt** [comment]
In case you haven't looked at it already, I think the "hyper-literate" package does something like that, but with `local-expand` on a synthesized submodule (if I remember correctly).

**Comment by lexi-lambda** [comment]
Yes, it looks like I got a trampoline that works for my needs. I think I can also apply this technique to fix something in Hackett, but that’s for another day. Thanks for your help. :)
