### ISSUE TITLE
syntax/parse/experimental/template docs need to be updated since it moved

### ISSUE THREAD

**Issue by jsmaniac** [racket/racket#2080]
After 8d607b83f9966a4e3d3ae269dbc9960f3810d7ae — Thanks @rmculpepper :) — syntax/parse/experimental/template stopped being "experimental", and is now used as `syntax`, `syntax/loc` etc.

We'll need to update the documentation at some later point: move the syntax/parse/experimental/template description to the right place, and document the changes (e.g. `define-template-metafunction` is still in experimental).

**Comment by rmculpepper** [comment]
I did update the docs: the current description of `template` is "Equivalent to `syntax`", and the `syntax` docs describe the new template forms. (The changes won't hit docs.racket-lang.org until the next release, but they're visible on the snapshot docs pages.)

**Comment by lexi-lambda** [comment]
The docs for metafunctions do need to be updated slightly, I think. They currently say:

> A metafunction application in a `template` expression **(but not a `syntax` expression)** is evaluated by applying the metafunction to the result of processing the “argument” part of the template.

Emphasis mine. Unless the docs are correct and the implementation is wrong, I think that should be changed.

**Comment by jsmaniac** [comment]
My bad, I probably looked at docs.racket-lang.org without thinking. Sorry about the noise.

I opened a PR for the small update suggested by @lexi-lambda .
