### ISSUE TITLE
Racket not able to show cyrillic properly in console.

### ISSUE THREAD

**Issue by AlexStefanov2** [racket/racket#2087]
Cyrillic works properly in drracket, and my console has proper cyrillic support and works fine with python. The issue only comes when I launch racket in the console and want to use cyrillic. The console I'm using is cmder (version 180206) with the default settings. Here are some screenshots of the issue.

[Screenshot 1.](https://imgur.com/H7KOKuN)
[Screenshot 2.](https://imgur.com/8PchIEG)

I have absolutely no idea why it happens...

**Comment by olopierpa** [comment]
You must tell racket what encoding to use.

You can try some suggestions offered in this thread:

https://lists.racket-lang.org/users/archive/2013-March/056993.html

HTH 


Il giorno 19 maggio 2018, alle ore 12:26, Alex Stefanov <notifications@github.com> ha scritto:

>
>
>Cyrillic works properly in drracket, and my console has proper cyrillic support and works fine with python. The issue only comes when I launch racket in the console and want to use cyrillic.

**Comment by mflatt** [comment]
Does installing the "readline-gpl" package solve the problem?

By default (and for licensing reasons), Racket uses libedit, which usually isn't built with Unicode support. Installing "readline-gpl" switches Racket to use readline instead of libedit.

**Comment by NoCheroot** [comment]
I have to fight with this issue in several languages on a regular basis.  I've never found a cross platform way to deal with it.  Very frustrating.

Installing `readline-gpl` did not resolve this for me.  Is there something which has to be done after installing it to make it have an effect?

I've always had to resort to native api calls to get this to work in Windows.  I'm definitely open to a better option if someone has it.

```Racket
#lang racket

(require ffi/unsafe
         ffi/unsafe/define
         ffi/winapi)

(define kernel32-dll (and (eq? (system-type) 'windows)
                          (ffi-lib "kernel32.dll")))

(define-ffi-definer define-kernel32 kernel32-dll
  #:default-make-fail make-not-available)

(define-kernel32 SetConsoleOutputCP (_fun #:abi winapi
                                         _uint
                                         -> _bool))


(define j "私のホバークラフトは鰻でいっぱいです\n")
(define g "Το αερόστρωμνο μου ειναι γεμάτο χέλια\n")
(define r "Моё судно на воздушной подушке полно угрей\n")

(display j)
(display g)
(display r)

(SetConsoleOutputCP 65001)

(display j)
(display g)
(display r)
```

![hovercraft](https://user-images.githubusercontent.com/10468415/40269049-26d3f730-5b3e-11e8-8609-5ae9aa5fcfbc.png)

**Comment by NoCheroot** [comment]
Sorry to reply to my own comment.  Wanted to add a follow up with input.

I don't actually _know_ Racket yet, so this took me a minute.  I still find Racket ffi pretty mind bending.  Not doing any error handling here, and all of this is probably completely wrong.  Point is, this sort of thing is what I resort to when dealing with utf in the terminal on Windows in any language except c or c++ (they have nice macros for it).

```
#lang racket

(require ffi/unsafe
         ffi/unsafe/define
         ffi/winapi)

(define kernel32-dll (and (eq? (system-type) 'windows)
                          (ffi-lib "kernel32.dll")))

(define-ffi-definer define-kernel32 kernel32-dll
  #:default-make-fail make-not-available)

(define-ffi-definer define-racket (ffi-lib #f))

(define _DWORD _int32)
(define _UINT _uint)
(define _BOOL _bool)
(define _HANDLE _intptr)

(define STD_INPUT_HANDLE -10)
(define cp 65001)

(define-kernel32 ReadConsoleW (_fun #:abi winapi
                                    _HANDLE
                                    (chars : _bytes)
                                    _DWORD
                                    (chars-read : (_ptr o _DWORD))
                                    _pointer
                                    -> _BOOL
                                    -> (values (cast chars _pointer _string/utf-16) chars-read)))
                                    

(define-kernel32 GetStdHandle (_fun #:abi winapi
                                    _DWORD
                                    -> _HANDLE))

(define-kernel32 SetConsoleCP (_fun #:abi winapi
                                    _UINT
                                    -> _BOOL))

(define-kernel32 SetConsoleOutputCP (_fun #:abi winapi
                                          _UINT
                                          -> _BOOL))

(void (SetConsoleCP cp))
(void (SetConsoleOutputCP cp))

(define hstdin (GetStdHandle STD_INPUT_HANDLE))

(define inbuf (make-bytes 1024 0))

(display "Enter some utf: ")
(flush-output)

(define-values (i n) (ReadConsoleW hstdin inbuf (bytes-length inbuf) #f))

(display "User entered: ")
(display i)
```

![hovercraft2](https://user-images.githubusercontent.com/10468415/40271354-db8f3644-5b61-11e8-8f55-366a8c8f74f9.png)

If `readline-gpl` can solve this problem please let me know.  I have not had any luck with it on Windows so far.

**Comment by mflatt** [comment]
Sorry — using "readline-gpl" can help on Unix variants, but not Windows, so that wasn't a good suggestion.

If I understand what @NoCheroot is trying, that would set the terminal to UTF-8, which is generally what Racket expect. Another possibility is to switch Racket's output to CP1251, assuming that's your terminal's mode:
```
(current-output-port (reencode-output-port (current-output-port) "CP1251"))
```

**Comment by NoCheroot** [comment]
```Racket
#lang racket
(current-output-port (reencode-output-port (current-output-port) "CP1251"))

(display "Enter some utf: ")
(flush-output)

(define i (read-line))

(display "User entered: ")
(display i)
(flush-output)
```

and

```Racket
#lang racket
(current-output-port (reencode-output-port (current-output-port) "CP1251"))
(current-input-port (reencode-input-port (current-input-port) "CP1251"))

(display "Enter some utf: ")
(flush-output)

(define i (read-line))

(display "User entered: ")
(display i)
(flush-output)
```

result in this:

![hovercraft3](https://user-images.githubusercontent.com/10468415/40272179-43ea9032-5b6f-11e8-9c8b-a2ea58735aff.png)

😞

**Comment by mflatt** [comment]
After refreshing my memory on how encodings, Unicode, and consoles interact on Windows, I don't think there's a good answer in Racket right now.

You get can ok output by setting the console's code page to 65001, either using @NoCheroot's code or using the command ``chcp 65001`` before starting Racket, but that doesn't work for input via functions like `read-line`.

To make Unicode input and output work with a console, Racket's I/O layer will have to change to detect that it's connected to a console and use a console-specific Windows API. That extra support will translate between wide-character I/O on the console side to a UTF-8 ports on the Racket side. (Having arrived at that conclusion, I see that it's apparently how Python works, too:
https://www.python.org/dev/peps/pep-0528/ )

**Comment by NoCheroot** [comment]
Can you suggest a good starting point for those changes to Racket?  My Racket knowledge/skill isn’t strong enough to build a worthy PR for it yet, but I could stand to spend the time experimenting.

**Comment by mflatt** [comment]
The changes will need to be in "racket/src/rktio/rktio_fd.c". I very much(!) appreciate your interest and effort, but I'm trying some changes now while I have everything paged in.

**Comment by NoCheroot** [comment]
Thanks 😄

**Comment by mflatt** [comment]
The next release should work correctly. You can try it out in the next snapshot dated 20180521 or later (available about 24 hours from now) from https://pre.racket-lang.org

Meanwhile, although we have workarounds like ``chcp 65001`` for the output side, I still don't see a way to fix the input side for the current release. It's possible that there's still some console configuration option that I don't know.

**Comment by NoCheroot** [comment]
Thank you.  This will save me a lot of trouble.
