### ISSUE TITLE
Drracket throw an error  whenever it keeps running for more then a few hours.

### ISSUE THREAD

**Issue by pbpf** [racket/racket#2095]
![dracketbug](https://user-images.githubusercontent.com/6541871/40336015-845df47a-5d99-11e8-9590-a7fd13fa6f5d.png)

Drracket throw this error (or sometime an runtime error)  whenever it keeps running (even just launch and do nothing) for more then a few hours.

v6.12.
operating system is win10.

**Comment by rfindler** [comment]
Is it possible you have more than one DrRacket running?

**Comment by mflatt** [comment]
Although the problem was never determined, closing because it has been so long.
