### ISSUE TITLE
Racket Docs Issue

### ISSUE THREAD

**Issue by Vm900** [racket/racket#2096]
After running raco setup the help-desk appears to be corrupted.
Here is what i see now
![racketdocumentation](https://user-images.githubusercontent.com/9399631/40376847-50746696-5de7-11e8-8829-ccbe14d176cb.png)

Help
Thanx

**Comment by jsmaniac** [comment]
I often see that happen.

I have been told that running `raco setup` a couple of times in a row should fix it, but `raco setup` has to exit successfully (no compilation errors). Still, I think it doesn't always solve the problem for me.
