### ISSUE TITLE
Racket7 test failures

### ISSUE THREAD

**Issue by samth** [racket/racket#2099]
Build failures are at #2090.

#### Caused by the new expander, expander probably needs fixing
- [x] [colon-kw](https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/colon-kw.txt) new placeholder values in `read/recursive`, fixed by https://github.com/AlexKnauth/colon-kw/commit/a338070d902753978a5a297c737845c013231ea7
- [x] [turnstile](https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/turnstile.txt) Fixed by https://github.com/racket/racket/commit/c7318cab33de113ec475d7e9fd6b0ceab8fcb61d
- [x] [adjutor](https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/adjutor.txt) probably caused by different error messages in the new expander
- [x] [cur-test](https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/cur-test.txt) @wilbowma 
- [x] [remix](https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/remix.txt) cc @jeapostrophe Fixed by https://github.com/racket/racket/commit/0d870fb11ce3e3a5b890ebb1786a536742d83f71

#### Caused by the new expander, intentional change

- [x] [rackjure](https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/rackjure.txt) related to `#%top`, see @lexi-lambda's comment, to be fixed in rackjure, cc @greghendershott  
- [x] [frog](https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/frog.txt) error message change @greghendershott 

#### Possibly caused by the new expander

- [x] [rex](https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/rex.txt) @alehed 
- [ ] [racketscript-compiler](https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/racketscript-compiler.txt) @stchang 

#### Broken by other changes

- [x] [delay-pure](https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/delay-pure.txt) @jsmaniac Seems related to new keyword expansion

#### Timeouts

- [x] [ralist](https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/ralist.txt) Tests pass locally

#### Other

- [x] [crypto-test](https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/crypto-test.txt) Bug exposed by new openssl version

#### Probably non-deterministic hash ordering

- [x] [csp](https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/csp.txt) @mbutterick 
- [ ] [symalg](https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/symalg.txt) @pyohannes
- [x] [rmacs](https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/rmacs.txt) @tonyg 
- [x] [yaml](https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/yaml.txt) @esilkensen 
- [x] [sinbad](https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/sinbad.txt) @nadeemabdulhamid

**Comment by AlexKnauth** [comment]
For `colon-kw`, the error was coming because `read/recursive` was returning `#<placeholder>` instead of a symbol. I was able to fix it by passing giving a false value to the optional `graph?` argument to read/recursive. 

However, I don't know whether there might be other code that calls `read/recursive` or `read-syntax/recursive` that might break because of this change in behavior in Racket 7. Is there a reason why it "has to" return `#<placeholder>` there, or can this be fixed back to the old Racket 6.12 behavior?

**Comment by rmculpepper** [comment]
The crypto-test error should be fixed now.

**Comment by LiberalArtist** [comment]
I think I remember that the new expander generates a different error message instead of things like "z: unbound identifier in module". If so, that would be the problem for `adjutor`.

I'm guessing the right thing to do would probably be for me to create a branch that does the right error-message check for Racket 7 and tell the package catalog server about it.

**Comment by samth** [comment]
@rmculpepper what was the problem with `crypto-test`?

@LiberalArtist You could also change the test to accept both messages.

**Comment by rmculpepper** [comment]
@samth the `crypto-test` error was a bug exposed by openssl 1.1; it was unrelated to racket changes. All openssl AEAD ciphers (before openssl 1.1) corresponded to specific block cipher modes (eg GCM, OCB). When I updated my code to recognize chacha20-poly1305 (an AEAD stream cipher), I forgot to update some of the places that conditionally did AEAD-specific operations like fetching the authentication tag at the end of encryption.

**Comment by LiberalArtist** [comment]
In addition to the unbound identifier error message change, `adjutor` was affected by a change in the errors raised by `map`. The current snapshot catches an error missed by the 6.12 `map`, but gives an arguably worse error message for a broader class of errors.

Given the function:
```racket
(define (example by-pos #:kw required-kw)
  'ok)
```

In Racket 6.12, `(map example null)` returns `null`, whereas in Racket 6.90.0.29--2018-05-22(caade2f830/a) it raises an exception, which I think is better.

However, the snapshot gives a confusing error message when `map` is passed function with a required keyword argument. Both `(map example null)` and `(map example '(1))` give the following error message, modulo the specific value for "argument lists":
```
map: argument mismatch;
 the given procedure's expected number of arguments does not match the given number of lists
  given procedure: example
  expected: 1
  given: 1
  argument lists...: 
   '(1)
```

It is nice that this error comes from `map` and not the attempt to apply `example`, but the "expected" and "given" numbers are the same and no mention is made of keywords, which I think is confusing. In Racket 6.12, the error from `(map example '(1))` is:
```
application: required keyword argument not supplied
  procedure: example
  required keyword: #:kw
  arguments...:
   1
```

**Comment by lexi-lambda** [comment]
For the `rackjure` errors, it looks like the new expander does not replicate a somewhat curious behavior of the old expander, which didn’t introduce explicit uses of `#%top` when expanding in a top-level context in a module namespace (this is, one created with `module->namespace` or `namespace-anchor->namespace` where the anchor is defined within a namespace). For example:

```racket
Welcome to Racket v6.12.
> (expand #'unbound)
#<syntax:10:10 (#%top . unbound)>
> (parameterize ([current-namespace (module->namespace 'racket/base)])
    (expand #'unbound))
#<syntax:9:12 unbound>
> (module anchor racket/base
    (define-namespace-anchor anchor)
    (provide anchor))
> (require 'anchor)
> (define ns (namespace-anchor->namespace anchor))
> (parameterize ([current-namespace ns])
    (expand #'unbound))
#<syntax:7:12 unbound>
```

I’m not sure if this behavior is worth preserving or not, and I think only @mflatt can answer that question.

**Comment by stchang** [comment]
The `turnstile` error is almost definitely due to https://github.com/racket/racket/issues/1495 (see also [mail thread 1] and [mail thread 2]), but probably a new variant of it (introduced with the new expander?), since:
- the tests pass with 6.12
- and the usual method of fixing it (delaying expansion until import) doesnt work

We've run into this issue on multiple occasions and @michaelballantyne has usually been able to figure out a workaround but this time we might be stuck.

[mail thread 1]: https://groups.google.com/forum/#!topic/racket-users/ZWjpz3kFmjo
[mail thread 2]: https://groups.google.com/forum/#!topic/racket-users/TGax2h8dVxs

**Comment by mflatt** [comment]
@LiberalArtist @samth No need for an issue; I have a repair to push soon.

@LiberalArtist Thanks for the report. The part that was an improvement was a kind of accident – a result of making `map` fully implemented in Racket to support of Racket-on-Chez.

**Comment by mflatt** [comment]
@lexi-lambda I agree with what (I think) you're suggesting, which is that we don't want to preserve/restore that old behavior.

**Comment by lexi-lambda** [comment]
I agree; that is what I am suggesting. I think an easy way to fix the test so it works on both versions of the expander is to use an identifier that is actually bound to a value instead of using an unbound identifier.

**Comment by mflatt** [comment]
On `read/recursive`: probably it should not return a placeholder when *not* in the dynamic extent of a `read` call, and I'll investigate more.

**Comment by mflatt** [comment]
On `read/recursive`: it looks like the documentation is wrong and this facet of the new reader was based on the docs. The `read/recursive` function doesn't always wrap its result in a placeholder in 6.12, and it's trivial to make the new reader match the old behavior. I'll do that and fix the docs.

(Historically, I think there would have been an issue with exposing partially read values; if I remember correctly, that issue went away with the `make-reader-graph` approach to constructing cycles. Probably placeholder values became non-opaque at the same time.)

**Comment by stchang** [comment]
All of the other "unknown" failures (except `remix`) seem to be caused by the tests relying on a particular ordering of hash keys (which has changed since 6.12?).

**Comment by samth** [comment]
Hash ordering hasn't changed, it just probably ends up different on the NWU machine than on the pkg-build machine at Utah. Should maybe open issues or at least cc the authors of those packages.

**Comment by rfindler** [comment]
@stchang @samth : Are you talking about the order in which loops iterate over hash keys?

**Comment by stchang** [comment]
Something definitely changed (random seed generation?) because I had to fix several tests as well, and they started failing on all machines (locally, and on travis).

**Comment by stchang** [comment]
@rfindler yes, possibly, did that change?

**Comment by rfindler** [comment]
As far as I understand it, you cannot rely on that ordering being anything in particular. It can change based on the phase of the moon.

**Comment by stchang** [comment]
Yes, I know. But sometimes people do, and I was trying to figure out if that is the cause of test failures (the tests should obviously be fixed regardless).

**Comment by LiberalArtist** [comment]
The tests for `adjutor` should be fixed by https://github.com/LiberalArtist/adjutor/commit/510cd351d6ad7cbff29d7a69f6a0c760730f5723

**Comment by mbutterick** [comment]
Tests for `csp` fixed in https://github.com/mbutterick/csp/commit/dfa52d0f0c50becd8ffaf8851824b0ec2e8ae9af

**Comment by esilkensen** [comment]
Tests for `yaml` should be fixed by https://github.com/esilkensen/yaml/commit/1c04345e0b05c0ec2332a6a0e8b079e35290aed4

**Comment by tonyg** [comment]
Tests for `rmacs` should be fixed by tonyg/rmacs@137b8cc7

**Comment by wilbowma** [comment]
I've traced the failure in cur-test to a use of `eval` that is surrounded by warnings that I'm probably doing something wrong. Anyone know what might have changed with `eval`?

**Comment by mflatt** [comment]
@wilbowma I think it's a bug in `eval` – more specifically, in `namespace-syntax-introduce` as used by `eval`. I'm testing a repair.

**Comment by samth** [comment]
@jsmaniac the description links to it, at https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/delay-pure.txt

**Comment by samth** [comment]
Also that error happens on travis too: https://travis-ci.org/jsmaniac/delay-pure/jobs/378941192#L968

**Comment by wilbowma** [comment]
Looks like `cur-test` all pass as of 7bbbb8f063252f0d1e594b2469f41402d8ac63f2

**Comment by jsmaniac** [comment]
`delay-pure` is broken due to racket/typed-racket#740 .

There were also other small issues due to internal changes to optional arguments, I'm currently pushing a patch for those.

**Comment by alehed** [comment]
For `rex` the regular invocation with a file still works.

For unit-testing, I wrote a [helper method](https://github.com/alehed/rex/blob/a419802796672a0046c4475a05bbc522ed8161a0/tests/helper.rkt#L9) that manually applied the parsing and eval steps, in order to invoke the program on strings instead of files. This helper method broke so I guess the problem really is not really with racket itself. At the time the method seemed like a hack to me.

**Comment by samth** [comment]
@alehed given the error message (which is at a layer that you shouldn't see) I'm pretty sure that the problem is a bug in the new expander, and not your fault.

**Comment by samth** [comment]
@jeapostrophe Can you look into what's going wrong with `remix`?

**Comment by jsmaniac** [comment]
@samth now that racket/typed-racket#740 is fixed, the package `delay-pure` works for me™.

**Comment by wilbowma** [comment]
Anyone notice errors arround `require/expose` related to this? I happened to be still running HEAD and had some errors that point to this, but haven't properly debugged yet.

**Comment by mflatt** [comment]
The `remix` failure was due to bugs in the reader, now fixed.
cc: @jeapostrophe

**Comment by mflatt** [comment]
@stchang I'm confused about the tunstile failure with v7. As you say, the problem in #1495 has been fixed. Meanwhile, the various mail threads were also about problems before the v7 expander. That is, it's not that bindings in syntax properties stopped working in v7; they never worked. Do you have an idea of why the tests pass with v6.12 and not v7?

**Comment by mflatt** [comment]
@stchang for `racketscript-compiler`: yes, `#%runtime` replaces `#%kernel` as the source of most primitive bindings. That change reflects how the expander assembles pieces from the C runtime in a separate primitive module than the additional pieces that are implemented by the expander.

**Comment by greghendershott** [comment]
>  `#%runtime` replaces `#%kernel` as the source of most primitive bindings.

I fixed a tiny issue with this in racket-mode [commit d3b639a](https://github.com/greghendershott/racket-mode/commit/d3b6395c5e63bfc5d73ad329eb152db533e5c294).

racket-mode isn't on the #2099 list...

- because it's not a Racket package...

- because the Racket code is instead delivered as part of an Emacs MELPA package...

- because I always found it annoying with CIDER that the Emacs and Clojure parts drifted out of sync.

That does mean racket-mode is "invisible" wrt this issue #2099. But I do have Travis CI always build against snapshot.

**Comment by mflatt** [comment]
@stchang Commit c7318cab33de113ec475d7e9fd6b0ceab8fcb61d should fix the `turnstile` test.

**Comment by alehed** [comment]
@mflatt Thanks, I can confirm that the `rex` issue is fixed.

**Comment by stchang** [comment]
@mflatt Will using `#%runtime` instead of `#%kernel` make the code incompatible with previous Racket versions?

**Comment by stchang** [comment]
Oh and `turnstile` tests pass with Racket7 now, thanks.

**Comment by mflatt** [comment]
@stchang Yes, the `racketscript-compiler` test will have to do something different, like ignore whether `#%runtime` or `#%kernel` in the result, to work for both v6.x and v7.x.

**Comment by samth** [comment]
Three new test failures: `hackett-doc`, (cc @lexi-lambda) `msgpack`, and `parsack` (@stchang).

**Comment by samth** [comment]
However, it appears that the `hackett-doc` and `msgpack` failures are timeouts, and the `parsack` failure is a regression caused by #2058 which isn't on the release branch.

**Comment by lexi-lambda** [comment]
It’s not surprising to me that `hackett-doc` takes more than 90 seconds—the documentation takes a long time to build—but I’m not sure what the appropriate fix is. Should I add the `.scrbl` files to `test-omit-paths`? That seems probably okay, since pkg-build is going to run those files already as a part of rendering the documentation.

**Comment by samth** [comment]
I believe that you can increase the timeout for that file -- it isn't running into the overall test timeout.

**Comment by lexi-lambda** [comment]
I thought about that, too, but it seems like that would still duplicate a lot of work—won’t it effectively run every `.scrbl` file included with `include-section` twice? (Or more, if it’s transitively included.) It seems unnecessary to run `raco test` on the scribblings that have already been executed by the build process.

**Comment by samth** [comment]
Closing now that v7 is out.
