### ISSUE TITLE
make-custom-hash-types and make-custom-set-types

### ISSUE THREAD

**Issue by joskoot** [racket/racket#2110]
Hi,
Hoping this is the right forum to place the following issue:

make-custom-set-types returns its values in another order than documented. (see below)
It would be nice to have make-custom-set-types return its values as documented
(in the same order as make-custom-hash-types does)

I find the name define-custom-hash-types confusing because the types
are accepted by dict-xxx procedures but not by hash-xxx procedures.
Has 'make-custom-dict-types' ever been considered?
I must admit that the docs do clearly state that the constructors produce dictionaries, though. 

> (make-custom-hash-types =)
#<procedure:custom-hash?>
#<procedure:immutable-custom-hash?>
#<procedure:mutable-custom-hash?>
#<procedure:weak-custom-hash?>
#<procedure:make-immutable-custom-hash>
#<procedure:make-mutable-custom-hash>
#<procedure:make-weak-custom-hash>

> (make-custom-set-types =)
#<procedure:custom-set?>
#<procedure:weak-custom-set?>
#<procedure:mutable-custom-set?>
#<procedure:immutable-custom-set?>
#<procedure:make-weak-custom-set>
#<procedure:make-mutable-custom-set>
#<procedure:make-immutable-custom-set>

Thanks, Jos

**Comment by joskoot** [comment]
Agreed, better for future compatibility.
Jos

  _____

**Comment by gus-massa** [comment]
I'd like that someone else confirm my plan before proceeding: Update the docs and add this to the Racket2 wish list.

**Comment by gus-massa** [comment]
@joskoot : Do you want to send the PR? The file is [racket-doc/scribblings/reference/sets.scrbl#L885](https://github.com/racket/racket/blob/4481546481a8e40fe555af5fbc426c3834e6276b/pkgs/racket-doc/scribblings/reference/sets.scrbl#L885) Please also fix the link at the bottom.

If you can't, I'd be happy to write it.

**Comment by joskoot** [comment]
I tried to edit the file, but it seems I am not allowed to do that.
I get a complaint that I must be on a branch.
So I would be happy if you can do it.

It only takes reordering of the following items:

933 @itemize[ 
934 @item{a predicate recognizing all instances of the new set type,} 
935 @item{a predicate recognizing immutable instances,} 
936 @item{a predicate recognizing mutable instances,} 
937 @item{a predicate recognizing weak instances,} 
938 @item{a constructor for immutable instances,} 
939 @item{a constructor for mutable instances, and} 
940 @item{a constructor for weak instances.} 

Thanks, Jos

**Comment by gus-massa** [comment]
Thanks. The fix is merged now in https://github.com/racket/racket/commit/76c30df8e652aa4c2ed23110a4ede477113f0538 . (I'm not sure if it too late for this fix to appear in the version 7.0 or the fix will be published in 7.1.)

If in the future you want to make a PR I think you must make a clone of the repository and then make the changes. There are some tutorials in [wiki/Contributing](https://github.com/racket/racket/wiki/Contributing-to-Racket#guides-to-contributing-to-racket) and there must be like a million more tutorials out there.

Anyway, the bugs report are also welcome. Thanks again.
