### ISSUE TITLE
Initial namespace does not properly interleave expansion and evaluation when evaluating begin

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#2111]
This fails on Racket 7:

```
$ racket -e '(begin (define-syntax x 42) (define-values () (let-syntax ([ignored (syntax-local-value #'\''x)]) (values))))'
syntax-local-value: unbound identifier: #<syntax:string::91 x>
  context...:
   expand+eval-for-syntaxes-binding108
   for-loop
   expand-capturing-lifts
   expand-single
   temp74_1
   begin-loop
   [repeats 1 more time]
   compile16
```

However, it works fine on Racket 6.12.

**Comment by lexi-lambda** [comment]
@florence pointed out that this error only happens when passing an expression to evaluate with `-e`. Evaluating the expression interactively does not trigger the error.

**Comment by lexi-lambda** [comment]
I’ve tracked down the source of this bug. `-e` goes through a different code path that calls `compile` followed by `eval` from C, which doesn’t interleave evaluation and expansion. In Racket 6.12, the C implementation of `compile` implicitly performed evaluation if a `for_eval` flag was set:

https://github.com/racket/racket/blob/4f9c2133041ae952ed34d5a208317ac86103158f/racket/src/racket/src/eval.c#L4215-L4219

Racket 7’s `compile` does not ever perform this evaluation, so the whole form is expanded before any evaluation takes place. I’m not sure what the right fix is here, but hopefully that extra context helps somewhat.

**Comment by mflatt** [comment]
Thanks! I’ll push a repair soon.
