### ISSUE TITLE
Expanding with a definition context in a 'module-begin context can cause namespace mismatch errors

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#2115]
This program fails at compile-time on Racket 7 with a namespace mismatch error:

```racket
#lang racket/base

(module l racket/base
  (require (for-syntax racket/base racket/syntax)
           syntax/parse/define)

  (provide #%module-begin m
           (all-from-out racket/base))

  (define-syntax-parser #%module-begin
    [(_ form ...)
     (let ([intdef-ctx (syntax-local-make-definition-context #f #f)])
       (local-expand #'(#%plain-module-begin form ...)
                     'module-begin
                     '()
                     intdef-ctx))])

  (define-syntax-parser m
    [(_)
     #:with x (generate-temporary)
     #'(begin
         (define x #f)
         (begin-for-syntax #'x))]))

(module c (submod ".." l)
  (#%module-begin
   (m)))
```
```
expand: namespace mismatch; cannot locate module instance
  module: #<module-path-index=(submod 'ns-mismatch[2541] c)>
  use phase: 1
  definition phase: 0
  for identifier: #<syntax g1>
  context...:
   binding->module-instance
   binding-lookup50
   loop
   /Users/alexis/gits/racket/racket/racket/collects/racket/private/template.rkt:291:4: parse-t-nonpair
   /Users/alexis/gits/racket/racket/racket/collects/racket/private/template.rkt:177:2: parse-template
   /Users/alexis/gits/racket/racket/racket/collects/racket/private/template.rkt:577:0: syntax
   apply-transformer-in-context
   apply-transformer52
   dispatch-transformer41
   loop
   expand+eval-for-syntaxes-binding108
   finish
   [repeats 1 more time]
   pass-1-and-2-loop
   module-begin-k
   do-local-expand50
   ...
```

The program expands successfully on Racket 6.12.

This is about as far as I could reduce the test case. This particular example depends on the intersection of three different things:

  1. Expansion must be forced in a `'module-begin` context with a definition context argument. Whether or not the definition context was created with a non-`#f` value for *`add-scope?`* is irrelevant, it still causes the error either way.

  2. A macro expanded in the definition context must generate a temporary identifier, then create a definition that binds that identifier.

  3. The same macro must reference the identifier under the `syntax` form. The error is not triggered if `quote-syntax` is used, nor is it triggered by `quote-syntax` followed by `identifier-binding` or `syntax-local-value`. I’m not sure exactly what `syntax` does that triggers the error.

This is pretty strange, so I really have no idea what the problem could be without further investigation.

**Comment by lexi-lambda** [comment]
Some extra interesting things of note:

  - The failure appears to happen when `syntax` inspects `x` with `syntax-local-value`.

  - When the definition context is provided to `local-expand`, `syntax-local-value` resolves `x` to a `full-module-binding`, but when the definition context is not provided, `syntax-local-value` does not find a binding for `x`.

Unfortunately, there are still many moving parts for me to figure out what’s going wrong, since I’m not entirely sure what’s supposed to happen here. (Why would `syntax-local-value` fail to find the binding when things go *right*?)

**Comment by mflatt** [comment]
The module lookup fails because `syntax-local-value` finds a should-be phase-0 binding when it was looking for a phase-1 binding.

The binding isn't restricted to phase 0 due to a lack of composition in `local-expand`. When a definition context is provided, then the enclosing context's `post-expansion-scope` is ignored. In a module-body expansion, the `post-expansion-scope` is the one that makes bindings phase-specific.

I think I have a repair, and I'll push if testing passes.

**Comment by lexi-lambda** [comment]
Thanks! I thought some of that looked a bit suspicious while I was digging around, but I wasn’t sure exactly how the pieces fit together. I’m pleased that your fix looks similar to something I had considered.

I did, however, have a question, which perhaps you can answer. What is the purpose of `post-expansion-scope` at all given the existence of `post-expansion-scope-action`? And, likewise, is it okay that `expand-module` adds `post-expansion-scope` directly instead of going through `post-expansion-scope-action`? What’s the difference between the two?

**Comment by mflatt** [comment]
The parts in `root-expand-context` need to be marshalable. The two separate fields are awkward, though, and `post-expand-shifts` make it worse.

A `module` form can mostly ignore the enclosing context, since it mostly starts fresh.

**Comment by mflatt** [comment]
I think I see how to clean things up, since the post-expansion value needs to be marshalable only in module and top-level contexts.

**Comment by lexi-lambda** [comment]
That does make sense, so thank you for the explanation. Unfortunately (or perhaps fortunately), that understanding gave me enough information to construct a slightly modified program that triggers the same error even with the patch; I’ll open another issue with the details.
