### ISSUE TITLE
Forcing expansion in a 'module-begin context can cause namespace mismatch errors if the surrounding context is not 'module-begin

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#2118]
Even with a1b5bab31b25bf1b3c7288355e78df4ae870467c, a modified version of the program in #2115 can still trigger the namespace mismatch error:

```racket
#lang racket/base

(module l racket/base
  (require (for-syntax racket/base racket/syntax)
           syntax/parse/define)

  (provide expand-in-modbeg m
           (all-from-out racket/base))

  (define-syntax-parser expand-in-modbeg
    [(_ form ...)
     (local-expand #'(#%plain-module-begin form ...)
                   'module-begin
                   '())
     #'(void)])

  (define-syntax-parser m
    [(_)
     #:with x (generate-temporary)
     #'(begin
         (define x #f)
         (begin-for-syntax #'x))]))

(module c (submod ".." l)
  (let ()
    (expand-in-modbeg
     (m))))
```

The program is different in two ways:

  1. While the context given to `local-expand` is still `'module-begin`, the macro that calls `local-expand` is not itself expanded in a `'module` or `'module-begin` context.

  2. A first-class definition context is not provided to `local-expand`. (The behavior is the same if one is provided, but I’ve omitted it because it’s not essential to triggering the bug.)

The change in a1b5bab31b25bf1b3c7288355e78df4ae870467c adjusts `local-expand` so that `post-expansion-scope` is never replaced with a different scope when the surrounding context matches the nested context, but it doesn’t help when the contexts differ. This program exposes a more fundamental issue than `local-expand` replacing `post-expansion-scope`, namely that expansion of `#%module-begin` does not re-instate the module’s value for `post-expansion-scope`, even if it is expanded in a context where `post-expansion-scope` has been changed.

My first instinct is to say that `module-begin-k` should be changed to perform the `post-expansion-scope` adjustment instead of `expand-module`, which would ensure that any nested expansion of `#%module-begin` will have the correct scopes. This might even eliminate the need for the special case in `make-local-expand-context`, but I’m not completely sure.

**Comment by mflatt** [comment]
Thanks – I'll make the easy change for now.

**Comment by mflatt** [comment]
As far as I can tell, the "easy" change was a good one. So, I'll close this, but please reopen if I misunderstand or misremember.
