### ISSUE TITLE
(contract-random-generate (</c +inf.0)) produces +inf.0

### ISSUE THREAD

**Issue by jessealama** [racket/racket#2121]
On Racket 6.12 (macOS), I find that `(contract-random-generate (</c +inf.0))` produces, unexpectedly, `+inf.0`. These don't seem to agree with one another:

    > (contract-random-generate (</c +inf.0))
    +inf.0
    > (< +inf.0 +inf.0)
    #f

**Comment by rfindler** [comment]
Fixed by: https://github.com/racket/racket/commit/aabd0e4603d237021a001eebecd45bc42764a22a

Thanks!
