### ISSUE TITLE
Better source location for error?

### ISSUE THREAD

**Issue by soegaard** [racket/racket#2128]
Is it possible to provide a better source location for the error message provoked by this program?

    #lang racket/base
    (define (loop #:foo foo)  (loop))
    (loop)

As is clicking the error icon in DrRacket sends you to racket/private/kw.rkt .

**Comment by sorawee** [comment]
Yeah, this happens so many times in our work that we have to add a filter to skip srcloc from `kw.rkt`.

**Comment by mflatt** [comment]
Looks like this was fixed, probably by 14e206bd0b9d8f5ee96cb87df4b86ae9f6e743fd.
