### ISSUE TITLE
find-executable-path should consider the system-type

### ISSUE THREAD

**Issue by Syntacticlosure** [racket/racket#2129]
On my computer (windows) , (find-executable-path "racket") returns #f , but (find-executable-path "racket.exe") returns the path of racket.
Is it better to implement find-executable-path like this?
```
(define (new-find-executable-path p)
  (find-executable-path (if (eq? (system-type 'os) 'windows)
                            (string-append p ".exe")
                            p)))
```

**Comment by mflatt** [comment]
I've been reluctant in the past to auto-add ".exe", but I think it might make sense to add ".exe" and try again if (1) the search fails with the given path and (2) no extension is already present.

**Comment by dmos62** [comment]
To chime in, in the Windows Command Prompt it's enough to enter `racket`, when the executable is on your PATH. I was a bit perplexed when `(find-executable-path "racket")` didn't work. If not for this thread I probably wouldn't have figured it out.
