### ISSUE TITLE
Tests Fail with release 6.12 on Centos 6

### ISSUE THREAD

**Issue by insertinterestingnamehere** [racket/racket#2137]
Hi, I noticed this while creating a conda package for racket (see https://github.com/conda-forge/staged-recipes/pull/6098). Currently the tests do not pass on CentOS 6. On the CI server in the linked pull request the tests hang, however they error out if tested locally. This issue first showed up inside the `condaforge/linux-anvil` docker image, however it can be replicated exactly inside the CentOS 6 docker image by running:

```
yum install centos-release-scl
yum install devtoolset-4-toolchain
yum install git
git clone https://github.com/racket/racket.git
cd racket
git checkout v6.12
source scl_source enable devtoolset-4
make unix-style PREFIX=/usr/local PKGS=""
raco setup
raco pkg config --set default-scope installation
raco pkg config --set catalogs \
    "https://download.racket-lang.org/releases/$PKG_VERSION/catalog/" \
    "https://pkg-build.racket-lang.org/server/built/catalog/" \
    "https://pkgs.racket-lang.org" \
    "https://planet-compats.racket-lang.org"
raco pkg install --auto --skip installed racket-test db-test unstable-flonum-lib net-test
raco test -l tests/racket/test
```

The output indicating the failure is
```
...
Section(port)
Section(file)
ERROR: expected an error
```

**Comment by insertinterestingnamehere** [comment]
FWIW, I think the error comes from [this line](https://github.com/racket/racket/blob/v6.12/pkgs/racket-test-core/tests/racket/file.rktl#L1923).

**Comment by mflatt** [comment]
The tests assume that they're not running as root, since root can write to a directory that has all of its "write" permission bits unset. I'll adjust the test to accommodate the possibility that unsetting bits doesn't remove access.

**Comment by insertinterestingnamehere** [comment]
Great, thank you!
