### ISSUE TITLE
DrRacket does not play nicely with dark-themed GTK

### ISSUE THREAD

**Issue by aidalgol** [racket/racket#2140]
The toolbar and bottom statusbar in DrRacket do not change to white-on-black when a dark GTK theme is in use.

(The screenshot shows Racket 6.7, but the appearance is the same with a build of master `96161f6`.)
![drracket-dark](https://user-images.githubusercontent.com/2313201/41504367-9f77b1e0-7240-11e8-8fa9-3545e96d0a82.png)

**Comment by banzr** [comment]
This is still a problem in 7.0. I know others that have the same dark GTK theme.

**Comment by banzr** [comment]
This is filed under racket and should be moved to racket/drracket.

**Comment by rfindler** [comment]
Probably racket/gui, actually.

**Comment by banzr** [comment]
@rfindler, it looks like your the author ofracket/gui. Is that accurate and do you know how to fix it?

**Comment by rfindler** [comment]
I contribute to it, yes. I have not tried to investigate this problem.

**Comment by banzr** [comment]
It looks like racket/gui/gui-lib/framework/gui-utils.rkt has font hardcoded
to Black. Is this the right place?

**Comment by banzr** [comment]
Lines 47 and 51 need to check for dark gtk themes I believe. I'll test now by hard-coding to white

**Comment by banzr** [comment]
No luck. I think I was able to make the border around the editor frame white by making other functions have a value "white" instead of "black" but no workie. I'll talk to Eli about it maybe.

**Comment by Piscium** [comment]
I also came across this issue. There is an easy workaround, see this alias I set, it works:

`alias dra='GTK_THEME=Materia drracket'`

Replace Materia with the name of a light theme that you have installed. Alternatively the .desktop file could be changed.

[https://developer.gnome.org/gtk3/stable/gtk-running.html](url)

**Comment by aidalgol** [comment]
Closing in favour of the equivalent bug on racket/drracket#235, as suggested by @banzr.
