### ISSUE TITLE
`with-handlers` interferes with optimizer source location in warnings

### ISSUE THREAD

**Issue by samth** [racket/racket#2159]
This program has a warning from the optimizer:

```
[samth@huor:~/.../racket-test-extra/tests/future (master) plt] cat /tmp/b.rkt 
#lang racket
(require racket/flonum)

(lambda () (with-handlers ([void void]) (->fl)))
```

```
[samth@huor:~/.../racket-test-extra/tests/future (master) plt] r -W info@optimizer /tmp/b.rkt 
optimizer: warning in: /home/samth/sw/plt/racket/collects/racket/private/more-scheme.rkt:261:28: .../more-scheme.rkt:261:28 in module: module: optimizer detects procedure incorrectly applied to 0 arguments: ->fl
optimizer: warning in: /home/samth/sw/plt/racket/collects/racket/private/more-scheme.rkt:261:28: .../more-scheme.rkt:261:28 in module: module: optimizer detects procedure incorrectly applied to 0 arguments: ->fl
optimizer: warning in: /home/samth/sw/plt/racket/collects/racket/private/more-scheme.rkt:261:28: .../more-scheme.rkt:261:28 in module: module: constant-fold attempt failed: ->fl: arity mismatch;
 the expected number of arguments does not match the given number
  expected: 1
  given: 0
#<procedure:/tmp/b.rkt:4:0>
```

But the source locations point to the source of the `with-handlers` implementation.

**Comment by mflatt** [comment]
In case there's any question of why this happens: The optimizer doesn't track expression source locations — only the locations of enclosing functions. The `with-handlers` form expands to wrap its body in a function, so that's the source location that shows up.

**Comment by samth** [comment]
Should the `with-handler` implementation adjust the source location of that function to point to the macro use?

**Comment by mflatt** [comment]
Although that sounds like it would work ok, I think we want something more automatic. Otherwise, we have to track down every macro that wraps an expression in a function (and remember in the future). I don't have a good idea at the moment, though.

**Comment by samth** [comment]
Well, I fixed it anyway.
