### ISSUE TITLE
syntax-parse: "required attribute not defined" when using state in a pattern-expander

### ISSUE THREAD

**Issue by AlexKnauth** [racket/racket#2164]
When a pattern expander uses mutable state to generate an identifier to insert into the pattern, and this pattern expander is used in a syntax class, it gives this error:
```
pattern: required attribute is not defined: tmp0
```

It seems to be the interaction of all three of these: state, `pattern-expander`, and `define-syntax-class`. When I write the same program but taking out one of these, it works fine.

```racket
#lang racket
(require syntax/parse
         (for-syntax racket/syntax syntax/parse))

(define-syntax ~temporary
  (let ([counter 0])
    (pattern-expander
     (syntax-parser
       [(_)
        #:with tmp (begin0 (format-id #'here "tmp~a" counter)
                           (set! counter (add1 counter)))
        #'tmp]))))

(define-syntax-class my-class
  [pattern {~temporary}])
;pattern: required attribute is not defined: tmp0 in: (pattern (~temporary))
```

P.S. The original version of this used `generate-temporary` instead of a local incrementing counter. I was using a temporary to try to prevent the pattern expander from binding any *externally visible* attributes, while allowing the code it produces to have access to the syntax object it's being matched against.
```racket
(define-syntax ~temporary
  (pattern-expander
   (syntax-parser
     [(_)
      #:with tmp (generate-temporary 'tmp)
      #'tmp])))

(define-syntax-class my-class
  [pattern {~temporary}])
;pattern: required attribute is not defined: tmp2 in: (pattern (~temporary))
```

**Comment by AlexKnauth** [comment]
This might be because `define-syntax-class` copies the patterns *before* expanding them, and so ends up expanding them twice. In the code below, it expands the `rhss` once on line 56, but copies them where they will be expanded a second time on line 74.

It would probably fix this if `define-syntax-class` could expand the `rhss` before copying it to two different places.
<img width="960" alt="stx-class-copies-code" src="https://user-images.githubusercontent.com/6600123/42412426-3f693626-81da-11e8-9ba4-f714d290417f.png">

**Comment by rmculpepper** [comment]
Yes, that sounds right. BTW, the reason for the copying is that attributes must be collected (if there is no `#:attributes` clause, at least) during pass 1 so they can be part of the information statically available to syntax-class references; but other syntax classes might not be available until pass 2 (for forward references).

It also seems reasonable to exclude uninterned (and unreadable) symbols from the list of inferred attributes.
