### ISSUE TITLE
SIGILL during build on NetBSD/macppc

### ISSUE THREAD

**Issue by sevan** [racket/racket#2190]
/usr/bin/make lib-finish
if [ "/var/tmp/pbulk/lang/racket/work/.destdir" = "" ]; then  echo "/usr/pkg/lib";  fi
racket/racket3m -X "/var/tmp/pbulk/lang/racket/work/.destdir/usr/pkg/share/racket/collects" -G "/var/tmp/pbulk/lang/racket/work/.destdir/usr/pkg/etc/racket"   --no-user-path -N "raco" -l- setup --no-user  
raco setup: bootstrapping from source...
 triggered by use of non-".zo" file
  path: /var/tmp/pbulk/lang/racket/work/.destdir/usr/pkg/share/racket/collects/compiler/cm.rkt
...
raco setup:  in <pkgs>/images-lib/images/private/latent-contract
[1]   Illegal instruction (core dumped) racket/racket3m ...

[info from gdb](http://www.netbsd.org/~sevan/pkg-53467.txt)

I've attempted the build with cairo, libjpeg & libpng explicitly built with debug symbols and still the backtrace is not giving any indication of the function. Can anyone shed any light on where the problem lies?

**Comment by mflatt** [comment]
We never tracked down the problem with BC, but Racket CS is now supported for NetBSD/macppc (as of v8.1.0.4).
