### ISSUE TITLE
pattern expanders can't use syntax-protect or syntax-rules

### ISSUE THREAD

**Issue by AlexKnauth** [racket/racket#2199]
Right now, pattern expanders can't use `syntax-protect`, which means they can't use `syntax-rules` either. However, this is not documented anywhere. We should fix this by either:

 1. Documenting the fact that pattern expanders shouldn't use `syntax-arm` or `syntax-protect` on their results (and so shouldn't use `syntax-rules` either).
 2. Changing syntax-parse so that it can disarm the "core" pattern forms, making `syntax-protect` okay in pattern expanders, and so making `syntax-rules` okay too.

See also #2197.

**Comment by lexi-lambda** [comment]
Was this issue introduced by the change to use `local-apply-transformer` to implement pattern expanders (#2082), or was it already a problem in Racket 6.12? If the former, is this related to the syntax protection hole @rmculpepper [mentioned being closed](https://github.com/racket/racket/pull/2082#issuecomment-390158646) by that change, or is it a distinct problem? (I haven’t really looked into the problem or thought very much about why it might be an issue, so I could probably answer these questions myself, but it seems likely you’ve already thought about it.)

**Comment by AlexKnauth** [comment]
No, it was already a problem in 6.12, and even in 6.1.1 when pattern-expanders were first put in.

**Comment by sorawee** [comment]
Per discussion at #1133, (1) would be the way to go I think?

**Comment by AlexKnauth** [comment]
Yes.

**Comment by sorawee** [comment]
`syntax-protect` is now deprecated since Racket 8.3. `syntax-rules` now works fine.

```
#lang racket

(require (for-syntax syntax/parse)
         (for-meta 2 racket/base))

(begin-for-syntax
  (define-syntax ~maybe
    (pattern-expander
     (syntax-rules ()
       [(~maybe pat ...)
        (~optional (~seq pat ...))]))))

(define-syntax (test stx)
  (syntax-parse stx
    [(_ (~maybe #:type x) #:id y)
     (if (attribute x)
         #''(x y)
         #''y)]))

(test #:type a #:id b)
(test #:id b)
```

So let's close the issue.
