### ISSUE TITLE
racketcs hitting tab causes malloc to complain

### ISSUE THREAD

**Issue by tgbugs** [racket/racket#2207]
```
racket/racket/src/build/cs $ ./racketcs 
Welcome to Racket v7.0.0.10 [cs]
> (+ 7 10)
17
> ; malloc: mulitple mode arguments
;   first: #f
;   second: 'raw
; [,bt for context]
; user break [,bt for context]
^C; user break [,bt for context]
^C; user break [,bt for context]
^Z
[1]+  Stopped                 racketcs
```
When running racketcs from a fresh compile on linux if at any point you hit tab the above message appears and the the terminal will print the above, but will not accept any further input, backgrounding with `C-z` and killing the process is required.

**Comment by mflatt** [comment]
Thanks for the report!
