### ISSUE TITLE
Description of `or` pattern for racket/match seems wrong or at least misleading

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#2213]
The `or` pattern for `match` is documented as follows:

> `(or pat ...)` — matches if any of the `pat`s match. **Beware**: the result expression can be duplicated once for each `pat`! Identifiers in `pat` are bound only in the corresponding copy of the result expression; in a module context, if the result expression refers to a binding, then all `pat`s must include the binding.

While not explicitly stated, this seems to imply that it’s okay for each `pat` to bind a different set of variables, so long as the variables are not referenced. However, this clearly isn’t actually true, since the following program produces a syntax error:

```racket
(match #f
  [(or a b)
   #f])
```

I think the documentation should be improved to explicitly state that each `pat` *must* bind the same set of variables, but I’m not confident enough that reflects the actual behavior in all situations to make the change myself.

**Comment by samth** [comment]
That is the actual restriction, but if you don't make the change then I will.
