### ISSUE TITLE
make cstartup, racketcgc SIGSEGV on OpenBSD/i386 -current

### ISSUE THREAD

**Issue by juanfra684** [racket/racket#2214]
I'm trying to build Racket 7.0 and the latest Racket snapshot (utah) on OpenBSD i386 -current.
```
ranlib libracket.a
make racketcgc
cc -I. -I/usr/ports/pobj/racket-minimal-7.0.0.10/racket-7.0.0.10/src/racket/include -O2 -pipe   -msse -msse2 -mfpmath=sse     -msse -msse2 -mfpmath=sse -pthread -I/usr/local/include  -DUSE_SENORA_GC  -DINITIAL_COLLECTS_DIRECTORY='"'"`cd /usr/ports/pobj/racket-minimal-7.0.0.10/racket-7.0.0.10/src/racket/../../collects; pwd`"'"' -DINITIAL_CONFIG_DIRECTORY='"'"`cd /usr/ports/pobj/racket-minimal-7.0.0.10/racket-7.0.0.10/src/racket/../..; pwd`/etc"'"' -c /usr/ports/pobj/racket-minimal-7.0.0.10/racket-7.0.0.10/src/racket/main.c -o main.o
cc -o racketcgc main.o  libracket.a libmzgc.a ../rktio/librktio.a -L/usr/local/lib -L/usr/X11R6/lib -pthread -lm  -Wl,--export-dynamic -L/usr/local/lib -lffi
libracket.a(error.o): In function `sch_vsprintf':
error.c:(.text+0x7e8): warning: sprintf() is often misused, please use snprintf()
libracket.a(numstr.o): In function `number_to_allocated_string':
numstr.c:(.text+0x56e3): warning: strcpy() is almost always misused, please use strlcpy()
make cstartup
make cstartup_`./racketcgc -cu /usr/ports/pobj/racket-minimal-7.0.0.10/racket-7.0.0.10/src/racket/src/startup-select.rkt`
SIGSEGV at 0x163aaffd
Abort trap (core dumped)
echo "Bad startup choice, probably an error running startup-select.rkt"
Bad startup choice, probably an error running startup-select.rkt
exit 1
*** Error 1 in racket (Makefile:339 'cstartup_')
*** Error 1 in racket (Makefile:326 'cstartup')
*** Error 1 in racket (Makefile:102 'cgc-core')
*** Error 1 in racket (Makefile:94 'cgc')
*** Error 1 in racket (Makefile:108 '3m')
```
Racket builds fine on amd64 but fails on i386 with a segfault. Racket 6.x built fine on both. The kernel dmesg doesn't show any W^X problem.

**Comment by mflatt** [comment]
It looks like the new W^X workaround doesn't work on i386 because, when an attempt to call into a non-executable page triggers a SIGSEGV, the `si_addr` field of the `siginfo_t` record contains an unhelpful address. It appears to be the address that tried to perform a call, instead of the address that is the target of the call.

I see no simple way to get the target of the call. The solution is probably to not define `IMPLEMENT_WRITE_XOR_EXECUTE_BY_SIGNAL_HANDLER` for i386, and instead go back to relying on a configuration that allows W^X when building on i386.

Do other platforms have a similar problem, or is it just i386?

**Comment by juanfra684** [comment]
Yes, on macppc doesn't build:
```
cd src; make all
make mzobjects
cc -O2 -pipe   -O0 -Wall -Wno-unused-value    -I./.. -I/usr/ports/pobj/racket-minimal-7.0/racket-7.0/src/racket/src/../include  -I/usr/ports/pobj/racket-minimal-7.0/racket-7.0/src/racket/src/../../rktio -I../../rktio -O0 -Wall -Wno-unused-value -pthread -I/usr/local/include  -DUSE_SENORA_GC  -c /usr/ports/pobj/racket-minimal-7.0/racket-7.0/src/racket/src/startup.c -I.. -I/usr/ports/pobj/racket-minimal-7.0/racket-7.0/src/racket/src -o startup.o
make libracket.a
/usr/ports/pobj/racket-minimal-7.0/racket-7.0/src/racket/../utils/nicear ar ruv libracket.a src/*.o ../foreign/foreign.o
r - src/startup.o
ranlib libracket.a
make racketcgc
cc -o racketcgc main.o  libracket.a libmzgc.a ../rktio/librktio.a -L/usr/local/lib -L/usr/X11R6/lib -pthread -lm  -Wl,--export-dynamic -L/usr/local/lib -lffi
libracket.a(error.o): In function `sch_vsprintf':
error.c:(.text+0x12cc): warning: sprintf() is often misused, please use snprintf()
libracket.a(error.o): In function `make_arity_expect_string':
error.c:(.text+0x4bf8): warning: strcpy() is almost always misused, please use strlcpy()
make mzcomcgc
:
make sysinfercgc
./racketcgc -cqu /usr/ports/pobj/racket-minimal-7.0/racket-7.0/src/racket/mksystem.rkt system.rktd "cc -E -I. -I/usr/ports/pobj/racket-minimal-7.0/racket-7.0/src/racket/include -I/usr/ports/pobj/racket-minimal-7.0/racket-7.0/src/racket/src -O0 -Wall -Wno-unused-value -pthread -I/usr/local/include  -DUSE_SENORA_GC    /usr/ports/pobj/racket-minimal-7.0/racket-7.0/src/racket/src/systype.c" "" "./racketcgc" "./racketcgc"
make cstartup
make cstartup_`./racketcgc -cu /usr/ports/pobj/racket-minimal-7.0/racket-7.0/src/racket/src/startup-select.rkt`
./racketcgc -cu /usr/ports/pobj/racket-minimal-7.0/racket-7.0/src/racket/src/compile-startup.rkt cstartup.inc cstartup.zo /usr/ports/pobj/racket-minimal-7.0/racket-7.0/src/racket/src/startup.inc /usr/ports/pobj/racket-minimal-7.0/racket-7.0/src/racket/src/schvers.h
cd gc2; make all
mkdir xsrc
make check-sdep
../racketcgc  -cqu /usr/ports/pobj/racket-minimal-7.0/racket-7.0/src/racket/gc2/check-sdep.rkt
*** Signal SIGABRT in racket/gc2 (Makefile:203 'check-sdep')
*** Error 1 in racket/gc2 (Makefile:177 'all')
*** Error 1 in racket (Makefile:110 '3m')
*** Error 1 in . (Makefile:58 '3m')
*** Error 1 in /usr/ports/pobj/racket-minimal-7.0/build-powerpc (Makefile:51 'all')
*** Error 1 in . (/usr/ports/infrastructure/mk/bsd.port.mk:2722 '/usr/ports/pobj/racket-minimal-7.0/build-powerpc/.build_done')
*** Error 1 in . (/usr/ports/infrastructure/mk/bsd.port.mk:1958 '/usr/ports/packages/powerpc/all/racket-minimal-7.0.tgz')
*** Error 1 in . (/usr/ports/infrastructure/mk/bsd.port.mk:1956 '/usr/ports/packages/powerpc/all/racket-minimal-7.0.tgz')
*** Error 1 in . (/usr/ports/infrastructure/mk/bsd.port.mk:2422 '_internal-package')
*** Error 1 in /usr/ports/lang/racket-minimal (/usr/ports/infrastructure/mk/bsd.port.mk:2401 'package')
```
I can't test on more platforms right now but I will just disable the handler for everything except amd64.

**Comment by juanfra684** [comment]
@mflatt quick question. In the platforms without JIT support, does racket uses the same signal handler with the workaround for W^X?. On arm64 looks like Racket builds without problems.

**Comment by mflatt** [comment]
No, it's use only for the JIT. The only other code generation is in libffi, which has it's own workaround.

(Adopting the libffi approach for Racket's JIT is a little painful, but maybe we should do that eventually.)

**Comment by DexterLagan** [comment]
Same error on 6.4 i386, Racket 7.1 with bins. Any solution? Shall I upgrade my old Thinkpad T60? Cheers!

**Comment by juanfra684** [comment]
@DexterLagan how are you installing Racket?. If you're building Racket outside of the OpenBSD port, you will need to use `-Wl,-z,wxneeded` as LDFLAGS and a partition mounted with `wxallowed`.

**Comment by DexterLagan** [comment]
Hi there I was able to build 7.0 it from ports by adding wxallowed in fstab. However I received the same error as described trying to build it from source. I’ll give it another try with the options you mentioned. 

  I installed drracket on 7.0 using raco but now I’m getting an out of memory error when building binaries from inside drracket. Building with raco works fine.

Cheers!

**Comment by juanfra684** [comment]
If Racket 7.0 is enough for you, there is a official package for 6.4. Install it with `pkg_add racket-minimal`. Delete the `.racket` directory from your home and read the instructions in `/usr/local/share/doc/pkg-readmes`. The document explains how to install additional raco packages.

Your problem with DrRacket is probably due to the limited datasize allowed for your user.  Try increasing the value with `ulimit -d 1000000` or something bigger. If you're building from source in your home directory, this partition will need also `wxallowed`.

**Comment by DexterLagan** [comment]
7.0 built just fine from the ports. I will try to increase the data size. I wasn’t aware there was such limit. Thank you so much for your help. Have a great day!

**Comment by DexterLagan** [comment]
I checked ulimit and it was set to unlimited. I only have 1gb of ram in this old system (thinkpad T60). I’m using it specifically to test compilers performance. I believe DrRacket is just too heavy for this system with Xfce. I’ll probably try a lighter wm or use raco to compile. Thanks again for your help, I learned quite a bit too.

**Comment by juanfra684** [comment]
You didn't use the right switch for `ulimit`. It's always 512MB for the datasize on i386 by default. You can see the options in https://man.openbsd.org/ksh#ulimit.

If you want to compare the performance of different compilers, don't use DrRacket. It has some additional options enabled which could slow down your code. Test always from the command line.

**Comment by DexterLagan** [comment]
I see. I’ll check the man page and try again. Thanks!
