### ISSUE TITLE
Version requirements? / CoreGraphics

### ISSUE THREAD

**Issue by bkovitz** [racket/racket#2215]
Running `drracket` or `gracket` from Racket v7.0 on OSX 10.7.5, I get this error:

    ffi-lib:` couldn't open "/System/Library/Frameworks/CoreGraphics.framework/CoreGraphics.dylib" (dlopen(/System/Library/Frameworks/CoreGraphics.framework/CoreGraphics.dylib, 6): image not found)

I figure the problem is just that I'm running on an old OS. Apple added CoreGraphics in OSX 10.8.

I couldn't find documentation on which OS versions each version of Racket requires. Is there any? If not, would it be possible to put it on a page such as https://download.racket-lang.org/all-versions.html ?

Alternatively, _is_ there a way to run Racket v7.0 under this old OS? Can I configure or rebuild it so it doesn't depend on CoreGraphics?

**Comment by mflatt** [comment]
Racket is meant to run on Mac OS X 10.6 and up (for a 64-bit build, or 10.5 for a 32-bit build). But I forgot to actually check v7.0 on older version of the OS. Version 7.0 introduced a problem change that targets Mac OS 10.13 and up, so it can be disabled for 10.7.

You should be able to make things run on OS X 10.7 by modifying the following files:

 * "share/pkgs/gui-lib/mred/private/wx/cocoa/utils.rkt" line 41, change to
```
(define cg-lib (ffi-lib (format "/System/Library/Frameworks/CoreGraphics.framework/CoreGraphics") #:fail (lambda () #f)))
```
 * "share/pkgs/gui-lib/mred/private/wx/cocoa/queue.rkt", change the two uses of `define-cg` to add `#:fail (lambda () #f)`.

**Comment by bkovitz** [comment]
Thanks, mflatt! It worked the first time.

Wow: Apple no longer supports this laptop (made in 2009) but Racket does.

**Comment by mflatt** [comment]
Patch applied in racket/gui@a2bed21f1aee48f872b4ec04265e2629e1bd6f68
