### ISSUE TITLE
bootstrappability

### ISSUE THREAD

**Issue by rain-1** [racket/racket#2218]
Hello!

I wanted to make an issue about building racket scheme from source code only. (Without having a pre-built racket scheme already to bootstrap off).

I think currently the only obstruction to this is the inc file: https://raw.githubusercontent.com/racket/racket/master/racket/src/racket/src/startup.inc

But when racket moves to racket on chez will this become harder? because chez scheme needs chez scheme binary .boot files to build. Will this be an issue and introduce a "vicious cycle" or not?

**Comment by mflatt** [comment]
I don't see "startup.inc" as being inherently bootstrapped. The code is readable, if awkwardly formatted, and you can modify it directly to fix a bug and escape a vicious cycle. (I've had to do that before.) There's nothing hidden to make it untrustworthy.

Racket-on-Chez is a bigger issue. The current plan is to build enough of a Chez Scheme compatibility layer on Racket that it can run the Chez Scheme compiler on itself.

**Comment by rain-1** [comment]
https://github.com/racket/racket/commit/e337c65204402ef4faf09f6a848d2d873d0e63a7

**Comment by mflatt** [comment]
The build process for Racket CS now uses (a freshly built) traditional Racket to build initial boot files for Chez Scheme, so I think this issue is now address.

**Comment by rain-1** [comment]
Fantastic, thank you for doing that.
