### ISSUE TITLE
inexact->exact gives wrong answer for some single-flonums

### ISSUE THREAD

**Issue by billzorn** [racket/racket#2223]
The following should probably round-trip (at least in value) rather than returning a completely different number:
```
$ racket
Welcome to Racket v7.0.
> (define f 5.844367f-39)
> f
5.844367f-39
> (define x (inexact->exact f))
> x
521335/21267647932558653966460912964485513216
> (exact->inexact x)
2.451305389543749e-32
> 
```
exact->inexact seems to be correct here, the problem is that inexact->exact is returning the wrong answer. 5.855367e-39 is exactly 521335/89202980794122492566142873090593446023921664, so the denominator as reported is off by a factor of 2^22.

After a bit of poking, this seems to be an issue with subnormals - the largest subnormal suffers from the bug, but the smallest normal float32 does not:
```
$ racket
Welcome to Racket v7.0.
> (exact->inexact (inexact->exact 1.1754942f-38))
4.9303800698841484e-32
> (exact->inexact (inexact->exact 1.1754944f-38))
1.1754943508222875e-38
>
```
The bug does not seem to manifest for double-flonums.

I'm running Ubuntu 16.04 on an intel system, with Racket 7.0 installed.

**Comment by mflatt** [comment]
Thanks very much for the report! It's amazing that this was broken and unnoticed for so long — I guess because few Racket programs use single-precision floating point.
