### ISSUE TITLE
raco exe fails on output of raco demod

### ISSUE THREAD

**Issue by rmculpepper** [racket/racket#2226]
Running `raco exe` on a .zo file produced by `raco demod` now raises an internal error. It worked in Racket 6.12.

Save the following program as "hello.rkt"

    #lang racket/base
    (displayln "Hello World!")

Run `raco demod hello.rkt` and then `raco exe -o hello hello_rkt_merged.zo`. The second command fails with the following error:

    hash-ref: no value found for key
      key: 'name
      context...:
       /opt/racket-7.0/collects/compiler/embed.rkt:421:0: get-code
       /opt/racket-7.0/collects/racket/private/map.rkt:267:2: gen-for-each
       /opt/racket-7.0/collects/compiler/embed.rkt:1115:0: do-write-module-bundle
       /opt/racket-7.0/collects/compiler/embed.rkt:1708:33
       /opt/racket-7.0/collects/compiler/private/elf.rkt:285:0: expand-elf26
       /opt/racket-7.0/collects/compiler/../racket/private/more-scheme.rkt:261:28
       "/opt/racket-7.0/share/pkgs/compiler-lib/compiler/commands/exe.rkt": [running body]
       for-loop
       run-module-instance!125
       "/opt/racket-7.0/collects/raco/raco.rkt": [running body]
       for-loop
       run-module-instance!125
       "/opt/racket-7.0/collects/raco/main.rkt": [running body]
       for-loop
       run-module-instance!125
       perform-require!78

Original report here: https://stackoverflow.com/questions/43307580/can-executable-size-be-optimized

**Comment by logc** [comment]
Commenting here so that this issue is easier to find: using `raco demod` before using `raco exe` is a way to reduce the total size of the produced executable.

Thanks for fixing this!

**Comment by lewisl** [comment]
Why was this closed?  It certainly has not been fixed.  Or perhaps reducing from 58mb to 50mb is considered fixed?  Gambit does this in 6mb, which is still too big for a 2 line program.

**Comment by sorawee** [comment]
The fix is about making it not crash, not about how effective size reducing is.

I don't know enough about Gambit, but size reducing is difficult for Racket in general because users can use `eval`, so the runtime needs to include a lot of things.
