### ISSUE TITLE
Weird behavior of popup menus in some stuffs on Linux

### ISSUE THREAD

**Issue by yjqww6** [racket/racket#2249]
DrRacket editors (and other editors use the defaulted current-text-keymap-initializer) popup menus when the right button is released and it works fine, but I found for other stuffs which popup menu when pressed (for example, the snip from "Insert Fraction", Macro Stepper, ...),  the menu immediately disappears when I release the button (on Ubuntu).

As a comparison, on Mac OS, If I release the button quickly enough, the menu still remains open.

I could still use the menu by holding down the button, but it is inconvenient with touchpad only.

**Comment by rfindler** [comment]
This may be because the initial x/y coordinates are the ones in the mouse record, instead of x+1/y+1?

**Comment by yjqww6** [comment]
I found the gui debugger and number-snip% use +1, but they have the same problem.

**Comment by mflatt** [comment]
The difference is that the edit menu is triggered by a mouse-up event, while other others are triggered on mouse-down events. But the underlying problem is related to managing the timestamp on events, and I'll push a repair for that.
