### ISSUE TITLE
Macro Stepper Internal Error

### ISSUE THREAD

**Issue by yjqww6** [racket/racket#2251]
The program is here: https://gist.github.com/yjqww6/5c44fff17ca96542a9384897cb38ed7c .

Open it with DrRacket and Macro Stepper, I get this error.

<img width="608" alt="default" src="https://user-images.githubusercontent.com/6269269/45089660-780d6580-b13f-11e8-84b6-602ff072ec2e.png">

I use Racket 7.0.

**Comment by sorawee** [comment]
@yjqww6 I cannot reproduce the problem anymore in Racket 7.6. Could you confirm that it's fixed?

**Comment by yjqww6** [comment]
@sorawee cannot reproduce it too.
