### ISSUE TITLE
Expansion contexts for module

### ISSUE THREAD

**Issue by LiberalArtist** [racket/racket#2253]
In the Racket Reference § [1.2.3.3 Expansion Context](http://docs.racket-lang.org/reference/syntax-model.html#(part._expand-context-model)), the prose currently says, "For example, a `module` form is allowed only in a _top-level context,_ and it fails in other contexts."

I think this is wrong given the existence of submodules, so that (unless I misunderstand something) `module` is also allowed in a "module context." 

If I'm right that this is incorrect, I've come across a few other things that also need updates:
- The error message for 
  ```racket
  (module example racket
    (let ()
      (module main racket)))
  ``` 
  says "module: allowed only at the top level"
- The actual [documentation](http://docs.racket-lang.org/reference/module.html#(form._((quote._~23~25kernel)._module))) for the `module` form doesn't say anything at all about the expansion contexts in which it is legal.

**Comment by iitalics** [comment]
Yes, I think you're right -- `module` forms are allowed in any "module context", not just any "top-level context".

To continue to pull things apart, I was under the impression that "top-level" was associated _only_ with the REPL. For instance take the following code:
```racket
#lang racket
(provide foo)
(define-syntax (foo stx)
  #`'#,(syntax-local-context))
(foo)
```

Then if we experiment with it:
```
$ racket foo.rkt
'module
$ racket -it foo.rkt
Welcome to Racket v7.0.0.7.
'module
> (foo)
'top-level
>
```

The documentation may still be _technical right_ given the fact that the contents of any file with a `#lang` is always implicitly within a module-begin, so the only way to not be in a module is to be at the REPL. However this is unclear from this section of the docs alone.
