### ISSUE TITLE
Compiling with Visual Studio 2017

### ISSUE THREAD

**Issue by gus-massa** [racket/racket#2259]
I got a new computer with Windows 10. I tried to install Visual Studio 2015 but I got many error, probably because I had to install some additional packages and some libraries like the UCRT, but VS2015 doesn't detect the current UCRT version. I tried installing a few more things without success.

I finally gave up and I installed Visual Studio 2017, and after failing and adding every optional package that looks barely related I could compile Racket without problems with VS2007. I'm not 100% sure that everything works, but I tried some of the builtin test and they are ok and I didn't found any problem so far.

My question is why the INSTALL.txt file says that Racket must be compiled with the version 2008-2015 of Visual Studio (see line [67-68](https://github.com/racket/racket/blob/master/INSTALL.txt#L67))? 

My guess is that nobody updated that line. If not, it would be nice to fix the problems so it's possible to use VS2017, because it's impossible to install VS2015 (in a weekend).

PS: What version of Visual Studio is AppVeyor using in the test?

**Comment by mflatt** [comment]
You're right – I forgot to update "INSTALL.txt" when adding VS 2017 support in early August. I'll do that now.

The AppVeyor tests currently use VS 2013, as specified in "appveyor.yaml" (where 12.0 = VS 2013).

**Comment by gus-massa** [comment]
Since this is fixed, I'm closing the issue.
