### ISSUE TITLE
`hash-ref` bug

### ISSUE THREAD

**Issue by DavidThien** [racket/racket#2263]
I have been running into issues with `hash-ref` (possibly memory related?) I have a set of data structures called posits which I am importing from the `softposit-rkt` library (this library is a set of ffi bindings). I am then generating 256 of them with random values and inserting them as keys into a hash table. Later on, I try to look up the same keys, but get a `hash-ref: no value found for key` error. However, if I call `hash-keys` or `hash->list`, then the keys show up in the output lists. I have confirmed that the hash table is comparing using `equal?` by checking with `hash-equal?`, and have done a test in the repl that verifies the keys can be compared using `equal?`.

Unfortunately, I haven't been able to minimize this error into a few lines of code because I have been running into major problems doing so. I first started by creating a test file which directly calls the function which sets up and then references the hash-table, which I was able to get to reproduce the error. However, I then started removing unneeded definitions from `require`ed files and got to the point where if I removed one definition that was no longer called or referenced anywhere in any file in the project (after I started removing definitions), `hash-ref` started working again. When I try to start moving definitions to another file that minimizes the bug, then it also starts working.

As such, I haven't been able to get a small example that demonstrates the problem, but I do have steps to reproduce it in the repo I am working on.

Clone into the Herbie repo and checkout to the posits branch
`git clone https://github.com/uwplse/herbie.git`
`git checkout remotes/origin/posits`
The `softposit-rkt` package must also be installed with
`raco pkg install softposit-rkt` (note the `softposit-rkt` library currently only works on linux)
From there, the bug can be demonstrated with `racket src/test.rkt`

The output you see should be something like

```
"Warning, posits don't currently support preconditions."
"Ignoring for now."
(#<cpointer:posit16>) -> #s(point-rec 1 (#<alt (λ (x) (-.p16 (sqrt.p16 (+.p16 x (real->posit16 1.0))) (sqrt.p16 x)))>))
(#<cpointer:posit16>) -> #s(point-rec 1 (#<alt (λ (x) (-.p16 (sqrt.p16 (+.p16 x (real->posit16 1.0))) (sqrt.p16 x)))>))
OK!
assert: (hash-has-key? point->alt k1) returned false!
  context...:
   /herbie/src/core/alt-table.rkt:149:6: for-loop
   /herbie/src/core/alt-table.rkt:141:16: for-loop
   /herbie/src/core/alt-table.rkt:130:0: best-and-tied-at-points
   /herbie/src/core/alt-table.rkt:234:0: atab-add-altn
   /herbie/src/core/alt-table.rkt:52:2: for-loop
   /usr/share/racket/collects/racket/contract/private/arrow-val-first.rkt:388:18
   /herbie/src/mainloop.rkt:287:0: run-improve43
   "/herbie/src/test.rkt": [running body]
   for-loop
   run-module-instance!125
   perform-require!78
```

The important lines are the `(#<cpointer:posit16>) -> ...` which shows the keys that we can properly look up in the hash table (which should have 256 entries) and the failing assert where we loop over the keys form the hash table asserting that each of the keys can be looked up in the hash table with `hash-has-key?`.

For an explanation of what the code is doing:

First looking at `src/test.rkt`, this just calls `run-improve` passing in a program, the number of iterations to run herbie on, and the precondition (these aren't important for the bug), as well as the precision `posit16` which indicates we should be using the posit bindings from `softposit-rkt`.

`run-improve` is in `src/mainloop.rkt` which calls `setup-prog!`. `setup-prog!` generates the `posit16`s which are to be used as the keys in our hash-table (really a list of `((posit16) exact-value)` where `exact-value` isn't important for the bug). We then assign this generated "context" to a parameter `*pcontext*` and pass it into `make-alt-table` which makes the hash table we are getting the bug with.

`make-alt-table` is in `src/core/alt-table.rkt` which generates a struct `alt-table` where the important field is `point->alts` (the first field of `alt-table`). We make the hash table with `make-hash` which loops over the points in the context we passed in, importantly assigning the first value (a `(posit16)`) as the keys. 

Moving back to `src/mainloop.rkt` in `setup-prog!`, we can see that we assign the result of `make-alt-table` to another parameter `^table^`. `setup-prog!` then returns to `run-improve` which prints some debug info to a log, eventually getting to "[Phase 2 of 3] Improving". None of the code between `setup-prog!` and the "Improving" phase do anything to the alt-table, and in the past I have successfully removed those lines without changing the behavior of the failing `hash-ref`. The improving phase calls `atab-add-altns` passing in `(^table^)` which was previously assigned the result of `make-alt-table`. `atab-add-altns` is again located in `src/core/alt-table.rkt`.

`atab-add-altns just loops over the `atab` and `altns` which we pass in, calling `atab-add-altn` with each of them. `atab-add-altn` gets the `pnts->alts` field from the table that we passed in, and then calls `best-and-tied-at-points` on it. This is where the bug shows up.

You can see in the first lines of `best-and-tied-at-points` we define `a` which is the list of points in `(*pcontext*)`, which is the list of `posit16`s we had previously generated. There are then 2 commented out lines which you can uncomment to see that the values of theses `posit16`s generated from `(*pcontext*)` and the keys of `hash->list` are the same. Next, we check various properties of the hash-table, eventually failing on the assert looping over `hash-keys point->alt`. Previously the program would fail on the line
`(let* ([pnt-rec (hash-ref point->alt pnt)]`
because the `hash-ref` couldn't find the key in the table. Notice that `pnt` is gotten from `(*pcontext*)`, which does indeed contain the keys of this table.

So there's the bug, sorry again that I wasn't able to minimize, but I was having all sorts of weird behavior when moving and/or removing definitions (which in combination with the ffi bindings makes me suspect it's a memory bug). If you have any questions or suggestions on how I can try to minimize this further, please tell me and I'll respond as quick as I can.

Thanks!

**Comment by samth** [comment]
I successfully reproduced this behavior (on linux) with herbie f4bdc744, softposit-rkt 077bb8501, racket aad98e563d1.

**Comment by rmculpepper** [comment]
I think the problem is in the default implementation of `equal-hash-code` for cstructs. IIUC it takes the hash code of the underlying pointer, which probably involves interpreting the pointer as an integer. But the default allocation mode for cstructs is `'atomic`, which means the pointers can be *moved* by the GC. So effectively the keys have mutable hash-codes, with the usual consequences.

Here's a short program that (I think) demonstrates the problem:

    #lang racket
    (require ffi/unsafe)

    (define-cstruct _intwrapper ([v _uint32]))
    (define ht (make-hash))

    (for ([i (in-range #e1e3)])
      (define iw (make-intwrapper (random #e1e6)))
      (when (zero? (random 5))
        (hash-set! ht iw (intwrapper-v iw))))

    (collect-garbage) ;; invite the GC to move intwrapper objects around
    (for ([key (in-list (hash-keys ht))])
      (hash-ref ht key))

When I run this, I consistently get a "hash-ref: no value found for key" error.

One workaround would be to change the relevant cstruct definitions to use `#:malloc-mode 'atomic-interior`, which prevents the objects from being moved.

**Comment by DavidThien** [comment]
That was the issue! Thanks so much!

**Comment by lexi-lambda** [comment]
The `equal-hash-code` implementation bug for cstructs that @rmculpepper points out seems worth opening another issue for, right? Or am I misunderstanding what you’re saying, Ryan?
