### ISSUE TITLE
`make cs` fails when `softpostit-rkt` is installed

### ISSUE THREAD

**Issue by samth** [racket/racket#2267]
Error message:

```
raco setup: --- installing foreign libraries ---
raco setup: installing: foreign library <lib>/libsoftposit.so
copy-directory/files: encountered path that is neither file nor directory
  path: /home/samth/sw/plt/racket/share/pkgs/softposit-rkt/libsoftposit.so
  context...:
   /home/samth/sw/plt/racket/collects/racket/file.rkt:94:2: loop
   /home/samth/sw/plt/racket/collects/setup/setup-core.rkt:1749:30: copy-lib
   /home/samth/sw/plt/racket/collects/setup/setup-core.rkt:1780:30: for-loop
   /home/samth/sw/plt/racket/collects/setup/setup-core.rkt:178:50
   /home/samth/sw/plt/racket/collects/setup/setup-core.rkt:1726:6: for-loop
   /home/samth/sw/plt/racket/collects/setup/setup-core.rkt:1722:4: make-libs-step
   /home/samth/sw/plt/racket/collects/setup/setup-core.rkt:71:0: setup-core
   "/home/samth/sw/plt/racket/collects/setup/main.rkt": [running body]
   temp37_0
   for-loop
   run-module-instance!125
   "/home/samth/sw/plt/racket/collects/raco/main.rkt": [running body]
   temp37_0
   for-loop
   run-module-instance!125
   perform-require!78
```

**Comment by mflatt** [comment]
The package seems not to exist anymore, so I'm not sure what the issue was. Closing as "unexplained", but maybe @samth will reopen if there was a specific issue we can address.

**Comment by samth** [comment]
The code is still here: https://github.com/DavidThien/softposit-rkt/.

**Comment by mflatt** [comment]
I see that the package's `info.rkt` says to install "libsoftposit.so", which doesn't exist. Maybe the intent is that a user builds the shared library, first.

In any case, although the error is reported, a `make` or `raco setup` continues. Maybe things were different in the original report so that setup stopped instead of continuing?

**Comment by samth** [comment]
I think what happened was that installing `softposit-rkt` succeeded, but then if I re-ran `make cs` (which implies `raco pkg update -a` and `raco setup`) it failed. I think it would have been at this commit: https://github.com/DavidThien/softposit-rkt/commit/6a9e0ee39dad2483c027eaa85a9d139a7d2877cf

I'll try to replicate this.
