### ISSUE TITLE
class/c contracts do not preserve equal?

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#2279]
This program produces `#f`:

```racket
#lang racket

(define foo%
  (class object%
    (super-new)))

(define/contract foo%-contracted (class/c) foo%)

(equal? foo% foo%-contracted)
```

**Comment by rfindler** [comment]
This is a long-known flaw in class/c, namely that it doesn't use chaperones. It seems like it requires a lot of work to fix and I've been putting it off for ages :(

**Comment by lexi-lambda** [comment]
As a short-term quick fix, couldn’t the `class` struct just define `prop:equal+hash` and implement it such that it inspects the `orig-class` field to implement equality?

**Comment by rfindler** [comment]
That sounds reasonable!
