### ISSUE TITLE
Missing definition of RACKET_CONFIGURE_ARGS

### ISSUE THREAD

**Issue by pmatos** [racket/racket#2282]
@samth I think this was merged, but we are missing the matrix definition of RACKET_CONFIGURE_ARGS, right? There's a reference to them but they are not defined anywhere.

https://github.com/racket/racket/blob/49d31414b768910e83b74b349a252c18da691486/azure-pipelines.yml#L16

**Comment by samth** [comment]
Yes, I think it should be the same as for Travis.

**Comment by pmatos** [comment]
We are about to replace this - so I will leave it for now and re-assign it to me so I remember to close it once we remove azure pipelines support.

**Comment by pmatos** [comment]
Azure Pipelines have been removed, this can be closed.
