### ISSUE TITLE
null pointer passed as source argument of memcpy 

### ISSUE THREAD

**Issue by pmatos** [racket/racket#2283]
Null pointer is being passed in this line as source of memcpy.

https://github.com/racket/racket/blob/49d31414b768910e83b74b349a252c18da691486/racket/src/racket/src/startup-glue.inc#L155

To see it in action, compile racket with `--enable-cify --enable-ubsan` and run a `raco exe`.
You'll see a line like this:
```
../../../racket/gc2/../src/../src/startup-glue.inc:155:3: runtime error: null pointer passed as argument 2, which is declared to never be null
```

So, I have only looked at the code for about 10 mins but this function is suspicious.
```
 /* stash before allocation: */
  p = scheme_current_thread;
  p->ku.k.p1 = (void *)proc;
  p->ku.k.i1 = argc;
  p->ku.k.i2 = runstack_space;
  p->ku.k.p2 = (void *)argv;
  
  argv2 = MALLOC_N(Scheme_Object*, argc);

  p = scheme_current_thread;
  argv = (Scheme_Object **)p->ku.k.p2;
  
  memcpy(argv2, argv, sizeof(Scheme_Object *) * argc);
```

Starts by assigning `scheme_current_thread` to `p`, assigns some values to `p` and then goes on to reassign `scheme_current_thread` to `p` (why?). I think `p->ku.k.p2` which is assigned to `argv` and passed as argument 2 to `memcpy` can be traced back to `(void *) argv`, which can clearly be NULL.

**Comment by mflatt** [comment]
This C code doesn't cooperate with GC, which can be triggered anytime memory is allocated in Racket. So, `p` needs to be refreshed from `scheme_current_thread`, just in case of a GC, since the GC knows to update `scheme_current_thread` but not `p`. More generally, that's why pointer values are saved in the thread record and then restored after allocation.

**Comment by pmatos** [comment]
I have replied to you on the PR page #2284
