### ISSUE TITLE
Unused value in regexp.c

### ISSUE THREAD

**Issue by pmatos** [racket/racket#2290]
I am not sure here if I am looking at simply a mistake in the code and we can remove the line or a bug.

On this line we set `did_alt`, but a few lines later
https://github.com/racket/racket/blob/bc3777792d835b8e3ad5140159032aacf9079a90/racket/src/racket/src/regexp.c#L4418

here:
https://github.com/racket/racket/blob/bc3777792d835b8e3ad5140159032aacf9079a90/racket/src/racket/src/regexp.c#L4425

we set it to something else. There are no jumps to or from this region, no cycles, nothing that uses `did_alt`.

**Comment by pmatos** [comment]
According to github this code was last touched by @elibarzilay 14 years ago! :)

**Comment by elibarzilay** [comment]
@pmatos 14 years ago was the time I migrated the code from cvs to svn, so it means that it's ancient code from before organized history...

**Comment by samth** [comment]
You can see the prior history at https://github.com/samth/old-plt

**Comment by samth** [comment]
That code was added here https://github.com/samth/old-plt/commit/a28f69665617d1bb150ee07b3167ca8b98a62d5a#diff-e459d8f24333f32bb3cdb4ae3d9d5b7fR1978 (I think that commit added UTF8 support to regexps and maybe other things) and has apparently always been dead.
