### ISSUE TITLE
Database error when docindex.sqlite is missing in the global scope

### ISSUE THREAD

**Issue by jsmaniac** [racket/racket#2292]
See here: https://stackoverflow.com/a/51581151

Dockerfile to reproduce the issue (thanks `kefin` on IRC!):

```
from base/archlinux

run pacman -Syu
run pacman --noconfirm -S racket
run raco pkg install --auto glfw3

cmd ["/usr/bin/env", "bash"]
```

Docker 2-liner (assuming `.` contains the above or below `Dockerfile`):

```
docker build -t some-name .
docker run -it --rm some-name
```

Dockerfile which works:

```
from base/archlinux

run pacman -Syu
run pacman --noconfirm -S racket
run pacman --noconfirm -S racket-docs
run raco pkg install --auto glfw3

cmd ["/usr/bin/env", "bash"]
```

I think it would be reasonable to allow package managers to exclude the docs, and if we need to rebuild them, do so entirely in the user scope.

**Comment by winny-** [comment]
It might be worthwhile to open a ticket on the [Archlinux bug tracker](https://bugs.archlinux.org/) about this behavior. Some mitigations for the current version of Racket in the Archlinux Repositories include merging `racket` and `racket-doc` together since they need each other to function correctly or move the `docindex.sqlite` from `racket-doc` to `racket`.

As a sidenote, I was able to run `raco pkg install` without error with the `racket-minimal` package installed.

Hope this helps!

**Comment by jsmaniac** [comment]
@winny- : Issue opened on the Archlinux bug tracker: https://bugs.archlinux.org/task/60413

**Comment by jsmaniac** [comment]
@winny- sorry to bother you, if you still use Arch Linux, could you check if racket 7.1-1 fixes this issue?

Kyle Keen asked on the upstream bug report if we could try this version.

Thanks!

**Comment by pmatos** [comment]
@jsmaniac I assume you mean 7.2-1? I use archlinux. What specifically would you like to see tested? `pacman -S racket`?

**Comment by pmatos** [comment]
When I try the docker file above I am getting:
```
docker build -t some-name .
Sending build context to Docker daemon  2.048kB
Step 1/5 : from base/archlinux
manifest for base/archlinux:latest not found
```

**Comment by jsmaniac** [comment]
@pmatos the commands are
```
pacman -S racket
run raco pkg install --auto glfw3
```

It used to fail if `pacman -S racket-docs` was absent, and succeed if that Arch package was installed.

Thanks!

**Comment by jsmaniac** [comment]
It seems that the base docker image for archlinux has been renamed / removed, but docker was used just to have a more easily reproducible bug (funny that this is the part that ended up disappearing).

**Comment by pmatos** [comment]
Works for me with `7.2-1` in arch. Also, I assumed the `run` in the prefix to `raco` above was a mistake. I ran:
```
pacman -S racket
raco pkg install --auto glfw3
```

Please close if fixed.

**Comment by jsmaniac** [comment]
@pmatos thanks for the test! I'm closing this and will close the report on the arch bug tracker too.

**Comment by pmatos** [comment]
@jsmaniac Perfect, thanks!
