### ISSUE TITLE
interal error from `contract-out` when super struct name is misspelled

### ISSUE THREAD

**Issue by florence** [racket/racket#2303]
The program

```
(provide
 (contract-out
  [struct (b not-a) ()]))

(struct a ())
(struct b a ())
```

errors with:

```
contract/provide.rkt: internal error.2: #<syntax:control-graph.rkt:4:11 b>
  context...:
   /Applications/Racket/racket/collects/racket/contract/private/provide.rkt:675:7: build-struct-code
   /Applications/Racket/racket/collects/racket/contract/private/provide.rkt:504:14: try-next
   /Applications/Racket/racket/collects/racket/contract/private/provide.rkt:458:0: true-provide/contract
   /Applications/Racket/racket/collects/racket/contract/private/out.rkt:32:0: handle-contract-out
```

**Comment by florence** [comment]
Two maybe related issues:

1)

In the program:

```
#lang racket
(module x racket
  (provide
   (contract-out
    [struct (child not-super) ([a any/c]
                               [b any/c])]))

  (struct not-super (c))
  (struct super (a))
  (struct child super (b)))
(require (submod "." x))

(child 1 2)
```

does not error even though the wrong super struct is given.

2)

The documentation states that:

```
If the structure type has a parent, the second struct form (above) must be used, with the first name referring to the structure type to export and the second name referring to the parent structure type. 
```
(where "the second form" appears to refer to `id/super`).

However the program:

```
#lang racket
(module x racket
  (provide
   (contract-out
    [struct child ([a any/c] [b any/c])]))
  (struct super (a))
  (struct child super (b)))
(require (submod "." x))

(child 1 2)
```

Does not error.

**Comment by florence** [comment]
More:

The documentation states: "The structure-type definition must appear before the provide clause within the enclosing module."

However that is not the case in any of these examples, yet it never errors. 

(I can open new Issues if desired)

**Comment by rfindler** [comment]
The commit that closed this PR does the minimal thing to make sure that the error message is sensible.

But looking over the code, I'm not sure why having the first parent struct is useful. Probably a good thing would be to ignore that entirely (but there would need to be more changes to make that happen).
