### ISSUE TITLE
places: bad error message / segfault on file descriptor dup fail

### ISSUE THREAD

**Issue by david-vanderson** [racket/racket#2305]
test.rkt:

#lang racket

(provide main)

(define (main)
  (define out
    (place in
           (for/list ((n (in-naturals)))
             (place-channel-get in))))

  (define PORT 12346)
  (define listener (tcp-listen PORT 100 #t))
  (define-values (i o) (tcp-connect "127.0.0.1" PORT))
  (for ((n (in-naturals)))
    (printf "sending port ~a\n" n)
    (place-channel-put out i)))

# racket -tm test.rkt
...
sending port 236
place-channel-put: value not allowed in a message
  value: #<input-port:127.0.0.1>
  message: #<input-port:127.0.0.1>
  context...:
   /Users/dvanderson/test.rkt:14:2: for-loop
   /Users/dvanderson/test.rkt:5:0: main
   eval-one-top12

On Mac and Linux you get that after exhausting your file descriptors, Windows gets a segfault.  Jay pointed me to place.c, and I was able to trace it to around line 1174:

1174             dupfd = rktio_dup(scheme_rktio, fd);
1175             if (!dupfd) {
1176               if (can_raise_exn)
1177                 scheme_rktio_error("dynamic-place", "socket dup");
1178               if (delayed_errno) {
1179                 intptr_t tmp;
1180                 tmp = rktio_get_last_error(scheme_rktio);
1181                 *delayed_errno = tmp;
1182                 tmp = rktio_get_last_error_kind(scheme_rktio);
1183                 *delayed_errkind = tmp;
1184               }
1185               return NULL;
1186             }

can_raise_exn is false, so scheme_rktio_error isn't called when it should be.  There's a similar block around line 1213 that probably has the same issue.

I'm not sure where to go from here.  Seems like either can_raise_exn should be true or we need to signal an error some other way if it's false?

**Comment by mflatt** [comment]
Thanks for the report! I see the problems, and I'll push repairs.

**Comment by david-vanderson** [comment]
Thank you!
