### ISSUE TITLE
`#lang info` only accepts <maj>.<min> version strings, contrary to documentation

### ISSUE THREAD

**Issue by wilbowma** [racket/racket#2309]
`raco` rejects the dependency specification in the file below, which uses a version string in the format `<maj>.<min>.<sub>`, but the  docs (https://docs.racket-lang.org/pkg/Package_Concepts.html?q=Package%20Concepts) claim `#lang info` accepts dependencies with version strings as either `<maj>.<min>`, `<maj>.<min>.<sub>`, or `<maj>.<min>.<sub>.<rel>`. 

Steps to reproduce:
1. Create the following `info.rkt` file in an empty directory.
```
#lang info

(define deps '(("foo" #:version "0.3.0")))
```
2. Run `raco pkg install` in that directory.
3. Get the unexpected error: 
```
Linking current directory as a package
raco pkg install: invalid `deps' specification
  specification: '(("foo" #:version "0.3.0"))
```

If we change the version string to "0.30", then step 2 succeeds as expected.

(Related but orthogonal problem: that error message is crap; I get the same message if I forget to make "foo" a string, or if I have multiple specs, so it doesn't help me debug at all.)

**Comment by mflatt** [comment]
The docs are missing the constraint that <sub> cannot be 0.

**Comment by wilbowma** [comment]
That's an odd restriction; is it necessary?

**Comment by mflatt** [comment]
The restrictions are intended to force version numbers to be in a canonical form. For example, it's meant to rule out using "4.3.0" instead of "4.3" or "4.3.1.0" instead of "4.3.1". Meanwhile, "4" by itself is not allowed, and must be written as "4.0".

**Comment by wilbowma** [comment]
Oh that makes sense; thanks a lot!
