### ISSUE TITLE
Runtime errors during core tests

### ISSUE THREAD

**Issue by pmatos** [racket/racket#2314]
I found a few runtime errors, thanks to ubsan, that should be fixed. At the moment I have no time so this is a reminder for me, or a note to anyone else who would like to tackle them.

If you compile with ubsan and run the core tests you'll see:

- [x] Section *reading*: `../../../racket/gc2/../src/numstr.c:448:18: runtime error: signed integer overflow: 266666666 * 10 cannot be represented in type 'int'` - fixed by #2319
- [x] Section *unsafe*: `../../../racket/gc2/../src/number.c:5508:11: runtime error: left shift of 1 by 63 places cannot be represented in type 'long int'` - fixed by #2653 
- Section *fixnum*:
  - [ ] `../../../racket/gc2/../src/numarith.c:1271:7: runtime error: signed integer overflow: 9172034182905281024 + 1268111012645630976 cannot be represented in type 'long int'`
  - [ ]  `../../../racket/gc2/../src/numarith.c:1272:7: runtime error: signed integer overflow: 7193340147698933760 - -2058250744780168704 cannot be represented in type 'long int'`
  - [ ] `../../../racket/gc2/../src/numarith.c:1273:7: runtime error: signed integer overflow: -4508138700560545280 * -3892215211304724480 cannot be represented in type 'long int'`

This is something I will definitely return to but not in the next few days.

**Comment by sorawee** [comment]
Fixed.
