### ISSUE TITLE
Mojave + nightly-build + language>show-details = crash

### ISSUE THREAD

**Issue by jbclements** [racket/racket#2317]
It appears to me that the nightly snapshot reproducibly crashes on Mojave when opening the "Language Details" sub-panel.

1) Download nightly snapshot from 2018-10-16, "7.1.0.1--2018-10-16(fa6bd87bcd/a) [3m]."
2) Open DrRacket
3) Choose menu "Language>Choose Language..."
4) Click "Show Details" button

DrRacket dumps core, showing this on the terminal:

```
 2018-10-16 14:45:39.124 DrRacket[4549:197907] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unbalanced disable posting.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff3b8b943d __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff677c6720 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3b8b926f +[NSException raise:format:] + 201
	3   Racket                              0x0000000103ad9e3c ffi_call_unix64 + 76
	4   ???                                 0x00007ffeec3fa840 0x0 + 140732862015552
)
libc++abi.dylib: terminating with uncaught exception of type NSException

[3]  + abort      ./bin/drracket
```

Also attaching the crash report:

[gg.txt](https://github.com/racket/racket/files/2485069/gg.txt)

I realize that this is strictly speaking a DrRacket crash rather than a Racket crash, but it appears to me that this is certain to be at least in part a Racket issue.

**Comment by mflatt** [comment]
Thanks – I can replicate the problem on my machine, too.

I meant to revert the Mojava-specific changes to `racket/gui` for v7.1. There are likely to be more problems, and the changes should not be needed for the way the release is built.
