### ISSUE TITLE
[racketcs] `make cs` does not work on FreeBSD

### ISSUE THREAD

**Issue by abmclin** [racket/racket#2344]
Firstly, is it planned for Racket-on-Chez to be supported on BSD family operating systems? 

If so here's a summary of all the issues I've found. I took `make cs` as far as I was able with my level of experience. It appears that the issues I ran into seem to be only arising from ChezScheme.

I'm running GhostBSD which is based on 64-bit FreeBSD kernel 11.1.

The first issue encountered is missing boot files for `ta6fb` architecture. As explained in https://github.com/cisco/ChezScheme/issues/7 BSD boot files are not built by default. Following the recommended method in the issue comments, I cross-compiled and copied the missing boot files to my FreeBSD machine which allows make to continue.

Second issue is ChezScheme's makefiles are only compatible with GNU make, to work around that I aliased `make` with `gmake`

The third issue and this is as far as I got, is a compilation error occurring when compiling `io.sls` an attempt is made to load `libc.so` which fails with invalid file format error. In FreeBSD variants, `libc.so` is a linker script which resolves to `libc.so.7` Apparently the linker doesn't know how to handle the FreeBSD case.

In case this is relevant, I see some code in `ChezScheme/mats/foreign.ms` which attempts to deal with loading `libc.so` on FreeBSD machines.

If RacketCS won't be supported on BSD family in the foreseeable future - which I hope won't be the case, then feel free to close this issue. Though I will continue to advocate for BSD support :-)

**Comment by mflatt** [comment]
Does b9c042329bfa45bf0c5d08fc75c401b43cac5284 let you use `gmake cs` (as opposed to having to globally redirect `make` to `gmake`), or is there still some other issue with `gmake cs`?

**Comment by abmclin** [comment]
with the latest commits `gmake cs` continues some more but there's a new issue with ld not finding libiconv during a compilation step.

I've attached a file of the last 50 lines of `gmake cs` output. The entire output is a 183 MB file, let me know if you want all of it.
[truncated_out.txt](https://github.com/racket/racket/files/2530232/truncated_out.txt)

**Comment by abmclin** [comment]
As far as I can tell libiconv is installed on my system.

`ldconfig -r | grep libiconv` returns `liconv.2 => /usr/local/lib/libiconv.so.2`

**Comment by samth** [comment]
From that output, it looks like Chez (or maybe Racket) is looking for libiconv without a version. Is there a package you can install that has the unversioned .so file?

**Comment by abmclin** [comment]
I searched for the locations of `libiconv` and found the below
```
-rw-r--r--  1 root  wheel  1137432 Oct 10  2017 /usr/local/lib/libiconv.a
lrwxr-xr-x  1 root  wheel       17 Oct 10  2017 /usr/local/lib/libiconv.so -> libiconv.so.2.5.1
lrwxr-xr-x  1 root  wheel       17 Oct 10  2017 /usr/local/lib/libiconv.so.2 -> libiconv.so.2.5.1
-rw-r--r--  1 root  wheel  1076457 Oct 10  2017 /usr/local/lib/libiconv.so.2.5.1
```
`libiconv.so` is in `/usr/local/lib/` and soft linked to `libiconv.so.2.5.1` I'm wondering if the problem is that the library isn't in `/usr/lib/` which seems to be preferred location in GNU/Linux systems. Maybe a viable approach is to configure `LD_LIBRARY_PATH` with additional information?

**Comment by abmclin** [comment]
When I manually edit `racket/src/cs/c/Makefile.in` to add `-L /usr/local/lib -liconv` to `LIBS` variable, `gmake cs` is able to proceed a bit further before hitting another error

```
cc -g -O2   -pthread -I/home/abm/Workspace/git/racket/racket/src/build/ChezScheme/ta6fb/boot/ta6fb -I../../cs/c/../../rktio -Irktio -I. -o raw_racketcs main.o boot.o /home/abm/Workspace/git/racket/racket/src/build/ChezScheme/ta6fb/boot/ta6fb/kernel.o rktio/librktio.a -pthread -lm  -L /usr/local/lib -liconv
main.o: In function `bytes_main':
/home/abm/Workspace/git/racket/racket/src/build/cs/../../cs/c/main.c:190: undefined reference to `get_self_path'
cc: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[8]: *** [Makefile:145: raw_racketcs] Error 1
gmake[8]: Leaving directory '/usr/home/abm/Workspace/git/racket/racket/src/build/cs'
gmake[7]: *** [Makefile:50: cs] Error 2
gmake[7]: Leaving directory '/usr/home/abm/Workspace/git/racket/racket/src/build/cs'
gmake[6]: *** [Makefile:331: cs-after-racket-with-abs-paths] Error 2
gmake[6]: Leaving directory '/usr/home/abm/Workspace/git/racket'
gmake[5]: *** [Makefile:327: cs-after-racket-with-racket-and-scheme-src] Error 2
gmake[5]: Leaving directory '/usr/home/abm/Workspace/git/racket'
gmake[4]: *** [Makefile:321: cs-after-racket-with-racket] Error 2
gmake[4]: Leaving directory '/usr/home/abm/Workspace/git/racket'
gmake[3]: *** [Makefile:308: racket-configured-then-cs] Error 2
gmake[3]: Leaving directory '/usr/home/abm/Workspace/git/racket'
gmake[2]: *** [Makefile:302: racket-then-cs] Error 2
gmake[2]: Leaving directory '/usr/home/abm/Workspace/git/racket'
gmake[1]: *** [Makefile:275: plain-cs] Error 2
gmake[1]: Leaving directory '/usr/home/abm/Workspace/git/racket'
gmake: *** [Makefile:269: cs] Error 2

```

**Comment by mflatt** [comment]
Although there's a generic Unix `get_self_path` in place, now, I think it would be a good idea to use your specialization. Can you turn this into a PR? It may be as easy as pasting in your code with an exttra `# undef USE_GENERIC_GET_SELF_PATH` before the `#endif`.

The "malformed fasl-object header in petite" problem is probably because the `strip` operation on install moved the embedded boot files within the executable. I've adjusted the configure script to turn on ELF support for finding embedded boot files, so `strip` now works.

**Comment by mflatt** [comment]
Also, in case you didn't know already: You won't have to build Chez Scheme boot files, anymore. They will be built automatically (via Racket running Chez Scheme's compiler).

**Comment by abmclin** [comment]
> 
> 
> Although there's a generic Unix `get_self_path` in place, now, I think it would be a good idea to use your specialization. Can you turn this into a PR? It may be as easy as pasting in your code with an exttra `# undef USE_GENERIC_GET_SELF_PATH` before the `#endif`.

Sure, I'd be happy to do that.

**Comment by abmclin** [comment]
In addition, I also found that with gcc version 7 and above `-Wextra` now includes a new `-Wimplicit-fallthrough` raising warnings about implicit fallthroughs which stops compilation of `schsig.c` in ChezScheme codebase. It can be resolved by modifying the FreeBSD makefiles in the ChezScheme to include `-Wno-implicit-fallthrough` in the cc options which turns off the new check.

I don't know if this also affects OpenBSD and NetBSD, I imagine it probably does since the makefiles for those platforms doesn't have the new option.

I can open another PR with the above fix. It probably is better to open the PR against cisco\ChezScheme and it can be merged downstream into racket\ChezScheme, right?

**Comment by abmclin** [comment]
Just to comment the sake of the discussion, with the recent Makefile changes, racket\ChezScheme and the above `-Wno-implicit-fallthrough` fix for gcc v7+ `make cs` is successful on FreeBSD variants including TrueOS. 

The malformed fasl-object header error has gone away too so your guess about its cause is probably correct.

**Comment by mflatt** [comment]
Yes, if you post a PR to Chez Scheme, I can pick it up early for the Racket fork.

I think a better solution for GCC 7+ is to adjust the source instead of changing the warning flags. Of the options illustrated at https://developers.redhat.com/blog/2017/03/10/wimplicit-fallthrough-in-gcc-7/, the comment one looks most appealing to me — hacky, but simple and portable.

**Comment by abmclin** [comment]
I like the idea of adding a comment to the source code. It should work automatically for wide variety of platform, making this approach more robust.

Just to make sure we're looking at the same comment, the one you have in mind is `/* Falls through. */`?

**Comment by mflatt** [comment]
Yes — that comment or any accepted variant that looks nice to you.

**Comment by abmclin** [comment]
Hmm, looking at the relevant lines in `schsig.c` under `handle_signal` https://github.com/cisco/ChezScheme/blob/master/c/schsig.c#L587-L610 that's causing the implicit fall through warning, I think adding fallthrough comments would be misleading because it appears that each case ends in non-returning function calls (I could be wrong about what those S_* functions are doing) so they don't actually fall through to the next case. It looks like a false positive gcc warning to me.

Looks like we're stuck with editing the makefiles instead. Thoughts?

**Comment by samth** [comment]
If they don't return, could you add a `break` after them?

**Comment by abmclin** [comment]
Yes that seems to work, I'll continue building and run some tests just to be sure.

**Comment by pmatos** [comment]
Hi... I need to intervene here since I am looking at something that looks potentially related. I think this is related to https://github.com/racket/ChezScheme/pull/8

The functions that do not return should be marked with noreturn. That fixes at least part of the issues. Problem is that GCC8 (maybe 7 as well) something like this will happen with certain optimization flags:
```
scheme.c: In function ‘find_boot’:
scheme.c:637:8: error: ‘n’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
     if (n != scheme_version) {
```

That's warning is a false positive. GCC can't know that because it doesn't know that the previous call to `S_abnormal_exit` won't return. I would really like this to be fixed properly upstream since it sorts out a bunch of problems. The current issue is defining a macro that works for both GCC, Clang and MSVC. Both GCC and Clang support `__attribute__((noreturn))`. MSVC doesn't, as pointed out by Matthew. We need an alternative but I haven't had the time to research this yet.

At the moment I am working on JSC, the JavaScript compiler in WebKit and I see this code here:
```
/* NO_RETURN */

#if !defined(NO_RETURN) && COMPILER(GCC_COMPATIBLE)
#define NO_RETURN __attribute((__noreturn__))
#endif

#if !defined(NO_RETURN) && COMPILER(MSVC)
#define NO_RETURN __declspec(noreturn)
#endif

#if !defined(NO_RETURN)
#define NO_RETURN
#endif
```

Maybe for Racket/Chez we can do (*untested*):
```
#if !defined(NORETURN)
#if defined(__GNUC__) || defined(__clang__)
#define NORETURN __attribute__((noreturn))
#elif defined(_MSC_VER)
#define NORETURN __declspec(noreturn)
#else 
#define NORETURN
#endif /* defined(__GNUC__) || defined(__clang__) */
#endif /* !defined(NORETURN) */
```

**Comment by abmclin** [comment]
I’ll be happy to give that a try, it does seem like a good approach to take here. I will report back soon.

Thank you.

**Comment by pmatos** [comment]
I should point out I haven't tested the above code or ensured it actually solves your problem. I just typed that from memory because it looked similar to a problem I was looking at a couple of days ago. Please confirm it actually solves this particular issue. :)

**Comment by abmclin** [comment]
@pmatos your suggestion worked, all implicit-fallthrough warnings were removed by adding `NORETURN` to appropriate places. And turns out it was also necessary to add `/* fall through */ in other places.

I've opened a PR against cisco/ChezScheme https://github.com/cisco/ChezScheme/pull/437

**Comment by DavidAlphaFox** [comment]
[config.log](https://github.com/racket/racket/files/6247337/config.log)

Hi 
I try to compile the Racket CS on FreeBSD machine.
I saw this config.log, but I pasted the test code in a file, built and ran it alone, it could give a correct value.

Thanks

**Comment by samth** [comment]
@DavidAlphaFox It looks like your system can't find libiconv. Do you have that installed?

**Comment by DavidAlphaFox** [comment]
@samth  

Thanks for reply
I found the problem, I should use gmake instead of make.

**Comment by mflatt** [comment]
I think we have CS build ok on FreeBSD (yes, with `gmake`), so I'll close this.
