### ISSUE TITLE
Documentation of parametric->/c

### ISSUE THREAD

**Issue by Paul-C-Anagnostopoulos** [racket/racket#2353]
The reference documentation for `parametric->/c` includes a single example that shows a parametric function that misuses its arguments. After some discussion on Slack, I suggest that the documentation be enhanced to first include a simple function that does not misuse its arguments. I also suggest that the existing example include a few sentences about why it misuses its arguments.

This paper contains a paragraph that can be used as a basis for the new sentences:

https://www.eecs.northwestern.edu/~robby/pubs/papers/dls2007-gmfk.pdf

**Comment by bennn** [comment]
https://github.com/racket/racket/commit/6abadc472edab7cccc6fc5db16f292fdfca88f90
