### ISSUE TITLE
Interaction of reset and exception is unexpected

### ISSUE THREAD

**Issue by sorawee** [racket/racket#2365]
I'm not sure if this is a bug. In case that it is not, I would appreciate if anyone can explain what's going on.

```
#lang racket/base
(require racket/control)
(+ 1 (reset (1 1)))
```

This produces _two_ exceptions in the same run.

```
application: not a procedure;
 expected a procedure that can be applied to arguments
  given: 1
  arguments...:
+: contract violation
  expected: number?
  given: #<void>
  argument position: 2nd
  other arguments...:
```

Also notice that somehow `(reset ...)` is evaluated to `#<void>`.

**Comment by sorawee** [comment]
I believe you are right. The question is, is this the intended semantics for `reset`?

**Comment by mfelleisen** [comment]
Check Matthew's web site for the model of racket/control. I conjecture that you will find that the behavior is correct though inconvenient. We had a similar discussion recently on a related thing I ran into with plain exceptions (off line). There are too many ways to combine control effects with side effects.
