### ISSUE TITLE
can't install from the .exe

### ISSUE THREAD

**Issue by elijahbotkin** [racket/racket#2376]
I keep getting this error:
![image](https://user-images.githubusercontent.com/5598686/48633353-1d8b5380-e991-11e8-8a35-b05e49ba97f4.png)

Tried both the 64- and 32- bit versions

**Comment by mflatt** [comment]
Thanks for the report. These are useful when we see correlated reports, but we didn't get similar report to help know what happened in this case, and things have changed quite a lot and seem to be working since.
