### ISSUE TITLE
Racket REPL up/down keys

### ISSUE THREAD

**Issue by ndrewtl** [racket/racket#2378]
Many command line read-evaluate-print-loops, such as `bash`, `irb`, `python`, `node`, and others maintain a per-session or persistent command history. In these interpreters, hitting the up arrow key replaces the current text at the prompt with the previously-executed command. A combination of the up and down keys can be used to 'scroll' up and down through one's command history in order to re-execute previous commands. However, when I try this in `racket`, it only produces `'^[[A'` for up and `'^[[B'` for down in the prompt.

Am I simply using racket wrong? If this feature exists, is there a way to use it? If not, are there plans to implement it?

**Comment by samth** [comment]
By default, the racket REPL loads the xrepl library, which provides this and many other features. You can load it manually with (require xrepl) but you shouldn't have to. Can you say more about how you installed and started racket?

**Comment by ndrewtl** [comment]
## Fixed! `xrepl` wasn't installed

Thanks for responding! I installed racket with Homebrew, without DrRacket using `brew cask install minimal-racket`. Running `racket` from the command-line, I encountered this issue. I tried running `(require xrepl)` from inside the racket prompt, and it didn't seem to exist:

```racket
Welcome to Racket v7.0.
> (require xrepl)
standard-module-name-resolver: collection not found
  for module path: xrepl
  collection: "xrepl"
  in collection directories:
... 
```

So I tried installing with `raco pkg install xrepl`. xrepl installed and everything worked from there.
