### ISSUE TITLE
curious printing of byte string in error message

### ISSUE THREAD

**Issue by mbutterick** [racket/racket#2387]
In ordinary Racket, this expression:

```racket
(cadr (list #"x"))
```

Produces this error:

```text
cadr: contract violation
   expected: (cons/c any/c pair?)
   given: '(#"x")
```

But in RacketCS:

```text
cadr: incorrect list structure (#vu8(120))
```

**Comment by mflatt** [comment]
While I hope to make further improvements to unify error messages, the problem of seeing Chez-style values in error messages instead of Racket-style values should be fixed.
