### ISSUE TITLE
[racketcs] literal vectors are mutable when file is compiled

### ISSUE THREAD

**Issue by florence** [racket/racket#2394]
give the file:

```
#lang racket
(immutable? #("a"))
```

If I delete my compiled files and run `racket` on this i get `#t`

but if I `raco make` the file then run `racket` on it i get `#f`

This is causing a build failure in Cover: https://travis-ci.org/florence/cover/jobs/457538301#L689

**Comment by gus-massa** [comment]
Probably boxes have the same problem.
