### ISSUE TITLE
`gensym` fails with any base argument

### ISSUE THREAD

**Issue by mbutterick** [racket/racket#2396]
Ice cold

```text
> (gensym 'foo)
'foo
> (gensym 'foo)
'foo
> (gensym 'foo)
'foo
> (gensym "bar")
'bar
> (gensym "bar")
'bar
> (gensym "bar")
'bar
```

**Comment by mflatt** [comment]
Just in case it's not clear, those symbols are all distinct, even though they print the same. But I agree that it's probably best to append a counter to make the difference a little more apparent.

**Comment by mfelleisen** [comment]
That would not be the traditional thing to do.

**Comment by mflatt** [comment]
@mfelleisen I'm not sure I understand what you mean. It's certainly traditional for `gensym` to append a counter so it looks different when printing, even though it's not really the counter that makes the generated symbol unique. Racket also has `string->uninterned-symbol` for cases where you want to fully control the printed form.

**Comment by mbutterick** [comment]
> Just in case it's not clear, those symbols are all distinct

Ah, my fault then — I misunderstood the mechanics of `gensym`. 

I was nevertheless confused by the fact that a) in RacketCS, `gensym` without an argument appends a counter to `g` (so I expected the `gensym` argument simply to replace the `g`); and b) in non-CS Racket, `gensym` with an argument has a counter (so I expected the same behavior in CS).

FWIW at times I’ve also (ab)used `gensym` to generate (what I took to be) symbols that remain unique after serialization — for instance, as ids for elements in an HTML page. Though apparently that has only worked incidentally, not inherently.
