### ISSUE TITLE
cs: Bad error message from `raise-argument-error`

### ISSUE THREAD

**Issue by LiberalArtist** [racket/racket#2400]
The error message produced by `raise-argument-error` in the many-argument case is different in the latest Racket-on-Chez snapshot (7.1.0.6) than in Racket 7.1, seemingly incorrectly. Specifically, Racket-on-Chez omits the `argument position` message field altogether and gives the `other arguments` field without the `...`.

Example:
```
Sapientia:~ philip$ racket
Welcome to Racket v7.1.
> (raise-argument-error 'example "symbol?" 0 "bad" 'ok)
; example: contract violation
;   expected: symbol?
;   given: "bad"
;   argument position: 1st
; [,bt for context]
> ,bt
; example: contract violation
;   expected: symbol?
;   given: "bad"
;   argument position: 1st
;   other arguments...:
;    'ok
;   context...:
;    eval-one-top12
;    /Applications/Racket v7.1/share/pkgs/xrepl-lib/xrepl/xrepl.rkt:1477:0
;    /Applications/Racket v7.1/collects/racket/repl.rkt:11:26
> ^D
Sapientia:~ philip$ /Applications/Racket\ v7.1.0.6/bin/racket
Welcome to Racket v7.1.0.6 [cs].
> (raise-argument-error 'example "symbol?" 0 "bad" 'ok)
; example: contract violation
;   expected: symbol?
;   given: "bad"
;   other arguments:
;    'ok
; [,bt for context]
> ,bt
; example: contract violation
;   expected: symbol?
;   given: "bad"
;   other arguments:
;    'ok
;   context...:
;    do-raise-argument-error
;    /Users/racket/build/plt/build/cs/racket/src/build/cs//compiled/expander.scm:50452:5: body of top-level
;    call-with-values
;    /Users/racket/build/plt/build/cs/bundle/racket/share/pkgs/xrepl-lib/xrepl/xrepl.rkt:1477:0
;    /Users/racket/build/plt/build/cs/racket/collects/racket/repl.rkt:11:26
;    main.sps:621:4: thunk_6
```

**Comment by LiberalArtist** [comment]
It might also be considered "bad" that Racket-on-Chez seems to report paths in terms of the build machine. (There is no such directory as `/Users/racket/` on my machine.)

**Comment by LiberalArtist** [comment]
OTOH, the Racket-on-Chez error message mentioning `do-raise-argument-error` wad enought for me to track down: https://github.com/racket/racket/blob/744d440ab9fe36bd291b582ebe2bec33e9364ac5/racket/src/cs/rumble/error.ss#L149-L157

**Comment by mflatt** [comment]
Thanks for the patch! Yes, there are a lot of issues still with paths and keeping full paths in the builds.
