### ISSUE TITLE
Vector mutability in quasiquote

### ISSUE THREAD

**Issue by shhyou** [racket/racket#2403]
Quasiquotes could produce either immutable or mutable vectors, depending on the actual program. Should `quasiquote` always produce immutable vectors?

```
$ racket
Welcome to Racket v7.1.0.2.
> (immutable? `#(A B C))
#t
> (immutable? `#(A ,0 C))
#f
```

~~Probably `t-vector` should invoke `vector->immutable-vector`~~.

EDIT: the related code is in `qq-and-or.rkt`, not `template.rkt`. <https://github.com/racket/racket/blob/master/racket/collects/racket/private/qq-and-or.rkt#L367>

**Comment by shhyou** [comment]
I tried changing `quasiquote` to be using `vector->immutable-vector` after `list->vector` in the above commit and timed these two programs.
```
;; a.rkt
#lang racket/base
(time
 (for ([i (in-range 100000000)])
   `#(4 ,i 5)))

;; b.rkt
#lang racket/base
(time
 (for ([i (in-range 10)])
   `#(3 5 ,@(for/list ([j (in-range 10000000)])
             (+ i j)))))
```

Before the change, the first one roughly took 4.4s. After the change, the fist one took 7.1s. The GC time went from 1.8~2.0s to 3.6~4.4s.

For the second program, it took roughly 16.5s with GC time 13.2s before the change. After the change, it took around 17.7s with GC time 13.9s.

There are some slowdown for quasiquoting vectors, though the time doesn't just directly double as I thought.

**Comment by shhyou** [comment]
Good point! Let me try that.

**Comment by shhyou** [comment]
The result seems better. Still slower, but more consistent.

The first program, original: cpu time 4597.5, real time 4643.7, gc time 219.1
The first program, immutable: cpu time 5843.0, real time 5892.2, gc time 307.1

The second program, original: cpu time 17680.9, real time 17862.2, gc time 14050.5
The second program, immutable: cpu time 18906.5, real time 19032.9, gc time 14401.6

**Comment by mfelleisen** [comment]
I don’t think quasiquote and quote have been that consistent at any point in history.

**Comment by shhyou** [comment]
I search in the documentation and there isn't a spec about the mutability of the produced value. In this case, producing mutable vectors and boxes should be fine. If people don't mind I'm happy to close this issue.

**Comment by mflatt** [comment]
I think this issue should trigger a documentation improvement, at least.

I'm not sure whether `quasiquote` should have been defined to produce immutable vectors and boxes, but I don't think it's worth the compatibility problems of trying to change it at this point.
