### ISSUE TITLE
ctrl-c should clear the current line in REPL

### ISSUE THREAD

**Issue by sorawee** [racket/racket#2432]
Consider:

```
> (+ 1 1)
```

After `ctrl-c`:

```
> (+ 1 1); user break [,bt for context]
```

After pressing the enter key:

```
> (+ 1 1); user break [,bt for context]


2
>
```

In the above interaction, most REPLs (`bash`, `python`, `node`, etc.) would:

- discard the current line after `ctrl-c` (so `(+ 1 1)` should be completely gone) and redisplay the prompt
- do not show `; user break [,bt for context]` (which is awkward because nothing is running)

**Comment by sorawee** [comment]
It turns out that if we use the usual input port, then `ctrl-c` will clear the current line as expected already. The weird behavior that we can see here is due to the `readline` package.

First, we can see the the usual input port works as expected.

```
#lang racket

(define (loop)
  (call-with-continuation-prompt
   (thunk (display "> ")
          (displayln (read-line)))
   (default-continuation-prompt-tag)
   (thunk* (loop))))

(loop)
```

```
> 1 ^Cuser break
  context...:
   ~/test.rkt:5:3
   "~/test.rkt": [running body]
   temp35_0
   for-loop
   run-module-instance!
   perform-require!
> 2
2
```

But when we `(require readline)`, it installs its custom input port which changes the interaction:

```
>
1 user break
  context...:
   /Users/sorawee/test.rkt:7:3
   "/Users/sorawee/test.rkt": [running body]
   temp35_0
   for-loop
   run-module-instance!
   perform-require!
2
2
> 1 2
```

**Comment by singpolyma** [comment]
What is strange is that the `readline` defaults are to do exactly what we want on SIGINT, so something in the `racket` library must be over-riding this? https://tiswww.cwru.edu/php/chet/readline/readline.html#SEC44

**Comment by rfindler** [comment]
I think that showing the break is actually very important. That is, the racket REPL thread seems to actually be eventspace aware and working well for stuff like this:

```
Welcome to Racket v8.1.0.6 [cs].
> (require racket/gui)
> (define f (new frame% [label ""]))
> (define (cb . x) (displayln "thinking...") (sleep 5) (displayln "aha!"))
> (define b (new button% [label "button"] [callback cb] [parent f]))
> (send f show #t)
```

At this point, evaluating expressions in the REPL and running GUI callbacks are all happening on the same thread (which is the way it should be) and so when you do a control-c you want to see the stacktrace for the thing that's actually running (say that `sleep` call was actually some buggily slow program -- you want to see where it is and break stacktraces are great for that kind of thing).

**Comment by sorawee** [comment]
Not fixed per se, but it's no longer a problem after expeditor becomes the default REPL, so I will close this.
