### ISSUE TITLE
[racketcs] Installing racquel package causes bound-identifier=? arity mismatch error

### ISSUE THREAD

**Issue by nadeemabdulhamid** [racket/racket#2435]
Using RacketCS 7.1.0.10, I tried installing the 'racquel' package, which fails to compile due to arity mismatch errors on bound-identifier=?. I can't figure out how to trace what exactly causes it, but it must have something to do with syntax parse? Here is the full install log:

Resolving "racquel" via https://www.cs.utah.edu/plt/snapshots/20181221-b60fed7916/catalog/
Resolving "racquel" via https://pkgs.racket-lang.org
Downloading repository git://github.com/brown131/racquel
raco setup: version: 7.1.0.10
raco setup: platform: x86_64-macosx [cs]
raco setup: target machine: ta6osx
raco setup: installation name: snapshot
raco setup: variants: cs
raco setup: main collects: /Applications/Racket v7.1.0.10/collects
raco setup: collects paths: 
raco setup:   /Users/nhamid/Library/Racket/snapshot/collects
raco setup:   /Applications/Racket v7.1.0.10/collects
raco setup: main pkgs: /Applications/Racket v7.1.0.10/share/pkgs
raco setup: pkgs paths: 
raco setup:   /Applications/Racket v7.1.0.10/share/pkgs
raco setup:   /Users/nhamid/Library/Racket/snapshot/pkgs
raco setup: links files: 
raco setup:   /Applications/Racket v7.1.0.10/share/links.rktd
raco setup:   /Users/nhamid/Library/Racket/snapshot/links.rktd
raco setup: main docs: /Applications/Racket v7.1.0.10/doc
raco setup: --- updating info-domain tables ---
raco setup: updating: /Users/nhamid/Library/Racket/snapshot/share/info-cache.rktd
raco setup: --- pre-installing collections ---
raco setup: --- installing foreign libraries ---
raco setup: --- installing shared files ---
raco setup: --- compiling collections ---
raco setup: --- parallel build using 4 jobs ---
raco setup: 3 making: <pkgs>/racquel (Racquel: An Object/Relational Mapper for Racket)
bound-identifier=?: arity mismatch;
 the expected number of arguments does not match the given number
  expected: 2
  compilation context...:
   /Users/nhamid/Library/Racket/snapshot/pkgs/racquel/stxclass.rkt
  context...:
   condition->exn
   dynamic-wind
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/private/id-table.rkt:369:10: loop
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/private/id-table.rkt:95:2: do-set!
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep-attrs.rkt:90:2: for-loop
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep-attrs.rkt:90:2: for-loop
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep-attrs.rkt:85:0: union-iattrs
   /Users/racket/build/plt/build/cs/bundle/racket/collects/racket/contract/private/arrow-val-first.rkt:390:18
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:1111:0: parse*-optional-pattern
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:1101:0: parse-hpat:optional
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:451:2: try-next
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:436:0: parse-*-pattern
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:451:2: try-next
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:436:0: parse-*-pattern
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:451:2: try-next
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:436:0: parse-*-pattern
raco setup: 3 making: <pkgs>/racquel/schema
bound-identifier=?: arity mismatch;
 the expected number of arguments does not match the given number
  expected: 2
  compilation context...:
   /Users/nhamid/Library/Racket/snapshot/pkgs/racquel/main.rkt
  context...:
   condition->exn
   dynamic-wind
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/private/id-table.rkt:369:10: loop
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/private/id-table.rkt:95:2: do-set!
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep-attrs.rkt:90:2: for-loop
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep-attrs.rkt:90:2: for-loop
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep-attrs.rkt:85:0: union-iattrs
   /Users/racket/build/plt/build/cs/bundle/racket/collects/racket/contract/private/arrow-val-first.rkt:390:18
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:1111:0: parse*-optional-pattern
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:1101:0: parse-hpat:optional
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:451:2: try-next
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:436:0: parse-*-pattern
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:451:2: try-next
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:436:0: parse-*-pattern
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:451:2: try-next
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:436:0: parse-*-pattern
bound-identifier=?: arity mismatch;
 the expected number of arguments does not match the given number
  expected: 2
  compilation context...:
   /Users/nhamid/Library/Racket/snapshot/pkgs/racquel/test-chinook.rkt
  context...:
   condition->exn
   dynamic-wind
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/private/id-table.rkt:369:10: loop
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/private/id-table.rkt:95:2: do-set!
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep-attrs.rkt:90:2: for-loop
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep-attrs.rkt:90:2: for-loop
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep-attrs.rkt:85:0: union-iattrs
   /Users/racket/build/plt/build/cs/bundle/racket/collects/racket/contract/private/arrow-val-first.rkt:390:18
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:1111:0: parse*-optional-pattern
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:1101:0: parse-hpat:optional
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:451:2: try-next
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:436:0: parse-*-pattern
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:451:2: try-next
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:436:0: parse-*-pattern
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:451:2: try-next
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:436:0: parse-*-pattern
bound-identifier=?: arity mismatch;
 the expected number of arguments does not match the given number
  expected: 2
  compilation context...:
   /Users/nhamid/Library/Racket/snapshot/pkgs/racquel/test.rkt
  context...:
   condition->exn
   dynamic-wind
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/private/id-table.rkt:369:10: loop
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/private/id-table.rkt:95:2: do-set!
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep-attrs.rkt:90:2: for-loop
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep-attrs.rkt:90:2: for-loop
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep-attrs.rkt:85:0: union-iattrs
   /Users/racket/build/plt/build/cs/bundle/racket/collects/racket/contract/private/arrow-val-first.rkt:390:18
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:1111:0: parse*-optional-pattern
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:1101:0: parse-hpat:optional
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:451:2: try-next
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:436:0: parse-*-pattern
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:451:2: try-next
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:436:0: parse-*-pattern
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:451:2: try-next
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:436:0: parse-*-pattern
bound-identifier=?: arity mismatch;
 the expected number of arguments does not match the given number
  expected: 2
  compilation context...:
   /Users/nhamid/Library/Racket/snapshot/pkgs/racquel/doc/racquel.scrbl
  context...:
   condition->exn
   dynamic-wind
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/private/id-table.rkt:369:10: loop
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/private/id-table.rkt:95:2: do-set!
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep-attrs.rkt:90:2: for-loop
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep-attrs.rkt:90:2: for-loop
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep-attrs.rkt:85:0: union-iattrs
   /Users/racket/build/plt/build/cs/bundle/racket/collects/racket/contract/private/arrow-val-first.rkt:390:18
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:1111:0: parse*-optional-pattern
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:1101:0: parse-hpat:optional
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:451:2: try-next
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:436:0: parse-*-pattern
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:451:2: try-next
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:436:0: parse-*-pattern
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:451:2: try-next
   /Users/racket/build/plt/build/cs/bundle/racket/collects/syntax/parse/private/rep.rkt:436:0: parse-*-pattern
raco setup: --- creating launchers ---
raco setup: --- installing man pages ---
raco setup: --- building documentation ---
raco setup: syncing: <pkgs>/racquel/doc/racquel

**Comment by mflatt** [comment]
Fixed by 5a12d7bf71d37c0e8ed4e08e5abafef4101f094f — thanks for the report!
