### ISSUE TITLE
xml/plist doesn't support numeric entities

### ISSUE THREAD

**Issue by LiberalArtist** [racket/racket#2440]
XML plist files can contain numeric entities, but `xml/plist` doesn't support them. For example, iTunes generates plists containing `<string>Gospel &#38; Religious</string>`, which becomes the xexpr `'(string "Gospel " 38 " Religious")`, which doesn't conform to the [expected grammar](https://docs.racket-lang.org/xml/#%28part._.P.List_.Library%29).

More broadly, I've implemented the transformation from x-expressions like `'(string "Gospel " 38 " Religious")` to `'(string "Gospel & Religious")` more than once before, which suggests to me that the best fix might be to add a parameter or function to `xml` and have `xml/plist` use it.

**Comment by jeapostrophe** [comment]
I'll take a look at this, but I am skeptical that we can get something you want. In particular, I feel like the most likely patch is going to change the grammar. The main problem is that we don't currently do anything anywhere to interpret entities and I am extremely not excited about maintaining a database of what various entities mean.

**Comment by LiberalArtist** [comment]
I agree that trying to interpret named/symbolic entities is not worth-while. Unless I'm misunderstanding (or there's some wacky corner of XML I don't know about, which is possible), I don't think a database would be needed to interpret what I've been calling "numeric entities" (it looks like the [spec](https://www.w3.org/TR/xml11/#sec-references) calls them "character references"), which are the only ones I've encountered in wild plist files.

I believe a "character reference" is always a Unicode character, so the XML concrete syntax `&#38;` and the x-expression `38` are both representations of the character produced by `(integer->char 38)`. The transformation I'm proposing would just produce a variant of x-expressions without the  `valid-char?` case by converting them to strings and appending adjacent strings.

**Comment by LiberalArtist** [comment]
Interestingly,
```racket
(xml->xexpr
  (read-xml/element
    (open-input-string "<string>Gospel &amp; Religious</string>")))
```
evaluates to `'(string () "Gospel " "&" " Religious")`. I had expected it to produce `'(string () "Gospel & Religious")`.

I think both converting character references to strings and merging adjacent strings would be useful additions to `xml`, but this illustrates that they are really two separate features.
