### ISSUE TITLE
LD_LIBRARY_PATH is not taking effect

### ISSUE THREAD

**Issue by corpix** [racket/racket#2450]
Hello. I have an application which breaks when I try to run it like this `raco exe --gui app.rkt && ./app` with "SSL not available" error.

Sample source code:
```
~/playground λ cat libssl-load-bug.rkt
#lang racket/base
(require openssl)
(printf "ssl load error: ~a\n\n" ssl-load-fail-reason)
```

Environment(I use [NixOS](https://nixos.org)):
```
~/playground λ racket --version
Welcome to Racket v7.1.
~/playground λ echo $LD_LIBRARY_PATH

~/playground λ ls -la /usr/lib /lib
/lib: No such file or directory
/usr/lib: No such file or directory
```

Example:
```
~/playground λ raco exe --gui ./libssl-load-bug.rkt && ./libssl-load-bug
ssl load error: ffi-lib: couldn't open "libcrypto.so" (libcrypto.so: cannot open shared object file: No such file or directory)
```

`LD_LIBRARY_PATH` with correct openssl lib path should fix this, but it is not:
```
~/playground λ LD_LIBRARY_PATH=/nix/store/...-openssl-1.0.2q/lib ./libssl-load-bug
ssl load error: ffi-lib: couldn't open "libcrypto.so" (libcrypto.so: cannot open shared object file: No such file or directory)
```

It worked only with this `LD_LIBRARY_PATH` value(notice `:` after `=`):
```
~/playground λ LD_LIBRARY_PATH=:/nix/store/...-openssl-1.0.2q/lib ./libssl-load-bug
ssl load error: #f
```

It should work without colon in `LD_LIBRARY_PATH`.

**Comment by rmculpepper** [comment]
PR #2452 fixes the immediate problem, the mangled library search path. But I wonder if there is another problem behind it. The embedded DLL path is supposed to be present only in "cross-installation" mode (when `(find-cross-dll-dir)` is set). Is Racket getting confused into cross-installation mode incorrectly on NixOS?

**Comment by corpix** [comment]
> PR #2452 fixes the immediate problem, the mangled library search path. But I wonder if there is another problem behind it. The embedded DLL path is supposed to be present only in "cross-installation" mode (when `(find-cross-dll-dir)` is set). Is Racket getting confused into cross-installation mode incorrectly on NixOS?

I don't know what "cross-installation" mode is but `find-cross-dll-dir` is undefined for me in the REPL.
