### ISSUE TITLE
wrap-expr/c cannot be used to add contracts on expressions used in phases other than (syntax-local-phase-level)

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#2455]
It’s entirely possible for a macro to receive an expression that will eventually be evaluated at phase 1 or more, and it might be useful to protect that expression with a contract. However, simply using `wrap-expr/c` or `expr/c` naïvely does not work:

```racket
(define-syntax-parser print-compile-time-integer
  [(_ {~var e (expr/c #'exact-integer?)})
   #:do [(println (syntax-local-eval #'e.c))]
   #'(void)])

(print-compile-time-integer 42)
```
```
macro-arg/c: undefined;
 cannot reference an identifier before its definition
```

This makes sense—`wrap-expr/c` has no way of guessing where the expression will be used. However, it would be nice if `wrap-expr/c` provided an optional `#:phase` argument to control where the introduced bindings come from so that the phase can be explicitly specified.

**Comment by rmculpepper** [comment]
Having a macro produce code for different phases depending on an argument feels a little sketchy to me. I'm surprised and a little disturbed that it appears to be in the neighborhood of possible, using `syntax-shift-phase-level` and `local-require`. I didn't get everything working at once, and I don't want to spend much more time on this right now, but here's what I have so far: https://github.com/rmculpepper/racket/tree/b-phase-polymorphic-exprc

Practically, it's probably easier to support only the cases where the phase is either `(syntax-local-phase-level)` or `(add1 (syntax-local-phase-level))`.

**Comment by lexi-lambda** [comment]
I think you would probably want to use `syntax-local-lift-require` directly rather than `local-require` to avoid the problem where module that defines `local-require` itself isn’t instantiated at the appropriate phase, but yes, it’s a little bit evil. :) I’d probably be okay with a version that only works at phase 0 or 1.
