### ISSUE TITLE
racketcs fails to build deinprogramm

### ISSUE THREAD

**Issue by pmatos** [racket/racket#2460]
I was building racket and racketCS from HEAD and was quite surprised to get only in the racketCS build the following error (this is in the package build):
```
/home/pmatos/racket-builds/racketCS-debug/racket/share/pkgs/deinprogramm/deinprogramm/sdp/tests/signature.rkt:294:55: kar: Selektor ist kein Bezeichner  in: (kar a)  
compilation context...:   
/home/pmatos/racket-builds/racketCS-debug/racket/share/pkgs/deinprogramm/deinprogramm/sdp/tests/signature.rkt   
/home/pmatos/racket-builds/racketCS-debug/racket/share/pkgs/deinprogramm/deinprogramm/sdp/tests/run-signature-tests.rkt  
context...:   
do-raise-syntax-error   
loop   
/home/pmatos/racket-builds/racketCS-debug/racket/share/pkgs/deinprogramm/deinprogramm/sdp/record.rkt:269:2   
apply-transformer52   
dispatch-transformer41   
loop   
for-loop   
finish-bodys   
lambda-clause-expander   
for-loop   
for-loop   
finish-bodys   
for-loop   
for-loop   
finish-bodys   
for-loop
```

The build command line looks like:
`time make CONFIGURE_ARGS_qq='CFLAGS="-O0 -g3 -Wall" --enable-ubsan --disable-strip' CPUS=4 cs 2>&1 | tee build.log`

**Comment by mflatt** [comment]
Which checksum of the "deinprogramm" package do you have installed, as reported by `racocs pkg show deinprogramm`?

I see that there was a sequence of commits to that package in the last day — with several that say "unbreak" — and I wonder whether you might have ended up with a broken intermediate version in just the CS build. The latest, 30f44328a8ba44, builds ok for me.

**Comment by pmatos** [comment]
Might have a broken version...
```
 ✗ racket/bin/racocs pkg show deinprogramm
Installation-wide:
 Package[*=auto]  Checksum              Source
 deinprogramm*    e91fd80ede382f1b3...  catalog...inprogramm
User-specific for installation "development":
 [none]
```

I have an old version... so I need to update. What is slightly confusing is that I cloned and built HEAD as recently as a couple of days ago so it doesn't make sense my `deinprogramm` is from Jan 12, right?

**Comment by mfelleisen** [comment]
I alerted Mike directly within minutes of his first commits, and he fixed them quickly.

**Comment by pmatos** [comment]
@mfelleisen thanks 
@mflatt was right. i was trying to build an old version it seems. All good now. Will close.
