### ISSUE TITLE
Possible leak for argument

### ISSUE THREAD

**Issue by pmatos** [racket/racket#2467]
I wanted to confirm my suspicions here before submitting a PR.

Is it the case that here:
https://github.com/racket/racket/blob/f8a130851f1541b1a89d4d75e79a8b36bd50d3f3/racket/src/rktio/rktio_fs.c#L920

argument `filename` is overwritten and the memory it pointed to leaks? Or is filename somehow under GC and the GC will free it during the next pass?

In general, in the rktio layer, are all arguments under GC? I assume not everything is under GC because I see calls to `free`.

**Comment by samth** [comment]
rktio is not processed to add GC -- for example it's also used in the Chez implementation.

**Comment by pmatos** [comment]
Thanks @samth
