### ISSUE TITLE
bug report : ffi/com com-get-property   -  chain properties  property name can only be string

### ISSUE THREAD

**Issue by nonamecor** [racket/racket#2470]
In ffi/com, com-get-property function when use a path of properties to return the last property.  all property names had to be a string.  property with argument get wrong message. 

code example  get excel com object

#lang racket
(require ffi/com)
(require syntax/parse)
(define xl (com-create-instance "Excel.Application"))
(com-set-property! xl "visible" #t)
(define wkbs (com-get-property xl "workbooks"))
(define wkb (com-invoke wkbs "add"))
(define wkb2 (com-get-property wkbs '("Item" 1) "Name"))
wrong message 
com-get-property: expected argument of type <string>; given: '("Item" 1)
The reason is the follow-chain function in com.rkt forces the property names to be string.

**Comment by gus-massa** [comment]
If I understand correctly, the correct error message should be

_com-get-property: expected argument of type **string?**; given: '("Item" 1)_

Is this correct?

**Comment by mflatt** [comment]
@nonamecor - thanks for the report!

@gus-massa - no, `<string>` in the error message (still old style) got eaten by Markdown. The issue is that a value other than a string should be allowed.
