### ISSUE TITLE
racketcs failures using sham LLVM interface

### ISSUE THREAD

**Issue by samth** [racket/racket#2493]
Steps to reproduce:

- `raco pkg install https://github.com/rjnw/rcf.git`
- `raco pkg install https://github.com/rjnw/sham.git`
- `racket -l sham/test/automata` # works
- `racketcs -l sham/test/automata` # usually fails

A few sample error messages:

This one is the most common
```
invalid memory reference.  Some debugging context lost
  context...:
   condition->exn
   dynamic-wind
   call-with-values
   body of "/home/samth/work/sham/test/automata.rkt"
   for-loop
   run-module-instance!125
   perform-require!78
   namespace-require+
   #%for-each
```

I've also seen:
```
bytes->string/utf-8: byte string is not a well-formed UTF-8 encoding
  byte string: #"\36\256@"
  context...:
   raise-arguments-error
   /home/samth/work/sham/private/llvm/ffi/execution-engine.rkt:45:2
   /home/samth/work/sham/private/init.rkt:44:0: module-initialize-mcjit!4
   /home/samth/work/sham/private/jit-utils.rkt:22:0: compile-sham-module!8
   call-with-values
   body of "/home/samth/work/sham/test/automata.rkt"
   for-loop
   run-module-instance!125
   perform-require!78
   namespace-require+
   #%for-each
```

**Comment by mflatt** [comment]
One quick question, first: Does the example involve uses of `ffi/unsafe`? If so, are there uses of `_bytes` to pass a byte string, where the foreign callee expects a nul terminator?

**Comment by samth** [comment]
The example very much uses the FFI. @rjnw can you answer the second question?

**Comment by samth** [comment]
From a quick look, there are only two uses of `_bytes`, both in `private/llvm/ffi/core.rkt` and both of them seem to be returned from the foreign callee. However, `LLVMGetModuleIdentifier` looks a little weird:

http://llvm.org/doxygen/group__LLVMCCoreModule.html#ga4198521497ad2b9558ceae36c3f893ce

Binding code is:

```
(define-llvm LLVMGetModuleIdentifier
  (_fun LLVMModuleRef (len : (_ptr o _size)) -> (ident : _bytes) ->
        (vector ident len)))
```

**Comment by rjnw** [comment]
The error about `bytes->string/utf-8` is coming from the function `LLVMCreateMCJITCompilerForModule` in the file execution-engine.rkt. The type of that function is 
```
(define-llvm LLVMCreateMCJITCompilerForModule
  (_fun (ee : (_ptr o LLVMExecutionEngineRef))
        (mod : LLVMModuleRef)
        (options : (_ptr i _LLVMMCJITCompilerOptions))
        (len : _size = (ctype-sizeof _LLVMMCJITCompilerOptions))
        (err : (_ptr o _string))
        -> (status : LLVMBool)
        -> (values ee status err)))
```
The string is coming from LLVM as an error message. The C-type for this function is here:
http://llvm.org/doxygen/group__LLVMCExecutionEngine.html#gaa97dff3ed910ce2e0fc7c96b50b1c897

**Comment by mflatt** [comment]
It looks like Racket CS is not zeroing out the memory for `(malloc 'raw ...)`, and that affects the use of `(_ptr o _string)`. I'll push a repair that may avoid the error here.

It's not clear to me that you can really rely on `LLVMCreateMCJITCompilerForModule` to leave the `err` argument alone for a non-error, but maybe some convention about LLVM allows that assumption. Usually, for a C API of this shape, it's better to get a pointer back and only convert it to a string if the return value indicates an error.

FWIW, using `_LLVMMCJITCompilerOptions-pointer` is more efficient than `(_ptr i _LLVMMCJITCompilerOptions)` unless you really mean to create a copy.

**Comment by samth** [comment]
With that commit, the program now seems to work consistently.
