### ISSUE TITLE
Can't require db, pict, etc in Minimal version.

### ISSUE THREAD

**Issue by cchuang0425** [racket/racket#2502]
I can't require libraries like db, pict, etc. when using minimal version.

I'm trying to build a web using Racket, but when I used the minimal version for porting,
I could not require "db", even install independently from official file or using `yum install` in Fedora.

How do I configure Minimal Version, or just using Full Version?

**Comment by mflatt** [comment]
Use `raco pkg install` to install additional packages. By default, packages are installed to a use-specific space, so use `-i` to put packages with the Racket installation (which may require permissions to write there.) To keep the installation as small as possible, try using packages with `-lib` in the name, such as `raco pkg install pict-lib`.

**Comment by cchuang0425** [comment]
Thank you, it works for me.
