### ISSUE TITLE
sigsev on place-channel-put with struct containing empty hash

### ISSUE THREAD

**Issue by MichaelMMacLeod** [racket/racket#2504]
## Describe the bug
The `racket` executable crashes when `place-channel-put` is supplied an instance of a (prefab) `struct` provided by `contract-out` with at least one field filled by `(hash)`.

## Steps to reproduce
Put the following in a file, say `test.rkt`:
```racket
#lang racket

(module other-module racket
  (provide (contract-out (struct the-struct ([value any/c]))))
  (struct the-struct (value) #:prefab))

(require 'other-module)

(define the-place
  (place channel (place-channel-get channel)))

(place-channel-put the-place (the-struct (hash)))
```
Then load the file with `racket`
```sh
$ racket test.rkt
SIGSEGV MAPERR si_code 1 fault on addr (nil)
[1]    4565 abort (core dumped)  racket test.rkt
```

## Expected behavior
Racket should properly send the `struct` to the `place` and not crash or throw an error.

## Racket version
Tested with both v7.2 and v7.2.0.6.

## Operating System
Linux x86_64 v4.20.8

## Additional context
Possibly related: https://github.com/racket/racket/issues/2298
https://github.com/racket/racket/issues/2298 provides a workaround which involves taking the hash maps out of the equation by `serialize` and `deserialize`.

#### Putting values in the `hash` instead of leaving it empty throws an error (which it shouldn't) instead of crashing
test.rkt:
```racket
#lang racket

(module other-module racket
  (provide (contract-out (struct the-struct ([value any/c]))))
  (struct the-struct (value) #:prefab))

(require 'other-module)

(define the-place
  (place channel (place-channel-get channel)))

(place-channel-put the-place (the-struct (hash 'key 'value)))
```
```sh
$ racket test.rkt 
hash-iterate-key: contract violation
  expected: hash?
  given: 0
  argument position: 1st
  other arguments...:
   0
  context...:
   "/home/michael/projects/debug/test.rkt": [running body]
   temp37_0
   for-loop
   run-module-instance!125
   perform-require!78
```

**Comment by mflatt** [comment]
Thanks for the report!

**Comment by pmatos** [comment]
Unfortunately #2298 didn't get fixed. I will try again to spend some time fixing it.
