### ISSUE TITLE
The --unused-pkg-deps flag doesn't seem to understand test dependencies

### ISSUE THREAD

**Issue by jackfirth** [racket/racket#2511]
When I run the `raco setup --unused-pkg-deps` with Racket 7.2, the tool doesn't seem to correctly handle packages in `build-deps` that I use in test submodules. I put together a [gist](https://gist.github.com/jackfirth/8a0188b07acec00c0fe6b971f34d20c3) containing the full list of all the unused dependencies reported by the tool on my installation. I know this particular section of the output is wrong:
```
raco setup: unused dependencies detected
  for package: "rebellion"
  on packages:
   "testing-util-lib"
   "rackunit-lib"
```
This is the output for my [`rebellion`](https://github.com/jackfirth/rebellion/blob/master/info.rkt) package, which uses rackunit in test submodules and has `rackunit-lib` as a `build-deps` dependency. Also, that package doesn't explicitly depend on `testing-util-lib` anywhere so I'm guessing the tool reports errors for transitive dependencies it thinks are unused in addition to direct dependencies.

**Comment by mflatt** [comment]
Dependency checking does not consider files that are not compiled, so I think the issue is that the "info.rkt" file in "rebellion" has
```
(define compile-omit-paths
  (list "private"))
```

**Comment by jackfirth** [comment]
Oops, silly me. Removing that fixes it.

The reason I had that in the first place was because I had a utility module in `rebellion/private` that was only used by my scribble docs. That module caused `raco setup` to report that my package now depends on `scribble-lib` at runtime. I wanted a way for `raco setup` to figure out that my public API surface is only the modules in `rebellion` and not in `rebellion/private`, and to use that to figure out the dependency checking. I think `compile-omit-paths` probably isn't a good way to achieve that. For now what I've done is put my scribble utility module in a `doc` submodule, so `raco setup` assumes its for documentation only.
