### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by MarcKaufmann** [racket/racket#2518]
The following link in the documentation seems broken and I couldn't figure out where the tests actually are for 2htdp:

https://github.com/racket/racket/blob/5bb837661c12a9752c6a99f952c0e1b267645b33/pkgs/racket-doc/scribblings/style/testing.scrbl#L19

I am not sure that the docs are wrong on claiming that most test suites still live in /collects/tests/. That seems to be generally wrong, no?

**Comment by samth** [comment]
That test directory is at: https://github.com/racket/htdp/tree/master/htdp-test/2htdp
Very little now lives in "collects" (the style guide was mostly written before the package system).

**Comment by MarcKaufmann** [comment]
This also means that the first part of the document should be updated to say that tests are now included ... where usually? Right now it claims /collects/tests. Shall I submit a new issue for someone who knows to figure it out or (if you tell me where test suites tend to live) submit a PR myself?

**Comment by samth** [comment]
I think the document needs a significant update (for example, the `TESTME.txt` convention is not actually used). Probably @mfelleisen, the original author, is the one to do it. There's not a particular place where test suites tend to live these days.

**Comment by MarcKaufmann** [comment]
OK, I'll consider my part done then, and this only being about fixing the
link.
