### ISSUE TITLE
Path no longer up to date, and should be link

### ISSUE THREAD

**Issue by MarcKaufmann** [racket/racket#2520]
In "Units of Code" in the Racket Style guide, there is the following line:

https://github.com/racket/racket/blob/5bb837661c12a9752c6a99f952c0e1b267645b33/pkgs/racket-doc/scribblings/style/unit.scrbl#L326

It claims that in "collects/setup/scribble" all functions use latex-dest. I couldn't find this file in collects/setup/, there was no scribble file. Even if there is, it would be better to turn it into a link to the actual file. I searched for latex-dest, and maybe the file it referred to is "racket/pkgs/racket-index/setup/scribble.rkt", although I really don't understand the point being made about latex-dest, since nothing named latex-dest is exported. However that's not the point of this issue.

Edit: Let me know if I should *not* add issues for these kinds of things on GitHub, but first check on an email list or what not (I did spend 5-10 minutes searching around).

**Comment by samth** [comment]
That file lives here: https://github.com/racket/racket/blob/master/pkgs/racket-index/setup/scribble.rkt
The best argument to `filepath` would probably be `pkgs/racket-index/setup/scribble.rkt`.

**Comment by MarcKaufmann** [comment]
Is there a reason for it being a filepath, rather than a link to it directly?

**Comment by samth** [comment]
A link seems like a good idea to me.
