### ISSUE TITLE
Blame seems wrong for `override` clauses in class/c

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#2531]
Here’s a small program, modified very slightly from the examples in the documentation for `class/c`:

```racket
#lang racket

(module a racket
  (provide woody2+override/c%)

  (define woody%
    (class object%
      (define/public (draw who)
        (format "reach for the sky, ~a" who))
      (super-new)))

  (define/contract woody2+override/c%
    (class/c (override [draw (->m symbol? string?)]))
    (class woody%
      (inherit draw)
      (define/public (draw2 a b)
        (string-append (draw a)
                       " and "
                       (draw b)))
      (super-new))))
 
(module b racket
  (require (submod ".." a))

  (provide woody2+broken-draw%)

  (define woody2+broken-draw%
    (class woody2+override/c%
      (define/override (draw x)
        'not-a-string)
      (super-new))))

(require 'b)
(send (new woody2+broken-draw%) draw2
      'evil-dr-porkchop
      'zurg)
```

It fails with the following error:

```
draw: broke its own contract
  promised: string?
  produced: 'not-a-string
  in: the range of
      the draw method in
      (class/c
       (override (draw (->m symbol? string?))))
  contract from: 
      (definition woody2+override/c%)
  contract on: woody2+override/c%
  blaming: (anonymous-module a)
   (assuming the contract is correct)
  at: unsaved-editor:12.19
```

This is a positive violation, as indicated by the “broke its own contract” message, and it blames module `a`. But module `a` isn’t at fault, module `b` is.

I imagine this was just a small oversight in the implementation: `override` contracts are a little different from other `class/c` contracts, since instead of being a contract between a method in the contracted class and some other party adding obligations to the contracted class itself, it’s effectively a contract on overriding methods in *subclasses*, and it’s the subclasses that accept obligation to fulfill (the positive parts of) the contract. So a `blame-swap` call is probably missing someplace.

Therefore, I think blame in `override` contracts needs to be swapped. The negative party for `override` contracts represents the subclass, and the positive party represents the contracted class, but currently this seems to be backwards.

**Comment by rfindler** [comment]
My initial reaction to this was "yes! right!" but then I put the contract into a `contract-out` in module `a` and I get the correct blame, so what I really think is that `define/contract` is confusing.

It may make sense to try to improve the wording of blame for `define/contract`-based contracts to make clear what both sides of the boundary are somehow, as I think that would have made it clear that this particular setup could never have blamed `b` as `b` wasn't a party to the contract.

**Comment by lexi-lambda** [comment]
Robby is right: the proper party is blamed when `contract-out` is used. But I was confused, because the negative party *is* clearly being blamed, but the contract violation still says “broke its own contract”. What gives?

I think I have the answer: `class/c` calls `blame-add-context` with an `#:important` argument, and it provides the name of the method. But, as it happens, it does this *after* swapping the blame for `override` (and `inner`) contracts, which the contract system interprets to mean “the important party is the negative party, so report ‘broke its own contract’ messages for negative violations, instead”. This is really subtle: the documentation for `blame-add-context` does not currently describe that behavior, so it’s easy to get wrong.

In any case, this bug is much less catastrophic than I thought, but I think the right fix for the smaller problem is to call `blame-add-context` *before* swapping the blame. That should make the contract error actually say “contract violation” for negative violations and “broke its own contract” for positive violations.

**Comment by mfelleisen** [comment]
@rfindler @lexi-lambda 

Keep in mind that 
```
(provide
  (contract-out
    (woody2+override/c% (class/c (override [draw (->m symbol? string?)])))))

(define woody2+override/c%
   (class woody%
      (inherit draw)
      (define/public (draw2 a b)
        (string-append (draw a) " and " (draw b)))
      (super-new)))
```
is not the same as 
```
(provide woody2+override/c%)

(define/contract woody2+override/c%
   (class/c (override [draw (->m symbol? string?)]))
    (class woody%
      (inherit draw)
      (define/public (draw2 a b)
        (string-append (draw a)
                       " and "
                       (draw b)))
      (super-new)))
```
(which I assume is the the transformation Robby is talking about). 

The second variant sets up another contract boundary between `woody2+override/c%` and module `a`, while the considers both class definitions to be within the same contract region. 

Here is the proper analog and then module `a` is still blamed: 
```
 (module inner-a racket
    
    (provide
     (contract-out
      (woody2+override/c% (-> any/c (class/c (override [draw (->m symbol? string?)]))))))

    (define (woody2+override/c% woody%)
      (class woody%
        (inherit draw)
        (define/public (draw2 a b)
          (string-append (draw a)
                         " and "
                         (draw b)))
        (super-new))))

  (require (prefix-in inner: 'inner-a))
  (define woody2+override/c% (inner:woody2+override/c% woody%))
```
[Apologies, I couldn't figure out how to import woody% into the inner module, export the derived class with a contract and re-export it again from the outer `a`.) 

Now you can see why this is *not* a bug. As far as `inner-a` is concerned, the blamed method  `draw` flows into `woody2+override/c%` via the surrounding module `a`. Hence when things go wrong with it, the only party it has to blame is `a` -- it can't possibly know about `b`. 

`define/contract` is a bit subtle in this way and often misunderstood.
