### ISSUE TITLE
check-requires suggests dropping syntax/parse

### ISSUE THREAD

**Issue by sorawee** [racket/racket#2546]
Consider `a.rkt`

```
#lang racket

(require (for-syntax syntax/parse))

(define-syntax (foo stx)
  (syntax-parse stx
    [(_) #'1]))

(foo)
```

`a.rkt` obviously uses `syntax/parse`, but `raco check-requires a.rkt` outputs:

```
(file "a.rkt"):
DROP syntax/parse at 1
```

**Comment by pmatos** [comment]
Can repro on 7.2. Documentation for `check-requires` says[1]:
```
Due to limitations in its implementation strategy, check-requires occasionally suggests dropping or bypassing a module that should not be dropped or bypassed. The following are typical reasons for such bad suggestions:

* The module’s invocation has side-effects. For example, the module body may update a shared table or perform I/O, or it might transitively require a module that does. (Consider adding the module to the whitelist.)

* Bindings from the module are used in identifier comparisons by a macro, such as appearing in the macro’s “literals list.” In such cases, a macro should annotate its expansion with the 'disappeared-use property containing the identifier(s) compared with its literals; however, most casually-written macros do not do so. On the other hand, macros and their literal identifiers are typically provided by the same module, so this problem is somewhat uncommon.
```

Not sure which of these issues `syntax-parse` tickles but I guess @rmculpepper would probably be able to add something to this.

[1] https://docs.racket-lang.org/macro-debugger/index.html#(def._((lib._macro-debugger%2Fanalysis%2Fcheck-requires..rkt)._check-requires))

**Comment by rmculpepper** [comment]
Thanks for the report! As far as I can tell, the new expander is not sending a `resolve` event during pass 1 of internal definition context expansion. There might be other factors, like the rename-transformers introduced by `lazy-require-syntax`, but I'm not sure yet.

Here's a minimal example that shows the bad DROP recommendation:

    (module use-sp-bad '#%kernel
      (#%require syntax/parse)
      (lambda () (syntax-parse '())))

And here's one that doesn't:

    (module use-sp-ok '#%kernel
      (#%require syntax/parse)
      (values (syntax-parse '())))

I think the fix will involve going through and re-syncing (and hopefully simplifying) the expander instrumentation and the events parser, but I probably won't get to that for a couple weeks.

**Comment by sorawee** [comment]
This is fixed. Thanks, @rmculpepper!
