### ISSUE TITLE
typed/racket: can't cast dynamically required function

### ISSUE THREAD

**Issue by MichaelMMacLeod** [racket/racket#2559]
### What version of Racket are you using?
Racket v7.2

### What platform are you using?
Linux x86-64

### What program did you run?
test.rkt:
```racket
#lang typed/racket

(module other-module typed/racket
  (provide f)
  (: f : Integer -> Integer)
  (define (f x)
    (* x 2)))

(define g (dynamic-require '(submod "test.rkt" other-module) 'f))

((cast g (-> Integer Integer)) 3)
```
### What should have happened?
The `cast` should not throw an error message, or, there should be some other way to load and then use a function from a different module at run-time in typed racket. (I don't think there is a way to do that at the moment, please correct me if it is possible).

### If you got an error message, please include it here:
```racket
contract violation
  Attempted to use a higher-order value passed as `Any` in untyped code: #<procedure:f>
  in: Any
  contract from: typed-world
  blaming: cast
   (assuming the contract is correct)
```
### Extra info
This came from the stackoverflow post here https://stackoverflow.com/questions/55321755/applying-cast-to-dynamically-required-function-in-typed-racket

**Comment by AlexKnauth** [comment]
Issues for Typed Racket should go on the `typed-racket` repository:
https://github.com/racket/typed-racket

**Comment by samth** [comment]
It's really fine to have it here, and I can transfer it as well.
