### ISSUE TITLE
DrRacket crash due to Cairo assertion failure

### ISSUE THREAD

**Issue by LiberalArtist** [racket/racket#2568]
Immediately after pressing "Run" in DrRacket, I encountered a crash with the message: `Assertion failed: (CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&cr->ref_count)), function cairo_destroy, file cairo.c, line 305.` I can't reproduce it (so far), and it's not immediately clear whether to blame Racket or Cairo, but [here is the crash report](https://github.com/racket/racket/files/3016460/crash-report.txt) in case it's useful.

(The only dependencies of the file I was running were `#lang racket` and `syntax/parse/define`, so it doesn't seem likely that the problem was triggered by the program being evaluated.)

**Comment by mflatt** [comment]
Not sure what happened here, but there have been many relevant changes since (including the shift to CS), so let's time this one out.

**Comment by tgbugs** [comment]
For the record we had the same error happen today on racket cs 8.13 running on macos Tahoe 26.1 on an M2 macbook air. It seems that this issue is still present.

```
Assertion failed: (CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&cr->ref_count)), function cairo_destroy, file cairo.c, line 524.
```

Some additional system information.
```
  System Software Overview:   System Version: macOS 26.1 (25B78)
   Kernel Version: Darwin 25.1.0
```
