### ISSUE TITLE
contract wrapping with mandatory keywords is not procedure? in racketcs

### ISSUE THREAD

**Issue by samth** [racket/racket#2569]
```
#lang racket/base
(require racket/contract)
(define (group-rows #:group x) 1)
(procedure? (contract (->* (#:group any/c) any/c) group-rows #t #f))
```

Prints #t on Racket and #f on RacketCS.

**Comment by rfindler** [comment]
Here's the thing that causes the contract system to go astray: this program should produce `#t` not `#f`.

```
#lang racket/base

(define (group-rows #:group x) 1)

(define-values (impersonator-prop:contracted 
                has-impersonator-prop:contracted? 
                get-impersonator-prop:contracted)
  (make-impersonator-property 'impersonator-prop:contracted))

(procedure?
 (chaperone-procedure group-rows
                      (λ (#:group x) x)
                      impersonator-prop:contracted 2))
```

**Comment by jeapostrophe** [comment]
I got such great feelz reading this. Great working together to find the issue and make it smaller to test. <3

**Comment by samth** [comment]
Here's a reduced version that is a single file: https://gist.github.com/1aec5a60b5f9af82c4d0df9a8384b52f

**Comment by samth** [comment]
Running creduce on that file found another bug:

```
(module a '#%kernel
 (define-values   (struct:keyword-procedure mkkwproc keywordprocedure? keywordprocedureref keywordprocedureset)   (make-struct-type    'procedure
#f
   4    0 ))  (define-values   (b-arity-string)   0)  (define-values   (c d ? e !)   (make-struct-type    'procedure
   struct:keyword-procedure
   0
   0
#f
   (list (cons prop:arity-string b-arity-string) )))
     (print   0))
```

has an error on racket but not on racketcs.

**Comment by samth** [comment]
And here's a much-reduced version with the actual bug: https://gist.github.com/d90f9e608f4acc3deaa4578b21d2d5c7

**Comment by mflatt** [comment]
Oops – I didn't mean to give away the repair by pushing to a branch in my repo. This would have been a good data point for whether bugs in Racket CS can be fixed by others. But I'll push the repair.
