### ISSUE TITLE
The value passed to prop:procedure is stripped of chaperones/impersonators

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#2574]
I find this program surprising:

```racket
#lang racket

(struct foo ([val #:mutable])
  #:property prop:procedure
  (λ (self) (foo-val self)))

(define the-foo
  (impersonate-struct
   (foo 'original)
   foo-val
   (λ (self val) 'impersonated)
   set-foo-val!
   (λ (self val) (error "cannot set!"))))

(foo-val the-foo) ; => 'impersonated
(the-foo)         ; => 'original
```

I would expect both calls to produce `'impersonated`, but they do not. I find this surprising because, as far as I can tell, it makes `prop:procedure` somewhat magical. For other structure type properties I define, there’s no way to achieve the same behavior. If I change the program to use my own property, I get different results:

```racket
#lang racket

(define-values [prop:my-procedure my-procedure? my-procedure-ref]
  (make-struct-type-property 'my-procedure))

(define (my-app f . args)
  (apply (my-procedure-ref f) f args))

(struct foo ([val #:mutable])
  #:property prop:my-procedure
  (λ (self) (foo-val self)))

(define the-foo
  (impersonate-struct
   (foo 'original)
   foo-val
   (λ (self val) 'impersonated)
   set-foo-val!
   (λ (self val) (error "cannot set!"))))

(foo-val the-foo) ; => 'impersonated
(my-app the-foo)  ; => 'impersonated
```

This seems counter to the Racket philosophy, which, if I understand correctly, tries to avoid blessing things in the core if at all possible. So I’m inclined to think this is just a bug, but maybe there’s some rationale I don’t see?

**Comment by rfindler** [comment]
In my way of thinking, the function that you put into the prop:procedure is "inside" the impersonator, not outside. The first code segment's response (`'impersonated`, followed by `'original`) seems right to me.

I agree that this means that `#%app`, `prop:procedure` and impersonators must be cooperating and if you wanted to replace that layer, you'd need to also replace all three, not just two. But I don't see this as a compelling argument that the current setup is counter to the "don't bless things in the core" (in a deep/important way).

**Comment by lexi-lambda** [comment]
At, first, I agreed with you. The idea that the property is “inside” the impersonator seems to make sense. But after thinking about it more, I’m no longer sure. Contracts shouldn’t be checked if the code in question is inside the *contract boundary*, but there’s no reason that the property code has to be inside the boundary. The boundary could be imposed by a different party, like this:

```racket
#lang racket

(module a racket
  (provide (struct-out foo))
  (struct foo (value)
    #:property prop:procedure
    (λ (self) ((foo-value self) #f))))

(module b racket
  (require (submod ".." a))
  (provide (contract-out
            [make-a-foo (-> (struct/c foo (-> integer? integer?)))]))
  (define (make-a-foo)
    (foo only-ints-please))
  (define (only-ints-please x)
    (* (add1 x) 2)))
```

In this program, module `b` puts a `struct/c` contract on the return value of `make-a-foo` to protect itself against clients misusing the value it put inside `foo`, which is a function that should only be called with integer arguments. I think it’s reasonable to expect that such a contract is sufficient to guarantee that, right? But the contract doesn’t guarantee it, since `prop:procedure` strips contracts off of values:

```racket
> (require 'b)
> ((make-a-foo))
add1: contract violation
  expected: number?
  given: #f
```

Now, there’s an argument that I think one can make here, which is that the above example is not convincing. After all, the same internal/external distinction is made by classes. If we replace the `foo` struct with a class with `(init-field value)`, and we change `make-a-foo` to produce `(new foo% [value only-ints-please])`, there *is no contract* that module `b` can put on the result of `make-a-foo` to protect against internal misuses of the `value` field. But `object/c` is very explicit about this internal/external distinction (as is the class system in general), whereas `struct/c` is not, and people don’t normally think about that kind of distinction in the context of structs (since, as far as I’m aware, it only happens with `prop:procedure` and isn’t documented).

To prove my point, it’s possible to create Typed Racket unsoundness using this oddity. This program segfaults:

```racket
#lang racket

(module untyped racket
  (provide (struct-out foo))
  (struct foo (value)
    #:property prop:procedure
    (λ (self) self)))

(module typed typed/racket
  (require/typed
   (submod ".." untyped)
   [#:struct foo ([value : (-> (Pair Integer Integer) Integer)])])
  (provide the-bar)
  (struct (A) bar foo ())
  (define the-bar ((inst bar Nothing) (λ (v) (car v)))))

(require 'untyped
         'typed)

((foo-value (the-bar)) #f)
```

(The polymorphic struct is necessary to convince TR to generate a `struct/c` contract, since otherwise it generates no contract at all and falls victim to the more egregious racket/typed-racket#815.)

In any case, obviously none of this discredits the perspective you gave, so maybe the answer really is “that’s just how structs work”. But if it is, I think it’s a confusing and unintuitive design decision!

**Comment by gus-massa** [comment]
I imagine that for "aplicative vectors" (like in clojure or qbasic) in this example:

    #lang ???
    (define v (something (vector 1 2 3)))
    (vector-ref v 1)
    (v 1)

the user expect that `(v 1)` is 100% equivalent to `(vector-ref v 1)`.

(@greghendershott How does this work currently in rackjure?)

(Also, what happens in the original example if you use `impersonate-procedure` instead of `impersonate-struct`?)

**Comment by greghendershott** [comment]
@gus-massa rackjure [uses `#app` for applicable dicts](https://github.com/greghendershott/rackjure/blob/master/rackjure/app.rkt#L73).

**Comment by mflatt** [comment]
Another point in favor of changing the behavior is that it makes it more consistent with using a field index as `prop:procedure`, as in

```
(struct bar (proc)
  #:property prop:procedure 0)

(define orig-bar (bar (lambda () 'ok)))

(define the-bar
  (chaperone-struct
   orig-bar
   bar-proc
   (lambda (self val) (log-error "chaperoned") val)))

(the-bar) ; logs "chaperoned"
```

The implementation goes out of its way to remember the original struct to make this work, and I think we probably needed the behavior for a specific application.

When I make the change, the chaperone tests and contract tests all still pass. That's not definitive, but it's another bit of positive evidence.

So, between the rationale that @lexi-lambda provides, the TR crash, consistency with field-index `prop:procedure`, and the lack of contradictory tests in the basic test suites, I'm inclined to try out this change.

The implementation in Racket CS is the kind of thing that looks straightforward once you have the answer. There's a loop that deals with `prop:procedure`, and there's a loop that deals with procedure impersonators, and those loops just have to be the same thing (explicitly mutually recursive) to carry the right "self" structure through. This is the same "self" that the impersonator loop already needed to support `chaperone-procedure*`.
