### ISSUE TITLE
Reading a FIFO file on macOS never produces #<eof>

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#2577]
Reading from FIFO files doesn’t seem to work properly in recent versions of Racket, at least on macOS 10.13.6. To demonstrate, here are two programs that print individual characters from stdin to stdout, one in C and the other in Racket:

```c
// test.c
#include <stdio.h>

int main() {
  int c;
  while ((c = getchar()) != EOF) {
    printf("%c\n", c);
  }
}
```
```racket
;; test.rkt
#!/usr/bin/env racket
#lang racket

(for ([c (in-producer read-char eof)])
  (displayln c))
```

These two programs ought to do the same thing, and normally, they do:

```sh
$ echo hello | ./test
h
e
l
l
o


$ echo hello | ./test.rkt
h
e
l
l
o


```

But if we indirect the I/O through a FIFO file, then the C program behaves the same way, but the Racket program hangs forever:

```sh
$ mkfifo some.fifo
$ echo hello > some.fifo & ./test < some.fifo
[1] 22258
h
e
l
l
o


[1]+  Done                    echo hello > some.fifo
$ echo hello > some.fifo & ./test.rkt < some.fifo
[1] 22260
h
e
l
l
o


# hangs forever until manually killed
^Cuser break
  context...:
   /private/tmp/test.rkt:4:0: for-loop
   "/private/tmp/test.rkt": [running body]
   temp37_0
   for-loop
   run-module-instance!125
   perform-require!78
[1]+  Done                    echo hello > some.fifo
```

Interestingly, this program appears to have once worked, but it’s been broken for a long time. The most recent version of Racket that handles it correctly appears to be Racket v6.3.

**Comment by mflatt** [comment]
It looks like I changed the configure script between v6.3 and v6.4 to enable the use of `poll` instead of `select` on Mac OS. And maybe https://stackoverflow.com/questions/591826/it-really-looks-like-os-x-has-a-bug-when-using-poll-on-a-named-pipe-fifo is still true.
