### ISSUE TITLE
raco reproducible builds

### ISSUE THREAD

**Issue by willghatch** [racket/racket#2601]
`raco setup` for packages is not [reproducible](https://reproducible-builds.org/), at least when run with multiple cores.

Recently someone made a [package of Rash for OpenSuse](https://build.opensuse.org/package/show/openSUSE:Factory/rash).  The OpenSuse team is trying to improve their reproducible build status, so they have noticed that the build is not reproducible.

Here is the issue raised in the Rash repository: https://github.com/willghatch/racket-rash/issues/52

Granted, macros may do all sorts of non-reproducible stuff, but in the common case where they don't it would make sense for `raco setup` to produce identical `.dep` and `.zo` files, at least for the same install directory, architecture, etc.

**Comment by samth** [comment]
I think they already do what you want, at least in most cases for code only using `#lang racket`. The most likely sources of non-reproducibility are hash table traversal order and `gensym` somewhere in libraries used by `rash`.

**Comment by willghatch** [comment]
Ah, that makes sense!  Sorry about this, then.

**Comment by willghatch** [comment]
And sure enough, I used a gensym for some reason...  I hadn't thought of gensym when I was thinking of what could cause macros to not be reproducible before posting this.

**Comment by jackfirth** [comment]
This issue is good evidence that we need stronger wording in the docs for `gensym` to discourage macro authors from using it (in favor of `generate-temporary` / `generate-temporaries` or `make-syntax-introducer`).

**Comment by willghatch** [comment]
While I didn't see it before opening this issue, I've now also noticed https://github.com/racket/racket/issues/1979 which is related.
