### ISSUE TITLE
Local Racket documentation doesn't work in Safari

### ISSUE THREAD

**Issue by tov** [racket/racket#2603]
The local documentation system isn’t working in Safari. In particular:

 - I can load the local index `file:///$HOME/Library/Racket/7.2/doc/search/index.html`, but searching the documentation produces no results.
 - The links from the index page, such as “Getting Started” and “Racket Cheat Sheet,” all produce a Safari error: `Safari can't open the page. The error is: ”The operation couldn’t be completed. Operation not permitted” (NSPOSIXErrorDomain:1)`. However, if I right click and copy one of those links, I get the path of the correct file, which exists, and if I paste it in the address bar then Safari can load it.
 - When I put the cursor inside `sqrt` in DrRacket (in a BSL buffer) and press F1, Safari attempts to load `file:///$HOME/Library/Racket/7.2/doc/search/search-context.html?q=sqrt&hq=O%3A%7B%20L%3Alang%2Fhtdp-beginner%20T%3Ateachpack%20T%3Apicturing-programs%20%20%7D&label=Beginning%20Student`, which results in a blank window. If I remove the `?` and everything after, it redirects me to `file:///Users/tov/Library/Racket/7.2/doc/search/index.html`, which shows the search box but without styling.

All of the above works correctly with Chrome.

Versions:
 - DrRacket 7.2
 - Safari 12.0.3
 - Mac OS 10.14.3

**Comment by mflatt** [comment]
@rfindler This looks like something that you're wrestled with a lot. Do you know what might be going on here?

**Comment by rfindler** [comment]
It looks like we still have this problem in the pre-release for 7.4 with macOS 10.14.5. The error I see in the safari console is 
```
[Error] Not allowed to load local resource: file:///Volumes/Racket%20v7.3.0.900/Racket%20v7.3.0.900/doc/search/plt-index.js
```

which I don't quite get because the /Volumes directory is there the .dmg file was mounted. If I delete the script tag that refers to that path and reload the file, then search continues not to work, but this time because it seems like it cannot load the documentation index, which makes sense if I look at the copy plt-index.js that's in the same directory as the .html file (it doesn't have the docs in it; it seems to refer to the /Volumes url). This is the precise error, if it matters:

```
[Error] TypeError: undefined is not an object (evaluating 'search_data.length')
	DoSearch (search.js:646)
	HandleKeyEvent (search.js:797)
	onkeydown (Script Element 1:1)
```

If I open the file `....../Racket\ v7.3.0.900/doc/search/index.html` (where the leading dots refer to my desktop directory because that's where I copied the contents of the pre-release dmg file) then I see `file:///Users/robby/Library/Containers/com.apple.Safari/Data/Desktop/Racket%20v7.3.0.900/doc/search/index.html` in the url bar in safari and the docs work correctly.

Could it be that this is a problem with the way `raco setup` is working when it is called to materialize the docs, at least under the newest mac os?

**Comment by rfindler** [comment]
If I delete the entire `doc` directory and re-materialize the docs (transcript below) then I end up with a working setup (I removed some interactions in the REPL that seemed irrelevant in the trace below -- in particular, deleting the index.html file didn't seem to rebuild enough).

After that builds, looking at `doc/search/index.html` I see that it is pointing at a different plt-index.js, namely the one in the installation directory, `src="file:///Users/robby/Desktop/Racket%20v7.3.0.900/doc/search/plt-index.js"`, and the plt-index.js in `~/Library/Racket/7.3.0.900/doc/search` also points there: `var plt_main_url = "file:///Users/robby/Desktop/Racket%20v7.3.0.900/doc/";`.

Here's that transcript.

```
Welcome to DrRacket, version 7.3.0.900 [3m].
Language: racket, with debugging; memory limit: 512 MB.
> (require setup/materialize-user-docs setup/dirs)
> (delete-directory/files (find-user-doc-dir))
> (materialize-user-docs)
raco setup: version: 7.3.0.900
raco setup: platform: x86_64-macosx [3m]
raco setup: target machine: racket
raco setup: installation name: 7.3.0.900
raco setup: variants: 3m
raco setup: main collects: /Users/robby/Desktop/Racket v7.3.0.900/collects
raco setup: collects paths: 
raco setup:   /Users/robby/Library/Racket/7.3.0.900/collects
raco setup:   /Users/robby/Desktop/Racket v7.3.0.900/collects
raco setup: main pkgs: /Users/robby/Desktop/Racket v7.3.0.900/share/pkgs
raco setup: pkgs paths: 
raco setup:   /Users/robby/Desktop/Racket v7.3.0.900/share/pkgs
raco setup:   /Users/robby/Library/Racket/7.3.0.900/pkgs
raco setup: links files: 
raco setup:   /Users/robby/Desktop/Racket v7.3.0.900/share/links.rktd
raco setup:   /Users/robby/Library/Racket/7.3.0.900/links.rktd
raco setup: main docs: /Users/robby/Desktop/Racket v7.3.0.900/doc
raco setup: --- updating info-domain tables ---                    [1:48:04]
raco setup: --- pre-installing collections ---                     [1:48:04]
raco setup: --- installing foreign libraries ---                   [1:48:04]
raco setup: --- installing shared files ---                        [1:48:04]
raco setup: --- compiling collections ---                          [1:48:04]
raco setup: --- parallel build using 4 jobs ---                    [1:48:04]
raco setup: --- creating launchers ---                             [1:48:05]
raco setup: --- installing man pages ---                           [1:48:05]
raco setup: --- building documentation ---                         [1:48:05]
raco setup: 1 running: <pkgs>/racket-index/scribblings/main/user/local-redirect.scrbl
raco setup: 0 running: <pkgs>/racket-index/scribblings/main/user/release.scrbl
raco setup: 2 running: <pkgs>/racket-index/scribblings/main/user/search.scrbl
raco setup: 3 running: <pkgs>/racket-index/scribblings/main/user/start.scrbl
raco setup: 3 rendering: <pkgs>/racket-index/scribblings/main/user/local-redirect.scrbl
raco setup: 2 rendering: <pkgs>/racket-index/scribblings/main/user/release.scrbl
raco setup: 1 rendering: <pkgs>/racket-index/scribblings/main/user/search.scrbl
raco setup: 0 rendering: <pkgs>/racket-index/scribblings/main/user/start.scrbl
raco setup: --- installing collections ---                         [1:48:16]
raco setup: --- post-installing collections ---                    [1:48:16]
> 
```

**Comment by rfindler** [comment]
@tov it appears that the basic problem that led to the bad state was that you first ran DrRacket while it was on the dmg. This leads to a state where chrome will work but safari won't. And, assuming I go this right, later (after you copy the installation to /Applications and eject the dmg), neither will work.

I don't have an idea on how to fix the problem where chrome works but safari doesn't, but I'll do something for the later state (after some offline discussion with @mflatt I have a plan here). You can work around this on your own by deleting the directory ~/Library/Racket/<version>/doc and restarting DrRacket. At least, I believe this will retrigger things and get your installation back into a good state.

**Comment by rfindler** [comment]
Also https://github.com/racket/racket/commit/6747766c6f0fe6c076f1cabc9da3801a313f5de2 was relevant. I think that probably this is about as good as we're going to do, at least for now, so I'll close this PR.

**Comment by crasm** [comment]
I was getting this error in Safari:
```
Safari can't open the page. The error is: "The operation couldn't be completed. Operation not permitted" (NSPOSIXErrorDomain:1)
```

Recreating the doc directory did not help. The solution is to enable `Settings→Advanced→Show features for web developers` and `Settings→Developer→Disable local file restrictions`.
