### ISSUE TITLE
Feature request: hash-ref-key operation for accessing representative key of `equal?`-based hash tables

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#2607]
For `equal?`-based hash tables, it can be useful to be able to access the “representative” key stored in the table that is `equal?` to some given key (but not necessarily `eq?`). For example, a key type used to record bindings in a binding form might use `bound-identifier=?` in its implementation of `equal?`, and obtaining the original key would be useful for signaling duplicate binding errors (since the original key and the new key could have different source locations).

Possible names for the operation: `hash-key`, `hash-key-ref`, `hash-ref-key`, `hash-ref/key`, or `hash-assoc` (which could return both key and value, a la `assoc`).

**Comment by mflatt** [comment]
This seems like a good idea. As a specific example, `datum-intern-literal` uses an internal version of this operation.

**Comment by 97jaz** [comment]
If this operation were added, I think we'd need to specify which key is retained after multiple `hash-set[!]`s with keys that are equal under `equal?` but not under `eq?`. E.g.,
```racket
(require racket/match)

(define (test hash setter)
  (define key1 "hello")
  (define key2 (substring key1 0))

(hash-set! tbl key1 1)
(hash-set! tbl key2 2)

(match-define (cons retained-key _) (hash-assoc tbl key1))

;; which is it?
(eq? retained-key key1)
(eq? retained-key key2)
```

That behavior isn't currently consistent across the several kinds of hashes in racket/c and racket/cs. Should it be?

**Comment by 97jaz** [comment]
There is a kind of consistency to the current behavior, now that I look at it more closely. Mutable hashtables consistently retain the older key; immutable ones consistently use the newer one. That does make a kind of sense. But I still think this behavior (or _some_ behavior) would need to be documented to make this feature useful.

**Comment by 97jaz** [comment]
I put together a [patch](https://github.com/97jaz/racket/commit/7014f90a3bce7645bbcf2914a0407d6873934024) that adds `hash-assoc` to the C-based racket implementation. I've taken the approach of adding an `interned_key` out-parameter to a number of existing hash-table/hash-tree functions.

@mflatt Is this a reasonable approach? It does add a bit of overhead to existing code.

As for racket/cs, it will be simple to add this to immutable hashes. As for mutable ones, there's a simple, but inefficient, approach using a combination of `hashtable-contains?` and `hashtable-cell` (mutatis mutandis for `eq?`-based hashtables). An efficient approach would require an addition to Chez tables (though probably a simple one).

**Comment by mflatt** [comment]
This approach at the C level looks fine to me. I think you can usefully remove a small bit of overhead in the C code by adding a `GC_CAN_IGNORE` annotations to each `Scheme_Object **_interned_key` in a function implementation (not needed in the prototype), since the argument is always stack-allocated.

**Comment by 97jaz** [comment]
Impersonated hashes look like trouble. We'd need a new variant of `impersonate-hash` to handle this/these operation(s) efficiently. And clients that didn't use the new variant would either not support the new operations or would get linear time versions base don `hash-iterate-keys`.

**Comment by 97jaz** [comment]
I've been hacking on this when I'm not out hiking around Utah. Although I started on `hash-assoc` (or `hash-ref-pair`, as I've been calling it lately), I'm beginning to think that `hash-ref-key` might be the better one to implement first. Initially, I was hoping to add a non-consing `hash-ref-pair` and then define `hash-ref-key` trivially in terms of the former, but I can't do that either for the C-based implementation of Racket, where key/value pairs are not already stored in cons cells, or for the Chez-based immutable hashes (unless we store a cons cell in the leaf record, which would add an additional pointer indirection).

Sooo... maybe it would be better to start with a non-consing `hash-ref-key`. But let me ask you, @mflatt and @lexi-lambda: which function is strictly more useful to you (assuming one of them is)?

**Comment by mflatt** [comment]
I think `hash-ref-key` is more useful.

**Comment by lexi-lambda** [comment]
I agree.

**Comment by 97jaz** [comment]
Thank you both.

**Comment by 97jaz** [comment]
How should impersonation of `hash-ref-key` work? If I understand the existing stuff correctly, the `key-proc` argument to `impersonate-hash` is used to map keys in the actual hash to keys-as-seen-by-the-user. However, there is no one function that takes keys in the opposite direction. The `ref-proc`, `set-proc`, and `remove-proc` all map user keys to actual keys, and could do so differently.

When someone calls `hash-ref-key` on an impersonated hash, I think the following needs to happen:
1. the given key needs to be mapped to a replacement
2. the replacement is used to do a lookup in the actual hash
3. the actual interned key (if there is one) needs to be mapped back to a user-visible key

Step 3 seems like a job for `key-proc`. Should we use `ref-proc` for step 1 and ignore the procedure that it returns?

(It's not clear that using `hash-ref-key` on an impersonated hash will be a terribly useful thing to do.)

**Comment by mflatt** [comment]
Good point that there isn't a directly applicable interposition function right now. (I previously thought there was an obvious choice, but I was confused.)

Could we repurpose the `remove-proc` callback to be for both `hash-remove` and `hash-ref-key`? That seems like a better choice than using `ref-proc`. If so, I suggest adjusting the docs to rename `remove-proc` to `in-key-proc` and rename `key-proc` to `out-key-proc`.

**Comment by 97jaz** [comment]
> Could we repurpose the `remove-proc` callback to be for both `hash-remove` and `hash-ref-key`?

We can, though the change won't be backwards-compatible. (Though that goes for repurposing any of these callbacks.) If someone used the callback specifically to track which keys were removed, for example, this change would belie their expectation.

It seems like a backwards-compatible change would require a new callback.

**Comment by mflatt** [comment]
I had in mind that repurposing `remove-proc` would work with existing impersonators that use the callback to transform keys. But I agree that it's not compatible with existing impersonators that track removals.

Just adding a new callback doesn't seem completely backward-compatible, either, because existing impersonators wouldn't interpose on `hash-ref-key`, and the new entry point might subvert some intended guarantee about keys for the table.

Maybe reusing `ref-proc` and ignoring the second result is the right idea (i.e, the most compatible), after all.
