### ISSUE TITLE
syntax/parse: `~!` at the head of a list cuts before determining the term is a list

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#2626]
The following program raises an error, but I expected it to return `#f`:

```racket
#lang racket
(require syntax/parse)
(syntax-parse 'not-a-list
  [(~! _:id ...)
   #t]
  [_
   #f])
```
```
not-a-list: bad syntax
  in: not-a-list
```

I expected `(~! _:id ...)` to essentially do the same thing as `(~and (_ . _) ~! (_:id ...))`, but it does not. The same behavior occurs with `(~! _ . _)`, but not with things like `#(~! _ ...)`:

```racket
#lang racket
(require syntax/parse)
(syntax-parse 'not-a-list
  [#(~! _ ...)
   #t]
  [_
   #f])
```
```
#f
```

I think this happens because lists are really built out of recursively nested pairs, and `syntax/parse` allows patterns like `(_ ... . _)` to actually match *anything*, even non-pairs. This allows parsing lambda formals to work out nicely, but it’s a bit confusing here. I’m not really sure if there’s a good solution, though, so I’d accept this being closed as “not a bug”.

**Comment by rmculpepper** [comment]
This is the intended behavior, for the reason you said.

**Comment by lexi-lambda** [comment]
Okay, thank you for the confirmation. I will write `(~and (_ . _) ~! (_:id ...))` explicitly, then.
