### ISSUE TITLE
sigsev on place-channel-put with place-message-allowed? data structure containing contract-protected non-prefab struct

### ISSUE THREAD

**Issue by MichaelMMacLeod** [racket/racket#2630]
### Describe the bug

Racket crashes when trying to send an instance of a prefab struct that contains a contract-protected non-prefab struct through a place channel.

EDIT: This also happens if the non-prefab struct is contained in some kind of `place-message-allowed?` data structure, like a `list` or `vector`.

### Steps to reproduce

Create two files

`place-start.rkt`:
```racket
#lang racket

(provide 'start)

(define (start ch)
  (place-channel-get ch))
```
`test.rkt`:
```racket
#lang racket

(module protected racket
  (provide (contract-out (struct X ())))
  (struct X ()))

(require 'protected)

(struct Y (x) #:prefab)

(define channel (dynamic-place "place-start.rkt" 'start))
(define payload (Y (X)))

(place-channel-put channel payload) ; crash happens here
; (place-channel-put (list (X)))   ; also crashes
; (place-channel-put (vector (X))) ; also crashes
```
Then, load `test.rkt` with the `racket` executable:
```sh
$ racket test.rkt
SIGSEGV MAPERR si_code 1 fault on addr (nil)
[1]    17326 abort (core dumped)  racket test.rkt
```

### Expected behavior

Racket should throw a contract exception for `place-message-allowed?`, since it isn't possible to send non-prefab structs through a place channel (even if they are inside of prefab structs) EDIT: or other `place-message-allowed?` data structures.

### Racket version

Racket v7.2

### Operating system

Linux x86_64 v5.0.9

### Possibly related

#2504
#2298

**Comment by pmatos** [comment]
I haven't had the time to double check but it seems to me that this is exactly like #2298. Perfect small repro example. Thanks.
