### ISSUE TITLE
Too many dependencies?

### ISSUE THREAD

**Issue by sorawee** [racket/racket#2643]
I just installed Racket on an Ubuntu server. Following packages are transitively installed:

```
adwaita-icon-theme fontconfig fontconfig-config fonts-dejavu-core gtk-update-icon-cache hicolor-icon-theme humanity-icon-theme libatk1.0-0 libatk1.0-data libavahi-client3 libavahi-common-data
  libavahi-common3 libcairo2 libcroco3 libcups2 libdatrie1 libfontconfig1 libgail-common libgail18 libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-bin libgdk-pixbuf2.0-common libgraphite2-3 libgtk2.0-0
  libgtk2.0-bin libgtk2.0-common libharfbuzz0b libjbig0 libjpeg-turbo8 libjpeg8 libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libpixman-1-0 librsvg2-2 librsvg2-common libthai-data libthai0
  libtiff5 libunique-1.0-0 libxcb-render0 libxcb-shm0 libxcomposite1 libxcursor1 libxdamage1 libxfixes3 libxi6 libxinerama1 libxrandr2 libxrender1 racket-common racket-doc ubuntu-mono
```

Some of these don't make sense. There should be no need to install icon themes, for instance.

**Comment by winny-** [comment]
Ubuntu [installs recommended packages by default](https://askubuntu.com/questions/18545/installing-suggested-recommended-packages). Much of those packages are for racket's GUI support. Some other Racket libraries *may* require these packages be installed, so YMMV with `--no-install-recommends`. Hope that helps!

**Comment by pmatos** [comment]
@sorawee if @winny- solved your problem, feel free to close the report. If not, provide more information although the best place for the report might be in the ubuntu bug db, not here.
