### ISSUE TITLE
`prop:impersonator-of` makes `equal?` and `chaperone-of?` inconsistent

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#2644]
I don’t know if this is a bug in the implementation or the documentation, but I found this very confusing. Normally, `equal?` implies `chaperone-of?` for immutable structures, and `prop:impersonator-of` implies `equal?`, but apparently `prop:impersonator-of` does *not* imply `chaperone-of?`. This program illustrates the issue:

```racket
#lang racket

(struct a (value) #:transparent)
(define a1 (a #t))
(define a2 (a #t))
       (equal? a1 a2) ; => #t
(chaperone-of? a1 a2) ; => #t
(newline)


(struct b (value)
  #:property prop:equal+hash
  (list (λ (a b recur) (recur (b-value a) (b-value b)))
        (λ (self recur) (recur (b-value self)))
        (λ (self recur) (recur (b-value self)))))
(define b1 (b #t))
(define b2 (b #t))
       (equal? b1 b2) ; => #t
(chaperone-of? b1 b2) ; => #t
(newline)


(struct c (value orig)
  #:property prop:impersonator-of (λ (self) (c-orig self)))
(define c1 (c #t #f))
(define c2 (c #t c1))
       (equal? c1 c2) ; => #t
(chaperone-of? c1 c2) ; => #f (!)
(newline)


(struct d (value orig)
  #:property prop:equal+hash
  (list (λ (a b recur) (recur (d-value a) (d-value b)))
        (λ (self recur) (recur (d-value self)))
        (λ (self recur) (recur (d-value self))))
  #:property prop:impersonator-of (λ (self) (d-orig self)))
(define d1 (d #t #f))
(define d2 (d #t d1))
       (equal? d1 d2) ; => #t
(chaperone-of? d1 d2) ; => #t
```

**Comment by mflatt** [comment]
So far, I think you're right that the "(!)"-marked result should be `#t`. It will be a few days before I look more closely, though.

**Comment by mflatt** [comment]
This is always difficult for me to keep straight, but on further investigation, I think the last result in the example is the wrong one. Along those lines, the current implementation's
```
 (impersonator-of? d1 d2) ; => #t
```
seems definitely wrong.

In the implementation, a `chaperone-of?` or `impersonator-of?` comparison can discard a `prop:impersonator-of` layer in a way that it won't with impersonators made by functions like `struct-impersonator`. That is, it seems like a bug specific to `prop:impersonator-of`, and there's a straightforward repair. Correcting the bug doesn't cause any existing tests to fail in the core Racket test suite.

Maybe the general rule should be `chaperone-of?` => `impersonator-of?` => `equal?`. In particular, `chaperone-of?` is intended to be constraining. It doesn't seem ok to ignore an impersonator layer in the second argument — even one that's not a chaperone — to decide that another value is `chaperone-of?` that impersonator.

**Comment by lexi-lambda** [comment]
I’m confused. Is what you’re saying that `chaperone-of?` must imply `eq?`-ness for user-defined struct types that do not use `chaperone-struct`? For built-in datatypes, like lists and immutable vectors, `equal?` lists are considered chaperones of one another. I would expect the same to be true of immutable user-defined types (but not mutable ones).

Or are you saying something different: that a non-`#f` value from the procedure associated with `prop:impersonator-of` is supposed to *disqualify* a value from being considered a chaperone? I guess maybe that makes sense, since `impersonator?` and `chaperone?` are (IIUC) mutually exclusive. But a non-`#f` value from `prop:impersonator-of` does not actually seem to imply `impersonator?`, anyway:

```racket
#lang racket

(struct c (value orig)
  #:property prop:impersonator-of (λ (self) (c-orig self)))
(define c1 (c #t #f))
(define c2 (c #t c1))

(chaperone?    c1) ; => #f
(chaperone?    c2) ; => #f
(impersonator? c1) ; => #f
(impersonator? c2) ; => #f (!)
```

But maybe that’s just another bug.

For context, I have a custom (opaque/non-transparent) datatype that I’d like to define a chaperone contract for, but I want the contract to copy my struct, not use `chaperone-struct`, just like `listof` and `vectorof` copy lists and immutable vectors. Doing this without changing `equal?` made the contract system rightfully complain that my new structs were not `chaperone-of?` the old ones, so I thought adding `prop:impersonator-of` would do the trick (especially since when one of my custom contract’s subcontracts is an impersonator contract, my new struct should actually be an impersonator, anyway).

It seems like maybe there needs to be a `prop:chaperone-of`, which would imply `chaperone?` in the same way that `prop:impersonator-of` should imply `impersonator?`, and the value produced by the associated procedure would be used for `equal?` in the same way that the value from `prop:impersonator-of` is used, but otherwise, `prop:chaperone-of` would not actually change the semantics of `chaperone-of?` (i.e. the produced value would be obligated to satisfy `chaperone-of?` even if the `prop:chaperone-of` property were ignored). Currently, it seems impossible to make `chaperone?` return `#t` on anything that does not use the blessed, built-in set of chaperone constructors.

And maybe that’s okay… immutable vectors produced by `vectorof` don’t return `#t` for `chaperone?`, either, so maybe the point is that `chaperone?` and `impersonator?` are kind of like `immutable?` in that they are limited checks that only work on a particular set of built-in values. But if that’s true, then I’m not sure why `prop:impersonator-of` can’t do what I want.

**Comment by mflatt** [comment]
I agree that the `impersonator?` result looks wrong and should be fixed.

For your custom datatype, the intent is indeed that either

 * your struct is immutable and has an equality implementation that lets you get a chaperone by copying, just like lists and immutable vectors are immutable and have an equality implementation; or

 * you have to use `chaperone-struct` to make a chaperone.

I think that adding `prop:chaperone-of` would greatly complicate the implementation, unless we give up on enforcing the constraint that chaperoned operations produce chaperones (and I would be very reluctant to give up on that). But `prop:impersonator-of` is easier, because there are no constraints on impersonated operations that need to be enforced.

**Comment by mflatt** [comment]
On further investigation of `impersonator?`, maybe it makes sense to leave the implementation alone. The `impersonator?` predicate is mostly used as a guard on representation, and its use in describing `unsafe-struct*-set!` and `unsafe-struct*-ref` is with the intention of the current implementation. I could adjust the docs to explain that it's a kind of weak predicate (so, all the more reason not to use it, normally).

**Comment by lexi-lambda** [comment]
That makes sense to me. But then why does `prop:impersonator-of` disqualify something from being `chaperone-of?`, if the value otherwise passes all the `chaperone-of?` checks? (I.e. it is an immutable struct that is `equal?` to the other struct.)

**Comment by mflatt** [comment]
Impersonators are less constrained than chaperones—even ones created with `prop:impersonator-of`, even with immutable fields. For example, suppose that V1 is chaperoned so that accessing its `x` field is allowed only on Mondays. Suppose also that V2 impersonates V1 via`prop:impersonator-of`, and V2 was able to become a copy of V1 because it was created on Monday. On Tuesday, V2 should not be considered a valid substitute for V1 in the sense of `chaperone-of?`, because V2 has effectively shed some of V1's chaperoning.

**Comment by lexi-lambda** [comment]
I am not sure I understand what you’re saying, so let me give a more concrete example. Let’s say I am building a parser combinator library, and I have struct that represents a parser:

```racket
; proc : (-> I (or/c (cons/c I O) #f))
(struct parser (proc))
```

I want to define contracts on my parsers, so I can write `(parser/c in/c out/c)` to protect a parser that can parse input streams that satisfy `in/c` and produce values that satisfy `out/c`. To build a chaperone contract, I need a way to chaperone parsers, so I write a `chaperone-parser` function that uses `chaperone-procedure` on the function inside a parser:

```racket
(define (chaperone-parser p neg-in-proc pos-in-proc out-proc)
  (parser (chaperone-procedure
           (parser-proc p)
           (lambda (in)
             (values (match-lambda
                       [(cons in* out)
                        (cons (pos-in-proc in*)
                              (out-proc out))]
                       [#f #f])
                     (neg-in-proc in))))))
```

But now I have a problem, since my `chaperone-parser` function doesn’t actually preserve `chaperone-of?`:

```racket
(define p1 (parser (lambda (in) #f)))
(define p2 (chaperone-parser p1 values values values))
(chaperone-of? p2 p1) ; => #f
```

So, to fix this, I can change `equal?` on parsers to keep track of the original, unchaperoned parser, and use that for equality:

```racket
; proc : (-> I (or/c (cons/c I O) #f))
; maybe-orig : (or/c parser? #f)
(struct parser (proc maybe-orig)
  #:methods gen:equal+hash
  [(define (equal-proc p1 p2 recur)
     (eq? (parser-orig p1) (parser-orig p2)))
   (define (hash-proc p recur)
     (eq-hash-code (parser-orig p)))
   (define hash2-proc hash-proc)])

(define (parser-orig p)
  (or (parser-maybe-orig p) p))
```

And I can change `chaperone-parser` to set the new parser’s `maybe-orig` field to `(parser-orig p)`. Now `chaperone-of?` does what I want:

```racket
(define p1 (parser (lambda (in) #f) #f))
(define p2 (chaperone-parser p1 values values values))
(chaperone-of? p2 p1) ; => #t
```

But isn’t what I just did more or less what supplying `#:property prop:impersonator-of parser-maybe-orig` would do? It would change `equal?` to operate the same way my custom `equal-proc` implementation operates. Why isn’t that enough?

You talk about how, in your example, V2 has “shed some of V1’s chaperoning.” But that could happen with my above example, too, and `chaperone-of?` would be totally happy with it. In fact, the fact that I used `chaperone-procedure` instead of `impersonate-procedure` or even just replacing it with a totally different value is irrelevant; as long as the structure is immutable, `chaperone-of?` doesn’t care:

```racket
(struct foo (value)
  #:methods gen:equal+hash
  [(define (equal-proc f1 f2 recur) #t)
   (define (hash-proc f recur) 1)
   (define (hash2-proc f recur) 1)])

(define f1 (foo #f))
(define f2 (foo 'something-totally-different))
(chaperone-of? f2 f1) ; => #t
```

**Comment by mflatt** [comment]
`chaperone-of?` is not totally happy with your `chaperone-parser`:
```
#lang racket/base
(require racket/match)

; proc : (-> I (or/c (cons/c I O) #f))
; maybe-orig : (or/c parser? #f)
(struct parser (proc maybe-orig)
  #:methods gen:equal+hash
  [(define (equal-proc p1 p2 recur)
     (eq? (parser-orig p1) (parser-orig p2)))
   (define (hash-proc p recur)
     (eq-hash-code (parser-orig p)))
   (define hash2-proc hash-proc)])

(define (parser-orig p)
  (or (parser-maybe-orig p) p))

;; The intended way to chaperone a parser:
(define (chaperone-parser p neg-in-proc pos-in-proc out-proc)
  (chaperone-struct
   p
   parser-proc
   (lambda (p proc)
     (chaperone-procedure
      proc
      (lambda (in)
        (values (match-lambda
                  [(cons in* out)
                   (cons (pos-in-proc in*)
                         (out-proc out))]
                  [#f #f])
                (neg-in-proc in)))))))

;; The suggested way:
(define (suggested-chaperone-parser p neg-in-proc pos-in-proc out-proc)
  (parser (chaperone-procedure
           (parser-proc p)
           (lambda (in)
             (values (match-lambda
                       [(cons in* out)
                        (cons (pos-in-proc in*)
                              (out-proc out))]
                       [#f #f])
                     (neg-in-proc in))))
          (parser-orig p)))

(define p1 (parser (lambda (in) #f) #f))
(define p2/suggested (suggested-chaperone-parser p1 values values values))
(chaperone-of? p2/suggested p1) ; => #t - so far, so good

(define p2 (chaperone-parser p1 values values values))
(chaperone-of? p2 p1) ; => #t - the intended way is also good, so far

(define p3/suggested (suggested-chaperone-parser p2 values values values))
(chaperone-of? p3/suggested p1) ; => #f - not totally happy
(chaperone-of? p3/suggested p2) ; => #f - not totally happy

(define p3 (chaperone-parser p2 values values values))
(chaperone-of? p3 p1) ; => #t - happy with the intended way
(chaperone-of? p3 p2) ; => #t - happy with the intended way
```

**Comment by lexi-lambda** [comment]
Isn’t that just because `p3` chaperones `p2`, not `p3/suggested`, and likewise the `chaperone-of?` checks compare against `p2`? If you change the checks to

```racket
(define p3/suggested (suggested-chaperone-parser p2/suggested values values values))
(chaperone-of? p3/suggested p1)
(chaperone-of? p3/suggested p2/suggested)
```

then they both return `#t`. Unless your point was just that what I tried doesn’t cooperate with chaperones created with `chaperone-struct`, but that’s fine with me: `parser` is an opaque type, so nobody except me can create chaperones of it, anyway.

Anyway, maybe this is a bad example, since I’m not saving very much by wrapping eagerly instead of on every call to `parser-proc`. But imagine I had a slightly different struct:

```racket
(struct foo (value))
```

…and then I had some contract `(foo/c really-expensive-first-order-check?)`. If I use `chaperone-struct` to implement `foo/c`, then I’ll pay for that cost every time I call `foo-value`. But `foo` is immutable, so there’s no reason to pay that cost. I want to copy it, instead, just as `vectorof`, `hash/c`, etc. do.

**Comment by mflatt** [comment]
I'm not seeing your point, yet.

It's nice that you have a function `chaperone-parser` that sometimes produces a chaperone, and you also have a context constrained such that `chaperone-parser` will always produces a chaperone. But that demonstration doesn't imply that we know how to implement a `prop:chaperone-of` that works in general with the expressiveness that is currently supported by chaperones.

In particular, chaperones can interpose on each access of a struct field, and that doesn't seem compatible the copying strategy outlined by `chaperone-parser`. Note that the chaperone system doesn't allow that kind of interposition on list elements, so maybe copying can always work on lists. The chaperone system does allow that kind of interposition on immutable vectors, so copying won't always produce a chaperone for immutable vectors.

**Comment by jackfirth** [comment]
I've been similarly confused about `chaperone-of?` before. I think my confusion comes down to this:
```
In particular, chaperones can interpose on each access of a struct field, and that doesn't seem compatible the copying strategy outlined by `chaperone-parser`.
```
What if I don't _want_ to support such chaperones? If I make an immutable`(point x y)` type it would be extremely surprising to me that I might be able to access a point's fields one moment and not the next.

**Comment by rfindler** [comment]
On Sat, May 18, 2019 at 3:08 PM Jack Firth <notifications@github.com> wrote:

> I've been similarly confused about chaperone-of? before. I think my
> confusion comes down to this:
>
> In particular, chaperones can interpose on each access of a struct field, and that doesn't seem compatible the copying strategy outlined by `chaperone-parser`.
>
> What if I don't *want* to support such chaperones? If I make an immutable(point
> x y) type it would be extremely surprising to me that I might be able to
> access a point's fields one moment and not the next.
>
>
Well, in some sense, this comes down to the nature of contracts. They can
be arbitrary predicates and those predicates might query some other state
to decide if any given access is legal, even for immutable structs.

Robby

**Comment by jackfirth** [comment]
Not for immutable lists though. What makes them special, aside from the fact that they're primitives? If it was easy to add support for accessor contracts on immutable lists, would that have been done?

**Comment by rfindler** [comment]
On Sat, May 18, 2019 at 3:18 PM Jack Firth <notifications@github.com> wrote:

> Not for immutable lists though. What makes them special, aside from the
> fact that they're primitives? If it was easy to add support for accessor
> contracts on immutable lists, would that have been done?
>

I believe it is not unreasonable to say that the effort of adding
chaperones to lists/pairs is unreasonably high, so we didn't do it. There
may be better rationales than that one, tho.

Robby

**Comment by lexi-lambda** [comment]
> I'm not seeing your point, yet.

I’m sorry—we’ve clearly been talking past each other. I think I finally understand what you’ve been saying from your most recent comment, though.

> It's nice that you have a function `chaperone-parser` that sometimes produces a chaperone, and you also have a context constrained such that `chaperone-parser` will always produces a chaperone. But that demonstration doesn't imply that we know how to implement a `prop:chaperone-of` that works in general with the expressiveness that is currently supported by chaperones.

I should be clear: I have not been arguing in favor of a `prop:chaperone-of`, as your first response to my mention of one was already enough to convince me it isn’t the right approach. That said, I finally see what you’ve been getting at, and I would have expected this program to illustrate your point with vectors:

```racket
#lang racket

(define v1 (vector-immutable (lambda () #f)))

(define/contract v2 (vectorof (-> #f) #:eager #f) v1)
(define/contract v3 (vectorof (-> #f)) v2)
```

But it doesn’t. It causes no errors, and `(chaperone-of? v3 v2)` still returns `#t`. It turns out this is because of 717cf332b6a12d0cb9bf476d8b78335ed80188a4 from 2012, which changed `vectorof` to explicitly avoid copying immutable vectors if they are chaperones (according to `chaperone?`).

In any case, the larger point is that `chaperone-of?` is more subtle than I realized. All I was really hoping to do was leverage the useful auto-generated `equal?` implementation that `prop:impersonator-of` happens to provide, without bringing in the implication that the value is actually an impersonator, but I think I see now why that is probably not right, and also why a `prop:chaperone-of` that adds the modified `equal?` check but does nothing else wouldn’t be appropriate, either.

Given both your explanation and your pushed fix, I’m content to call this issue closed.
