### ISSUE TITLE
v7.2 does not run on MacOS Mojave 10.14.4

### ISSUE THREAD

**Issue by apanos** [racket/racket#2649]
I have an iMacPro, running MacOS  Mojave 10.14.4

I tried the Racket v7.2  the 64 bit, and the 32 bit versions, and neither runs on my iMac. 

No window opens.  I cannot open a file, and I cannot even show the "about Racket" dialog box

**Comment by jbclements** [comment]
To clarify: you download the installer, drag the folder into your Applications folder, then double-click on the DrRacket icon? What do you see after this?

**Comment by apanos** [comment]
The DrRacket menu shows up, and the initialization dialog window comes up.  There are small icons at the bottom of the window, and a thermometer bar that progresses all the way across. Then the window goes away. No other window comes up, not the normal editor (or listener) window.

The menu items drop down when you use the mouse, but nothing happens when you select a menu item.   The command key shortcuts do not work.   I cannot exit with command-Q.  I have to use the “command-alt-escape” keys sequence to call the task manager window and force DrRacket to quit.

Does this description help?

the same happens with 64 bit or 32 bit versions.

Please let me know if there is a way to fix this, or a new update

On May 9, 2019, at 16:03, John Clements <notifications@github.com<mailto:notifications@github.com>> wrote:


To clarify: you download the installer, drag the folder into your Applications folder, then double-click on the DrRacket icon? What do you see after this?

**Comment by mflatt** [comment]
You could try the current v7.3 candidate from https://pre-release.racket-lang.org, but I don't recall any change since v7.2 that seems relevant to the symptoms you describe.

Can you try running "bin/drracket" in a terminal? It's possible that some errors will be reported that way to help explain the problem.

**Comment by apanos** [comment]
Thank you for your email.

I downloaded the pre-release  Racket v7.2.0.900  and the same problems occur if I double click on the DrRacket icon.  No editor comes up, and none of the menu items works.  

I also tried the  bin/drracket  command, and the same occurs.  I could not end the program, so I used the ‘command-option-Escape’ sequence to force DrRacket to quit.   This resulted in an error dialog box, and the Racket error dialog message gave the following output


user break
  context...:
   /Applications/Racket v7.2.0.900/collects/racket/private/port.rkt:126:2: loop
   /Applications/Racket v7.2.0.900/share/pkgs/gui-lib/framework/private/aspell.rkt:56:0: do-aspell-problematic
   /Applications/Racket v7.2.0.900/share/pkgs/gui-lib/framework/private/aspell.rkt:232:0: get-aspell-dicts
   /Applications/Racket v7.2.0.900/collects/racket/contract/private/arrow-val-first.rkt:390:18
   /Applications/Racket v7.2.0.900/share/pkgs/drracket/drracket/private/unit.rkt:3882:6: edit-menu:between-find-and-preferences method in frame-mixin
   ...ass-internal.rkt:1666:49
   /Applications/Racket v7.2.0.900/collects/racket/private/class-internal.rkt:3570:0: continue-make-object
   /Applications/Racket v7.2.0.900/share/pkgs/gui-lib/framework/private/frame.rkt:1406:2
   /Applications/Racket v7.2.0.900/collects/racket/private/class-internal.rkt:3570:0: continue-make-object
   [repeats 1 more time]
   /Applications/Racket v7.2.0.900/share/pkgs/gui-lib/framework/private/frame.rkt:762:2
   /Applications/Racket v7.2.0.900/collects/racket/private/class-internal.rkt:3570:0: continue-make-object
   [repeats 1 more time]
   /Applications/Racket v7.2.0.900/share/pkgs/gui-lib/framework/private/frame.rkt:1058:2
   /Applications/Racket v7.2.0.900/collects/racket/private/class-internal.rkt:3570:0: continue-make-object
   [repeats 2 more times]
   …



I hope  this helps.  I really enjoy using Racket for my research, and  hope I can use it again soon.  Let me know if I can be of help.

**Comment by apanos** [comment]
A little more information.  The bin/drracket command was stuck with the error message I sent you earlier.  To end it, I used Ctrl-C from the Terminal Window.  Then the About Dialog box popped up.  I still could not do anything with DrRacket, the menu items did not work, and I got the Racket error window again, with the following  message in it.

standard-module-name-resolver: collection not found
  for module path: racket/base
  collection: "racket"
  in collection directories:
   /Users/anthonypanos/Library/Racket/7.2.0.900/collects
   /Applications/Racket v7.2.0.900/collects
   ... [165 additional linked and package directories]
  context...:
   show-collection-err
   standard-module-name-resolver
   module-path-index-resolve
   loop
   do-attach-module17
   /Applications/Racket v7.2.0.900/collects/racket/private/namespace.rkt:18:2: make-base-empty-namespace
   /Applications/Racket v7.2.0.900/share/pkgs/drracket/drracket/private/insulated-read-language.rkt:235:0: make-irl
   /Applications/Racket v7.2.0.900/collects/racket/contract/private/arrow-higher-order.rkt:364:33
   /Applications/Racket v7.2.0.900/share/pkgs/drracket/drracket/private/module-language-tools.rkt:206:4
   /Applications/Racket v7.2.0.900/collects/racket/private/class-internal.rkt:3570:0: continue-make-object
   [repeats 4 more times]
   /Applications/Racket v7.2.0.900/share/pkgs/drracket/gui-debugger/debug-tool.rkt:177:6
   /Applications/Racket v7.2.0.900/collects/racket/private/class-internal.rkt:3570:0: continue-make-object
   [repeats 5 more times]
   /Applications/Racket v7.2.0.900/collects/racket/private/class-internal.rkt:3524:0: do-make-object
   /Applications/Racket v7.2.0.900/share/pkgs/drracket/drracket/private/unit.rkt:1402:4
   …

I hope this adds some more information to help resolve this issue.

**Comment by rfindler** [comment]
It looks like something has gone wrong with DrRacket's attempt to use the aspell program on your machine and, during DrRacket's attempts to get an error message with some value, DrRacket is getting stuck.

What happens if you just type "aspell" at the prompt. That is, instead of "bin/drracket", just go to the same place and type "aspell -a"? Also "ispell -a", if you don't have aspell.

**Comment by apanos** [comment]
I get the following error message from aspell -a

Error: No word lists can be found for the language "en_US”.



My iMacPro does not have ispell command at all

**Comment by rfindler** [comment]
My read of the code suggests that maybe "aspell -a" didn't return (which would have, before the commit above, cause drracket to hang I think). Did you see the prompt come right back after the error message?

**Comment by apanos** [comment]
no I did not see the prompt come back

I think you are right, that aspell did not return.

On May 12, 2019, at 20:39, Robby Findler <notifications@github.com<mailto:notifications@github.com>> wrote:


My read of the code suggests that maybe "aspell -a" didn't return (which would have, before the commit above, cause drracket to hang I think). Did you see the prompt come right back after the error message?

**Comment by rfindler** [comment]
It looks like the snapshot builds here

   https://www.cs.utah.edu/plt/snapshots/

have the commit I pushed. Can you give that DrRacket a try and see if works better for you?

**Comment by apanos** [comment]
Thank you, I just tried it, and it works very well.  

Thank you to the whole team for Racket, and all the work you do to keep the project going, and growing.  


Tony Panos

**Comment by rfindler** [comment]
Thank you!
