### ISSUE TITLE
fl: 0 devided by 1 gives nan

### ISSUE THREAD

**Issue by bdeket** [racket/racket#2654]
> (/ 0.0+0.0i 1+1e-320i)
+nan.0+nan.0i

This seems to happen for (imag-part x)<1e-310

maybe related:
> (expt 1+1.0e-320i -1)
+nan.0-0.0i

calculating the inverse as:
(/ (conjugate x) (* x (conjugate x)))
does work...

**Comment by mflatt** [comment]
Thanks for the report!

**Comment by bdeket** [comment]
Great,

thanks for the quick fix
