### ISSUE TITLE
R5RS: Internal definitions not handled properly according to the specification

### ISSUE THREAD

**Issue by timutable** [racket/racket#2655]
It seems to me that the implementation for R5RS doesn't handle internal define expressions properly according to the [specification](https://schemers.org/Documents/Standards/R5RS/HTML/r5rs-Z-H-8.html#%_sec_5.2.2). For the procedure definition 
```
(define (test)
  (define a 2)
  (define b 5)
  (define c (+ a b))
  c)
```
we'd expect `(test)` to output `7` but it fails with an error
```
a: undefined;
 cannot use before initialization
```
(note: this was tested in DrRacket 7.1)

**Comment by soegaard** [comment]
If I remember correctly, your definition is in R5RS equivalent to

    (define (test) (letrec ((a 2) (b 5) (c (+ a b))) c))

And `letrec` is in R5RS is free to choose the order in which the bindings are evaluated.
This means that `a` and `b` might not be initialized before `(+ a b)` is to be evaluated.

So an implementation is free to choose to report an error - or to attempt an evaluation - but 
the program in question is no longer portable between R5RS-implementations.

**Comment by timutable** [comment]
Okay, thanks for the clarification.
