### ISSUE TITLE
Error reading uppercase complex

### ISSUE THREAD

**Issue by gus-massa** [racket/racket#2660]
I found a few errors in the [test suit of the racket-r7rs package](https://github.com/lexi-lambda/racket-r7rs/issues/11) in Racket 7.3

The result of

    (read (open-input-string "1+2I"))

is `1+2i` (a complex number) in Racket 7.2, but it is `|1+2I|` (a symbol) in Racket 7.3.

The exact commit that change the behavior is https://github.com/racket/racket/commit/0549bfb1e5f4bf49a433e2f390d6bb4965cf07e4 "rewrite number parser". In my opinion this is an overlooked obscure feature of the old number parser. But the uppercase version of the complex numbers is not documented in the docs [Reading Numbers](https://docs.racket-lang.org/reference/reader.html#%28part._parse-number%29), so if this is reverted, it will be a good idea to fix the docs.

**Comment by mflatt** [comment]
Reopening because I forgot to fix the docs.
