### ISSUE TITLE
Error changing read-case-sensitive inside read

### ISSUE THREAD

**Issue by gus-massa** [racket/racket#2661]
I found a few errors in the [test suit of the racket-r7rs package](https://github.com/lexi-lambda/racket-r7rs/issues/11) in Racket 7.3. This is due to an old change in Racket 7.0

The problem is changing `read-case-sensitive` inside a `read`, something similar to the effect of `#ci` but it uses `#!fold-case` instead. My example is a simplified version of [racket-r7rs/lang/reader.rkt](https://github.com/lexi-lambda/racket-r7rs/blob/master/r7rs-lib/lang/reader.rkt). I use `#!` instead to simplify the code. 

    #lang racket
    
    (define (myread [in (current-input-port)])
      (r7rs-parameterize-read
       (lambda () (read in))))
    
    (define (r7rs-parameterize-read do-read)
      (parameterize (;[read-case-sensitive (read-case-sensitive)] ; I added this line
                     [current-readtable (make-r7rs-readtable (current-readtable))])
        (do-read)))
    
    (define (make-r7rs-readtable base)
      (make-readtable base
                      #\! 'dispatch-macro read-directive
                      #f  'non-terminating-macro (reparameterize-read base)))
    
    (define (reparameterize-read base)
      (case-lambda
        [(c in)                  (read/recursive in c base)]
        [(c in src line col pos) (read-syntax/recursive src in c base)]))
    
    (define (read-directive c in src line col pos)
      (read-case-sensitive #f)
      (make-special-comment #f))
    
    (myread (open-input-string "#!ABC"))
    (myread (open-input-string "#!ABC"))

The result is `abc` and `abc` in Racket 6.12, but it is `|ABC|` and `abc` in Racket 7. The commit that changed this is https://github.com/racket/racket/commit/59ef2543182e0445979a2245dbaa06d1cdca35fd "switch to a new, Racket-implemented expander & module system"

I'm not sure about this, because the code is using a workaround to implement the feature, and I'm not sure if it is necessary to fix the implementation of the reader in Racket or use another workaround in the package.

**Comment by lexi-lambda** [comment]
Many thanks to both of you for noticing and fixing this!
