### ISSUE TITLE
Printing structs and print-pair-curly-brace

### ISSUE THREAD

**Issue by gus-massa** [racket/racket#2662]
Outside DrRacket, the output of this code

    #lang racket

    (struct b (x y) #:transparent)

    (parameterize ([print-pair-curly-braces #t])
      (print (vector (b 1 2) 3)))

is `;==> (vector {b 1 2} 3)`, 

i.e. the `vector`  constructor has normal parenthesis and the `b` constructor has curly-braces.

(Inside DrRacket, the output changes with the configuration, but you never get exactly this.)

Is this a bug or a feature? It looks like it has not changed for a long time, but I'm not sure if anyone has noticed.

**Comment by mflatt** [comment]
I agree that this seems wrong, and `pretty-print` makes a different choice. There are test cases that check specifically for this behavior for the built-in printer (not the pretty printer), but I suspect sloppy testing instead of a carefully thought-out intent. Since we have inconsistent behavior right now, I'm inclined to fix the inconsistency by changing the built-in printer.

**Comment by gus-massa** [comment]
I added that test recently, to ensure the current behavior. But I think it was weird so I'm happy with the change.

With this change it is possible to simplify `curly?` in [io/print/list.rkt#L16-L24](https://github.com/racket/racket/blob/6381e3c009a32ebc1fd50ae3c9e54bfcdb832ef5/racket/src/io/print/list.rkt#L16-L24) to a single line. I wrote that version to preserve the curly bracket in structs, but if the `alt-constructor` and `alt-prefix` will always use parens, it is not necessary. (And notice that the code fails in case one of them is `""`, or it is a weird prefix like `"#xyz{"`. It is not very robust code.)

**Comment by gus-massa** [comment]
Something like this: https://github.com/gus-massa/racket/commits/19-5-CurlyMPair-More  (Assuming that "all" the tests pass https://travis-ci.org/gus-massa/racket/jobs/538750546 )

**Comment by mflatt** [comment]
That simplification looks like it would use "}" to close a constructor started with `(`, as in `(parameterize ([print-pair-curly-braces #t]) (print (arity-at-least 1)))`. Am I misreading it?

**Comment by gus-massa** [comment]
Fixed

**Comment by mflatt** [comment]
That looks good to me (and I see that the tests pass, if I'm reading it right).

**Comment by gus-massa** [comment]
Merged in https://github.com/racket/racket/commit/daba5db44a27644f8793a576e3982793eb47db9e
