### ISSUE TITLE
Raco pkg install failed: version mismatch

### ISSUE THREAD

**Issue by ncihnegn** [racket/racket#2668]
```
raco pkg install: version mismatch for dependency
  for package: base
  mismatch packages:
   racket (have 7.3, need 7.3.0.4)
```
How can I solve this?

**Comment by pmatos** [comment]
Can you please provide more information on what you are trying to install?

**Comment by ncihnegn** [comment]
I find out my installation is messed up. After a clean installation, it works. Thanks.
