### ISSUE TITLE
bytes-utf-8-index signature doesn't match documentation

### ISSUE THREAD

**Issue by jackfirth** [racket/racket#2670]
The docs for [`bytes-utf-8-index`](https://docs.racket-lang.org/reference/bytestrings.html#(def._((quote._~23~25kernel)._bytes-utf-8-index))) state that it requires two arguments and accepts three more optional arguments. But the implementation only accepts up to four arguments:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/8175575/58619370-a442b680-8279-11e9-9e1e-e879c7eb24ef.png">

I think this is because of [this line in `string.c`](https://github.com/racket/racket/blob/be828b184ca2e2dadaa9be00c194a47146099f90/racket/src/racket/src/string.c#L667) where it appears the wrong number is used in a call to `scheme_make_immed_prim`:

```
p = scheme_make_immed_prim(byte_string_utf8_index, "bytes-utf-8-index", 2, 4);
```

**Comment by mflatt** [comment]
I guess I should have noticed/tested this when fixing `bytes-utf-8-ref` recently.
