### ISSUE TITLE
Typo in racket guide, Section 5.2 (copying and update), resulting in confusing example

### ISSUE THREAD

**Issue by dueringa** [racket/racket#2671]
https://github.com/racket/racket/blob/daba5db44a27644f8793a576e3982793eb47db9e/pkgs/racket-doc/scribblings/guide/define-struct.scrbl#L103

Instead of
~~~
(list (posn-x p2) (posn-y p2))
(list (posn-x p1) (posn-x p2))
~~~

it should probably say
~~~ racket
(list (posn-x p2) (posn-y p2))
(list (posn-x p1) (posn-y p1))
~~~

(it doesn't make sense to print posn-x p2 twice)

**Comment by gus-massa** [comment]
I have the feeling that it was written this way to show simultaneously the value of the `x` field in the two structs, but I think that your version is more clear. Let's wait for a few more opinions.

(Meanwhile, do you want you send a PR with the change? I'm not 100% that it will be merged, but I like it. If you can't send a PR, we can fix it instead.)

**Comment by bennn** [comment]
Oops, I saw the PR and merged it before I read the "let's wait" here.

**Comment by gus-massa** [comment]
I thing you count as a second opinion. :)
