### ISSUE TITLE
processor-count always returns 2?

### ISSUE THREAD

**Issue by pbpf** [racket/racket#2674]
I use a I7-9750H(6 cores and 12 threads), but (processor-count) return 2
why? It there anything woring?

**Comment by pmatos** [comment]
Can you please post the output of `racket --version` and the OS you are running racket under?

**Comment by pbpf** [comment]
racket version is 7.3, and OS is windows10 1903 x64

**Comment by pmatos** [comment]
thanks @pbpf 
I can confirm this. x86_64 racket on x86_64 windows 10 return 2 for `(processor-count)` instead of the correct value. This is a regression against 6.12.
