### ISSUE TITLE
Error in test in racket-r7rs in RackerCS

### ISSUE THREAD

**Issue by gus-massa** [racket/racket#2675]
There is only one remainder error in the test of racket-r7rs when they are run in RacketCS: [racket-r7rs/r7rs-tests.rkt#L1878-L1881](https://github.com/lexi-lambda/racket-r7rs/blob/master/r7rs-test/tests/r7rs/chibi/tests/r7rs-tests.rkt#L1878-L1881) Something like:

    #lang r7rs
    (define-syntax test ...)
    (test #t
      (let* ((out (open-output-string))
             (r (begin (newline out) (get-output-string out))))
        (or (equal? r "\n") (equal? r "\r\n"))))

Approximately one half of the times it fails with "[newline: output port is closed](https://travis-ci.org/gus-massa/racket-r7rs/jobs/540246920#L640-L641)" and the other half of the times it fails with "[invalid memory reference.  Some debugging context lost](https://travis-ci.org/gus-massa/racket-r7rs/jobs/539476025#L640-L641)". I expected that it would have been fixed by  https://github.com/racket/racket/commit/40846e3ed9b95af17d281a88a55d89f210e88b30 "_racket/system: add some missing synchronization_" but it is still failing. 

It is strange because the test with `newline` fails every time, but the other test with `write-string`, `display`, don't fail.

**Comment by samth** [comment]
Here's a simplified program:

```
#!r7rs
(import (scheme base))
(let* ((out (open-output-string))
       (r (begin (newline out) (get-output-string out))))
  (or (equal? r "\n") (equal? r "\r\n")))
```

**Comment by samth** [comment]
This is a bug in racket, see: #2677.

**Comment by gus-massa** [comment]
Thanks for the reduction to plain racket code. Let's hope that it is easy to solve now.
