### ISSUE TITLE
memory corruption on racketcs with reencode-output-port

### ISSUE THREAD

**Issue by samth** [racket/racket#2677]
This program:

```
#lang racket/base
(require scheme/port)
(define-struct transcoder (codec eol-style error-handling-mode))
(define-struct codec (enc))
(define utf-8 (make-codec "utf-8"))
(define-struct textual-output-port (port transcoder)
  #:property prop:output-port 0)

(define utf8-transcoder
  (make-transcoder utf-8 'none '?))
(define (transcode-output p t)
  (reencode-output-port p
                        (codec-enc (transcoder-codec t))
                        #f
                        #t
                        (object-name p)
                        #f
                        #f))

(let-values (((out) (make-textual-output-port (transcode-output (open-output-string) utf8-transcoder) utf8-transcoder)))
  (let-values
             (((r) (begin (newline out) #;(get-output-string out))))
  #t))
```

causes an "invalid memory reference" error on racketcs, but works correctly on racket.

**Comment by samth** [comment]
Originally reported in racket/racket#2675.

**Comment by gus-massa** [comment]
Minimized version:

    #lang racket/base
    (define-struct myport (port)
      #:property prop:output-port 0)

    (define out
      (make-myport
       #;(current-output-port)
       (open-output-string)))
    #;(display 777 out)
    (newline out)

You can replace `(open-output-string)` with `(open-output-string)`, but you can't replace `newline` with `display`. My guess is that `newline` doesn't understand custom ports.

**Comment by mflatt** [comment]
Thanks for the report and for narrowing down the problem!

For future reference, when you suspect a bug in the Racket layer over Chez Scheme, it can help to try building that layer in safe mode. To do that, comment out `--unsafe` in `racket/src/cs/Makefile`, then go to `racket/src/build/cs/c` (or wherever your build directory is) and delete all ".so" files, `make`, and try `./racketcs`.

Safe mode produces an error that confirms @gus-massa's suspicion: `core-port-buffer: #<myport> is not of type #<struct-type>`.

**Comment by gus-massa** [comment]
Now the test of racket-r7rs finish cleanly in HEAD and HEADCS https://travis-ci.org/gus-massa/racket-r7rs/builds/542031427
