### ISSUE TITLE
RacketCS does not like to build with external racket

### ISSUE THREAD

**Issue by pmatos** [racket/racket#2683]
For CI purposes I have been experimenting with a staggered building. Instead of running `make cs` at top-level and let Racket build everything, do first a build of `racketcgc`, install it. Then `racket3m` using `racketcgc` and install it and finally `racketcs` using `racket3m`.

However, this last `racketcs` build fails.
Configured with :
```
./configure CFLAGS='-march=native -O3' --enable-racket=/home/pmatos/tmp/install/racket3m/bin/racket --prefix=/home/pmatos/tmp/install/racketcs --enable-csdefault
```

- [x] this not only seems to rebuild `racket3m` anyway therefore defeating the purpose of having built it earlier on
- [x] but it also fails with: 
```
Use /home/pmatos/tmp/racket/racket/src/cs/bootstrap/.
Use /home/pmatos/tmp/racket/racket/src/ChezScheme/nanopass
Use /home/pmatos/tmp/racket/racket/src/ChezScheme/s
Check /home/pmatos/tmp/racket/racket/src/ChezScheme/boot/ta6le
Load nanopass
load/cd: directory of #<path:/home/pmatos/tmp/racket/racket/src/ChezScheme/nanopass/nanopass/implementation-helpers.ikarus.ss> does not exist (current directory is #<path:/home/pmatos/tmp/racket/racket/src/cs/c/>)
  context...:
   /home/pmatos/tmp/install/racket3m/share/racket/collects/racket/private/misc.rkt:87:4: load/cd
   "/home/pmatos/tmp/racket/racket/src/cs/bootstrap/make-boot.rkt": [running body]
   temp37_0
   for-loop
   run-module-instance!125
   "/home/pmatos/tmp/install/racket3m/share/racket/collects/setup/main.rkt": [running body]
   temp37_0
   for-loop
   run-module-instance!125
   perform-require!78
Makefile:149: recipe for target 'scheme-make-finish' failed
```
I should point out that I ran configure line and make in `racket/racket/src`. And it failed for cs because I forgot to clone Chez so I did clone Chez (from `racket/ChezScheme`) to `racket/racket/src/ChezScheme` which is here it was asking it to be.

This are a few mental notes I will return to when I get some more time to look into this.

**Comment by pmatos** [comment]
The second issue was solved by me actually cloning Chez properly with `--recurse-submodules`.
```
racket/racket/src$ git clone --recurse-submodules -j8 https://github.com/racket/ChezScheme
```

**Comment by mflatt** [comment]
For the first issue, using `--enable-csonly` should do the right thing already, and it seems possible that you want that flag instead of `--enable-csdefault` (so you skip the configure of traditional Racket). But I'll push a configure correction for the case of `--enable-csdefault` or `--enable-cs`.

**Comment by pmatos** [comment]
Thanks for the fix. Will test and close the issue.

**Comment by pmatos** [comment]
Fix is good. Full racketcs from existing racket3m is now down to 8minutes. That's good although from skimming the build logs it looks like there are quite a few repeated steps although it might be that I just don't know the build steps involved. :) Anyway, thanks for this fix.
