### ISSUE TITLE
Possible issue with splice_ptr_array

### ISSUE THREAD

**Issue by pmatos** [racket/racket#2686]
I might be just misunderstanding the function, but please bear with me. I looked at it because scan-build shows a possible null dereference.
![2019-06-06-211802_785x873_scrot](https://user-images.githubusercontent.com/7911/59060527-97d5e380-88a1-11e9-9faa-1dd9d310939a.png)

However, one of the things that scan-build is not aware of is that `al = length of a` and `bl = length of b`. So I think that the complaint is bogus. However, what might not be bogus is that if the assumptions are correct, the loop in the else branch is unnecessary because we will only enter it if `!b` in which case `bl == 0`.  What am I missing here?

**Comment by mflatt** [comment]
The intent here is that is `b` is `NULL`, then the element at `a[i]` is duplicated in place of every phantom element of `b`. It turns out that the function will never be called with `a` as `NULL` when `b` is `NULL` and `bl` is non-0. Actually, I don't think `a` can ever be `NULL`, since this function is triggered by a nested array in `a[i]`.

**Comment by pmatos** [comment]
I agree with you. So you're saying it's possible that `bl != 0` and `b == 0`? It's the only case where it makes sense to have the loop. In which case, there can be a null pointer dereference if `a == 0`. If you say that we cannot have `a ==0 && b == 0` then we can add a constraint to teach the analyzer that. Does this make sense?

**Comment by mflatt** [comment]
Yes.

**Comment by pmatos** [comment]
`assert` needs `#include <assert.h>` and xform doesn't seem to like it. Have to take a look at it since I am getting during compilation:
```
precompiled-header: line mismatch with precompiled: #"typedef unsigned char __u_char;" (line 1) versus #"extern void __assert_fail (const char *__assertion, const char *__file,"
```
