### ISSUE TITLE
run-bootstrap.rkt failed to generate linklets

### ISSUE THREAD

**Issue by pmatos** [racket/racket#2688]
After some discussions with @samth in slack I was attempting to get some linklets for a module.

I tried in: `racket/src/expander` subdir the following for the module `forty-two.rkt`
```
$ racket bootstrap-run.rkt -s -c out --linklets -l forty-two.rkt
compile: /home/pmatos/Projects/LT-racket/pkgs/racket-test-core/mzlib/forty-two.rkt
...during /home/pmatos/Projects/LT-racket/pkgs/racket-test-core/mzlib/forty-two.rkt...
open-input-file: cannot open input file
  path: /home/pmatos/Projects/LT-racket/pkgs/racket-test-core/mzlib/forty-two.rkt
  system error: No such file or directory; errno=2
  context...:
   /home/pmatos/Projects/LT-racket/racket/collects/racket/private/kw-file.rkt:102:2: call-with-input-file*61
   /home/pmatos/Projects/LT-racket/racket/collects/racket/private/more-scheme.rkt:261:28
   /home/pmatos/Projects/LT-racket/racket/src/expander/boot/handler.rkt:258:2: standard-module-name-resolver
   /home/pmatos/Projects/LT-racket/racket/src/expander/run.rkt:291:1
   "/home/pmatos/Projects/LT-racket/racket/src/expander/run.rkt": [running body]
   temp37_0
   for-loop
   run-module-instance!125
   for-loop
   [repeats 1 more time]
   run-module-instance!125
   perform-require!78
```

`forty-two.rkt`:
```
#lang racket
(printf "42")
```

Passing the full path doesn't help either but the error is different:
```
$ racket bootstrap-run.rkt -s -c out --linklets -l `pwd`/forty-two.rkt
standard-module-name-resolver: contract violation
  expected: module-path?
  given: '(lib "/home/pmatos/Projects/LT-racket/racket/src/expander/forty-two.rkt")
  context...:
   /home/pmatos/Projects/LT-racket/racket/src/expander/boot/handler.rkt:258:2: standard-module-name-resolver
   /home/pmatos/Projects/LT-racket/racket/src/expander/run.rkt:291:1
   "/home/pmatos/Projects/LT-racket/racket/src/expander/run.rkt": [running body]
   temp37_0
   for-loop
   run-module-instance!125
   for-loop
   [repeats 1 more time]
   run-module-instance!125
   perform-require!78
```

Is this simply broken or am I making some mistake here?

**Comment by pmatos** [comment]
Might be that I should have used the `-t` instead of `-l` flag but it still doesn't work ending up in:
```
Removing unused definitions...
Can remove 1438 of 5137 defined names, keeping 3699
Checking that references outside the runtime were removed by simplification...
Unfortunately, some linklets depend on pre-defined host instances
 that are not part of the runtime system; at least one the following
 references is a problem, but not necessarily all of them, because
 some references may be detected as unused by the flattener (but
 we've lost track of the connection):
```

which is slightly cryptic if you are looking at this for the first time. Nothing gets generated. I assume something went wrong but I don't understand what depending on host instances mean. It's such a simple example that, if it doesn't work for this example, I can't see how it works for anything else.

**Comment by mflatt** [comment]
A `#lang racket` program won't work, because extract mode only works when the residual of the phase-0 code doesn't refer to the expander, reader, etc. It's fairly constraining. The same module body should work with `#lang racket/base`, though.

**Comment by mflatt** [comment]
Thinking about this again, I think I got confused about what you're trying to do. The "some linklets depend on pre-defined host instances" error should only happen in `-x`/`--extract` mode. It shouldn't happen in `--linklets` mode. And a "forty-two.rkt" that uses `#lang racket` does work for me in `--linklets` mode.

But I see that the final linklet is printed in machine-independent bytecode form instead of source. That doesn't seem right, and I'll look into that more.

**Comment by pmatos** [comment]
Using current master I got what I needed from this. Thanks. Closing issue.
