### ISSUE TITLE
Function call with an extra argument can segfault Racket

### ISSUE THREAD

**Issue by sorawee** [racket/racket#2690]
The full code that demonstrates the bug is private, so I can't show it here. On the other hand, I can't find a minimal code that demonstrates the bug, but I can show this just in case it's useful.

```
;; main.rkt
#lang racket/base
(require "utils.rkt")
(define fun (choose (list f)))
(println fun)
(fun 1 2 3)
(displayln "after call")
```

```
;; utils.rkt
#lang racket/base
(provide f g choose)
(define (f a b)
  (displayln "called"))
(define (choose xs)
  (list-ref xs (random (length xs))))
```

Here's the output:

```
#<procedure:f>
[1]    8813 segmentation fault
```

In case it's helpful, in the actual `main.rkt`, I parameterize `current-namespace` and `current-compile` to `dynamic-require` some code to run before `(println fun)`. However, `(println fun)` (and hence the call to `fun`) is outside the parameterization. Also, arguments to `fun` contain objects from the other namespace.

**Comment by sorawee** [comment]
I will keep throwing more information here so that I do not forget.

On Linux, the error is a little bit different:

```
*** stack smashing detected ***: <unknown> terminated
[1]    3503 abort (core dumped)
```

It's also more sporadic. Sometimes, the arity mismatch error was raised correctly.

**Comment by pmatos** [comment]
@sorawee I was trying to repro this but `utils.rkt` provides a `g` without defining it.

**Comment by pmatos** [comment]
@sorawee can you still reproduce this?

**Comment by sorawee** [comment]
I can't, sorry. Closing...
