### ISSUE TITLE
Improve error message for missing last expression in begin

### ISSUE THREAD

**Issue by sorawee** [racket/racket#2696]
Missing an expression at the end of `define` body is a somewhat common problem (in StackOverflow):

- https://stackoverflow.com/questions/56568358/racket-scheme-nested-define
- https://stackoverflow.com/questions/16378703/a-strange-error-in-racket-no-expression-after-a-sequence-of-internal-definition
- https://stackoverflow.com/questions/56503105/how-to-fix-this-error-begin-possibly-implicit-no-expression-after-a-sequence
- https://stackoverflow.com/questions/17332236/differences-between-common-lisp-and-scheme-lexical-closures
- https://stackoverflow.com/questions/33403937/scheme-tail-recursion-bitson-count

A small example is:

```
(define (foo)
  1
  (define x 1))
```

which results in

```
begin (possibly implicit): no expression after a sequence of internal definitions in:
  (begin 2 (define x 1))
  2
  (define x 1)
```

While the error message makes sense at some level, it could be confusing (Is `2` an internal definition? Why are forms in `begin` shown twice -- one inside `begin` and one independently?).

I propose changing the error message to the following:

For a non-empty `begin` expression like `(begin 2 (define x 1))`:

```
begin (possibly implicit): required the last clause to be an expression; found:
 (define x 1) in:
 (begin 2 (define x 1))
```

For an empty `begin` expression like `(begin)`:

```
begin: required at least one expression
```

(The error message for `(define (foo))` is perfect already, I think. `(lambda ())` could be improved, but it's at least not confusing)

But if anyone has a better idea, feel free to suggest.

**Comment by samth** [comment]
That error message is here if you want to try it out: https://github.com/racket/racket/blob/master/racket/src/expander/expand/body.rkt#L260-L266

**Comment by rmculpepper** [comment]
The phrasing "the last form must be an expression" is inaccurate. For example, consider the following macro:

    (define-syntax-rule (define-and-call fun expr) (begin (define fun expr) (fun 0)))

Then `(let () (define-and-call f add1))` is allowed, but `(define-and-call f add1)` is not an expression.

How about "the subforms must end with an expression"? It might be good to add a paragraph to the docs about the nuances of "end with", too.

(I suppose I'm just saying that I interpret "end with" more flexibly than "the last form".)

**Comment by rmculpepper** [comment]
I see that the Guide has an index entry for "implicit begin", but it doesn't really clarify this issue, and the actual deftech anchor points to text talking about expressions only. My thoughts on how to improve it:

Add a margin note at the current "implicit begin" deftech site, something like "In fact, implicit begin generally allows definitions too. See (link to new reference section) for more details."

In the next paragraph, change "... a body after only internal definitions" to "... a body in an internal definition context". (This text describes an old restriction of internal definition contexts.)

Add a new subsection of section 3 in the reference for "Implicit Begin and Internal Definition Contexts" that discusses the nuances. (If there is such a section already, I missed it.) Link to the new section from the standard forms that have internal definition contexts. Maybe mention the alternative name "body".

**Comment by sorawee** [comment]
This is essentially resolved, closing.
