### ISSUE TITLE
`hash-ref` with C structs

### ISSUE THREAD

**Issue by pavpanchekha** [racket/racket#2702]
There seems to be a bad interaction between C structs and hash tables, but I'm having a lot of trouble minimizing it. It might be related to the garbage collector moving objects (as in bug #2263) but I'm not sure).

I can reproduce the bug by installing the `softposit-rkt` package and then running the `optional-posits` branch of Herbie (which I'm currently working on).

Reproducing
---

First, install `softposit-rkt`. It uses a C library and only supports Linux ☹:

    raco pkg install softposit-rkt

The get the `optional-posits` branch of Herbie:

    git clone https://github.com/uwplse/herbie herbie
    git -C herbie checkout optional-posits

Finally run Herbie:

    cd herbie
    racket src/herbie.rkt report bench/posits.rkt graphs/

I find that the error happens pretty consistently on some benchmarks but not on others, and it goes away when I run the benchmarks in a different order or one by one instead of in a loop, which is why I can't seem to minimize it.

Details
---

The `softposit-rkt` defines several C structs, including this one:

```
(define-cstruct _posit16 ([v _uint16]) #:malloc-mode 'atomic-interior)
```

Note that it's defined as `'atomic-interior` to avoid bug #2263.

Herbie then creates lists of `_posit16` objects (L316 in `src/points.rkt`, which calls L74 in `src/float.rkt`, which through L77 in `src/syntax/softposit.rkt` calls L318 in `softposit-rkt`) and uses these lists as the keys to a hash table (in `make-alt-table` in `src/core/alt-table.rkt`). However, sometimes when I look up a point in the hash table, it can't be found.

Here's an example of some code that [goes wrong](http://warfa.cs.washington.edu:8000/3-quad2mproblem321negative/graph.html):

```
(define (atab-min-errors atab)
  (for/list ([(pt ex) (in-pcontext (alt-table-context atab))])
    (point-rec-berr (dict-ref (alt-table-point->alts atab) pt))))
```

In this case, `(alt-table-point->alts atab)` has keys for each `pt` that is `(in-pcontext (alt-table-context atab))`; however, I sometimes get a `hash-ref` error here. I modified the code to execute the following when `dict-ref` failed:

```
(eprintf "equal? ~a has? ~a found? ~a\n"
             (length (filter (curry equal? pt) (dict-keys (alt-table-point->alts atab))))
             (dict-has-key? (alt-table-point->alts atab) pt)
             (and (dict-ref (alt-table-point->alts atab) pt false) true))
```

And I get the output

    equal? 1 has? #f found? #f

Indicating that the hash table has a key `equal?` to what I'm looking up, but `dict-has-key?` is returning `#f`.

The main Herbie branch (`develop`) does something very similar with the very same FFI structs and doesn't seem to have any problem. So I can totally believe this is a bug in Herbie, not in Racket.

**Comment by mflatt** [comment]
The problem may be that `#:malloc-mode` does not take effect when the struct ctype is used as the result type for a function. I'll fix that...

**Comment by pavpanchekha** [comment]
Matt, is there a workaround we could use? The support window for Herbie
goes back at least to 7.0. Though I suppose we could demand more for posit
support.

>

**Comment by mflatt** [comment]
It may make sense to check whether my current guess is really the problem, although I think it's likely.

Another approach is to use `#:property prop:equal+hash` in `define-cstruct` to specify custom equality and hashing functions. That's better if you'd really like to check whether two values represent the same number, and not just that they happen to be from the same allocation (but I haven't looked at the code in detail).

**Comment by pavpanchekha** [comment]
If the bug works as you describe (function outputs ignore malloc-mode) then
that would definitely cause this problem. I'm not sure how to check, though.

You're right that implementing equal+hash will work better anyway. I'll
look into how to do that. Thanks!

**Comment by pavpanchekha** [comment]
I believe I implemented this idea:
```
(define-cstruct _posit16 ([v _uint16])
  #:property prop:equal+hash
  (list (λ (x y f) (f (posit16-v x) (posit16-v y))) (λ (x f) (f (posit16-v x))) (λ (x f) (f (posit16-v x))))
  #:malloc-mode 'atomic-interior)
```
However, the crashes still occur, with more or less the same symptoms. Is there anything I did wrong? One thing I can think of is that adding a `#:property` causes Racket to generate a Racket struct wrapper around the C struct, and that Racket struct has `equal+hash` implemented; maybe it overwrites the property I'm trying to set.

**Comment by mflatt** [comment]
That's puzzling. Just to make sure, this program produces `'ok`, right?
```
#lang racket/base
(require ffi/unsafe)

(define-cstruct _posit16 ([v _uint16])
  #:property prop:equal+hash
  (list (λ (x y f) (f (posit16-v x) (posit16-v y))) (λ (x f) (f (posit16-v x))) (λ (x f) (f (posit16-v x))))
  #:malloc-mode 'atomic-interior)

(define ht (hash-set #hash() (make-posit16 77) 'ok))
(hash-ref ht (make-posit16 77))
```

**Comment by pavpanchekha** [comment]
Just ran it, it does indeed produce `'ok`.

**Comment by pavpanchekha** [comment]
After some more poking around, Matt's suggested workaround fixes this problem.
