### ISSUE TITLE
Surprising lexical scope with for/fold (redux)

### ISSUE THREAD

**Issue by toddjonker** [racket/racket#2703]
Even more surprising than #1659 is that the lexical scope appears to be inconsistent, perhaps depending on what's being iterated:
```
#lang racket
(for/fold ([x #f])
          ([x (in-value 1)])
  x)
(for/fold ([x #f])
          ([x (in-list '(2))])
  x)
(for/fold ([x #f])
          ([x '(3)])
  x)
```
returns
```
#f
2
3
```

I see the same results in DrRacket 5.3, 6.5, and 7.3 (the ones I happen to have around).

**Comment by AlexKnauth** [comment]
The `in-value` form behaves differently if you use it syntactically within the for-clause rather than define the sequence just outside and refer to it.
```racket
> (for/fold ([x #f])
            ([x (in-value 1)])
    x)
#false
> (let ([seq (in-value 1)])
    (for/fold ([x #f])
              ([x seq])
      x))
1
```

**Comment by AlexKnauth** [comment]
Has this been fixed by https://github.com/racket/racket/commit/94725ffb4eb39a34f95305cd15d224c8059a7e8e ?

**Comment by AlexKnauth** [comment]
This has been fixed by https://github.com/racket/racket/commit/94725ffb4eb39a34f95305cd15d224c8059a7e8e.
```racket
(test 1 'in-value-bind-correctly (for/fold ([x #f])
                                           ([x (in-value 1)])
                                   x))
```
