### ISSUE TITLE
Does not install on aarch64 (Jetson Nano) using recommended PPA

### ISSUE THREAD

**Issue by vegabook** [racket/racket#2737]
```
tbrowne@nano:~$ sudo apt-get install racket
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 racket : Depends: racket-common (= 6.11+dfsg1-1) but 7.3+ppa1-1~bionic1 is to be installed
          Recommends: racket-doc (>= 6.11+dfsg1) but it is not going to be installed
          Recommends: libjpeg62-turbo but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Full asciinema:

https://asciinema.org/a/OC515rCPH4RnyKtIoHGlccRNS

```
tbrowne@nano:~$ uname -a
Linux nano 4.9.140-tegra #2 SMP PREEMPT Sun Jun 16 19:25:32 BST 2019 aarch64 aarch64 aarch64 GNU/Linux
tbrowne@nano:~$ 

```

**Comment by pmatos** [comment]
@takikawa I know you are involved with Racket for Ubuntu. Do you know anything about this?

**Comment by takikawa** [comment]
Hi. AFAICT, the error is because Ubuntu is trying to fetch the 18.04 packages for Racket (which are at v6.11) because the PPA did not have arm64 packages available.

I just turned on arm64 built support and asked it to rebuild, so if the build goes ok there should be packages available soon.

**Comment by takikawa** [comment]
It looks like the amd64 build [was successful](https://launchpad.net/~plt/+archive/ubuntu/racket/+build/17265724). Please let me know if it still doesn't install.

**Comment by vegabook** [comment]
Works a charm thank you. 

![image](https://user-images.githubusercontent.com/3780883/61188624-f9942500-a679-11e9-9cf8-beb4b8f52ef4.png)
