### ISSUE TITLE
XDG Base Directory Support

### ISSUE THREAD

**Issue by billop** [racket/racket#2740]
Could support of [XDG Base Directories](https://wiki.archlinux.org/index.php/XDG_Base_Directory) be considered? It would be nice to be freedesktop.org compliant and use XDG base directories by default. The sooner this is fixed the better, since the more the incorrect behavior is assumed the more difficult it will be to fix, and racket would continue to pollute home directories.

**Comment by willghatch** [comment]
For what it's worth, I've created the [basedir](https://github.com/willghatch/racket-basedir) package for Racket for package authors to easily use the XDG basedir standard, though it doesn't help with the Racket core.

I would be in favor of moving the `~/.racket` directory contents and the `~/.racketrc` into appropriate XDG directories (with fallback behavior).

**Comment by lhanson** [comment]
This would be fantastic, there's no downside to respecting users' preferences.

**Comment by roket1428** [comment]
Any news?

**Comment by a-vrma** [comment]
workaround for now: `export PLTUSERHOME="$XDG_DATA_HOME"/racket`. You can use `~/.local/share` instead of `XDG_DATA_HOME`.

Stolen from https://wiki.archlinux.org/index.php/XDG_Base_Directory.

**Comment by sorawee** [comment]
Fixed. Closing.
