### ISSUE TITLE
Attempting to use local directory as catalog fails

### ISSUE THREAD

**Issue by pmatos** [racket/racket#2742]
I have installed racket using the normal `./configure && make` line from `racket/racket/src`. Then I want to install some base packages but I want them to be installed from the source dir if possible. So `raco pkg install compiler-lib` should not grab the package from the internet. It should instead install it from `racket/racket/pkgs/compiler-lib`. So I attempt to do:
```
# raco pkg install --no-setup --catalog /root/racket/pkgs/ compiler-lib
raco pkg install: cannot find package on catalogs
  package: compiler-lib
```

The problem seems to be the following line:
https://github.com/racket/racket/blob/5bb837661c12a9752c6a99f952c0e1b267645b33/racket/collects/pkg/private/catalog.rkt#L170

Somehow this line is creating a path for the pkg. If path is `/root/racket/pkgs`, it's looking for the file `/root/racket/pkgs/pkg/compiler-lib`. This doesn't exist. I think this is a mistake. There's no reason to append `"pkg"` here to the path as far as I am aware.

**Comment by mflatt** [comment]
A package catalog isn't the same as directory containing package sources. A catalog refers to sources but doesn't contain them. You can use `create-dirs-catalog` from `pkg/dirs-catalog` to build a catalog that points to a directory of package sources.

**Comment by pmatos** [comment]
@mflatt explained this on Slack. Closing. I was confusing package sources with the catalog itself.

**Comment by pmatos** [comment]
Thanks @mflatt !
