### ISSUE TITLE
class system binds init/field within their initializer expressions

### ISSUE THREAD

**Issue by tchajed** [racket/racket#2751]
If you have a function with the same name as an init argument (or field name), you can't use it as part of the initialization expression because the name is bound to a macro that throws an error:

```racket
#lang racket/base

(require racket/class)

(define (style) #t)

(define test%
  (class object%
    (init (style (style)))))

(new test%)
;; style: undefined;
;; cannot use before initialization
```

Would it be possible to make `(style)` refer to the outer function, and only throw the syntax error for later fields?

**Comment by mflatt** [comment]
Changing the scope of an initialization-argument binding would likely be incompatible with lots of existing Racket code.

In a case like this, I think you'll have to pick between choosing a different internal and external name for the initialization argument, as in
```
(init ([local-style style] (style)))
```
or accessing the `style` function through another name, as in
```
(define test%
  (let ([outer-style style])
    (class object%
      (init (style (outer-style))))))
```

**Comment by tchajed** [comment]
I think this change would only take previously broken code (as in code that throws a runtime error) and give it some behavior, but I can see that it's a big change.

I think internal names actually solve my problem pretty well, thanks for pointing that out!
