### ISSUE TITLE
RacketCS difference on make-known-char-range-list

### ISSUE THREAD

**Issue by rmculpepper** [racket/racket#2757]
One of the srfi/14 tests fails on RacketCS. Investigating revealed a difference in the result of `(make-known-char-range-list)`. Diffing the results (from Racket to RacketCS) gives:

    430c430
    <   (69216 69246 #t)
    ---
    >   (69216 69246 #f)
    595c595
    <   (194560 195101 #f)
    ---
    >   (194560 195101 #t)

**Comment by mflatt** [comment]
Probably related to 25a4f67912a1f9c4678e4b2b170ce275d3931c8f and the fact that `make-known-char-range-list` was not really implemented, so I'll do that now.
