### ISSUE TITLE
`resolve-module-path` in threads raises instantiate: unknown module

### ISSUE THREAD

**Issue by JustinHuPrime** [racket/racket#2758]
In a multithreaded program, calling `resolve-module-path` in multiple threads simultaneously raises an error with the message "instantiate: unknown module module name: '(resolved-module-path ...)" This error happens some of the time, and is only raised by some threads. I believe that this error is similar to the bug discussed [here](https://github.com/racket/racket/issues/2067#issuecomment-434797825).

Unfortunately, I do not have a simple example (this error is from code buried in a non-trivial codebase). However, if it would help, I can send you the code that is causing the problem.

**Comment by mflatt** [comment]
I think this is probably related to #3805 and #3128. The addition of `namespace-call-with-registry-lock` doesn't automatically fix `resolve-module-path`, but it provides a way to make multiple threads cooperate. I'll update the documentation to explain the problem and point to `namespace-call-with-registry-lock`.
