### ISSUE TITLE
Cross-phase persistent gensym?

### ISSUE THREAD

**Issue by gus-massa** [racket/racket#2760]
I think many modules of the low level part of racket are not cross-phase persistent because they have to create a `gensym` becuase they need their own `null`/`#f`/`nothing`/`none`. (I'm not sure how many.)

Is it possible to make a cross-phase-persistent-safe version of `gensym`. Perhaps it should not add a number to the name of the `gensym`. (I'm not sure if there is a technical problem that makes this impossible.)

**Comment by rmculpepper** [comment]
I thought most of the uses of `gensym` had been removed, since it also breaks deterministic compilation. The problem is the global counter; use `string->uninterned-symbol` instead.

**Comment by jackfirth** [comment]
@rmculpepper I think that specific kind of `gensym` use was removed only from macros that need to generate unique ids. Whereas @gus-massa seems to be talking about using `gensym` at runtime to create generative data types.

**Comment by gus-massa** [comment]
Yes, I was thinking in something like https://github.com/racket/racket/blob/ba8d442e754079178da0f95cfb6908524d10af6c/racket/src/thread/future-object.rkt#L27 or https://github.com/racket/racket/blob/ba8d442e754079178da0f95cfb6908524d10af6c/racket/collects/racket/struct.rkt#L11

Anyway, I underestimated the problems to make a cross-phase persistent module. See: https://github.com/racket/racket2-rfcs/issues/93

**Comment by mflatt** [comment]
I think allowing `gensym` for cross-phase persistent modules is probably ok and useful. In fact, I think I've considered that a time or two before; I forget why I abandoned the idea, but maybe it was one the general obstacles to making a module cross-phase persistent.

**Comment by rmculpepper** [comment]
The docs seem to say that `gensym` (and `string->uninterned-symbol`) are okay: https://docs.racket-lang.org/reference/syntax-model.html#(part._cross-phase._persistent-grammar)

**Comment by mflatt** [comment]
Well, that explains why I can't remember the reason for abandoning the change. :)

**Comment by gus-massa** [comment]
Ups, then it's better to close this.
