### ISSUE TITLE
mysql-connect: back end requested unsupported authentication plugin   plugin: "caching_sha2_password"

### ISSUE THREAD

**Issue by imxingquan** [racket/racket#2761]
this is my code , I used mysql8
#lang racket
(require db)
(mysql-connect #:server "127.0.0.1"
               #:port 3306
               #:database "db1"
               #:user "root"
               #:password "root"
               #:ssl 'no)
and run it  output window show this error messag:

mysql-connect: back end requested unsupported authentication plugin
  plugin: "caching_sha2_password"

**Comment by rmculpepper** [comment]
Support for caching_sha2_password will be in Racket 7.4. Could you try the pre-release build (https://pre-release.racket-lang.org) and see if it works for you?

You should also read the notes about MySQL Authentication[1]. One thing I forgot to say there, though, is that if the server rejects the fast path, you must use either TLS/SSL or a unix socket to connect. (That is, you can't do the slow path over TCP without TLS/SSL.) Once you connect, the server will cache your credentials and you can expect the fast path to work until the server clears its authentication cache.

[1] https://pre-release.racket-lang.org/doc/db/notes.html#(part._.My.S.Q.L_.Authentication)
