### ISSUE TITLE
Crash in 3m while testing mongodb

### ISSUE THREAD

**Issue by pmatos** [racket/racket#2764]
`raco test -p mongodb` crashes with `free(): invalid pointer`.
Backtrace suggests a GC issue.

Can't bisect but crash shows up between 7.1 and 7.2.

**Comment by pmatos** [comment]
This log was what triggered researching into this:
https://pkg-build.racket-lang.org/server/built/test-fail/mongodb.txt

@jeapostrophe noted that tests never pass because mongod is not installed anyway. 
Problem is that when `mongod` is not installed, we get an `exec failed`, not a racket crash. However, this assumption hid the failure (racket crash) for quite a few months - not @jeapostrophe fault though. We should strive to either run the test and shout when it fails than running and accepting failure just because...  I don't have yet a good solution for this, but I am hopefully proposing one soon - apologies for the rant.

**Comment by pmatos** [comment]
Some further analysis of the problem using racket master's HEAD (`7.4.0.2`).

I have reduced the problem to:
```
#lang racket/base

(subprocess (current-output-port) #f (current-error-port) (find-executable-path "does-not-exist") "-v")
```

which outputs:
```
$ racket ~/tmp/crash.rkt
#<subprocess>
#f
#<output-port:subprocess-stdin>
#f
free(): invalid pointer 
```

If on the other hand, I do not pass `"-v"`:
```
#lang racket/base

(subprocess (current-output-port) #f (current-error-port) (find-executable-path "does-not-exist"))
```
```
subprocess: contract violation
  expected: path-string?
  given: #f
  argument position: 4th
  other arguments...:
   #<output-port:stdout>
   #f
   #<output-port:stderr>
  context...:
   "/home/pmatos/tmp/crash.rkt": [running body]
```

Instead if I do:
```
$ racket ~/tmp/crash.rkt
#<subprocess>
#<input-port:subprocess-stdout>
#<output-port:subprocess-stdin>
#<input-port:subprocess-stderr>
```

So no problem either. It would be interesting, once we find out what's the problem, if our static analysis has caught it.

**Comment by pmatos** [comment]
Although we should probably never get to call `rktio_process` as:
```
rktio_process (rktio=0x555555aa9260, 
    command=0x7ffff6d35b88 "/home/pmatos/Projects/LT-racket/racket/src/racket/src/-v", argc=1, argv=0x7ffff6d35b48, 
    stdout_fd=0x555555aea6e0, stdin_fd=0x0, stderr_fd=0x555555aea700, group_proc=0x0, 
    current_directory=0x7ffff633c228 "/home/pmatos/Projects/LT-racket/racket/src/racket/src/", envvars=0x0, flags=0)
    at ./rktio_process.c:1410
```
(note the `command` variable)

the `free` that's problematic is the one in line 1536:
```
(gdb) 
1536              free(env);
(gdb) 
free(): invalid pointer
```

**Comment by pmatos** [comment]
I will prepare a PR

**Comment by pmatos** [comment]
Happy day... `scan-build`, the clang static analyzer actually finds this problem:
https://racket.gitlab.io/-/racket/-/jobs/259220574/artifacts/scan-report_mmm/2019-07-25-141422-5548-1/report-6fcd9c.html#EndPath

**Comment by mflatt** [comment]
That analysis seems to highlight a different problem.

Here's a patch intended to fix both problems, but maybe you're already working on a repair:
https://github.com/mflatt/racket/commit/b9dc884dae3ea06d62248715d7bb417b186afd7b

**Comment by pmatos** [comment]
@mflatt can you please merge that? The other thing I was looking at is that I think, but am not entirely sure, that we should capture the case where we pass `#false "-v"` to subprocess and not allow it to get into `rktio_process`. If we do, somehow `rktio_process` ends up being called with a command string like `/home/pmatos/.../-v`. I don't have time today to look at this but if you do, feel free to get it sorted. Thanks!

**Comment by mflatt** [comment]
The more I think about it, I'd prefer a slightly different change. (The bad `free` was arguably that `env` was abused for two different meanings, and those conflicted in the interpretation of a non-NULL value. So I may update before pushing, but it will be the same idea.

The behavior with `#f "-v"` as arguments is confusing but intentional. The `#f` in that case is interpreted as a group argument.

**Comment by pmatos** [comment]
@mflatt ok, thanks for the clarification and fix.
