### ISSUE TITLE
In chapter 7.3.8 of the guide, one of the contracts is incorrect

### ISSUE THREAD

**Issue by NieDzejkob** [racket/racket#2780]
Specifically, the "slightly cheaper version" contract at the end of this section will be broken when an input without newlines is passed, due to an off-by-one error in the contract -- `string-len/c` compares with `<`, and it's used as a replacement for `<=`.

**Comment by AlexKnauth** [comment]
A link to the rendered docs might be helpful:
https://docs.racket-lang.org/guide/contracts-general-functions.html#%28part._contracts-multiple%29
as well as to the current scribble source:
https://github.com/racket/racket/blob/68621c3ee1fa3bf105849877f11eb16a20273136/pkgs/racket-doc/scribblings/guide/contracts/general-function.scrbl#L476
