### ISSUE TITLE
syntax-source doc

### ISSUE THREAD

**Issue by joskoot** [racket/racket#2790]
Hi,

https://docs.racket-lang.org/reference/stxops.html?q=syntax-source#%28def._%28%28quote._~23~25kernel%29._syntax-source%29%29

states:

(syntax-source stx) → any

I suppose this should be:

(syntax-source stx) → any/c

Best wishes, Jos Koot

**Comment by gus-massa** [comment]
I think you are right. The error is in [reference/stx-ops.scrbl#Line36](https://github.com/racket/racket/blob/master/pkgs/racket-doc/scribblings/reference/stx-ops.scrbl#L36) , and there are other two similar errors in that file. Do you want to fix them and send a pull request? If not, we can fix it.

**Comment by mfelleisen** [comment]
any is okay for the co-domain of a contract; it's a "fast" version of any/c.

**Comment by joskoot** [comment]
Thanks, gus-massa and matthias felleisen.
Does 'any' in the docs not suggest that syntax-source might return a multiple value?
If in fact syntax-source always returns one value, the docs should indicate so, I think,
even if the code itself would use 'any' as a fast version of any/c.
BTW, I can't fix anything in racket. I don't think I am permitted to do pull requests.
Jos Koot

**Comment by mfelleisen** [comment]
You're correct that `any` includes `(values 1 2 3)` while `any/c` does not. Using the latter would tighten the contract by a bit.

**Comment by gus-massa** [comment]
@joskoot You can make a pull request [1]. The changes will be reviewed by us, and if approved they will be merged. (I recommend to start with something small, until you understand what kind of changes are approved.) Anyway, remember that comments and bug reports like this as welcome.

Thanks.

[1] It has many steps, but I think you know most of them:
- fork the racket repository in Github
- make a local clone in your computer
- make some changes
- save them in a branch
- push the branch with the changes to your fork in Github
- find the "compare and make a PR" button in Github
- write a short description (like the one you wrote here)

**Comment by mflatt** [comment]
(But in this case, the suggested change is already done... so, next time!)

**Comment by joskoot** [comment]
Thanks to all.
To be safe and to learn, can it be useful to do a pull request on an example repository of my own?
Never done that before. For my own repositories I simply use upload after testing on my PC.
Jos
