### ISSUE TITLE
"Macro stepper internal error" error box blocks other DrRacket interactions

### ISSUE THREAD

**Issue by jasonhemann** [racket/racket#2799]
In at least 7.0 and 7.4, when the macro-stepper encounters a `macro stepper error (derivation)`, and you click the link for Details, this raises a `Macro stepper internal error` error box.

That prevents interaction with other windows, e.g. even the `About DrRacket` menu bar on OSX. You can still _open_ this menu from the menu bar, but you cannot then close it. I did not expect this behavior. 

Presently working on an MWE to cause a macro-stepper error.

**Comment by rmculpepper** [comment]
I've pushed a change that should make it non-modal. Thanks for the report!
