### ISSUE TITLE
MZ_NORETURN causing problems in obscure configurations

### ISSUE THREAD

**Issue by pmatos** [racket/racket#2808]
There are some more obscure - less used - configurations where the `MZ_NORETURN` definition is causing problems.
1. 32-bit Windows build fails with Visual Studio 2017;
2. backtraces are more often disabled on 64-bit Linux;

@mflatt thinks 1 might be due to a compiler bug and 2 due to a problem in our slice of libunwind. I will investigate and propose a PR. Due to 2, http://drdr.racket-lang.org/52498/racket/share/pkgs/drracket-test/tests/drracket/repl-test-raw.rkt started failing.

**Comment by pmatos** [comment]
2. might not be the case. I have run the test `repl-test-raw.rkt` on checkout b7654d9a84 which predates any `NORETURN` work and the test was already failing then.

**Comment by pmatos** [comment]
Doing a bisect to confirm.

**Comment by pmatos** [comment]
I was confused. The problem is indeed `NORETURN` specifically in the `scheme_raise_exn` procedure:
```
3e301d22b50b210f6b3f36b01e037e07a20a3e74 is the first bad commit
commit 3e301d22b50b210f6b3f36b01e037e07a20a3e74
Author: Paulo Matos <pmatos@linki.tools>
Date:   Wed Feb 13 15:20:04 2019 +0100

    Mark scheme_raise_exn as noreturn - regenerate schemex
    
    scheme_raise_exn raises an exception and doesn't return.
    Static analysis tools find a huge amount of problems with regards
    to memory leaks that are actually false positives because the tools
    are not aware the function does not return. Marking it as such aids
    further inspection of real problems.

 racket/src/racket/src/schemef.h | 2 +-
 racket/src/racket/src/schemex.h | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)
```

**Comment by mflatt** [comment]
Would it be ok to go back to a preprocessor variable to enable annotations, maybe something like `MZ_PRECISE_RETURN_SPEC`?

**Comment by pmatos** [comment]
Yes, let's do that for now. My time has been limited to look at this. I am sorry. If you don't do this in the meantime, I add a PR first thing tomorrow. 

On 10 September 2019 16:59:18 CEST, Matthew Flatt <notifications@github.com> wrote:
>Would it be ok to go back to a preprocessor variable to enable
>annotations, maybe something like `MZ_PRECISE_RETURN_SPEC`?
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/racket/racket/issues/2808#issuecomment-529976668

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by pmatos** [comment]
@mflatt what's your best guess on the lifetime of Racket as default installation, as in before we make RacketCS the default? Months, years? I am attempting to plan where I should put my efforts with regards to Racket contributions. Given time is limited, it's better to put my time on things that will have a long shelf-life. :-)

**Comment by mflatt** [comment]
@pmatos My best guess is about 1 year, and I would also guess that my guess is on the optimistic side.

**Comment by pmatos** [comment]
@mflatt Thanks. Running some tests on https://github.com/LinkiTools/racket/commit/5ff2a8f91b08c2f3b53669c690606f1d22cc3164
Will create PR once it looks good.

**Comment by mflatt** [comment]
Change was merged.

**Comment by pmatos** [comment]
Thanks for closing this - I had forgotten.
