### ISSUE TITLE
please add label "good first issue"

### ISSUE THREAD

**Issue by spdegabrielle** [racket/racket#2810]
Only one issue in /racket is currently using "good-first-issue" switching to "good first issue" would make is easier for volunteers to find these tasks.
With the search: type:issue org:racket state:open label:"good first issue"
e.g. currently this query successfully finds these issues in /math /scribble and /drracket
https://github.com/search?q=type:issue+org:racket+state:open+label:%22good+first+issue%22

KR

Stephen

**Comment by pmatos** [comment]
Renamed `good-first-issue` to `good first issue`.

**Comment by pmatos** [comment]
...which in itself is a `good first issue`.
