### ISSUE TITLE
Macro-introduced uses of rename transformer references lose their macro-introduction scope and are considered syntax-original?

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#2818]
When a rename transformer is expanded, it is replaced with its target. This can affect `syntax-original?`-ness, since macro-introduction scopes may be lost. For example, see how Check Syntax interprets this program:

<img width="551" alt="Screen Shot 2019-09-14 at 13 07 57" src="https://user-images.githubusercontent.com/759911/64912174-28b62980-d6f1-11e9-8b59-8a70d52f5e5c.png">

I think the solution to this problem is to treat rename transformer expansions the same way as other macro applications, adding a fresh macro-introduction scope each time. Uses that actually are original should still be treated as references to the original variable by Check Syntax because the expansion will leave behind an `'origin` property, and `free-identifier=?` equivalences installed by rename transformers will cause Check Syntax to treat that as a reference to the original variable, too.

A side-effect of that change would be that rename transformers marked `'not-free-identifier=?` would *not* be treated as references to their targets by Check Syntax any longer. However, I think that’s actually probably the right behavior, so I think that’s okay.

**Comment by jackfirth** [comment]
> A side-effect of that change would be that rename transformers marked 'not-free-identifier=? would not be treated as references to their targets by Check Syntax any longer. However, I think that’s actually probably the right behavior, so I think that’s okay.

I've done some weird things with rename transformers and this seems to match my intuition. So 👍 to changing to this behavior.

**Comment by mflatt** [comment]
Repair was merged.
