### ISSUE TITLE
Scope pruning of local variable expansion makes macro-introduced identifiers `syntax-original?`

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#2820]
This is a very similar issue to #2818, but with a distinct cause: when a local variable is expanded, its scopes are pruned to be the same as the scopes on the original binding identifier (I do not know why). This causes problems for Check Syntax, since pruning of macro-introduction scopes may turn a macro-introduced reference `syntax-original?`:

<img width="536" alt="Screen Shot 2019-09-14 at 14 43 48" src="https://user-images.githubusercontent.com/759911/64913054-7e450300-d6fe-11e9-8cb1-60abf76a74a8.png">

I’m less sure how to fix this than I was about #2818. @mflatt, can you explain why this scope-pruning is performed in the first place?

**Comment by mflatt** [comment]
Scope pruning turns references within a fully expanded program into `bound-identifier=?` references. It was necessary in the old marks-and-renames expander to make re-expansion work, but it does not seem necessary in the same way with scope sets. In fact, we considered removing this pruning step in the scope-sets expander (and did at first); unfortunately, removing pruning breaks various things that rely on `bound-identifier=?` references in expansions, including Typed Racket. I forget the details, but after experimenting with changes to Typed Racket, we concluded that it was best to keep the pruning and `bound-identifier=?` property of expansions after all.

**Comment by lexi-lambda** [comment]
Thanks for the explanation. I’m okay with the pruning, but the way it affects `syntax-original?` seems wrong. Do you think it makes sense to add some extra information to the lexical context when a macro-introduction scope is pruned that is observed by `syntax-original?` (but does not affect `bound-identifier=?`)?

**Comment by mflatt** [comment]
Yes, I think we should do something. It may make sense to remove the "original" syntax property if the pre-pruned identifier has macro-introduction scopes (just in case the post-pruned identifier doesn't).

**Comment by mflatt** [comment]
@lexi-lambda Does that commit look like the right idea to you? (It does remove the arrow from "y" to "x" in your example.)

**Comment by lexi-lambda** [comment]
It looks good to me. Thank you for the fix!
