### ISSUE TITLE
When does ->i evaluate range contracts?

### ISSUE THREAD

**Issue by LiberalArtist** [racket/racket#2822]
The [docs for `->i`](https://docs.racket-lang.org/reference/function-contracts.html#(form._((lib._racket%2Fcontract%2Fbase..rkt)._-~3ei))) say:

> If all of the identifier positions of the range contract are _s (underscores), then the range contract expressions are evaluated when the function is called instead of when it returns. Otherwise, dependent range expressions are evaluated when the function returns.

This appears to be incorrect. In the following program, the range contract expression is evaluated only once, "at the time that the `->i` expression is evaluated rather than the time when the function is called or returns"—the same behavior `->i` documents for dependency-free domain contract expressions. Is that statement also meant to cover range contract expressions? If so, it was not clear to me.

```racket
#lang racket

(define/contract (foo x)
  (->i #:chaperone ([x any/c]) [_ (begin (println 'contract) any/c)])
  x)

'a
(foo 1)
'b
(foo 2)
'c
```
Output:
```
'contract
'a
1
'b
2
'c
```

**Comment by rfindler** [comment]
That's meant to be when there are dependencies (possibly zero of them, so
you just need parents in the right spot). When there are no dependencies,
then the contract expressions are evaluated when the ->i form is evaluated.

Robby

**Comment by LiberalArtist** [comment]
Thanks. I may take a stab at clarifying the docs. Are these the correct rules?

1. When the `->i` expression is evaluated, domain and range contract expressions with no dependencies (not even `()`)—regardless of whether their identifiers are `_`—are evaluated exactly once, in the order in which they appear. As consequence of "the order in which they appear", domain contract expressions come before range contract expressions.
2. When the function is called:
    1. Contracts expressions with dependencies for optional arguments that are not supplied are not evaluated at all.
    2. Other domain contract expressions with dependencies are evaluated according to the _dependency ordering rules_:
        1. If `y` depends on `x`, the `x` contract expression is evaluated before the `y` contract expression so that the `x` argument value, with its contract checked, is available during the evaluation of the `y` contract expression.
        2. When dependencies don't impose ordering constraints, contract expressions are evaluated in the order in which they appear.
    3. Pre-condition expressions are evaluated in the order in which they appear.
    4. If **all** of the range contract expressions have a literal `_` in the identifier position, any range contract expressions that have dependencies are evaluated according to the _dependency ordering rules_ (i.e. `2.i.a` & `2.i.b`).  Any range contract expressions that don't have dependencies were already evaluated under rule `1`.
3. When the function returns:
    1. If the range contract expressions weren't evaluated under rule `2.iv` (i.e. they don't all have `_` in the identifier position), any range contract expressions that have dependencies are evaluated according to the _dependency ordering rules_. Again, any range contract expressions that don't have dependencies were already evaluated under rule `1`.
    2. Post-condition expressions are evaluated in the order in which they appear.

Also, I think this example is buggy, because `x` and `y` may be `the-unsupplied-arg` instead of numbers when the range contract expression is evaluated:
```racket
(->i ()
     (#:x [x number?]
      #:y [y (x) (>=/c x)])
     [result (x y) (and/c number? (>=/c (+ x y)))])
```

**Comment by rfindler** [comment]
That sounds right to me, but mostly I'm struck by how bad English is as a medium for conveying this kind of information. If we feel we need that level of detail, probably a redex model is the way to go. 

As for that example, I agree. I'll push a fix. And I'll push an edit to the passage that you first referred to.

**Comment by sorawee** [comment]
As I understand, this issue is resolved. Feel free to reopen if that's not the case.
