### ISSUE TITLE
racket/gui Language Code Crashing DrRacket

### ISSUE THREAD

**Issue by akzaring** [racket/racket#2825]
The attached code (distilled from a larger body of code) sometimes crashes DrRacket 7.4 on an iMac running MacOS 10.14.6.  An Apple problem report is generated when DrRacket crashes.  The code always displays the get-choices-from-user box, but, when it dies, always dies before displaying the get-file browser.
[problem.ss.txt](https://github.com/racket/racket/files/3627444/problem.ss.txt)

**Comment by mflatt** [comment]
I haven't been able to replicate the crash. Can you send the generated crash report? You should be able to find old ones by running the "Console" application, selecting "User Reports", and finding a suitable entry in the middle panel that appers when you select "User Reports".

**Comment by mflatt** [comment]
Since it has been so long, we don't have more information, there have been many changes to Racket and `racket/gui` meanwhile, and we don't have similar reports so far, I'm closing as "unexplained".
