### ISSUE TITLE
macOS Catalina 10.15 Beta (19A573a) Save Issue

### ISSUE THREAD

**Issue by mmoore96** [racket/racket#2835]
When attempting to save a NEW Racket project/file I get the error message in terminal:
2019-09-25 15:10:50.988 DrRacket[1226:12023] WARNING: <NSSavePanel: 0x134017490> running implicitly; please run panels using NSSavePanel rather than NSApplication.

The project cannot be saved. However, if I import an existing racket project that I have previously saved on a non-mac machine, it will then save the file without any issue.

I am running Dr. Racket  version 7.4 [3m]

**Comment by mflatt** [comment]
This is a little bit of a shot in the dark, but does it help to change "share/pkgs/gui-lib/mred/private/wx/cocoa/filedialog.rkt" on line 118 from `(tell app runModalForWindow: ns)` to `(tellv ns runModal)`?

(You should be able to directly edit that file and then restart DrRacket.)

**Comment by mmoore96** [comment]
That actually worked!!! Thank you very much!

**Comment by mmoore96** [comment]
@mflatt Do other users using macOS Catalina have this same problem? and if so, will this be fixed in a future update?

**Comment by mflatt** [comment]
Thanks for the report and quick test!

I've pushed a repair for the next Racket release, which is scheduled for sometime in October. The fix will also be in the next round of snapshot builds at https://pre.racket-lang.org . It would be great if you can try a snapshot (after 24 hours or so from now) to make sure I didn't mangle the repair.
