### ISSUE TITLE
Opening Dr. Racket in macOS Catalina 10.15 Beta (19A573a)

### ISSUE THREAD

**Issue by mmoore96** [racket/racket#2836]
When attempting to open Dr. Racket via Toolbar on macOS Catalina it will give me the following error in terminal: Sep 25 15:20:03 ip-168-26-142-208 com.apple.xpc.launchd[1] (org.racket-lang.DrRacket.20568[1417]): Service exited with abnormal code: 1

The workaround for this is to open finder and open the folder "Racket v7.4" > Right click on Dr. Racket Icon > Click "Show Packet Contents" >  Click "Contents" > Click "macOS" > Click the Dr. Racket Unix executable and it will run.

Terminal will run the following:
~ % /Applications/Racket\ v7.4/DrRacket.app/Contents/MacOS/DrRacket ; exit;

**Comment by mflatt** [comment]
Does double-clicking the DrRacket applicaiton fail in the same way? If so, does it help to drag the "DrRacket" application out of the "Racket" folder (may require Command-drag) and then drag it back? Although that may sound crazy, it can be a signal to the OS that you trust the application, which can fix the problem if it's related to signing.

**Comment by mmoore96** [comment]
That worked, which I cannot believe. Thank you! 
Do other users using macOS Catalina have this same problem? and if so, will this be fixed in a future update?

**Comment by mflatt** [comment]
We'll have to investidate more. Maybe Apple is imposing yet another requirement on application signing.

**Comment by qubist** [comment]
When I click on the icon, right-click to open, or follow @mmoore96's instructions, i get this window, 5 times:
<img width="372" alt="Screen Shot 2020-12-03 at 7 52 31 PM" src="https://user-images.githubusercontent.com/3607279/101107884-4f37dd00-35a1-11eb-9a62-2c7dd814a142.png">

**Comment by mflatt** [comment]
Thanks for checking v7.9. We forgot to mention that the problem was fixed and close this PR after signing executables in later releases.

**Comment by chipotle** [comment]
For the record, I just downloaded Racket 8.0 today and had this exact same mystifying problem when I tried to launch Dr. Racket -- and indeed, dragging the executable to the desktop and then back to the Racket folder fixed the issue. (And I'm even on Catalina, albeit the current 10.15.7 release.)
