### ISSUE TITLE
racket/exists doesn't

### ISSUE THREAD

**Issue by LiberalArtist** [racket/racket#2837]
The [contracts guide](https://docs.racket-lang.org/guide/contracts-gotchas.html#(mod-path._racket%2Fexists)) refers to a `#lang racket/exists`:
https://github.com/racket/racket/blob/01de71981b45d59c059864cd3b071b6e6449a167/pkgs/racket-doc/scribblings/guide/contracts/gotchas.scrbl#L123-L130
However, ironically, `racket/exists` does not appear to exist. Trying to use it in 7.4 CS reports "collection not found for module path," and I'm not having any luck finding it in the Git history, either.

**Comment by rfindler** [comment]
I think that we probably have to delete this paragraph from the guide, sadly.

**Comment by zyrolasting** [comment]
PR open in case others agree.

**Comment by bennn** [comment]
#2873
