### ISSUE TITLE
odd behavior - Mac OS X Mojave, DrRacket 7.4, big-bang 

### ISSUE THREAD

**Issue by smtuttle** [racket/racket#2838]
Is anyone else seeing this happen to them?

While running DrRacket 7.4, 
on Mac OS X Mojave, 
running a Racket program that has at least one, but usually more than one, calls to 2htdp/universe’s big-bang,

…DrRacket will just become non-responsive. Sometimes there has been a World window open, sometimes there has not been. The little figure in the lower right is stopped mid-run, 
but clicking the Stop button does not have an effect. If there is a World window open at the time, trying to close it has no effect. Trying to close the DrRacket window has no effect. I end up force-quitting DrRacket, and when I restart DrRacket and run the same program, it typically works the next time.

It is intermittent, but has happened during class, which means I at least got to warn them to stop DrRacket in the Windows Task Manager or force-quit it if this happens. But it is worrisome, since I don’t recall this kind of thing happening in previous versions of DrRacket.

**Comment by jbclements** [comment]
Actually, yes I have. I was working on a little game with my son, and ran into something like this a whole lot.

In my case, it appears to only have happened when there were one or more test case failures, and it appeared to me that it was getting wedged on trying to display error messages while setting up the big bang window. In my experience, the big bang window was never displayed.

One additional piece of information; my reflex when something bad happens is to hit cmd-K, which caused a strange visual artifact; the drop shadow of the pull-down “I stopped your program” dialog gets displayed, but not the dialog itself. I have screenshots of this on my machine at home, but I hadn’t bothered to file an Issue for it yet. I also have a copy of the way the source looked the last time it occurred.

John

**Comment by mflatt** [comment]
This problem was fixed in racket/gui@d743716f5c728652e4d14c9224cdc9e3e2df134a.
