### ISSUE TITLE
Invalid flag passed to git during build

### ISSUE THREAD

**Issue by pmatos** [racket/racket#2854]
During a racketcs build, it looks like `git` is being called as I see these in my logs:
```
error: unknown option `exclude=*'
usage: git describe [<options>] [<commit-ish>...]
   or: git describe [<options>] --dirty

    --contains            find the tag that comes after the commit
    --debug               debug search strategy on stderr
    --all                 use any ref
    --tags                use any tag, even unannotated
    --long                always use long format
    --first-parent        only follow first parent
    --abbrev[=<n>]        use <n> digits to display SHA-1s
    --exact-match         only output exact matches
    --candidates <n>      consider <n> most recent tags (default: 10)
    --match <pattern>     only consider tags matching <pattern>
    --always              show abbreviated commit object as fallback
    --dirty[=<mark>]      append <mark> on dirty working tree (default: "-dirty")
```

**Comment by pmatos** [comment]
Problem stems from `racket/src/build/ChezScheme/s/update-revision:  git describe --always --exclude='*' --abbrev=40 --dirty`

This flag is not supported in git 2.11.0 (default in debian stretch) - althought it works fine on recent `git`s. 2.11 is from around 2017 so not terrible old but no modern either.

This means I should probably upgrade my docker images to something more recent. Closing.

**Comment by mflatt** [comment]
Another possibility may be to adjust `update-revision` to use `--include` with a pattern that matches nothing.

I'm pretty sure I made that change in some exploration, but I forget why I didn't keep it.

**Comment by pmatos** [comment]
True - however, I tend to favour solutions that don't require us to support old software/platforms/etc. In the long term, it's a huge amount of work and hacks to favour the very few which for some reason don't upgrade. However, if it's just a change of `--exclude=*` to an include, I can take a look once I have a bit of time (I am a bit squeezed atm). Reopening.

**Comment by mflatt** [comment]
I changed `update-revision` to use `-match=''` back in 7675d58fb2b4c6f19343dab7a724ce84ce51b233.
