### ISSUE TITLE
The error message of `require`-ing a non-existent file is not helpful

### ISSUE THREAD

**Issue by edom** [racket/racket#2855]
### Version

Racket 7.4 on Debian 9.

### How to reproduce

Save this in `a.rkt`.

```
#lang racket/base
(require b)
```

Run `racket -t a.rkt`.

The problem: The error message does not mention `a.rkt`.

### What is expected

The error message should also mention the path of the offending source (`a.rkt`).

**Comment by sorawee** [comment]
Duplicate of #2680
