### ISSUE TITLE
Scroll lags on retina displays

### ISSUE THREAD

**Issue by jackpmastrangelo** [racket/racket#2861]
When using Dr. Racket on a retina display, scrolling lags noticeably.

If you run Dr. Racket using "low resolution mode" (my machine is OSX 10.14.5 2017 Macbook Pro)
the scrolling improves and there is no lag.

Just ran this on the latest nightly build available on pre.lang-racket.org SHA1: 0a16a38d09dcb609a742f960575408661c785f7b

**Comment by yjqww6** [comment]
Here is a hack for this: https://github.com/yjqww6/drracket-responsive-scrolling
You could try it until DrRacket solves this problem.

**Comment by sorawee** [comment]
@jackpmastrangelo  Is it better now in Racket 7.6?

**Comment by sorawee** [comment]
I tested it on Racket 7.6 and it now scrolls smoothly. So I will close the issue. Feel free to reopen it if it's not the case for you.
