### ISSUE TITLE
stream leaking memory

### ISSUE THREAD

**Issue by joskoot** [racket/racket#2870]
The piece of code shown below leaks memory.
When commenting out the marked cond-case, which calls stream-empty?,
no memory is leaked.

```
#lang racket

(define (naturals n) (stream-cons n (naturals (add1 n))))

; Copied from Racket-7.4.10/collects/racket/stream.rkt
(define (stream-ref st i)
  (unless (stream? st) (raise-argument-error 'stream-ref "stream?" st))
  (unless (exact-nonnegative-integer? i)
    (raise-argument-error 'stream-ref "exact-nonnegative-integer?" i))
  (let loop ([n i] [s st])
    (cond
   ;=====================================================
     [(stream-empty? s)
      (raise-arguments-error 'stream-ref
                             "stream ended before index"
                             "index" i
                             "stream" st)]
   ;=====================================================
     [(zero? n)
      (stream-first s)]
     [else
      (loop (sub1 n) (stream-rest s))])))

(stream-ref (naturals 0) 1000000000000000000)
```

I guess the struct-type-property defined in
Racket-7.4.10/collects/racket/private/for.rkt
causes the trouble. It is used in the following definition in module
Racket-7.4.10/collects/racket/private/stream-cons.rkt

```
(define-struct stream (promise) 
  #:mutable
  #:property for:prop:stream (vector
                              stream-null?
                              stream-car
                              stream-cdr))
```

Sorry, indenting is lost.
I don't know how to preserve indentation in a GitHub issue.
Best wishes, Jos

**Comment by jackfirth** [comment]
You can preserve indentation by inserting a line with three backticks (```) before and after your code. See [here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) for examples.

**Comment by joskoot** [comment]
Thanks Jack, next time I’ll do better.
Jos Koot

**Comment by joskoot** [comment]
To Sam,: well pointed! You’re absolutely right.
However, it’s not my code, it is Racket’s code: Racket-7.4.10/collects/racket/stream.rkt.

To all: can someone fix this?

Thanks, Jos

**Comment by gus-massa** [comment]
I think the current error message is correct. It should show the original stream `st` instead of only the tail of the steam `s`. The additional memory usage is not avoidable.

**Comment by samth** [comment]
In situations like this, it makes streams a not very useful version of themselves to have this behavior. What if we used a weak box here to sometimes give the full stream in the error message?

**Comment by joskoot** [comment]
I strongly disagree with gus-massa.
Whenever garbage collection is possible, stream traversal should be done in bound space.
That’s where streams have been designed for (SRFI 41)
Bound space traversal is more important than the error message, I think.
An error message necessarily points to the spot where the error is detected rather than to the spot where the error was made. 
Jos

**Comment by mflatt** [comment]
I've had enough recent experience with streams to agree that keeping `st` for an error damages the usefulness of the functions (especially `stream-take`), so I'm planning to make the change.
