### ISSUE TITLE
Documented signatures for `bound-id-set-map` and `bound-id-set-for-each` incorrect

### ISSUE THREAD

**Issue by rocketnia** [racket/racket#2881]
The documented signatures for `bound-id-set-map` and `bound-id-set-for-each` seem wrong:

```
@defproc[(bound-id-set-map [s bound-id-set?]) list?]
@defproc[(bound-id-set-for-each [s bound-id-set?]) void?]
```

The documentation suggests they're comparable to `free-id-set-map` and `free-id-set-for-each`, which each take a function to call on each element, but that argument is missing here.

Calling `procedure-arity` confirms that these procedures have arities of 2, so I think this is simply a documentation issue.

**Comment by gus-massa** [comment]
I think it's an error in the docs, the unary version makes no sense. 

Do you want to send a PR? If not, we can fix it instead.

**Comment by rocketnia** [comment]
Thanks for suggesting to make a PR. This is my first PR for Racket, and it was a good excuse to speed with the build instructions and contributing guidelines. :)

**Comment by gus-massa** [comment]
Merged in https://github.com/racket/racket/commit/73dd32cd51a3b008a5ed0b471f859830287a4a2f . Thanks!
