### ISSUE TITLE
Docs incorrectly claim `get/build-late-neg-projection` is in `racket/contract/combinator`

### ISSUE THREAD

**Issue by rocketnia** [racket/racket#2883]
The docs say `get/build-late-neg-projection` is provided from

* `racket/contract/combinator`,
* `racket/contract`, and
* `racket`.

However, it's actually not provided from `racket/contract/combinator`. Instead, it's provided from `racket/contract/base` (and this fact is undocumented).

I've been working around this by requiring it from `racket/contract`, since that's the most specific require spec that's consistent with the documentation.

I'm not sure what I consider "expected behavior" here. It looks like `racket/contract/combinator` is meant for people who are implementing new contract combinators, so it *would* be a great home for `get/build-late-neg-projection`. On the other hand, changing the documentation might have fewer backwards-compatibility issues than changing the behavior.

**Comment by spdegabrielle** [comment]
Hi @rocketnia is this resolved?

**Comment by rocketnia** [comment]
No, as of Racket 7.7, the situation is still as I described.

**Comment by jackfirth** [comment]
I think changing the behavior isn't an option, it's too likely to break code. We'll have to change the docs.

**Comment by xxyzz** [comment]
`get/build-val-first-projection` is also provided from`racket/contract/base`. I'd like to help but don't know how to change the doc. Will move the doc of these two procedures to another section solve the issue?

**Comment by jackfirth** [comment]
@xxyzz Yes, moving the `defproc` form to the right section should fix it.
