### ISSUE TITLE
displayln has no ouput in a thread

### ISSUE THREAD

**Issue by yangh** [racket/racket#2889]
Hi Racket

I'm trying to print some log with displayln in a thread, but it never shows up when I run the program in a terminal, and it shows up in the interactive window when I run it with in drracket.

Example code:

```lisp
#lang racket

(displayln "Main thread message 1")

(thread
 (lambda ()
   (displayln "displayln: Thread message")
   (printf "printf: Thread messag\n")))

(displayln "Main thread message 2")
```
drracket interactive window output:

```shell
Main thread message 1
#<thread:...st-displayln.rkt:6:1>
displayln: Thread message
printf: Thread messag
Main thread message 2
```
terminal output:

```shell
$ racket test-displayln.rkt 
Main thread message 1
#<thread:...st-displayln.rkt:6:1>
Main thread message 2
```

Racket v7.4

**Comment by rmculpepper** [comment]
The racket process exits when the main thread finishes, even if there are other threads still running. If you wait on the other thread to complete, you'll get its output:

    #lang racket

    (displayln "Main thread message 1")

    (define t
      (thread
       (lambda ()
         (displayln "displayln: Thread message")
         (printf "printf: Thread messag\n"))))

    (displayln "Main thread message 2")

    (thread-wait t)

**Comment by yangh** [comment]
Got it, Thanks, @rmculpepper
