### ISSUE TITLE
IME does not work well 

### ISSUE THREAD

**Issue by kerwinxu** [racket/racket#2899]
win10 , microsoft pinyin IME , 
1, IME cannot follow cursor 
2, Only the first entry of the IME can be entered.

**Comment by mflatt** [comment]
Thanks for the report! Does using the content of

 https://gist.github.com/mflatt/1c9c367b4fe5bdb86e99aa69b9f55890

as a replacement for

 Racket\share\pkgs\gui-lib\mred\private\wx\win32\queue.rkt

solve the problem? You can simply overwrite the existing "queue.rkt" with the replacement, and Racket should start up.

**Comment by mflatt** [comment]
I've merged this change to https://github.com/racket/gui/commit/823e940809e41db54f9d14abdef3288d4554388d , so it will be in the next round of snapshot builds. Unfortunately, the repair is too late to make it into the upcoming v7.5 release.

**Comment by pmatos** [comment]
@kerwinxu Can you please confirm the fix or close the bug?

**Comment by sorawee** [comment]
@kerwinxu Racket 7.6, which included the fix, was released for a while. Could you confirm that the fix works?

**Comment by sorawee** [comment]
It looks like the original bug was fixed, and any remaining issue is now reported at #3350, so let me close this issue. Feel free to reopen if you disagree.
