### ISSUE TITLE
builtin struct property accessors can't pass struct-type-property-accessor-procedure? 

### ISSUE THREAD

**Issue by capfredf** [racket/racket#2904]
when given a struct property accessor, struct-type-property-accessor-procedure? should true.
But it looks like built-in ones fail to pass this test.
```
> (struct-type-property-accessor-procedure? custom-write-accessor)
#f
> (struct-type-property-accessor-procedure? custom-print-quotable-accessor)
#f
> (define-values (p p? p-ref) (make-struct-type-property 'p))
> (struct-type-property-accessor-procedure? p-ref)
#t
```

**Comment by mflatt** [comment]
It looks like this may have been intentional after all, because commit 39a96dd699a goes out of its way to add a wrapper that hides the provenance of these accessors. I think that was probably a bad idea, though, and I'm inclined to revert the change.
