### ISSUE TITLE
GUI - text% class - a clickback doesn't change style on a button-down event

### ISSUE THREAD

**Issue by haijinSk** [racket/racket#2909]
A clickback is installed with the hilite-delta, but the clickback region's style is not changed when the clickback is selected (= button-down event).

I'm a Racket and programming beginner, but my point of view is: 

The text% class has a private field - a list of installed clickbacks defined as: (define clickbacks null). A clickback is a struct with data about clickback and the one struct's field is named "hilited?".

This "hilited?" bit/piece of data about clickback works according the button-down event. It is set to #t - when you click and you are still holding the mouse over the clickback. 

But any method/code in the text% class for changing the style according the clickbacks's "hilited?" value is never called. 

I love Racket. Thank you very much for your talent, time and energy.

---

;; Please, run the code and click the link (a clickback) in the opened gui window.

#lang racket
(require racket/gui/base)
(require framework/gui-utils)

(define f (new frame% [label "Simple Edit"]
               [width 300]
               [height 200]))
(define c (new editor-canvas% [parent f]))
(define t (new text%))

(send c set-editor t)
(send f show #t)

(send t insert "Clickback doesn't change style") ; on button-down event
(send t change-style (gui-utils:get-clickback-delta) 0 30)
(send t set-clickback 0 30
      (lambda (obj start end)
        (displayln "Button up"))
      (gui-utils:get-clicked-clickback-delta) ; delta
      #f) ; If I understand it, #f means:
          ; change the style (with delta) on mouse button-down event, then give the old style (without this delta) back
          ; but it doesn't work, the style is not changed on button-down event.
         
;; https://docs.racket-lang.org/gui/text_.html#%28meth._%28%2%28lib._mred%2Fmain..rkt%29._text~25%29._set-clickback%29%29

**Comment by mflatt** [comment]
Thanks for the report! It looks like clickback highlighting has been broken since the `racket/gui` rewrite 10 years ago!

**Comment by haijinSk** [comment]
Glad I could help. Thank you very much for Racket.

**Comment by mflatt** [comment]
Was fixed in racket/gui@bdd1b4e827161f509cfbffb033f2d52723cea046.
