### ISSUE TITLE
Error message in bad function call loses function name

### ISSUE THREAD

**Issue by jessealama** [racket/racket#2914]
I'm on macOS Catalina, 7.4., CS variant. I noticed that if you incorrectly use the circle function in the slideshow language, like doing this at the command line

````
racket -I slideshow --eval '(circle 10 20)'
````

you get an error message where the function name (here, `circle`) gets lost:

````
loc_2999: arity mismatch;
 the expected number of arguments does not match the given number
  ...
````

Shouldn't it be:

````
circle: arity mismatch;
 the expected number of arguments does not match the given number
  ...
````
?

My understanding is that this is the error message on the regular (non-CS) 7.4 variant of Racket, so I suspect something is up with the CS expander.

(This example is taken from early on in the [Quick](https://docs.racket-lang.org/quick/index.html) tutorial.)

**Comment by capfredf** [comment]
I think this bug has been fixed already
```
Welcome to Racket v7.5.0.8 [cs].
> (circle 10 20)
; circle: arity mismatch;
;  the expected number of arguments does not match the given number
;   expected: 1 plus optional arguments with keywords #:border-color and
;     #:border-width
;   given: 2
; [,bt for context]
```

**Comment by jessealama** [comment]
Now that 7.5 is officially out, I see that the bug has indeed been fixed. I'm closing this issue.
