### ISSUE TITLE
[CS] struct accessor exception incorrectly calls custom-write

### ISSUE THREAD

**Issue by jamesbornholt** [racket/racket#2926]
This program shouldn't call the `bitvector`'s `write-proc`, because `#f` is not a `bitvector?`:

```racket
(struct bitvector (size)
  #:methods gen:custom-write
  [(define (write-proc self port m)
     (/ 1 0))])

(bitvector-size #f)
```

But if you add enough dead code to the program, it will call `write-proc` and trip the division by zero. See here: https://gist.github.com/jamesbornholt/0a03d34f6c13f654bf76b8b91358116d -- this crashes with division by zero, but if you remove any one of the `dead-code` procedures, it instead throws the expected contract violation about `#f` not being a `bitvector?`. If you swap to the commented out version of `write-proc`, it will infinite loop (because it calls bitvector-size recursively).

This happens on the CS variant of 7.5 but not on the regular variant, which always throws the expected contract violation. It has caused some breakage for us in [Serval](https://github.com/uw-unsat/serval) and Rosette while testing CS.

---

It seems like what's going on is that the exception behavior is changing depending on the size of the program. For smaller programs, we get this Racket contract violation (which we'd expect):

```
bitvector-size: contract violation
  expected: bitvector?
  given: #f
  context...:
   do-raise-argument-error
   /Users/james/code/rosette/bv.rkt:9:0
   call-with-values
   body of "/Users/james/code/rosette/bv.rkt"
   temp37_0
   for-loop
   run-module-instance!125
   perform-require!78
   namespace-require+
   #%for-each
```

but with enough dead code we instead get this Chez error (after changing `write-proc` to just print `(bitvector)` rather than infinite looping or crashing):

```
#f is not of type (bitvector)
  context...:
   condition->exn
   do-raise
   dynamic-wind
   proc
   call-with-values
   body of "/Users/james/code/rosette/bv.rkt"
   temp37_0
   for-loop
   run-module-instance!125
   perform-require!78
   namespace-require+
   #%for-each
```

**Comment by mflatt** [comment]
JFYI, the change depending on the amount of dead code has to do with the way Racket CS avoids sending too-large code blocks to Chez Scheme. That's why the second commit referenced above is related to non-inlined selectors. (The first commit more directly fixes the bug in the printer, though, that the non-inlined error happened to trip over.)

**Comment by jamesbornholt** [comment]
Thanks for the quick fix!
