### ISSUE TITLE
Flaky tests in tests/racket/test

### ISSUE THREAD

**Issue by pmatos** [racket/racket#2930]
Commit https://github.com/racket/racket/commit/bdce2c8be76ac25769ccecf0b320061d0ca9804c reverted a previous commit that added CI testing of `tests/racket/test`. 

As explained in the description there are a few flaky tests that need to be fixed before being added again to CI. 

- [x] Section places
```
Section(places)
open-input-file: the custodian has been shut down
  custodian: #<custodian>
  context...:
   default-load-handler
   standard-module-name-resolver
   module-path-index-resolve
   do-dynamic-require5
   /home/runner/work/racket/racketcgc/collects/racket/place/private/th-place.rkt:70:21
Hello from place
Hello form place 2
```
- [x] Section generator
```
Section(generator)
ERROR: doubling an `in-producer` sequence seems to take more than twice as long
```

**Comment by samth** [comment]
Note that these tests failed running on racketcgc.

**Comment by samth** [comment]
I reproduced the "places" issue consistently with racketcgc on my machine. I haven't reproduced the "generator" issue.

**Comment by mflatt** [comment]
Maybe we should just skip memory- and performance-intensive tests for racketcgc?

Note that true places are not supported on racketcgc. They're simulated using Racket threads. Maybe the simulation could be improved, but it doesn't sound worth much effort.

**Comment by pmatos** [comment]
Sure - I will leave this open until I add the tests for 3m and cs to see if there are repeats.

**Comment by samth** [comment]
A small amount more debugging -- the place test _only_ fails when run under `quiet.rktl`, so I'm not sure yet what part of the test is failing.

**Comment by mflatt** [comment]
Looks like the `place-kill` problem is a real bug in non-places places and easily fixed, so I'll push a repair.

**Comment by mflatt** [comment]
I think the two commits should fix these two problems.

**Comment by pmatos** [comment]
I am testing these now - thanks.

**Comment by pmatos** [comment]
@mflatt looks good, thanks.
