### ISSUE TITLE
Section sandbox fails to test

### ISSUE THREAD

**Issue by pmatos** [racket/racket#2933]
CI run is here: 
https://github.com/LinkiTools/racket/runs/322602794#step:8:420

```
Section(sandbox)
ERROR: current-load-relative-directory: `exists' access denied for /home/runner/work/racket/racket/pkgs/racket-test-core/tests/racket/
##[error]Process completed with exit code 2.
```

This is run with `racket -l quiet.rktl sandbox.rktl` in the racket tests package folder.

**Comment by mflatt** [comment]
The failure is because "racket-test-core" is not installed as a package, so the current directory when running the test is not in the space of directories that a sandbox allows for reading. I think the solution is to install the "racket-test-core" package before using its content.

**Comment by pmatos** [comment]
Yes - that's right. Closing.
