### ISSUE TITLE
Build failed under Termux (Android)

### ISSUE THREAD

**Issue by dram** [racket/racket#2947]
Following error is encountered, when trying to build Racket (git master) under Termux (a Linux environment for Android):

```
...
gcc -g -O2 -Wall   -I. -I. -o rktio_dll.o -c ./rktio_dll.c
./rktio_dll.c:313:32: error: use of undeclared identifier
      'scheme_start_atomic_no_break'
      adjustment = ((uintptr_t)scheme_start_atomic_no_break
                               ^
1 error generated.
make[9]: *** [Makefile:128: rktio_dll.o] Error 1
...
```

**Comment by pmatos** [comment]
@dram Thanks - I can reproduce on a Pixel C. I will take a look.

**Comment by pmatos** [comment]
the `scheme_start_atomic_no_break` is defined in `thread.c`, not in `rktio`. 
@mflatt Is it ok to include `scheme.h` from `rktio`?

**Comment by mflatt** [comment]
No, but that's supposed to be `rktio_dll_find_object`, anyway — directly referencing the same function as the `dlsym` call. I'll push a repair.
