### ISSUE TITLE
Stack-checkpoint error: two values in single value context on v7.5.0.8 [cs]

### ISSUE THREAD

**Issue by joergen7** [racket/racket#2951]
Racket: version 7.5.0.8--2019-12-04(-/f) [cs]
git sha1 id: 22387af060f7a2624cb140b90831ed5d27cac6e9
OS: Xubuntu 19.10
gcc: version 9.2.1 20191008 (Ubuntu 9.2.1-9ubuntu2) Target: x86_64-linux-gnu
platform: Intel Core i7-2600

# Error description

Compiling one of my projects in DrRacket I get the following error:

    ../../racket/racket/share/pkgs/drracket/drracket/private/stack-checkpoint.rkt:40:30: returned two values to single value return context

# Reproducing the error

- Download the project from [https://github.com/joergen7/cfplot](https://github.com/joergen7/cfplot)
- Open Drracket with the `drracketcs` command
- Open the source file `cfplot.rkt`
- Type check with [F6]

Run with [F5] produces the following error message (as before):

    ../../racket/racket/share/pkgs/drracket/drracket/private/stack-checkpoint.rkt:40:30: returned two values to single value return context

This is also the only entry in the backtrace.

# Observation

## On the Command Line it works

Surprisingly, compiling the tool on the command line and running it with an example input works fine.

    racocs make -j 8 *.rkt
    racocs exe cfplot.rkt
    ./cfplot examples/2019-01-17-variant-call-varscan-gruenau-4x120-2x32-2x16-gluster4.json

Thus, I suspect that the problem is related to DrRacket.

## Disabling Debugging makes it Work

Disabling debugging in DrRacket's language menu makes the error go away.

**Comment by mflatt** [comment]
Thanks for the report!
