### ISSUE TITLE
Default input focus on docs.racket-lang.org

### ISSUE THREAD

**Issue by soegaard** [racket/racket#2953]
When docs.racket-lang.org loads no input field has focus.
Pressing tab moves set the focus to the "Racket Documentation" link below the search box.

I propose to make the search box be first in the input focus order.

**Comment by capfredf** [comment]
@soegaard you can press `s` to set the focus to the search box.

**Comment by capfredf** [comment]
but the search box to be first in the input focus order would be a nice feature to have
