### ISSUE TITLE
Flaky unsafe tests on CGC

### ISSUE THREAD

**Issue by pmatos** [racket/racket#2955]
Flaky tests on unsafe Section:
https://github.com/racket/racket/runs/338214028#step:9:28

First seen for commit:
https://github.com/racket/racket/commit/83ae4cd9a44b28c0508c24f422ade6265335c0ff

```
Errors were [13]:
(Section (got expected (call)))
((unsafe) (#f #t (#<procedure:boolean?> 4)))
((unsafe) (((1 2 3 4 5 6 7 8 9 10)) Error (unsafe-weak-hash-iterate-key ht i)))
((unsafe) ((not-an-error) Error (let () (unsafe-weak-hash-iterate-key ht i) (quote not-an-error))))
((unsafe) ((1 2 3 4 5 6 7 8 9 10) gone (#<procedure:unsafe-weak-hash-iterate-key> #<hash> 4 gone)))
((unsafe) ((val) Error (unsafe-weak-hash-iterate-value ht i)))
((unsafe) ((not-an-error) Error (let () (unsafe-weak-hash-iterate-value ht i) (quote not-an-error))))
((unsafe) (val gone (#<procedure:unsafe-weak-hash-iterate-value> #<hash> 4 gone)))
((unsafe) ((((1 2 3 4 5 6 7 8 9 10) . val)) Error (unsafe-weak-hash-iterate-pair ht i)))
((unsafe) ((not-an-error) Error (let () (unsafe-weak-hash-iterate-pair ht i) (quote not-an-error))))
((unsafe) (((1 2 3 4 5 6 7 8 9 10) . val) (gone . gone) (#<procedure:unsafe-weak-hash-iterate-pair> #<hash> 4 gone)))
((unsafe) (((1 2 3 4 5 6 7 8 9 10) val) Error (unsafe-weak-hash-iterate-key+value ht i)))
((unsafe) ((not-an-error) Error (let () (unsafe-weak-hash-iterate-key+value ht i) (quote not-an-error))))
((unsafe) (((1 2 3 4 5 6 7 8 9 10) val) (gone gone) (#<procedure:call-with-values> #<procedure:...cket/unsafe.rktl:853:30> #<procedure:list>)))
```

Possibly related to https://github.com/racket/racket/issues/2954

**Comment by samth** [comment]
Do these both only happen on macOS?

**Comment by pmatos** [comment]
Until now... Only on macos. 

On 7 December 2019 22:38:51 CET, Sam Tobin-Hochstadt <notifications@github.com> wrote:
>Do these both only happen on macOS?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/racket/racket/issues/2955#issuecomment-562889009

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mflatt** [comment]
I think something about the compiler is making CGC more conservative than usual. This set of failures might be resolved by moving the test into a function that will be compiled by the JIT.

**Comment by pmatos** [comment]
Happy to close this given https://github.com/racket/racket/commit/602c7b033101e97b4deba7a108cee3b018daedc3
