### ISSUE TITLE
CC not being passed to zlib when building CS

### ISSUE THREAD

**Issue by pmatos** [racket/racket#2958]
Noticed while adding compilation with `clang`. 
Logs show this here: 
https://github.com/LinkiTools/racket/runs/339080627#step:9:325

It seems that `zlib` just default to `gcc`.

**Comment by mflatt** [comment]
Attempt at repair: https://github.com/racket/ChezScheme/commit/cbb7c5f21a879ee90293c3abf99d344c4fc42b7f

**Comment by pmatos** [comment]
That was fast! :) 
I will look at testing this a bit later. Will close if fixed.

**Comment by pmatos** [comment]
Confirmed fixed with https://github.com/racket/ChezScheme/commit/cbb7c5f21a879ee90293c3abf99d344c4fc42b7f

@mflatt thanks.
