### ISSUE TITLE
Section foreign generating TIMEOUT in Actions tests

### ISSUE THREAD

**Issue by pmatos** [racket/racket#2961]
In foreign test section we are getting a timeout. We should think what we can do about these.
https://github.com/racket/racket/runs/342343626#step:9:92

**Comment by samth** [comment]
Is this because we're timing out of our total limit of GitHub Actions runtime?

**Comment by pmatos** [comment]
This timeout is coming from racket.

**Comment by samth** [comment]
Ok, that's reassuring. How can we tell, though?

**Comment by mflatt** [comment]
"TIMEOUT -- ABORTING!" is in "quiet.rktl". (I had forgotten about that timeout, though.)

**Comment by pmatos** [comment]
I am away so I couldn't look into it yet but is it something we can remove or increase during CI if its important for local runs?

**Comment by samth** [comment]
I think we should just increase it generally -- 20 minutes is not that long for this test suite any more.

**Comment by pmatos** [comment]
Could you push a fix? Otherwise I will look at it tomorrow.

**Comment by samth** [comment]
@mflatt already did. If the tests take an hour to run that's probably a different issue, so I'm closing this.
