### ISSUE TITLE
racket3m nojit, noefp fails memory test in will section

### ISSUE THREAD

**Issue by pmatos** [racket/racket#2963]
With Racket3m on both Linux and Mac with cify or no cify, if I compile racket with no jit and no extflonums, no futures and no places, the test:
```
Errors were [1]:
(Section (got expected (call)))
((wills) (#f #t (many-vectors-in-reasonable-space? #f)))
```
fails predictably.

Here's all the occurrences:
https://github.com/LinkiTools/racket/runs/345208378#step:9:41
https://github.com/LinkiTools/racket/runs/345208430#step:9:40
https://github.com/LinkiTools/racket/runs/345208517#step:9:40
https://github.com/LinkiTools/racket/runs/345208599#step:9:42

I expected this to be dependent on gc behaviour, however there might be a relation between no jit and gc behaviour. efp might in itself not be the problem.

@mflatt should this test be disabled without a jit?

**Comment by pmatos** [comment]
Unfortunately this still seems to be failing after 58f51f1: https://github.com/LinkiTools/racket/runs/347193643#step:10:43

**Comment by mflatt** [comment]
That's a different test. It checks whether a contract applications runs in under 5 seconds, so it's easy to see why that causes problems. I don't yet have a good idea on how to handle this one.

**Comment by samth** [comment]
That problem is #2964.

**Comment by pmatos** [comment]
> That problem is #2964.

Right - mixed this up. Sorry.

**Comment by pmatos** [comment]
Fixed wtih https://github.com/racket/racket/commit/58f51f15eddfe41f4a6c17630091441230fa93ac
Thanks.
