### ISSUE TITLE
for/fold does not support the `#:result` clause in typed/racket

### ISSUE THREAD

**Issue by co-dan** [racket/racket#2971]
The following code works both with `#lang racket` and `#lang typed/racket`:
```
(for/fold ([a 0] [b 1])
          ([i '(1 2 3)])
  (values (+ a i) (* b i)))
```

However, if I change the fold to:
```
(for/fold ([a 0] [b 1] #:result a)
          ([i '(1 2 3)])
  (values (+ a i) (* b i)))
```
then it doesn't work in `typed/racket` anymore:
```
. for/fold: expected optionally type-annotated identifier
  parsing context: 
   while parsing accumumulator binding
   while parsing accumumulator bindings in: #:result
```

The documentation for `for/fold` in typed/racket states that it behaves like its non-annotated counterpart, so I would expect it to support the `#:result` keyword as well.

Would it be possible to make the typed version of `for/fold` to support the `#:result` keyword?
Thanks.

**Comment by bennn** [comment]
This is fixed in the latest Typed Racket:
https://github.com/racket/typed-racket/pull/877

You can get the fix now in a [snapshot build](https://snapshot.racket-lang.org/), or in a few months with the next release.

**Comment by co-dan** [comment]
Ah, thanks! I didn’t realize that typed racket has its own repository.
Thank you for a very quick reply
