### ISSUE TITLE
delay/thread exception handler has an internal error when custodian changed

### ISSUE THREAD

**Issue by LiberalArtist** [racket/racket#2973]
In a promise created with `delay/thread`, raising an exception in a context where the `current-custodian` has been changed can provoke an internal error in `delay/thread`'s exception handler.

For example, this program:
```racket
#lang racket

(define demo
 (delay/thread
  (parameterize ([current-custodian (make-custodian)])
    (error "some error"))))

(force demo)
```
prints the output:
```
exception raised by exception handler: kill-thread: the current custodian does not solely manage the specified thread
  thread: #<thread:run>; original exception raised: some error
some error
```

Note that the internal error occurs even if `demo` is never forced (because it is running in a background thread), and `(force demo)` correctly raises the original exception.

This is where `delay/thread` sets up the exception handler (n.b. using `call-with-exception-handler`) and creates the thread: https://github.com/racket/racket/blob/c3a57f6fb7de4eace833112012d41d87b8976c3a/racket/collects/racket/promise.rkt#L115-L124

It seems like the exception handler should `parameterize` an appropriate `current-custodian` around the call to `kill-thread`. My guess is that the custodian when the promise is created should be saved and restored, but I haven't fully thought through potential issues like kill-safety.

**Comment by mflatt** [comment]
Thanks for the report and repair approach!
