### ISSUE TITLE
Section optimization test fails because it took too long

### ISSUE THREAD

**Issue by pmatos** [racket/racket#2977]
Test fails with:
https://github.com/racket/racket/runs/351757815#step:9:53

```
Errors were [1]:
(Section (got expected (call)))
((optimization) (74.66304347826087 fail ("compilation took too long" 74.66304347826087)))
```

after commit https://github.com/racket/racket/commit/61000a454e58df6ad65f0dd6755639953151f863

**Comment by pmatos** [comment]
Another instance of the failure just in the last commit: https://github.com/racket/racket/runs/360983592#step:9:53

**Comment by pmatos** [comment]
And another:
https://github.com/racket/racket/runs/360495769#step:9:51

**Comment by mflatt** [comment]
Probably best just to declare it as unreliable, so I'll do that.

**Comment by pmatos** [comment]
That sorted this one out - closing. Thanks.
