### ISSUE TITLE
expander module instantiation bug?

### ISSUE THREAD

**Issue by stchang** [racket/racket#2981]
This was partially fixed by ee4ceb7ae40870e0bd3643e132501ab37d49ce5c, but the problem still occurs when installing [`Cur`](https://github.com/wilbowma/cur/tree/turnstile-core), during doc compile.

Below is a cut down example that produces the error. It does not require installing `Cur` or `Turnstile`.

As an alternative, to produce the err, one can clone [this `module-instantiate-err` branch](https://github.com/stchang/cur/tree/module-instantiate-err), and run `cur-lib/cur/curnel/cur-test.rkt` from the repo root.

error msg:
```
instantiate-linklet: mismatch;
 reference to a variable that is uninitialized;
 possibly, bytecode file needs re-compile because dependencies changed
  name: TY/internal+
  exporting instance: "/home/stchang/cur-stchang/cur-lib/cur/curnel/coc.rkt"
  importing instance: "/home/stchang/cur-stchang/cur-lib/cur/curnel/reflection.rkt"
```

Some notes:
- to produce err, run `cur-test.rkt`
- All the files seem to be necessary to produce the err
- On some machines, the call to `make-module-evaluator` requires an additional `#:allow-for-load` kw arg. But not on my machine for some reason.

`cur-test.rkt`:
```racket
#lang racket/base
(require racket/sandbox)
(make-module-evaluator "#lang s-exp \"lang.rkt\"")
```

`lang.rkt`:
```racket
#lang racket/base
(provide #%module-begin)
(require "cic-saccharata.rkt"
         (for-syntax "reflection.rkt"))
```

`reflection.rkt`:
```racket
#lang racket/base
(require
 syntax/parse
 (for-template "coc.rkt"))
(define-syntax-class expanded-Π
  (pattern (~Π (x : arg-type) body-type)))
```

`coc.rkt`:
```racket
#lang racket/base
(require (for-syntax racket/base syntax/parse
                     (for-syntax racket/base)))

(provide (for-syntax ~Π))
(struct Π- (X))
(begin-for-syntax
  (define TY/internal+ (local-expand #'Π- 'expression null))
  (define-syntax ~Π
    (pattern-expander (λ (stx) #'(~do TY/internal+)))))
```

`cic-saccharata.rkt`:
```racket
#lang racket/base
(require (for-syntax racket/base syntax/parse)
         "coc.rkt")
(provide #%module-begin)
(define-for-syntax nested-positivity? (syntax-parser [(~Π (x : A) B) (void)]))
```

cc @mflatt @wilbowma @michaelballantyne

**Comment by mflatt** [comment]
Thanks for the example!

**Comment by wilbowma** [comment]
I can no longer reproduce this in Cur so I think that solves it! Thanks!
