### ISSUE TITLE
Regression in section names due to bf1eb435

### ISSUE THREAD

**Issue by pmatos** [racket/racket#2983]
Regression introduced for 3m and cgc in section names:
https://github.com/racket/racket/runs/354488786#step:9:52

by commit: https://github.com/racket/racket/commit/bf1eb4351b428abc588c6872109602769594315a
by @mflatt 

I was wondering if this could be a flaky test, but looks more like a regression.

**Comment by mflatt** [comment]
This was a regression, but fixed by a135a868a89338aa864f15b728f0a370705a2af5. At the time of the repair, I didn't realize that I was also fixing a cify problem.

**Comment by pmatos** [comment]
Thanks.
