### ISSUE TITLE
(error-print-width 3) incorrectly errors in 3m

### ISSUE THREAD

**Issue by sorawee** [racket/racket#2986]
This line https://github.com/racket/racket/blob/master/racket/src/racket/src/error.c#L3066 should be `>=`, not `>`.

**Comment by gus-massa** [comment]
I think you are correct. RacketCS alredy uses `>=` [rumble/error.ss#L47](https://github.com/racket/racket/blob/master/racket/src/cs/rumble/error.ss#L47) Do you want to send a PR?

**Comment by sorawee** [comment]
Sure. Here's the PR: #2991
