### ISSUE TITLE
bug when running configure with --enable-cs --enable-shared

### ISSUE THREAD

**Issue by tgbugs** [racket/racket#2993]
I'm working on a gentoo ebuild that builds all 3 racket interpreters, cgc, 3m, and cs. While sorting out the right way to run configure I encountered the issue described below.

Running the following causes configure to fail.
```bash
pushd racket/src
./configure --enable-cs --enable-shared
```
Initially this seems to be because the path to libtool is incorrect, this seems to be fixed by the patch below, however this reveals a new failure mode, which is that `checking size of void *... 0` fails. As far as I can tell the size of the void pointer is probably not actually zero, but is an artifact of another command failing (`AC_CHECK_SIZEOF`). libtool seems to be involved in the underlying cause (it doesn't matter whether the bundled libtool or libtool-2.4.6 is used set via `--enable-lt`).

Extract from `racket/src/cs/c/config.log`
```
libtool --mode=compile --tag=CC gcc -o conftest -g -O2 -Wall  -DELF_FIND_BOOT_SECTION  -pthread conftest.c -ldl -lm  -lrt -luuid >&5
libtool:   error: cannot determine name of library object from 'conftest'
configure:5350: $? = 1
configure: program exited with status 1
```

Contrast this with the test that normally succeeds
```
cfg-racket:6119: checking size of void *
cfg-racket:6124: gcc -o conftest  -g -O2   conftest.c -ldl -lm  -ldl -lm -rdynamic >&5
```
I'm not sure why the libtool prefixed build command is being used for this test, and suspect that it might be the cause, but I don't know enough about the configure process to be sure.

Patch that reveals the deeper issue.
```patch
diff --git a/racket/src/cs/c/configure b/racket/src/cs/c/configure
index 085c0e32c2..f9ebfb0fa6 100755
--- a/racket/src/cs/c/configure
+++ b/racket/src/cs/c/configure
@@ -5280,8 +5280,8 @@ if test "${enable_shared}" = "yes" ; then
   abssrcdir=`(cd ${srcdir}; pwd)`
 
   if test "${LIBTOOLPROG}" = "" ; then
-    (cd ../lt; sh ${abssrcdir}/../lt/configure --enable-shared --disable-static)
-    LIBTOOLPROG=`pwd`/../lt/libtool
+    (cd ../../lt; sh ${abssrcdir}/../../lt/configure --enable-shared --disable-static)
+    LIBTOOLPROG=`pwd`/../../lt/libtool
   fi
 
   if test "${need_gcc_static_libgcc}" = "yes" ; then
diff --git a/racket/src/cs/c/configure.ac b/racket/src/cs/c/configure.ac
index fe45211ff9..db02efc59e 100644
--- a/racket/src/cs/c/configure.ac
+++ b/racket/src/cs/c/configure.ac
@@ -610,8 +610,8 @@ if test "${enable_shared}" = "yes" ; then
   abssrcdir=`(cd ${srcdir}; pwd)`
 
   if test "${LIBTOOLPROG}" = "" ; then  
-    (cd ../lt; sh ${abssrcdir}/../lt/configure --enable-shared --disable-static)
-    LIBTOOLPROG=`pwd`/../lt/libtool
+    (cd ../../lt; sh ${abssrcdir}/../../lt/configure --enable-shared --disable-static)
+    LIBTOOLPROG=`pwd`/../../lt/libtool
   fi
 
   if test "${need_gcc_static_libgcc}" = "yes" ; then
```

**Comment by tgbugs** [comment]
Another suspicious line:
https://github.com/racket/racket/blob/0d1a85237e6a46ac85cafb7429fad060e5886542/racket/src/cs/c/configure#L5307

**Comment by mflatt** [comment]
I've pushed some repairs for the problems that you've pointed out, but mostly I disabled the effect of `--enable-shared` for Racket CS (because there are lots more problems and there's no benefit to `--enable-shared` for Racket CS).

**Comment by tgbugs** [comment]
This fixes the issue for me. I will add a pointer to this issue as a reminder that CS has different behavior with respect to shared libs. Thanks!
