### ISSUE TITLE
RackUnit check-exn fails to catch raised syntax error when error not called directly

### ISSUE THREAD

**Issue by tommymchugh** [racket/racket#2996]
Example:
```
#lang racket
(require rackunit)

(check-exn
   exn:fail:syntax?
   (lambda ()
     (raise-syntax-error #f "Failed" #f #f null "")))

(check-exn
   exn:fail:syntax?
   (lambda ()
     (struct apple (seeds) #:constructor-name pear)
     (apple 53)))
```

First check passes, but second check never seems to catch that raise-syntax-error (and thus produces an exn:fail:syntax) is called when the identifier is called for a struct that has a different constructor name.

**Comment by rfindler** [comment]
I believe that's because the exception is being raise at compile time (phase 1) and that's not when `check-exn` is catching errors.

**Comment by sorawee** [comment]
I think you will find https://docs.racket-lang.org/syntax/macro-testing.html#%28form._%28%28lib._syntax%2Fmacro-testing..rkt%29._convert-compile-time-error%29%29 useful.

**Comment by tommymchugh** [comment]
Yes that is very helpful thanks a bunch works perfectly! Not that that is a hassle at at all, but for curiosities sake, is there a reason why check-exn does't wrap the  convert-compile-time-error procedure around the check-exn thunk procedure? It seems that would be useful especially for syntax errors unit testing which may often produce the error testing for not at runtime.

**Comment by rfindler** [comment]
The designers of rackunit decided not to do that, IMO, wisely in this case,
since catching exceptions is routinely a runtime issue. (Although the extra
think doesn't seem necessary to me.)

In other words, it is best to pick a phase to evaluate things and not try
to do things simultaneously in multiple phases as would be required here.

Robby

**Comment by tommymchugh** [comment]
Gotcha, make sense. Thanks for the assistance on this!

**Comment by jackfirth** [comment]
A separate `check-compile-time-exn` form would be very handy though.

**Comment by tommymchugh** [comment]
@jackfirth  I'll build it out and report back. Will reopen for now to see if there is interest in this.

**Comment by jackfirth** [comment]
@tommymchugh Sounds great 🙂 Heads up: the implementation of rackunit is in the repository racket/rackunit, not racket/racket.

**Comment by tommymchugh** [comment]
https://github.com/racket/rackunit/pull/114 is the PR with the implementation. Comments, contributions, etc. are welcome!

**Comment by sorawee** [comment]
Since everything works as expected, can we close this issue, @tommymchugh?

**Comment by tommymchugh** [comment]
Yup!
