### ISSUE TITLE
Windows zip release

### ISSUE THREAD

**Issue by cup** [racket/racket#3001]
If you go here:

https://download.racket-lang.org

You see EXE installer for Windows. This contrasts with other programming
languages that offer both an executable installer and ZIP files that can be
extracted and run. For example Go:

https://golang.org/dl

and Nim:

https://nim-lang.org/install_windows.html

Python:

https://python.org/downloads/release/python-373

and C#:

https://dotnet.microsoft.com/download/dotnet-core/2.2

PHP:

https://windows.php.net/download

Perl:

http://strawberryperl.com/releases.html

**Comment by mflatt** [comment]
You can find a ".zip" for Minimal Racket by following the "More Variants and Checksums" link on the download page.

**Comment by cup** [comment]
@mflatt thank you!

https://download.racket-lang.org/releases
