### ISSUE TITLE
Windows10 Racket Install Error

### ISSUE THREAD

**Issue by jsMichot** [racket/racket#3015]
When running the installer on Windows 10, I receive an "Error opening file for writing" for every .exe file.

**Comment by jsMichot** [comment]
The problem seems to be that the installer does not have a compatibility mode for Windows 10. Are there any resolutions to installing Racket on Windows 10?

**Comment by mflatt** [comment]
The installer should work on Windows 10, and I haven't seen this particular error, so I'm stumped. I guess you don't have an existing installation, where the old ".exe" files cannot be overwritten.

**Comment by jsMichot** [comment]
@mflatt Thanks for responding. When I right-click and view the Properties of the installer, The Compatibility mode list does not include Windows 10. Windows 8 is the latest version available.

**Comment by jsMichot** [comment]
Problem solved: I needed to right-click and Run as Admin. Applying the Admin setting in Properties > Security did not work.
