### ISSUE TITLE
Program in ISL+ diverges but it shouldn't

### ISSUE THREAD

**Issue by klauso** [racket/racket#3027]
This program loops in the ISL+ language. Obviously it shouldn't. Since `f` is a function, it's body shouldn't be evaluated.

It works correctly in ASL and in Racket. The bug only shows up in ISL+.

```
(define f
  (lambda (x)
    (lambda (y)
      (local [(define recursion (f x))]
        (+ x y)))))
```

**Comment by mflatt** [comment]
The problem is a broken inlining heuristic in the optimizer, which causes it to unroll the recursion forever. The following `racket/base` program has the  same problem.

```
#lang racket/base

(define (f x)
  (lambda (y)
    (letrec ([recursion (f x)])
      (+ x y))))
```

**Comment by klauso** [comment]
Wow, that was fast! Thanks!
