### ISSUE TITLE
regexp-replace Racket 7.5 CS

### ISSUE THREAD

**Issue by wcs4217** [racket/racket#3032]
There is a bug in Racket 7.5 CS:

```
> (regexp-replace "(x)?" "" (lambda a ""))
invalid memory reference.  Some debugging context lost
  context...:
   condition->exn
   body of top-level
   dynamic-wind
   eval-one-top12
   /home/pltbuild/build/plt-cs-release/bundle/racket/collects/racket/repl.rkt:11:26

```

However, it works fine in Racket 7.5 Regular:

```
> (regexp-replace "(x)?" "" (lambda a ""))
""
```

**Comment by 97jaz** [comment]
This looks like a problem [here](https://github.com/racket/racket/blob/master/racket/src/regexp/replace/main.rkt#L82), where the code isn't accounting for the case where elements of `poss` are `#f`.

**Comment by jbclements** [comment]
I can confirm that this is a problem in the release candidate for 7.6 as well, alas. @97jaz , is it clear why that would affect CS but not Classic?

**Comment by 97jaz** [comment]
@jbclements Yeah, because CS uses a version of the regexp interpreter that is written in Racket, whereas the C runtime has its own regexp implementation, written in C.

BTW, I'm working on a fix.

**Comment by jbclements** [comment]
OIC

**Comment by jbclements** [comment]
BTW, the bar for putting something in the 7.6 release is pretty ridiculously high at this point...JFYI...

**Comment by 97jaz** [comment]
Sure, didn't expect this would make it into 7.6.

**Comment by jbclements** [comment]
Phew!

**Comment by 97jaz** [comment]
The way that I read the documentation is that if the `insert` parameter is a function, then it will be passed the list of match+submatches exactly as `regexp-match` would return them, meaning that the function could be passed `#f` values. On the other hand, if the parameter is a (byte)string that contains back-references (e.g., `\3`), a back-reference that refers to a non-match resolves to the empty string/byte-string.

Does that sound correct?
