### ISSUE TITLE
32bit FFI enum problem

### ISSUE THREAD

**Issue by lockie** [racket/racket#3036]
Hello.
I have a [report](https://github.com/lockie/racket-sdl2/issues/2) from one of the users of my Racket FFI library, [racket-sdl2](https://github.com/lockie/racket-sdl2), regarding error on 32 bit environment. I was able to produce this MWE to demonstrate the issue:
```
#lang racket/base
(require ffi/unsafe)
(define _test_enum (_enum `(TEST = 1073741906) _sint32))
(define atol (get-ffi-obj "atol" "libc.so.6" (_fun _string -> _test_enum)))
(displayln (atol "1073741906"))
```

The value `1073741906` fits perfectly into signed 32 bit value. However there are differences depending on platform this code is being run:

- on my 64-bit Gentoo Linux machine with Racket 7.3 it prints "TEST", just as expected;
- on 32-bit Ubuntu virtual machine with Racket 7.5 it produces the following error:
```
enum:int->_test_enum: expected a known #<ctype:int32>, got: 1073741906
```

Seems like there's a problem in implementation of `_enum`; I'll be happy to be wrong about that. I wasn't able to pinpoint it due to complex nature of racket ctype objects (can't exactly figure why [here](https://github.com/racket/racket/blob/b9d917a6740e8b73f64f8a11d1b247e9a0a03de7/racket/collects/ffi/unsafe.rkt#L945) `assq` is not able to find the value in question).

I'd appreciate any help. Thanks in advance.

**Comment by mflatt** [comment]
I agree that this is a bug: `assq` is the wrong choice, because  a number like 1073741906 is not a fixnum on 32-bit machines. (It looks like the code was written with the assumption of fixnums.) Does changing `assq` to `assv` fix the problem?

**Comment by lockie** [comment]
> Does changing assq to assv fix the problem?

Yes, as a matter of fact it does.

**Comment by lockie** [comment]
Thanks Matthew!
