### ISSUE TITLE
continue the :"Can't run in Windows 10 insider.  "

### ISSUE THREAD

**Issue by BearJean** [racket/racket#3037]
the context follow https://github.com/racket/racket/issues/3010
for "you cannot close or re-open issues opened by someone else",so I reopen it in new one:

I'm sorry for the interruption agagin,but still some puzzled me.
I want to know the reason about the question above.

    because it sounds like the issue is at the GUI level, which is implemented in Racket.
    If I remember correctly, v7.5 had a problem with input methods, and that should be fixed for the upcoming v7.6 release.

I found what you said in racket/drracket#331.
the question I still puzzled is ,why that would happen.
I find the src in https://github.com/racket/drracket
but not find the README as I except in https://github.com/racket/racket/blob/master/README.md.
which include a url tell me how to build the src .
in the build.md :

On Windows with Microsoft Visual Studio (any version between 2008/9.0 and 2019/16.0), nmake win32-in-place creates a build in the "racket" directory. For information on configuring your command-line environment for Visual Studio, see "racket/src/worksp/README.txt".

what I do is:
open the x64 Native Tools Command Prompt for VS 2019 and execute C:\Users\mingy\Desktop\racket-7.5.0.900\src\worksp\build.bat.

follow above I finish the build of racket.

I found this https://groups.google.com/forum/#!topic/racket-dev/B0VlRlX1LkQ

"The resultant DrRacket starts up fine and kind of works, but the UI locks up after a few keystrokes or mouse clicks."

that's the same as my condition ,rather just chinese input methods.
my env: Windows 10 Insider Preview Build 19041.21 （Slow）
Dr.racket version :download from https://download.racket-lang.org/ racket-7.5-x86_64-win32.exe (78M)
before update the OS it just work fine.
but after update to this version,whenever I open the Dr.Racket ,it just Stuck and I can't do anything ,even input a number,every Button no response,I have to kill it in Task Manage

my question here is :how can I build the Drracket? can you please tell me how to build the Drracket,or give some url. I can't find it anywhere.
but find this https://groups.google.com/forum/#!searchin/racket-dev/Build$20Drracket|sort:date/racket-dev/kuGJ_Znww0Y/aVqqWwAEBwAJ
which say:
"I’m failing to build DrRacket on 10.14.6 with a recently updated XCode...""
so i think "to build Drracekt"may could todo.

I'm so sorry for that.
I have try it again, and find ,Every time I turn on the software for the first time
Button can be pressed
When the input method is eng, the software works normally
Only after I change the input method to pinyin can the software get stuck
so I agree with you that"If I remember correctly, v7.5 had a problem with input methods",
so the request only one ,I want to know how to compile the Drracket and find the reason.
or if you can share whit about that bug..
sorry,because I need it to someone ,

When I first encountered this bug, I asked some people whether it was the operating system or the software itself. At last, they asked me to download the source code, compile and execute by myself, and find out the problematic code. And guess is not good, which is what a qualified programmer should do.

So I have to know why.

**Comment by mflatt** [comment]
The bug repair is in the `racket/gui` package as racket/gui@823e940809e41db54f9d14abdef3288d4554388d — which is really difficult to find if you don't know to look there!

I think it's fair to blame Racket for the bug; to implement eventspaces, the `racket/gui` library uses the Windows event loop in a way that it is not intended. But the Windows update seems to have triggered the problem by changing the Win32 function `EnumThreadWindows`; it no longer actually enumerates all of the windows for a thread's event queue (or maybe it never did?), which seems to me unfortunate.

**Comment by BearJean** [comment]
Thank you, but I was asked to build drracket on my own computer, and to find the bug myself, so can you please tell me how to build the Drracket,or give some url.
I really can't find it.

**Comment by mflatt** [comment]
Hi @BearJean. I'm not sure I understand what you're looking for. You seem to have already found the instructions for building from a Git checkout: `nmake win32-in-place`. Does that not work?

**Comment by BearJean** [comment]
Yes, it works fine. Thanks for the reply, I successful compile the racket/racket, the output file as follows: 
```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2020/1/26     21:06                collects
d-----         2020/1/20     12:56                doc
d-----         2020/1/20     12:56                etc
d-----         2020/1/26     21:06                include
d-----         2020/1/26     21:06                lib
d-----         2020/1/26     21:06                share
d-----         2020/1/26     21:07                src
-a----         2020/1/20     14:59         678912 Racket.exe
-a----         2020/1/20     14:59        3341888 Racket.ilk
-a----         2020/1/20     14:59        5943296 Racket.pdb
-a----         2020/1/20     13:04         504832 RacketCGC.exe
-a----         2020/1/20     13:04        5844992 RacketCGC.pdb
-a----         2020/1/20     15:04         491520 raco.exe
-a----         2020/1/20     15:20         491520 racoCGC.exe
```
Now I want to know how to compile DrRacket and try to find the bug by myself. I am learning the usage of raco.exe, depends.exe , procexp64 and something about win32. https://docs.racket-lang.org/raco/exe.html
I have only a little knowledge about c plus plus.Is there any introduction about racket translation_phases like this ?
 
https://en.cppreference.com/w/cpp/language/translation_phases

I find this https://docs.racket-lang.org/raco/setup.html and try it in my computer with command "reco setup".but only find 

```
PS D:\zzzq\drracket-7.5> raco setup drracket
raco setup: version: 7.6.0.12
raco setup: platform: win32\x86_64 [3m]
raco setup: target machine: racket
raco setup: installation name: snapshot
raco setup: variants: 3m
raco setup: main collects: C:\Program Files\Racket-7.6.0.12\collects
raco setup: collects paths:
raco setup:   C:\Users\mingy\AppData\Roaming\Racket\snapshot\collects
raco setup:   C:\Program Files\Racket-7.6.0.12\collects
raco setup: main pkgs: C:\Program Files\Racket-7.6.0.12\share\pkgs
raco setup: pkgs paths:
raco setup:   C:\Program Files\Racket-7.6.0.12\share\pkgs
raco setup:   C:\Users\mingy\AppData\Roaming\Racket\snapshot\pkgs
raco setup: links files:
raco setup:   C:\Program Files\Racket-7.6.0.12\share\links.rktd
raco setup:   C:\Users\mingy\AppData\Roaming\Racket\snapshot\links.rktd
raco setup: main docs: C:\Program Files\Racket-7.6.0.12\doc
raco setup: --- updating info-domain tables ---                    [10:57:32]
raco setup: updating: C:\Program Files\Racket-7.6.0.12\share\info-cache.rktd
raco setup: WARNING: with-output-to-file: error deleting file
  path: C:\Program Files\Racket-7.6.0.12\share\info-cache.rktd
  system error: 拒绝访问。; errid=5
raco setup: --- pre-installing collections ---                     [10:57:32]
raco setup: --- installing foreign libraries ---                   [10:57:32]
raco setup: --- installing shared files ---                        [10:57:32]
raco setup: --- compiling collections ---                          [10:57:32]
raco setup: --- parallel build using 8 jobs ---                    [10:57:32]
raco setup: 7 making: <pkgs>/drracket-plugin-lib/drracket
raco setup: 7 making: <pkgs>/drracket-plugin-lib/drracket/private
raco setup: 6 making: <pkgs>/drracket-tool-lib/drracket
raco setup: 5 making: <pkgs>/drracket/drracket
raco setup: 5 making: <pkgs>/drracket/drracket/private
raco setup: 6 making: <pkgs>/drracket-tool-lib/drracket/private
raco setup: 6 making: <pkgs>/drracket-tool-lib/drracket/private/syncheck
raco setup: 5 making: <pkgs>/drracket/drracket/private/syncheck
raco setup: --- creating launchers ---                             [10:57:36]
raco setup: launcher: <gui-bin>/DrRacket.exe
delete-file: cannot delete file
  path: C:\Program Files\Racket-7.6.0.12\DrRacket.exe
  system error: 拒绝访问。; errid=5
  context...:
   C:\Program Files\Racket-7.6.0.12\collects\compiler\embed.rkt:1445:0: create-embedding-executable
   C:\Program Files\Racket-7.6.0.12\collects\launcher\launcher.rkt:637:0: make-windows-launcher
   C:\Program Files\Racket-7.6.0.12\collects\setup\setup-core.rkt:1501:13: for-loop
   C:\Program Files\Racket-7.6.0.12\collects\setup\setup-core.rkt:1478:8: make-launcher
   C:\Program Files\Racket-7.6.0.12\collects\setup\setup-core.rkt:1590:8: for-loop
   C:\Program Files\Racket-7.6.0.12\collects\setup\setup-core.rkt:190:50
   C:\Program Files\Racket-7.6.0.12\collects\setup\setup-core.rkt:1475:4: for-loop
   C:\Program Files\Racket-7.6.0.12\collects\setup\setup-core.rkt:72:0: setup-core
   "C:\Program Files\Racket-7.6.0.12\collects\setup\main.rkt": [running body]
   temp35_0
   for-loop
   run-module-instance!
   "C:\Program Files\Racket-7.6.0.12\collects\raco\main.rkt": [running body]
   temp35_0
   for-loop
   run-module-instance!
   ...
raco setup: --- building documentation ---                         [10:57:37]
raco setup: --- installing collections ---                         [10:57:39]
raco setup: --- post-installing collections ---                    [10:57:39]
raco setup: --- summary of errors ---                              [10:57:39]
raco setup: error: during launcher setup for <pkgs>/drracket/drracket
raco setup:   delete-file: cannot delete file
raco setup:     path: C:\Program Files\Racket-7.6.0.12\DrRacket.exe
raco setup:     system error: 拒绝访问。; errid=5
```

I know "path: C:\Program Files\Racket-7.6.0.12\share\info-cache.rktd system error: 拒绝访问。; errid=5" is because not have administrator permissions.
but it seem not access the 7.5 source.I will continue to read the document to find a way.

If I want to have the ability to find the bug you mention (Interface stuck for input), what should I know and can you talk to me a little and how to do.Thanks for your patience.

emmmm..or should I to compile /racket/gui/ ?
what I do is In order to improve the ability of look up documents and analyzing problems.
I'm sorry to bother you with these silly questions
