### ISSUE TITLE
`--enable-shared` breaks src/racket/Makefile et al. on Linux builds of racket-7.4 and -7.5?

### ISSUE THREAD

**Issue by ermo** [racket/racket#3039]
I'm finding that building racket-7.4 and racket-7.5 from source on Linux with `./configure --enable-shared` results in some pretty funky `AR=(...)` `src/*/Makefile` statements. 

Racket-7.3 builds fine with `--enable-shared` in my experience.

Here's the error message that GNU make spits out during the build when trying to parse `src/racket/Makefile`:

`Makefile:36: *** missing separator.  Stop.`

This is what line 36/37/38 of the `src/racket/Makefile` looks like:

```
AR = libtool --mode=link --tag=CC x86_64-pc-linux-gnu-cc -release .
.
. -rpath /usr/x86_64-pc-linux-gnu/lib $(ARLIBFLAGS) -o
```
I've seen the exact same error building racket-7.4/-7.5 on two different Linux distributions with `--enable-shared`. 

If I manually fix the AR invocation in `src/racket/Makefile`, the build stops with the same error during parsing of an AR=(...) statement (with the exact same syntax as above) in the next `Makefile` in the build.

... help?

**Comment by mflatt** [comment]
This problem should be fixed for the upcoming v7.6 release. You can try the current v7.6 pre-release at https://pre-release.racket-lang.org/.

**Comment by ermo** [comment]
@mflatt I don't suppose you could point me to the commit(s) in question fixing this so I can create a backport-patch?

I did a cursory look in the master branch commit history, but didn't spot any obvious candidate, hence my question.

Thanks for the quick response!

**Comment by ermo** [comment]
Ah. Looks like it's described as part of #2890 -- will see what I can do.
