### ISSUE TITLE
gui button object mistreats min-height specification

### ISSUE THREAD

**Issue by paschlie** [racket/racket#3040]
#lang racket/gui

; The following demonstrates a bug, where the gui buttion object does not properly treat its
; min-height specification as min-height of the drawn button-object, instead it appears to treat
; it as the min-height of the drawn-object + its vert-margin; which is wrong; although its parent
; will determine its child's effective minium height will be its (min-height + 2 * vert-margin).
; Nor does it appear to understand how to increase the min-height required to host multiple
; lines of text.

; Create a dialog box
(define dialog (instantiate dialog% ("Example")))

; Add a horisonal panel, centered within the dialog box
(define hpanel-1
  (new horizontal-panel% [parent dialog]
       [alignment '(center center)]))
; Add buttons within the horizonal panel having a minium height of 80 pixels (bug!)
(new button% [parent hpanel-1] [min-height 80] [label "a b/c\rdms"])
(new button% [parent hpanel-1] [min-height 80] [label "sin\racos"])
(new button% [parent hpanel-1] [min-height 80] [label "cos\racos"])
(new button% [parent hpanel-1] [min-height 80] [label "tan\ratan"])

; Add another horisonal panel, centered within the dialog box
(define hpanel-2
  (new horizontal-panel% [parent dialog]
       [alignment '(center center)]))
; Add buttons within the horizonal panel, having a minium height of 80 pixels (bug!)
(new button% [parent hpanel-2] [min-height 80] [label "X^Y\re^X"])
(new button% [parent hpanel-2] [min-height 80] [label "X^1/Y\rsqrt X"])
(new button% [parent hpanel-2] [min-height 80] [label "XvY\rln X"])
(new button% [parent hpanel-2] [min-height 80] [label "1/X"])

; Show the dialog
(send dialog show #t)

**Comment by mflatt** [comment]
Discussion at racket/gui#163
