### ISSUE TITLE
2htdp/image's `scale/xy` translates text-images out of the bounding-box

### ISSUE THREAD

**Issue by ibarland** [racket/racket#3043]
==== to reproduce
````
(require 2htdp/image)
(scale/xy 2 1 (text "hello" 20 'black))
; resulting image has text too high (and cropped off)
````

==== description
In 2htdp/image:
scale/xy of text-images, when y<x, gives results that don't "look" correct -- the result is translated higher than it should be, and therefore falls outside the bounding box.

<img width="492" alt="Screen Shot 2020-02-10 at 13 29 11" src="https://user-images.githubusercontent.com/287051/74346373-7fe22800-4d7d-11ea-9a15-e0141bcbc270.png">

(I guess a unit-test for this issue would require a bitmap of the desired-result.)

This is v7.5, on Mac OS (10.14.6) and a student said they got this on Windows as well.

**Comment by rfindler** [comment]
The diff below fixes the problem and kind of sort of makes sense to me as a bug. And yes, it turns out that that code is in the drawing code but it sure seems like we can move it out into a function that computes what the new origin should be, given various properties of the text we're trying to draw so I don't think we need to resort to bitmaps for a test case here.

```
--- a/gui-lib/mrlib/image-core.rkt
+++ b/gui-lib/mrlib/image-core.rkt
@@ -1120,7 +1120,8 @@ has been moved out).
                  [else color])))
        (let-values ([(w h _1 _2) (send dc get-text-extent (text-string np-atomic-shape))])
          (let ([p (- (make-rectangular dx dy)
-                     (* (make-polar 1 (- θ)) (make-rectangular (/ w 2) (/ h 2))))])
+                     (* (make-polar 1 (- θ)) (make-rectangular (/ w 2)
+                                                               (* (text-y-scale np-atomic-shape) (/ h 2)))))])
            (define-values (x-scale y-scale) (send dc get-scale))
            (define-values (ox oy) (send dc get-origin))
            (send dc set-origin (+ ox (real-part p)) (+ oy (imag-part p)))
```
