### ISSUE TITLE
7.6: Must specify --enable-useprefix for old unixstyle install default behavior

### ISSUE THREAD

**Issue by winny-** [racket/racket#3046]
With the current 7.6 release, it appears one needs to always specify `--enable-useprefix` enable a unix package style installation. Without `--enable-useprefix`, `--prefix` indeed specifies a root directory, however `collects`, `man`, and so on are placed directly in the prefix, that is, a unixstyle install isn't used, and datadir is not used.

Looking at https://github.com/racket/racket/blob/master/racket/src/ac/path.m4#L3

```
unixstyle=no
if test "${enable_useprefix}" = "yes" -a "${prefix}" != "NONE" ; then
    # all tests that can possibly set unixstyle=yes
fi
```

Is the `-a` intended to be an `-o`?

Context — I ran into this when [packaging racket for Gentoo](https://github.com/winny-/winny-overlay/blob/c43be0f3f4d887b8647f5d4e316ed4cd3e975507/dev-scheme/racket/racket-7.6.ebuild#L48). [The commit that introduced `useprefix`.](https://github.com/racket/racket/commit/7e3a8c9a3be7b842990c0b7ec65187a08094398d)

**Comment by juanfra684** [comment]
I've the same problem on OpenBSD. Changing the `-a` to `-o` reverted the Racket installation to the old behavior.

**Comment by pmatos** [comment]
Looks like a regression - we need to take a look at it.

**Comment by samth** [comment]
Unfortunately, changing `-a` to `-o` breaks the behavior this originally fixed.

**Comment by mflatt** [comment]
I'm pretty sure the commit above fixes the problem, so I've pushed it, but more eyes on that change would be great.

**Comment by samth** [comment]
In my testing, the change seems to have the behavior I expect for both `make base` and `make unix-style`, with and without `CONFIG_SITE` set.
