### ISSUE TITLE
Missing strings in "View" menu

### ISSUE THREAD

**Issue by VedVid** [racket/racket#3058]
Some fields from "View" menu are displayed incorrectly. The functionality does work, but the description is gone.

![image](https://user-images.githubusercontent.com/16949680/75278048-7c34b380-5809-11ea-915b-0af1abd66d70.png)

Version: 7.6; tested with all three Windows releases.  
OS: Fresh install of 64-bit Windows 10 (16299)

**Comment by mflatt** [comment]
I think this was the same issue as racket/gui#168 and fixed by racket/gui@51a2731.
