### ISSUE TITLE
The option "Open recent" under the File submenu of DrRacket 7.6 doesn't work as expected in Windows 7.

### ISSUE THREAD

**Issue by encomer** [racket/racket#3064]
In version 7.5 the "_Open recent_" option under the File submenu in DrRacket used to work fine, but in version 7.6 under Windows 7, doesn't opens the corresponding window listing the recent files.

**Observation**: One problem about this "bug" is that *sometimes* the expected window of _Recent files_ (at least in my installation) happens to open correctly. but I don't know yet how to reproduce the "expected" behavior. 

_Thank you in advance_ for your support, and congratulations for all your excellent work with Racket, and particularly DrRacket. 
Sincerely, E. Comer.

**Comment by joskoot** [comment]
Same on Windows 10. The recent files do appear after opening a new tab.
I sometimes also saw 7.6 having trouble with the preference file.
I went back to 7.5

From: E. Comer
Sent: 02 March 2020 05:54
To: racket/racket
Cc: Subscribed
Subject: [racket/racket] The option "Open recent" under the File submenu ofDrRacket 7.6 doesn't work as expected in Windows 7. (#3064)

In version 7.5 the "Open recent" option under the File submenu in DrRacket used to work fine, but in version 7.6 under Windows 7, doesn't opens the corresponding window listing the recent files.
Observation: One problem about this "bug" is that sometimes the expected window of Recent files (at least in my installation) happens to open correctly. but I don't know yet how to reproduce the "expected" behavior.
Thank you in advance for your support, and congratulations for all your excellent work with Racket, and particularly DrRacket.
Sincerely, E. Comer.

**Comment by encomer** [comment]
Thank you very much Professor Jos Koot. I tested on Windows 7, and as you said: opening first a new tab, the _Recent files_ option works fine. For the moment I can work with that. Thank you again.

**Comment by mflatt** [comment]
I think this was the same issue as racket/gui#168 and fixed by racket/gui@51a2731904cc8aa163c5d01804740a882624809c.
