### ISSUE TITLE
Slow compilation of functions with many keyword arguments

### ISSUE THREAD

**Issue by nmoroze** [racket/racket#3070]
I'm working on a project that involves auto-generating a Racket function with hundreds to thousands of keyword arguments. However, I've noticed that the `raco make` compilation time grows superlinearly with respect to the number of arguments. This behavior does not seem to occur with regular, non-keyword arguments. 

I ran an experiment to demonstrate this, generating a simple function with an increasing number of arguments and recording the compilation times. Here's the benchmark:
```python
import subprocess
import time
lang = "racket"

arg_template = 'foo-{}'
kwarg_template = '#:foo-{0} foo-{0}'

for mem in range(50, 1500, 25):
    with open('test.rkt', 'w') as f:
        f.write('#lang {}\n'.format(lang))
        f.write('(define (foo {}) (void))\n'.format(' '.join(kwarg_template.format(i) for i in range(mem)))) # swap in arg_template for kwarg_template to test non-keyword arguments
    start = time.time()
    subprocess.check_call(['raco', 'make', 'test.rkt'])
    end = time.time()
    print('{} {}'.format(mem, end-start))
```

And here's a plot of the results:
![chart](https://user-images.githubusercontent.com/4412459/76271198-1820df00-624e-11ea-80ce-be6296202f16.png)

I've observed this behavior on both Racket release 7.3 as well as 601ffc9b36 (master as of March 7). 

Feel free to close if this is considered outside of Racket's usual use-case, but I wanted to report in case this is considered a performance bug that can be fixed. 

(issue report/benchmark based on emina/rosette#147, which is related to this project)

**Comment by mflatt** [comment]
I've pushed a commit that improves things by a constant factor, but it does not avoid quadratic expansion time.

The problem in this case is that the expansion for N keyword arguments involves a `let` nesting N deep. That triggers quadratic behavior in the expander and in scope sets, and I don't know a solution.

**Comment by nmoroze** [comment]
Thanks for taking a look and making the improvement! I reran my benchmark and this definitely helps, although it seems like this is still a bottleneck in my use case. Given that it doesn't seem like there's an obvious solution, I can just come up with a workaround.
