### ISSUE TITLE
Quote-related issues in syntax->string

### ISSUE THREAD

**Issue by sorawee** [racket/racket#3071]
1. `(syntax->string #'(quote . 0))` errors because the code assumes that if the `car` of a pair is `quote`, then the pair must be a list.
2. `(syntax->string #'(,hello))` results in `"(unquotehello)"`. Same problem occurs for quasiquote, unquote-splicing,  syntax, quasisyntax, unsyntax, unsyntax-splicing.

**Comment by sorawee** [comment]
One more issue: `(quote a b)` results in `'a`. This can come up in:

```
(syntax->string #'((define (quote a b) (+ a b)) (quote 1 2)))
```

which evaluates to `"(define 'a    (+ a b)) '1"`

**Comment by lkh01** [comment]
I did a bit of work on `syntax->string` in #2911, but I focused on issues #1629 and #1628.
I think I could fix this too, but I could use some help with devising the tests, which is why I missed some of these errors in the first place.

**Comment by sorawee** [comment]
Thanks! The core idea, I think, is to use `syntax-span` to ask how many characters are in the identifier `quote`. If the answer is 1, then it's written using the shorthand form. If the answer is `5`, then it's written using the full form.

Here's another bug: `(syntax->string #'((  a  b  )))` evaluates to `"(  a  b)"`, but it should actually be `"(  a  b  )"`. This could be similarly fixed by finding what `syntax-span` of the syntax list is.

That being said, here are tests:

```
(check-equal? (syntax->string #'((  a  b  ))) "(  a  b  )")
; we can't find where . is, default to earliest position
(check-equal? (syntax->string #'((  a  b  .  c  ))) "(  a  b .   c  )") 

;; quote tests
(check-equal? (syntax->string #'('a)) "'a")
(check-equal? (syntax->string #'('  a)) "'  a")
(check-equal? (syntax->string #'((quote a))) "(quote a)")
(check-equal? (syntax->string #'((  quote  a  ))) "(  quote  a  )")
(check-equal? (syntax->string #'((quote a b))) "(quote a b)")
(check-equal? (syntax->string #'((  quote  a  b  ))) "(  quote  a  b  )")
(check-equal? (syntax->string #'((quote . a))) "(quote . a)")
(check-equal? (syntax->string #'((  quote  .  a  ))) "(  quote .   a  )")
(check-equal? (syntax->string #'((quote a b . c))) "(quote a b . c)")
(check-equal? (syntax->string #'((  quote  a  b  .  c  ))) "(  quote  a  b .   c  )")
```

Then, repeat quote tests with `unquote`, `unquote-splicing`, `syntax`, `quasisyntax`, `unsyntax`, `unsyntax-splicing`. E.g.,

```
(check-equal? (syntax->string #'(,a)) ",a")
(check-equal? (syntax->string #'(,  a)) ",  a")
(check-equal? (syntax->string #'((unquote a))) "(unquote a)")
(check-equal? (syntax->string #'((  unquote  a  ))) "(  unquote  a  )")
...
```

**Comment by sorawee** [comment]
Actually, `span` won't suffice for the syntax list case because `\n` and ` ` are both considered one character. It might make sense to just default to space.

**Comment by sorawee** [comment]
@lkh01 @mflatt @mbutterick @samth : I think we should brainstorm here. What's a reasonable behavior for the following code? In particular, I think they are indistinguishable because the reader loses necessary information to reconstruct the original surface syntax, so we need to default to some behavior.

```
(syntax->string #'((  quote  a  )))
```

and:

```
(syntax->string #'((  quote  a
 )))
```

**Comment by lkh01** [comment]
If we're going to default to something, I think spaces only is the safest bet. 
So my vote goes to:
```
> (syntax->string #'((  quote  a
 )))
"(  quote  a  )"
```
Other than that, we could try fixing the problem at the reader level, by adding the position (column and line) of the last character as a syntax property before that information is lost. 
I'm not sure where to start, though, since I've never tried hacking on the reader so far.

**Comment by sorawee** [comment]
Let me close this since the original issue that I reported is fixed. Adding right parenthesis position could be considered a new feature request.
