### ISSUE TITLE
Bulk bindings not found in registry?

### ISSUE THREAD

**Issue by zyrolasting** [racket/racket#3080]
I've encountered the following error in a private project that uses the Scribble reader for a `#lang`.

```
namespace mismatch: bulk bindings not found in registry for module: #<resolved-module-path:"/home/sage/racket/share/pkgs/at-exp-lib/scribble/reader.rkt">
; Context:
;  .../langs/doc.rkt:28:11 for-loop
;  .../langs/doc.rkt:26:16
; [Due to errors, REPL is just racket/base]
```

What makes this error strange is that it only appears when the Racket modules using the custom `#lang` are compiled into bytecode. If you delete the `compiled` directory next to those modules, the code works as expected.

I copied the project and removed a lot of code to reach what will hopefully be a minimal reproduction: https://github.com/zyrolasting/bulk-bindings-bungle

**Comment by mflatt** [comment]
I bet this has to do with syntax objects injected by a language's `read-syntax` with a non-empty scope. That's not really a good way to do things, but it's the best way we have to do some things.

If you can avoid scopes/bindings on the output of `read-syntax`, then that may solve the problem.

If you need bindings on the output of `read-syntax`, then you should make sure that there's a `require` dependency path (to ensure, in turn, the presence of the bindings at compile time). Is that already the case?

**Comment by zyrolasting** [comment]
I can't say I fully understand, but here's what I did in my interpretation of your post.

1. I removed and consolidated more code to limit the number of moving pieces.
1. I blindly added `for-syntax` to every require spec in the reader submodule and the syntax object it produces.
1. I made sure `read-syntax` used only pattern variables.
1. I stopped using quasisyntax and expanded `code` in the template using only a quote.

The behavior reproduces in the original post, so I'm guessing I hit everything but the target. What am I missing?

**Comment by bennn** [comment]
I tried to reproduce this, but didn't see the error. I'm on Racket commit b69c1208b71

(PS `bulk-bindings-bungle` has an undeclared dep. on `txexpr`)

**Comment by mflatt** [comment]
Looks like the repo with the example has gone away. Is it still around somewhere, or should be just close as "unexplained" for now?

**Comment by zyrolasting** [comment]
The latter, and I apologize. I was too eager with a cleanup job. I will reopen if I find a copy in my files.
