### ISSUE TITLE
arity error in syntax-parse internals

### ISSUE THREAD

**Issue by samth** [racket/racket#3087]
If you run the redex/examples/letrec-vs-racket tests with a random seed of 0 on RacketCS you get this error:

```
[samth@homer:~/.../redex-examples/redex/examples (master) plt] time racocs test letrec-vs-racket.rkt
...e/private/parse.rkt:559:26: arity mismatch;
 the expected number of arguments does not match the given number
  expected: 6
  given: 5
  context...:
   make-arity-exn
   do-raise
   dynamic-wind
   call-in-empty-metacontinuation-frame
   apply-transformer
   dispatch-transformer
   loop
   lambda-clause-expander
   for-loop
   [repeats 1 more time]
   finish-bodys
   lambda-clause-expander
   loop
   [repeats 37 more times]
   module-begin-k
   expand-module
```

The diff to reproduce is just add `(random-seed 0)` at the beginning of the `test` submodule. This doesn't happen on Racket BC.

**Comment by rmculpepper** [comment]
When I try to run that file on Racket CS, with or without the random seed change, the memory usage gets up to about 16 GB virtual / 12-13 GB resident and then kernel's OOM handler eventually kills it. (On Racket BC it finishes in about 10 seconds.)

**Comment by samth** [comment]
I realized I wasn't running an up-to-date racketcs binary, with that changed I see similar behavior. Closing this unless I replicate it.

**Comment by samth** [comment]
Loop filed as #3088.
