### ISSUE TITLE
Loop in RacketCS compiler

### ISSUE THREAD

**Issue by samth** [racket/racket#3088]
This program:

```
(letrec ((hs (letrec ((d T)) d))
          (bo (if + (set! Oh T) (let () wM)))
          (M (Oh))
          (ty
           (let ((v 5)
                 (j (let () q))
                 (N (if ty hs wM))
                 (V (begin bo))
                 (e (hs)))
             #t))
          (i (T (M wM)))
          (wM (letrec ((F =) (n (* F))) (begin wM)))
          (Oh (set! B (if Oh bo -)))
          (T wM)
          (t (if (begin Oh) 3 (letrec () r)))
          (B t))
   ty)
```

seems to make racketcs loop in the compiler. Stack trace when I kill it here:

```
[samth@homer:~/.../redex-examples/redex/examples (master) plt] racketcs -f /tmp/d.rkt 
^Cuser break
  context...:
   p
   call-in-empty-metacontinuation-frame
   check-break-prefix
   call-with-empty-metacontinuation-frame-for-swap
   compile-to-proc
   thunk
   compile-module-linklet
   for-loop
   compile-forms
   compile-top
   temp71_2
   compile
   temp65_2
   proc
   call-in-empty-metacontinuation-frame
   loop
```

**Comment by gus-massa** [comment]
I get

    q: unbound identifier in: q

and after that

    r: unbound identifier in: r

I tried to add some dummy definitions like 

    (define q (read))

or

    (define q 0)

but I don't get the error.

**Comment by samth** [comment]
How long did you have to wait to get an error?

**Comment by mflatt** [comment]
I usually see the hang. By hacking "linklet.sls" to use `compile` instead of `compile*`, I get a backtrace like this:

```
   p
   call-in-empty-metacontinuation-frame
   check-break-prefix
   call-with-empty-metacontinuation-frame-for-swap
   make-1seq*
   dr
   make-seq
   dr
   make-seq
   dr
   make-seq
   dr
   make-seq
```

**Comment by samth** [comment]
Aha, @gus-massa's note caused me to investigate further, and I don't see the hang on my other machine, which has racket/ChezScheme@0bc286e81827f029dd02a3627a192edd053b3b91 but I do see it on my machine which has racket/ChezScheme@1c44e61a8174629cacc71adedccc028e982ca323.

**Comment by mflatt** [comment]
... and my installed `scheme` was similarly out-of-date.

**Comment by mflatt** [comment]
Here's a variant to load directly in Chez Scheme (based on `PLT_LINKLET_SHOW`):

```
(define-syntax |#%app|
  (syntax-rules ()
    [(_ f a ...) (f a ...)]))

(lambda (instance-variable-reference .top-level-bind!1
         .top-level-require!2 .mpi-vector3 .syntax-literals4
         .namespace5 .phase6 .self7 .inspector8
         .bulk-binding-registry9 .set-transformer!10 r11 q12)
  (let ([hs_1 unsafe-undefined]
        [bo_2 unsafe-undefined]
        [M_3 unsafe-undefined]
        [ty_4 unsafe-undefined]
        [i_5 unsafe-undefined]
        [wM_6 unsafe-undefined]
        [Oh_7 unsafe-undefined]
        [T_8 unsafe-undefined]
        [t_9 unsafe-undefined]
        [B_10 unsafe-undefined])
    (set! hs_1
      (let ([d_11 unsafe-undefined])
        (set! d_11 (check-not-unsafe-undefined T_8 'T))
        d_11))
    (set! bo_2
      (if +
          (let ([set13 (check-not-unsafe-undefined T_8 'T)])
            (check-not-unsafe-undefined/assign Oh_7 'Oh)
            (set! Oh_7 set13))
          (check-not-unsafe-undefined wM_6 'wM)))
    (set! M_3 (|#%app| (check-not-unsafe-undefined Oh_7 'Oh)))
    (set! ty_4
      (let ([j_13 (variable-ref q12)])
        (let ([N_14 (if (check-not-unsafe-undefined ty_4 'ty)
                        hs_1
                        (check-not-unsafe-undefined wM_6 'wM))])
          (let ([V_15 bo_2])
            (let ([e_16 (|#%app| hs_1)])
              (let ([V_15 V_15] [N_14 N_14] [j_13 j_13]) #t))))))
    (set! i_5
      (let ([app_18 (check-not-unsafe-undefined T_8 'T)])
        (|#%app|
          app_18
          (let ([app_16 M_3])
            (|#%app| app_16 (check-not-unsafe-undefined wM_6 'wM))))))
    (set! wM_6
      (let ([F_17 unsafe-undefined] [n_18 unsafe-undefined])
        (set! F_17 =)
        (set! n_18 (* =))
        (check-not-unsafe-undefined wM_6 'wM)))
    (set! Oh_7
      (let ([set20 (if (check-not-unsafe-undefined Oh_7 'Oh)
                       bo_2
                       -)])
        (check-not-unsafe-undefined/assign B_10 'B)
        (set! B_10 set20)))
    (set! T_8 (check-not-unsafe-undefined wM_6 'wM))
    (set! t_9
      (if (check-not-unsafe-undefined Oh_7 'Oh)
          3
          (variable-ref r11)))
    (set! B_10 t_9)
    (check-not-unsafe-undefined ty_4 'ty)))
```

**Comment by samth** [comment]
That also indicates why this bug showed up when it did, and why the `pkg-show` page on DrDr didn't show the problem. @jeapostrophe can you add a top-level DrDr command that just prints the SHA for `racket/src/build/ChezScheme` on every run?

**Comment by samth** [comment]
Simpler:

```
(lambda (instance-variable-reference .top-level-bind!1
         .top-level-require!2 .mpi-vector3 .syntax-literals4
         .namespace5 .phase6 .self7 .inspector8
         .bulk-binding-registry9 .set-transformer!10)
  (let ([hs_1 unsafe-undefined]
        [bo_2 unsafe-undefined]
        [M_3 unsafe-undefined]
        [ty_4 unsafe-undefined]
        [i_5 unsafe-undefined]
        [wM_6 unsafe-undefined]
        [Oh_7 unsafe-undefined]
        [T_8 unsafe-undefined]
        [t_9 unsafe-undefined]
        [B_10 unsafe-undefined])
    (set! hs_1
      (let ([d_11 unsafe-undefined])
        (set! d_11 (check-not-unsafe-undefined T_8 'T))
        d_11))
    (set! bo_2 #t)
    (set! M_3 (check-not-unsafe-undefined Oh_7 'Oh))
    (set! ty_4 #t)
    (set! i_5 (check-not-unsafe-undefined T_8 'T))
    (set! wM_6
      (let ([n_13 (=)]) (check-not-unsafe-undefined wM_6 'wM)))
    (set! Oh_7
      (let ([set11 (if (check-not-unsafe-undefined Oh_7 'Oh)
                       bo_2
                       #t)])
        (check-not-unsafe-undefined/assign B_10 'B)
        (set! B_10 set11)))
    (set! T_8 (check-not-unsafe-undefined wM_6 'wM))
    (set! t_9 #t)
    (set! B_10 t_9)
    ty_4))
```

**Comment by mflatt** [comment]
Smaller:
```
(lambda ()
  (let ([bo_2 unsafe-undefined]
        [wM_6 unsafe-undefined]
        [Oh_7 unsafe-undefined]
        [B_10 unsafe-undefined])
    (set! wM_6
      (let ([F_17 unsafe-undefined] [n_18 unsafe-undefined])
        (set! F_17 =)
        (set! n_18 (* =))
        (check-not-unsafe-undefined wM_6 'wM)))
    (set! Oh_7
      (let ([set20 (if (check-not-unsafe-undefined Oh_7 'Oh)
                       bo_2
                       -)])
        (check-not-unsafe-undefined/assign B_10 'B)
        (set! B_10 set20)))))
```

**Comment by samth** [comment]
Git bisect suggests that the problematic commit is racket/ChezScheme@fe085761cbd200f4c67025d968d6d1418ab7d3e7 by @gus-massa.

**Comment by gus-massa** [comment]
A shorter example, to load in Chez Scheme

    (lambda (f)
      (set! f (* 'error))
      (if (f) f 0))

**Comment by samth** [comment]
This program (very large), seemingly without a `set!` or `letrec`, also has the problem, but in `jitify`: https://gist.github.com/190f98e0424e982cc81f59832259d70e

**Comment by gus-massa** [comment]
I did't check the long example yet, but will be helpful to check that the fix can fix all problems.

A smaller example:

    (lambda (f)
      (box? (box (f))))

The important part is is reduced to `(#3%$value (f))`. The `drop` tries to discard it in  [cptypes.ss#L176-L185](https://github.com/racket/ChezScheme/blob/master/s/cptypes.ss#L176-L185) and notices that the `#3%$value` is not doing anything and can be removed.  But it is necessary to check that `(f)` is single value, so it is wrapped in a new copy of `#3%$value`, and then the compiler checks if the new copy of `(#3%$value (f))` cab be discarded calling `drop` ...

I think it's easy to solve just checking that the name of the primitive is not `$value` but it would be nice to remove any unnecessary `$value`, so the fix will need a few lines for this special case.

**Comment by gus-massa** [comment]
Fixed in https://github.com/racket/ChezScheme/commit/858cc5fe0f40e73a3473e3cc3f506c2c232c0a81

**Comment by samth** [comment]
Two things: 
1. You can write "fixes racket/racket#3088" in the commit message in other repositories.
2. Should we add some Racket-level tests for this?

**Comment by jeapostrophe** [comment]
> @jeapostrophe can you add a top-level DrDr command that just prints the SHA for `racket/src/build/ChezScheme` on every run?

I think it would be better to put this in the `Makefile`, but if you really disagree, I can do it. Can you tell me exactly what information you want though... `cd racket/src/build/ChezScheme && git status`?

**Comment by samth** [comment]
By "put this in Makefile" do you mean "print the SHA by default in `make both`" or "add a new make target"? I'm hoping for something like the top-level `pkg-show` (http://drdr.racket-lang.org/53722/pkg-show) so that it's easy to see when it changed.

**Comment by samth** [comment]
For the command, I think `(cd racket/src/build/ChezScheme/ && git log --oneline -n 1)` would be good.

**Comment by jeapostrophe** [comment]
I meant "print the SHA by default in `make both`"

So, you mean if there's a new top-level thing, then the output will be the same for a very long time and then when it does, it is always interesting.

**Comment by samth** [comment]
Yes, that's what I mean. The output of make changes regularly, and I find the "Changed" checkmark for pkg-show to be very helpful (and the ability to diff it).

**Comment by gus-massa** [comment]
@samth: I was triying to tranlate my short example to Racket, but there are some problem. One is that `racket:box?` is not `chez:box?` because it checks for impersonators (perhaps the fast optimistic case should be inlined?). The second is that `(f)` is expanded to allow aplicative structs. So the additional things that schemify adds hide the bug.

An alternative is to use something like the original example that uses `(set! x (* 'error))`, that creates a weird state because the return type of the expression is `#<void>` and the bag with the types of all the variables is `pred-env-bottom` (i.e. all variables are `'bottom`). This should not cause problems, but I'd probably add soon the line to make the return type `'bottom` too.

Anyway, while looking for easy alternatives I found another bug: https://github.com/racket/racket/issues/3092

**Comment by samth** [comment]
I would just go with one of the original examples, probably -- having something is better than worrying too much.

**Comment by gus-massa** [comment]
I minimized the first example to 

    #lang racket
    (letrec ([x (* 'error)]
             [y (if y x 0)])
       0)

I'm not sure where to include it.

**Comment by samth** [comment]
Maybe is basic.rktl?
