### ISSUE TITLE
vector->values: ending index is out of range

### ISSUE THREAD

**Issue by BearJean** [racket/racket#3094]
```
调用tool #<path:C:\Program Files\Racket\share\pkgs\algol60>出错；("tool.rkt")
调用tool #<path:C:\Program Files\Racket\share\pkgs\deinprogramm\deinprogramm>出错；"sdp/private/sdp-langs.rkt"
调用tool #<path:C:\Program Files\Racket\share\pkgs\deinprogramm\deinprogramm>出错；"DMdA/private/DMdA-langs.rkt
调用tool #<path:C:\Program Files\Racket\share\pkgs\htdp-lib\lang>出错；"htdp-langs.rkt"
调用tool #<path:C:\Program Files\Racket\share\pkgs\lazy>出错；("lazy-tool.rkt")
调用tool #<path:C:\Program Files\Racket\share\pkgs\optimization-coach\optimization-coach>出错；("tool.rkt")
调用tool #<path:C:\Program Files\Racket\share\pkgs\quickscript>出错；("tool.rkt")
调用tool #<path:C:\Program Files\Racket\share\pkgs\rackunit-plugin-lib\rackunit>出错；("tool.rkt")
调用tool #<path:C:\Program Files\Racket\share\pkgs\deinprogramm-signature\deinprogramm\signature>出错；"tool.rkt"
调用tool #<path:C:\Program Files\Racket\share\pkgs\slideshow-plugin\slideshow>出错；("tool.rkt")
调用tool #<path:C:\Program Files\Racket\share\pkgs\htdp-lib\stepper>出错；("stepper+xml-tool.rkt")
调用tool #<path:C:\Program Files\Racket\share\pkgs\swindle>出错；("tool.rkt")
调用tool #<path:C:\Program Files\Racket\share\pkgs\htdp-lib\test-engine>出错；("test-tool.scm")
调用tool #<path:C:\Program Files\Racket\share\pkgs\frtime\tool>出错；"frtime-tool.rkt"
调用tool #<path:C:\Program Files\Racket\share\pkgs\htdp-lib\xml>出错；("text-box-tool.rkt")
vector->values: ending index is out of range
  ending index: 166
  starting index: 0
  valid range: [0, 164]
  vector: '#(#<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52>...
```
whenever I open DrRacket,that occur in a cmd"DrRacket"。

**Comment by samth** [comment]
Is there any more of the error message anywhere?

**Comment by BearJean** [comment]
sorry the Complete information is:

Error invoking tool #<path:C:\Program Files\Racket\share\pkgs\algol60>;("tool.rkt")

vector->values: ending index is out of range
  ending index: 166
  starting index: 0
  valid range: [0, 164]
  vector: '#(#<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52>...
Error invoking tool #<path:C:\Program Files\Racket\share\pkgs\deinprogramm\deinprogramm>;"sdp/private/sdp-langs.rkt"

vector->values: ending index is out of range
  ending index: 166
  starting index: 0
  valid range: [0, 164]
  vector: '#(#<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52>...
Error invoking tool #<path:C:\Program Files\Racket\share\pkgs\deinprogramm\deinprogramm>;"DMdA/private/DMdA-langs.rkt"

vector->values: ending index is out of range
  ending index: 166
  starting index: 0
  valid range: [0, 164]
  vector: '#(#<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52>...
Error invoking tool #<path:C:\Program Files\Racket\share\pkgs\htdp-lib\lang>;"htdp-langs.rkt"

vector->values: ending index is out of range
  ending index: 166
  starting index: 0
  valid range: [0, 164]
  vector: '#(#<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52>...
Error invoking tool #<path:C:\Program Files\Racket\share\pkgs\lazy>;("lazy-tool.rkt")

vector->values: ending index is out of range
  ending index: 166
  starting index: 0
  valid range: [0, 164]
  vector: '#(#<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52>...
Error invoking tool #<path:C:\Program Files\Racket\share\pkgs\optimization-coach\optimization-coach>;("tool.rkt")

vector->values: ending index is out of range
  ending index: 166
  starting index: 0
  valid range: [0, 164]
  vector: '#(#<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52>...
Error invoking tool #<path:C:\Program Files\Racket\share\pkgs\quickscript>;("tool.rkt")

vector->values: ending index is out of range
  ending index: 166
  starting index: 0
  valid range: [0, 164]
  vector: '#(#<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52>...
Error invoking tool #<path:C:\Program Files\Racket\share\pkgs\rackunit-plugin-lib\rackunit>;("tool.rkt")

vector->values: ending index is out of range
  ending index: 166
  starting index: 0
  valid range: [0, 164]
  vector: '#(#<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52>...
Error invoking tool #<path:C:\Program Files\Racket\share\pkgs\deinprogramm-signature\deinprogramm\signature>;"tool.rkt"

vector->values: ending index is out of range
  ending index: 166
  starting index: 0
  valid range: [0, 164]
  vector: '#(#<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52>...
Error invoking tool #<path:C:\Program Files\Racket\share\pkgs\slideshow-plugin\slideshow>;("tool.rkt")

vector->values: ending index is out of range
  ending index: 166
  starting index: 0
  valid range: [0, 164]
  vector: '#(#<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52>...
Error invoking tool #<path:C:\Program Files\Racket\share\pkgs\htdp-lib\stepper>;("stepper+xml-tool.rkt")

vector->values: ending index is out of range
  ending index: 166
  starting index: 0
  valid range: [0, 164]
  vector: '#(#<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52>...
Error invoking tool #<path:C:\Program Files\Racket\share\pkgs\swindle>;("tool.rkt")

vector->values: ending index is out of range
  ending index: 166
  starting index: 0
  valid range: [0, 164]
  vector: '#(#<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52>...
Error invoking tool #<path:C:\Program Files\Racket\share\pkgs\htdp-lib\test-engine>;("test-tool.scm")

vector->values: ending index is out of range
  ending index: 166
  starting index: 0
  valid range: [0, 164]
  vector: '#(#<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52>...
Error invoking tool #<path:C:\Program Files\Racket\share\pkgs\frtime\tool>;"frtime-tool.rkt"

vector->values: ending index is out of range
  ending index: 166
  starting index: 0
  valid range: [0, 164]
  vector: '#(#<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52>...
Error invoking tool #<path:C:\Program Files\Racket\share\pkgs\htdp-lib\xml>;("text-box-tool.rkt")

vector->values: ending index is out of range
  ending index: 166
  starting index: 0
  valid range: [0, 164]
  vector: '#(#<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52> #<procedure:.../racket/unit.rkt:1032:52>...

OS version:windows 2004
DrRacket version:7.6.
what I do:
No problems before, until the last time I opened a pkg source file with DrRacket.
the information above occur in cmd before DrRacketGUI open whenever I open it.
but the DrRacket itself work normal.

**Comment by BearJean** [comment]
I reinstalled the software and it disappeared, maybe I accidentally modified a file, sorry.
