### ISSUE TITLE
`s-exp->fasl` fails to encode small data

### ISSUE THREAD

**Issue by mbutterick** [racket/racket#3095]
Peculiar error on Mac OS / Racket 7.6 (either BC or CS). Fasl encoding seems to fail if the data is insufficiently large. In this example, a list of 1132 ints (or more) will be encoded successfully, but a list of 1131 ints (or fewer) will not:

```racket
#lang racket/base
(require racket/fasl racket/list)

(define (test-fasl val)
  (define fn "fasl.rktd")
  (s-exp->fasl val (open-output-file fn #:exists 'replace))
  (equal? val (fasl->s-exp (open-input-file "fasl.rktd"))))

(test-fasl (range 2000)) ; #true
(test-fasl (range 1132)) ; #true 
(test-fasl (range 1131)) ; error parsing fasl stream (Racket BC)
(test-fasl (range 1127)) ; error parsing fasl stream (Racket CS)
```
On my machine, the threshold of failure is slightly different for BC and CS, but close.

**Comment by sorawee** [comment]
Looks like the writes are not flushed on `s-exp->fasl`. Adding `flush-output` on the port solves the problem.

**Comment by sorawee** [comment]
This is why we should always use `close-output-port` or use `call-with-output-file*`/`with-output-to-file`. So I don't think this is a Racket issue.

**Comment by mbutterick** [comment]
OK, fair enough. Thanks.
