### ISSUE TITLE
Hard-to-debug internal error using scribble/manual @code form.

### ISSUE THREAD

**Issue by rxg** [racket/racket#3102]
Seeming misuse of @code leads to a read-syntax error that does not point to the source of the error, even in my backtrace.  In a large document, it's painful to track down the error (using comment-based triage)

To reproduce, try to create html from a file with the following content:

```
#lang scribble/manual

@code|{A . + . B}|

```

**Comment by samth** [comment]
The error message for that file is:

```
[samth@homer:~/work/Agenda (master) plt] r /tmp/x.scrbl 
prog:1:2: read-syntax: illegal use of `.`
  context...:
   read-symbol-or-number
   read-undotted
   read-syntax
   /home/samth/sw/plt/racket/share/pkgs/scribble-lib/scribble/private/manual-code.rkt:112:0: get-tokens
   /home/samth/sw/plt/racket/share/pkgs/scribble-lib/scribble/private/manual-code.rkt:56:0: typeset-code
   "/tmp/x.scrbl": [running body]
   temp35_0
   for-loop
   run-module-instance!
   perform-require!
```

I'm pretty sure this is a result of `code` not setting the port name that it creates, but I'll check more.

**Comment by samth** [comment]
I opened racket/scribble#226 to fix this.
