### ISSUE TITLE
[cs] `dump-memory-stats` crashes with contracted keyword-argument functions

### ISSUE THREAD

**Issue by LLazarek** [racket/racket#3113]
Summary: `dump-memory-stats` crashes when there's a function `define`d in the same module that has:
1. a mandatory keyword argument
2. a contract attached to it (e.g. by `contract` or `define/contract`)

Specifically, it crashes with a format error: `fprintf: incomplete format directive "~-"`.

It does not happen when the function is defined in another module and provided with `contract-out`. 
It also does not happen without the contract.

Example to reproduce (tested on `v7.7.0.2 [cs]`):
```racket
#lang racket

(define foo
  (contract (-> #:x any/c any/c)
            (λ (#:x x) 0)
            'pos
            'neg))

(dump-memory-stats)
```
Output:
```
Begin Dump                                                                                        
Current memory use: 92757968                                                                      
Begin RacketCS                                                                                    
 locked                         0            0  |          1          352                         
 fxvector                       0            0  |          3        8,240
 ... many more lines ...
 #<will-executor>               1           48  |          9          432
 #<procedure-chaperone>         1           48  |          1           48
fprintf: incomplete format directive "~-"
  context...:
   condition->exn
   do-raise
   dynamic-wind
   go
   dump-memory-stats
   call-with-values
   call-in-empty-metacontinuation-frame
   body of "/tmp/test.rkt"
   for-loop
   run-module-instance!
   perform-require!
   namespace-require+
   #%for-each
   call-in-empty-metacontinuation-frame
   thunk_10
   call-in-empty-metacontinuation-frame

**Comment by samth** [comment]
I think what's happening here is that some of the structures in `rumble/impersonator.ss` have `~-` in their name, and those names get substituted into a string which is then used again as a format string in the implementation of `dump-memory-stats`.
