### ISSUE TITLE
[7.6 CS] Persistent, deeply confusing linklet blocker and non-existent phase 0

### ISSUE THREAD

**Issue by zyrolasting** [racket/racket#3128]
EDIT: Brevity.

I ran into this in my project.

![image](https://user-images.githubusercontent.com/1312121/80175122-b7aded00-85c2-11ea-970e-0c8ab08da08c.png)

I didn't change those files, but I ran `raco make` anyway. Error persists. Okay. I deleted `~/racket/collects/racket/contract/private/compiled`. Then I got this.

```
eval: namespace mismatch: phase level not found;
  module: #<module-path-index:"unit-contract-syntax.rkt" + 'unit-contract[111852]>
  phase level: 0
```

The... runtime doesn't exist? I ran `raco make *.rkt` in `contract/private`. Error for `list` re: `*list-ctx-suffix` came back. I ran `raco setup`, which took an hour. `*list-ctx-suffix` error came back. I reinstalled Racket. Error Persists. On one attempt I saw the same `phase level not found` error, except the first line read `module: <module-path-index:"util.rkt" + 'closure[4542]>`.

## Reproduction steps, as far as I can tell
This console session will install some unreleased packages along with the source code for my private website located at zyrolasting/sgcom. I am not going to ask you to read all of my code. I'll just give you a console session, add details as I poke around, and answer any questions.

I added some of you as collaborators, as I've done before. If we've spoken before, you should have access. If you don't, ping me.

```
git clone git@github.com:zyrolasting/sgcom.git
raco pkg install https://github.com/zyrolasting/unlike-assets.git?path=unlike-assets#asset-packages
raco pkg install https://github.com/zyrolasting/unlike-assets.git?path=unlike-assets-css#asset-packages
raco pkg install ./sgcom
sgcom work -dv all
```
Accept the dry run when prompted. The last command is where I see the aforementioned errors.

**Comment by mflatt** [comment]
My best guess at the moment is that something is wrong with `(dynamic-require module-path (void))`. That's a relatively weird action, it would not get used much (if at all), and it would be easy for that go wrong wrong with the symptoms you're seeing. It may be just a missing force of on-demand visits, or something like that.

It looks like you're using `(dynamic-require .... (void))` to force a module to be loaded/declared. Does using `(module-declared? module-path #t)` work better?

**Comment by mflatt** [comment]
Unrelated, but in "highlight-code.rkt", I recommend `(process*/ports #f #f (current-error-port) ....)` to run a program and let error messages through if you're otherwise going to ignore stderr.

**Comment by zyrolasting** [comment]
Thanks much. The project is set to load every Racket module in `assets/` with reload support so I can interact with them via a project server. I expect that every module targeted by `(dynamic-require modpath (void))` is first hit by `dynamic-rerequire`.

I switched `(void)` to `#f`.

The errors are now _intermittent_. Meaning, I am _sometimes_ able to get to the end of `sgcom work -dv all`. When I don't, I see different instances of the same errors. Some still repeat after `raco make`.

```
instantiate-linklet: mismatch;
  name: if-stream-out
  exporting instance: "/home/sage/racket/collects/racket/private/streams.rkt"
  importing instance: "/home/sage/racket/collects/racket/place.rkt"
```

```
...
exporting instance: "/home/sage/racket/share/pkgs/parser-tools-lib/parser-tools/private-lex/deriv.rkt"
importing instance: "/home/sage/racket/share/pkgs/parser-tools-lib/parser-tools/private-lex/front.rkt"
```
```
eval: namespace mismatch: phase level not found;
  module: #<module-path-index:racket/struct>
  phase level: 0
  found phase levels: ()
```

I suspect something scheduling related. There is only one source of threads of my doing. The unreleased package is acting as an asynchronous module resolver that promises to deliver only the latest version of a value, and it has a plugin for Racket modules.

Here's the code that computes a new value: https://github.com/zyrolasting/unlike-assets/blob/asset-packages/unlike-assets/unlike-assets/resolver/pod.rkt#L38

And here's where Racket modules (re)load for its sake: https://github.com/zyrolasting/unlike-assets/blob/asset-packages/unlike-assets/unlike-assets/racket-modules.rkt#L38 The `make-pod/fenced` expression means "Try dynamic-rerequire. If you get a non-empty list, apply `make-asset` to get a new value."

I switched `#:verbosity` on `dynamic-rerequire` to `'all`, but I saw no extra output.

Do you see any funny business in that light?

**Comment by mflatt** [comment]
I think you're saying that Racket modules might get `dynamic-rerequire`d in a thread. That does seem like a potential problem, because the expander doesn't expect to have races in code that is roughly
```
(begin
  (make-sure-all-available-modules-are-visited)
  (do-something-that-needs-visited-modules))
```
That particular example seems like a stretch, but maybe there are other issues in the expander if modules are loaded into a namespace concurrent with other loading or expansion.

If I understand correctly, it is possible to disable the thread and make it synchronous?

**Comment by zyrolasting** [comment]
You understand correctly, and my website behaves like that pseudocode. I can refactor away the threads and replace them with enclosing lambdas. I will keep this issue open in case the problem persists or I encounter a design limitation.

**Comment by mflatt** [comment]
Racket v8.1.0.5 provides `namespace-call-with-registry-lock`. See #3809 for more on why the lock is not automatically used by `dynamic-require` and similar, but maybe it would hep with the problem here.

**Comment by mflatt** [comment]
@zyrolasting Should we close this or keep it open? I think the situation has at least improved, in that `namespace-call-with-registry-lock` offers a way to synchronize, but it's far from clear that it's the best solution or even whether it's always practical.

**Comment by zyrolasting** [comment]
I apologize for vanishing. I changed my approach to dodge my original problem, but am happy to see your suggestion now. I do not see reason to keep this open, so I'll close it out now. Thank you.
