### ISSUE TITLE
(Racket CS) read-line-evt mode `'any` behaves differently to read-line (also read-bytes-line-evt/read-bytes-line)

### ISSUE THREAD

**Issue by tonyg** [racket/racket#3132]
**(Racket CS only -- non-CS Racket doesn't have this problem)**

The following program, run interactively and fed lines one at a time, accepts the first without yielding output, so the output is delayed by one line wrt the input.

The program:

```racket
#lang racket
(define stdin-evt (read-line-evt (current-input-port) 'any))
(let loop ()
  (sync (handle-evt stdin-evt
                    (lambda results
                      (printf "~v\n" results)
                      (when (not (eof-object? (car results)))
                        (loop))))))
```

Input (line at a time, with pauses):

```
1
2
3
<control D to end the input>
```

Actual output:

```
1
2
'("1")
3
'("2")
'("3")
'(#<eof>)
```

Expected output:

```
1
'("1")
2
'("2")
3
'("3")
'(#<eof>)
```

Compare to the following program, which doesn't have the off-by-one issue:

```racket
#lang racket
(let loop ()
  (define line (read-line (current-input-port) 'any))
  (printf "~v\n" line)
  (when (not (eof-object? line))
    (loop)))
```

The issue vanishes for `read-line-evt` if you use mode `'any-one`, so I'm guessing there's some state machine somewhere that's peeking too much input when it sees a newline.

**Comment by mflatt** [comment]
Looks like the problem is in the matcher where it wants to match to a literal string like "\r\n". In that case, it checks first for two bytes available, instead of checking for one byte as "\r" and only then checking whether another byte is available.

**Comment by tonyg** [comment]
In a Racket CS installation, changing `collects/racket/port.rkt` so that the definition for `read-bytes-line-evt` reads as follows "fixes" the bug, by checking for `\n`, then `\r\n`, then `\r`, unlike the checked-in code, which checks for `\r\n` first.

```racket
(define read-bytes-line-evt
  (lambda (input-port [mode 'linefeed])
    (wrap-evt
     (regexp-match-evt (case mode
                         [(linefeed) (newline-rx "\n")]
                         [(return) (newline-rx "\r")]
                         [(return-linefeed) (newline-rx "\r\n")]
                         [(any) (newline-rx "(?:\n|\r\n|\r)")]
                         [(any-one) (newline-rx "[\r\n]")])
                       input-port)
     (lambda (m)
       (or (cadr m)
           (let ([l (caddr m)])
             (if (and l (zero? (bytes-length l))) eof l)))))))
```

This could (?) be considered enough of a fix, but it only really changes things for Unix-style input. Mac-style input would still wait indefinitely for a `\r`. However, I've not tested Mac-style input at all so I don't know whether it works even on non-CS racket.

**Comment by mflatt** [comment]
Thanks for the suggested workaround, which may be useful for someone more in a position to modify "port.rkt" than to pull the general repair. :)

**Comment by tonyg** [comment]
Wow, thanks Matthew. Amazing as always!
