### ISSUE TITLE
log-info doesn't work?

### ISSUE THREAD

**Issue by lucabol** [racket/racket#3133]
Apologies if I missed something obvious ...

I created a file `test-log.rkt` with the following code:
~~~~racket
#lang racket
(log-info "test")
~~~~

I then call: `racket -L "info" test-log.rkt`. Nothing is displayed. I have tried setting the `PLTSYSLOG` environment variable as well. I am running Racket 7.6 on Windows 10.

**Comment by mflatt** [comment]
Did you mean `racket -W info test-log.rkt` or `PLTSTDERR` to see output in a console?

Using `-L` ot setting `PLTSYSLOG` means that the logged message goes to the system log, which on Windows you can read with the "Event Viewer" application.

**Comment by lucabol** [comment]
Apologies. Beginner mistake. I am not sure how I misread the docs. Sorry to burn some of your cycles. I'll close this.

**Comment by mflatt** [comment]
No problem — I'm happy if that's all it is!
