### ISSUE TITLE
Preserve procedure-arity for composed functions

### ISSUE THREAD

**Issue by countvajhula** [racket/racket#3137]
**Observed behavior**: For composed functions, `procedure-arity` always(?) reports an arity of `at least 0`.

**Expected behavior**: the arity of a composed function should be the same as the arity of the leading function in the composition.

**Example**:
```
(define (str-append-3 x y z)
  (string-append x y z))
```
`(procedure-arity str-append-3) ; => 3`

```
(define f (compose string-length str-append-3))
(procedure-arity f) ; => (arity-at-least 0)
```
```
(f "hello" "there" "friend") ; => 16
(f "hello")
; str-append-3: arity mismatch;
;  the expected number of arguments does not match the given number
;   expected: 3
;   given: 1
; Context:
;  .../private/list.rkt:322:16 composed
;  .../racket/repl.rkt:11:26

```
**Additional details** (probably superfluous, but in case it is useful):
I'm using `procedure-arity` inside an experimental high-level function abstraction that can in principle stand in for normal functions but provide additional insight into their composition and semantics. It is also curried by default, like Haskell functions. `procedure-arity` is being used to report the arity of the composed function inside the wrapper struct, to decide whether the fresh arguments should be incorporated into the function call to return a curried function, or whether the results of invocation (including errors, such as arity errors) should simply be returned to the caller. Since the arity reported for the composed function doesn't match the leading function arity (leading to premature termination of currying) I'm instead checking the leading function specifically (which is retained and only composed at invocation time), which works correctly. But I'm not sure if this might lead to other issues down the line -- for instance, if the leading function is already (an elementary) composed one, it seems like we wouldn't be able to reliably know the arity here.

**Comment by NoahStoryM** [comment]
The comment in the source (https://github.com/racket/racket/blob/master/racket/collects/racket/private/list.rkt#L336) says that the reason why `procedure-reduce-keyword-arity` is not used to preserve the information is because it adds a significant overhead. But if I understand correctly, `compose` runs `mk-simple-compose` at most twice, which means it runs `procedure-reduce-keyword-arity` at most twice too, why is there a significant overhead?
