### ISSUE TITLE
2 Scripts menu items

### ISSUE THREAD

**Issue by gknauth** [racket/racket#3139]
20200430-eea9a85 snapshot Mac OS X 64-bit Intel
I have two Scripts Menu items in the menu bar.
![2scripts](https://user-images.githubusercontent.com/74927/80761460-9b510980-8b08-11ea-8d7b-5f7d9da8727d.jpg)

**Comment by mflatt** [comment]
@gknauth Is this still happening? I don't see it on my machine, but I don't recall seeing it before.

**Comment by gknauth** [comment]
@mflatt Just tried DrRacket on Mac & Windows. It's not happening any more.

**Comment by mflatt** [comment]
Thanks!
