### ISSUE TITLE
racket locking during build

### ISSUE THREAD

**Issue by pmatos** [racket/racket#3140]
I have been finding that with `CPUS=16` (or any higher number) I tend to get locks during the `xform` portion of the build. In specific when trying `make snapshot-site CONFIG=$PWD/.github/workflows/site-small.rkt CPUS=16` from the root racket folder I get stuck at some point and Ctrl-C generates:
```
env XFORM_USE_PRECOMP=xsrc/precomp.h ../racketcgc -G /home/pmatos/dev/racket/build/config -O "info@compiler/cm error" -l- setup --boot /home/pmatos/dev/racket/racket/src/build/../racket/gc2/../../setup-go.rkt ../../compiled --tag ++out /home/pmatos/dev/racket/racket/src/build/../racket/gc2/xform-mod.rkt --depends --cpp "gcc -E -I./.. -I/home/pmatos/dev/racket/racket/src/build/../racket/gc2/../include -I/home/pmatos/dev/racket/racket/src/build/../racket/gc2/../../rktio -I../../rktio -g -O2  -pthread   -DUSE_SENORA_GC   "  --keep-lines -o ++out xsrc/hash.c /home/pmatos/dev/racket/racket/src/build/../racket/gc2/../src/hash.c
^Cuser break
  context...:
   /home/pmatos/dev/racket/racket/collects/compiler/private/xform.rkt:508:10: loop
   /home/pmatos/dev/racket/racket/collects/compiler/private/xform.rkt:8:2: xform
   "/home/pmatos/dev/racket/racket/src/racket/gc2/xform-mod.rkt": [running body]
   temp35_0
   for-loop
   run-module-instance!
   "/home/pmatos/dev/racket/racket/collects/setup/main.rkt": [running body]
   temp35_0
   for-loop
   run-module-instance!
   perform-require!
```

The backtrace is not necessarily always the same. In a previous run I got:
```
env XFORM_USE_PRECOMP=xsrc/precomp.h ../racketcgc -G /home/pmatos/dev/racket/build/config -O "info@compiler/cm error" -l- setup --boot /home/pmatos/dev/racket/racket/src/build/../racket/gc2/../../setup-go.rkt ../../compiled --tag ++out /home/pmatos/dev/racket/racket/src/build/../racket/gc2/xform-mod.rkt --depends --cpp "gcc -E -I./.. -I/home/pmatos/dev/racket/racket/src/build/../racket/gc2/../include -I/home/pmatos/dev/racket/racket/src/build/../racket/gc2/../../rktio -I../../rktio -g -O2  -pthread   -DUSE_SENORA_GC   "  --keep-lines -o ++out xsrc/jitinline.c /home/pmatos/dev/racket/racket/src/build/../racket/gc2/../src/jitinline.c
^Cuser break
  context...:
   /home/pmatos/dev/racket/racket/collects/racket/system.rkt:125:8: control
   /home/pmatos/dev/racket/racket/collects/compiler/private/xform.rkt:8:2: xform
   "/home/pmatos/dev/racket/racket/src/racket/gc2/xform-mod.rkt": [running body]
   temp35_0
   for-loop
   run-module-instance!
   "/home/pmatos/dev/racket/racket/collects/setup/main.rkt": [running body]
   temp35_0
   for-loop
   run-module-instance!
   perform-require!
make[11]: *** [Makefile:248: xsrc/jitinline.c] Error 1
make[10]: *** [Makefile:178: all] Interrupt
make[9]: *** [Makefile:109: 3m] Interrupt
make[8]: *** [Makefile:63: 3m] Interrupt
make[7]: *** [Makefile:56: racket-variant] Interrupt
make[6]: *** [Makefile:206: plain-base] Interrupt
make[5]: *** [Makefile:731: plain-server] Interrupt
make[4]: *** [Makefile:713: with-setup-flags] Interrupt
make[3]: *** [Makefile:727: server] Interrupt
make[2]: *** [Makefile:988: installers] Interrupt
make[1]: *** [Makefile:1008: site] Interrupt
make: *** [Makefile:1026: snapshot-site] Interrupt
```

I don't have time to investigate now but wanted to keep this on record. This is on my Linux machine, arch linux, 16cores.

**Comment by pmatos** [comment]
Also - after Ctrl-C, if I run the command line on its own it finishes within a few seconds.

**Comment by mflatt** [comment]
I'm not able to replicate this so far.

Just to make sure, how long did you let it stay stuck? Files like "jitinline.c" and "jitcommon.c" take a long time to compile — upwards of 20 seconds on my machine — so that could look like getting stuck compared to everything else that happens before.

**Comment by mflatt** [comment]
It seems possible that a SIGCHLD is getting lost somehow on Linux with enough cores. Might be related to #3127.

**Comment by pmatos** [comment]
> I'm not able to replicate this so far.
> 
> Just to make sure, how long did you let it stay stuck? Files like "jitinline.c" and "jitcommon.c" take a long time to compile — upwards of 20 seconds on my machine — so that could look like getting stuck compared to everything else that happens before.

Several minutes - `top` shows no CPU usage.

**Comment by pmatos** [comment]
> It seems possible that a SIGCHLD is getting lost somehow on Linux with enough cores. Might be related to #3127.

Will test - thanks.

**Comment by mflatt** [comment]
FWIW, it's not going to be related to #3127, which was specific to a sandbox function and mostly to CS.

**Comment by pmatos** [comment]
@mflatt I have tested this several times with tip of master on several configuration and cannot repro it anymore so I assume it's fixed.

Thanks for looking into it.
