### ISSUE TITLE
No such device or address creating snapshots in CI

### ISSUE THREAD

**Issue by pmatos** [racket/racket#3142]
In the create snapshots jobs we are getting: `fatal: could not read Username for 'https://github.com': No such device or address`

https://github.com/racket/racket/runs/633486033?check_suite_focus=true#step:6:6579

It's quite dangerous that after a fatal error the process continues without breaking.

**Comment by samth** [comment]
This probably belongs on racket/distro-build, but not failing when one build fails is intentional.

**Comment by pmatos** [comment]
This looks ok now so closing.
