### ISSUE TITLE
build failed for android

### ISSUE THREAD

**Issue by elephanter** [racket/racket#3149]
i'm build with --enable-racket=auto --enable-places --enable-foreign --enable-ffipoll --enable-libffi 
for arm-linux-androideabi target

android pthread implementation does not support cancellation. so there is no defined varialbe in pthread headers for android.

../../rktio/rktio_file.c:485:25: error: use of undeclared identifier 'PTHREAD_CANCEL_DISABLE'
  pthread_setcanceltype(PTHREAD_CANCEL_DISABLE, &old_type);

maybe I can disable that part of code? or pthread completely?

**Comment by elephanter** [comment]
fix that changing
```
#ifdef RKTIO_USE_PTHREADS
# define RKTIO_USE_PENDING_OPEN
#endif
```
in src/rktio/rktio_private.h  to
```
#ifdef RKTIO_USE_PTHREADS
#ifndef __ANDROID__
# define RKTIO_USE_PENDING_OPEN
#endif
#endif
```

**Comment by pmatos** [comment]
Hi @elephanter 
Thanks for this report. Could you please provide more information on how you are  building for android and which device are you using to compile?

**Comment by elephanter** [comment]
Makefile variables is:
```
export NDK := /home/danil/Android/Sdk/ndk/21.1.6352462
export TOOLCHAIN:=${NDK}/toolchains/llvm/prebuilt/darwin-x86_64
export TARGET:=armv7a-linux-androideabi
export TARGET_S:=arm-linux-androideabi
export API:=21
export AS := ${TOOLCHAIN}/bin/${TARGET_S}-as
export PATH := ${TOOLCHAIN}/bin:$(PATH)

export LIBFFI := dist/libffi
export LIBFFIPATH:=$(shell pwd)/${LIBFFI}
```
and build rule
```
mkdir -p ${RACKETDIR}/src/build && cd ${RACKETDIR}/src/build && \
        AR=${TOOLCHAIN}/bin/${TARGET_S}-ar \
        CC=${TOOLCHAIN}/bin/${TARGET}${API}-clang \
        CXX=${TOOLCHAIN}/bin/$TARGET$API-clang++ \
        LD=${TOOLCHAIN}/bin/${TARGET_S}-ld \
        RANLIB=${TOOLCHAIN}/bin/${TARGET_S}-ranlib \
        STRIP=${TOOLCHAIN}/bin/${TARGET_S}-strip \
        CFLAGS="-fPIE -fPIC -I${LIBFFIPATH}/include" \
        CPPFLAGS="-I${LIBFFIPATH}/include" \
        LIBS="-lffi" \
        LDFLAGS="-pie" \
        LDFLAGS="-L${LIBFFIPATH}/lib" \
        ../configure --host=${TARGET} --enable-racket=auto --enable-places --enable-foreign --enable-ffipoll --enable-libffi && $(MAKE) && $(MAKE) plain-install
```

I'm build libffi v3.3 from github source because included libffi in racket also not build on android and i found that problem part of code changed in libffi repo... so i build it separately.

All code compiled successfully, but I haven't run anything on device yet

**Comment by pmatos** [comment]
> All code compiled successfully, but I haven't run anything on device yet

OK, are you attempting to cross compile here? From a x86_64? Linux?

**Comment by elephanter** [comment]
Oh, I see, I made mistake when copying from makefile
there was 
export TOOLCHAIN:=${NDK}/toolchains/llvm/prebuilt/linux-x86_64

not darwin)

**Comment by pmatos** [comment]
Thanks for double-checking. Closing.
