### ISSUE TITLE
spurious bytecode caching in BC but not CS

### ISSUE THREAD

**Issue by mbutterick** [racket/racket#3158]
This sample simulates a render of a Pollen source `"doc.rkt"` that relies on `"pollen.rkt"`. The `"pollen.rkt"` is changed and the bytecode regenerated for both files.

Under Racket BC, when `"doc.rkt"` is re-evaluated, it shows the wrong (= original) value. 
Under Racket CS, it shows the correct (= updated) value.

At first, I thought the dependency manager was failing to notice that `"doc.rkt"` relies on `"pollen.rkt"` (and thus should be recompiled when `"pollen.rkt"` changes). But the tests using `module-recorded-dependencies` seem to disprove this theory.

Then I thought that the bytecode for `"doc.rkt"` wasn’t being refreshed on the second set of calls to `managed-compile-zo`. But even if I erase the first set of bytecode files, the problem persists.

My only remaining theory is that `managed-compile-zo` has some deeper caching that needs to be overcome. But because the behavior is different in BC vs. CS, I conclude that one of them — BC, probably — is behaving badly.

```racket
#lang at-exp debug racket
(require compiler/cm compiler/depend rackunit)

(display-to-file @string-append{
 #lang racket/base
 (provide id)
 (define id "first")} "pollen.rkt" #:exists 'replace)

(display-to-file @string-append{#lang pollen
 ◊id doc} "doc.rkt" #:exists 'replace)

(managed-compile-zo "pollen.rkt")
(managed-compile-zo "doc.rkt")

;; proves that dependency manager notices that "doc.rkt" relies on "pollen.rkt"
(check-true (and (member (path->complete-path (string->path "pollen.rkt")) (module-recorded-dependencies "doc.rkt")) #true))

(parameterize ([current-namespace (make-base-namespace)])
  (check-equal? (dynamic-require "pollen.rkt" 'id) "first"))

(parameterize ([current-namespace (make-base-namespace)])
  (check-equal? (dynamic-require "doc.rkt" 'doc) "first doc"))

(display-to-file @string-append{
 #lang racket/base
 (provide id)
 (define id "second")} "pollen.rkt" #:exists 'replace)

;; we erase the bytecode!
;; we erase the bytecode!
(for ([bc '("compiled/pollen_rkt.zo" "compiled/doc_rkt.zo")])
     (when (file-exists? bc)
       (delete-file bc)))

(managed-compile-zo "pollen.rkt")
(managed-compile-zo "doc.rkt")

(check-true (and (member (path->complete-path (string->path "pollen.rkt")) (module-recorded-dependencies "doc.rkt")) #true))

(parameterize ([current-namespace (make-base-namespace)])
  (check-equal? (dynamic-require "pollen.rkt" 'id) "second"))

(parameterize ([current-namespace (make-base-namespace)])
  (check-equal? (dynamic-require "doc.rkt" 'doc) "second doc")) ; test fails on Racket BC
```

**Comment by mflatt** [comment]
The difference between BC and CS is that BC is better at cross-module inlining in this case: it inlines "first" into the compiled form of "doc.rkt", while CS generates a call to `id`. If I change `id` to a macro (which effectively forces inlining), then BC and CS behave the same: "first doc" is the result.

I think the issue is that `managed-compile-zo` uses the current namespace. Specifically, the first compilation of "doc.rkt" loads "pollen.rkt" into the current namespace, and the second compilation uses the previously loaded version. If I add `(parameterize ([current-namespace (make-base-namespace)]) ...)` around the first pair of `managed-compile-zo` calls, then the test succeeds on BC and CS, with a macro or with a function.

**Comment by mbutterick** [comment]
> the issue is that managed-compile-zo uses the current namespace

OK — yes, that was absent from my understanding. I have had spooky-caching problems before that were traceable to the current namespace. 

But IIUC neither BC nor CS is doing it wrong. So does this program occupy the realm of undefined behavior, and the CS behavior shouldn’t be relied upon?

**Comment by mflatt** [comment]
Right. Neither BC nor CS compiled against the newer "pollen.rkt" in your example, and running compiled modules with difference dependencies than used at compile time will behave somewhat unpredictably.

**Comment by mbutterick** [comment]
One follow-up Q: IIUC `zo` files are tracked for freshness using timestamps in the `dep` file. But when are these timestamps checked to ensure the `zo` is still valid? The first time the module is loaded into a namespace?
