### ISSUE TITLE
raco test should add support to output to file

### ISSUE THREAD

**Issue by pmatos** [racket/racket#3161]
In #3159 @samth commented regarding the command line:
```
$ raco test ... 2>&1 | tee log
```

that `raco test` could have in-build support to output to file. This is an enhancement request so we don't forget to discuss it.

**Comment by yangh** [comment]
Do we need to extend the scope this feature to all raco sub commands?

**Comment by pmatos** [comment]
Thanks for giving this a go.
I would say this is most relevant to `raco test`, and that would be good to have for a start.

It looks like you are in the right path and I do not see why we would want/need to change `rackunit`. 
Feel free to open a Draft PR with your current changes and we can work out the details together with a better view of all the changes you're proposing.

**Comment by samth** [comment]
I don't think extending the scope to all subcommands is the right thing here. `raco` commands are intended to be entirely separate -- they don't have to treat options the same way at all. So just adding this to `raco test` is the right way to go.

**Comment by pmatos** [comment]
Thanks for confirming that @samth

**Comment by sorawee** [comment]
FWIW: `raco test` and `rackunit` are orthogonal. There are other testing frameworks too, like:

- https://docs.racket-lang.org/overeasy
- https://docs.racket-lang.org/chk/

So modifying `rackunit` would not suffice.

**Comment by yangh** [comment]
@samth @sorawee 
So we still need to parse the --output <file.name> command line option in the raco.rkt, in this way, no need to change any code else where.

Since raco is widely used, we'd better not to introduce to much changes or make any significant behavior changes.

I'll make a PR as soon as I can, after item 1/2/3 is ready.
