### ISSUE TITLE
Logger can send inconsistent messages

### ISSUE THREAD

**Issue by camoy** [racket/racket#3168]
The logger under very specific circumstances can yield the incorrect message format.

```rkt
#lang racket/base

(require racket/logging)

(define-logger hello)
(define (f)
  (log-hello-info "foo")
  (define result (findf (λ (x) #f) null))
  (log-hello-info "bar")
  result)

(define recv (make-log-receiver hello-logger 'info))
(f)
(sync recv)
(sync recv)
```

When running this under 7.7 BC I get:
```
'#(info "hello: foo" #<continuation-mark-set> hello)
'#(info "bar" #<continuation-mark-set> hello)
```

For some reason, the second message is not prefixed with `hello: `. The thing that creeps me out is perturbing the program slightly will cause the bug not to manifest. For example, changing `findf` to `map` will give the correct behavior. Or not returning `result` from `f` will give the correct event.

This example seems to work fine on Racket CS. I'm not sure if this issue is fixed in CS, or if it's still present but just isn't triggered with this particular example.

**Comment by mflatt** [comment]
This is an off-by-one bug in BC in handling the arguments to `log-message`. I'll push a repair soon.

Thanks for the report!
