### ISSUE TITLE
Future tests timeout

### ISSUE THREAD

**Issue by pmatos** [racket/racket#3172]
Future tests were added in https://github.com/racket/racket/commit/2195db72331d4195c6a12c854a35c812b692c653 but are timing out:
https://github.com/racket/racket/runs/659543624#step:23:7

**Comment by samth** [comment]
I think some of them are quite intensive. It's worth looking on DrDr to identify the slow ones.

**Comment by pmatos** [comment]
This has now been fixed and they made into trunk again in https://github.com/racket/racket/commit/8859d6596a6ef6ca78ccb5cc68b684a16be68ccb
