### ISSUE TITLE
Racket 7.7 fails to build on armhf

### ISSUE THREAD

**Issue by nmeum** [racket/racket#3176]
Hi, I am currently working on the [Alpine Linux](https://alpinelinux.org/) racket package. While upgrading it to 7.7 I noticed that the build failed on armhf. The error message is:

```
make[7]: *** No rule to make target 'gmp_arm_gcc.o', needed by 'mzobjects'.  Stop.
```

I haven't investigated this further yet but may this be a parallel build issue? The full build log: [racket-7.7-r0.log](https://github.com/racket/racket/files/4614386/racket-7.7-r0.log)

**Comment by pmatos** [comment]
I am surprised - I ran the compilation just fine on a raspberrypi3 with alpine.
If after the compilation you do:
```
 # grep gmp_arm racket/src/racket/src/Makefile
	vector.o  gmp_arm_gcc.o
gmp_arm_gcc.o: $(srcdir)/gmp/gmp_arm_gcc.s
	$(CC) -o gmp_arm_gcc.o -c $(srcdir)/gmp/gmp_arm_gcc.S
```

dont you see the make rule for `gmp_arm_gcc`?

**Comment by pmatos** [comment]
Ah yes - I can repro. It's due to the use of `--enable-shared`.

**Comment by pmatos** [comment]
I wil fix.

**Comment by pmatos** [comment]
I have a fix - running some further tests before opening PR.

**Comment by pmatos** [comment]
@nmeum this should be fixed now. Feel free to try out https://github.com/racket/racket/commit/8ff7b4cc86dcd0addcead1b36febae82fa9d4b40

**Comment by nmeum** [comment]
Backported the patch to our racket package, worked like a charm. Thanks a lot for the quick fix!
