### ISSUE TITLE
Parameterize doesn't work for generators inside it, should it?

### ISSUE THREAD

**Issue by peey** [racket/racket#3179]
Consider this piece of code

```
(define yyy (make-parameter "sweet"))

(define (gen-parameter-1)
  (parameterize ([yyy "salty"])
    (generator () (let loop () (yield (yyy)) (loop)))
    ))

(define (gen-parameter-2)
  (generator ()
             (parameterize ([yyy "salty"])
               (let loop () (yield (yyy)) (loop)))
    ))

(define (gen-parameter-3)
  (let ([g (gen-parameter-1)])
    (generator ()
               (parameterize ([yyy "salty"])
                 (let loop () (yield (g)) (loop)))
               )))
```

If I try 

```
((gen-parameter-1))
((gen-parameter-2))
((gen-parameter-3))
```

I get 

```
sweet
salty
salty
```

Shouldn't the output of the first generator also be "salty"?

**Comment by samth** [comment]
What's going on here is that the continuation captured when you do `yield` is delimited by the use of `generator`, and so when you invoke it, it doesn't contain the `parameterize` in the first example. In the other two, the invocation captures the `parameterize`, and so you get `salty`.

**Comment by sorawee** [comment]
A simpler example that exhibits the same behavior:

```
#lang racket

(require racket/generator)

(define yyy (make-parameter "sweet"))

(define (gen-parameter-1)
  (parameterize ([yyy "salty"])
    (λ () (yyy))))

((gen-parameter-1))
```

This is totally expected, as Sam explained. To make it clearer, consider rewriting your code to:

```
(define f (gen-parameter-1))
(f)
```

According to the doc:

>  The parameterize form associates a new value with a parameter during the evaluation of body expressions:

It is indeed the case that `yyy` is associated to `"salty"` in the dynamic extent of `parameterize`. But when you invoke `f`, you are no longer in the dynamic extent of `parameterize`.

**Comment by peey** [comment]
Thanks for clarifying. I thought that there was a scoping issue and this may not be expected behavior.
