### ISSUE TITLE
CS: missing support for powerpc32 and arm for *BSD

### ISSUE THREAD

**Issue by juanfra684** [racket/racket#3181]
Racket BC has JIT support for ARMv7 and PowerPC on *BSD but it's missing with CS. I don't have a PowerPC or ARM machine with Linux at hand to test Racket CS but looks like it has support for those architectures for Linux in the file `racket/src/cs/rumble/system.ss`.

What's the status of CS on those architectures? Are the entries in the CS builds system the only missing part?.

**Comment by mflatt** [comment]
Probably entries in the CS build system are the only part, but I haven't tried them.

**Comment by pmatos** [comment]
@juanfra684 At the moment, the only supported/working arch is x86_64. I have attempted to get arm32, ppc32 and i386 to work but there are problems at some point down the line. I am working with @jessealama to bring more ports to CS and possibly fix those which are broken.

To be clear, Racket CS has only been tested on x86_64 but even if you add the pieces to RacketCS to use Chez for other archs it won't work because Chez itself is broken on those other archs.

**Comment by samth** [comment]
There are Windows and Mac 32 bit builds of Racket CS for x86 on download.racket-lang.org, so it does work there.

**Comment by mflatt** [comment]
I agree that 32-bit x86 should work, and I have sometimes built and run that variant (but we don't provide any pre-built 32-bit CS versions, as far as I know).

**Comment by pmatos** [comment]
I have tried running a cs-bootstrap on i386 last week and it didn't work. I don't have the logs here as I am not home. I will get to this later.

Also, the reason I didn't add 32 bits tests to racket Chez last week was due to this.

**Comment by juanfra684** [comment]
Thanks for the info guys. I've updated the OpenBSD package to Racket to 7.7 just a minutes ago, changing to CS only amd64.

**Comment by pmatos** [comment]
For non-threaded intel (32 and 64) we have this:
https://github.com/racket/ChezScheme/runs/677508407?check_suite_focus=true#step:7:233

For threaded i386 we have lots of failures in tests:
https://github.com/racket/ChezScheme/runs/677508396?check_suite_focus=true#step:8:48

More info in action for PR https://github.com/racket/ChezScheme/pull/24

**Comment by mflatt** [comment]
Closing this because support has been added. There are likely to be problems, since I tried only a couple of of BSDs and architectures, but let's take those as new issues.
