### ISSUE TITLE
An error occurred while updating the package checksum.

### ISSUE THREAD

**Issue by sorawee** [racket/racket#3185]
Rosette (https://pkgs.racket-lang.org/package/rosette) currently has this problem:

```
git-checkout: won't extract a file with an up-directory element
  path: #<path:../regular/assertion.rkt>
  context...:
   /home/pkgserver/racket/collects/file/private/check-path.rkt:5:0: check-unpack-path5
   /home/pkgserver/racket/collects/net/git-checkout.rkt:689:5: loop
   [repeats 4 more times]
   /home/pkgserver/racket/collects/net/git-checkout.rkt:157:11
   /home/pkgserver/racket/collects/net/git-checkout.rkt:54:2: retry-loop
   /home/pkgserver/racket/collects/pkg/private/download.rkt:102:2: download!
   /home/pkgserver/racket/collects/pkg/private/download.rkt:94:0: download-repo!24
   /home/pkgserver/racket/collects/pkg/private/stage.rkt:300:11
   /home/pkgserver/racket/collects/pkg/private/stage.rkt:107:0: stage-package/info46
   /home/pkgserver/racket/collects/pkg/private/stage.rkt:694:0: pkg-stage62
   /home/pkgserver/racket/collects/pkg/private/content.rkt:39:0: get-pkg-content20
   /home/pkgserver/racket/collects/racket/contract/private/arrow-val-first.rkt:397:3
   /home/pkgserver/pkg-index/official/update.rkt:123:0: update-from-content
   /home/pkgserver/racket/collects/racket/private/more-scheme.rkt:261:28
   /home/pkgserver/racket/collects/racket/private/list.rkt:264:4: loop
   /home/pkgserver/pkg-index/official/update.rkt:149:0: do-update!
   ...
```

I also noticed that a doc change that I made about 20 days ago doesn't appear at https://docs.racket-lang.org/rosette-guide/index.html.

**Comment by mflatt** [comment]
Using links in a package is generally not a good idea, because they don't work on Windows.

The check for ".." in a link is there to avoid security problems. The check could be refined to see whether the link stays within the repository; I think we skipped that because it seemed difficult to get right, and it did not seem worthwhile given that links should be avoided.

**Comment by sorawee** [comment]
Ah, I see. It's due to links (created from `ln`). I'm perfectly fine with links not working, and I will fix Rosette shortly. Could the error message from the package server be improved somehow, though?

**Comment by mflatt** [comment]
I can at least update the message to say "link" instead of "file".

**Comment by samth** [comment]
I've written that change already, so you might not need to.

**Comment by mflatt** [comment]
I called it `what` instead of `kind`, but otherwise exactly the same. :)
