### ISSUE TITLE
Racket CS prints reals differently from Racket BC

### ISSUE THREAD

**Issue by Bogdanp** [racket/racket#3195]
I noticed this today while debugging some code that uses `current-inexact-milliseconds`.

Racket CS master:

```
$ racket -e '1589922390614.112'
1.589922390614112e+12
```

Racket BC 7.6:

```
$ racketbc -e '1589922390614.112'
1589922390614.112
```

**Comment by mflatt** [comment]
I'll adjust the number printer in Racket's branch of Chez Scheme. I think there will always be some differences — just as there are differences for BC across platforms — but the printers can be much better aligned than currently.
