### ISSUE TITLE
DrRacket behavior oddity

### ISSUE THREAD

**Issue by jasonhemann** [racket/racket#3208]
At least in DrRacket 7.5, on OSX, if you

- Open Package Installer
- Click back over to the DrRacket window
- Open Package Manager

The package manager pops up but is then denied focus so you can't e.g., close out of the package manager.

You can also:

- Open Package Installer
- Click back over to the DrRacket window
- Open Package Installer

And you now have two copies of that same dialog box, and only the second one prevents focus back on the main DrRacket window.

**Comment by jbclements** [comment]
Yes, I can confirm that this happens on Racket CS 7.7.0.4--2020-05-03 as well.
