### ISSUE TITLE
Gracket (CS) fails to start on Ubuntu 18.04 LTS and 20.04 LTS

### ISSUE THREAD

**Issue by dbriemann** [racket/racket#3216]
I Installed the CS variant of Racket from here: https://download.racket-lang.org/

Version 7.7 (same results with snapshot from: https://snapshot.racket-lang.org/)
System: Ubuntu 20.04 LTS 
Arch: x64

Runny _any_ racket application that has a gui results in the following (endless) output:
```
string-append: contract violation
  expected: string?
  given: #f
  context...:
   condition->exn
   do-raise
   dynamic-wind
   go
   invoke
   proc
   .../gtk/queue.rkt:236:0: dispatch-all-ready
   .../gtk/queue.rkt:247:12: loop
   call-in-empty-metacontinuation-frame
   call-with-empty-metacontinuation-frame-for-swap
internal error: terminated in atomic mode!
  context...:
   call-with-empty-metacontinuation-frame-for-swap
exception raised by error escape handler: #<procedure>: arity mismatch;
 the expected number of arguments does not match the given number
  expected: 1
  given: 0; original exception raised: internal error: terminated in atomic mode!
  context...:
   proc
   loop
   dynamic-wind
   exit
   default-uncaught-exception-handler
   loop
   call-in-empty-metacontinuation-frame
exception raised by error escape handler: #<procedure>: arity mismatch;
 the expected number of arguments does not match the given number
  expected: 1
  given: 0; original exception raised: exception raised by error escape handler: #<procedure>: arity mismatch;
 the expected number of arguments does not match the given number
  expected: 1
  given: 0; original exception raised: internal error: terminated in atomic mode!
  context...:
   proc
   loop
   dynamic-wind
   exit
   default-uncaught-exception-handler
   loop
   dynamic-wind
   exit
   default-uncaught-exception-handler
   loop
   call-in-empty-metacontinuation-frame
exception raised by error escape handler: #<procedure>: arity mismatch;
```
See a longer log here: https://pastebin.com/7zDEXUHq (it never ends, I have to kill the process).

(In this case I just started drracket but it seems to be like this as soon as gracket is started)

I reproduced the same behaviour on an Ubuntu 18.04 LTS system on a VM. I then tried another VM with Ubuntu 16.04 LTS because it seems like racket(cs) was built on this system and there it works.

If you need more information please ask!

edit: typo

**Comment by mflatt** [comment]
Thanks for the report!

I haven't yet been able to replicate the error, but based on the stack trace and some guesses, I see a problem that fits these symptoms. The repair will be in the next snapshot (20200502 or later), and maybe that will fix the crash on your machines.

**Comment by dbriemann** [comment]
I tried snapshot 20200602 and yes the problem seems to be fixed. Thanks!
