### ISSUE TITLE
Duplication of "Contributing" section in README.md and .github/CONTRIBUTING.md

### ISSUE THREAD

**Issue by kryptine** [racket/racket#3219]
Not only that, these two files also contradict each other.
[README.md](README.md) states: 

> By making a contribution, you are agreeing that your contribution is licensed under the Apache 2.0 and MIT licenses.

[.github/CONTRIBUTING.md](.github/CONTRIBUTING.md) states:

> By making a contribution, you are agreeing that your contribution is licensed under the LGPLv3, Apache 2.0, and MIT licenses.

[My pull request](https://github.com/racket/racket/pull/3177) fixes this.

**Comment by sorawee** [comment]
The PR is merged. Closing.
