### ISSUE TITLE
Not working namespace-attach-module example

### ISSUE THREAD

**Issue by corpix** [racket/racket#3224]
There is an example in the `namespace-attach-module` docs available [here](https://docs.racket-lang.org/reference/Namespaces.html?q=namespace-attach-modul%3Be#%28def._%28%28quote._~23~25kernel%29._namespace-attach-module%29%29).

It behaves wrong, here is what I mean (commented version of the code from the example):

> $ racket --version
> Welcome to Racket v7.7.

```scheme
(module food racket/base
  (provide apple)
  (define apple (list "pie")))
(namespace-require ''food)
(define ns (current-namespace))
(parameterize ([current-namespace (make-base-namespace)])
  (namespace-require ''food))
;;;; example says it should be failed at this point, but it does not

(parameterize ([current-namespace (make-base-namespace)])
  (namespace-attach-module ns ''food)
  (namespace-require ''food)
  (eq? (eval 'apple) apple))
;;;;;;;;;;;;;;;;;;;; ^- it fails at this point with error: apple: unbound identifier

(parameterize ([current-namespace (make-base-namespace)])
  (namespace-attach-module-declaration ns ''food)
  (namespace-require ''food)
  (eq? (eval 'apple) apple))
```

**Comment by gfbee** [comment]
Are you running it as a program or in the repl (which is what the `>` are indicating in the example). This example is sensitive to that distinction.
Unfortunately the reference for namespaces doesn't appear to mention the corresponding part of the Guide. In the Guide, there's a marginal note at the top of [15.1 eval](https://docs.racket-lang.org/guide/eval.html) about the example there only working in the repl, and that also applies to many of the other namespace examples.

**Comment by corpix** [comment]
I am running this as file, to be more precise - as part of the development process in Emacs using `racket-mode`, evaluating whole buffer.

Ah, namespace should be specified explicitly to eval. I keep forgetting about this every time.
Thank you for your answer @gfbee!

So... code from example that uses eval should be transformed into something like this to work in my case?

```racket
(module food racket/base
  (provide apple)
  (define apple (list "pie")))

(define ns (current-namespace))
(define new-ns (make-base-namespace))

(namespace-require ''food ns)

(namespace-attach-module ns ''food new-ns)
(namespace-require ''food new-ns)
(eval 'apple new-ns)
```

I believe I am missing something again, because I see an error:

```
require: unknown module
  module name: #<resolved-module-path:'food>
```

**Comment by gfbee** [comment]
Someone familiar with emacs racket-mode evaluating a buffer should confirm/help here, but it's presumably running the buffer as a module in the racket language, not through a repl.
Study the module examples (syntactically, the ones that start with `#lang` and don't have `>` prompts), in https://docs.racket-lang.org/guide/mk-namespace.html#%28part._.Sharing_.Data_and_.Code_.Across_.Namespaces%29 and https://docs.racket-lang.org/guide/eval.html#%28part._.Namespaces_and_.Modules%29 .

I happened to be reviewing all this yesterday, and know it's easy to miss the significance of the examples being in a module vs at the repl, and hard to know what to look for if you don't know that. I don't really have time to discuss it further, at least for a week or so, but there are many friendly racketeers who can take you further, on the racket google group, reddit board, or slack.

**Comment by corpix** [comment]
Ok, thank you very much!

**Comment by corpix** [comment]
> ```racket
> (module food racket/base
>   (provide apple)
>   (define apple (list "pie")))
> 
> (define ns (current-namespace))
> (define new-ns (make-base-namespace))
> 
> (namespace-require ''food ns)
> 
> (namespace-attach-module ns ''food new-ns)
> (namespace-require ''food new-ns)
> (eval 'apple new-ns)
> ```
> 
> ```
> require: unknown module
>   module name: #<resolved-module-path:'food>
> ```

For anybody who will find this issue in the future, here is modified example which works:

```racket
#lang racket
(require syntax/location)

(module food racket/base
  (provide apple)
  (define apple (list "pie")))

(define ns (current-namespace))
(define new-ns (make-base-namespace))

(namespace-require (quote-module-path food) ns)

(namespace-attach-module ns (quote-module-path food) new-ns)
(namespace-require (quote-module-path food) new-ns)
(eval 'apple new-ns)
```

```
'("pie")
```

And link to racket mailing list which could shade more light on the reason https://lists.racket-lang.org/users/archive/2013-May/058029.html

All credits to people in racket slack :)
