### ISSUE TITLE
cmdline_to_argv invalid parsing

### ISSUE THREAD

**Issue by nu8** [racket/racket#3227]
For Windows, I see that Racket calls a function `cmdline_to_argv`:

<https://github.com/racket/racket/blob/aa0cfd055704ebb1a78f9eda1239ad8865c6349b/racket/src/racket/main.c#L339>

which in turn calls `GetCommandLine` to pull the command string:

<https://github.com/racket/racket/blob/aa0cfd055704ebb1a78f9eda1239ad8865c6349b/racket/src/start/parse_cmdl.inc#L93>

and then `parse_command_line` to parse the string:

<https://github.com/racket/racket/blob/aa0cfd055704ebb1a78f9eda1239ad8865c6349b/racket/src/start/parse_cmdl.inc#L101>

finally `parse_command_line` does some voodoo to parse the string:

<https://github.com/racket/racket/blob/aa0cfd055704ebb1a78f9eda1239ad8865c6349b/racket/src/start/parse_cmdl.inc#L22>

It seems the reason for this is that the Windows entry point is `WinMain`:

<https://github.com/racket/racket/blob/aa0cfd055704ebb1a78f9eda1239ad8865c6349b/racket/src/racket/main.c#L330>

and Microsoft tells people to use `GetCommandLine` for this case:

<https://docs.microsoft.com/windows/win32/api/winbase/nf-winbase-winmain>

but that is not the only option. `__argv` is also available inside `WinMain`:

<https://docs.microsoft.com/cpp/c-runtime-library/argc-argv-wargv>

That is what Python is using:

<https://github.com/python/cpython/blob/4649202e/PC/WinMain.c>

The reason I am suggesting this, is because Racket seems to have an issue with
the current command line processing. Take this file:

~~~rkt
#lang racket
(define a
   (current-command-line-arguments)
)
(define s
   (vector-ref a 0)
)
(displayln s)
~~~

Result:

~~~
C:\> racket a.rkt "a ""b"" c"
a b c
~~~

and this Python file:

~~~py
import sys
s = sys.argv[1]
print(s)
~~~

Result:

~~~
C:\> python a.py "a ""b"" c"
a "b" c
~~~

Since Visual C++ 2008, Windows uses the Quote Quote syntax to escape a double
quote.

<http://daviddeley.com/autohotkey/parameters/parameters.htm#WINCRULES>

Racket parser seems to be failing in this case. As a workaround, you can use the
old style quoting with Racket:

~~~
C:\> racket a.rkt "a "\^"b\^"" c"
a "b" c
~~~

To utilize the new parsing, `GetCommandLine` would need to be removed, and
replaced with `__argv`, then linked with `msvcr90.dll` or better.

**Comment by mflatt** [comment]
Thanks for the report!

Unfortunately, it's not as simple as using `__arg` and linking to `msvcr90.dll`. One issue is that our distribution executables are cross-compiled using MinGW. (When building with MSVC, as I normally do for my own work, Racket does use the MSVC library's command-line parsing.) Another issue is that we don't want to be in the business of distributing extra DLLs needed on startup — not even redistributables like `mscvr90.dll`.

I worry a little about changing Racket's parser and its effect on backward compatibility, but the current difference between the Racket builds using MSVC and MinGW is certainly bad, and the MSVC library's de facto standard certainly seems like the right choice to unify them. So, probably the right repair here is to adjust the parser.

David Deley's report on parsing is very helpful. I hadn't seen it before, but the last time I looked for a specification of Windows command-line might have been before 2009. I recall working from Microsoft's description, and I'm not exactly shocked that it turns out to have been incomplete.

**Comment by nu8** [comment]
Um, MinGW defines both `__argv`and `__wargv` in `stdlib.h`...

**Comment by mflatt** [comment]
But they don't actually provide the command-line arguments, at least in my tests.

**Comment by nu8** [comment]
Works fine...

~~~
$ cat main.c
#include <stdio.h>
int main(int __argc, char **__argv) {
   char *s = __argv[1];
   puts(s);
}

$ cc -o main main.c
$ ./main.exe Sunday
Sunday

$ cat winmain.c
#include <stdio.h>
#include <windows.h>
int WINAPI WinMain (
   HINSTANCE hInstance,
   HINSTANCE hPrevInstance,
   LPSTR lpCmdLine,
   int nShowCmd
) {
   char *s = __argv[1];
   puts(s);
}

$ cc -o winmain winmain.c
$ ./winmain.exe Sunday
Sunday
~~~

**Comment by mflatt** [comment]
Looks like I tried only `__wargv`. Although `__argv` does seem to work, `__argv` doesn't – unless I'm doing something wrong. Does `__wargv` (or something similar) work for you?

**Comment by mflatt** [comment]
Also, `__argv` seems to be the pre-2008 behavior. Probably it's based on calling the `mvcrt.dll` parser.

**Comment by nu8** [comment]
`__wargv` works. Also you have to link with proper Runtime, if you want the new
behavior.

~~~
$ cat a.c
#include <stdio.h>
#include <windows.h>
int WINAPI wWinMain (
   HINSTANCE hInstance,
   HINSTANCE hPrevInstance,
   LPWSTR lpCmdLine,
   int nShowCmd
) {
   wchar_t *s = __wargv[1];
   // example 1
   wprintf(L"%s\n", s);
   // example 2
   printf("%ls\n", s);
   // example 3
   printf("%ws\n", s);
}

$ cc a.c -lmsvcr100 -municode
~~~

Result:

~~~
C:\> a.exe "a ""b"" c"
a "b" c
a "b" c
a "b" c
~~~

**Comment by mflatt** [comment]
Ah, ok! In retrospect, it makes sense that something like `-municode` would be needed for `__wargv` to be initialized.

I see that using something like `-lmsvcr100` also really is needed to get the right parsing, but that leaves the problem of having to distribute `msvcr100.dll`, which does not work with the distribution process or creating for stand-alone executables via `raco exe`. Is there some way that I'm missing to avoid the extra DLL?

**Comment by nu8** [comment]
You can either include the DLL like Python does, or you can direct users to this
page:

https://support.microsoft.com/help/2977003

but yes, the DLL is required. Regarding stand alone, thats not really a thing
with regard to the Microsoft C Runtime. Even when Go and Rust output fully
"static" programs, they still rely on that DLL. But the DLL can be anywhere on
the PATH, so its never really been an issue.

In the past I have discouraged use of the newer C Runtime as is complicates
distribution, but in this case I think its warranted.

**Comment by mflatt** [comment]
I agree that some C runtime library is needed, but `msvcrt.dll` is always available, unlike the other variants. From long experience, I'm convinced that trying to use a different C runtime on Windows is not the way to go. It still looks to me like fixing the current parser is the best choice (along with some clean-ups).

FWIW, I found this page useful as another reference on the topic of parsing command-line arguments: http://www.windowsinspired.com/how-a-windows-programs-splits-its-command-line-into-individual-arguments/

**Comment by nu8** [comment]
Your idea might be the best, because even with newer parsing, one issue remains.  With both Microsoft parsers, if you pass this:

~~~
sun.exe "C:\Mon\Tue\"
~~~

this is received:

~~~
C:\Mon\Tue"
~~~

both parsers incorrectly interpret the quote as literal. So to workaround Ive had to do stuff like this:

~~~php
function f_escape_sh($s_in) {
   $s_out = '';
   $a_in = str_split($s_in);
   foreach ($a_in as $s_chr) {
      if ($s_chr == ' ') {
         $s_out .= '" "';
      } else if ($s_chr == '"') {
         $s_out .= '\^"';
      } else {
         $s_out .= '^' . $s_chr;
      }
   }
   return $s_out;
}
~~~

**Comment by mflatt** [comment]
Commit 774bfd9139c26147b2276f4283ed8c1f60e351fa is meant to address this issue. (Further comedy of errors: I mistyped the issue number in the commit message.)

The problem with a trailing `\"` is definitely a pain, but the intent of the repair is to match MSVC's parsing rather than improve it.

**Comment by mflatt** [comment]
As far as I can tell, parsing now works consistently in recent snapshots that are built at Northwestern (which, like the release builds, are cross-compiled via MinGW): https://plt.eecs.northwestern.edu/snapshots/

Thanks again for the report and your help.
