### ISSUE TITLE
[CS] result of struct-type-make-predicate claims to be constructor

### ISSUE THREAD

**Issue by LiberalArtist** [racket/racket#3239]
On Racket CS, the result of `struct-type-make-predicate` claims to be a constructor rather than a predicate:
```racket
#lang racket
(struct posn (x y)
  #:transparent)
(define pred (struct-type-make-predicate struct:posn))
(struct-predicate-procedure? pred) ; -> #f, should be #t
(struct-constructor-procedure? pred) ; -> #t, should be #f
```
The problem seems to be here: https://github.com/racket/racket/blob/05dfd85853a12c90cb7ff8af41687ad8c660a466/racket/src/cs/rumble/struct.ss#L939-L949

**Comment by samth** [comment]
@capfredf might be the right person to fix this.
