### ISSUE TITLE
bulk bindings error

### ISSUE THREAD

**Issue by michaelballantyne** [racket/racket#3241]
The attached files in ([minimal-example.zip](https://github.com/racket/racket/files/4742613/minimal-example.zip)) produce the following error when `c.rkt` is run in DrRacket with the options for debugging and populating compiled directories on:

```
namespace mismatch: bulk bindings not found in registry for module: #<resolved-module-path:"/Users/michaelballantyne/leifexample/minimal-example/subdir/subdir/a.rkt">
```

Note that the correct path to `a.rkt` is `/Users/michaelballantyne/leifexample/minimal-example/subdir/a.rkt` (one less `subdir`).

The problem seems to have been introduced after version 7.7.02.

It seems to be triggered by re-expansion of `b.rkt` due to errortrace annotation plus serialization to a `.zo` file. The operations in `test.rktl` reproduce the problem without using DrRacket or errortrace.

`b.rkt` calls a macro defined in `subdir/a.rkt` that introduces a syntax literal in the `b.rkt` module. When the `b.rkt` module is re-expanded, its module scope is added to the syntax literal. Then `b.rkt` is compiled to a zo file. Finally, expansion of `c.rkt` deserializes `b.rkt` and inspects the bindings of the syntax literal. Because `b.rkt` requires `subdir/a.rkt`, the bindings associated with its module scope on the syntax literal include bulk bindings from `subdir/a.rkt`. It seems that the expander attempts to look up those bulk bindings using the wrong module path index, looking relative to `subdir/a.rkt` rather than relative to `b.rkt`. This probably happens because the literal originated in `subdir/a.rkt`.

The example was minimized from a problem @LeifAndersen ran into with her `interactive-syntax` package.

**Comment by michaelballantyne** [comment]
@mflatt

**Comment by mflatt** [comment]
Thanks for the small example!

I'll have to try again to fix the compiler non-determinism that the broken commit was intended to fix.
