### ISSUE TITLE
Place creation leaks resources

### ISSUE THREAD

**Issue by camoy** [racket/racket#3243]
In `worker.rkt:`
```rkt
#lang racket
(provide place-main) 
(define (place-main pch) (sleep 1))
```

And in `main.rkt`:
```rkt
#lang racket
(let go ()
  (define pl (dynamic-place "worker.rkt" 'place-main))
  (place-wait pl)
  (go))
```

Running the following:
```
$ racket main.rkt &
[1] 1234567
$ lsof -p 1234567
...
```

If you keep running `lsof`, you'll notice a bunch of FIFO pipes that are never closed that continue to be opened. Is there some sort of explicit cleanup necessary for `dynamic-place`, or is this a bug? The documentation doesn't seem to indicate any cleanup needed. (Btw, found this because I have a long-running script that makes many calls to `parallel-compile-files` and eventually this exhausted the number of open files.)

**Comment by mflatt** [comment]
Yes, it looks like a problem at the rktio level, where a pipe used for polling is never cleaned up. I'll investigate more to make sure, but probably will have a repair soon.

Unfortunately, if that's right, then I don't see a workaround for existing Racket builds.
