### ISSUE TITLE
datum->syntax stopped using datum-intern-literal in Racket 7.0

### ISSUE THREAD

**Issue by LiberalArtist** [racket/racket#3245]
The [documentation](https://docs.racket-lang.org/reference/stxops.html#(def._((quote._~23~25kernel)._datum-~3esyntax))) for `datum->syntax` says that:
> For any kind of value other than a pair, vector, box, immutable hash table, immutable prefab structure, or syntax object, conversion means wrapping the value with lexical information, source-location information, and properties after the value is interned via `datum-intern-literal`.

This behavior seems to have changed in Racket 7.0:

```
Sapientia:Downloads philip$ ./racket-6.12/bin/racket 
Welcome to Racket v6.12.
> (immutable? (syntax-e (datum->syntax #f (string #\a))))
#t
> ^D
Sapientia:Downloads philip$ ./racket-7.0/bin/racket 
Welcome to Racket v7.0.
> (immutable? (syntax-e (datum->syntax #f (string #\a))))
#f
```

(This had come up a while ago [on the mailing list](https://groups.google.com/d/msg/racket-users/vVRNtKQZppA/vFj3y12JBQAJ), but I just confirmed that Racket used to do what the docs say.)

**Comment by mflatt** [comment]
Thanks for resuming this issue!

I think it's probably best to restore the use of `datum->syntax`. When I try that, nothing in the distribution build goes wrong, so I'll push the change and we'll see whether it triggers and problems for packages.

**Comment by sorawee** [comment]
This is fixed, I believe. Closing.
