### ISSUE TITLE
racket/base provides the unsafe function expand-for-clause

### ISSUE THREAD

**Issue by LiberalArtist** [racket/racket#3246]
`expand-for-clause` is supposed to be provided only by `syntax/unsafe/for-transform`, but `racket/base` also `provide`s it `for-syntax`, so this program, unfortunately, compiles:
```racket
(module issue racket/base
  (begin-for-syntax
    expand-for-clause))
```
It looks like this happened accidentally in https://github.com/racket/racket/commit/a84cf6b61db5b4beb06db59747c6804049e1120c, when `expand-for-clause` was first exported from `racket/private/for`, as there was no corresponding change to: https://github.com/racket/racket/blob/99acbdaf8ca7ce6362eaf60029af808151830ace/racket/collects/racket/private/pre-base.rkt#L229-L236

**Comment by stchang** [comment]
Thanks for catching this. I'll just add `expand-for-clause` to the `all-from-except` list. Is that the right thing to do?

**Comment by LiberalArtist** [comment]
I hope so. There could be complications if any packages rely on `expand-for-clause` being exported from `racket/base`, but I hope they don't, and, even if they do, safety seems like an important consideration in favor of removing it anyway.
