### ISSUE TITLE
Definition context API change proposal

### ISSUE THREAD

**Issue by michaelballantyne** [racket/racket#3251]
Starting with <https://github.com/racket/racket/issues/3198>, I've been thinking about the first-class definition context API. Several flaws make most all macros using the API unhygienic in certain situations. To fix the API, I propose:

* Each first-class definiton context should come with an associated outside-edge scope.
* The expander should track sets of use-site scopes to remove for each first-class definition context, rather that in the surrounding expand context.
* We should replace `internal-definition-context-introduce` with operations that manipulate outside-edge and use-site scopes along with inside-edge scopes.

### Outside-edge scopes

See <https://github.com/racket/racket/issues/3198>.

I prefer to integrate the outside-edge scopes into definition context operations rather than create separate operations so that macro authors don't need to know about and apply separate operations for each kind of scope. Instead, one operation should do all the work needed to add syntax to the definition context's conceptual scope.

### Parent inside-edge scopes

`local-expand` and other operations add the inside-edge scope of the immediate definition context, but not parent definition contexts. Currently, macros that use chains of definition contexts sometimes accumulate a list of all the definition contexts and either use `internal-definition-context-introduce` or pass the whole list to `local-expand` to ensure that the parent inside-edge scopes are added.

With the addition of an outside-edge scope, macros will need to apply the outside-edge scope from each definiton context before syntax expands. If the same operation applies the inside-edge scope, macros will not need to perform the additional work to accumulating definition contexts to ensure that parent inside-edge scopes have been applied.

### Use-site scopes

The current strategy of tracking use-site scopes to remove in the expand context and resetting at expression contexts doesn't quite work. Consider this example:

```
#lang racket

(require racket/block)

(define x 'good)

(let ()
  (define-syntax-rule (m1 arg)
    ; I use an explicit `#%expression` because the current 
    ; implementation of block does not check it is in an
    ; expression context.
    (#%expression
     (block
      (define arg 'bad)
      x)))
  (define res (m1 x))
  res) ; => evaluates to 'bad
```

The definition right-hand-side where `(m1 x)` expands is already in an expression context, with a fresh, empty set of use-site scopes. The use-site scope of the expansion is recorded in the set. Expansion in `block`'s first-class definition contexts uses the set from the expand context, so when `block` binds or uses `syntax-local-identifier-as-binding`, the use-site scope is removed.

I expect it to work better to track use-site scopes individually for each first-class definition context. In the example above, the use-site scope from `m1` would be in the expand-context's set, but not the set managed by the first-class definition context. Thus it would not be removed at binding or `syntax-local-identifier-as-binding`. This solution also makes expansion easier to understand because hygiene behavior depends less on the context type. 

Tracking use-site scopes for each definition context also improves use-site hygiene behavior for definition contexts with internal scoping structure, like `define*` in `compatibility/package`. Imagine a `let-def*-ctx` that supports `define*`. In this example:

```
(define x 'old)
(define x 'old)
(let-def*-ctx ()
  (define-syntax-rule (m arg1 arg2)
    (begin
      (define* arg1 'new)
      (define arg2 'new)
      (list x y)))
  (m x y))
```

I think the `x` reference should have the value `'old` but `y` should have value `'new`. `(define y 'new)` binds in the whole definition context, so should be visible at the macro definition, whereas `(define* x 'new)` binds in a new, nested scope and thus should not be visible at the definition-site.

By using a new child first-class definition context for each `define*` scope along with my proposed change, this use-site hygiene behavior works. I don't know how to get this right with the current API.

### New operations

(I would appreciate suggestions on better names for these operations)

```
(add-to-definition-context stx intdef-ctx) -> syntax?
```

Adds the defintion context's inside- and outside-edge scopes to `stx`.

```
(splice-from-definition-context stx intdef-ctx) -> syntax?
```

Removes the definition context's inside- and outside-edge scopes. Also removes any use-site scopes created by expansions in the definition context. Removing these use-site scopes ensures that bindings properly  splice out of the definition context, such as the definition of `y` in the example above.

### Changed operations

```
(syntax-local-identifier-as-binding id-stx [intdef-ctx]) -> identifier?
```

When the new optional `intdef-ctx` argument is given, use-site scopes from expansion within the first-class definition context are removed, rather than use-site scopes from expansion in the surrounding expand context.

```
(syntax-local-bind-syntaxes
  id-list	 	 	 	 
  expr	 	 	 	 
  intdef-ctx	 	 	 	 
  [extra-intdef-ctxs])
  -> (listof identifier?)
```

This change is more about convenience. Internally, `syntax-local-bind-syntaxes` must add the inside-edge scope and remove use-site scopes for the definition context. Rather than requiring programmers to perform the same operations themselves using `internal-definition-context-introduce` and `syntax-local-identifier-as-binding`, I propose that `syntax-local-bind-syntaxes` return the identifiers with changed scopes.

### Behaviors that could be deprecated

All cases I've seen should use either `add-to-defintion-context` or `splice-from-definition-context` rather than `internal-definition-context-introduce`. I propose we add documentation to `internal-definition-context-introduce` to this effect

The `add-scope?` argument to `syntax-local-make-definition-context` only seems to have been useful for an old implementation of `splicing-syntax-parameterize`. I propose we add documentation indicating this option is only for backwards compatibility.

Using `add-to-definition-context` to add outside-edge scopes should ensure inside-edge scopes are also applied as needed. As such, I don't think there are situations where the `extra-intdef-ctxs` argument from `syntax-local-bind-syntaxes` is useful, or where passing multiple definition contexts to `local-expand` or similar operations is useful. It would be nice if the documentation guided users in the right direction here, but I'm not sure what the right thing to say is.

### Use-site hygiene for splicing forms

The changes above aren't quite enough to get use-site scope hygiene right for macros like `splicing-let`. This example would still evaluate to `'bad`:

```
#lang racket

(require racket/splicing)

(define x 'good)

(define-syntax-rule (m arg)
  (splicing-let ([arg 'bad])
    x))

(m x) ; => bad
```

Intuitively, the problem is that the macro system thinks that it is meant to infer part of the scoping structure of the `splicing-let` macro from its expansion to `define`. Because the bindings expand to `define`, we must intend them to splice out.

To solve this problem we could make one further change, but it's deeper than those discussed above. Binding in a first-class definition context, expanding a `define`, or using `syntax-local-identifier-as-binding` could annotate the use-site scopes that are not removed by that operation as "resolved" use-site scopes. The same operations would not remove use-site scopes already marked as resolved. Thus, when `splicing-let` uses `syntax-local-identifier-as-binding`, it would lock-in the use-site scope due to `m`. When the definitions that `splicing-let` expands to expand, the scope would not be removed.

### 3D syntax

The implementation of splicing forms currently relies on `make-syntax-delta-introducer` to pass along definition context scopes to a trampolining macro. To use the new definition context operations instead, the implementation would need to use 3D syntax to pass along the definition context object itself. I think this is okay, but others may look less kindly on 3D syntax.

### Definition context uses that don't correspond to new scopes

Some previous uses of definiton contexts, such as an earlier implementation of `splicing-syntax-parameterize`, used definition contexts to extend the expander environment but did not intend to create a new scope. The `add-scope?` argument to `syntax-local-make-definition-context` supported this situation. This behavior was only useful in combination with `syntax-local-get-shadower`; otherwise there is no way to access the bindings due to their inside-edge scope.

Tracking use-site scopes on a per-definition-context basis would be a problem for this kind of use of definition contexts. I don't think any macros still use definition contexts in this way, so that should be okay.

## Backwards compatibility

All definition context macros should eventually be updated to use the new operations for proper hygiene. Until they are updated, most uses would still work as they currently do. There are a couple of exceptions described below. Updating macros to improve their hygiene behavior could itself break backwards compatiblility with unhygienic uses, of course.

Some code might rely on `syntax-local-bind-syntaxes` returning void, in the contract of a derived operation, for example.

### Use-site scope misbehavior

Uses of macros that do not adjust their uses of `syntax-local-identifier-as-binding` to take the definition context will fail to remove use-site scopes in some situations. However, the `frame-id` optimization keeps these situations to a minimum.

Here's an example use of `block` that would break until `block` is updated:

```
(block
 (define-syntax-rule (my-define x v) (define x v))
 (my-define x 5)
 x)
```

### Splicing 

Macros that expand in a first-class definition context and then splice names out of the context will fail to remove use-site scopes from the spliced identifiers unless they update to use `splice-from-definition-context`. I'm not aware of any existing macros this would affect; forms such as `splicing-let` use trampolining rather than local expansion in a definition context.

## Related issues

As described in <https://github.com/racket/racket/pull/2237>, `local-expand` with context `'expression` currently does not apply use-site scopes; that also needs to be fixed for fully-correct hygiene behavior. However, the fixes are mostly independent.

**Comment by mflatt** [comment]
This all sounds plausible to me. It looks like you've thought it through enough and looked at existing modules enough that the next step is to see what happens with an implementation (plus pkg-build). It would make sense to try the #2237 change at the same time. Are you working on the implementation or planning to?

For names, how about `internal-definition-context-add-to` instead of `add-to-definition-context`? That follows the existing naming convention better, and I think the direction of what being added to what fits better with the description. Similarly, `internal-definition-context-from-from`?

**Comment by michaelballantyne** [comment]
Today I discovered two additional wrinkles:

### With which definition context should `local-expand` record use-site scopes?

At some point in the last few years, the API of `local-expand` was generalized such that the `intdef-ctx` argument can be a list of definition contexts rather than a single definition context. Which, if any, of these definition contexts should `local-expand` record the use-site scope with? The other changes I propose should eliminate the circumstances when it is useful to pass a list of contexts, so the question is mostly about backwards compatibility.

Recording with the expand context rather than a first-class definition context when a list is given seems the most likely to preserve backwards compatibility. I think this behavior would make it especially important to document that passing more than one definition context is only supported for backwards compatibility and has this strange behavior.

`local-apply-transformer` creates an additional challenge because it expects to always receive a list of definition contexts rather than an individual definition context, so it has the same problem as `local-expand`, but worse. We could widen the API to also work with a single internal definition context so that it works similarly to `local-expand`.

### `local-apply-transformer` can no longer be implemented atop `local-expand`

With the use-site scope changes, `local-apply-transformer` can no longer be implemented atop `local-expand`. The current implementation relies a new definition context to bind the transformer. With the use-site scope changes, this definition context would record use-site scopes created during expansion, whereas they should be recorded by the definiton context given as argument.

Thus, we'd need to implement `local-apply-transformer` or a similar operation as a primitive in the expander. I propose that we implement a more general operation that works with multiple arguments and return values that may or may not be syntax:

```
(apply-as-transformer f ctx intdef-ctx arg ...) -> any? ...
```

This operation works much like `local-apply-transformer`. Arguments and returns that are syntax have their scopes manipulated in the same way as `local-apply-transformer`; others are not modified. `local-apply-transformer` would be re-implemented as a simple wrapper around this more general operation.

**Comment by mfelleisen** [comment]
> internal-definition-context-from-from?


I can’t help it.  Are you sure you didn’t forget a `from` :-)

**Comment by mflatt** [comment]
Maybe better to change the first `from` to `remove`. :)

**Comment by michaelballantyne** [comment]
> Are you working on the implementation or planning to?

Planning to soon. Wanted to make sure it looks plausible first.

**Comment by michaelballantyne** [comment]
@mflatt Any feeling on the resolved use-site scope bit (in "Use-site hygiene for splicing forms")? I can't decide if the extra complication is worthwhile.

**Comment by mflatt** [comment]
No, I don't have any better thoughts, and it does seem like a significant complication. I also worry about having to use 3-D syntax. Maybe splicing forms should work some entirely different way, but no doubt you've also considered that.

**Comment by michaelballantyne** [comment]
> For names, how about internal-definition-context-add-to instead of add-to-definition-context?

I find those a bit awkward. How about either:

* `add-to-definition-context-scope` and `splice-from-definition-context-scope`
* `internal-definition-context-add-scopes` and `internal-definition-context-remove-scopes`

I prefer the first pair because they imply that something is being done to the syntax rather than the definition context.

**Comment by mflatt** [comment]
The name `add-to-definition-context-scope` still reads to me as something that changes a scope. For that reason, and because the second pair follows conventions better, I prefer your second pair of options.

**Comment by michaelballantyne** [comment]
Completed with changes discussed in https://github.com/racket/racket/pull/3927 as https://github.com/racket/racket/commit/816c26482c414ed7a244bc25d0ba9749a6290e0b
