### ISSUE TITLE
read-compiled-linklet: version mismatch

### ISSUE THREAD

**Issue by abbycin** [racket/racket#3253]
![image](https://user-images.githubusercontent.com/6814167/84908975-b8a55b80-b0e7-11ea-8979-1a901720ad35.png)

binary `x` in the picture was compiled by raco 7.7 in another machine.  

how can I fix this issue?

**Comment by mflatt** [comment]
What command(s) did you use to create `x`?

**Comment by abbycin** [comment]
> What command(s) did you use to create `x`?

```
raco exe --gui x.rkt
```

**Comment by mflatt** [comment]
Does using `raco dist` to package the output of `raco exe` make any difference? I don't think it will, but I may have forgotten something for this case.

Does `x.rkt` use `eval` or `dynamic-require`? I would expect a different error in that case, but I may again be forgetting something.

Do you have any environment variables set? Again, probably not the issue, but checking in case.

**Comment by abbycin** [comment]
> Does using `raco dist` to package the output of `raco exe` make any difference? I don't think it will, but I may have forgotten something for this case.
> 
> Does `x.rkt` use `eval` or `dynamic-require`? I would expect a different error in that case, but I may again be forgetting something.
> 
> Do you have any `PLT...` environment variables set? Again, probably not the issue, but checking in case.

1. I don't even know how to use `raco dist` ...  
2. no `dynamic-require` used  
3. no `PLT...` environment present  

here is the code, in case you need it

```racket
#lang racket

(require plot racket/gui racket/draw)

(define epsilon 0.02)

(define (heart [n 233])
  (define (range r f)
    (if (< (- n f) epsilon)
        r
        (range (cons f r) (+ f epsilon))))
  (define ps (range '() (- n)))
  (define xs
    (λ (t) (* 16 (expt (sin t) 3))))
  (define ys
    (λ (t) (- (* 13 (cos t)) (* 5 (cos (* 2 t))) (* 2 (cos (* 3 t))) (cos (* 4 t)))))
  (define (points r fp ns)
    (map (λ (t)
           (append r (fp t)))
         ns))
  (lines-interval
         (map vector
              (points '() xs ps)
              (points '() ys ps))
         '(#(0 1))
         #:color 'red
         #:line1-color 'red))

(define f (new frame% [label "+1s"]
               [width 800]
               [height 800]))
(define c (new canvas% [parent f]
               [vert-margin 10]
               [horiz-margin 10]))

(send f show #t)

(define (loop dx)
  (plot/dc (heart dx)
           (send c get-dc)
           80 80
           (- (send f get-width) 200)
           (- (send f get-height) 200)
           #:title "moha"
           )
  (sleep/yield .2)
  (if (< dx epsilon)
      (display "it's over")
      (loop (- dx epsilon))))

(loop 3.5)
```

**Comment by mflatt** [comment]
Thanks for the code! You really do need to use `raco dist` to convert the executable to one that can be moved to another machine. Or use "Create Executable" in DrRacket, which does the same thing as combining `raco exe` and `raco dist`.

**Comment by abbycin** [comment]
> Thanks for the code! You really do need to use `raco dist` to convert the executable to one that can be moved to another machine. Or use "Create Executable" in DrRacket, which does the same thing as combining `raco exe` and `raco dist`.

thank you, it works. it seems need a racket3m-7.7 to execute the standalone executable itself (`/path/to/racket3m-7.7 /path/to/x ...`).
