### ISSUE TITLE
[Docs] Link to source

### ISSUE THREAD

**Issue by konsumlamm** [racket/racket#3256]
It would be very convenient to be able to have something like a `Goto source` button in the docs, to be able to quickly look at the implementation of a function or macro. Is something like that possible with the current documentation system?

**Comment by sorawee** [comment]
I think this is a duplicate of https://github.com/racket/scribble/issues/238.

**Comment by konsumlamm** [comment]
It is indeed, thanks! Closing this in favour of that issue
