### ISSUE TITLE
Please add my file to wiki

### ISSUE THREAD

**Issue by nwg** [racket/racket#3264]
Github does not allow file uploads or pull requests for wiki contents. I needed to add something to the 'files' directory and reference it. Please see my branch https://github.com/nwg/racket-wiki/tree/add-apple-info-plist and clone and merge my branch so my file reference (Info.plist) works at https://github.com/racket/racket/wiki/Embedding-Racket

Or more simply just clone the official wiki, mkdir files, and get my Info.plist from https://raw.githubusercontent.com/nwg/racket-wiki/add-apple-info-plist/files/Info.plist

**Comment by samth** [comment]
Done (although I think including the text inline, or on a separate wiki page might be easier for people).

**Comment by nwg** [comment]
Hm, ok. I think you are right.
