### ISSUE TITLE
Windows SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE

### ISSUE THREAD

**Issue by nu8** [racket/racket#3288]
Using this file:

~~~rkt
#lang racket/base
(make-file-or-directory-link
   "a.rkt"
   "b.rkt"
)
~~~

I get this result:

~~~
PS C:\racket> racket a.rkt
make-file-or-directory-link: cannot make link
  path: C:\racket\a.rkt
  system error: A required privilege is not held by the client.; errid=1314
~~~

I am not running as admin, but I do have developer mode enabled:

<https://howtogeek.com/292914/what-is-developer-mode-in-windows-10>

Since December 2016, admin rights are not required to create a symlink, as long
as the application uses the flag `SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE`:

<https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10>

Note that other programming languages are already doing this. For example
Python:

<https://github.com/python/cpython/blob/1f764531/Modules/winreparse.h#L50>

Dart:

<https://github.com/dart-lang/sdk/blob/a677c245/runtime/bin/file_win.cc#L430>

Go:

<https://github.com/golang/go/blob/dd150176/src/internal/syscall/windows/symlink_windows.go#L13>

Nim:

<https://github.com/nim-lang/Nim/blob/af27e6bd/lib/pure/os.nim#L2417-L2419>

**Comment by mflatt** [comment]
Ok, I'll add this soon. I have avoided this change in the past, because I worried about adding something that won't work on most Windows users' machines — but that kind of problem already exists with a `make-file-or-directory-link` that works on non-Windows machines.

(To be honest, I also delayed partly out of spite toward a perpetually uncooperative filesystem whose quirks have demanded so much extra effort already.)

**Comment by nu8** [comment]
> Ok, I'll add this soon.

Thank you

> I have avoided this change in the past, because I worried about adding
> something that won't work on most Windows users' machines — but that kind of
> problem already exists with a `make-file-or-directory-link` that works on
> non-Windows machines.

If you talking about older Windows versions, I have to be honest with you. I
purposely held out on upgrading from Windows 7 for many years. Partially because
my work computer was still Windows 7, and partially because I thought it was
important to have someone still testing the old versions as long as possible.
But some significant changes have come recently, like Windows Terminal. Also
some projects have been agressively removing older Windows support recently.
For example until people complained, The newest version of Node wouldnt even
load on Windows 7.

This year I finally upgraded to Windows 10, as my work computer is now Windows
10 and it just seems time. I am telling you this it seems you are not primary
a Windows user and I wanted to give you a perspective from a Windows developer.

> (To be honest, I also delayed partly out of spite toward a perpetually
> uncooperative filesystem whose quirks have demanded so much extra effort
> already.)

Yes I agree, I am happy that admin is not required for Symlink, but this seems
like a dumb way to implement it (from Microsoft not you). I say this because it
requires every large project to change their codebase instead of just Microsoft
changing some code to "make it work". Thanks for understanding.

**Comment by mflatt** [comment]
Not surprisingly, more was needed than I expected to provide good support for links on Windows, since the filesystem distinguishes between file links and directory links. But it's in place, now.
