### ISSUE TITLE
Minor typo error in section 6.3.5 (Structure Reference) of Scribble: The Racket Documentation Tool

### ISSUE THREAD

**Issue by encomer** [racket/racket#3299]
In the text in section 6.3.5 (Structure Reference) of Scribble: The Racket Documentation Tool:

numberer — A numberer created with make-numberer determines a representation of the part’s section number as an extension of it’s patent’s number

"_patent's number_" should be (I assume) "**parent's number**".

Thank you for your great documentation.
_Please Keep Safe_.

**Comment by jackfirth** [comment]
Fixing in racket/scribble#253.

**Comment by encomer** [comment]
Thank you and congratulations for all your work.Please Keep Safe.

    On Sunday, July 19, 2020, 07:53:52 PM PDT, Jack Firth <notifications@github.com> wrote:  
 
 


Closed #3299.
