### ISSUE TITLE
Error saving file

### ISSUE THREAD

**Issue by nguyenn121019** [racket/racket#3317]
![image](https://user-images.githubusercontent.com/35902029/88848164-11bbe100-d1b6-11ea-8c2c-77d7376484dc.png)
I keep getting this error when attempting to save a file on my computer. Not sure what's going on. I redownloaded Racket and still got this error. I'm assuming it might be a local issue with my computer but I'm not sure what it could be.

**Comment by mfelleisen** [comment]
If you are running Catalina, you need to tell your OS to allow DrRacket to touch file systems. See System Preferences.

**Comment by nguyenn121019** [comment]
> If you are running Catalina, you need to tell your OS to allow DrRacket to touch file systems. See System Preferences.

I'm running Mojave v10.14.

**Comment by brightshadow42** [comment]
@mfelleisen how would you give this permission? I'm running Catalina and get the following, rather similar error: 
Thanks a lot for your help!
![Screenshot 2021-09-05 at 15 34 43](https://user-images.githubusercontent.com/90155369/132139661-c3e61fc9-b5a1-441c-b267-e1827bad30f7.png)

**Comment by capfredf** [comment]
@brightshadow42 save your files in a different folder or Go to "preferences" -> "security & privacy" -> "File and Folders" then find DrRacket check the box "Document folder"
