### ISSUE TITLE
i can't input anything .

### ISSUE THREAD

**Issue by kerwinxu** [racket/racket#3319]
**What version of Racket are you using?**
e.g., 7.7 [cs]
win 10 
racket version : 7.7
**What program did you run?**
Please include a short example that triggers the bug

i run DrRacket or GRacket , but i can't input anything and move the window of program .  what i should do ?

step:
1, run DrRacket.exe
2, i can operate the menu .
3, but Program unresponsive when i try input any keys .

Racket.exe is ok .

**What should have happened?**

**If you got an error message, please include it here.**

**Please include any other relevant details**
e.g., the operating system used or how you are running the code.

**Comment by mflatt** [comment]
You might be running into a problem with input methods that is fixed for the upcoming v7.8 release. Does the release candidate at http://pre-release.racket-lang.org/ work any better?

**Comment by kerwinxu** [comment]
> You might be running into a problem with input methods that is fixed for the upcoming v7.8 release. Does the release candidate at http://pre-release.racket-lang.org/ work any better?

Thank you . work well .
