### ISSUE TITLE
Bad compile flags

### ISSUE THREAD

**Issue by eddierucker** [racket/racket#3335]
GUI programs created with DrRacket popup a command terminal before for displaying on Windows 10. I suspect the proper flags haven't been set during compiling.

**Comment by alex-hhh** [comment]
Did you select GRacket as the base for your executable?

<img width="357" alt="cex" src="https://user-images.githubusercontent.com/11592690/89358673-95198d00-d6f6-11ea-80f7-6b70462b155a.png">

**Comment by eddierucker** [comment]
Ah! Thanks.

Eddie Rucker


________________________________________
