### ISSUE TITLE
Possible Chez flaky test

### ISSUE THREAD

**Issue by pmatos** [racket/racket#3338]
There's a CI failure for `i3le` on Solo Chez Tests that might show a flaky test:
https://github.com/racket/racket/runs/949217726#step:9:199
```
-------- o=0 cp0=t --------
0a1
> 7.mo:Bug in mat collect clause 13 at line 5600, char 3 of 7.ms
```

Started failing at https://github.com/racket/racket/commit/65b69a91e56eeea0403cb3b5165f31f80a32049b
Not failing previously at https://github.com/racket/racket/commit/342e95cf32276159164c854717f673008b573093

**Comment by samth** [comment]
That change should be a no-op on x86 so it definitely seems like a test problem.

**Comment by mflatt** [comment]
I think I've fixed this one, but lets watch it for a while.

**Comment by mflatt** [comment]
The repair was to improve `bytes-allocated` reporting to not include mark-bit space. The test remains as it was.

**Comment by pmatos** [comment]
Has been fine since. Closing. Thanks @mflatt

**Comment by mflatt** [comment]
Still happening.

**Comment by mflatt** [comment]
I don't recall seeing a failure after that later commit, so let's close.
