### ISSUE TITLE
hash-copy returns a hash table with only 32 entries max

### ISSUE THREAD

**Issue by jjsimpso** [racket/racket#3344]
**What version of Racket are you using?**
7.8 cs

**What program did you run?**
```
#lang racket

(define ht (make-hash))

(for ([i 64])
  (hash-set! ht i i))

(hash-copy ht)
```

**What should have happened?**
hash-copy should return a hash table containing 64 entries, but the table it returns only has 32 entries.

**If you got an error message, please include it here.**

**Please include any other relevant details**
Doesn't appear to happen in BC, but haven't tried this minimal example there. Testing in Linux using emacs racket-mode.

**Comment by mflatt** [comment]
Thanks for the report!

It appears that the hash keys and values are all in the copy according to `hash-ref`, but something is going wrong with iteration (as used by printing).

**Comment by jjsimpso** [comment]
This was breaking my code when I serialized the hash table and later read it back in. The serialized hash table is also missing the elements. Just mentioning in case that affects the severity.

**Comment by mflatt** [comment]
Yes, that makes sense. Like printing, serialization has to iterate through the hash table, and the bug affected iteration generally.
