### ISSUE TITLE
Chez pointer fail in CI

### ISSUE THREAD

**Issue by pmatos** [racket/racket#3345]
During CI for https://github.com/racket/racket/commit/543dab59640fa5e911443baaadaae471406dbf40 there's a failure in testing Racket CS.
https://github.com/racket/racket/runs/964580522#step:10:91

```
Section(foreign)
ERROR: pointer: fail 1414337432 vs. 1327284624
```

**Comment by mflatt** [comment]
Closing as "old, unexplained, and there have been potentially relevant repairs".

**Comment by pmatos** [comment]
@mflatt Thanks for the effort you're putting cleaning up bug reports.
