### ISSUE TITLE
assemble-site passed too many arguments

### ISSUE THREAD

**Issue by pmatos** [racket/racket#3346]
https://github.com/racket/racket/commit/983601f61158070ed9f77bc751535ccdf23cf6fa introduces afaict a new bug: 
https://github.com/racket/racket/runs/966658028?check_suite_focus=true

```
racket/bin/racket  -G build/user/config -X racket/collects -A build/user -MCR /home/runner/work/racket/racket/build/zo: -l- distro-build/assemble-site  ".github/workflows/site-small.rkt" "default" "racket"
racket: expects <config-file> <config-mode> on the command line, given 3 arguments: .github/workflows/site-small.rkt default racket 
```

**Comment by samth** [comment]
@mflatt was this supposed to still work?

**Comment by mflatt** [comment]
I expect that it will be fine going forward. The makefile and `distro-build` needed update at the same time, but there's always a lag with package updates. The Utah snapshot succeeded last night, which suggests that everything is back in sync.

**Comment by samth** [comment]
Ah, ok. Closing now, will re-open if the next one fails.
