### ISSUE TITLE
get-ffi-obj failed to get C-level functionality exported by the run-time system for chez-scheme on Mac

### ISSUE THREAD

**Issue by mrmathematica** [racket/racket#3349]
With Racket CS 7.8 on Mac

(require ffi/unsafe)
(get-ffi-obj "Sinteger" #f
             (_fun _intptr -> _scheme))

=>

 ../../../Applications/Racket v7.8/collects/ffi/unsafe.rkt:264:7: ffi-obj: could not find export from foreign library
  name: Sinteger
  library: [all opened]
  system error: dlsym(0x600000438000, Sinteger): symbol not found

The same code works fine on Racket CS 7.8 Windows.

**Comment by jackfirth** [comment]
Does it work properly on Racket BC?

**Comment by mflatt** [comment]
Yes, at least with functions that are defined in the BC implementation.

Now that I look a second time, I think the problem is that the CS configure script doesn't adjust the use of `strip` in `--enable-embedfw` mode.
