### ISSUE TITLE
Unexpected error with for/set

### ISSUE THREAD

**Issue by howell** [racket/racket#3351]
**What version of Racket are you using?**
7.6[bc] (reproduced in 7.8)

**What program did you run?**
```racket
#lang racket

(for/set ([x (set)])
  (begin
    (define-syntax (m stx) #'0)
    x))
```

**What should have happened?**
expanded successfully then evaluated to `(set)` I would think.

**If you got an error message, please include it here.**
> define-syntax: not allowed in an expression context in: (define-syntax (m stx) (syntax 0))

**Please include any other relevant details**
observed in DrRacket on mac OS 10.12

**Comment by sorawee** [comment]
Seems to be a problem with `for/fold/derived`, which assumes that `(begin ...)` is in the expression context.

**Comment by jackfirth** [comment]
Does this also fail?

```scheme
(for/set ([x (set)])
  (define-syntax (m stx) #'0)
  x)
```

**Comment by sorawee** [comment]
That works fine. My wild guess is that it treats the last expression in the for body as expression context.
