### ISSUE TITLE
[cs] "internal error: terminated in atomic mode!" on FreeBSD

### ISSUE THREAD

**Issue by Bogdanp** [racket/racket#3353]
I built Racket CS at 9619205a9dccce8b7900254701a5258c2b3a5f85 on FreeBSD 12.1-RELEASE today and, while the build succeeds, `raco setup` fails during the documentation rendering phase.

Here's the partial output: https://clbin.com/7Ytwj . I had to cut it because it was too long, but the rest was just more of the same. 

I have not encountered the issue on macOS. I figured this could have something to do with the GC changes (re. the "invalid memory reference" errors in the output) so I tried building 45a84dcb97 and ran into the same problem.

**Comment by mflatt** [comment]
Thanks for the report!

It looks like the problem may be `iconv`-related, where a missing `iconv` or failed attempt to get a converter is not handled correctly.

**Comment by Bogdanp** [comment]
Thanks for the insight! It looks like `io/converter` returns `#f` when `iconv` is not detected except for the cases where it can use its own `utf8-converter`, which seems sensible. The problem in my case was that `configure` couldn't detect `iconv` because it was installed under `/usr/local/lib`. Setting `LDFLAGS` to `-L/usr/local/lib` fixed the issue.

**Comment by mflatt** [comment]
Reopening because I have a couple of repairs to push — including correctly and finding libiconv, since one `configure` script knows it will be there.
