### ISSUE TITLE
string-contains has inversed parameters in documentation

### ISSUE THREAD

**Issue by CamiRedigonda** [racket/racket#3356]
**What version of Racket are you using?**
6.11

**What program did you run?**
```scheme
(string-contains? "Racket" "ack")
```

**What should have happened?**
It should have returned #t, as specified in the [documentation](https://docs.racket-lang.org/reference/strings.html#%28def._%28%28lib._racket%2Fstring..rkt%29._string-suffix~3f%29%29)

It seems that the parameters are inversed in the documentation.

**Comment by sorawee** [comment]
It does return `#t` to me, at least for `v7.8` CS and `v7.7` BC.

**Comment by sorawee** [comment]
What language are you using? If you use *SL languages (beginning student language, etc.), then yes, the arguments are flipped. But that's [documented](https://docs.racket-lang.org/htdp-langs/advanced.html?q=string-contains%3F#%28def._htdp-advanced._%28%28lib._lang%2Fhtdp-advanced..rkt%29._string-contains~3f%29%29).

**Comment by sorawee** [comment]
@CamiRedigonda: is the issue resolved? If so, you can close it.
