### ISSUE TITLE
Update browser history when searching manuals - racket-index

### ISSUE THREAD

**Issue by asmarcz** [racket/racket#3370]
Hello,

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I search for something at https://docs.racket-lang.org/search/index.html select what I want and then want to return to the search result. Or if you click in the language entry (like r5rs), then you cannot get back to the previous search using by hitting the back button in the browser.

**Describe the solution you'd like**
I would be glad if the search used the browser History API and modified the URL (also good for sharing).

**Describe alternatives you've considered**
I suppose this hasn't been implemented back then <2017 because of browser support. Nowadays, it is a pretty standard feature.
https://github.com/racket/racket/blob/d280462250b3b4be721a887cb0e97bf28eedeee7/pkgs/racket-index/scribblings/main/private/search.js#L829-L831

**Do you want to contribute to this feature**
I would implement this (I don't know how to build the docs myself though). I mainly want to ask whether this is a welcomed feature or it will be declined for browser compatibility (although it can be implemented in a compatible fashion).

**Comment by sorawee** [comment]
This seems very related to #936. I'd suggest you to take a look at the discussion there to see if there's anything useful. We do care about backward compatibility in a sense that whatever works before (in both new and old browsers) shouldn't break, but new features might not need to work in older browsers (though it would be nice if they work).

**Comment by rfindler** [comment]
I'd be delighted if someone added this. I believe that @samth has codified rules for backwards compatibility with our docs and browsers so probably looking at those will tell if this is a non-starter or not.

**Comment by sorawee** [comment]
This is now fixed if I understand correctly. Closing, but feel free to reopen if that's not the case.
