### ISSUE TITLE
byte strings in CS don’t have an implicit NUL terminator

### ISSUE THREAD

**Issue by sorawee** [racket/racket#3372]
**What version of Racket are you using?**
7.8 [cs]

**What program did you run?**

In Racket REPL, try to autocomplete the identifier `a`

**What should have happened?**

No corrupted entries, but there are corrupted entries like `abstractq`, `arithmetic-shift�`, and `augment*i`.

**If you got an error message, please include it here.**

N/A

**Please include any other relevant details**

@mflatt said in Slack:

> I see mangled endings in CS and not BC. It might be that byte strings in CS don’t have an implicit NUL terminator (as exposed by the FFI) like they do in BC.

**Comment by mflatt** [comment]
I have experimented (twice) with adding a NUL to bytevectors in Chez Scheme, but each time, I go back to the conclusion that foreign bindings should just use `_bytes/nul-terminated`. I haven't looked into the readline problem, but I there may be a `_bytes` to turn into `_bytes/nul-terminated`.

**Comment by mflatt** [comment]
It wasn't a `_bytes` to turn into `_bytes/nul-termrinated` (although many of those were in place), but it was an assumption of a NUL terminator: https://github.com/racket/readline/commit/f856721ae237deb053aed67a85521348451301da

Overall, the fact that CS strings don't have a NUL terminator is documented, long planned for, and specifically supported by `_bytes/nul-terminator` — so I don't think this is a bug. A case can be made for changing Chez Scheme, but I'm still reluctant to impose the extra cost globally, even though it's a very small cost.

**Comment by sorawee** [comment]
Thanks! I agree, and the bug is fixed, so I will close the issue.
