### ISSUE TITLE
"chezscheme.h" and "racketcs.h" missing from include directory

### ISSUE THREAD

**Issue by dotoscat** [racket/racket#3377]
Related with #3374

The docs talk about include those two files, but they aren't there.

Plus, whether I include "scheme.h", just trying, appears another error
`
bc_suffix.h: No such file or directory #include "bc_suffix.h"`

Thank you for your time.

**Comment by mflatt** [comment]
I see that the non-cross build was in even worse shape than the cross build for installing include files. I've made some changes, but something unrelated appears to have gone wrong with the most recent snapshot build. I've restarted it, and I'll let you know when a new one is available with the right files.

Meanwhile, to get the "chezscheme.h" and "racketcs.h" headers before then, you could get them out of something like https://www.cs.utah.edu/plt/snapshots/current/installers/racket-minimal-7.8.0.9-x86_64-linux-xenial-cs.tgz or one of the non-Windows release distributions.

**Comment by dotoscat** [comment]
Hello. I got the the headers and finally I compiled the executabled with them without any problem.

Another problem here are the boot files: *petite.boot*, *scheme.boot* and *racket.boot*. The docs say that they are at *lib* folder, however they aren't in the windows installation as well as the https://www.cs.utah.edu/plt/snapshots/current/installers/racket-minimal-7.8.0.9-x86_64-linux-xenial-cs.tgz.

I found them looking at inside the https://www.cs.utah.edu/plt/snapshots/current/installers/racket-7.8.0.9-src.tgz.

**Comment by mflatt** [comment]
Ah, of course, the boot files have the same problem. I should have thought of that.

Boot files from other archives will not work, unfortunately, and the "racket.boot" file in "racket-7.8.0.9-src.tgz" should not be there (so that's another problem to fix).

**Comment by mflatt** [comment]
It will be another day or so until the Utah snapshots pick up this change.
