### ISSUE TITLE
module instantiation failure

### ISSUE THREAD

**Issue by camoy** [racket/racket#3381]
**What version of Racket are you using?**
7.7 [bc]

**What program did you run?**
```rkt
(require (for-syntax racket/base racket/require-transform))

(begin-for-syntax
  ;; (A)
  (define-values (_ srcs) (expand-import #'racket/list))
  ;; (B)
  (parameterize ([current-namespace (make-base-namespace)])
    (namespace-require 'racket/list)))
;; (C)
(require racket/list)
```

**What should have happened?**

No error, I should think? Interestingly, commenting any one of (A), (B), or (C) is enough to fix the issue. Interesting too that this doesn't manifest in DrRacket or emacs racket-mode.

**If you got an error message, please include it here.**

```
instantiate: unknown module
  module name: ".../racket/collects/racket/private/list-predicates.rkt"
  context...:
   namespace-module-instantiate!
   for-loop
   [repeats 1 more time]
   run-module-instance!
   perform-require!
   for-loop
   finish
   [repeats 3 more times]
   pass-1-and-2-loop
   module-begin-k
   expand-module
   expand-capturing-lifts
   temp98_0
   temp71_0
   compile
   temp65_0
   ...
```

**Please include any other relevant details**
Running on Linux from command line.

**Comment by sorawee** [comment]
This appears to be fixed. Can you confirm, @camoy?

**Comment by camoy** [comment]
Looks fixed to me, thanks!
