### ISSUE TITLE
Document disappeared-use and disappeared-binding properly

### ISSUE THREAD

**Issue by sorawee** [racket/racket#3389]
`disappeared-use` is currently `indexed-racket`-ed in two places: [the Racket Reference](https://docs.racket-lang.org/reference/stxprops.html?q=disappeared-use#%28idx._%28gentag._208._%28lib._scribblings%2Freference%2Freference..scrbl%29%29%29) and [Check Syntax](https://docs.racket-lang.org/reference/stxprops.html?q=disappeared-use#%28idx._%28gentag._208._%28lib._scribblings%2Freference%2Freference..scrbl%29%29%29). Neither documents the property in detail. For example, the fact that the value ideally should be a `(`[`treeof`](https://docs.racket-lang.org/unstable/contract.html?q=treeof#%28def._%28%28lib._unstable%2Fcontract..rkt%29._treeof%29%29)` identifier?)` should be mentioned, as well as the fact that identifiers should be `syntax-local-introduce`-d when it's attached during macro expansion.

**Comment by sorawee** [comment]
Well, `treeof` seems to be inaccurate because `(cons id1 id2)` is also fine. It seems to me that the best way to describe it is to mentally run:

```
(define (extract prop)
  (let loop ([prop prop])
    (cond
      [(pair? prop) (append (loop (car prop)) (loop (cdr prop)))]
      [(identifier? prop) (list prop)]
      [else '()])))
```

**Comment by rfindler** [comment]
The value of the property is something that's not unique to this property, tho? All properties end up being trees where the interior nodes are `cons` and the non-`cons`s are the actual values that accumulated on the syntax object during expansion.

As for the introduced thing, that's also a consequence of a more general issue (that putting syntax objects into properties evades the marking that the expander does and so the code putting them into the property probably wants to do that itself too) but I can see that adding a reminder about that is a good idea.

**Comment by sorawee** [comment]
Right, I agree on both counts.
