### ISSUE TITLE
Bad error message from define-inline

### ISSUE THREAD

**Issue by yjqww6** [racket/racket#3402]
**What version of Racket are you using?**
7.8

**What program did you run?**
```
#lang racket
(require racket/performance-hint)

(define-inline (a #:a a)
  a)

(a)
```

**What should have happened?**
raise a syntax error indicating where it failed

**If you got an error message, please include it here.**
```
racket/collects/racket/private/kw.rkt:1553:14: application: required keyword argument not supplied
  procedure: a-aux
  required keyword: #:a
```
This error message is compile time but not very helpful because it is simply an exn:fail:contract without source locations: No "Jump to Error" in drracket.

**Comment by jackfirth** [comment]
Is there an error if `a` isn't called? If not, there definitely should be.

**Comment by yjqww6** [comment]
@jackfirth Yes, there is an error since the expansion of `(a)` fails. The issue here is the error message doesn't tell where it failed.

**Comment by jackfirth** [comment]
I meant is there an error if only the definition is provided:
```scheme
#lang racket
(require racket/performance-hint)
(define-inline (a #:a a)
  a)
```
And there isn't, which isn't what I expected. But after seeing that `define` allows that too, I guess it makes sense because the `a` argument is shadowing the function name.

**Comment by yjqww6** [comment]
Sorry for the confusing example. I think there is nothing wrong with the definition, it correctly handles all the things.
The issue here is about the error message of incorrect usage of the inlined function. 
Probably the following example is more clear:
```
 #lang racket
(require racket/performance-hint)

(define-inline (a arg)
  arg)

(lambda () (a))
```
In this example, the argument arg is missing in `(a)`. It fails with
```
a-aux: arity mismatch;
 the expected number of arguments does not match the given number
  expected: 1
  given: 0
```
It should carry source locations but it doesn't.

From the implementation 
https://github.com/racket/racket/blob/5bb837661c12a9752c6a99f952c0e1b267645b33/racket/collects/racket/performance-hint.rkt#L116-L121 ,
I can see it calls an aux function to handle arguments but doesn't translate the possible argument mismatch to a syntax error.

**Comment by mflatt** [comment]
Only indirectly related to the report: In looking at the implementation of `define-inline`, I notice that it defines `a-internal` and `a-inline` with the same scope as `a` (i.e., the source program can refer to them), which is surely not as intended.
