### ISSUE TITLE
regexp-replace* allocates when docs say it shouldn't

### ISSUE THREAD

**Issue by LiberalArtist** [racket/racket#3404]
The [documentation for `regexp-replace`](https://docs.racket-lang.org/reference/regexp.html#(def._((quote._~23~25kernel)._regexp-replace))) guarantees that “if `pattern` matches no part of `input`, then `input` is returned unmodified.” For `regexp-replace*`, while the documentation doesn't address this case directly, [it does say](https://docs.racket-lang.org/reference/regexp.html#(def._((lib._racket%2Fprivate%2Fbase..rkt)._regexp-replace*))) that `regexp-replace*` is “like `regexp-replace`, except that every instance of `pattern` in `input` is replaced with `insert`, instead of just the first match.” So the implication is that `regexp-replace*` should behave like `regexp-replace` when there is no match and return the `input` argument unmodified. However, currently `regexp-replace*` always returns a newly-allocated string or byte-string, both on Racket CS and Racket BC.

Example:
```racket
#lang racket

(require rackunit)

(define (input-is-returned-unmodified? replace)
  (define input (string #\a #\a #\a))
  (eq? input (replace #rx"b" input "c")))

;; `regexp-replace` docs:
;; “If `pattern` matches no part of `input`,
;;  then `input` is returned unmodified.”

(check-pred input-is-returned-unmodified?
            regexp-replace)

;; `regexp-replace*` docs:
;; “Like `regexp-replace`, except that every
;;  instance of `pattern` in `input` is replaced
;;  with `insert`, instead of just the first match.”

;; Fails! (on both CS & BC)
(check-pred input-is-returned-unmodified?
            regexp-replace*)
```

**Comment by jackfirth** [comment]
Does it make a difference if the input string is mutable or immutable? Is the output string always immutable or mutable?
