### ISSUE TITLE
Racket text-search not working

### ISSUE THREAD

**Issue by ctlj13** [racket/racket#3407]
**What version of Racket are you using?**
7.8

**What program did you run?**
I am just trying to do a simple find and replace on the code I have open.

**What should have happened?**
normal text search

**If you got an error message, please include it here.**
framework/private/text.rkt: something is wrong
  context...:
   /Applications/Racket v7.8/share/pkgs/gui-lib/framework/private/text-search.rkt:354:17: loop
   /Applications/Racket v7.8/share/pkgs/gui-lib/framework/private/coroutine.rkt:20:33
   /Applications/Racket v7.8/share/pkgs/gui-lib/framework/private/coroutine.rkt:47:20
   /Applications/Racket v7.8/share/pkgs/gui-lib/framework/private/coroutine.rkt:56:0: coroutine-run
   /Applications/Racket v7.8/collects/racket/contract/private/arrow-val-first.rkt:486:18
   /Applications/Racket v7.8/share/pkgs/gui-lib/framework/private/text-search.rkt:297:26
   /Applications/Racket v7.8/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:435:6
   /Applications/Racket v7.8/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:486:32
   /Applications/Racket v7.8/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:634:3

**Please include any other relevant details**
running Racket on macOS Catalina, Version 10.15.6

**Comment by rfindler** [comment]
Thanks for the report!

Is this something you can make happen or did it just happen on its own once? If so, can you share some steps that reliably make it happen starting from a newly opened DrRacket with no files open?

**Comment by ctlj13** [comment]
Yes. Each time Racket opens (to replicate the issue I just Force Quit racket and re-open) I will hit Cmd+F and as I type in a letter to the search box I get the error message that was included in the original issue submission.

Best,

Calen Jackman

**Comment by rfindler** [comment]
I made a short video showing search working from a fresh DrRacket with the letter `a` [here](https://users.cs.northwestern.edu/~robby/tmp/search-working.mov). I guess you see experience something different? If you have the ability to make a similar movie maybe I'll be able to spot something that will help me figure out what's going on?

**Comment by ctlj13** [comment]
See my video here <https://drive.google.com/file/d/1SVmeOiZIJKee3g_oQLVxyWDIhqn3d0qs/view?usp=sharing>.

Best,

Calen Jackman

**Comment by rfindler** [comment]
Thank you! Can you send me the file you open DrRacket with? (if it is homework or something and you don't want to post it publicly, just send it to robby@racket-lang.org)

**Comment by ctlj13** [comment]
The file seems like it’s the problem.

It’s not crucial. I just won’t open that file anymore.

Best,

Calen Jackman

**Comment by rfindler** [comment]
Thanks for confirming. I do think it really is a bug, tho, so if you were to share the file, it would help me understand what's happening and possibly even fix it. It may be that only part of the file is needed to trigger the problem if you want to shrink what's in it before sending it.

In any case, thank you for the report!

**Comment by ctlj13** [comment]
I think this is the file that was causing the issue.

Best,

Calen Jackman

**Comment by samth** [comment]
@ctlj13 Unfortunately, attaching files to email to github doesn't work. You can upload them at https://github.com/racket/racket/issues/3407 or email them to Robby or to me at samth@racket-lang.org.

**Comment by ctlj13** [comment]
See the file attached. I had to just copy and paste the source .rkt code into a .txt file because I guess .rkt is not a supported file format for attachments.
[sudoku-v3.txt](https://github.com/racket/racket/files/5262405/sudoku-v3.txt)


Best,

Calen Jackman

**Comment by rfindler** [comment]
@ctlj13 Is it possible that you copied and pasted the contents of the file into another editor to save it, instead of using the file that DrRacket itself saves?

**Comment by rfindler** [comment]
Yeah, I am guessing that the file in your drracket has comment boxes or racket boxes nested several layers deep (but the text file doesn't). I can see in the video that your contour window is shorter than the one you get if you simply rename the file and upload it, which suggests you have some nested boxes down at the bottom there.
