### ISSUE TITLE
add racket/bin to PATH on installation

### ISSUE THREAD

**Issue by spdegabrielle** [racket/racket#3409]
**Is your feature request related to a problem? Please describe.**
new users struggle with setting the PATH environment variable when first using racket
while this *is* something they will learn as they grow as developers it would be nice to smooth the early experience with racket by setting it for them

**Describe the solution you'd like**
Set PATH on install or first run of DrRacket

**Describe alternatives you've considered**

- [x] making instructions more prominent on the [racket wiki](https://github.com/racket/racket/wiki/Set-your-PATH-environment-variable)
- [x] pinning to the #help and #beginners channels on discord and slack
- [ ] creating a quickscript to do this for them - disregarded as quickscript comes with no base set of scripts

**Do you want to contribute to this feature**

Yes

**[Optional] Additional context**

e.g.
![set path on install of Python](https://lwstatic-a.akamaihd.net/kb/wp-content/uploads/2018/12/installpython-min.png)

**Comment by jackfirth** [comment]
Yes _please_.

**Comment by yangh** [comment]
Yes, please, especially for Windows and Mac OS.

**Comment by sorawee** [comment]
Just found from #1610 that DrRacket already has "configure command line for racket" under "Help". So I don't think we need a redundant quickscript. What we should do instead is to somehow make users aware of its existence.
