### ISSUE TITLE
Incorrect Output from run-tests in Version 7.8

### ISSUE THREAD

**Issue by mwb33** [racket/racket#3410]
**What version of Racket are you using?**
Version 7.8 Regular

**What program did you run?**
I teach unit testing and use run-tests frequently. The behavior seems to have changed in version 7.8. Here is a small test example.

#lang racket
(require rackunit)
(require rackunit/text-ui)

(define-test-suite test_example
  (check-equal? 1 4)
  (check-equal? 1 1)
  (check-equal? 2 5)
)
(define failures (run-tests test_example))
(display failures)
(newline)
;Version 7.7: 1 success(es) 2 failure(s) 0 error(s) 3 test(s) run
;Version 7.8: 3 success(es) 0 failure(s) 0 error(s) 3 test(s) run

**What should have happened?**
In Version 7.7 and below, it would say 1 success and 2 failures. It would also return 2. That makes sense since 2 tests failed. In Version 7.8, it says all three tests passed even though they clearly failed.

**If you got an error message, please include it here.**

**Please include any other relevant details**
I test this on Mac, but have student try it in Linux and Windows with the same results.

**Comment by sorawee** [comment]
I can confirm this. This happens in Rosette's test suites, too.

**Comment by samth** [comment]
There's only been one change in rackunit since 7.7, which is https://github.com/racket/rackunit/pull/109. @sorawee can you test if reverting that fixes the problem?

cc @AlexKnauth

**Comment by sorawee** [comment]
Yes, reverting that PR fixes the problem.
