### ISSUE TITLE
check-box% callback receives incorrect event type on Windows 10

### ISSUE THREAD

**Issue by eddierucker** [racket/racket#3419]
In Windows 10, from a check-box% callback, the event type is 'button. On Linux the event type is 'check-box. According to the documentation, I expect to get 'check-box on both platforms. I am using racket bc version 7.8.0.10--2020-09-22(54367de/a) [3m].

[testing.txt](https://github.com/racket/racket/files/5307908/testing.txt)

**Comment by mflatt** [comment]
Thanks for the report!
