### ISSUE TITLE
build-path/convention-type errors for “opposite” OS when using path-strings

### ISSUE THREAD

**Issue by otherjoel** [racket/racket#3424]
Using Racket 7.7 and 7.8, the following on macOS fails with error:

```racket
(build-path/convention-type 'windows "subfolder" "file.txt")
build-path/convention-type: specified convention incompatible with string path element
  path element: "tutorial"
  convention: 'windows
```

The same error results when running on Windows and specifying the type as `'unix`.

It seems to me that this should not produce an error. The [docs][1] say `build-path/convention-type` accepts path-strings, but do not say anything about path-strings being unusable for constructing a path for the “opposite” OS. But if this is the designed behavior, maybe the resolution is to update the docs.

[1]: https://docs.racket-lang.org/reference/Manipulating_Paths.html#%28def._%28%28quote._~23~25kernel%29._build-path%2Fconvention-type%29%29

**Comment by mflatt** [comment]
The documentation for `build-path` does say that strings are treated as paths for the current platform. It makes sense to improve the documentation for `build-path/convention-type` to note that strings still count for the current platform, the same as for `build-path`.

The reason that a string cannot be converted to a path for a different platform is highlight the fact that the target platform's encoding of string into paths in generally unknown. You can use `bytes->string` to insist that a particular sets of bytes is used as the path name, but that hopefully helps draw out the portability issues and potential problem of making encoding assumptions. (There are also sorts of problems that the string<->bytes<->paths conversion rules don't prevent, of course, and it's a surprisingly fraught area.)

**Comment by alex-hhh** [comment]
This was discussed a while ago on racket-users: https://groups.google.com/g/racket-users/c/OAXqQd7XYbc/m/Q8M_jbVwCAAJ

**Comment by otherjoel** [comment]
Thanks Matthew; I can see *why it works the way it does*, so at a minimum I can create a PR for the docs.

In crafting the language for that PR, however, I’m sort of blocked by no longer understanding why `build-path/convention-type` exists. It would seem the only way to assemble a path for the “opposite” platform is with path elements whose convention type is already using that platform. But I can just as well do that with plain old `build-path`. So what can you actually do with `build-path/convention-type` that you cannot do with `build-path`?
