### ISSUE TITLE
DrRacket 7.8 help desk won't open 

### ISSUE THREAD

**Issue by CloudyPhia** [racket/racket#3426]
Hello everyone! I am currently using DrRacket 7.8 on Mac.

The issue that I am currently having is that whenever I am in DrRacket and I try to use the help desk (from within DrRacket) it pulls up the helpdesk but doesn't provide any results. I have included a picture below where I have searched for "define" as an example, and you can see that there are no results. If I click on anything else on the screen, it just says "Your File Was Not Found (it may have been moved or deleted)". 

![drracketproblem](https://user-images.githubusercontent.com/64567175/95144482-021cc380-0736-11eb-8154-14ed8b874b9b.jpg)

I'm not really sure what to do about this. I've deleted DrRacket entirely from my computer and re-installed it twice now, which fixes the helpdesk for all of one minute before it starts doing this again. If the file "couldn't be found" then re-installing DrRacket should've fixed this so it seems like a bug...

 I know I could search on google for the helpdesk, but it's a lot more convenient to use the internal helpdesk rather than searching on google. I just want to know how to fix this because right now it seems like a weird bug.

I hope someone can provide help/fix this bug (if it is a bug...)! Thank you in advance :)

**Comment by sorawee** [comment]
Can you provide us the URL of the page?

**Comment by CloudyPhia** [comment]
> Can you provide us the URL of the page?

This isn't part of the helpdesk you find on google its part of DrRacket's internal help desk - so the URL at the top of the page for me is file:///Users/sophiahiebert/Library/Racket/7.8/doc/search/index.html?&q=define

Maybe the URL isn't supposed to look like that when you use the internal system but that's what it looks like for me :)

**Comment by IlnarSelimcan** [comment]
@CloudyPhia , when you install a racket package with `raco`, e.g. `raco pkg install pollen`, do you get any error / warning messages regarding the `local database' or something like that?

I experienced the same issue as you do, and was getting a message like that, but after removing the `.racket/7.7/ directory and re-installing racket the issue was re-solved.

Unfortunately I hadn't taken a note on what exactly the message was.

**Comment by jbclements** [comment]
Out of curiosity: if you hover over the links that don’t work, and right click to copy the link URL, what do you get?

John

**Comment by CloudyPhia** [comment]
> @CloudyPhia , when you install a racket package with `raco`, e.g. `raco pkg install pollen`, do you get any error / warning messages regarding the `local database' or something like that?
> 
> I experienced the same issue as you do, and was getting a message like that, but after removing the `.racket/7.7/ directory and re-installing racket the issue was re-solved.
> 
> Unfortunately I hadn't taken a note on what exactly the message was.

I installed the racket package through this link: https://racket-lang.org/download/ which was given to me by my school. I'm not exactly sure I know what you mean by 'raco'. I haven't gotten any messages regarding the local database that I can remember. 

How would I go about removing the .racket/7.7/ directory? Ive looked everywhere and I can't find it. (I've also only ever downloaded 7.8).

Thank you for your response!!! :)



> Out of curiosity: if you hover over the links that don’t work, and right click to copy the link URL, what do you get? John

It still says "Your file was not found" :(

**Comment by sorawee** [comment]
@CloudyPhia: try `mv ~/Library/Racket/7.8 ~/Library/Racket/7.8.bak` to temporarily remove the directory. If things go wrong, you can rename `7.8.bak` back to `7.8` later.

**Comment by sorawee** [comment]
Note that on my computer, immediately after removing the directory `7.8`, the page doesn't work at all (I think this is another bug). I needed to install a Racket package (via DrRacket package manager) to initialize the user scope search page. So you might need to do that as well.

**Comment by CloudyPhia** [comment]
> @CloudyPhia: try `mv ~/Library/Racket/7.8 ~/Library/Racket/7.8.bak` to temporarily remove the directory. If things go wrong, you can rename `7.8.bak` back to `7.8` later.

I am going to sound like an absolute idiot but what do I do with that? I tried searching it on my computer and no results came up :/ it doesn't even exist in my DrRacket application file...

**Comment by sorawee** [comment]
@CloudyPhia: sorry, I assume that you know how to use command-line, and apparently you are not.

What I meant by that is to use a file manager (Finder) to navigate to `/Users/sophiahiebert/Library/Racket/`. Then, rename the `7.8` directory to `7.8.bak`.

**Comment by CloudyPhia** [comment]
> /Users/sophiahiebert/Library/Racket/



> @CloudyPhia: sorry, I assumed that you know how to use command-line, and apparently you are not.
> 
> What I meant by that is to use a file manager (Finder) to navigate to `/Users/sophiahiebert/Library/Racket/`. Then, rename the `7.8` directory to `7.8.bak`.

OH!!!! Sorry omg yes I know how to do this my brain just wasn't working for a sec there lmao. Thank you!!! :)

**Comment by rfindler** [comment]
I believe the real issue here is that Mac OS has some security layers that sometimes cause it to decline to open javascript on pages with file: urls. DrRacket is attempting to play various tricks to allow these pages to run javascript but apparently they aren't always successful.

A short term fix: can you reach the internet? If so, then using docs.racket-lang.org should have the documentation. Not ideal, I know.

**Comment by Metaxal** [comment]
@CloudyPhia Try `raco setup --doc-index` maybe with `--avoid-main` if it fails without it
