### ISSUE TITLE
A minor typo error at the data-frame package documentation.

### ISSUE THREAD

**Issue by encomer** [racket/racket#3433]
There is a minor typo error at the start of **section 8** of the data-frame package documentation:
It says: GPX Exchange Format (GPX)
instead of: **GPS** Exchange Format (GPX)

Thank you for the excellent data-frame package, and the great documentation system.

**Comment by alex-hhh** [comment]
This issue was reported on the wrong project and should be transferred to the [data-frame](https://github.com/alex-hhh/data-frame) project.

**Comment by sorawee** [comment]
I think it requires the write permission on both repos to transfer the issue. In any case, it's fixed, so I will simply close it.

**Comment by alex-hhh** [comment]
Well, it is not fixed yet, since I don't accept pull requests with typo fixes (I explained this when I closed that pull request), but I will fix it myself later this week.

**Comment by sorawee** [comment]
My apologies. I didn't take a look carefully.
