### ISSUE TITLE
Syntax objects are falsey in `if`?

### ISSUE THREAD

**Issue by jswrenn** [racket/racket#3436]
**What version of Racket are you using?**
7.8

**What program did you run?**
```racket
#lang racket
(if #`() #t #f)
```

**What should have happened?**
The documentation for [`if`](https://docs.racket-lang.org/reference/if.html?q=if#%28form._%28%28quote._~23~25kernel%29._if%29%29) suggests that this program should produce `#t`:
> Evaluates `test-expr`. If it produces any value other than `#f`, then `then-expr` is evaluated, and its results are the result for the `if` form. Otherwise, `else-expr` is evaluated, and its results are the result for the `if` form.

Instead, it produces `#f`.

**Please include any other relevant details**
I executed this snippet in DrRacket. The results are the same whether in the definitions pane, or in the REPL.

**Comment by mflatt** [comment]
Thanks for the report!

I am able to replicate this (very surprising!) bug, even with the more primitive form
```
#lang racket/kernel
(printf "~s\n" (if (quote-syntax 1) 'ok 'bug!))
```
Something is wrong at macro-expander layer, since the generated linklet has `#f` in place of the syntax object.

**Comment by shriram** [comment]
Credit to Jonathan Weisskopf, who discovered this bug.
