### ISSUE TITLE
[Feature Request] Predicate-based dispatch form

### ISSUE THREAD

**Issue by countvajhula** [racket/racket#3438]
**Is your feature request related to a problem? Please describe.**

`cond` expressions like this one are fairly common:
```
(cond [(number? v) 'do-this]
      [(string? v) 'do-that]
      [(char? v) 'do-something-else]
      [else 'do-the-other-thing])
```

In this illustrative example, all of the conditions are predicated on some common subject (in this case, `v`), but this fact is only implicit in the conditional, and the reader must go through the entire conditional expression (which may span multiple screens) before coming to this conclusion themselves. Additionally in writing out such an expression the developer must repeat the (possibly multi-variadic) subject in each predicate, an activity that is always error-prone and likely to lead to bugs.

```
;; multi-variadic subject
(cond [(< a b) 'less]
      [(> a b) 'greater]
      [(= a b) 'equal]
      [else 'incomparable])
```

**Prevalence**
Using the racket/racket source as an arbitrary sample and from eyeballing [these search results](https://github.com/racket/racket/search?q=cond), this "subject-predicates" form is a non-trivial fraction of all `cond` expressions (at a ballpark, somewhere between a tenth and a third). See [this comment](https://github.com/racket/racket/issues/3438#issuecomment-709567341) for some examples taken from the Racket source.

**Describe the solution you'd like**
_Good syntax is general enough to be useful, and specific enough to be clear._ With this in mind, I propose:

A "subject-predicates" conditional form, `on`, that encodes the known constraint into the syntax, so that:

1. the reader (and for that matter, the compiler) knows immediately (even for expressions that may extend beyond the boundaries of the screen) that the conditions all refer to a subject
2. the developer Doesn't need to Repeat (Y)themselves, avoiding errors and bugs, and saving development time
3. With less repetition, there's less visual clutter and more clarity resulting from the commonalities being factored out at the outset, leading to time saved in reading and understanding code

```
(on (v)
   [number? 'do-this]
   [string? 'do-that]
   [char? 'do-something-else]
   [else 'do-the-other-thing])

(on (a b)
   [< 'less]
   [> 'greater]
   [= 'equal]
   [else 'incomparable])
```
[**Note: this form was called `dispatch` in the original version of this issue, and was subsequently renamed to `on`. See [here](https://github.com/racket/racket/issues/3438#issuecomment-708558236) for more on the choice of name.**]

Here is an implementation of this macro that has some but not all of the proposed properties:

```
(define-syntax-parser on
  [(on (arg ...)) #'(cond)]
  [(on (arg ...)
       [predicate consequent ...] ...
       [(~datum else) else-consequent ...])
   #'(cond [(predicate arg ...) consequent ...]
           ...
           [else else-consequent ...])]
  [(on (arg ...)
       [predicate consequent ...] ...)
   #'(cond [(predicate arg ...) consequent ...]
           ...)])
```

This macro supports all of the examples that follow. More work would be needed, however, in order for it to exhibit all of the proposed behavior (see the "variations" that follow the examples below).

**Additional examples (collected from comments)**
```
;; unary predicate
(on (n)
  [positive? 'positive]
  [negative? 'negative]
  [zero? 'zero])

;; binary predicate
(on (u v)
  [follows? 'follows]
  [(flip follows?) 'is-followed-by]
  [else 'unconnected])

(on (n m)
  [= 'equal]
  [factor? 'factor]
  [multiple? 'multiple]
  [(compose (curryr > 1) gcd) 'common-factors]
  [else 'coprime])

;; n-ary predicate
(on (1 2 3)
  [> 'decreasing]
  [< 'increasing]
  [else 'non-monotonic])

;; heterogeneous predicate
(on (person book)
  [has-read? (solicit-review person)]
  [is-reading? (display-status person book)]
  [is-likely-to-read? (show-recommendations person book)]
  [else 'uninterested])

```

**Proposed Variations**

Some possible ways to extend `on`'s expressiveness in ways that would be natural.

1. Succinctly indicate standard predicates like `eq?` of the appropriate arity, and boolean combinators like `and` (conjoin)
```
(on subject-form [(eq? v) 'action])
(on subject-form [(equal? v) 'action])
(on subject-form [(and pred1 pred2) ( 'action]) ; `and` (or perhaps `&&`) is specially handled and compiles to `conjoin` since the condition is constrained to be a predicate, but using `conjoin` would also work here without triggering special handling
(on subject-form [(or pred1 (not pred2))] 'action]) ; `and`, `or`, `not` (or perhaps stand-in symbols like && || and !!) all compile to functions, i.e. conjoin, disjoin, and negate
```
2. A "functional" operator, say `call` (as a placeholder), that passes the subjects through to a function. This would be useful in cases where both the condition as well as the consequent action are in terms of the subject(s)
```
(on subject-form [positive? call displayln])
(define (abs-difference) (on (u v) [> call -] [else call (flip -)]))
```
3. Retain support for cond's `=>` operator for cases where the consequent action is in terms of the result of the condition
```
(on subject-form [(regexp-match "[[(link)]]") => displayln])
```
4. Seamless "parallel composition" of unary predicates to form n-ary predicates [syntax is just an example]
```
(on (user cart) [subscriber?|empty? (show-offers user)])
```
5. "Predicate under a mapping" / "apply-map" pattern for when the condition is in terms of the subjects under a mapping
```
(on (a b) [(equal? \ string-upcase) 'equal])  ; "equal under string-upcase"
```

**Describe alternatives you've considered**
- The [`case`](https://docs.racket-lang.org/reference/case.html) form comes to mind, but it only does literal, symbolic equality rather than arbitrary predicates.
- [Pattern-matching](https://docs.racket-lang.org/reference/match.html) is another possibility. While it is usable in a subset of cases covered in this proposal, it may not be the best construct to use in such cases. Pattern matching is naturally applied to the _form_ of the input rather than assertions about its contents. On this point, [==](https://docs.racket-lang.org/reference/match.html?q=match#%28form._%28%28lib._racket%2Fmatch..rkt%29._~3d~3d%29%29) and sentinels like `?` (pointed out in the comments) seem to represent overreach on the part of the pattern matching forms, since these deal not with the _structure_ but rather, assertions about the _properties_ of the input. Additionally, `?` does not generalize to the n-ary case out of the box. Extending pattern matching to support assertions about the contents is arguably a tendency toward bloat, avoided by the addition of the `on` form.
- There's also the [`=>`](https://docs.racket-lang.org/reference/if.html#%28form._%28%28lib._racket%2Fprivate%2Fletstx-scheme..rkt%29._~3d~3e%29%29) syntax in `cond`, which plays a similar role to the proposed syntax in that it propagates context to avoid repetition within the cond form, but it is a different thing and not applicable here. It could, however, be supported in the `on` form if that's something we'd want.

**Do you want to contribute to this feature**
Sure, with some guidance (and if we agree this is a worthwhile addition), I could start a PR to add this feature.

**Comment by samth** [comment]
Note that you can do predicates in `match`:
```
(match v 
  [(? number?) 'do-this]
  [(? string?) 'do-that]
  [(? char?) 'do-something-else]
  [_ 'do-the-other-thing])
```

**Comment by countvajhula** [comment]
@samth I figured there ought to be a way already, that's great. Although, that still doesn't handle the n-ary predicate case, or does it?

**Comment by samth** [comment]
Here's one way to do it (untested):
```
(define-match-expander ?? (syntax-rules () [(?? pred) (? (lambda (x) (apply pred x)))]))
(match (list 1 2 3)
  [(?? >) 'decreasing]
  [(?? <) 'increasing]
  [_ 'non-monotonic])
```

**Comment by countvajhula** [comment]
It works! And TIL how to define match expanders :)
Nevertheless, the proposal above for this common case is simpler and more uniform than having to learn about and use/define match patterns.

**Comment by samth** [comment]
I think the important questions are:
1. `dispatch` is very specialized -- it takes list arguments, and procedure names. `match` is significantly more general, at the cost of a little more verbosity. Where on the balance do we want to be?
2. Would adding something like `??` to `match` be better than having a distinct macro?
3. Either `dispatch` or `??` could be defined outside the standard library. Do we want to add it to the standard library, or should it live somewhere else, such as in a package that people can install?

**Comment by countvajhula** [comment]
FTR `dispatch` doesn't require the arguments as a list - it accepts them directly as arguments. And it also doesn't expect procedure names, just anything that evaluates to an n-ary predicate.

**Comment by samth** [comment]
Sure, there are some differences. Although any expression works with `?` (and also `??`).

**Comment by countvajhula** [comment]
We are on the same page re: the important questions, modulo that `dispatch`, while more specialized than `cond`, is no more specialized than it needs to be. In fact it's less specialized than `case` which checks for literal equality. We don't need `case`, yet, it's handy in some common cases where it expresses things cleanly. `case` being in the standard library seems to make a "case" for `dispatch` as another syntactic recourse for a common case.

Please take whatever action you see fit on this issue, and I'm happy to provide opinions if they help :)

**Comment by jackfirth** [comment]
`case` being in the standard library is a bad precedent that probably shouldn't be followed. Were I to redesign the standard library today, I wouldn't include it.

I think an n-ary `??` is more complexity than I'd like in match patterns. For one thing, it's not clear whether it should work with lists or with arbitrary sequences. If it's restricted to lists, that's unnecessary headache for users who happen to have a vector or set or some other kind of sequence. If it's made to operate on arbitrary sequences, then we have to answer complex questions about how it applies to sequences like ports whose iteration has side effects.

For the use cases presented in this issue, I'd rather just have predicates like `ascending?` and `descending?` for directly testing whether a sequence of numbers is sorted, instead of relying on the variable-arity behavior of `<` and `>`. Especially because `<` and `>` do not work when given zero arguments.

**Comment by countvajhula** [comment]
More examples:
```
(dispatch (u v)
  [follows? 'follows]
  [(flip follows?) 'is-followed-by]
  [else 'unconnected])

(dispatch (n m)
  [= 'equal]
  [factor? 'factor]
  [multiple? 'multiple]
  [(compose (curryr > 1) gcd) 'common-factors]
  [else 'coprime])
```

@jackfirth Where would you suggest putting syntax like `case` and `dispatch`, if not in the standard library? Is there a collection namespace for general-purpose syntactic extensions?

**Comment by countvajhula** [comment]
@jackfirth also note that the zero argument case doesn't affect the example since the arguments aren't provided to the macro as a list but directly. `(dispatch () [< ...])` would be a programmer error.

**Comment by countvajhula** [comment]
I've renamed the proposed syntax to `on` as an homage to the `ON x GOTO` from good ol' BASIC.
This has the other benefits that (1) "on" suggests a subject. "On the subject of ...", (2) it could also be read as "dispatch on ...", (3) it's succinct, and (4) it isn't being used for anything else, as far as I know.
I've updated the issue description to reflect this.

**Comment by jackfirth** [comment]
> Where would you suggest putting syntax like `case` and `dispatch`, if not in the standard library? Is there a collection namespace for general-purpose syntactic extensions?

It's less about where I'd put them, and more that I'd rather use `match` and/or `cond` instead of using `case` or `dispatch`. I don't think `case` and `dispatch` add enough value to be worth the increased number of forms to learn. And `case` is especially weird because it implicitly (!) uses `eq?` instead of `equal?`.

> also note that the zero argument case doesn't affect the example since the arguments aren't provided to the macro as a list but directly. `(dispatch () [< ...])` would be a programmer error.

That use case _shouldn't_ be a programmer error. Applying `<` to a sequence is a way of asking if a sequence is sorted. Empty sequences are sorted. So I don't think applying `<` is a good way to test if sequences are sorted.

The reason I'm in favor of a function that explicitly accepts a sequence instead of reusing `<` and `>` is because it makes it easier to explain its behavior on different, more exotic kinds of sequences than plain lists. For instance, you can ask if a side effectful sequence is sorted without evaluating all of it - just stop as soon as you encounter an unsorted element. That's not possible to express if the sequence is represented as arguments to a variable-arity function.

**Comment by sorawee** [comment]
> And case is especially weird because it implicitly (!) uses eq? instead of equal?.

Is this actually true? I'm surprised to hear it. The [doc](https://docs.racket-lang.org/reference/case.html) mentions that it uses `equal?`, and in my testing it does seem to use `equal?`

```
#lang racket

(define x (add1 1111111111111111111111111111111111110))

'equal?
(equal? 1111111111111111111111111111111111111 x)

'eq?
(eq? 1111111111111111111111111111111111111 x)

'case
(case x
  [(1111111111111111111111111111111111111) #t]
  [else #f])
```

produces

```
'equal?
#t
'eq?
#f
'case
#t
```

**Comment by countvajhula** [comment]
Re: minimizing the number of syntactic forms, I agree. Yet, if minimization were the only goal, then we wouldn't have both `if` as well as `cond`. We don't just need a minimum of syntactic forms, we need a minimum number that are sufficiently general to be useful and also sufficiently specific to be clear. This is the balance we are assessing.

Those are some good points re: sorting, but I think maybe the `<` example may not be the best one here, because for one thing, the limitation that `(on () [< ...])` is a programmer error is because `<` doesn't accept 0 arguments, not that `on` doesn't. That example is really representative of a ternary predicate, rather than a variadic one. It's just that a variadic example was convenient instead of contriving a familiar ternary example. Although, for the variadic case (not necessarily `<` and the attendant sorting implications), I would argue that in practice since the arguments are supplied manually by the programmer, we can treat them as constant-length, so that any considerations around algorithmic complexity would be moot.

**Comment by jackfirth** [comment]
> > And case is especially weird because it implicitly (!) uses eq? instead of equal?.
> 
> Is this actually true? I'm surprised to hear it. The [doc](https://docs.racket-lang.org/reference/case.html) mentions that it uses `equal?`, and in my testing it does seem to use `equal?`

Oops, nope, I misremembered things. The problem I hit with `case` is that it only works with built-in Racket datatypes, and only those that have quoted forms recognized by the reader. I can't use `case` on constants defined in variables:

```scheme
(define magic-number 42)
(case x [(magic-number) "answer to everything"])
; doesn't work, matches x against the quoted symbol 'magic-number
```

So I can't use it with my [enum types](https://docs.racket-lang.org/rebellion/Enum_Types.html). No idea where I got the `eq?` misconception from.

Anyway. I agree that the goal is not to minimize the number of forms. What I'm saying is that each new form is a cost (because readers need to learn the form) and that needs to be offset by the value added by the form. I don't think either `case` or `dispatch` really offers enough value over `cond` and `match` to be worth that cost, because they're pretty uncommon use cases and when they do apply they're not much simpler than the existing alternatives. I think `if` _is_ worth that cost, because a conditional with only two branches is by far the most common kind of conditional and `if` gets rid of a _lot_ of noise that `cond` would introduce in those cases, especially for simple conditionals.

**Comment by countvajhula** [comment]
I've definitely been bitten by that one too. `case` is a little odd, to be sure.

Out of curiosity, I searched the racket/racket repo source for occurrences of `cond` to get a sense of the prevalence of the kind of pattern we're talking about here. It's a non-trivial fraction, at a ballpark somewhere between a tenth and a third of all conds follow this subject-predicates pattern ([take a look](https://github.com/racket/racket/search?q=cond)).

The benefit I saw to `on` in each of these instances was that while the `cond` tells you that a result is dependent on conditions, `on` tells you right off the bat that these conditions are all predicated on some value or on a relationship between some values. With `cond`, you need to read the entire conditional to come to that conclusion yourself, since there are no constraints on what the conditions might be.

Syntactically, while `on` clears up noise in each of these cases, the extent of visual cleanup is not significant. But the conceptual clue that it gives you, and the constraint it places on the conditions, is where it brings value. Here are some examples from the first few pages of search results on the Racket source (there's no suggestion here that these be replaced - they're just samples to illustrate `cond` usage in the wild):

```
;; cond
(define (tak0 x y z)
    (cond ((not (< y x)) z)
          (else (tak1 (tak37 (- x 1) y z)
                      (tak11 (- y 1) z x)
                      (tak17 (- z 1) x y)))))

;; on
(define (tak0 x y z)
  (on (x y)
      (>= z)
      (else (tak1 (tak37 (- x 1) y z)
                  (tak11 (- y 1) z x)
                  (tak17 (- z 1) x y)))))

;; cond
(define (fxmap-count d)
   (cond
     [($branch? d)
      ($branch-count d)]
     [($leaf? d) 1]
     [else 0]))

;; on
(define (fxmap-count d)
  (on (d)
      [$branch? ($branch-count d)]
      [$leaf? 1]
      [else 0]))

;; cond
(define name (cond
               [(string? in-name) (string->symbol in-name)]
               [(gensym? in-name) (string->symbol (gensym->pretty-string in-name))]
               [else in-name]))

;; on
(define name (on (in-name)
                 [string? (string->symbol in-name)]
                 [gensym? (string->symbol (gensym->pretty-string in-name))]
                 [else in-name]))

;; cond
(cond
  [(blame-yes-swap? b) (loop (blame-and-more b) (not swapped?))]
  [(blame-no-swap? b) (loop (blame-and-more b) swapped?)]
  [else (f b swapped?)])

;; on
(on (b)
    [blame-yes-swap? (loop (blame-and-more b) (not swapped?))]
    [blame-no-swap? (loop (blame-and-more b) swapped?)]
    [else (f b swapped?)])

;; cond
(define match-empty
  (lambda (p r)
    (cond
      [(null? p) r]
      [(eq? p 'any) (cons '() r)]
      [(pair? p) (match-empty (car p) (match-empty (cdr p) r))]
      [(eq? p 'each-any) (cons '() r)]
      [else
       (case (vector-ref p 0)
         [(each) (match-empty (vector-ref p 1) r)]
         [(each+) (match-empty
                   (vector-ref p 1)
                   (match-empty
                    (reverse (vector-ref p 2))
                    (match-empty (vector-ref p 3) r)))])])))

;; on
(define match-empty
  (lambda (p r)
    (on (p)
        [null? r]
        [(eq? 'any) (cons '() r)]
        [pair? (match-empty (car p) (match-empty (cdr p) r))]
        [(eq? 'each-any) (cons '() r)]
        [else
         (case (vector-ref p 0)
           [(each) (match-empty (vector-ref p 1) r)]
           [(each+) (match-empty
                     (vector-ref p 1)
                     (match-empty
                      (reverse (vector-ref p 2))
                      (match-empty (vector-ref p 3) r)))])])))

```

This last example requires an additional feature not present in the version of `on` in the issue description, viz. recognizing the `eq?` pattern. This is similar to the syntax for equality checks in pattern-matching, but I think it's more natural here, since pattern matching is commonly and most neatly applied to the _form_ of the input rather than assertions about its contents. There are probably a couple more standard checks that would be natural for `on`, and which might take away from the inclination to bloat `match` with content-related (rather than form-/shape-related) features.

**Comment by countvajhula** [comment]
Just noticed that this is still open. It's no longer relevant as a lot of it became [switch](https://docs.racket-lang.org/qi/Language_Interface.html#%28form._%28%28lib._qi%2Fmain..rkt%29._switch%29%29) in Qi, which does all of the above and a lot more!
