### ISSUE TITLE
Package Regressions in 7.9

### ISSUE THREAD

**Issue by jbclements** [racket/racket#3444]
Currently, the following packages either fail to build, or have test failures, regressing from 7.8.

7.8 build: https://pkg-build.racket-lang.org
7.9 pre-release build: https://plt.eecs.northwestern.edu/release-pkg-build/

Use check-boxes to indicate "IMO not a release blocker (anymore)"

## All packages

- [x] ("deferred" . (success test-fail))
  
Per Sam, known bug in the pkg's tests

- [x] ("herbie-test-deploy" . (install-conflict build-fail))

https://plt.eecs.northwestern.edu/release-pkg-build/server/built/archive-fail/herbie-test-deploy.txt

looks like this might be from me@pavpanchekha.com, probably was supposed to be deleted, sent mail to ask.

confirmed via email, meant to be deleted.

- [ ] ("quickscript-test" . (success test-fail))

sent email to ask about this

- [x] ("runomatic" . (no-docs build-fail))

looks like a transient pkg dependency failure, wait for re-run

- [ ] ("rwind" . (no-docs test-fail))

per Sam, "different environment on the release-pkg-build server"

- [ ] ("sass" . (success test-fail))

discussion below, not sure why the shared library doesn't load

- [x] ("zeromq-r" . (success test-fail))

see discussion below.

- [x] ("gtp-benchmarks" . (success test-fail))

https://plt.eecs.northwestern.edu/release-pkg-build/server/built/test-fail/gtp-benchmarks.txt

no idea what's going on here yet.

**Comment by Bogdanp** [comment]
Re. `sass`, the dependency was pulled in and added to the lib directory. From [the logs](https://plt.eecs.northwestern.edu/release-pkg-build/server/built/test-fail/sass.txt):

```
raco setup: --- installing foreign libraries ---                   [16:57:12]
raco setup: installing: foreign library /home/racket/build-pkgs/user/.local/share/racket/7.8.0.900/lib/libsass.so
```

The error from `ffi-lib` is `No such file or directory` so maybe there's some sort of lib search path or permissions issue.

**Comment by jbclements** [comment]
@Bogdanp I'm really interested in that path: it looks like the package-build-server is putting it in a path that looks very much like a windows path (.local/share). But the machine itself is pretty clearly linux, and it's clearly fetching the linux version of the library. So I'm really not sure what's going on. Maybe @rfindler or @samth knows what's going on here? (BTW, yes I see that it works fine on the 7.8 release, including the install of libsass.so).

7.9 test release : https://plt.eecs.northwestern.edu/release-pkg-build/server/built/test-fail/sass.txt (dated Wednesday, October 14th, 2020 5:57:08pm)
7.8 release : https://pkg-build.racket-lang.org/server/built/install/sass.txt

**Comment by samth** [comment]
`.local` is a pretty common on Linux.

**Comment by mflatt** [comment]
The `.local/share` path is due to the (new to v7.9) XDG conventions by default for paths reported by `find-system-path`. See also #3268.

**Comment by jbclements** [comment]
Okay, then I have no idea why it failed :).

**Comment by rmculpepper** [comment]
Re zeromq-r, that's mine, not Jay's. The tests run on Racket BC, but there is one consistent failure on Racket CS and sometimes the tests hang completely on Racket CS.

The one consistent failure (with the message "test: busy wait: pair send") probably does not indicate a real problem. It's attempting to test that waiting sockets don't wake up too often. But it does that by intercepting log messages, and I can imagine that interacting differently with the scheduler differently on CS. I'll rewrite that test.

The hangs seem to involve the ZMQ "draft" APIs, which have a more complicated synchronization mechanism. I'll double-check my code for bugs using the FFI or unsafe-poller early next week.

I discovered that if I edit zeromq-r-lib/private/ffi.rkt, run the tests, and then comment out the change (reverting to the previous behavior but not identically the previous source), and run the tests again, they hang in client-server.rkt. Then if I interrupt with Ctrl-C, Racket prints a corrupted stack trace. Might be my fault, another consequence of whatever bug causes the test to hang, but just in case it isn't, here's an example:

    ryan@nettle:~$ LD_LIBRARY_PATH=/opt/r/zeromq-4.3.3/lib /tmp/ryan/racket/bin/raco test -c zeromq/tests
    raco test: "/tmp/ryan/racket/share/pkgs/zeromq-r/tests/client-server.rkt"
    ^Cuser break
      context...:
       /tmp/ryan/racket/share/pkgs/compiler-lib/compiler/commands/test.rkt:139:4: go
       /tmp/ryan/racket/share/pkgs/compiler-lib/compiler/commands/test.rkt:490:3
       /tmp/ryan/racket/share/pkgs/compiler-lib/compiler/commands/test.rkt:370:27
       /tmp/ryan/racket/share/pkgs/compiler-lib/compiler/commands/test.rkt:372:0: call-with-summary
       .../private/map.rkt:40:19: loop
       /tmp/ryan/racket/share/pkgs/compiler-lib/compiler/commands/test.rkt:372:0: call-with-summary
       .../private/map.rkt:40:19: loop
       user break/tmp/ryan/racket/share/pkgs/compiler-lib/compiler/commands/test.rkt
      context...:
       :372:0: call-with-summary
       /tmp/ryan/racket/share/pkgs/ze.../private/map.rktromq-r/tests/client-server.rkt:39::400
       body of "/tmp/ryan/racket/share/pkgs/zeromq-r/tests/client-server.rkt":19
       : loop/tmp/ryan/racket/share/pkgs/compiler-lib/compiler/commands/test.rkt
    :   77.../racket/:cmdli2ne.rkt
    :191: 51  
       body of (submod "/tmp/ryan/racket/share/pkgs/cobody of "/tmp/ryan/racket/share/pkgs/compiler-lib/compiler/commands/test.rkt"mpile
       r-lib/compiler/commands/test.rkt" process)
       body of top-level
    /tmp/ryan/racket/collects/raco/raco.rkt:41:0
       body of "/tmp/ryan/racket/collects/raco/raco.rkt"
       body of "/tmp/ryan/racket/collects/raco/main.rkt"

**Comment by samth** [comment]
`runomatic` was fixed to have the correct dependency since the last release pkg-build.

**Comment by mflatt** [comment]
@rmculpepper That output looks to me like "user break" error output from two threads interleaved.

**Comment by samth** [comment]
There's a new test failure in gtp-benchmarks: https://plt.eecs.northwestern.edu/release-pkg-build/server/built/test-fail/gtp-benchmarks.txt

cc @bennn

**Comment by jbclements** [comment]
Looks like there are no changes to the gtp-benchmarks code since 2018, is that right?

**Comment by samth** [comment]
gtp-benchmarks and zeromq-r are now fixed. quickscript-test has a fix on master which I assume will get merged to the release. rwind is not a real problem. 

That leaves `sass`, which I still don't understand. The package installs fine and passes all tests, on both regular and natipkg distributions, on my machine.

**Comment by jbclements** [comment]
Closing this, 7.9 is released.
