### ISSUE TITLE
duplicated syntax properties on for/set

### ISSUE THREAD

**Issue by howell** [racket/racket#3452]
**What version of Racket are you using?**
7.9.0.3 [cs] and reproduced with 7.9.0.3 [bc] (a HEAD build from yesterday afternoon)

**What program did you run?**

```racket
#lang racket

(require (for-syntax syntax/parse))

(define-syntax (loop/prop stx)
  (syntax-parse stx
    [(_ loop stuff ...)
     (define before (syntax-property #'(loop stuff ...) 'hi 'mom))
     (define after (local-expand before 'module '()))
     (println (syntax-property after 'hi))
     #'(void)]))

;; for/list does what I expect, prints 'mom
(loop/prop for/list ([x (list)]) x)
;; for/set instead prints '(mom . mom)
(loop/prop for/set ([x (list)]) x)
```

(note: I'm using local-expand here to actually get my hands on the syntax property post-expansion, using the macro stepper I observed the same behavior without local-expanding).

**What should have happened?**
the value of the `'hi` syntax property on the `after` syntax object should just be `'hi`

**Please include any other relevant details**
I see this behavior on macOS 10.15.6 and haven't tried any others

**Comment by yjqww6** [comment]
I see this behavior actually comes from struct constructors, which redundantly copies syntax properties and then causes them to be merged via cons.
```
#lang racket

(struct ss ())

(syntax-property (expand (syntax-property
                            #'(ss)
                            'hi 'mom))
                   'hi)
```
https://github.com/racket/racket/blob/a5b69b6594028673d729d8f439374f839005a06b/racket/collects/racket/private/define-struct.rkt#L76-L85

**Comment by samth** [comment]
In general, syntax properties can always appear as a tree of `cons` cells, and you shouldn't assume that they only appear once. See the discussion here: https://docs.racket-lang.org/reference/stxprops.html

**Comment by jackfirth** [comment]
Is there a point to this particular duplication though? It seems unnecessary.

**Comment by howell** [comment]
the behavior in this example still doesn't make a ton of sense to me, but I see that it is documented and possible to work around.
