### ISSUE TITLE
File won't compile with `raco make` using Racket CS

### ISSUE THREAD

**Issue by nmoroze** [racket/racket#3454]
**What version of Racket are you using?**
7.8 CS (tried with stable and prerelease)

**What program did you run?**
I don't have a minimal example for this, but I was trying to compile the file in this [gist](https://gist.github.com/nmoroze/99f9e51e54933601ad7976873aeb13e6) (which is a fairly large, autogenerated file using a custom `#lang`). 

Compiling this file requires https://github.com/anishathalye/rtl, which itself requires Rosette.

**What should have happened?**
I expect that compiling this file with `raco make` would successfully generate bytecode, since the file can be run directly with `racket`. However, `raco make` fails with an error. This issue only seems to occur with Racket CS, it works as expected using standard Racket 7.8. 

**If you got an error message, please include it here.**
With CS prerelease, the error message is:
```
$ ~/racket-cs-prerelease/bin/raco make opentitan.rkt
#<procedure>: arity mismatch;
 the expected number of arguments does not match the given number
  expected: 1
  given: 2
  compilation context...:
   /home/noah/shiva-opentitan/opentitan.rkt
  context...:
   /home/noah/racket-cs-prerelease/collects/compiler/private/cm-minimal.rkt:608:0: compile-zo*
   /home/noah/racket-cs-prerelease/collects/compiler/private/cm-minimal.rkt:407:15
   /home/noah/racket-cs-prerelease/collects/compiler/private/cm-minimal.rkt:396:12: build
   /home/noah/racket-cs-prerelease/collects/compiler/private/cm-minimal.rkt:372:0: maybe-compile-zo
   /home/noah/racket-cs-prerelease/collects/compiler/private/cm-minimal.rkt:206:0: compile-root
   /home/noah/racket-cs-prerelease/collects/compiler/private/cm-minimal.rkt:102:4
   /home/noah/racket-cs-prerelease/share/pkgs/compiler-lib/compiler/commands/make.rkt:69:0
   body of "/home/noah/racket-cs-prerelease/share/pkgs/compiler-lib/compiler/commands/make.rkt"
   /home/noah/racket-cs-prerelease/collects/raco/raco.rkt:41:0
   body of "/home/noah/racket-cs-prerelease/collects/raco/raco.rkt"
   body of "/home/noah/racket-cs-prerelease/collects/raco/main.rkt"
```

With the stable release, I get a slightly different trace:
```
#<procedure>: arity mismatch;
 the expected number of arguments does not match the given number
  expected: 1
  given: 2
  compilation context...:
   /Users/noah/Research/shiva-opentitan/opentitan.rkt
  context...:
   make-arity-exn
   do-raise
   dynamic-wind
   start
   dynamic-wind
   do-compile-to-port
   dynamic-wind
   compile*-to-bytevector
   make-jit-on-call
   jitify-expr
   jitify-let
   jitify-expr
   jitify-top-expr
   loop
   [repeats 2 more times]
   thunk
```

**Please include any other relevant details**
I tested this on MacOS 10.15.6 as well as Arch Linux. 

Thanks for taking a look!

**Comment by mflatt** [comment]
Thanks! As expected, the problem appears to be related to serializing a large module, and I should be able to push a repair soon.
