### ISSUE TITLE
CI failure in Chez tests

### ISSUE THREAD

**Issue by pmatos** [racket/racket#3458]
Test failure: https://github.com/racket/racket/runs/1295337443#step:9:200
Possibly introduced by: https://github.com/racket/racket/commit/614992a65c26a267d4c95dbe7057b17476a9f45a

**Comment by pmatos** [comment]
After a closer look, problematic commit is probably: https://github.com/racket/racket/commit/0a6b8356c1ce489ce60eee22d4b0c5d8fdac8f1e

**Comment by mflatt** [comment]
I doubt that the commit is relevant. I've seen the test fail occasionally, but never investigated enough. Commit 9caa0554bc42c1bb7d4920c66718d8a211abee87 repairs a race in the test.

**Comment by pmatos** [comment]
This looks fixed to me. Closing, thanks.
