### ISSUE TITLE
Reorganize CS Make flags

### ISSUE THREAD

**Issue by pmatos** [racket/racket#3467]
Ref: https://github.com/racket/racket/pull/3466

We should reorganize the CS Make flags, so that they are not added in addition to CFLAGS, but are just defaults that are overwritten by CFLAGS.

**Comment by xxyzz** [comment]
Like this?

```
# ChezScheme/config file:
warningFlags="-Wpointer-arith -Wall -Wextra -Werror -Wno-implicit-fallthrough"
optFlags=-O2
: ${CFLAGS:=${warningFlags} ${optFlags}}

# Mf-* files: 
CFLAGS+=" -pthread"
C = ${CC} ${CPPFLAGS} ${CFLAGS}
CFLAGS+=" -m32"
    (cd ../zlib; ${SetConfigEnv} CFLAGS=${CFLAGS}" ./configure)
```

**Comment by mflatt** [comment]
Your example make sense as a minimal change, but I think a bigger rewrite is in order.

To bring things better in line with Racket's `configure` (i.e., a more typical `configure`), I'm going to try moving more details from `Mf-*` to `configure` and allowing things to be overridden more consistently.
