### ISSUE TITLE
BC/CS timezone offset difference

### ISSUE THREAD

**Issue by willghatch** [racket/racket#3474]
**What version of Racket are you using?**
7.8 [cs]

**What program did you run?**

```
#lang racket/base
(date-time-zone-offset (seconds->date -67768040609715604))
```

**What's the problem?**
It returns a different value, off by 4, for BC and CS.  It requires a big number for seconds, or CS gives the same result that BC does.  It also only happens when using local time -- the default when not providing a second argument to `seconds->date`.

**Please include any other relevant details**
Tested on Linux (Ubuntu and NixOS).

This bug brought to you by Xsmith.

**Comment by mflatt** [comment]
The differing result appears to be a difference between using `tm_gmtoff` in `struct tm` (as used by Chez Scheme) versus using `timezone` (as used by BC via rktio).

Using the `tm_gmtoff` field seems better, and as far as I can tell, it's always. going to be available on Linux. I'll investigate more, but probably change the Linux configuration of rktio.
