### ISSUE TITLE
BC/CS downcase difference

### ISSUE THREAD

**Issue by willghatch** [racket/racket#3475]
**What version of Racket are you using?**
7.8 [cs]

**What program did you run?**

```
#lang racket/base
(string-downcase   "ẞß")
```

RacketCS returns a string with two of the second character, while RacketBC returns the original string (depending on your font the two characters may look the same, but they are different code points).  I thought this might be the same issue as with [titlecase](https://github.com/racket/racket/issues/3440), but @mflatt suggested that it's likely a different bug.

I'm not sure if this generalizes, I've only seen a difference with this particular character.

**Please include any other relevant details**
Run on Linux (Ubuntu and NixOS).

This bug brought to you by Xsmith.

**Comment by mflatt** [comment]
This is a bug in Racket BC. In building up conversion tables, information from "SpecialCasing.txt" data was incorrectly merged with data from "UnicodeData.txt" so that not-quite-so-special casings were fumbled.
