### ISSUE TITLE
rename-in is slow compare to correspoding raw-require-spec

### ISSUE THREAD

**Issue by yjqww6** [racket/racket#3476]
**What version of Racket are you using?**
7.8 [cs]

**What program did you run?**
```racket
#lang racket

(parameterize ([current-namespace (make-base-namespace)])
  (expand '(module a racket/gui))
  
  (collect-garbage)
  (time
   (expand '(module a racket/base
              (#%require (rename racket/gui f% frame%)
                         (all-except racket/gui frame%))))
   (void))

  (collect-garbage)
  (time
   (expand '(module a racket/base
              (require (rename-in racket/gui
                                  [frame% f%]))))
   (void))

  
  (collect-garbage)
  (time
   (expand '(module a racket/base
              (#%require (all-except racket/gui frame%))))
   (void))

  (collect-garbage)
  (time
   (expand '(module a racket/base
              (require (except-in racket/gui frame%))))
   (void))
)
```
outputs
```
cpu time: 59 real time: 60 gc time: 11
cpu time: 113 real time: 114 gc time: 23
cpu time: 59 real time: 59 gc time: 11
cpu time: 65 real time: 66 gc time: 10
```
**What should have happened?**
I think `rename-in` should have minimal overhead for such simple forms, like `except-in`.
Although the difference is just 60ms in this example, it would be significant if we have so many files to compiled.

**If you got an error message, please include it here.**

**Please include any other relevant details**
I see in "reqprov.rkt", there is a fast path for `except-in`, but not for `rename-in`.

**Comment by jackfirth** [comment]
@yjqww6 Is it slow in both racket BC and racket CS? Or only in CS?

**Comment by yjqww6** [comment]
@jackfirth didn't try BC. Since rename-in is implemented as a require transformer, BC probably has same problem.
