### ISSUE TITLE
[CS] ill-formed call of "format" fails with "division by zero" error

### ISSUE THREAD

**Issue by rgherdt** [racket/racket#3481]
**What version of Racket are you using?**
7.8 [cs]

**What program did you run?**
(printf "~a")
(format "~a")

**What should have happened?**
A better error message, as in 7.8 BC:
format: format string requires 1 arguments, given 0; arguments were: "~a"

**If you got an error message, please include it here.**
 /: division by zero

**Please include any other relevant details**
I installed racket 7.8 cs manually on Debian 10 (Buster).

**Comment by sorawee** [comment]
This bug has already been fixed at https://github.com/racket/racket/commit/100597f9bbf7b47f488026b6f68bc3d6da46e6d3#diff-f1ad02ab7ccb2750d7556a8ced08044d8b46265e9f8330b7edca2b639b12ba06, so I will close the issue.

**Comment by mflatt** [comment]
But also: Thanks for taking the time to report a bug!

**Comment by sorawee** [comment]
Actually, I just noticed that in the new CS error message, the error is different from that of BC. `; arguments were: "~a"` is missing.

The information `arguments were: "~a"` in BC seems useful, so I think CS should include it too. However, I don't like the off by one error in BC (how it says "given 0" but at the same time also says `arguments were: "~a"`)

The problem in BC is that we overload the term "arguments". One is arguments in a general function call. Another is arguments of a `format` call where the format string is implicitly not counted.

CC: @samth

**Comment by sorawee** [comment]
On a second thought, CS behavior is consistent. BC should be changed at match CS.
