### ISSUE TITLE
[CS] some unused bindings don't get optimized away

### ISSUE THREAD

**Issue by Bogdanp** [racket/racket#3487]
**What version of Racket are you using?**
CS HEAD

**What program did you run?**

When I run

```racket
(require racket/match)

(struct st (x))
(define a (st 42))

(collect-garbage)
(collect-garbage)
(collect-garbage)

(time
 (for ([x 100000000])
   (match a
     [(? st?) 'ok])))

(collect-garbage)
(collect-garbage)
(collect-garbage)

(time
 (for ([x 100000000])
   (match a
     [(st _) 'ok])))

(collect-garbage)
(collect-garbage)
(collect-garbage)

(time
 (for ([x 100000000])
   (let ([a1 (st-x a)])
     'ok)))
```

I get the following timings:

```
cpu time: 162 real time: 174 gc time: 0
cpu time: 230 real time: 242 gc time: 0
cpu time: 174 real time: 186 gc time: 0
```

**What should have happened?**

I would have expected the unused binding in the second match clause to be optimized away, but it doesn't seem to be. When I run the same program on [this branch](https://github.com/racket/racket/compare/master...Bogdanp:optimize-struct-match), which changes `match` to eliminate unused wildcard bindings, I get the following timings:

```
cpu time: 148 real time: 159 gc time: 0
cpu time: 152 real time: 164 gc time: 0
cpu time: 177 real time: 189 gc time: 0
```

According to @samth, the binding seems to be optimized away on Racket BC. It seems like CS ought to be able to apply the same optimization.

**Comment by mflatt** [comment]
I think the main CS issue here is that `unsafe-struct-ref` is slower than a safe reference (while `unsafe-struct*-ref` is faster), I expect that can be improved easily.

I see that BC optimizes away `unsafe-struct-ref`, but I'm not certain that it should, since an impersonator can interpose on `unsafe-struct-ref`.

**Comment by Bogdanp** [comment]
That makes sense, thanks. In that case should `match` also be changed so as to not generate these references altogether or should clauses like `(st _)` trigger an impersonator on the first field? I'd find the latter surprising and it seems like the documentation for match agrees that it shouldn't bind anything in this case:

> _ — matches anything, without binding any identifiers.

So the reason match isn't doing this already might be because it was previously relying on BC to do that work for it.

**Comment by mflatt** [comment]
Along the same lines as dropping `unsafe-struct-ref`, BC drops `(when (st? v) (st-x v))` when the result is unused. Similarly, it will drop `(when (box? x) (unbox x))`. So, BC doesn't generally guarantee that accessors will be applied and trigger interposition.

I can imagine that more code depends on BC's implementation, so I'm not yet sure of a conclusion here.

**Comment by mflatt** [comment]
My current conclusion is that it makes sense to change BC. It helps that the change is easy: just means removing "ok to drop" flags on `unsafe-vector-ref`, `unsafe-unbox`, and `unsafe-struct-ref`. Other effects, such as dropping uses of struct accessors, were a result of compiler transformations to those operations. Naturally, an accessor for an authentic struct type boils down to `unsafe-struct*-ref`, and that's still marked as "ok to drop".

Meanwhile, `unsafe-struct-ref` is already implemented in the CS the way I expected, after all. The variation in times seems to have more to do with the fine details of machine-code generation — maybe small branch-distance differences or having a structure type in a closure versus loading it as an immediate that is installed by the linker.

**Comment by mflatt** [comment]
This can be closed because we concluded that CS shouldn't change, and `match` is now improved — right?

**Comment by Bogdanp** [comment]
Yup, closing. Thanks!
