### ISSUE TITLE
Error location uses . instead of :

### ISSUE THREAD

**Issue by sorawee** [racket/racket#3492]
### What version of Racket are you using?

version 7.9.0.3--2020-08-02

### What program did you run?

```
#lang typed/racket
let
```

### What should have happened?

In `#lang racket`, the error message is:

```
unsaved editor:2:0: let: bad syntax in: let
```

In `#lang typed/racket`, the error message is:

```
unsaved editor:2.0: let: bad syntax in: let
```

Notice the use of `.` to separate line and column, which does not follow the error location convention.

**Comment by rmculpepper** [comment]
The dot comes from `source-location->prefix` (from `syntax/srcloc`), which `syntax/parse` uses to format the location. I don't know why it uses a dot, but the tests indicate that it was intentional. I wouldn't object to changing it, but I don't know who else might care about the current formatting.

**Comment by sorawee** [comment]
Would it make sense to have a parameter controlling the printing style? It could default to `.`, but clients like `syntax-parse` would set the parameter so that it prints `:`.

**Comment by mflatt** [comment]
I'll change `syntax/srcloc` to use `:`, and we can see what breaks.

**Comment by mflatt** [comment]
So far, I found only one test (not specifically for `syntax/srcloc`) that needed to be updated. There may be more probably when we get to building all packages, but the limited impact so far make me think this change will be ok. Closing for now.
