### ISSUE TITLE
Racket crash when file path is too long?

### ISSUE THREAD

**Issue by chansey97** [racket/racket#3493]
**What version of Racket are you using?**
Racket v7.9 [bc]

**What program did you run?**

Reproduce steps:

1. Create a `file.rkt`

    ```
    #lang racket/base

    "hello, world"
    ```
2. Copy this file to, for example, 

    `C:\Users\Chansey\xxx` 

    and 

    `C:\Users\Chansey\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`
   
3.  In windows command prompt

    ```
    Microsoft Windows [Version 6.1.7601]
    Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

    C:\Users\Chansey>cd xxx

    C:\Users\Chansey\xxx>racket file.rkt
    "hello, world"

    C:\Users\Chansey\xxx>raco expand file.rkt
    (module file racket/base
      (#%module-begin
       (module configure-runtime '#%kernel
         (#%module-begin (#%require racket/runtime-config) (#%app configure '#f)))
       (#%app call-with-values (lambda () '"hello, world") print-values)))
    ```
    It works fine, but if you type:

    ```
    C:\Users\Chansey\xxx>cd ../xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

    C:\Users\Chansey\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx>racket file.rkt
    ```

    Racket crash!

    If you type:
    ```
    C:\Users\Chansey\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx>>raco expand file.rkt
    ```

    It doesn't print anything and create a `raco` file in C:\Users\Chansey\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

    The `raco` file's content is 

    ```
    Microsoft (R) File Expansion Utility  Version 6.1.7600.16385
    Copyright (c) Microsoft Corporation. All rights reserved.
    
    No destination specified for: file.rkt.
    ```

**What should have happened?**

    `racket file.rkt` should not crash.

    `raco expand file.rkt` should print correct message.

**If you got an error message, please include it here.**
Crash dialog box:
![Capture](https://user-images.githubusercontent.com/4015056/98717404-0177ec80-23c8-11eb-8147-c4af9a2147e7.PNG)

**Please include any other relevant details**
So the issue doesn't seem to be so much where the file is and how long its pathname is. Instead the issue seems to be with Racket running when the current directory is so "deep" and "long".

For example, the following command line works fine:

```
C:\Users\Chansey>racket C:\Users\Chansey\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\file.rkt
"hello, world"

C:\Users\Chansey>raco expand C:\Users\Chansey\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\file.rkt
(module file racket/base
  (#%module-begin
   (module configure-runtime '#%kernel
     (#%module-begin (#%require racket/runtime-config) (#%app configure '#f)))
   (#%app call-with-values (lambda () '"hello, world") print-values)))
```

My testing operating system is Windows 7, but Windows 10 seems has the same problem.

Related issue: https://github.com/greghendershott/racket-mode/issues/505

**Comment by mflatt** [comment]
Thanks for the report!

This problem seems to afflict MinGW-based Racket builds, but not MSVC-based Racket builds. If correct, that doesn't mean that it's an MinGW problem, necessarily — probably just the way Racket is implemented via MinGW.

Do you get different behavior if you use a Utah snapshot build, which (unlike other builds) uses MSVC? https://www.cs.utah.edu/plt/snapshots/

**Comment by chansey97** [comment]
I installed https://www.cs.utah.edu/plt/snapshots/current/installers/racket-7.9.0.4-x86_64-win32-bc.exe

It has the same problem:

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Chansey>racket --version
Welcome to Racket v7.9.0.4 [bc].

C:\Users\Chansey>cd C:\Users\Chansey\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

C:\Users\Chansey\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx>racket file.rkt

C:\Users\Chansey\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx>raco expand file.rkt
```

`racket file.rkt` crash.

`raco expand file.rkt` doesn't print anything as well (the slight difference is it doesn't create a `raco` file).

**Comment by mflatt** [comment]
Thanks! I guess the difference I was seeing was random luck. Now I see the problem, and it would be the same for both compilers.

**Comment by mflatt** [comment]
This should be fixed in the latest snapshots: https://snapshot.racket-lang.org/

**Comment by chansey97** [comment]
I tested https://www.cs.utah.edu/plt/snapshots/current/installers/racket-7.9.0.5-x86_64-win32-bc.exe

This issue has been fixed!

Thanks.

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Chansey>racket -v
Welcome to Racket v7.9.0.5 [bc].

C:\Users\Chansey>cd C:\Users\Chansey\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

C:\Users\Chansey\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx>racket file.rkt
"hello, world"

C:\Users\Chansey\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx>raco expand file.rkt
(module file racket/base
  (#%module-begin
   (module configure-runtime '#%kernel
     (#%module-begin (#%require racket/runtime-config) (#%app configure '#f)))
   (#%app call-with-values (lambda () '"hello, world") print-values)))

C:\Users\Chansey\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx>
```
