### ISSUE TITLE
After updating to Racket 7.9 Raco is unable to install packages

### ISSUE THREAD

**Issue by wsgac** [racket/racket#3499]
**What version of Racket are you using?**
7.9

**What program did you run?**
I updated from Racket 7.8 to 7.9 and, as usual, started by reinstalling the packages I was using before. I ran `raco pkg install beautiful-racket`

**What should have happened?**
Normally, the installation process would start at this point.

**If you got an error message, please include it here.**
I got the following error message:
```
$ raco pkg install beautiful-racket
Resolving "beautiful-racket" via https://download.racket-lang.org/releases/7.9/catalog/
raco pkg install: cannot find package on catalogs
  package: beautiful-racket
```

**Please include any other relevant details**
After seeing the error message above I visited `https://download.racket-lang.org/releases/7.9/catalog/` and saw the following:
```
> ((uncaught-exception-handler)    (*(+(*)(*(+(*)(*)(*)(*)(*))(+(*)(*)(*)(*)(*))(+(*)(*)(*)(*))))(+(*)(*)(*)(*)))) uncaught exception: 404
```
Seems like the `7.9` package catalog is unavailable for some reason.

I'm running `Ubuntu 20.04.1 LTS`, but this seems to be OS-independent.

**Comment by mflatt** [comment]
For now, please see https://groups.google.com/g/racket-users/c/aOJPcvoJrk8/m/WEVqAFlmAgAJ

We are in the process of updating the v7.9 source distribution to fix this problem.

**Comment by wsgac** [comment]
Thanks a lot! That helped. Do you want me to keep this issue open until this gets resolved?

**Comment by mflatt** [comment]
Yes, keeping it open is a good idea, in case someone else hits the problem before we get it fixed (although that's hopefully very soon).

**Comment by mflatt** [comment]
Distributions are now fixed.
