### ISSUE TITLE
Misreading characters #\U00<digit16>{5,6}

### ISSUE THREAD

**Issue by dvanhorn** [racket/racket#3507]
The reader misreads inputs of the form `#\U00<digit16>{5,6}`.  It appears to be "skipping" over the leading zeros and interpreting the remaining digits as part of the character.

For example the text `(#\U000000 A)` should read the same as `(#\U000000A)`: `(#\nul A)`, but the reader sees the latter as `(#\U00000A)`, i.e. `(#\newline)`.  Likewise for `(#\U0000000A)`.

**What version of Racket are you using?**
7.9

**What program did you run?**
`(with-input-from-string "(#\\U000000A)" read)` => `(#\newline)`
`(with-input-from-string "(#\\U0000000A)" read)` => `(#\newline)`

**What should have happened?**
`(with-input-from-string "(#\\U000000A)" read)` => `(#\nul A)`
`(with-input-from-string "(#\\U0000000A)" read)` => `(#\nul 0A)`

**If you got an error message, please include it here.**

**Please include any other relevant details**
e.g., the operating system used or how you are running the code.

**Comment by mflatt** [comment]
I think the problem here is again documentation (although also a bad choice in the implementation): up to 8 hex digits are allowed, instead of up to 6.

**Comment by dvanhorn** [comment]
Sounds good to me; although now I notice DrRacket it out of sync with this.  It colors `#\U000000AA` with `AA` in blue instead of green.  I can submit an issue there.

**Comment by mflatt** [comment]
Documentation corrected in b28d682.
