### ISSUE TITLE
Allow (system-type 'os) to distinguish BSD (or unix) from Linux.

### ISSUE THREAD

**Issue by Parakleta** [racket/racket#3510]
**What version of Racket are you using?**
7.8

**Please include any other relevant details**

Currently (system-type 'os) only distinguishes 'unix, 'windows' and 'macosx, but in fact Linux is different from 'unix (regularly not following the OpenGroup standards) whereas the BSDs and other Unices do.  In fact, in many ways 'macosx is closer to the OpenGroup standards than Linux is.

I know its likely too late now to take back the 'unix symbol for true unicies and create a 'linux symbol, but would it be possible to add some other symbol to differentiate the non-linux unicies?

**Comment by mflatt** [comment]
We have mostly used `(system-library-subpath #f)` for that kind of distinction. It combines OS and architecture, though.

**Comment by Parakleta** [comment]
I can use a suffix test on that well enough, but it feels a bit clumsy and a bit like I'm peeking behind the curtain to make it work.  Is it possible to have that codified in the documentation as a safe method to use, and list the current definitions (and perhaps a convenient library method to extract just the OS)?

**Comment by mflatt** [comment]
Yes, this is an overdue improvement. I'll add `(system-type 'os*)` to provide more specific OS information and `(system-type 'arch)` to provide the architecture separately.
