### ISSUE TITLE
[Feature Request] Support for Apple M1

### ISSUE THREAD

**Issue by j3parker** [racket/racket#3513]
Is there a central issue to track support for [Apple M1](https://www.apple.com/mac/m1/)?

Ultimately it would be good to have that as an option [on the download page](https://download.racket-lang.org).

At a glance it looks like the JIT supports 32-bit ARM but not AArch64.

**Comment by j3parker** [comment]
By the way, it seems both racket and DrRacket segfault immediately under Rosetta (version 7.9).

**Comment by samth** [comment]
There is already support for aarch64, see https://blog.racket-lang.org/2020/08/racket-v7-8.html.

Once we have build machines, a subsequent release (and before that, snapshot builds) will support macOS on aarch64. 

It would be great to find out what happens when you build Racket from source on an M1-based machine.

**Comment by j3parker** [comment]
Ah, fantastic. Ok, I'll give that a try.

**Comment by samth** [comment]
Also, more information about the failures under Rosetta would be great, as well as checking if Racket CS also crashes.

**Comment by mbutterick** [comment]
On a Macbook Air M1, I can’t get anywhere with `make` or `make cs`. I immediately get a welter of errors along these lines:

```
/path/racket/racket/src/build/../foreign/libffi/src/arm/sysv.S:64:1: error: unexpected token at start of statement
@ This selects the minimum architecture level required.
^
/path/racket/racket/src/build/../foreign/libffi/src/arm/sysv.S:112:1: error: unknown directive
.syntax unified
^
/path/racket/racket/src/build/../foreign/libffi/src/arm/sysv.S:145:2: error: unexpected token at start of statement
 @ r0: ffi_prep_args
 ^
/path/racket/racket/src/build/../foreign/libffi/src/arm/sysv.S:146:2: error: unexpected token at start of statement
 @ r1: &ecif
 ^
/path/racket/racket/src/build/../foreign/libffi/src/arm/sysv.S:147:2: error: unexpected token at start of statement
 @ r2: cif->bytes
 ^
```

About 64 of these errors total.

**Comment by mflatt** [comment]
Thanks! I expect the M1 that I ordered to arrive this week, and things will start working sometime after that.

**Comment by mbutterick** [comment]
See https://github.com/strukturag/libde265/issues/116 for possibly related issue:

> You must set arch flag to tell compiler to compile for ARM instead of x86: "-arch armv7"

**Comment by mbutterick** [comment]
[FWIW](https://stackoverflow.com/a/21771160): “that's armv7 assembly which an arm64 assembler will reject as invalid”

Perhaps it’s possible that the `libffi/src/arm` subdirectory contains armv7 assembly, which is incorrectly being invoked by `make` in this case? I notice the `libffi/src` directory has another subdirectory called `aarch64` — perhaps this is the right one? I should’ve posted the `make` output just before the errors:

```
make[11]: `../libmzgc.a' is up to date.
/Applications/Xcode.app/Contents/Developer/usr/bin/make foreign-stuff
cd ../foreign; /Applications/Xcode.app/Contents/Developer/usr/bin/make all
/Applications/Xcode.app/Contents/Developer/usr/bin/make foreign.o
make[12]: `foreign.o' is up to date.
/Applications/Xcode.app/Contents/Developer/usr/bin/make libffi_ON
/Applications/Xcode.app/Contents/Developer/usr/bin/make libffi/libffi.la
cd libffi; /Applications/Xcode.app/Contents/Developer/usr/bin/make libffi.la
depbase=`echo src/arm/sysv.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ./libtool    --mode=compile gcc -DHAVE_CONFIG_H -I. -I/path/to/racket/racket/src/build/../foreign/libffi  -I. -I/path/to/racket/racket/src/build/../foreign/libffi/include -Iinclude -I/path/to/racket/racket/src/build/../foreign/libffi/src  -I. -I/path/to/racket/racket/src/build/../foreign/libffi/include -Iinclude -I/path/to/racket/racket/src/build/../foreign/libffi/src  -MT src/arm/sysv.lo -MD -MP -MF $depbase.Tpo -c -o src/arm/sysv.lo /path/to/racket/racket/src/build/../foreign/libffi/src/arm/sysv.S &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/path/to/racket/racket/src/build/../foreign/libffi -I. -I/path/to/racket/racket/src/build/../foreign/libffi/include -Iinclude -I/path/to/racket/racket/src/build/../foreign/libffi/src -I. -I/path/to/racket/racket/src/build/../foreign/libffi/include -Iinclude -I/path/to/racket/racket/src/build/../foreign/libffi/src -MT src/arm/sysv.lo -MD -MP -MF src/arm/.deps/sysv.Tpo -c /path/to/racket/racket/src/build/../foreign/libffi/src/arm/sysv.S  -fno-common -DPIC -o src/arm/.libs/sysv.o
```

**Comment by mflatt** [comment]
If you're interested in moving this along, we can try. What does `uname -a` say?

**Comment by mbutterick** [comment]
Only if it’s useful information. Just didn’t want to leave an opaque report. No rush of course.

`uname -a`:

```
Darwin Matthews-MacBook-Air.local 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:10 PDT 2020; root:xnu-7195.50.7~2/RELEASE_ARM64_T8101 arm64
```

**Comment by mflatt** [comment]
In `racket/src/bc/foreign/libffi/configure`, you could try changing the line `aarch64*-*-*)` to `aarch64*-*-*|arm64*-*-*)`. Delete the `build` directory just to make sure `configure` re-runs.

(Even if this works, you're going to end up with a slow Racket BC without a JIT!)

**Comment by mbutterick** [comment]
Oops, turns out my Racket fork was inadvertently behind `upstream`. I just updated to 31d0c07d3754c0e190a45a3000329a89b8d35d08 and ran `make` again (without making the suggested adjustment) and got a different error:

```
make[7]: `Makefile' is up to date.
cd racket/src/build/cs/c && /Applications/Xcode.app/Contents/Developer/usr/bin/make CS_HOST_WORKAREA_PREFIX=""
/Applications/Xcode.app/Contents/Developer/usr/bin/make scheme
mkdir -p ChezScheme
if [ "./raw_racketcs" != "./raw_racketcs" ] ; \
          then /Applications/Xcode.app/Contents/Developer/usr/bin/make scheme-via-rktboot BOOTFILE_RACKET="./raw_racketcs" ; \
          else /Applications/Xcode.app/Contents/Developer/usr/bin/make scheme-via-pb ; fi
/bin/sh ../../../cs/c/check_boot.sh tarm32osx "../../../cs/c/../../ChezScheme" ChezScheme
if [ -f boot_pending ] ; then /Applications/Xcode.app/Contents/Developer/usr/bin/make pb-bootquick ; fi
/Applications/Xcode.app/Contents/Developer/usr/bin/make config-scheme MACH=pb CONFIG_SCHEME_MODE=--pb
cd ChezScheme && "../../../../cs/c/../../ChezScheme"/configure --pb --machine=tarm32osx --disable-x11  --disable-auto-flags --enable-warning-flags  CC="gcc" CFLAGS="-g -O2 -Wall   -DOS_X" LDFLAGS="-Wl,-headerpad_max_install_names" LIBS="-ldl -lm  -lncurses -framework CoreFoundation -liconv" AR="ar" ARFLAGS="rc" RANLIB="ranlib" WINDRES="windres"
Configuring for pb
Unrecognized machine name tarm32osx
../../../../cs/c/../../ChezScheme/configure: line 673: pb/Makefile: No such file or directory
../../../../cs/c/../../ChezScheme/configure: line 675: pb/Mf-boot: No such file or directory
../../../../cs/c/../../ChezScheme/configure: line 679: pb/Mf-install: No such file or directory
../../../../cs/c/../../ChezScheme/configure: line 695: pb/c/next_config.h: No such file or directory
../../../../cs/c/../../ChezScheme/configure: line 707: pb/c/next_config.h: No such file or directory
mv: rename pb/c/next_config.h to pb/c/config.h: No such file or directory
../../../../cs/c/../../ChezScheme/configure: line 727: pb/c/Mf-config: No such file or directory
make[9]: *** [config-scheme] Error 1
make[8]: *** [pb-bootquick] Error 2
make[7]: *** [scheme-via-pb] Error 2
make[6]: *** [scheme] Error 2
make[5]: *** [cs] Error 2
make[4]: *** [cs-base] Error 2
make[3]: *** [cs-minimal-in-place] Error 2
make[2]: *** [plain-in-place] Error 2
make[1]: *** [in-place] Error 2
make: *** [main] Error 2
```

**Comment by mbutterick** [comment]
As for that error “Unrecognized machine name tarm32osx”: the symbol `tarm32osx` also appears in several lines of the log dropped at `racket/racket/src/build/cs/c/config.log` —

```
SCHEME_CONFIG_ARGS='--machine=tarm32osx --disable-x11  --disable-auto-flags --enable-warning-flags '
SCHEME_CROSS_CONFIG_ARGS='--machine=tarm32osx --disable-x11 --disable-auto-flags --enable-warning-flags  '
TARGET_MACH='tarm32osx'
MACH='tarm32osx'
```

**Comment by mflatt** [comment]
Yes, I'll have to fill in all that.

How about `make bc`?

**Comment by mbutterick** [comment]
`make bc` gets a little farther but then terminates with an error similar to the one I saw before (when I was using the outdated fork). An excerpt from the wipeout zone:

```
depbase=`echo src/arm/sysv.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ./libtool    --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../../../bc/foreign/libffi  -I. -I../../../../bc/foreign/libffi/include -Iinclude -I../../../../bc/foreign/libffi/src  -I. -I../../../../bc/foreign/libffi/include -Iinclude -I../../../../bc/foreign/libffi/src  -MT src/arm/sysv.lo -MD -MP -MF $depbase.Tpo -c -o src/arm/sysv.lo ../../../../bc/foreign/libffi/src/arm/sysv.S &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../../../bc/foreign/libffi -I. -I../../../../bc/foreign/libffi/include -Iinclude -I../../../../bc/foreign/libffi/src -I. -I../../../../bc/foreign/libffi/include -Iinclude -I../../../../bc/foreign/libffi/src -MT src/arm/sysv.lo -MD -MP -MF src/arm/.deps/sysv.Tpo -c ../../../../bc/foreign/libffi/src/arm/sysv.S  -fno-common -DPIC -o src/arm/.libs/sysv.o
../../../../bc/foreign/libffi/src/arm/sysv.S:64:1: error: unexpected token at start of statement
@ This selects the minimum architecture level required.
^
../../../../bc/foreign/libffi/src/arm/sysv.S:112:1: error: unknown directive
.syntax unified
^
../../../../bc/foreign/libffi/src/arm/sysv.S:145:2: error: unexpected token at start of statement
 @ r0: ffi_prep_args
 ^
```

… and so on.

**Comment by mflatt** [comment]
The `libffi` branch of `https://github.com/mflatt/racket` upgrades to the latest libffi. Any better?

You need to discard `build` again (as will everyone who builds Racket BC in a repo checkout if I push this upgrade).

**Comment by mbutterick** [comment]
Using eaaf6bac5dfbfb7f56f090eb688b62f2c9eeb4c9:

`make` (CS) still fails with the same error.

`make bc` gets farther but still fails:

```
/bin/sh ./libtool  --tag=CC   --mode=link gcc  -O3 -Wall -fexceptions -no-undefined -version-info `grep -v '^#' ../../../../bc/foreign/libffi/libtool-version`     -o libffi.la -rpath /Users/mb/git/racket/racket/lib src/prep_cif.lo src/types.lo src/raw_api.lo src/java_raw_api.lo src/closures.lo  src/arm/ffi.lo src/arm/sysv.lo 
libtool: link: gcc -dynamiclib  -o .libs/libffi.7.dylib  src/.libs/prep_cif.o src/.libs/types.o src/.libs/raw_api.o src/.libs/java_raw_api.o src/.libs/closures.o src/arm/.libs/ffi.o src/arm/.libs/sysv.o    -O3   -install_name  /Users/mb/git/racket/racket/lib/libffi.7.dylib -compatibility_version 9 -current_version 9.0 -Wl,-single_module
Undefined symbols for architecture arm64:
  "_ffi_call", referenced from:
      _ffi_raw_call in raw_api.o
      _ffi_java_raw_call in java_raw_api.o
  "_ffi_closure_trampoline_table_page", referenced from:
      _ffi_closure_alloc in closures.o
  "_ffi_prep_cif_machdep", referenced from:
      _ffi_prep_cif_core in prep_cif.o
  "_ffi_prep_cif_machdep_var", referenced from:
      _ffi_prep_cif_core in prep_cif.o
  "_ffi_prep_closure_loc", referenced from:
      _ffi_prep_closure in prep_cif.o
      _ffi_prep_raw_closure_loc in raw_api.o
      _ffi_prep_raw_closure in raw_api.o
      _ffi_prep_java_raw_closure_loc in java_raw_api.o
      _ffi_prep_java_raw_closure in java_raw_api.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by xxyzz** [comment]
> ```
>Undefined symbols for architecture arm64:
>    "_ffi_call", referenced from:
>         _ffi_raw_call in raw_api.o
>...
> ```
It's the same error of this issue(https://github.com/libffi/libffi/issues/571#issuecomment-654646523).

**Comment by mflatt** [comment]
My machine is still a few days away, but I've pushed changes that allow BC and CS to compile — or, at least, cross compile on an Intel Mac. I can't try running it, so I doubt that the build works, yet.

**Comment by mbutterick** [comment]
Thanks — FWIW, using 3b262edfa0bcb771960f030e9783878d011fbd0d:

`make` (CS) fails with the same error as before:

```
Configuring for pb
Unrecognized machine name tarm32osx
../../../../cs/c/../../ChezScheme/configure: line 679: pb/Makefile: No such file or directory
../../../../cs/c/../../ChezScheme/configure: line 681: pb/Mf-boot: No such file or directory
../../../../cs/c/../../ChezScheme/configure: line 685: pb/Mf-install: No such file or directory
../../../../cs/c/../../ChezScheme/configure: line 701: pb/c/next_config.h: No such file or directory
../../../../cs/c/../../ChezScheme/configure: line 713: pb/c/next_config.h: No such file or directory
mv: rename pb/c/next_config.h to pb/c/config.h: No such file or directory
../../../../cs/c/../../ChezScheme/configure: line 733: pb/c/Mf-config: No such file or directory
```

`make bc` also fails with the same error as before:

```
/bin/sh ./libtool  --tag=CC   --mode=link gcc  -O3 -Wall -fexceptions -no-undefined -version-info `grep -v '^#' ../../../../bc/foreign/libffi/libtool-version`     -o libffi.la -rpath /Users/mb/git/racket/racket/lib src/prep_cif.lo src/types.lo src/raw_api.lo src/java_raw_api.lo src/closures.lo  src/arm/ffi.lo src/arm/sysv.lo 
libtool: link: gcc -dynamiclib  -o .libs/libffi.7.dylib  src/.libs/prep_cif.o src/.libs/types.o src/.libs/raw_api.o src/.libs/java_raw_api.o src/.libs/closures.o src/arm/.libs/ffi.o src/arm/.libs/sysv.o    -O3   -install_name  /Users/mb/git/racket/racket/lib/libffi.7.dylib -compatibility_version 9 -current_version 9.0 -Wl,-single_module
Undefined symbols for architecture arm64:
  "_ffi_call", referenced from:
      _ffi_raw_call in raw_api.o
      _ffi_java_raw_call in java_raw_api.o
  "_ffi_closure_trampoline_table_page", referenced from:
      _ffi_closure_alloc in closures.o
  "_ffi_prep_cif_machdep", referenced from:
      _ffi_prep_cif_core in prep_cif.o
  "_ffi_prep_cif_machdep_var", referenced from:
      _ffi_prep_cif_core in prep_cif.o
  "_ffi_prep_closure_loc", referenced from:
      _ffi_prep_closure in prep_cif.o
      _ffi_prep_raw_closure_loc in raw_api.o
      _ffi_prep_raw_closure in raw_api.o
      _ffi_prep_java_raw_closure_loc in java_raw_api.o
      _ffi_prep_java_raw_closure in java_raw_api.o
ld: symbol(s) not found for architecture arm64
```

I ran the commands twice, erasing the `build` directory (resetting the whole branch, actually) before each try. Same results.

**Comment by mflatt** [comment]
As a change of pace, here are some executable bundles that won't work instead of sources that won't work:
http://www.cs.utah.edu/~mflatt/tmp/racket-7.9.0.9-aarch64-macosx-bc.tgz
http://www.cs.utah.edu/~mflatt/tmp/racket-7.9.0.9-aarch64-macosx-cs.tgz

**Comment by mbutterick** [comment]
Thanks — the CS `racket` wouldn’t run (failed with message `Killed: 9`). 

The BC `racket` almost launched — then ran aground on the new, pickier security settings (“racket can’t be opened because Apple cannot check it for malicious software.”)

**Comment by sorawee** [comment]
> The BC racket almost launched — then ran aground on the new, pickier security settings (“racket can’t be opened because Apple cannot check it for malicious software.”)

Does right click > open fix the problem? Alternatively, `xattr -r -d com.apple.quarantine /path/to/racket` might help?

**Comment by mbutterick** [comment]
Right-clicking didn’t work, but the `xattr` command ended the quarantine for BC `racket`. It still failed after launch.

```
Welcome to Racket v7.9.0.9 [bc].
WARNING: couldn't protect 16384 bytes of page 0x100f84000(os/kern) protection failure
Abort trap: 6
```

**Comment by LiberalArtist** [comment]
That error calls to mind [Apple’s porting docs](https://developer.apple.com/documentation/apple_silicon/porting_just-in-time_compilers_to_apple_silicon) on memory protection for JIT compilers. You all may have seen them already, but [here are some other interesting porting notes](https://developer.apple.com/documentation/apple_silicon/addressing_architectural_differences_in_your_macos_code).

**Comment by mflatt** [comment]
Thanks for that pointer!

I made some progress toward `MAP_JIT` (but still just cross-compiling). Here are executables with the latest, although they're still unlikely to work, of course:

http://www.cs.utah.edu/~mflatt/tmp/racket-7.9.0.9-aarch64-macosx-cs.dmg
http://www.cs.utah.edu/~mflatt/tmp/racket-7.9.0.9-aarch64-macosx-bc.dmg

Those images are signed and notarized, so you shouldn't have to use `xattr` to crash at their full potential.

**Comment by mbutterick** [comment]
Thanks — the CS `racket` still fails immediately with error `Killed: 9`. 

Despite the notarization, the BC `racket` still provoked the same security warning (and `xattr` resolved it, again). After that, I was able to launch the Racket BC REPL and evaluate expressions. I was able to make a `rkt` source file and run it with `racket`. 

But any attempt to use `raco pkg install` resulted in the error`Illegal instruction: 4`. (Because this is a minimal build, trying to run any practical project means installing more packages, thereby triggering this error.)

**Comment by mflatt** [comment]
My laptop arrived today, so minimal Racket now builds and runs.

The next step is compiling the native-library packages like openssl and Cairo.

**Comment by zwarich** [comment]
Racket should work under Rosetta in the latest macOS 11.1 Beta 2 (build 20C5061b) released today.

**Comment by mflatt** [comment]
Racket (including DrRacket, etc.) should build and run on M1 Macs, now. I'll test more and work on adding the build to the Utah snapshots.

**Comment by mflatt** [comment]
I've uploaded the download page with a note for M1 Mac users to try the snapshot builds.

**Comment by LiberalArtist** [comment]
For those of us who maintain native-library packages, would you recommend that we also add `aarch64-macosx` variants, rather than, for example, building "universal binaries"?

**Comment by mflatt** [comment]
Yes. I think the aarch64 libraries have to be signed, too, since Big Sur on ARM seems to ignore the `com.apple.security.cs.disable-library-validation` entitlement.

**Comment by LiberalArtist** [comment]
Do you know if they can use an ad-hoc signature or need an Apple-recognized one? From the [docs for that entitlement](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_disable-library-validation), it sounded like it might be the later, but I am easily confused by all of the variations on code-signing.

**Comment by mflatt** [comment]
I'm not sure, and I also get confused easily, but I think an ad hoc signature may work in this case — which suggests that maybe `raco setup` should add a signature the way it does for executables.

**Comment by mflatt** [comment]
It looks like an ad hoc signature will work, even starting a Racket that is itself signed (not ad hoc), so you can do that.

Although I could make `raco setup` add an ad hoc signature, probably it's better to just include an ad hoc signature on the library in its package, and then there's less room for `raco setup` to go wrong.
