### ISSUE TITLE
Upgrade to libffi3.3 breaks CI build

### ISSUE THREAD

**Issue by pmatos** [racket/racket#3521]
Upgrade in 403ef87ec26e25b85cc35e2fda936ea0de43b475 breaks CI build because some used functions are marked as deprecated creating a warning and failing due to `-Werror`.

**Comment by mflatt** [comment]
I had a repair for this, but forgot to push! Done now.

**Comment by pmatos** [comment]
Fixed by f2d7f1d8221e684309f357dab4e474ecae090868
Thanks
