### ISSUE TITLE
read (compiled): ill-formed code racket [SOLVED]

### ISSUE THREAD

**Issue by xMonny** [racket/racket#3522]
Hey guys. I had a homework where I had to write unit tests. When I tried to run my tests, I get this problem:
read (compiled): ill-formed code [../../../racket/gc2/../src/read.c:2591] in: compiled\drracket\errortrace\tree_rkt.zo ,
where "tree" is the name of my file.
"tree-test.rkt" has this in first lines:
#lang racket/base
(require rackunit rackunit/gui)
(require racket/string)
(require racket/stream)
(require "tree.rkt")

I tried everything to run my code without this annoying error and I think that I succeeded. Now I will share the solution of my problem:
1. Go to "Language" in the menu bar
2. Choose "Choose Language"
3. Select "The Racket Language"
4. In the left bottom corner choose "Show Details"
5. UNCHECK "Populate "compiled" directories (for faster loading)"

When I did these steps, the problem was solved and my tests ran without this error. My OS is Windows 10, DrRacket version is 7.9 but I think that other versions may have same problem so I guess that these steps can help there again. Hope this helped!

**Comment by samth** [comment]
Can you also post what was in `"tree.rkt"`?

**Comment by xMonny** [comment]
Yes. 

#lang racket/base
(require racket/string)
(require racket/stream)

(provide tree?)
(provide string->tree)
(provide tree-valid?)
(provide balanced?)
(provide tree->string)
(provide order?)
(provide stream-equal?)
(provide tree->stream)

(provide <name_function>) means that you want to give your functions to the test file. If this is not the solution of your problem, you can share your error.

**Comment by samth** [comment]
@jackfirth did we confirm that there's no bug here?

**Comment by jackfirth** [comment]
I think so, since the title was changed to say [SOLVED]. @xMonny are you still seeing unexpected behavior?
