### ISSUE TITLE
Reference comparisons change in CS for +inf.0 and procedures

### ISSUE THREAD

**Issue by zyrolasting** [racket/racket#3547]
`(eq? (string->number "+inf.0") +inf.0)` is `#t` in v7.9 3m but `#f` in CS.

Similarly, procedure references are not `eq?` in CS if they cross module boundaries

```
(module cmp racket/base
  (require file/untar)
  (define other untar)
  (module+ test
    (writeln (eq? untar untar)) ; #t
    (writeln (eq? other untar)))) ; #f
```

From the [docs](https://docs.racket-lang.org/reference/Equality.html?q=equality#%28part._model-eq%29):

> In some cases, however, eq? is unsuitable as a comparison operator, because the generation of objects is not clearly defined

I'd expect that to mean that the `+inf.0` case is not a bug, but I'm not sure how it explains the latter case. I'd expect `other` to stay bound to an `eq?`-comparable reference.

Currently I'm working around this by always using `equal?`

**Comment by mflatt** [comment]
The `untar` example behaves the same in BC and CS, right? It's about the contract system: `other` has a contract that blames the `cmp` module, while `untar` has a contract that blames the `test` submodule, so they're not completely the same procedure.

Meanwhile, you're right that `(eq? (string->number "+inf.0") +inf.0)` just doesn't have a well-specified behavior. I think the difference between CS and BC is an artifact of the msot primitive number-parsing layers.

**Comment by zyrolasting** [comment]
> The untar example behaves the same in BC and CS, right?

(forehead slap) Yes. Disregard. Thank you for explaining how contracts play into that.

> Meanwhile, you're right that (eq? (string->number "+inf.0") +inf.0) just doesn't have a well-specified behavior. I think the difference between CS and BC is an artifact of the msot primitive number-parsing layers.

Gotcha. It sounds like this isn't a bug then, so I'll close this out.
