### ISSUE TITLE
1.0e45 is displayed as 1.0000000000000001e+045

### ISSUE THREAD

**Issue by Hamayama** [racket/racket#3548]
**What version of Racket are you using?**
7.9 [bc] [cs]

**What program did you run?**
1.0e45

**What should have happened?**
1.0000000000000001e+045 is displayed in REPL.

**If you got an error message, please include it here.**
no error message

**Please include any other relevant details**

Is the specification for displaying floating point numbers changed?

- OS     : Windows 10 (version 1909) (64bit)
  Racket : Racket 7.9 [bc] (installed by racket-7.9-x86_64-win32.exe)
  ```
  Welcome to Racket v7.9 [bc].
  > 1.0e45
  1.0000000000000001e+045
  ```

- OS     : Windows 10 (version 1909) (64bit)
  Racket : Racket 7.9 [cs] (installed by racket-7.9-x86_64-win32-cs.exe)
  ```
  Welcome to Racket v7.9 [cs].
  > 1.0e45
  1.0000000000000001e+45
  ```
  (NOTE : The zero-padding of exponential part is not displayed.)

- OS     : Windows 10 (version 1909) (64bit)
  Racket : Racket 7.0 (installed by racket-7.0-x86_64-win32.exe)
  ```
  Welcome to Racket v7.0.
  > 1.0e45
  1e+045
  ```

**Comment by mflatt** [comment]
I can confirm that this change happened with a rewrite of Racket's reader in v7.3. The input `1.0e45` is converted imprecisely (so incorrectly) while the input `1e45` still happens to be right.
