### ISSUE TITLE
[Feature Request] openssl: support TLS 1.3

### ISSUE THREAD

**Issue by LiberalArtist** [racket/racket#3551]
Racket's `openssl` module doesn't support TLS 1.3, which is now in fairly widespread use. [Matthew updated](https://groups.google.com/g/racket-users/c/WwZvIelYjMA/m/hSLvwzoyAwAJ) the foreign library shipped with Racket in August, so this should hopefully be an easy change.

**Comment by rmculpepper** [comment]
Racket does support TLS 1.3 whenever OpenSSL supports it, and the `'auto` (default) and `'secure` protocol symbols will automatically use it. It doesn't have a `'tls13` protocol symbol, but OpenSSL has deprecated that method of specifying the protocol anyway.

You can verify TLS 1.3 client support by creating a TLS 1.3-only server and connecting to it with Racket.

    openssl genrsa -out server.key
    openssl req -x509 -key server.key -out server.pem -days 10  # and answer some questions
    openssl s_server -key server.key -cert server.pem -port 4433 -tls1_3

Now connect using Racket:

    (ssl-connect "localhost" 4433)

It should succeed. When I ran this test, the server reported that it negotiated `TLS_AES_256_GCM_SHA384`, which is a TLS 1.3 ciphersuite.

If you try either of the following, they should fail:

    (ssl-connect "localhost" 4433 'tls12) ;; fails because the server supports only TLS 1.3
    (ssl-connect "localhost" 4433 'secure) ;; fails because the server certificate is not trusted
