### ISSUE TITLE
Program contour display state doesn't always match display option under View menu

### ISSUE THREAD

**Issue by bmitc** [racket/racket#3559]
**What version of Racket are you using?**
7.9 [CS] on Windows 10

**What program did you run?**
Dr. Racket. No programs are required other than potentially a definitions file long enough to effectively show the program contour such that it shows out from behind the help arrow UI element in the top-right.

There are two issues occurring:

1. It isn't clear or documented if the `Show/Hide Program Contour` selection in the `View` menu is global across all open files/tabs in Dr. Racket or if it's set for each individual file/tab.

2. The state of the option in the `View` menu, that is `Show Program Contour` and `Hide Program Contour`, does not always reflect whether the program contour is hidden or shown, respectively.

    To replicate this, simply open two tabs in Dr. Racket. Put some code (e.g., dummy comments) to make the file long enough. In one tab:

    ![image](https://user-images.githubusercontent.com/65685447/102022630-b4cc5c00-3d4d-11eb-8a35-b91250bac818.png)

    In the other tab:

    ![image](https://user-images.githubusercontent.com/65685447/102022651-d3325780-3d4d-11eb-84fe-8c5695bbe465.png)

    Note that there's actually another bug in the second tab where the program contour is strangely wide.

    ![image](https://user-images.githubusercontent.com/65685447/102022713-3cb26600-3d4e-11eb-9607-7ec03dad0a12.png)

    Everything is okay up through here because the view option correctly reflects the state. Now in one of the tabs (the second one in this example), select the option to hide (`View` -> `Hide Program Contour`).

    ![image](https://user-images.githubusercontent.com/65685447/102023626-8604b480-3d52-11eb-9b47-f870e270a983.png)

   This looks good. Now switch to the other tab (the first in this example). Note how the program contour is still showing, but under `View`, the option says to `Show Program Contour`.

    ![image](https://user-images.githubusercontent.com/65685447/102023661-c49a6f00-3d52-11eb-84ef-1db8d4092099.png)

Selecting `Show Program Contour` in this state will actually hide the contour and the option will then remain as `Show Program Contour` in the `View` menu.

**What should have happened?**
Two things should have happened:
1. The setting for showing or hiding the program contour should be global across all files (tabs) open in Dr. Racket or should be on a per file (tab) basis, and this should be documented.
2. The state in the `View` menu should always reflect what is displayed and vice versa.

**If you got an error message, please include it here.**
n/a

**Please include any other relevant details**
n/a

**Comment by rfindler** [comment]
Thanks for the report!

The deal with the overly wide contour might be the known (but not documented anywhere) bug where the contour window never decides to make itself narrower. So if you have some very wide lines but then delete them, the contour gets pushed way to the left. Doing cmd/ctl-u twice will bring it back to normal but the code internally never checks for the situation and cleans it up itself. The code with that problem is [here](https://github.com/racket/gui/blob/master/gui-lib/framework/private/text-inline-overview.rkt).

**Comment by bmitc** [comment]
Thanks for the fix!

And I see. I thought it may have had something to do with me starting off with the window itself wide, but what you say fits the issue here because I had mistakenly copy and pasted my `;; testing` string a bunch of times on a single line before I copied it with a newline at the end.
