### ISSUE TITLE
real->decimal-string takes rationals

### ISSUE THREAD

**Issue by dvanhorn** [racket/racket#3565]
The `real->decimal-string` function is documented as taking a `real?`, although (a) it doesn't check this, and (b) it only works for rational numbers.  This leads to bad error messages when given inputs outside its domain: non-numeric inputs trigger a contract violation on `inexact->exact`, complex inputs trigger a contract violation on `abs`.  It also leads to errors on inputs that are `real?` but not `rational?`, e.g. `+nan.0`, `+inf.0`, etc. break `inexact->exact`.

I'm happy to fix, but not sure what the right thing to do here is.  Should the contract be changed to `rational?` and the implementation updated to check?  This leads to a mismatch with the name of the function and its contract, but I think that mismatch already exists and there should be better error checking and reporting.

**Comment by rfindler** [comment]
Numeric stuff gets fiddly, but it seems like all the non-`rational?` `real?` number don't have any digits? So maybe adjusting the contract (but leaving the name alone) is the best way to go?

**Comment by dvanhorn** [comment]
OK, I submitted PR #3584.
