### ISSUE TITLE
Typo reminder

### ISSUE THREAD

**Issue by brunobell** [racket/racket#3567]
Hi, I think this is a typo in the documentation: `skim` -> `skip`
https://github.com/racket/racket/blob/5bb837661c12a9752c6a99f952c0e1b267645b33/pkgs/racket-doc/scribblings/getting-started/getting-started.scrbl#L46

**Comment by sorawee** [comment]
I believe "skim" is the right word here. 

> skim verb
> 2 : to read, study, or examine superficially and rapidly
> especially : to glance through (something, such as a book) for the chief ideas or the plot

I will close the issue, but feel free to reopen if you think there's anything unclear.
