### ISSUE TITLE
Dr. Racket GUI displays sloping text

### ISSUE THREAD

**Issue by sym233** [racket/racket#3569]
**What version of Racket are you using?**
9.7

**What program did you run?**
Just run dr. racket

**What should have happened?**
Text should be aligned horizontally.

**Please include any other relevant details**
Os: windows 10 x64 19042

Screenshot:
![image](https://user-images.githubusercontent.com/10321547/102524891-898e9780-40d4-11eb-93e9-807c7b24a809.png)

**Comment by sym233** [comment]
Ah, I got it.
It is caused by MacType.
The GUI gets normal after stopping MacType service.
I will post an issue there.

**Comment by otherjoel** [comment]
Can this be closed?

**Comment by mflatt** [comment]
It looks like this is not a Racket bug, but please re-open if I have misunderstood.
