### ISSUE TITLE
[cs] potential issue related to syncing and breaks

### ISSUE THREAD

**Issue by Bogdanp** [racket/racket#3574]
While working on https://github.com/racket/unix-socket/pull/4, I tried adding a test for my implementation of `tcp-accept/enable-break` and found that my test reports a failure for the implementation

```racket
    (define (tcp-accept/enable-break l)
      (apply values (sync/enable-break
                     (unix-socket-accept-evt l))))
```

under CS, but I haven't been able to get it to fail under BC.  For full context, please see [this discussion](https://github.com/racket/unix-socket/pull/4/files#r544170166) and to reproduce the issue you can check out commit https://github.com/racket/unix-socket/pull/4/commits/f41ba9bde0328638426a32219456c0e1b16df916 and add

```racket
   (let loop ([n 1000000000])
     (unless (zero? n)
       (loop (sub1 n))))
```

to the top of `accept-poll/check` in `unix-socket-lib/racket/unix-socket.rkt` (to increase the likelihood that the timing works out) then run the tests under Racket CS and BC. You might need to run the tests a few times before you see a failure under CS.

I'm running 7.9 CS and BC off of commit 627c45e8d4.

**Comment by mflatt** [comment]
It looks like the problem is indeed in the CS thread layer. The implementation of `sync/enable-break` carefully sets up a fresh thread cell for the break-enabled and makes it ignored at the right time, but it neglects to set the cell to #f before removing it from the set of ignored cells while it is still the current cell.

**Comment by mflatt** [comment]
That bug turned out to be the easy one to find and fix compared to the other bug that it masked.
