### ISSUE TITLE
Docs for box-cas! contain a typo

### ISSUE THREAD

**Issue by sinistersnare** [racket/racket#3600]
This is found in the docs for the [`box-cas!` function](https://docs.racket-lang.org/reference/boxes.html#%28def._%28%28quote._~23~25kernel%29._box-cas%21%29%29)

The equivalency example uses a variable `loc`, when it should probably say `box`

What it is:

```racket
(and (eq? old (unbox loc)) (set-box! loc new) #t)
```

What it should be :

```racket
(and (eq? old (unbox box)) (set-box! box new) #t)
```

**Comment by gus-massa** [comment]
The error is in https://github.com/racket/racket/blob/master/pkgs/racket-doc/scribblings/reference/data.scrbl

Do you want to write a PR? Otherwise we can fix it.

**Comment by sinistersnare** [comment]
Id be happy to do it. I haven't contributed to Racket before so as long as you are all patient if the process is quirky at all!

I will have something in soon, thank you.

**Comment by shhyou** [comment]
Hope this tutorial by Ben helps.
<https://blog.racket-lang.org/2017/09/tutorial-contributing-to-racket.html>

There is a section titled “How to fix a typo”.
