### ISSUE TITLE
Subprocess signal handling

### ISSUE THREAD

**Issue by willghatch** [racket/racket#3609]
Subprocesses spawned with the `subprocess` function inherit Racket's signal handling.  I'm not sure if there is a reason we want non-default signal handlers in the child process.  But at least for Rash I do generally want default signal handlers.  Eg. right now when a child process gets SIGPIPE, instead of exiting with status 141 (which I can detect and potentially handle as a non-failing pipeline stage), the process exits with status 1 and prints a message about a broken pipe to stderr.

The only signal handling I'm aware of that needs to happen with regards to fork/exec for a subprocess is SIGCHLD, which the parent needs to handle, not the child.

So unless there is a reason for child processes to inherit some of Racket's signal handling, I propose that `rktio_process` should set signal handlers to `SIG_DFL` before running `exec`.  If there is a reason for the child to inherit Racket's signal handling, I propose that we add some kind of option for it.

**Comment by mflatt** [comment]
@willghatch Does the commit above look like the right idea, especially the part in "rktio_signal.c"?

**Comment by mflatt** [comment]
I'm starting to think that this is too complicated, after all, and it's not so bad for rktio to just know the signal-ID range for each supported platform.

Originally, I had in mind saving the startup state (i.e., maybe some process started Racket with ignored signals, for example), but moved towards setting all signals to their default and setting the signal mask to empty. And after going that direction, maybe there's no need to track a specific set of signals.

Even more simply, it looks like just iterating from 1 to `SIGPROF` is going to work fine in practice. At worst, the range from 1 to `SIGPROF` is too narrow for some platform, and then we're just back to the current state until it's fixed for that platform.

**Comment by willghatch** [comment]
I think tracking the original state is the best solution, since without it Racket can't compose with eg. `nohup`, which I know people use and generally expect to work.  I think c697f11 is going in the right direction for that, simply needing a second argument to get the original value.  Is there something that makes that impractical?  If adding another argument to restore the original value works, that's my favorite solution.  If there is something that makes that impractical, then I guess the simpler solution is better for its simplicity.

**Comment by mflatt** [comment]
Saving the state and restoring it works fine — `nohup` is a good example — and I had that in an iteration before c697f11 . So, it's easy to go back, and it will be nice that the work there wasn't wasted.
