### ISSUE TITLE
unbound identifier for syntax transformer inside expand-once

### ISSUE THREAD

**Issue by aymanosman** [racket/racket#3611]
**What version of Racket are you using?**
7.9 [cs]

**What program did you run?**
```
#lang racket

(define-syntax (foo stx)
  #'(+ 1 2))

(expand-once '(foo))
```

**What should have happened?**
`#<syntax: (+ 1 2)>`

**If you got an error message, please include it here.**
```
foo: unbound identifier;
 also, no #%app syntax transformer is bound in: foo
```

**Please include any other relevant details**
This also fails in Racket 7.8 [bc], so it may just be my faulty understanding.

**Comment by sorawee** [comment]
Try:

```
#lang racket

(define-syntax (foo stx)
  #'(+ 1 2))

(define-namespace-anchor an)
(parameterize ([current-namespace (namespace-anchor->namespace an)])
  (expand-once '(foo)))
```

**Comment by aymanosman** [comment]
@sorawee that works, thanks. I'll take that to mean this is expected behaviour.

**Comment by yfzhe** [comment]
You can use [`expand-syntax-once`](https://docs.racket-lang.org/reference/Expanding_Top-Level_Forms.html#(def._((quote._~23~25kernel)._expand-syntax-once))) here.

**Comment by aymanosman** [comment]
Thanks @yfzhe, using the `expand-syntax-...` variants does indeed work.

**Comment by ajith17a** [comment]
this is the code i am running 


#lang racket
(define quine
  (let ((source '((lambda (x) (list x (list 'quote x)))
                  '(lambda (x) (list x (list 'quote x))))))  
    (list 'define 'quine source)))


(equal? quine (eval quine))


i am getting this error 
"define: unbound identifier;
 also, no #%app syntax transformer is bound in: define"

**Comment by sorawee** [comment]
In general, please ask questions at https://racket.discourse.group/. GitHub issues is for bug report.

For this particular question, the Racket Guide (https://docs.racket-lang.org/guide/eval.html#%28part._namespaces%29) explains why you get that result, and how to fix the problem.
