### ISSUE TITLE
Race condition in raco pkg install with build-time dependency

### ISSUE THREAD

**Issue by wilbowma** [racket/racket#3612]
**What version of Racket are you using?**
7.4 [bc] -- 7.8 [cs]

**What program did you run?**
A module that uses `#lang at-exp racket/base`, when `at-exp-lib` is not yet installed (such as when installing both the package and `at-exp-lib` as a dependency through raco from a minimal Racket distribution). At example package is constructed here:
https://github.com/wilbowma/test-setup-racket/tree/main/dummy-lib

**What should have happened?**
`raco pkg install dummy-lib` should install `at-exp-lib`, its dependency, and install `dummy-lib`.

**If you got an error message, please include it here.**
Depending on which packages finishes being setup first, the following error is raised:
```
instantiate: unknown module
  module name: #<resolved-module-path:"/usr/share/racket/collects/syntax/readerr.rkt">
  compilation context...:
   /home/runner/work/test-setup-racket/test-setup-racket/foo/dummy-lib/foo/meow.rkt
```

**Please include any other relevant details**
The error is completely avoided by manually installing `at-exp-lib` first, or running `raco pkg install -j 1` (eliminating concurrency). `raco pkg install -j 2` seems to trigger the bug often, while `raco pkg install -j 8` triggers it infrequently.

Examples runs can be viewed here:
https://github.com/wilbowma/test-setup-racket/runs/1654453141?check_suite_focus=true#step:4:43
https://github.com/wilbowma/test-setup-racket/runs/1654486000?check_suite_focus=true#step:4:45

`shu--hung` added the following:

> I agree with the race condition part, but the error message seems to suggest that this is a deeper concurrency problem involving namespaces and module loading (at Racket level), not about whether a file is built or not:
> 
> instantiate: unknown module
>   module name: #<resolved-module-path:"/usr/share/racket/collects/syntax/readerr.rkt">
>   compilation context...:
>    /home/runner/work/test-setup-racket/test-setup-racket/foo/dummy-lib/foo/meow.rkt
> 
> as far as I understand, this could happen when a module is supposed to be registered in a namespace (perhaps registered/loaded by the module name resolver), but later can't actually be found.
> https://github.com/racket/racket/blob/17b7033402078038bca85b478243a19baba52f4f/racket/src/expander/namespace/module.rkt#L384
> racket/src/expander/namespace/module.rkt:384

**Comment by wilbowma** [comment]
I'm not sure if this is related, but we're experiencing a similar issues that seems to be a race condition related to module initialization in the handin server, presumably when launching a student's code in a sandbox. We OCCASSIONALLY, get the following error, but only when running the server in threaded mode:
```
Error running submission instantiate: unknown module
  module name: "/home/c/cs-110/.racket-app/collects/syntax/docprovide.rkt"
```

This module isn't part of any student submission so I'm not entirely sure where it comes from.

**Comment by wilbowma** [comment]
Here's a fun test that replicates the problem. When given a `semaphore` with value 1, this prints `120` in a loop. When given a value greater than 1, the sandbox thread randomly crashes with a module initialization error, sometimes. 


```
#lang racket/base
(require
 racket/sandbox)

;; Works when set to 1, but not with 2 or more
(define s (make-semaphore 2))

(let loop ()
  (semaphore-wait s)
  (thread
   (lambda ()
     (with-handlers ([void (lambda (exn)
                             (printf "Error running ~a~n" (exn-message exn))
                             (semaphore-post s)
                             #;(exit))])

       (let ([evalor (make-evaluator
                      '(special beginner)
                      '(define (fact n)
                         (if (zero? n)
                             1
                             (* n (fact (sub1 n))))))])
         (printf "Finished ~a~n" (evalor '(fact 5)))
         (semaphore-post s)))))
  (loop))
```

Example with semaphore set to 2:
```
> racket -t stress.rkt
Error running module: cannot redeclare cross-phase persistent module
  module name: "/Users/bluephoenix47/workspace/racket/racket/collects/racket/private/serialize-structs.rkt"
Error running instantiate: unknown module
  module name: "/Users/bluephoenix47/workspace/racket/racket/collects/syntax/transformer.rkt"
Error running instantiate: unknown module
  module name: "/Users/bluephoenix47/workspace/racket/racket/share/pkgs/htdp-lib/lang/private/signature-syntax.rkt"
Error running instantiate: unknown module
  module name: "/Users/bluephoenix47/workspace/racket/racket/share/pkgs/scheme-lib/scheme/class.rkt"
Finished 120
Error running with-limit: out of memory
Error running instantiate: unknown module
  module name: "/Users/bluephoenix47/workspace/racket/racket/share/pkgs/pict-lib/pict/convert.rkt"
Finished 120
Finished 120
Finished 120
Finished 120
```

And when set to 1
```
> racket -t stress.rkt
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
Finished 120
```

**Comment by mflatt** [comment]
@wilbowma Thanks! This is an especially helpful example that exposes three different problems. The problem that it hits most often is related to module caching and is the most subtle.

**Comment by wilbowma** [comment]
Happy to help, and thanks a lot for the quick fix! Is that commit going to be in the snapshots soon?

**Comment by samth** [comment]
The ci-driven snapshots should be available already, if you just need a Linux build. The Utah snapshot should be available tomorrow.

**Comment by rmculpepper** [comment]
@samth can the ci-driven snapshots be linked from pre.racket-lang.org?

**Comment by elfprince13** [comment]
Is there any reason to believe this might impact #3105?

**Comment by mflatt** [comment]
Yes, I think this issue fixed. (I don't think the repair has any effect on #3105.)
