### ISSUE TITLE
get-ffi-obj failed to get C-level functionality exported by the run-time system for chez-scheme

### ISSUE THREAD

**Issue by mrmathematica** [racket/racket#3617]
Similar to #3349, but on Linux with Racket 7.9. Error message below.

ffi-obj: could not find export from foreign library
  name: Sstring_utf8
  library: [all opened]
  system error: /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0: undefined symbol: Sstring_utf8

**Comment by mflatt** [comment]
One solution is to add `-rdynamic` to the Linux link flags, but after thinking about it some, I'm not sure this direction is a good idea. Historically, C-level functions from BC were needed for various libraries, but we've moved away from that approach, mostly to avoid BC- or CS-specific code.

Can you say more about how it would be useful to access functions like `Sstring_utf8` dynamically?

**Comment by mrmathematica** [comment]
Using FFI to process unicode string from C is useful. Calling `(system-type 'vm)` to tell BC or CS so no problem on that part. Also nowadays things like `Sstring_utf8` can be dynamically accessed on Windows and Mac so no able to do it on Linux is not consistent.

On the other side, I tried

```
(define s (make-string len))
(for ((i (in-range len)))
  (string-set! s i (integer->char (ptr-ref ptr _uint32 i))))
```  

and can verify it is an inefficient replacement for the old `scheme_make_sized_char_string`.
