### ISSUE TITLE
ODBC memory allocation errors

### ISSUE THREAD

**Issue by eddierucker** [racket/racket#3619]
**What version of Racket are you using?**
Welcome to DrRacket, version 8.0.0.1--2021-01-09(259f92a/a) [cs].

**What program did you run?**
#lang racket

(require db)

(define sql "
SELECT DISTINCT CSSV.StudentUID,
                CSAV.Department + CSAV.Course + CSAV.Section AS Course,
                CSAV.Grade
FROM CAMS_StudentStatus_View AS CSSV
         JOIN CAMS_SRAcademic_View AS CSAV
              ON CSSV.StudentUID = CSAV.StudentUID
                  AND CSSV.TermCalendarID = CSAV.TermCalendarID
WHERE CSSV.TextTerm IN (?, ?)
  AND CSAV.Department = ?
  AND CSAV.Course = ?")

(define (pull c course year)
  (define term1 (format "Fall ~a" year))
  (define term2 (format "Spring ~a" (add1 year)))
  (match course
    [(list department course-number)
     (for/fold
	 ([v (vector 0 0 0 0 0)])
	 ([(uid crs grade)
	   (in-query c sql term1 term2 department course-number)]
	  #:unless (string=? grade ""))
       (define pos (case grade
		     [("A") 0]
		     [("B") 1]
		     [("C") 2]
		     [("D" "F" "FA" "WF") 3]
		     [else 4]))
       (vector-set! v pos (add1 (vector-ref v pos)))
       v)]))

(define (% n d)
  (if (> d 0)
      (~r (/ (* 100.0 n) d) #:precision '(= 2))
      "0.0%"))

(define c (odbc-connect #:dsn "cams"))

(for* ([course (in-list '(("BY" "390-")
			  ("BY" "391-")
			  ("BY" "300-")
			  ("BY" "460-")
			  ("MA" "110-")
			  ("MA" "140-")))]
       [year (in-list '(2016 2017 2018 2019 2020))])
  (match (touch (future (lambda () (pull c course year))))
    [(vector a b c d-f nc)
     (let ([t (+ a b c d-f nc)])
       (printf "~a\t~a/~a\t~a%\t~a/~a\t~a%\t~a/~a\t~a%\t~a/~a\t~a%\t~a/~a\t~a%\n"
	       year a t (% a t) b t (% b t) c t (% c t) d-f t (% d-f t) nc t (% nc t)))]))

(disconnect c)

**What should have happened?**
Should pull data from a MSSQL database.

**If you got an error message, please include it here.**
in-query: [Microsoft][ODBC Driver 11 for SQL Server]Memory allocation failure
  SQLSTATE: HY001
  context...:
   C:\Program Files\Racket-8.0.0.1\collects\db\private\generic\interfaces.rkt:170:0: raise-sql-error
   C:\Program Files\Racket-8.0.0.1\share\pkgs\db-lib\db\private\odbc\connection.rkt:781:0: handle-status*
   C:\Program Files\Racket-8.0.0.1\share\pkgs\db-lib\db\private\odbc\connection.rkt:86:8
   C:\Program Files\Racket-8.0.0.1\collects\db\private\generic\common.rkt:277:13
   C:\Program Files\Racket-8.0.0.1\collects\db\private\generic\common.rkt:163:24
   C:\Program Files\Racket-8.0.0.1\collects\db\private\generic\functions.rkt:66:0: query/rows
   C:\Program Files\Racket-8.0.0.1\share\pkgs\db-lib\db\private\generic\functions2.rkt:64:0: in-query-helper
   C:\Users\erucker.BMC\Documents\racket-projects\four-year-course-completion.rkt:17:0: pull
   C:\Program Files\Racket-8.0.0.1\collects\racket\private\for.rkt:1540:9
   body of "C:\Users\erucker.BMC\Documents\racket-projects\four-year-course-completion.rkt"

**Please include any other relevant details**
Window 10. The error occurs both from DrRacket and from the command line. I did not get this error with previous [bc] versions. However, occasionally, odbc queries crashed at at random times in [bc], mostly when the (disconnect con) was executed.

**Comment by rmculpepper** [comment]
Thanks for the report! I've just pushed a fix for an issue that may have caused the error you saw. Please let me know whether that change fixes the behavior of your program.

**Comment by eddierucker** [comment]
The nightly version [cs] from Northwestern University works. The one from Utah doesn't. Thank you for fixing this issue!

**Comment by mflatt** [comment]
I think the Utah build was just slower by a day to pick up the change. I'm closing the PR, but please reopen if that's not right.
