### ISSUE TITLE
The on-double-click method in a pasteboard% behaves incorrectly

### ISSUE THREAD

**Issue by bmitc** [racket/racket#3626]
**What version of Racket are you using?**
Racket 7.9 CS on Windows 10

**What program did you run?**
When overriding `on-double-click` for a class specializing a `pasteboard%`, the method is fired twice instead of once and is also sometimes generated when a double-click did not occur. Run the below code.

```racket
#lang racket/gui

(define square-snip-class
  (make-object
      (class snip-class%
        (super-new)
        (send this set-classname "square"))))

(send (get-the-snip-class-list) add square-snip-class)

(define (set-extent-others others)
  (for/list ([other others])
    (when other (set-box! other 0.0))))

(define square%
  (class snip%
    (super-new)
    (send this set-snipclass square-snip-class)

    (define/override (get-extent dc x y width height . others)
      (when width (set-box! width 50))
      (when height (set-box! height 50))
      (set-extent-others others))

    (define/override (draw dc x y . other)
      (send dc set-pen "Black" 3 'solid)
      (send dc set-brush "Pale Turquoise" 'solid)
      (send dc draw-rectangle 100 100 50 50))
    ))

(define diagram%
  (class pasteboard%
    (super-new)

    (define/override (on-double-click snip mouse-event)
      (displayln "Snip was double-clicked."))
    ))

(define diagram (new diagram%))

(define toplevel (new frame%
                      [label "Diagram"]
                      [width 300]
                      [height 300]))

(define canvas (new editor-canvas%
                    [parent toplevel]
                    [style '(no-hscroll no-vscroll)]
                    [horizontal-inset 0]
                    [vertical-inset 0]
                    [editor diagram]))

(send toplevel show #t)

(send diagram insert (new square%) 100 100)
```

To reproduce, do the following:
1. Run the code in DrRacket.
2. Click on the square snip _once_. Note that no double-click event was generated (monitor the interactions window for a string saying `Snip was double-clicked.`.
3. Wait as long as you want (many seconds).
4. Click the snip again. Note that a double-click event is generated. This is one of the bugs, but they are likely related.

To reproduce another instance, do the following:
1. Run the code in DrRacket.
2. Double-click on the square snip. Note that a single double-click event is correctly generated.
3. Now, double-click on the square snip again. Note that _two_ double-click events are incorrectly generated.

These bugs don't happen if the snip is unselected (for example, by selecting the pasteboard canvas area) in between clicks.

**What should have happened?**
The `on-double-click` method should only be called once for each double-click and never after a single-click.

**If you got an error message, please include it here.**
n/a

**Please include any other relevant details**
n/a

**Comment by mflatt** [comment]
It looks like the problem is that the `time-stamp` field of an event is always 0 on Windows. I'll push a repair.

Unfortunately, this repair is unlikely to make it into the v8.0 release. We're into the testing phase, where we generally merge only repairs for new bugs or especially serious bugs, and this bug appears to be over a decade old.

**Comment by bmitc** [comment]
Thanks for the quick fix!

Regarding making it into the 8.0 release, that's okay. I understand the timing isn't great to get it in. Do you have an estimate of a snapshot that might have it in there?

Also, do you happen to know of applications that heavily use the pasteboard? I'm familiar with Alex Harsányi's blog posts and his ActivityLog2 application and that DrRacket uses snips heavily, but is there another good reference codebase that uses a pasteboard that you're familiar of? I'm particularly interested in diagramming and drag/drop applications or behavior.

**Comment by mflatt** [comment]
DrRacket's module broswer uses patseboards, if I remember correctly, and the `games/cards` library. You may find other good examples by grepping for `pasteboard` in ".rkt" files.

The very old GUI builder also uses pasteboards: https://github.com/mflatt/guibuilder
