### ISSUE TITLE
Adding and removing a scope does not leave a syntax object unchanged

### ISSUE THREAD

**Issue by jackfirth** [racket/racket#3631]
### What version of Racket are you using?

7.9 BC

### What program did you run?

```scheme
#lang racket

(define flip-scope (make-syntax-introducer))
(define stx #'(+ 1 2 3))

(equal? stx (flip-scope (flip-scope stx))) ;; produces #f
```

### What should have happened?

I expected the above to return true, since it seems logical that flipping a scope twice should leave a syntax object unchanged. However it returns false. I can't tell if this is a bug or not though, is this behavior intentional?

### Please include any other relevant details

I ran the code using DrRacket on macOS. For background, I'm writing some syntax object processing functions and this is making it trickier to test them.

**Comment by samth** [comment]
I think this is expected behavior. My guess is that those two objects will behave the same in all contexts, but there isn't a general syntax object equality test. 

And yes, it's hard to test things like this.

**Comment by jackfirth** [comment]
Also according to @mflatt, syntax objects compare using `eq?` and changing that isn't feasible. So I'm closing this as working-as-intended.
