### ISSUE TITLE
Gap between shapes when overlaying images with 2htdp/image teachpack

### ISSUE THREAD

**Issue by nadeemabdulhamid** [racket/racket#3640]
The following code snippet results in a slight gap between the two rectangles, whereas if you have just the `above` expression alone, the rectangles are joined flush together with no gap. It's confusing my students, who think they are doing something wrong...

This has a visible gap between the rectangles (and it only seems to appear if the height of the top rectangle is an odd number - 11 vs. 12):
```
(require 2htdp/image)

(overlay/offset
 (ellipse 20 40 "solid" "blue")
 0 50
 (above
  (rectangle 40 11 "solid" "red")
  (rectangle 50 100 "solid" "blue")))
```

This has no gap:
```
(above
  (rectangle 40 11 "solid" "blue")
  (rectangle 50 100 "solid" "blue"))
```

**Comment by rfindler** [comment]
I'm not seeing a gap. FWIW, the 2htdp/image library is just asking the underlying OS's drawing library to draw rectangles in the expected places --- and based on my understanding of the semantics of these drawing commands, as issued by Racket, there should not be any visible gap.

<img width="176" alt="Screen Shot 2021-01-21 at 11 48 03 AM" src="https://user-images.githubusercontent.com/399024/105390427-a5f38780-5bde-11eb-9c36-701a5507f520.png">

**Comment by sorawee** [comment]
@rfindler I can see the gap.

FWIW, here're zoomed-in images, where both are modified to have the same color.

<img width="468" alt="Screen Shot 2021-01-21 at 9 53 22 AM" src="https://user-images.githubusercontent.com/9099577/105391029-8bb1ad80-5bce-11eb-9c91-ecc972359f92.png">
<img width="518" alt="Screen Shot 2021-01-21 at 9 53 27 AM" src="https://user-images.githubusercontent.com/9099577/105391033-8d7b7100-5bce-11eb-980d-0d3e0912084a.png">

<img width="361" alt="Screen Shot 2021-01-21 at 9 51 08 AM" src="https://user-images.githubusercontent.com/9099577/105391071-979d6f80-5bce-11eb-8d14-137e48a10bf1.png">
<img width="333" alt="Screen Shot 2021-01-21 at 9 51 16 AM" src="https://user-images.githubusercontent.com/9099577/105391081-99673300-5bce-11eb-8015-788f14623936.png">

**Comment by mfelleisen** [comment]
Given Robby's response, he needs to know which OS you're on -)

**Comment by sorawee** [comment]
It's Mac OS (Big Sur) for me.

**Comment by shhyou** [comment]
I can confirm that there is a visible line on Mac when the height is odd and that the y offset of `overlay/offset` is greater than the rectangle's height.

However, I think it's safe to consider this to be the expected behavior: it's probably the result of anti-aliasing done by the underlying drawing library. Zooming in shows that the line looks like the gradient from the rectangle instead of a gap.

![Screenshot of DrRacket showing line-separated rectangles in the Interaction Window](https://github.com/racket/racket/assets/1910898/c17f4c4b-06cd-4606-bef3-232b8981c5ba)

**Comment by sorawee** [comment]
Is this the expected behavior though?

**Comment by shhyou** [comment]
I think so. It falls under the same category as circles & ellipses are drawn with anti-aliasing.

**Comment by shhyou** [comment]
In this code, it can be observed that the first and the third images contains a seam between the rectangles, while the second one doesn't. In fact, not only that there is a seem between the rectangles, but the upper rectangle actually has blurred edges.

```racket
(require 2htdp/image)
(for/list ([Y-OFFSET '(34 34.5 35)])
  (overlay/offset
   empty-image
   0 Y-OFFSET
   (above
    (rectangle 80 30 "solid" "green")
    (rectangle 80 31 "solid" "green"))))
```
