### ISSUE TITLE
read-string!, read-bytes!, read-bytes-avail! have contract errors

### ISSUE THREAD

**Issue by Noble-Mushtak** [racket/racket#3641]
**What version of Racket are you using?**
I'm using Racket v7.9 [bc].

**What program did you run?**

```
#lang racket
(require racket/contract)

(define empty-string (make-string 0))
(define empty-bytes (make-bytes 0))

((or/c exact-positive-integer? eof-object?) (read-string! empty-string))

((or/c exact-positive-integer? eof-object?) (read-bytes! empty-bytes))

((or/c exact-positive-integer? eof-object? procedure?) (read-bytes-avail! empty-bytes))
```

**What should have happened?**

This program outputs three Booleans. According to the output contracts of `read-string!`, `read-bytes!`, `read-bytes-avail!`, all of these Booleans should be `#t`. Instead, all of the Booleans are `#f`, which shows that the return value does not satisfy the output contract of these functions.

**Please include any other relevant details**

The output contract of `read-string!` is `(or/c exact-positive-integer? eof-object?)` [according to the documentation](https://docs.racket-lang.org/reference/Byte_and_String_Input.html?q=read-string!#%28def._%28%28quote._~23~25kernel%29._read-string%21%29%29). However, the documentation also says, "If the difference between start-pos and end-pos is 0, then 0 is returned and str is not modified." Clearly, 0 is neither a positive integer nor a EOF object, so this violates the output contract of `read-string!`. This can easily be tested as above by seeing that calling `read-string!` on an empty string causes it to output `0`, even though `0` does not satisfy its output contract.

`read-bytes!` and `read-bytes-avail!` output `0` when given an empty bytestring because they are similar to `read-string!`. This also causes a contract violation in `read-bytes!` and `read-bytes-avail!`.

I'm fairly new to Racket, so I apologize if I made any mistakes in using certain terminology or in reporting this issue. Thanks for understanding.

**Comment by mflatt** [comment]
Thanks for the report! I'll repair the documentation.
