### ISSUE TITLE
ssl-make-client-context fails in stand-alone executable

### ISSUE THREAD

**Issue by sidibu** [racket/racket#3655]
**What version of Racket are you using?**
The newest snapshot: 20210125-87bf20c

**What program did you run?**
Create a file called program.rkt:

#lang racket/base
(require openssl)

(ssl-make-client-context)

Create a stand-alone Windows executable from that program with raco and embed all dlls:

`raco.exe --embed-dlls program.rkt`

**What should have happened?**
The executable should have exited without error.

**If you got an error message, please include it here.**
Running the exe causes the following error:

ssl-make-client-context: context creation failed (error:00000000:lib(0):func(0):reason(0))
  context...:
   .../openssl/mzssl.rkt:586:18
   .../unsafe/atomic.rkt:73:13
   .../openssl/mzssl.rkt:717:0: make-raw-context
   .../openssl/mzssl.rkt:706:0: make-context
   .../openssl/mzssl.rkt:734:0: ssl-make-client-context
   .../private/arrow-val-first.rkt:555:3
   body of 'program
   body of top-level

[Exited. Close box or Ctrl-C closes the console.]

**Please include any other relevant details**
e.g., the operating system used or how you are running the code.
Windows 10 Home 64Bit. Ran from Powershell, cmd.exe and by double-clicking the exe.

If built without `--embed-dlls` or run via DrRacket, the error does not appear.

**Comment by mflatt** [comment]
It appears that the OpenSSL library is not compatible with https://github.com/fancycode/MemoryModule, which is what Racket uses to embed DLLs. I'm not sure where things go wrong, but if there's an improvement to the MemoryModule code that would make the OpenSLL libraries work, that would be very welcome!

**Comment by sidibu** [comment]
Thank you for looking into this. Is it possible to use a different SSL library with racket instead? And if so, how?

**Comment by mflatt** [comment]
It looks like someone figured this out since the last time I tried: py2exe/py2exe#67. Thanks, @leejeonghun!
