### ISSUE TITLE
Selection of editor-snip% causes unwanted redraw of its pasteboard%

### ISSUE THREAD

**Issue by bmitc** [racket/racket#3657]
**What version of Racket are you using?**
7.9 CS on Windows 10

**What program did you run?**

```racket
#lang racket/gui

(define (set-extent-others others)
  (for/list ([other others])
    (when other (set-box! other 0.0))))

(struct dc-state (smoothing pen brush))

(define (capture-dc-state dc)
  (dc-state (send dc get-smoothing)
            (send dc get-pen)
            (send dc get-brush)))

(define (restore-dc-state dc dc-state)
  (send dc set-smoothing (dc-state-smoothing dc-state))
  (send dc set-pen (dc-state-pen dc-state))
  (send dc set-brush (dc-state-brush dc-state)))

(define node-pasteboard%
  (class pasteboard%
    (super-new)
    
    (define/override (on-paint before? dc left top right bottom dx dy . others)
      (when before?
        (let* ([old-dc-state (capture-dc-state dc)]
              [x (+ left dx)]
              [y (+ top dy)]
              [width 150]
              [height 100]
              [radius (/ (min width height) 2)])
          (send dc set-smoothing 'smoothed)
          (send dc set-pen
                (send the-pen-list find-or-create-pen
                      "black" 2 'solid))
          (send dc set-brush
                (send the-brush-list find-or-create-brush
                      "White Smoke" 'solid))
          (send dc draw-rectangle x y width height)
          (send dc draw-rectangle x y width 20)
          (send dc draw-ellipse (+ x (/ width 3)) (+ y (* 0.35 height)) radius radius)
          (restore-dc-state dc old-dc-state))))
    ))

(define node-editor-snip%
  (class editor-snip%
    (init-field [label "<no label>"])
    (init [pasteboard (new node-pasteboard%)])
    (super-new [editor pasteboard]
               [with-border? #f]
               [left-margin 0]	 
               [top-margin 0]	 
               [right-margin 0]	 
               [bottom-margin 0]
               [left-inset 0]
               [top-inset 0]
               [right-inset 0]
               [bottom-inset 0]
               [min-width 150]
               [min-height 100]
               [max-width 150]
               [max-height 100])
    (let ([pb (send this get-editor)])
      (send pb set-selection-visible #f)
      (send pb set-area-selectable #f)
      (send pb set-dragable #f))
    ))

(define pasteboard (new pasteboard%))

(define frame (new frame%
                   [label "Window"]
                   [width 500]
                   [height 500]))

(define canvas (new editor-canvas%
                    [parent frame]
                    [style '(no-hscroll no-vscroll)]
                    [horizontal-inset 0]
                    [vertical-inset 0]
                    [editor pasteboard]))

(send pasteboard insert (new node-editor-snip%))

(send frame show #t)
```

**What should have happened?**
I believe that no change should have happened to the `editor-snip%`'s `pasteboard%`. It's of course possible that I am missing something. If that's the case, I don't know how to rectify the situation and would propose an update to the documentation if I haven't missed existing documentation that explains this.

**If you got an error message, please include it here.**
None.

**Please include any other relevant details**

When dragging a selection window from the bottom right to the top left:
![image](https://user-images.githubusercontent.com/65685447/106090252-67cefa00-60ef-11eb-99a4-37d3621b5066.png)

When dragging a selection window from the top left to the bottom right:
![image](https://user-images.githubusercontent.com/65685447/106090343-9056f400-60ef-11eb-8c75-dab4bb9672aa.png)

**Comment by alex-hhh** [comment]
You are misinterpreting the left top right bottom arguments to the on-paint method: they represent the region of the editor that needs to be repainted (to optimize painting when just a sub-region needs updating).  In your case, you can just ignore them and just draw the snip at `dx`, `dy` (i.e. set `x` to just `dx` and `y` to just `dy`.

**Comment by bmitc** [comment]
Thanks, and I see.

I think the follow paragraph for [`on-paint`](https://docs.racket-lang.org/gui/editor___.html#%28meth._%28%28%28lib._mred%2Fmain..rkt%29._editor~3c~25~3e%29._on-paint%29%29) should be clarified then, since it is where my interpretation came from, particularly the second sentence.

> The left, top, right, and bottom arguments specify which region of the editor is being repainted, in editor coordinates. To get the coordinates for dc, offset editor coordinates by adding (dx, dy).

**Comment by bmitc** [comment]
Does anyone have any thoughts as to how to clarify the documentation I pointed out in the above comment? The documentation is misleading or at least unclear when the editor, a `pasteboard%` in this case, is contained within an `editor-snip%`.

**Comment by mflatt** [comment]
I changed the docs by moving the description of `dx` and `dy` earlier, since those are the more useful arguments. I also adjusted the description of `left`, etc., along the lines of Alex's answer, which is that they're for potentially optimizing drawing.

**Comment by bmitc** [comment]
Thank you for the documentation change @mflatt!
