### ISSUE TITLE
list-ref's error message is inaccurate

### ISSUE THREAD

**Issue by sorawee** [racket/racket#3661]
**What version of Racket are you using?**
v8.0.0.3 [cs]

**What program did you run?**

```
(list-ref '(1 2 . 3) 2)
```

**What should have happened?**

An error should occur, but its message probably shouldn't be:

```
; list-ref: contract violation
;   expected: list?
;   given: '(1 2 . 3)
```

since `(list-ref '(1 2 . 3) 1)` is totally fine, so clearly `list-ref` does not expect a list there.

**If you got an error message, please include it here.**

See above

**Please include any other relevant details**

Same for `list-tail`, and potentially other more functions.

**Comment by mfelleisen** [comment]
expected: sufficiently long `list?` prefix
