### ISSUE TITLE
Internal error from struct* match pattern

### ISSUE THREAD

**Issue by LiberalArtist** [racket/racket#3662]
I haven't found a minimal example yet, but I am getting this error from the `struct*` `match` pattern:
```
collects/racket/match/struct.rkt:26:2: cadddr: contract violation
      expected: (cons/c any/c (cons/c any/c (cons/c any/c pair?)))
      given: #<procedure:struct-info-self-ctor>
```

The (large) program where I encountered this attempted to use `struct*` with a child struct type to match against a field from the parent struct type, which the [docs](https://docs.racket-lang.org/reference/match.html#(form._((lib._racket%2Fmatch..rkt)._struct*))) say is an error. (“The fields do not include those from super types.”) But my simple attempts to recreate the situation instead get the correct error, `struct*: field name not associated with given structure type`.)

The immediate problem seems to be line 14 of:
https://github.com/racket/racket/blob/4e76091c6498ff470c0990eb6bfbaa6925424525/racket/collects/racket/match/struct.rkt#L10-L15
which should instead be something like `(length (cadddr (extract-struct-info (syntax-local-value parent))))`.

**Comment by sorawee** [comment]
That's definitely my fault in #3290. It's a bit difficult to provoke this behavior because the code is executed as a fallback method when the information that should be available is not available. Here's a minimal buggy program:

```
#lang racket

(require web-server/http)

(match (binding:file #"1" #"2" '() #"3")
  [(struct* binding:file ([filename _])) #f])
```
