### ISSUE TITLE
Confusing error message in *SL if inadvertently rebinding `quote`

### ISSUE THREAD

**Issue by ibarland** [racket/racket#3667]
**What version of Racket are you using?**
e.g., 7.9 [bc]

**What program did you run?**
(define (make-a-meme quote)
    'stub)

; ERROR: the `'` is highlighted, with message:
;   stub: unbound identifier in: stub

**What should have happened?**

I understand the message, but it might have been nice to get a warning like "redefining `quote` means that symbols won't work", perhaps?  (Something more "correct", like changing the reader or expander, is probably overkill.)

Pedagogically, I like that there aren't forbidden keywords.  And in practice people don't naturally try to rebind `#%app`, and if they try to define `define` they presumably know something strange might happen.  But `quote` is different -- it is both (a) an eminently plausible well-named variable, and (b) there's no indication to a student that this variable is already in use.

**If you got an error message, please include it here.**
stub: unbound identifier in: stub

**Please include any other relevant details**
(Sorry if I submitted this bug-report twice -- but I don't see my first submit and I think I closed the window w/o submitting.)

In writing this bug report, I was tickled to find `(define (define define) define)` works fine.

**Comment by jbclements** [comment]
Actually, the error in *B*SL is different, and possibly even worse.

However, it looks like there may already be an easy mechanism for fixing this. Specifically, when I run this program:

```
(define (make-a-meme cond)
  (cond [(= 3 3) #t]
        [else #f]))
```

... in *SL, I get basically exactly the right error message (highlights cond, says "expected a variable, found a keyword".)

So maybe this is as easy as finding the list of keywords in the *SL languages, and adding "quote" ?

**Comment by jbclements** [comment]
Also: Hi!

**Comment by ibarland** [comment]
Whoops, you're right, I'd confused my language-level tabs when writing this up, d'oh.  So `define` (and `cond` and `#%app`) *are* tagged as keywords in {B,I,A}SL.

And: Yeah, hi!

**Comment by xxyzz** [comment]
I tried to add `quote` to `keyword-list` in https://github.com/xxyzz/htdp/commit/695352c7fdd57e789692f27c3ca7eb11f99375ad, but the test complained about `function call: expected a function after the open parenthesis, but found a variable\n  at: quote\n  in: (#%app quote y)"`(https://github.com/xxyzz/htdp/runs/2084819976?check_suite_focus=true#step:7:280). It seems add `quote` doesn't work?

**Comment by samth** [comment]
@xxyzz I think you should just change the body of that test to `5` or something to get the error message you expect. You're seeing the error message from the function body before the error you added.

**Comment by xxyzz** [comment]
> change the body of that test to `5` or something

But it just returns `(values #<void>)`(https://github.com/xxyzz/htdp/runs/2091481460?check_suite_focus=true#step:7:281).

**Comment by sorawee** [comment]
I think you need to use `beginner-quote`, `intermediate-quote`, etc.

**Comment by xxyzz** [comment]
Thanks!
