### ISSUE TITLE
The exe can't run wth use DRacket  [Create Executable..] menu

### ISSUE THREAD

**Issue by imxingquan** [racket/racket#3676]
**What version of Racket are you using?**
7.9 [cs]

**What program did you run?**
![image](https://user-images.githubusercontent.com/14246824/106846386-bda33380-66e7-11eb-8eff-b56a732fa07e.png)

I Click Racket/Create Executable... and choose to Stand-alone...

**What should have happened?**
![image](https://user-images.githubusercontent.com/14246824/106846448-d9a6d500-66e7-11eb-87e1-7eabfe4fdd18.png)

**Comment by sorawee** [comment]
This works for me. I'm using v8.0.0.5 on Mac M1, though, so either this is a Windows specific bug, or the problem has already been fixed.

@imxingquan can you try a snapshot version of Racket (https://www.cs.utah.edu/plt/snapshots/) and see if you still experience the issue?

**Comment by mflatt** [comment]
This seems likely to have been the problem in CS where executables can't start in a path that has non-ASCII characters. That problem has been fixed for the upcoming v8.1. That version will be available soon, and a pre-release is currently available at https://pre-release.racket-lang.org/.
