### ISSUE TITLE
Contracts on (super ...) calls are not enforced

### ISSUE THREAD

**Issue by formalizm** [racket/racket#3682]
Internal class contracts on (super ...) calls are not enforced. This is demonstrated in the Reference: https://docs.racket-lang.org/reference/Object_and_Class_Contracts.html - search for the phrase "The last call signals an error blaming woody2% because ..." The error is in fact not issued.

I've checked also in REPL (of Racket 7.7) that the error is not signaled. But it should be.

Also the aforementioned phrase in the documentation is not clear. So I think it is both a bug and a documentation issue.

**Comment by mfelleisen** [comment]
I suspect that code snippet was supposed to look like this: 

```
  (define/contract woody%+s
    (class/c (super [draw (->m symbol? string?)]))
    (class object%
      (define/public (draw who)
        (format "reach for the sky, ~a" who))
      (super-new)))

  (define woody2+c%
    (class woody%+s
      (define/override draw
        (case-lambda
          [(a) (super draw a)]
          [(a b) (string-append (super draw a)
                                " and "
                                (super draw b))]))
      (super-new)))
```

because the contract system _does_ check contracts on `super` call (if there is one).

**Comment by formalizm** [comment]
So, I misunderstood it, because the Reference puts the (super) contract into the subclass. But in fact, it must be in the superclass, right?

So, it is not a bug, but only a documentation issue, where the snippet should have been as you wrote it, correct?
