### ISSUE TITLE
"cannot capture ast continuation barrier" error in Racket CS

### ISSUE THREAD

**Issue by alex-hhh** [racket/racket#3696]
**What version of Racket are you using?**

I can reproduce this problem with Racket 7.9[cs] and 8.0[cs] **but not** with 8.0[bc].  Running under Windows 10.

**What program did you run?**

Running the program below (requires installing the `map-widget` package), will open a window displaying the map.  Resize the window.    Under Windows, a new console window pops up with the following error message repeated:

> get-tile-bitmap(#(struct:tile 10 843 610)): call-with-composable-continuation: cannot capture past continuation barrier

```racket
#lang racket/gui

(require map-widget) ;; requires the map-widget package

(define toplevel (new frame% [label "test"] [width 300] [height 300]))
(define the-map (new map-widget% [parent toplevel]))
(send toplevel show #t)
```

**Please include any other relevant details**

The message is printed by the exception handler installed here: https://github.com/alex-hhh/map-widget/blob/cfaa9eb1ddeffc52c8e30a85ca550c2c76b444a8/private/map-tiles.rkt#L578, but I am not sure what the exception is, and where is it raised.

While manipulating the map widget (zoom , pan, or resizing the window), sometimes DrRacket is terminated with the following message also in a console window, unfortunately, I don't have a reliable way to reproduce this.

>  exception raised by error display handler: internal error: tried to deschedule a descheduled thread; original exception raised: 
exception raised by exception handler: internal error: tried to deschedule a descheduled thread; original exception raised: internal error: tried to deschedule a descheduled thread
> internal error: terminated in atomic mode!

**Comment by mflatt** [comment]
Thanks for the report!
