### ISSUE TITLE
do not install 

### ISSUE THREAD

**Issue by kerwinxu** [racket/racket#3699]
**What version of Racket are you using?**
e.g., 8.0[cs] 

**What program did you run?**
Please include a short example that triggers the bug

win 10 , i want install recket 8.0 , but get error : windows Defender 
Windows 已保护你的电脑
Microsoft Defender SmartScreen 阻止了无法识别的应用启动。运行此应用可能会导致你的电脑存在风险。
应用: | racket-8.0-x86_64-win32-cs (1).exe
-- | --
发行者: | PLT Design Inc

**What should have happened?**

**If you got an error message, please include it here.**

**Please include any other relevant details**
e.g., the operating system used or how you are running the code.

**Comment by jbclements** [comment]
Yes, this is a known problem. We've spoken with Microsoft repeatedly about this issue. The basic issue here is that windows defender SmartScreen issues warnings like this for binaries that haven't already been downloaded thousands of times. It also appears that it's possible to circumvent this by purchasing a more expensive certificate to sign our code with.

In case it's not already obvious: this is an expected error. If you downloaded the binary from the racket-lang website, it should be safe to install.

**Comment by jbclements** [comment]
... and by "spoken with Microsoft," what I mean of course is "received automated replies from Microsoft". Sorry for any confusion!
