### ISSUE TITLE
Docs for struct incorrect about #:prefab #:authentic being a syntax error

### ISSUE THREAD

**Issue by jackfirth** [racket/racket#3700]
**What version of Racket are you using?**
8.0 [cs]

**What program did you run?**
Please include a short example that triggers the bug

```scheme
#lang racket/base

(struct foo ()
  #:authentic
  #:prefab)
```

**What should have happened?**

The docs for `struct` have this to say on the `#:prefab` keyword:

> The #:prefab option obtains a prefab (pre-defined, globally shared) structure type, as opposed to creating a new structure type. Such a structure type is inherently transparent and cannot have a guard or properties, so using #:prefab with #:transparent, #:inspector, #:guard, #:property, #:authentic, or #:methods is a syntax error.

So the program should have failed to compile, yet it runs just fine. Either the docs need to change or this should be a syntax error, but I'm not sure which course of action is best.

**Comment by mflatt** [comment]
This bug has been fixed at the `make-struct-type` level in Git HEAD.

Probably it be a syntax error instead of a run-time error, though, like combining `#:prefab` and `#:property`. Making it a syntax error in `struct` would be technically backwards-incompatible, but it seems unlikely that anyone is relying on this working in a non-evaluated context.

**Comment by jackfirth** [comment]
I found this in some real-world code that would stop working if it changed to either a runtime error or a syntax error. The code is very easy to fix, however. It seemed to occur because the author wanted their structs to be easy to read and write, so they made them `#:prefab`, then they were concerned about performance and read that `#:authentic` improves performance at the expense of using contracts. Since having both is a no-op, but the expected change from adding `#:authentic` is minor performance improvements, I think it's plausible people could get into this situation occasionally.

**Comment by mflatt** [comment]
In case it's not clear clear, adding `#:authentic` to `#:prefab` was only ever a no-op on CS. It was always at least a run-time error for BC.

**Comment by jackfirth** [comment]
Oh I see, I didn't realize it was a CS-specific issue. In that case yes, making this a syntax error makes sense.
