### ISSUE TITLE
Unzip appears to be unbreakable

### ISSUE THREAD

**Issue by sorawee** [racket/racket#3703]
**What version of Racket are you using?**
v8.0.0.7 [cs, bc]

**What program did you run?**

```
#lang racket

(require net/url file/unzip)

(define the-port (get-pure-port (string->url "https://github.com/Z3Prover/z3/releases/download/z3-4.8.8/z3-4.8.8-x64-osx-10.14.6.zip") #:redirections 10))
'success
(call-with-unzip the-port void)
```

1. Run the program
2. Wait until `success` appears. 
3. Wait for a few more seconds.
4. Break the program via `ctrl-c`.

**What should have happened?**

The program exits.

Instead, what happened is:

```
'success
^Cuser break
  context...:
   /Users/sorawee/projects/racket/racket/collects/racket/private/port.rkt:113:0: copy-port
   /Users/sorawee/projects/racket/racket/collects/file/unzip.rkt:364:4: make-filesystem-entry-reader
   /Users/sorawee/projects/racket/racket/collects/file/unzip.rkt:206:12
   /Users/sorawee/projects/racket/racket/collects/file/unzip.rkt:181:0: unzip-one-entry
   /Users/sorawee/projects/racket/racket/collects/file/unzip.rkt:320:5
   /Users/sorawee/projects/racket/racket/collects/file/unzip.rkt:414:8
   body of "/Users/sorawee/test2.rkt"
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^Cinflate: incomplete table
  context...:
   /Users/sorawee/projects/racket/racket/collects/file/gunzip.rkt:217:0: inflate
   /Users/sorawee/projects/racket/racket/collects/file/unzip.rkt:172:11
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
```

**If you got an error message, please include it here.**

See above.

**Please include any other relevant details**

N/A

**Comment by mflatt** [comment]
I think the problem is likely `unzip-one-entry`, which creates a thread inside a `dynamic-wind`, but the `kill-thread` is in the body thunk.

The right strategy is may be to create a custodian outside the `dynamic-wind`, make it current while the thread is created inside the main thunk, and then use `custodian-shutdown-all` in the `dynamic-wind` post thunk.

**Comment by mflatt** [comment]
No, I take it back; the thread shouldn't be a problem, because it's limited by a pipe. The problem is more likely `skip-bytes` in the post thunk.
