### ISSUE TITLE
OpenBSD: works with BC, fails with CS

### ISSUE THREAD

**Issue by jtmcx** [racket/racket#3717]
**What version of Racket are you using?**
7.8, 7.9, and 8.0

**What program did you run?**

Using the Chez Scheme backend on OpenBSD seems to produce malformed binaries. To reproduce:

On a fresh OpenBSD 6.8 install (amd64), install the default flavor. This will install racket version 7.8 [cs].

	$ doas pkg_add racket-minimal--

Install the racket main distrubution:

	$ raco pkg install --jobs $(sysctl -n hw.ncpuonline) \
		--auto main-distribution
	
Compile a simple "hello world" program with `raco exe':

	$ cat << EOF > main.rkt
	> #lang racket
	> (display "hello, world")
	> EOF
	$ raco exe main.rkt

Run the binary:

	$ ./main
	malformed fasl-object header in petite

**What should have happened?**

The output of `./main` should have been `"hello, world"`

**If you got an error message, please include it here.**

```
malformed fasl-object header in petite
```

**Please include any other relevant details**

I have tested this issue using racket 7.8, 7.9, and 8.0 on OpenBSD `6.8-stable` and `-current`. All versions produce this issue when using the `cs` backend. The version of OpenBSD current used was:

```
$ sysctl -n kern.version
OpenBSD 6.9-beta (GENERIC.MP) #371: Tue Mar  2 10:42:59 MST 2021
    deraadt@amd64.openbsd.org:/usr/src/sys/arch/amd64/compile/GENERIC.MP
```

Thank you!

/cc @juanfra684

**Comment by jtmcx** [comment]
I also have `wxallowed` enabled on `/usr/local` and `/home`

**Comment by mflatt** [comment]
Thanks for the report!

**Comment by jtmcx** [comment]
Thank you for the quick fix!
