### ISSUE TITLE
REPL: unable to paste multibyte characters correctly

### ISSUE THREAD

**Issue by cwfoo** [racket/racket#3720]
**What version of Racket are you using?**
v7.2

**Steps to reproduce**
1. Start the REPL.
2. Paste a multibyte character (e.g. lambda: `λ`).
3. Result: `Î»` is inserted.
    
    ![2021-03-08_16-36](https://user-images.githubusercontent.com/11555232/110295752-6e288e00-802c-11eb-9be8-7ce04e845f74.png)

**What should have happened?**
`λ` should have appeared instead.

**Please include any other relevant details**
Racket v7.2 on Ubuntu 20.04.2.
Terminal: xterm and GNOME Terminal

**Comment by sorawee** [comment]
IIUC, this is a duplicate of https://github.com/racket/readline/issues/13. The issue is already fixed in Racket 8.0.

**Comment by cwfoo** [comment]
@sorawee Thank you for the information.
