### ISSUE TITLE
do not reopen

### ISSUE THREAD

**Issue by kerwinxu** [racket/racket#3724]
when i close racket ,  i do not reopen it , i kill "Racket GUI application" in explorer , then i can open it .

racket 8.0 , win10 .

**Comment by sorawee** [comment]
This sounds like https://github.com/racket/htdp/issues/136 which was recently fixed. Are you using a student language?

**Comment by kerwinxu** [comment]
> This sounds like [racket/htdp#136](https://github.com/racket/htdp/issues/136) which was recently fixed. Are you using a student language?

Yes .

**Comment by sorawee** [comment]
As mentioned earlier, this was already fixed. It will no longer be an issue in Racket 8.1. However, if you can't wait for the release, you can download and use a snapshot build (https://snapshot.racket-lang.org/) now.
