### ISSUE TITLE
Racket 8.0 fails to build against NetBSD & musl libc (Linux)

### ISSUE THREAD

**Issue by ismaell** [racket/racket#3725]
The embedded ChezScheme on Racket 8.0 fails to build against some libc implementations due to a missing inclusion of `<time.h>` in `c/externs.h`, required to make `struct timespec` available for some function prototypes in it.

* Fix: https://github.com/cisco/ChezScheme/commit/c984fba897308fe10e1ffdecc3f9ce01d3ed0206
* Original bug report: https://github.com/cisco/ChezScheme/issues/281

**Comment by mflatt** [comment]
Thanks! I saw that Chez Scheme report, but I was puzzled that it didn't seem to be a problem when I built on my NetBSD installation. I do see the problem when trying to build with musl. 

Merged as 44964359ae274b4335c7cf707c6ba29bbdbc9fcd.

**Comment by ismaell** [comment]
@mflatt thanks; musl is very clean wrt namespacing, which exposes these bugs more often than not, OTOH the report is from NetBSD 8.0, maybe some change hid the issue since then, but it could resurface anytime, as well as in other systems.
