### ISSUE TITLE
DYLD_LIBRARY_PATH is not recognized in raco make

### ISSUE THREAD

**Issue by sorawee** [racket/racket#3737]
**What version of Racket are you using?**
8.0

**What program did you run?**

```
(begin-for-syntax (println (getenv "DYLD_LIBRARY_PATH")))
```

When running `rm -rf compiled; DYLD_LIBRARY_PATH=/opt/homebrew/lib/ raco make file.rkt`, I get `#f`

Note that changing `raco make` to `racket` will make `DYLD_LIBRARY_PATH` recognized as expected.

**What should have happened?**

See above

**If you got an error message, please include it here.**

N/A

**Please include any other relevant details**
Mac M1

It seems that this affects every environment variable starting with `DYLD_`.

**Comment by sorawee** [comment]
@soegaard mentions on Slack that this could be due to [System Integrity Protection](https://stackoverflow.com/questions/35568122/why-isnt-dyld-library-path-being-propagated-here).

> all DYLD_* environment variables are purged.

definitely happens in the above scenario.

**Comment by sorawee** [comment]
Adjusting `lib-search-dirs` to `("/opt/homebrew/lib/" #f)` can be used as a workaround. And in light of the discussion at #3718, this is probably a better solution anyway.

**Comment by mflatt** [comment]
Just a little information for the record: The `racket` executable recognizes `DYLD_LIBRARY_PATH` because it has an entitlement (as part of signing) that enabled `DYLD_LIBRARY_PATH`, but `raco` is a script that uses `/bin/sh`, and `/bin/sh` doesn't have that entitlement.

**Comment by mflatt** [comment]
Ok to close, leaving #3718 as the representative for potential improvements to the lib search path?

**Comment by sorawee** [comment]
Yes!
