### ISSUE TITLE
raco pkg install: Don't rely on `.git` suffix to recognize Git repos

### ISSUE THREAD

**Issue by sschwarzer** [racket/racket#3747]
**Is your feature request related to a problem? Please describe.**
I have a package repository hosted on Sourcehut, at https://git.sr.ht/~sschwarzer/todo-txt . When I try
```
$ raco pkg install https://git.sr.ht/~sschwarzer/todo-txt
```
I get an error
```
Downloading checksum for todo-txt
Cloning remote directory https://git.sr.ht/~sschwarzer/todo-txt
raco pkg install: could not find MANIFEST for package source
  source: https://git.sr.ht/~sschwarzer/todo-txt
  possible solution:
   If the URL is intended to refer to a Git repository, use
     https://git.sr.ht/~sschwarzer/todo-txt.git
   so that the URL ends in ".git"
```
However, Sourcehut repos can't be accessed with a `.git` suffix:
```
$ raco pkg install https://git.sr.ht/~sschwarzer/todo-txt.git
Querying Git references for todo-txt at https://git.sr.ht/~sschwarzer/todo-txt.git
pkg: Git checkout initial protocol failed;
 the given URL might not refer to a Git repository
  given URL: https://git.sr.ht/~sschwarzer/todo-txt.git
  context...:
   /sd/racket/current/collects/pkg/private/stage.rkt:762:25
   /sd/racket/current/collects/net/git-checkout.rkt:336:0: parse-initial-refs
   /sd/racket/current/collects/net/git-checkout.rkt:73:8
   /sd/racket/current/collects/net/git-checkout.rkt:54:2: retry-loop
   /sd/racket/current/collects/pkg/private/stage.rkt:59:2: lookup-normally
   /sd/racket/current/collects/pkg/private/stage.rkt:107:0: stage-package/info
   /sd/racket/current/collects/pkg/private/install.rkt:141:0: install-packages
   /sd/racket/current/collects/pkg/private/install.rkt:925:4
   /sd/racket/current/collects/racket/contract/private/arrow-val-first.rkt:555:3
   /sd/racket/current/collects/racket/file.rkt:437:8
   /sd/racket/current/collects/racket/file.rkt:426:0: call-with-file-lock
   /sd/racket/current/collects/pkg/main.rkt:216:16
   body of (submod "/sd/racket/current/collects/pkg/main.rkt" main)
   /sd/racket/current/collects/raco/raco.rkt:41:0
   body of "/sd/racket/current/collects/raco/raco.rkt"
   body of "/sd/racket/current/collects/raco/main.rkt"
```

As I was told in the Racket Slack, `raco pkg install` needs the `.git` suffix to distinguish the Git repo from a plain HTTP URL.

**Describe the solution you'd like**
It would be great if `raco pkg install` had a way to recognize a Git package source without relying on the `.git` suffix. For this, it could try first to interpret the URL as a Git URL and fall back to a plain HTTP URL if cloning with Git doesn't work. That approach may be brittle though, so it would be good if someone could come up with a better idea.

**Describe alternatives you've considered**
1) Use a `git://` URL. This requires that the hosting provider runs a Git server on port 9418. Github and Gitlab do this, but Sourcehut doesn't. (Github doesn't mention `git://` clone URLs in the "Clone URL" dialog and in https://docs.github.com/en/github/getting-started-with-github/about-remote-repositories . Therefore I assume that Github has the Git server only for backward compatibility. I haven't checked Gitlab yet.)

2) Change the URL to https://git.sr.ht/~sschwarzer/todo-txt/tree/<tag_or_branch>/item/ and provide a MANIFEST file. This should allow `raco pkg install` to treat the URL as a plain HTTP URL. Of course, this would require a MANIFEST file that must be maintained together with the other repository contents.

3) Ask the Sourcehut team to allow aliased clone URLs with a `.git` suffix. I'll do this. I guess this should be relatively simple to implement, but I don't really know. A downside of this approach is that it's exclusive to a specific Git hosting provider.

4) Ask the Sourcehut team to provide a Git server. I don't think that's feasible. IMHO it wouldn't make sense to deploy a Git server specifically for clients that can't access Git URLs as such. After all, if a repo is hosted on `git.sr.ht`, it's already "obvious" that it's a Git repo.

5) Use a different hosting service that already works with `raco pkg install`. I'd rather not do this because I like the values of Sourcehut, see https://sourcehut.org/ .

**Do you want to contribute to this feature**
I'm a relative beginner with Racket, so I _probably_ won't be able to make the needed code changes. That said, I would participate in further discussions.

**Additional context**
- A change in `raco pkg install` would only help users that have this new `raco pkg install` command. So at the earliest, this would go into the next Racket release. Furthermore, users who want to benefit from the suggested `raco` enhancement would need to update their Racket installation. (But this applies to any enhancement you want to use.)
- There has been a specific fix to the Sourcehut repo pages to [support specific Go features](https://todo.sr.ht/~sircmpwn/git.sr.ht/130), so I'm somewhat confident supporting a `.git` suffix alias would be ok for them, too.
- There's a [more generic ticket for Sourcehut](https://todo.sr.ht/~sircmpwn/git.sr.ht/163), but it seems this hasn't been implemented so far. Also the suggested `link` element isn't a proper standard, as far as I understand, and it also would need changes to `raco`. Moreover, this would require that all hosting providers which don't work with `raco` would need to add this `link` element. Still, this may be a cleaner change than trying Git cloning and possibly falling back to a plain HTTP URL.

**Comment by sschwarzer** [comment]
I sent an [email](https://lists.sr.ht/~sircmpwn/sr.ht-discuss/%3C1795b4ed-0cdb-d8ba-0909-5f3b301f9239%40sschwarzer.net%3E) to the Sourcehut discussion list to hopefully get the `.git` suffix aliasing implemented.

**Comment by sschwarzer** [comment]
> I sent an [email](https://lists.sr.ht/~sircmpwn/sr.ht-discuss/%3C1795b4ed-0cdb-d8ba-0909-5f3b301f9239%40sschwarzer.net%3E) to the Sourcehut discussion list to hopefully get the `.git` suffix aliasing implemented.

The [answer](https://lists.sr.ht/~sircmpwn/sr.ht-discuss/%3C1795b4ed-0cdb-d8ba-0909-5f3b301f9239%40sschwarzer.net%3E) (further down) is pretty clear.

**Comment by rfindler** [comment]
Ouch.

**Comment by sschwarzer** [comment]
Here's a proposal for discussion:
- Specifying a protocol and a server/path should be separate. `raco` shouldn't assume a protocol from the path if possible.
- URLs can have a protocol part like `https://` (plain HTTPS directory), `git://` (Git protocol, already supported) or `git+https://` for Git over HTTPS. The Python package manager, pip, already [supports various combinations](https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support), which we could use, too.
- The current URL path/specifications should remain supported by raco with their current meanings, for backward compatibility.

**Comment by mflatt** [comment]
I like the `git+https` proposal, especially give that there's a precedent.

**Comment by mflatt** [comment]
I've pushed the `git+https://` change on the client side, so it's ready to try out.

At the point where we become sure this is the right idea, pkgd.racket-lang.org will need to update to this version of the "pkg" collection.

And then maybe the server's web inteface's Git source-creation helper should be updated somehow to offer the option of a `git+hhtps://` path, but I expect that the box where you can type a literal package source would work without changes.

**Comment by sschwarzer** [comment]
@mflatt That was quick! :+1:

The change works for me, I was able to install my `todo-txt` package from https://git.sr.ht/~sschwarzer/todo-txt .

**Comment by sschwarzer** [comment]
To continue with this ticket, what's to be done?
- The actual support for the `git+https` scheme in `raco pkg install` is in place. Does this need to be added anywhere else in `raco`?
- Do we need tests for the new URL scheme? Are there tests for the other URL formats?
- The documentation at https://docs.racket-lang.org/pkg/Package_Concepts.html#%28part._concept~3asource%29 / https://github.com/racket/racket/blob/master/pkgs/racket-doc/pkg/scribblings/pkg.scrbl needs to be updated.
- The package server needs to be updated.
- Anything else?

If we want to keep the enhancement in `raco pkg install` (it looks like it :-) ), I could give the documentation change a try. Or is someone already working on this?

Where's the source code for the package server? (I'm not sure if I can help here, but I could have a look.)

**Comment by samth** [comment]
#3749 already has tests and documentation updates -- is there something in particular you think is missing?

Updating the pkg server to use the current Racket should take care of most things there, but maybe user interface changes would be good. The interface is at https://github.com/racket/racket-pkg-website/

**Comment by sschwarzer** [comment]
@samth I missed the documentation update. Awesome that this is already done! :-)

**Comment by mflatt** [comment]
Between the v8.1 release and updated to the package-server interface, I think this is all in place.

Although the package server is apparently having some issues (racket/racket-pkg-website#76), I think that's probably unrelated.
