### ISSUE TITLE
'module-variable-provides and possibly other syntax properties missing from expanded modules

### ISSUE THREAD

**Issue by Runi-c** [racket/racket#3750]
**What version of Racket are you using?**
8.0 [cs]

**What program did you run?**
```racket
#lang racket/base
(require syntax/modread)

(define in (open-input-string "#lang racket/base (define (a) 3) (provide a)"))

(define stx
  (parameterize ([current-namespace (make-base-namespace)])
    (expand (with-module-reading-parameterization
              (λ () (read-syntax #f in))))))

(syntax-property-symbol-keys stx)
```

Output:
![image](https://user-images.githubusercontent.com/5150427/113108031-ca14ab80-91c1-11eb-83e0-3aa2bdc0f833.png)

**What should have happened?**
I expect all the keys defined in [the docs](https://docs.racket-lang.org/reference/Expanding_Top-Level_Forms.html#%28part._modinfo%29) on expanded module syntax, especially `'module-variable-provides` - but this key seems to be missing despite the sample module providing a procedure `(a)`.

**Please include any other relevant details**
Explicitly providing a `(module)` instead of a lang directive produces the same behavior.
A [codebase search](https://github.com/search?l=&q=%22%27module-variable-provides%22+user%3Aracket&type=code) under the racket GitHub user seems to show all uses of the key `'module-variable-provides` under the `old-plt` repo. Perhaps it got accidentally removed?

**Comment by mflatt** [comment]
You're right that the properties were lost, but it was with the macro expander rewrite of version 7.0. Only the `'module-body-context`, `'module-body-inside-context`, and `'module-body-context-simple?` properties were kept.

Since we haven't missed the properties before, I'm inclined to correct the documentation. But did you have a particular case where you need the missing properties?

**Comment by Runi-c** [comment]
I was investigating supported means of determining an expanded module's provided and required symbols for the purpose of providing language features in https://github.com/jeapostrophe/racket-langserver (go to definition, rename symbol, etc). This seemed like the exact point to look for, but if there's a better way of getting this information now I'd love to hear it.

**Comment by rfindler** [comment]
Probably you want to use the same library that DrRacket and Emacs mode use: https://docs.racket-lang.org/drracket-tools/Accessing_Check_Syntax_Programmatically.html

**Comment by Runi-c** [comment]
Yeah we're already using Check Syntax traversals, though I think I was having problems with `add-definition-target` being unreliable. It does probably obsolete this syntax property though.

**Comment by greghendershott** [comment]
As @rfindler said `drracket/check-syntax` supplies many interesting things. I recommend using it when possible, for instance for "go to definition" or "rename within one file".

If you need more things, you can supplement it.

- If you're interested in _all_ exported or imported bindings, even if they're not yet used -- and therefore check-syntax won't draw an arrow to or from them -- you can use things like `module->exports` and `module->imports`. You might want this for completion candidates.
 
- More generally, that fully-expanded syntax (`stx` in your example code screen shot above)? You can both:
    - Give it to check-syntax and get its answers.
    - Analyze the syntax yourself (using e.g. `syntax-case*` much like `drracket-lib/private/traversals.rkt` does).

**Comment by rfindler** [comment]
And if you're finding bugs in the information that is coming out of drracket/check-syntax, please let us know!

**Comment by mflatt** [comment]
It seems that DrRacket tools (as abstracted from DrRacket itself) is the way to go, and any needed improvements could be there. Meanwhile, I've updated the documentation.
