### ISSUE TITLE
Package registration incorrectly assumes .git suffix

### ISSUE THREAD

**Issue by williewillus** [racket/racket#3763]
Please redirect if this belongs elsewhere. Relates to #3747.

The flow for creating a new package on pkgs.racket-lang.org incorrectly attaches a `.git` suffix to repository URLs.

In the package creation flow, I see this:
![image](https://user-images.githubusercontent.com/2015032/113813762-1e75d900-9736-11eb-8fd4-741b4f00ee58.png)

However, once I save, `.git` is added to the end of the repository. This is nonstandard, and my code forge (SourceHut) does not support it.

So there are two issues here:
1. The URL preview is not accurate
2. There should be a way to tell the interface to not add that suffix automatically. For one of my other packages, I've resorted to setting up a GitHub mirror which is kind of a hassle.

Package in question: https://pkgd.racket-lang.org/pkgn/package/rfc8949

**Comment by samth** [comment]
cc @jeapostrophe @tonyg

**Comment by jeapostrophe** [comment]
We'll work on it. For now, you can just use the `Simple URL` option and then type in exactly what you want. The `Git Repository` helper is intended to be a quick helper for the majority of users.

**Comment by williewillus** [comment]
Cool, thanks. I was under the impression "Simple URL" meant a direct zip download of the code, not a git repository.

**Comment by jeapostrophe** [comment]
Nope, it just means "Don't use a wizard"

**Comment by williewillus** [comment]
I tried using Simple URL and things still failed: https://pkg-build.racket-lang.org/server/built/archive-fail/rfc8949.txt

**Comment by samth** [comment]
You will need to use the `git+https` scheme added in #3749 to make that work. Note that the scheme is not supported in 8.0, so it won't work for the current pkg-build server and will probably not work for pkgs.racket-lang.org to fetch the checksum until the server is upgraded.

**Comment by williewillus** [comment]
Cool, thanks. I'll set up a github mirror in the meantime.
