### ISSUE TITLE
commenting out a region of code

### ISSUE THREAD

**Issue by hblazeviczx6r** [racket/racket#3764]
Hi,
Have just installed Racket 8.0 on fedora 33, and have found our that region comment out does not work (both ; and box comment). Everything else apparently works. After a couple of hours of programming, i did not find any other issues.

Hrvoje

**Comment by maueroats** [comment]
Can you provide more information?

* How did you install Racket? (Download from the internet? Pre-packaged for your distribution?) 
* What does it say in the About Racket box?
* Can you provide a very specific example of what happens when you see region commenting "not work"? 

Are there any more details you can provide about your setup? 

Details matter in tracking down a problem like this - when I try to reproduce without the details, I can't.

**Comment by hblazeviczx6r** [comment]
Last time I was seriously using Racket was some 6-7 months ago when I
was working through HTDP2 and Realm of Racket. At that time I had
Racket 7.X installed on Manjaro Linux, and everything (at least
everything that I'm using in IDE) was working. After  that I installed
Fedora 33 on my computer. I also installed Racket (7.X) and the same
problem as now appeared (commenting out not working). However since I
was not using Scheme at all that time (learning Python now), I did not
bother to report, thinking that probably the new version of Racket is
going to fix this anyway.
But when I installed v.8.0 few days ago, the first thing I tested was
comments, and it still doesn't work.
BTW: I installed (as always) by downloading from
download.racket-lang.org, and did not change any decisions in
installation process. It is installed in standard UNIX style.

As for commenting out, I proceed as countless times before by marking
the region of code with the mouse (highlights in blue) and then click
in the Racket menu on Comment Out with Semicolons. And absolutely
nothing happens. Same if I try Comment out with a Box.

What does it say in the About Racket Box?
Well: Welcome to DrRacket, version 8.0, english by PLT.
And then a lot of other stuff...

**Comment by maueroats** [comment]
Unable to reproduce.

* Clean install of fedora 33
* Update all packages
* Installed DrRacket in /usr unix-style install by downloading the sh file from racket-lang.org 
* Run DrRacket
* Set language "determine language from source"
* Type some stuff and select it.
* Racket -> Comment out with box
A comment box appears containing the selected material.

Conclusion: something in your local setup is causing these problems.

**Comment by rfindler** [comment]
Can you do a screen capture / movie @hblazeviczx6r ? Maybe we'll be able to spot something that would help us figure out what's going on if we can see what you see, in its full detail.

**Comment by hblazeviczx6r** [comment]
OK, have uninstalled Racket, then downloaded and installed racket
again, no change.

**Comment by sorawee** [comment]
As @robby said, a screen recording showing the problem would be very nice. Here's my recording of the "Comment Out with Semicolons" feature:

![Untitled2](https://user-images.githubusercontent.com/9099577/114339333-1e833800-9b7f-11eb-8688-5aebb28b8691.gif)

**Comment by hblazeviczx6r** [comment]
Have tried to attached two screenshots and a video from the phone, but
it is apparently too large.

Maybe it is something with Fedora. Actually the only reason I switched
from Manjaro to Fedora is because Emacs did not look nice on Manjaro,
and I spend most of my programming time in Emacs (even Scheme, except
Racket).
Fedora seems to be the least convenient distro  for programmers.

**Comment by hblazeviczx6r** [comment]
I just upgraded fedora to v.34 hoping that updated version might
resolve the commenting problem. It did not!
So I removed the Racket from my computer and then did a fresh install,
by building completely from Racket Unix source. Even this did not
help.
Commenting out (with semi-columns or box) simply does nothing. Not
only that, but it looks like the whole portion of Racket menu
(Reindent, Reindent All, Comment out with a Box, Comment out with
Semicolons, Uncomment) does absolutely nothing.
The rest of Racket menu entries seem to work. I tested Create
Executable, and this works.

**Comment by maueroats** [comment]
You still need to post a video. Upload it to a github repo.

**Comment by hblazeviczx6r** [comment]
OK, I found out how to record it on computer, so here it is.

**Comment by sorawee** [comment]
I could not see anything... I see that you are replying through email, so that is likely the culprit. Can you use the GitHub interface instead?

**Comment by hblazeviczx6r** [comment]
https://user-images.githubusercontent.com/73069309/116664029-7963be80-a9ca-11eb-9ca4-f76141765a2f.mov

**Comment by sorawee** [comment]
That indeed looks like a bug.

**Comment by hblazeviczx6r** [comment]
Sorry about this closing/reopening. Obviously I don't know how to use this.
As for the video I sent before it was some format that is not accepted by github. Now I made a new video and have converted it to .mov format.
Anyway, trhere is nothing to see.

**Comment by rfindler** [comment]
What does this program produce for you, @hblazeviczx6r ?

```
#lang racket
(require framework)

(define t (new racket:text%))
(send t insert "a\nb")
(send t set-position 0 (send t last-position))
(send t comment-out-selection)
(send t get-text)
```

**Comment by hblazeviczx6r** [comment]
produces:

Welcome to DrRacket, version 8.0 [cs].
Language: racket, with debugging; memory limit: 1024 MB.
#t
";a\n;b"
>

**Comment by rfindler** [comment]
Well, that's what the menu callback does, so I guess that somehow the callback isn't happening?

**Comment by capfredf** [comment]
will `racket -l drracket` show more information about this error?

**Comment by hblazeviczx6r** [comment]
This showed after I opened Racket entry on menu:

Gdk-Message: 21:24:04.771: Window 0x1469b90 is a temporary window
without parent, application will not be able to position it on screen.
Gdk-Message: 21:24:04.976: Window 0x1469b90 is a temporary window
without parent, application will not be able to position it on screen.

**Comment by jbclements** [comment]
Ooh, sounds like maybe an error dialog that can't be displayed? Sorry, I should go back to lurking here, but I admit I'm really curious about this bug.

**Comment by hblazeviczx6r** [comment]
More news about the same problem.
I got tired of this problem, so I trashed fedora and first installed
Ubuntu 21.04, and then Manjaro 21. (All on Gnome). I immediately
tested DrRacket on both, and both showed the same problem! Everything
else (I mean all other programs (like Chez in Emacs, or Python in
Emacs) works normally. The strangest thing is that when I was working
with HTDP2 (maybe a year ago) there were no problems, on both Ubuntu
20.04, or Manjaro 20.. Well, really not nothing. After commenting with
a box, shading (parentheses matching) would stop working, but for
that, I simply stopped using box comments.

**Comment by rfindler** [comment]
> Ooh, sounds like maybe an error dialog that can't be displayed? Sorry, I should go back to lurking here, but I admit I'm really curious about this bug.

Looking at the code that shows errors, it [first tries the print the error to stderr](https://github.com/racket/drracket/blob/master/drracket/drracket/private/init.rkt#L95-L100) (although it does swallow any errors that happen during that printing) before opening the dialog.

**Comment by hblazeviczx6r** [comment]
I tried to remember which distro, was I using last year when Racket
was fully working. It was Ubuntu 20.04 (by now a year old version). So
I trashed everything again, and installed back Ubuntu 20.04.02. And
magic... Racket menu works (both on ubuntu installed v7.2, and my
install of v8.0)

So it must be something in these new versions, because all behave the
same (Fedora 33, Fedora 34, Manjaro 21, Ubuntu 21.04). Maybe, just
maybe it has something to do with Wayland. The new ones all use
Wayland, but ubuntu 20.04, does not.

**Comment by samth** [comment]
Aha, @hblazeviczx6r, that's it! I run Wayland, and I just tried using "Comment out with semicolons" and it indeed doesn't work. I don't get any error messages on the command line either.  The test program that @rfindler provided works correctly, though.

**Comment by rfindler** [comment]
I guess the next obvious culprit to explore is the racket/gui handling of menus?

**Comment by samth** [comment]
I just tried out all the menu entries in the Racket menu. None of the ones in the section with "Comment out with semicolons" seem to work, but all the other ones do (Run, Module Browser, etc).

**Comment by mflatt** [comment]
It looks like Wayland makes the keyboard focus leave the editor when the menu is clicked. Also, it looks like the non-working menu items use `get-focus-object` instead of `get-edit-target-object`. Using `get-edit-target-object` (like most other things in DrRacket) fixes the problem.

**Comment by rfindler** [comment]
Thanks!
