### ISSUE TITLE
Please provide a (convenient) way to link against system zlib and lh4

### ISSUE THREAD

**Issue by bremner** [racket/racket#3769]
**What version of Racket are you using?**
 8.0 [cs]

Like many linux distros, in Debian we try to avoid embedded code copies when possible (they complicate our security support process, for one thing). I understand that the copy of ChezScheme is at least in the medium term needed, but it seems that it turn embeds copies of zlib and lh4.  I tried deleting the copies at build time,  and that seems to work, but is a bit messy. It would be nice to have a top level configure switch to force the use of the system libraries. Another option would be to delete the embedded compression libraries in ChezScheme, or just to default to the system libraries if they are found.

**Comment by mflatt** [comment]
The `configure` flags intended for that are `--enable-libz` and `--enable-liblz4`.

**Comment by bremner** [comment]
Are these options documented somewhere? src/configure --help doesn't seem to know about them.

**Comment by samth** [comment]
If you look at the output of `racket/src/configure --help`, it suggests `--help-bc` and `--help-cs`; the `--help-cs` output mentions those options.

**Comment by bremner** [comment]
Oops, my bad. I could have sworn I tried that, but obviously not.
