### ISSUE TITLE
Node JS/NPM style package installations

### ISSUE THREAD

**Issue by koratkar** [racket/racket#3772]
In the NodeJS/NPM development environment, the packages can be installed locally where the code is being written. I think that could be useful for racket projects. Something like `raco -l` would make sense.
Thanks!

**Comment by rfindler** [comment]
This is supported via `raco pkg install directory/` where `directory` is
the place with the pkg on your filesystem. (There are other ways to do it
too but that's a convenient one.)

Robby

**Comment by rfindler** [comment]
This is supported via `raco pkg install directory/` where `directory` is the place with the pkg on your filesystem. (There are other ways to do it too but that's a convenient one.)

**Comment by koratkar** [comment]
Cool, thanks!

**Comment by rfindler** [comment]
If you have questions about how to do stuff with racket, check out the [users@ mailing list](https://lists.racket-lang.org/).
