### ISSUE TITLE
cs: build failure on debian ppc64el

### ISSUE THREAD

**Issue by bremner** [racket/racket#3773]
**What version of Racket are you using?**
8.0 [cs] 

**If you got an error message, please include it here.**
Full log:
[ppc64el.txt](https://github.com/racket/racket/files/6290141/ppc64el.txt)
Tail:
```
echo '(reset-handler abort)'\
             '(base-exception-handler (lambda (c) (fresh-line) (display-condition c) (newline) (reset)))'\
             '(keyboard-interrupt-handler (lambda () (display "interrupted---aborting\n") (reset)))'\
             '(optimize-level 3)'\
             '(debug-level 0)'\
             '(commonization-level (commonization-level))'\
             '(fasl-compressed #t)'\
             '(compress-format (compress-format))'\
             '(compress-level (compress-level))'\
             '(generate-inspector-information #t)'\
             '(subset-mode (quote system))'\
             '(compile-file "cmacros.ss" "cmacros.so")'\
             | ../../pb/bin/pb/scheme -q
bytes_per_segment (4000) < S_pagesize (10000)
Aborted
```
**Please include any other relevant details**

OS: debian GNU/Linux ppc64el

**Comment by mflatt** [comment]
There's not currently a PPC64 backend for Chez Scheme.

**Comment by bremner** [comment]
OK, good to know. I guess some configuration fine tuning might be in order, since to my untrained eye it looks like it misdetects the host as ppc32. 
Is the best source of documentation for which architectures are supported by the Chez Scheme backend the files in `src/ChezScheme/s`, or is there a definitive list of os/architecture combos somewhere else?

**Comment by mflatt** [comment]
I bet you're right that the platform is misdetected as ppc32. Generally, the platform-detection approach isn't well defined for unsupported platforms.

The list of supported platforms is kept in "ChezScheme/README.md": https://github.com/racket/racket/blob/master/racket/src/ChezScheme/README.md

**Comment by mflatt** [comment]
I've changed configure scripts to make them more likely to detect an unsupported platform for Racket CS and to provide a more useful error message in that case.

I considered trying to make the main configure script select BC by default for an platforms that are not supported by CS. I decided against that, both because it's tricky and on the grounds that selecting BC should be more explicit.

**Comment by bremner** [comment]
Matthew Flatt ***@***.***> writes:

> I've changed configure scripts to make them more likely to detect an unsupported platform for Racket CS and to provide a more useful error message in that case.
>
> I considered trying to make the main configure script select BC by
> default for an platforms that are not supported by CS. I decided
> against that, both because it's tricky and on the grounds that
> selecting BC should be more explicit.

FWIW, we're already selecting BC explicitely in Debian for the currently
unsupported platforms. This works fine, although I guess it means we'll
probably miss new Racket CS platforms until someone complains.

d
