### ISSUE TITLE
Dr Racket V8.0 - Program won't start

### ISSUE THREAD

**Issue by Marshwiggle1** [racket/racket#3774]
Hi I am a beginner student keen to keep on with my studies but cannot get Dr Racket to work.
I was able to work with this program yesterday and the day before (I kept the widow open), but have been unable to to today (window disappeared and haven't been able to get it to open).
 
The loading screen pops up, and I have the open process in my tool bar and in task manager but I am unable to open any window to work in. Anyone else had this issue? 
Rebooting and uninstalling and reinstalling the program did not solve the issue. I am on the latest Windows Pro 10.0.19042 and have double checked I am on the 64 version, not 32.

**Comment by mfelleisen** [comment]
Are you on Windows 10? Is it possible that the DrRacket window is "outside" the laptop screen?

**Comment by Marshwiggle1** [comment]
Hi, thanks for your reply. I'm on Windows 10. Screen res is 1920 x 1080, which is the default setting. How would I check if it is outside the screen? There isn't anything I can grab with my cursor.

**Comment by mfelleisen** [comment]
Does this [bring window back to screen](https://www.technipages.com/bring-off-screen-window-back-onto-screen) help?

**Comment by Marshwiggle1** [comment]
Hello,  Yes that did help, not sure why it did that, but relieved I can keep working away. Thank you for your help.

**Comment by mfelleisen** [comment]
Next time ask on @users, the Racket mailing list.

**Comment by Marshwiggle1** [comment]
Thanks again, I had no idea it existed.
