### ISSUE TITLE
`(make-custodian)` prevents subprocess custodian from cleaning up

### ISSUE THREAD

**Issue by wilbowma** [racket/racket#3782]
**What version of Racket are you using?**
 v8.0.0.11 [cs].

**What program did you run?**
Please include a short example that triggers the bug

```
#lang racket

;; Run like: racket -t meow.rkt; pgrep -a racket

Welcome to Racket v8.0.0.11 [cs].
(require racket/engine)

(define exe-path (find-executable-path "racket"))

(define (doit)
  (parameterize ([current-subprocess-custodian-mode 'kill])
    (let ([e (engine (lambda (_)
                       (system*/exit-code
                        exe-path
                        "-e"
                        "((lambda (x) (x x)) (lambda (x) (x x)))")))])
      (if (engine-run 1000 e)
          (void)
          (begin
            (displayln "Timed out"))))))
;; When uncommented, this process terminates when "meow.rkt" terminates.
#;(doit)

;; When uncommented, this process terminates does NOT terminate the subprocess when "meow.rkt" terminates.
(parameterize ([current-custodian (make-custodian)])
  (doit))
```

**What should have happened?**
After the process exits, the subprocess `racket -e '((lambda (x) (x x)) (lambda (x) (x x)))'` should have been killed by the custodian. However, this does not happen if a new custodian has been created with `make-custodian`.

**Please include any other relevant details**
Running via `racket -t meow.rkt; pgrep -a racket`, which shows the still running subprocess after the racket process terminates.

cc @jackfirth

**Comment by mflatt** [comment]
Thanks for the report!
