### ISSUE TITLE
simple place example generates system error: Too many open files; errno=24

### ISSUE THREAD

**Issue by nmosier** [racket/racket#3784]
**What version of Racket are you using?**
8.0 [cs]

**What program did you run?**
This is the example code found on the [Racket documentation for Places](https://docs.racket-lang.org/reference/places.html?q=places).

```
#lang racket

(provide place-main)
 
(define (place-main pch)
  (place-channel-put pch (format "Hello from place ~a"
  (place-channel-get pch))))


(let ([pls (for/list ([i (in-range 2)])
  (dynamic-place "place-worker.rkt" 'place-main))])
  (for ([i (in-range 2)]
          [p pls])
     (place-channel-put p i)
    (printf "~a\n" (place-channel-get p)))
  (map place-wait pls))
```

**What should have happened?**
Hello from place 0
Hello from place 1

**If you got an error message, please include it here.**
open-input-file: cannot open module file
  module path: syntax/readerr
  path: /Applications/Racket v8.0/collects/syntax/compiled/readerr_rkt.zo
  system error: Too many open files; errno=24
open-input-file: cannot open module file
  module path: racket/local
  path: /Applications/Racket v8.0/collects/racket/compiled/local_rkt.zo
  system error: Too many open files; errno=24
invalid memory reference.  Some debugging context lost
open-input-file: cannot open module file
  module path: /Applications/Racket v8.0/collects/racket/private/for.rkt
  path: /Applications/Racket v8.0/collects/racket/private/compiled/for_rkt.zo
  system error: Too many open files; errno=24
open-input-file: cannot open module file
  module path: /Applications/Racket v8.0/collects/racket/private/unit-contract.rkt
  path: /Applications/Racket v8.0/collects/racket/private/compiled/unit-contract_rkt.zo
  system error: Too many open files; errno=24
dynamic-place: error during stderr dup
  system error: Too many open files; errno=24
  context...:
   /Applications/Racket v8.0/collects/racket/private/place.rkt:107:0: start-place*
   /Applications/Racket v8.0/collects/racket/private/place.rkt:80:0: dynamic-place
   <dir>/place-worker.rkt:8:0
   body of "<dir>/place-worker.rkt"
invalid memory reference.  Some debugging context lost
open-input-file: cannot open module file
  module path: racket/sequence
  path: /Applications/Racket v8.0/collects/racket/compiled/sequence_rkt.zo
  system error: Too many open files; errno=24
open-input-file: cannot open input file
  path: /Applications/Racket v8.0/etc/config.rktd
  system error: Too many open files; errno=24
  context...:
   /Applications/Racket v8.0/collects/racket/private/kw-file.rkt:102:2: call-with-input-file*
   /Applications/Racket v8.0/collects/racket/promise.rkt:65:10
   /Applications/Racket v8.0/collects/racket/promise.rkt:45:2
   /Applications/Racket v8.0/collects/setup/private/dirs.rkt:53:15: config:installation-name
   /Applications/Racket v8.0/collects/racket/promise.rkt:65:10
   /Applications/Racket v8.0/collects/racket/promise.rkt:45:2
   /Applications/Racket v8.0/collects/setup/private/dirs.rkt:102:0: get-installation-name
   body of "/Applications/Racket v8.0/collects/planet/config.rkt"
open-input-file: cannot open module file
  module path: /Applications/Racket v8.0/collects/racket/splicing.rkt
  path: /Applications/Racket v8.0/collects/racket/compiled/splicing_rkt.zo
  system error: Too many open files; errno=24
open-input-file: cannot open module file
  module path: <dir>/place-worker.rkt
  path: <dir>/place-worker.rkt
  system error: Too many open files; errno=24
invalid memory reference.  Some debugging context lost
error closing stream port
  system error: Bad file descriptor; errno=9
open-input-file: cannot open module file
  module path: /Applications/Racket v8.0/collects/racket/contract/private/kwd-info-struct.rkt
  path: /Applications/Racket v8.0/collects/racket/contract/private/compiled/kwd-info-struct_rkt.zo
  system error: Too many open files; errno=24
open-input-file: cannot open module file
  module path: /Applications/Racket v8.0/collects/racket/contract/private/blame.rkt
  path: /Applications/Racket v8.0/collects/racket/contract/private/compiled/blame_rkt.zo
  system error: Too many open files; errno=24
invalid memory reference.  Some debugging context lost
open-input-file: cannot open module file
  module path: setup/cross-system
  path: /Applications/Racket v8.0/collects/setup/compiled/cross-system_rkt.zo
  system error: Too many open files; errno=24
open-input-file: cannot open module file
  module path: syntax/name
  path: /Applications/Racket v8.0/collects/syntax/compiled/name_rkt.zo
  system error: Too many open files; errno=24
invalid memory reference.  Some debugging context lost
open-input-file: cannot open module file
  module path: /Applications/Racket v8.0/collects/syntax/parse/experimental/contract.rkt
  path: /Applications/Racket v8.0/collects/syntax/parse/experimental/compiled/contract_rkt.zo
  system error: Too many open files; errno=24
open-input-file: cannot open module file
  module path: /Applications/Racket v8.0/collects/racket/private/qqstx.rkt
  path: /Applications/Racket v8.0/collects/racket/private/compiled/qqstx_rkt.zo
  system error: Too many open files; errno=24
open-input-file: cannot open module file
  module path: /Applications/Racket v8.0/collects/racket/private/serialize-structs.rkt
  path: /Applications/Racket v8.0/collects/racket/private/compiled/serialize-structs_rkt.zo
  system error: Too many open files; errno=24
dynamic-place: error during stderr dup
  system error: Too many open files; errno=24
  context...:
   /Applications/Racket v8.0/collects/racket/private/place.rkt:107:0: start-place*
   /Applications/Racket v8.0/collects/racket/private/place.rkt:80:0: dynamic-place
   <dir>/place-worker.rkt:8:0
   body of "<dir>/place-worker.rkt"
invalid memory reference.  Some debugging context lost
error reading from stream port
  system error: Bad file descriptor; errno=9
  context...:
   /Applications/Racket v8.0/collects/syntax/module-reader.rkt:186:17: body
   /Applications/Racket v8.0/collects/syntax/module-reader.rkt:183:2: wrap-internal
   /Applications/Racket v8.0/collects/racket/../syntax/module-reader.rkt:67:9: wrap-internal/wrapper
error closing stream port
  system error: Bad file descriptor; errno=9
invalid memory reference.  Some debugging context lost
dynamic-place: error during stdin pipe
  system error: Too many open files; errno=24
  context...:
   /Applications/Racket v8.0/collects/racket/private/place.rkt:107:0: start-place*
   /Applications/Racket v8.0/collects/racket/private/place.rkt:80:0: dynamic-place
   <dir>/place-worker.rkt:8:0
   body of "<dir>/place-worker.rkt"
invalid memory reference.  Some debugging context lost

**Please include any other relevant details**
e.g., the operating system used or how you are running the code.
macOS 10.14.6
`racket place-worker.rkt`

**Comment by sorawee** [comment]
IIUC, this works as intended, and the behavior is documented at https://docs.racket-lang.org/guide/parallelism.html#%28part._effective-places%29.

**Comment by mflatt** [comment]
As a further clarification, the original example is in two parts. The `let` form is not meant to be added to the module that defines `place-main`, but instead meant to be run separately (such as a in a REPL).

**Comment by LiberalArtist** [comment]
It might help to use [`filebox`](https://docs.racket-lang.org/scribble/Miscellaneous.html#(def._((lib._scribble%2Fmanual..rkt)._filebox))) in the documentation to emphasize that
```racket
#lang racket
(provide place-main)
 
(define (place-main pch)
(place-channel-put pch (format "Hello from place ~a"
(place-channel-get pch))))
```
should be saved in its own file.
