### ISSUE TITLE
Unbound identifier error when combining `struct` `#:name` and `#:constructor-name` with a contract

### ISSUE THREAD

**Issue by sschwarzer** [racket/racket#3791]
**What version of Racket are you using?**
8.0 [cs]

**What program did you run?**
```
#lang racket/base

(require racket/contract)

(provide
 (contract-out
  (struct Foo ([x integer?]))))

(struct foo (x)
  #:name Foo
  #:constructor-name Foo)

(define my-foo (Foo 1))

(displayln my-foo)
```

**What should have happened?**
The expected output should have been `#<Foo>` and no error message.

**If you got an error message, please include it here.**
`foo: unbound identifier in: foo` (with DrRacket highlighing the `foo` in the `struct` definition).

**Please include any other relevant details**
- I executed the above code in DrRacket (but had noticed it in another context)
- According to @mflatt , this is a bug in `struct`.
- Maybe other forms for struct definitions are affected as well?
- The bug only occurs when combining all three things, `#:name`, `#:constructor-name` and the contract.

**Comment by sschwarzer** [comment]
If that helps with debugging: The error doesn't occur if the names for `#:name` and `#:constructor-name` are different:
```
#lang racket/base

(require racket/contract)

(provide
 (contract-out
  (struct Foo ([x integer?]))))

(struct foo (x)
  #:name Foo
  #:constructor-name workaround-Foo)

(define my-foo (workaround-Foo 1))

(displayln my-foo)
```
displays `#<foo>`.

Unfortunately, this isn't a "complete" workaround since a redefinition `(define Foo workaround-Foo)` isn't possible because `Foo` is already defined.

**Comment by samth** [comment]
This comment mentions another issue with `contract-out` and `#:constructor-name` that may be related: https://github.com/racket/typed-racket/issues/1050#issuecomment-791622937

**Comment by capfredf** [comment]
A quick glance: the expanded code shows there is a bug in `struct` in `struct-out` when #:name is identical to #:constructor-name
<img width="990" alt="image" src="https://user-images.githubusercontent.com/512906/115060045-61157f00-9eb5-11eb-8980-46d5d0709312.png">
