### ISSUE TITLE
arithmetic-shift of large negative number with -32 produces 0

### ISSUE THREAD

**Issue by samth** [racket/racket#3794]
```
[samth@homer:~/sw/plt (toom3) racket-8.0] r
Welcome to Racket v8.0 [cs].
> (arithmetic-shift
-9745314011399999080353382387875188310876226857595007526867906457212948690766426102465615065882010259225304916231408668183459169865203094046577987296312653419531277699956473029870789655490053648352799593479218378873685597925394874945746363615468965612827738803104277547081828589991914110669
    -32)
0
```

Both -33 and -31 produce answers that look sensible.

The large number is close to the negation of a power of 2.

**Comment by gus-massa** [comment]
If I cut and paste the code in racket running in the command line (in Windows) the long number is truncated and the error disappears.

A shorted version with exactly the same number is

    (arithmetic-shift (- 307 (expt 16 240)) -32)  ; ==> 0 

The linklet after cp0 is

    (lambda (instance-variable-reference ...))
      ((#3%$top-level-value 'general-arithmetic-shift) -974...669 -32))

**Comment by mflatt** [comment]
I'll push a repair (and will upstream to cisco/ChezScheme).
