### ISSUE TITLE
It doesn't seem to support arm9?

### ISSUE THREAD

**Issue by NingShenTian** [racket/racket#3795]
make[3]: 进入目录“/home/ning/Project/CppProject/racket-8.0/src/build/cs/c”
env MAKE_BOOT_FOR_CROSS=yes SCHEME_SRC="../../../cs/c/../../ChezScheme" SCHEME_WORKAREA=ChezScheme MACH="tarm32le" racket -O 'info@compiler/cm' -l- setup --chain ../../../cs/c/../../setup-go.rkt ./compiled ignored ./ignored.d "../../../cs/c/../../ChezScheme"/rktboot/make-boot.rkt
Use /home/ning/Project/CppProject/racket-8.0/src/ChezScheme/rktboot/.
Use /home/ning/Project/CppProject/racket-8.0/src/ChezScheme/nanopass
Use /home/ning/Project/CppProject/racket-8.0/src/ChezScheme/s
Check ChezScheme/boot/tarm32le
Up-to-date
/bin/sh ../../../cs/c/reset_boot.sh tarm32le ChezScheme
cd ChezScheme && "../../../../cs/c/../../ChezScheme"/configure --machine=tarm32le --disable-x11 --disable-auto-flags --enable-warning-flags --disable-curses  CC="arm-linux-gcc" CFLAGS="-g -O2 -Wall  -DELF_FIND_BOOT_SECTION  -pthread" LDFLAGS="-pthread" LIBS="-ldl -lm  -lrt -liconv" AR="arm-linux-ar" ARFLAGS="rc" RANLIB="arm-linux-ranlib" WINDRES="windres"
Configuring for tarm32le
cd ChezScheme/tarm32le/c && make o=o cross=t
make[4]: 进入目录“/home/ning/Project/CppProject/racket-8.0/src/build/cs/c/ChezScheme/tarm32le/c”
arm-linux-gcc  -g -O2 -Wall -DELF_FIND_BOOT_SECTION -pthread -Wpointer-arith -Wall -Wextra -Werror -Wno-implicit-fallthrough -c -DARMV6 -I../boot/tarm32le -I../zlib -I../lz4/lib gc-011.c
/tmp/ccFPMflk.s: Assembler messages:
/tmp/ccFPMflk.s:31645: error： selected processor does not support ARM mode `ldrex r12,[r2,#0]'
/tmp/ccFPMflk.s:31647: error： selected processor does not support ARM mode `strex r7,r12,[r2]'
make[4]: *** [Mf-arm32le:27：gc-011.o] error 1
make[4]: 离开目录“/home/ning/Project/CppProject/racket-8.0/src/build/cs/c/ChezScheme/tarm32le/c”
make[3]: *** [Makefile:166：scheme-cross] error 2
make[3]: 离开目录“/home/ning/Project/CppProject/racket-8.0/src/build/cs/c”
make[2]: *** [Makefile:81：cs] error 2
make[2]: 离开目录“/home/ning/Project/CppProject/racket-8.0/src/build/cs/c”
make[1]: *** [Makefile:79：racketcs] error 2
make[1]: 离开目录“/home/ning/Project/CppProject/racket-8.0/src/build”
make: *** [Makefile:41：all] error 2

**Comment by pmatos** [comment]
Hi @NingShenTian , thanks for the report. Which board are you trying to compile this on?

**Comment by mflatt** [comment]
If ARM9 means https://en.wikipedia.org/wiki/ARM9, then it's true that it's not supported currently, since that's an ARMv4T machine. Racket CS requires ARMv6 or up. I think Racket BC should still build and run for ARMv4T, though.

**Comment by NingShenTian** [comment]
@pmatos it is nuc972

**Comment by NingShenTian** [comment]
@pmatos is nuc972

**Comment by NingShenTian** [comment]
> If ARM9 means https://en.wikipedia.org/wiki/ARM9, then it's true that it's not supported currently, since that's an ARMv4T machine. Racket CS requires ARMv6 or up. I think Racket BC should still build and run for ARMv4T, though.

thank you
