### ISSUE TITLE
Can't Launch DrRacket 8, 7.8 Normally on Mac

### ISSUE THREAD

**Issue by JustinCEO** [racket/racket#3800]
Hi,
Downloaded and installed the Racket 8 files appropriate for my Mac (an intel Mac running Big Sur 11.2.3).

Cannot launch Racket normally by double-clicking on DrRacket.app in the Racket 8.0 folder.

When i try to, I get the following in the system log:

`Apr 24 09:57:27 [redacted] com.apple.xpc.launchd[1] (application.org.racket-lang.DrRacket.514602823.514602829[58422]): Service exited with abnormal code: 1`

However, I can launch Racket if I Show Package Contents on DrRacket.app and then navigate to Contents/MacOS/DrRacket. It seems to work fine.

This is obviously only mildly annoying but still seemed worth reporting.

The issue affects version 7.8 as well but does not affect version 7.4, which launches normally. These are the only versions I have tested. I recall having this issue with Catalina as well before upgrading but don't currently have a Catalina install to test and confirm that.

Thanks!

**Comment by JustinCEO** [comment]
update: I tried opening Racket 8 on another Mac, which has the same version of Big Sur installed, and it opened fine, so this appears to be an issue that just affects one of my computers (a 2015 iMac)

**Comment by mflatt** [comment]
Hi — it sounds like you may be running into a problem that we see on some Mac installations (not most) where something like `xattr -d -r com.apple.quarantine "Racket v8.0"` is needed to remove a quarantine flag on the Racket installation, even though the distribution disk image is signed and notarized.

We still don't know why this sometimes happens. The phenomenon seemed to become much less common in versions of Mac OS before Big Sur, but if so, it has reappeared with Big Sur. When a machine gets into this state, it seems to stay there, even though other machines with the same configuration (as far as we can tell) will run DrRacket happily.

So, using `xattr` is the suggestion for now.

**Comment by JustinCEO** [comment]
Using `xattr` on `DrRacket.app` seemed to do the trick, thanks. Glad I asked - would have never figured that one out :)

**Comment by sorawee** [comment]
Issue resolved. Closing.
