### ISSUE TITLE
flush-output on closed output ports

### ISSUE THREAD

**Issue by rmculpepper** [racket/racket#3803]
In Racket CS (both 8.0 and a recent build from HEAD), `flush-output` does not check whether the output port is closed.

For example:

    > (define out (open-output-bytes))
    > (close-output-port out)
    > (flush-output out)
    ;; no error

On Racket 8.0 BC, the last expression raises the error "flush-output: output port is closed".

Calling `flush-output` on a closed ssl-output-port seems to enter a busy loop (100% cpu usage), but my guess is that's a consequence of the write procedure being called with broken invariants due to to the missing closed check.

**Comment by mflatt** [comment]
I notice also that automatic port flushing differs between BC and CS: both flush when the original input port is read, but BC only flushes the original output or error port when it's a terminal port, while CS flushes all kinds of ports as the original output or error port. I'm currently inclined to make CS match BC.
