### ISSUE TITLE
ssl input port fails to wake up

### ISSUE THREAD

**Issue by rmculpepper** [racket/racket#3804]
This occurs on a recent build of Racket CS.

Sometimes a read on an ssl-input-port blocks and fails to complete even when there ought to be data available. (That is, I believe the read should be able to complete; I know the network delivered some data, and I expect that Google probably tries not to send incomplete TLS packets.) When additional data arrives from the network (in this case, an timeout message from the server), the SSL input port finally does wake up.

My best guess is that the problem is in the use of `(mzssl-i mzssl)` as the base event in the "want read" case of `do-read` port function. (Currently, https://github.com/racket/racket/blob/master/racket/collects/openssl/mzssl.rkt#L1197.) If input is pumped from the underlying input port before that event being sync'd on, then it won't become ready.

I tried changing the base event from `(mzssl-i mzssl)` to `(choice-evt (mzssl-i mzssl) (port-progress-evt (mzssl-i mzssl)))`, and I haven't seen the issue since that change. I haven't made a PR for that change because not all ports support progress events and because there might be other related issues.

**Comment by mflatt** [comment]
Your analysis makes sense to me as long as some concurrent reads or writes are happening on the SSL ports. Is that the case, or is there some other way for input and output pumping to happen concurrent to waiting on input?

**Comment by rmculpepper** [comment]
There are writes and flushes happening in a separate thread. I was puzzled, because the writes probably should not be close enough to interfere, but it looks like `flush-output` always calls `flush-ssl`, which calls `pump-input-once`, so that's probably the cause.
