### ISSUE TITLE
Potential problem in12.1 Pattern-Based Syntax Matching of Racket References

### ISSUE THREAD

**Issue by zh4ui** [racket/racket#3807]
I'm new to Racket, and tying to understand syntax-case's supported patterns.

The current document (https://github.com/racket/racket/blob/cfa10d5f3079bd45351f3a2d5b3fcccb7214fe50/pkgs/racket-doc/scribblings/reference/stx-patterns.scrbl#L22) says:

```
               [pattern np-pattern
                        (pattern ...)
                        (pattern ...+ . np-pattern)
                        (pattern ... pattern ellipsis pattern ... . np-pattern)]
```

Shouldn't there be a `(pattern ... pattern ellipsis pattern ...)` in the middle? like

```
               [pattern np-pattern
                        (pattern ...)
                        (pattern ...+ . np-pattern)
===>                    (pattern ... pattern ellipsis pattern ...)
                        (pattern ... pattern ellipsis pattern ... . np-pattern)]
```

**Comment by soegaard** [comment]
Since `(foo . ())` is the same as `(foo)` and `()` is a legal np-pattern it is strictly not necessary 
to list that case - but I agree that it would be easier to read if the case were made explicit.

**Comment by sorawee** [comment]
Unless I misread, `np-pattern` can't be `()`.

**Comment by soegaard** [comment]
I think `np-pattern` can be a `const` which in turn can be `()`.

**Comment by zh4ui** [comment]
If `np-pattern` can be a `const`, then perhaps `(pattern ...)` shall not be necessary?

What really does the `np` in `np-pattern` stand for? Didn't find a clue in the document.

**Comment by sorawee** [comment]
I believe `np` stands for "not pair". The text also supports this:

> The final np-pattern never matches a syntax object whose datum is a pair.

And yeah, reading this again, I now agree with @soegaard that `np-pattern` can stand for `()`.

**Comment by zh4ui** [comment]
Thanks for the comments, I'm closing it.
