### ISSUE TITLE
Recommend ratnum algorithms from Section 4.5.1 of Knuth's TAOCP

### ISSUE THREAD

**Issue by gambiteer** [racket/racket#3816]
This isn't really a bug, just a recommendation.

**What version of Racket are you using?**
Welcome to Racket v8.1.0.5 [cs].

**What program did you run?**
Please include a short example that triggers the bug
```
heine:~/programs/racket> /usr/local/racket/bin/mzscheme
Welcome to Racket v8.1.0.5 [cs].
> (define (phi n)
    (do ((i 0 (+ i 1))
         (r 1 (+ 1 (/ r))))
        ((= i n) r)))
> (define a (time (phi 100000)))
cpu time: 10142609 real time: 10152424 gc time: 40
```

**What should have happened?**

It can run quite a bit faster.

Gambit's ratnum routines are based on the basic algorithms from Section 4.5.1 of Knuth's TAOCP.  They're written in Scheme, are fairly short, and should be easy to adapt to the new Racket CS runtime.  If you want to use them as is (which seems possible, with Chez's naming convention, etc.), please do.  They start at

https://github.com/gambit/gambit/blob/ead2ba415b5c4cae9bb0f4505e3e359a97f00ad7/lib/_num.scm#L10722

The same program in Gambit is
```
heine:~/programs/racket> gsi
Gambit v4.9.3-1390-g9267589b

> (define (phi n)
  (do ((i 0 (+ i 1))
       (r 1 (+ 1 (/ r))))
      ((= i n) r)))
> (define a (time (phi 100000)))
(time (phi 100000))
    0.363497 secs real time
    0.363390 secs cpu time (0.355362 user, 0.008028 system)
    184 collections accounting for 0.027910 secs real time (0.027315 user, 0.000600 system)
    132009416 bytes allocated
    2579 minor faults
    no major faults
```
Brad

**Comment by samth** [comment]
Hi Brad,

Thank you for the suggestion!

I was interested in some of the other algorithms you've written in Gambit (in particular FFT multiplication), but I had a question about the license. In particular, it's unclear to me from the Gambit repository/docs if everything in the repository is available under the Apache License, or if it's under the LGPL, or something else (those are the two licenses whose source appears in https://github.com/gambit/gambit).

**Comment by gambiteer** [comment]
It’s your choice.

I’d welcome any improvements you might find.

Brad

On May 5, 2021, at 9:13 PM, Sam Tobin-Hochstadt ***@***.******@***.***>> wrote:



Hi Brad,

Thank you for the suggestion!

I was interested in some of the other algorithms you've written in Gambit (in particular FFT multiplication), but I had a question about the license. In particular, it's unclear to me from the Gambit repository/docs if everything in the repository is available under the Apache License, or if it's under the LGPL, or something else (those are the two licenses whose source appears in https://github.com/gambit/gambit).

**Comment by samth** [comment]
Thanks! I'll have a look.

**Comment by mflatt** [comment]
The low-hanging fruit for this example is that `/` lacks a special case for `(/ 1 <exact-rational>)` (or `(/ -1 <exact-rational>)`). I'd like to fix that now, while Sam looks into more interesting improvements.

**Comment by samth** [comment]
I wrote the special cases as well (which did indeed provide a big speedup for @gambiteer's example).

**Comment by samth** [comment]
One other question for @gambiteer -- I assume gambit has a bunch of tests for the correctness of arithmetic routines; can you point me to them?

**Comment by gambiteer** [comment]
They're in `gambit/tests/unit-tests/`.  I attempted to do some test coverage of `_num.scm` in `gambit/tests/unit-tests/03-number/_num.scm`, but it's not complete.  The other files are smaller, in Marc's style of unit tests.

**Comment by gambiteer** [comment]
PS:  I made a comment in https://github.com/racket/racket/commit/e368f9e22b29cf3be52b543d39940a03092219cb about it being better to implement mixed ratnum-integer operations by converting the integers to unnormalized ratnums and then using the existing ratnum algorithms rather than doing some special cases by hand and then applying `integer/`.

**Comment by samth** [comment]
I saw that; I think https://github.com/racket/racket/pull/3818/commits/49b486850638e052d5bc53a379f04deebdbfb85e does that.
