### ISSUE TITLE
[CS] build failure "out of memory" - [BC - builds successfully]

### ISSUE THREAD

**Issue by hopkinsr** [racket/racket#3819]
**What version of Racket are you using?**
* 8.0 and 8.1 [cs] both fail during `gmake`
* 8.0 and 8.1 [bc] succeed with  `gmake && gmake install` using `--enable-bconly`

**What program did you run?**
The usual `configure && make` cycle on a plain/fresh OpenBSD 6.9 amd64 on

* physical with 2GB RAM
* VirtualBox with 2GB, then 4GB then 8GB RAM- same issue

The shell script below reproduces the issue

```shell
#!/bin/sh
# NOTE: It installs GNU make using pkg_add - you can remove the line if you already have it.
su root -c 'pkg_add gmake'
ftp https://mirror.racket-lang.org/installers/8.1/racket-8.1-src-builtpkgs.tgz
tar xzf racket-8.1-src-builtpkgs.tgz
cd racket-8.1/src
mkdir build
cd build
../configure
gmake
```

**What should have happened?**
A successful build that produces the Racket executables

**If you got an error message, please include it here.**
```shell
gmake
# ...
mkdir -p ../boot/ta6ob
gmake -f Mf-boot ta6ob.boot o=3 d=0 what=all
rm -rf ../xc-ta6ob
( cd .. ; "../../../../cs/c/../../ChezScheme"/workarea ta6ob xc-ta6ob pb )
( cd ../xc-ta6ob/s ; gmake -f Mf-cross base=../../pb m=pb xm=ta6ob )
ln -s "../../../../../../cs/c/../../ChezScheme"/s/patch.ss patch.ss
ln -s "../../../../../../cs/c/../../ChezScheme"/s/cmacros.ss cmacros.ss
ln -s "../../../../../../cs/c/../../ChezScheme"/s/layout.ss layout.ss
echo '(reset-handler abort)'\
             '(base-exception-handler (lambda (c) (fresh-line) (display-condition c) (newline) (reset)))'\
             '(keyboard-interrupt-handler (lambda () (display "interrupted---aborting\n") (reset)))'\
             '(optimize-level 3)'\
             '(debug-level 0)'\
             '(commonization-level (commonization-level))'\
             '(fasl-compressed #t)'\
             '(compress-format (compress-format))'\
             '(compress-level (compress-level))'\
             '(generate-inspector-information #t)'\
             '(subset-mode (quote system))'\
             '(compile-file "cmacros.ss" "cmacros.so")'\
             | ../../pb/bin/pb/scheme -q
out of memory
Abort trap (core dumped) 
gmake[9]: *** [Mf-base:393: cmacros.so] Error 134
gmake[8]: *** [Mf-boot:25: ta6ob.boot] Error 2
gmake[7]: *** [Makefile:59: ta6ob.bootquick] Error 2
gmake[6]: *** [Makefile:58: ta6ob.bootquick] Error 2
# ...
```

**Please include any other relevant details**
This also fails when using a "staff" user which has higher limits and also as root.

I don't know if (#3459 _errorrtrace uses very large amounts of memory on Racket CS (and runs out of memory)_) is relevant as that relates to out of memory with CS.

**Comment by mflatt** [comment]
I expect that the "out of memory" error message is bad, and the real error is "cannot make a page both executable and writeable". On OpenBSD, you have to build on a filesystem that allows executables with write+executable permission on pages.

If you're interested in the details the write+execute problem, see #1296. BC hacks around the problem on x86_64, but we can't do things right without better support from the OS.

Meanwhile, I'll keep this issue open until we get the error message fixed, at least. (I meant to fix that before, but never got to it.)

**Comment by hopkinsr** [comment]
Spot on, thanks! For reference on OpenBSD the "wxallowed" mount option is required for CS.
