### ISSUE TITLE
com-invoke fails in Racket CS

### ISSUE THREAD

**Issue by Kalimehtar** [racket/racket#3820]
**What version of Racket are you using?**
8.1 [cs]

**What program did you run?**
```
(require ffi/com)
(define com (com-create-instance "WScript.Shell"))
(com-invoke com "SendKeys" "ok")
```

**What should have happened?**
"ok" typed in active window (DrRacket)

**If you got an error message, please include it here.**
; com-invoke: unknown method name: "SendKeys"

**Please include any other relevant details**
The method is listed in com-methods, but com-method-type doesn't return it's type:
```
> (map (lambda (x) (list x (com-method-type com x))) (com-methods com))
'(("AppActivate" #f)
  ("CreateShortcut" #f)
  ("Exec" #f)
  ("ExpandEnvironmentStrings" #f)
  ("LogEvent" #f)
  ("Popup" #f)
  ("RegDelete" (-> (string) void))
  ("RegRead" #f)
  ("RegWrite" (-> ((opt string) (opt (box any)) (opt (box any))) void))
  ("Run" #f)
  ("SendKeys" #f))
```

The same bug in 8.0 cs
com-invoke works in 8.1 bc. But com-method-type also returns #f.

I'm using Windows 10.

**Comment by mflatt** [comment]
Thanks for the report! I've pushed a repair that will get picked up in the next snapshot build. Unfortunately, I don't have a workaround for v8.1 other than to apply the patch or use BC (as you've noted).
