### ISSUE TITLE
float complex divided by `i` produces division by 0 error 

### ISSUE THREAD

**Issue by samth** [racket/racket#3821]
```
 [samth@homer:~/.../tests/unit-tests/03-number (master) plt] r
Welcome to Racket v8.1.0.5 [cs].
> (/ 2.0+3.0i +i)
; /: division by zero [,bt for context]
> (/ 2+3i +i)
3-2i
```

Found thanks to @gambiteer's tests.

**Comment by samth** [comment]
Weirdly this works in Chez. 

```
[samth@homer:~/.../tests/unit-tests/03-number (master) plt] /usr/bin/scheme
Chez Scheme Version 9.5
Copyright 1984-2017 Cisco Systems, Inc.

> (/ 2+3i +i)
3-2i
> (/ 2.0+3.0i +i)
3.0-2.0i
> 
```

**Comment by samth** [comment]
Bug introduced here: https://github.com/racket/racket/commit/35a0dfcafecaa3c9f3a8dc852be02865bc265332

**Comment by gambiteer** [comment]
Complex divide is difficult.  The Gambit code is ugly and I'm not terribly confident of it.

**Comment by samth** [comment]
We have the "advantage" of having two implementations and this program works correctly in Racket BC (and also in upstream Chez).

**Comment by gus-massa** [comment]
I proposed a new implementation https://github.com/racket/racket/issues/3359 . (It's still need some work.)
