### ISSUE TITLE
Windows 10 installation hangs

### ISSUE THREAD

**Issue by sshark** [racket/racket#3830]
**What version of Racket are you using?**
racket-8.1-x86_64-win32

**What program did you run?**
racket-8.1-x86_64-win32-cs.exe 

**What should have happened?**
It should install into Windows when I double-clicked it in Windows Explorer

**If you got an error message, please include it here.**
no error message. it just hung and made Windows Explorer unresponsive

**Please include any other relevant details**
Microsoft Windows [Version 10.0.21376.1]

**Comment by itmuckel** [comment]
When I execute it, I get a Windows warning that the program might not be trustworthy.

Lacking any other information: Do you have an anti virus program running? Windows Defender? Do you have an administrator account?
