### ISSUE TITLE
Stripping a Linux binary built with `raco exe --orig-exe` gives a contract violation

### ISSUE THREAD

**Issue by sschwarzer** [racket/racket#3831]
**What version of Racket are you using?**
8.1 [cs]

**What program did you run?**
I compiled a Racket program on Fedora Linux 33 with
```
raco exe --orig-exe myprogram.rkt
```
(Actually the program source is in a different directory and is named differently.)

If I run the program with `./myprogram --help`, I get the help output as expected.

If I run `strip myprogram` and then `./myprogram --help`, I get
```
open-input-bytes: contract violation
  expected: bytes?
  given: #<eof>
```

**What should have happened?**
The output of the program should be the same as before stripping.

**If you got an error message, please include it here.**
See above

**Please include any other relevant details**
- I'm running Fedora Linux 33.
- I installed Racket from the shell installer `racket-8.1-x86_64-linux-cs.sh`.

**Comment by mflatt** [comment]
The issue here is that `--orig-exe` is disabling proper ELF manipulation of the executable by `raco exe` and uses absolute-file-offset mode. Running `strip` can change offsets or discard the orphaned (not in an ELF section) bytes. So, `--orig-exe` mode should be improved.
