### ISSUE TITLE
`parameter/c` contracts are not `parameter-procedure=?`

### ISSUE THREAD

**Issue by samth** [racket/racket#3840]
This program prints #f on both CS and BC. Reported by @ralsei.
```
#lang racket
(let ([v (make-parameter 3)])
  (parameter-procedure=?
   (contract (parameter/c exact-integer? any/c) v 'a 'b)
   (contract (parameter/c exact-integer? any/c) v 'a 'b)))
```

This is because `parameter/c` uses `make-derived-parameter`, and thus the result isn't a chaperone of the original parameter. However, there's no `chaperone-parameter`, and there's no way to avoid specifying a guard in `make-derived-parameter`.

**Comment by samth** [comment]
This doesn't violate the specification of `parameter-procedure=?` but it does make it basically useless.

**Comment by rfindler** [comment]
Is it the case that `parameter/c` should just use `chaperone-procedure` instead? This much is okay, at least:

```
> (parameter? (chaperone-procedure
               (make-parameter 1)
               (λ args
                 (printf "!! ~s\n" args)
                 args)))
#t
> (let ([p (make-parameter 1)])
    (chaperone-of?
     (chaperone-procedure
      p
      (λ args
        (printf "!! ~s\n" args)
        args))
     p))
#t
```

**Comment by samth** [comment]
It seems like that would work, but I haven't tested it much.

**Comment by jackfirth** [comment]
Wow it's weird that `chaperone-procedure` can return a `parameter?`

**Comment by rfindler** [comment]
One more:
```
> (let ([p (make-parameter 1)])
    (parameter-procedure=?
     (chaperone-procedure
      p
      (λ args
        (printf "!! ~s\n" args)
        args))
     p))
#t
```

**Comment by rfindler** [comment]
@samth I've pushed a changed version of `parameter/c` [here](https://github.com/rfindler/racket/); do you want to try it out before I push it?

**Comment by rfindler** [comment]
@jackfirth does this make it seem less wierd?

```
> (procedure? (make-parameter 1))
#t
```

**Comment by jackfirth** [comment]
@rfindler Nope, I totally get how that works. What's surprising to me is that `chaperone-procedure` is aware of `prop:procedure` and able to wrap procedure-like structs in ways that preserve their struct-ness.

**Comment by samth** [comment]
Well those tests make me confident, except that they seem to fail: https://github.com/rfindler/racket/runs/2647636160?check_suite_focus=true#step:11:71

**Comment by rfindler** [comment]
Ah, right! That was a dumb bug and I've fixed it and force pushed the commit to rfindler/master. I tried to re-run the CI jobs but I'm not sure I'm doing this right.

**Comment by samth** [comment]
They should automatically run, but this is a case where opening a pull request makes it easy to see what's going on.

**Comment by rfindler** [comment]
I've created a pull request and poking around the CI stuff is illuminating, but I was asking you because I thought you might have some TR things to check before I pushed the commit.
