### ISSUE TITLE
call-in-os-thread etc may prevent GC of calling Racket thread

### ISSUE THREAD

**Issue by rmculpepper** [racket/racket#3843]
In the following program, the finalizer is not run if its object is created in the new thread. If the object is created in the main thread, the finalizer is run.

    #lang racket/base
    (require ffi/unsafe
             ffi/unsafe/os-thread
             ffi/unsafe/os-async-channel)

    ;; Use PLTSTDERR="debug@bug" to check for "shutdown" message.
    (define-logger bug)

    (define (make-thing)
      (define req-chan (make-os-async-channel))
      (call-in-os-thread (lambda () (os-async-channel-get req-chan)))
      (define obj (list req-chan))
      obj)

    (define (register obj)
      (register-finalizer obj (lambda (obj)
                                (log-bug-debug "shutdown")
                                #;(os-async-channel-put (car obj) #f))))

    (let ()
      ;; If c is created in main thread, then can be GC'd.
      #;(define c (make-thing))
      (thread
       (lambda ()
         ;; If c is created in new thread, then not GCable!
         (define c (make-thing))
         (register c)
         (sync never-evt)
         c))
      (void))

    (for ([i 100])
      (sleep 0.01)
      (collect-garbage))

The object (`c`) should be unreachable because the new thread is unreachable and blocked on `never-evt`, so it should be GC'd, which means its reference to `c` should disappear.

My conjecture is that `call-in-os-thread` somehow creates an OS thread with a strong reference to the Racket thread that created it.

(This is simplified from an issue involving db connection pools and sqlite connections using os-threads.)

**Comment by mflatt** [comment]
Yes, that's what happens. Repair on the way.
