### ISSUE TITLE
chaperone error with plot-lib

### ISSUE THREAD

**Issue by Bogdanp** [racket/racket#3852]
**What version of Racket are you using?**
a7a1f526a1d622580c2abb760dc88cf72e1ced08

**What program did you run?**

```racket
#lang racket/base

(require plot racket/math)

(parameterize ([plot-new-window? #t])
  (plot
   (function sqr 1 10)))
```

When I hover over the plot on macOS, I get the following error:

```
; procedure chaperone: non-chaperone result; received an argument that is not a chaperone of the original argument
;   original: (object:ps-setup% ...)
;   received: (object:ps-setup% ...)
; Context (plain; to see better errortrace context, re-run with C-u prefix):
;   /Users/bogdan/sandbox/racket/racket/share/pkgs/plot-gui-lib/plot/private/gui/snip.rkt:174:4 draw method in plot-snip%
;   /Users/bogdan/sandbox/racket/racket/share/pkgs/plot-gui-lib/plot/private/gui/snip2d.rkt:361:4 draw method in 2d-plot-snip%
;   /Users/bogdan/sandbox/racket/racket/share/pkgs/gui-lib/mred/private/wxme/text.rkt:5468:22 process-snips
;   /Users/bogdan/sandbox/racket/racket/share/pkgs/gui-lib/mred/private/wxme/text.rkt:5438:16 lloop
;   /Users/bogdan/sandbox/racket/racket/share/pkgs/gui-lib/mred/private/wxme/text.rkt:5225:2 refresh method in text%
;   /Users/bogdan/sandbox/racket/racket/share/pkgs/gui-lib/mred/private/wxme/editor-canvas.rkt:648:2 redraw method in editor-canvas%
;   /Users/bogdan/sandbox/racket/racket/share/pkgs/gui-lib/mred/private/wxme/editor-canvas.rkt:1294:4 all-in-chain method in canvas-editor-admin%
;   /Users/bogdan/sandbox/racket/racket/share/pkgs/plot-gui-lib/plot/private/gui/snip2d.rkt:271:4 on-event method in 2d-plot-snip%
;   /Users/bogdan/sandbox/racket/racket/share/pkgs/gui-lib/mred/private/wxme/text.rkt:475:2 on-event method in text%
;   /Users/bogdan/sandbox/racket/racket/share/pkgs/gui-lib/mred/private/wxme/editor-canvas.rkt:412:2 on-event method in editor-canvas%
;   /Users/bogdan/sandbox/racket/racket/collects/racket/private/more-scheme.rkt:148:2 call-with-break-parameterization
;   /Users/bogdan/sandbox/racket/racket/collects/ffi/unsafe/atomic.rkt:73:13
;   /Users/bogdan/sandbox/racket/racket/share/pkgs/gui-lib/mred/private/wx/cocoa/window.rkt:900:4 dispatch-on-event method in window%
;   /Users/bogdan/sandbox/racket/racket/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:435:6
;   /Users/bogdan/sandbox/racket/racket/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:460:2 yield
```

If I switch to the previous commit (b6b1ffec03b6bbc7eff76a2a99f6cc1a1c6dcc00), everything works fine so it seems like  a7a1f526a1d622580c2abb760dc88cf72e1ced08 introduced a regression (or uncovered a bug in `plot-lib` -- I don't know enough to tell the difference).

**Comment by samth** [comment]
I think what's happening here is that object contracts are not chaperones,
and prior to @rfindler's change, parameter contracts didn't use chaperones
so they didn't perform a chaperone check. I think the right fix is for
parameter/c to always use impersonate-procedure, which will remove the
check.

**Comment by rfindler** [comment]
Maybe an option for parameter/c to bump it up to impersonator contract even
if its argument is a chaperone contract? Then TR can generate that option?

Robby

**Comment by samth** [comment]
That seems like a good idea, but for backwards compatibility I think that
option should be the default.

**Comment by rfindler** [comment]
I made the change but still see the error so maybe something else is going on.

If, indeed, this is not the problem, I would prefer to change the default to be in step with the rest of the contract library. Of course, I realize backwards compatibility is important, so I've not done this for now.

**Comment by samth** [comment]
I think there's an error in your change; this commit fixes things for me: https://github.com/samth/racket/commit/523662c665834aa77971c534e078dc597ead34c5

**Comment by samth** [comment]
Here's a test case that we could add that checks that the bug is fixed:

```
#lang racket

(define c (parameter/c (or/c #f (object/c (m (->m number? number?))))))

(define c% (class object% (super-new) (define/public (m x) (+ x 5))))

(define/contract p c (make-parameter #f))

(p (new c%))
(send (p) m 7) ; => 12
```

**Comment by rfindler** [comment]
Oops. Duh. Thanks, @samth .
