### ISSUE TITLE
Possible Bug in Regexp Parser

### ISSUE THREAD

**Issue by peblair** [racket/racket#3854]
**What version of Racket are you using?**
8.1 [cs]

**What program did you run?**
```racket
> #px"abc)"
#px"abc)"
> (regexp-match #px"abc)" "abc)")
'("abc")
```

**What should have happened?**
Either a parse error or a match of `'("abc)")`. My guess is that the former is the intended behavior.

**If you got an error message, please include it here.**
N/A

**Please include any other relevant details**
This was produced in the DrRacket REPL on MacOS Big Sur.

**Comment by mflatt** [comment]
Yes, that should be a parse error. Thanks for the report!
