### ISSUE TITLE
Use of invariant assertion within make-parameter causes invalid memory reference.

### ISSUE THREAD

**Issue by natebragg** [racket/racket#3865]
**What version of Racket are you using?**
8.1 [cs]

**What program did you run?**

    $ racket
    Welcome to Racket v8.1 [cs].
    > (define test-bad
        (make-parameter 4
        (invariant-assertion
            (-> natural? natural?)
            identity)))
    > (test-bad)
    4
    > (test-bad 5)
    ; invalid memory reference.  Some debugging context lost [,bt for context]
    > ,bt
    ; invalid memory reference.  Some debugging context lost
    ;   context...:
    ;    body of top-level
    ;    /home/nate/.local/share/racket/pkgs/xrepl-lib/xrepl/xrepl.rkt:1493:0
    ;    /home/nate/.local/share/racket/collects/racket/repl.rkt:1
    > (test-bad)
    4
    > (define test-good
        (make-parameter 4
            identity))
    > (test-good)
    4
    > (test-good 5)
    > (test-good)
    5
    > ((invariant-assertion
            (-> natural? natural?)
            identity) 5)
    5

**What should have happened?**
Running `(test-bad 5)` should have set `test-bad` to 5, and not reported an error.

**If you got an error message, please include it here.**

Error message is inline above.

**Please include any other relevant details**
I am running on ARM 64.

**Comment by mflatt** [comment]
Thanks for the report!
