### ISSUE TITLE
Possible bug in regexp parser (group self-reference)

### ISSUE THREAD

**Issue by peblair** [racket/racket#3866]
**What version of Racket are you using?**
8.1 [cs]

**What program did you run?**
```racket
> (pregexp "((.)\\1+)")
#px"((.)\\1+)"
> (regexp-match (pregexp "((.)\\1+)") "aa")
#f
```

**What should have happened?**
I'm not entirely sure 🙂. Python [treats this as a syntax error](https://hg.python.org/cpython/file/178075fbff3a/Lib/test/re_tests.py#l621), but Racket does not. That doesn't mean that Racket's interpretation is incorrect, but I was a little surprised, given that this pattern is impossible to match. Is this behavior intentional?

**If you got an error message, please include it here.**
N/A

**Please include any other relevant details**
Sample run in DrRacket.

**Comment by mflatt** [comment]
If for no reason other than backward compatibility, I think we'll need to declare it as allowed (and improve the documentation).

I'll note that referring to an open group does not necessarily imply that a pattern is unmatchable. For example, `#px"(^a|\\1){2}"` matches `"aa"`. So, it seems at least remotely possible that allowing a reference to an open group is useful.

It also seems possible that a "type system" (similar to the one used to constrain lookahead or lookback) could rule out some/all unmatchable patterns, but that doesn't sound worthwhile.

**Comment by peblair** [comment]
Understood. That makes sense, and thank you for providing an example of a matchable pattern!
