### ISSUE TITLE
`locale-string-encoding` not following `current-locale` on Windows

### ISSUE THREAD

**Issue by tomyun** [racket/racket#3872]
**What version of Racket are you using?**
8.1 [cs]

**What program did you run?**
```racket
(current-locale "ko_KR.CP949")
(locale-string-encoding)
```

**What should have happened?**
Expected "CP949", but received "CP1252" which was the locale set in the system.

**If you got an error message, please include it here.**
N/A

**Please include any other relevant details**
Confirmed this issue on Windows 10.
It seems like `(locale-string-encoding)` always returns system locale regardless of `current-locale` on Windows.
The same code ran without issue on macOS 11.4, correctly returning a locale (i.e. "CP949") set by `current-locale`.

**Comment by mflatt** [comment]
I've pushed a repair for `locale-string-encoding` for Windows (for the next snapshot build and the upcoming v8.2 release). Beware, though, that the Windows convention is apparently the locale string `Korean_Korea.949` instead of `ko_KR.CP949`.
