### ISSUE TITLE
`shift_jisx0213` encoding not available on Windows

### ISSUE THREAD

**Issue by tomyun** [racket/racket#3877]
**What version of Racket are you using?**
8.1 [cs]

**What program did you run?**
```racket
> (bytes-open-converter "utf-8" "shift_jisx0213")
#f
```

**What should have happened?**
```racket
> (bytes-open-converter "utf-8" "shift_jisx0213")
#<bytes-converter>
```

Should have gotten a `#<bytes-converter>` as in other platforms like macOS.
`shift_jisx0213` is an encoding supported by iconv.

**If you got an error message, please include it here.**
N/A

**Please include any other relevant details**
Windows 10. This issue was found with #3876.

**Comment by mflatt** [comment]
It looks like iconv must be configured with `--enable-extra-encodings` to get `shift_jisx0213`. Our current iconv build for Windows doesn't include that flag. I think it makes sense to enable extra encodings, and I'll be able to try that later this week.

**Comment by mflatt** [comment]
The libiconv DLL in the "racket-win32-x86_64-3" package now includes extra encodings, and it should be part of snapshots 20210617 and later.
