### ISSUE TITLE
has-focus? always returns #f

### ISSUE THREAD

**Issue by jjsimpso** [racket/racket#3883]
**What version of Racket are you using?**
8.1[cs] on Linux

**What program did you run?**
#lang racket/gui
(define address-field%
  (class text-field%
    (super-new)
    (inherit get-editor
             has-focus?
             focus)
    (define/override (on-focus on?)
      (eprintf "on-focus was ~a -> now ~a~n" (has-focus?) on?)      
      (queue-callback
       (lambda ()
         (eprintf "later: has focus? ~a~%" (has-focus?)))))))
(define f (new frame% [label "hello"] [width 100] [height 100]))
(define a (new address-field% [parent f] [label "test "]))
(send f show #t)

**What should have happened?**
has-focus? appears to return #f even if the text-field has focus.

**If you got an error message, please include it here.**

**Please include any other relevant details**
Brought this up in the Slack channel. Hopefully I'm interpreting the documentation for has-focus? correctly.

**Comment by mflatt** [comment]
Thanks for the report!
