### ISSUE TITLE
`raco exe` mangles executable names under Windows

### ISSUE THREAD

**Issue by sschwarzer** [racket/racket#3891]
**What version of Racket are you using?**
8.1 cs

**What program did you run?**
```
raco cross --target x86_64-win32 exe --embed-dlls -o "sudoku-solver-0.14.0-x86_64-windows" games/sudoku-solver.rkt
```
I know, this isn't a straightforward `raco exe` on Windows, but since I'm on Linux and @mflatt assumes that the path change is unrelated to `raco-cross`, I enter the bug here. :-)

**What should have happened?**
I expected `raco exe` to generate an executable `sudoku-solver-0.14.0-x86_64-windows` or `sudoku-solver-0.14.0-x86._64-windows.exe`.

**If you got an error message, please include it here.**
I don't get an error message, but the actually generated name is `sudoku-solver-0.14.exe`. It seems everything starting with the last dot is removed and replaced with `.exe`.

**Please include any other relevant details**
- I'm using Fedora Linux 33 to run `raco cross`, with the intention to generate a binary for Windows.
- The name from the command line is used as-is under a native `raco exe` on my Linux system, so this seems to be a Windows-specific issue.
- A workaround would be to append `.exe` in the `-o` option value. This is a bit inconvenient for me because otherwise I could use the same file name in the `-o` option for all platforms. That said, specifying the name including `.exe` shouldn't be a big problem.
- Still, the current behavior seems weird to me and I'd like your opinions.

**Comment by mflatt** [comment]
I think the current behavior is weird enough that we should fix it. A repair would be backward-incompatible, but the old behavior is so weird that it seems unlikely that anyone wanted it or relies on it — especially given that a suffix is changed only for some platforms and GUI modes.
