### ISSUE TITLE
DrRacket: "Scribble HTML" launcher does not work on some .scrbl files

### ISSUE THREAD

**Issue by haruo-wakakusa** [racket/racket#3900]
**What version of Racket are you using?**
v8.0 [cs]

**What program did you run?**
In DrRacket, I copied the scribble math example code:
```
#lang scribble/manual

@require[scribble-math]

@title[#:style (with-html5 manual-doc-style)]{Example}

The derivative of @${x^2} is @${2x}. Complex formulas
look best when typeset in display mode:

@$${\sum_{i=0}^n x_i^3}
```
[Github - jsmaniac / scribble-math](https://github.com/jsmaniac/scribble-math)

And I saved as "TheFoundationOfMathematics.scrbl", I cannot browse the correct HTML page in DrRacket.

Next, I saved as "example.scrbl", I can browse the correct HTML page in DrRacket.

Last, I tried to save as some filenames and got the following results:
```
TheFoundationOfMathematics.scrbl -> NG
example.scrbl -> OK
tmp1.scrbl -> OK
TemporaryFile1.scrbl -> NG
temporary-file1.scrbl -> NG
temporary_file1.scrbl -> NG
```

**What should have happened?**
In the above files, the correct HTML page should have shown.

**If you got an error message, please include it here.**
Not particularly.

**Please include any other relevant details**
MacBook Pro 2020(Intel Core i5, BigSur).

**Comment by soegaard** [comment]
This sounds odd.

Can you add the resulting html files to the gist below, so we can compare them?
One file that works, and one that doesn't.

https://gist.github.com/

**Comment by soegaard** [comment]
I have tried your snippet in DrRacket 8.0 [cs] in Big Sur 
using the "Scribble HTML" button --  and it seems to work for me.

Do you get any messages in the repl inside DrRacket? 

I see:
```
Welcome to DrRacket, version 8.0 [cs].
Language: scribble/manual [custom]; memory limit: 512 MB.
scribble: loading xref
scribble: rendering
```
And then the browser is launched with the generated html-file.

When you write "I cannot browse the correct HTML" does that mean
you have an html file that doesn't work, or that you don't get an html file at all?

**Comment by haruo-wakakusa** [comment]
Umm, I can browse "TheFoundationOfMathematics.html" correctly. I doubt some setup or cache problems. So, I start it all over again, but I cannot reproduce the problem. Thanks, Soegaard. I close this issue.
