### ISSUE TITLE
make-module-evaluator does not accept #:readers keyword

### ISSUE THREAD

**Issue by pmatos** [racket/racket#3905]
Fails:
https://github.com/racket/racket/runs/2967251364?check_suite_focus=true#step:10:79

Possibly caused by: https://github.com/racket/racket/commit/6ca4ffeca1e5877d44f835760ad89f18488d97e1

**Comment by mflatt** [comment]
I think this was a result of package-update lag. Now that the package server reports the latest "sandbox-lib" checksum, the test should pass.

Maybe the "sandbox-lib" package should be moved back to the main Racket repo, since its documentation and tests live there.

**Comment by samth** [comment]
I re-ran those tests and they have passed (or will soon). I agree about moving the code.

**Comment by shhyou** [comment]
> I think this was a result of package-update lag. Now that the package server reports the latest "sandbox-lib" checksum, the test should pass.
> 
> Maybe the "sandbox-lib" package should be moved back to the main Racket repo, since its documentation and tests live there.

The situation of the `db` package is the same. I thought about adding CI workflows to `db` but was got stuck on this.

**Comment by samth** [comment]
The `db` situation is somewhat different -- most of the code and tests is in `racket/db` but some of it is in `racket/racket`.

**Comment by shhyou** [comment]
What I see is that part of the core db code is in `db/private` in `racket/racket`, and the other part of `db` is in `db-lib`. The tests is in `db-test`.

The `db` library and the tests depend on the latest `db/private` code in `racket/racket`, and right now `racket/racket` is in charge of running the db tests (not counting DrDr) -- without knowledge of any update of the `db` library. Am I missing anything?

**Comment by samth** [comment]
That's all accurate, except that the racket tests get the latest db library from the pkg server, so will see the right code modulo package server delays. Having CI for the `racket/db` repository would be nonetheless good, though.
