### ISSUE TITLE
racket-8.1: `make cs` fails on Fedora 34 with gcc-11: '__builtin_memcpy' reading 784 bytes from a region of size 0

### ISSUE THREAD

**Issue by juhp** [racket/racket#3910]
**What version of Racket are you using?**
8.1

**What program did you run?**
`make cs`

**What should have happened?**
The build of racket to complete

**If you got an error message, please include it here.**
```
:
gcc  -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wall -DELF_FIND_BOOT_SECTION -pthread -Wpointer-arith -Wall -Wextra -Werror -Wno-implicit-fallthrough -o ../bin/pb/scheme ../boot/pb/main.o ../boot/pb/libkernel.a ../zlib/libz.a ../lz4/lib/liblz4.a -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -pthread -ldl -lm -lrt
In function 'memcpy',
    inlined from 'S_create_thread_object' at thread.c:83:5,
    inlined from 'Sbuild_heap' at scheme.c:1148:15,
    inlined from 'main' at main.c:298:3:
/usr/include/bits/string_fortified.h:29:10: error: '__builtin_memcpy' reading 784 bytes from a region of size 0 [-Werror=stringop-overread]
   29 |   return __builtin___memcpy_chk (__dest, __src, __len,
      |          ^
lto1: all warnings being treated as errors
make[9]: *** [/tmp/ccw7WU4c.mk:2: /tmp/cc0xvdMj.ltrans0.ltrans.o] Error 1
make[9]: *** Waiting for unfinished jobs....
lto-wrapper: fatal error: make returned 2 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[8]: *** [Mf-a6le:38: ../bin/pb/scheme] Error 1
make[7]: *** [Makefile:57: ta6le.bootquick] Error 2
make[6]: *** [Makefile:58: ta6le.bootquick] Error 2
make[6]: Leaving directory '/builddir/build/BUILD/racket-8.1/src/cs/c/ChezScheme'
make[5]: *** [Makefile:155: pb-bootquick] Error 2
make[5]: Leaving directory '/builddir/build/BUILD/racket-8.1/src/cs/c'
make[4]: *** [Makefile:149: scheme-via-pb] Error 2
make[4]: Leaving directory '/builddir/build/BUILD/racket-8.1/src/cs/c'
make[3]: *** [Makefile:131: scheme] Error 2
make[3]: Leaving directory '/builddir/build/BUILD/racket-8.1/src/cs/c'
make[2]: *** [Makefile:85: cs] Error 2
make[2]: Leaving directory '/builddir/build/BUILD/racket-8.1/src/cs/c'
make[1]: *** [Makefile:81: racketcs] Error 2
make[1]: Leaving directory '/builddir/build/BUILD/racket-8.1/src'
make: *** [Makefile:85: cs] Error 2
```

**Please include any other relevant details**
Fails on Fedora Linux 34 x86_64
Succeeds with Fedora Linux 33 x86_64 (gcc-10.3)

Related Fedora racket bug: https://bugzilla.redhat.com/show_bug.cgi?id=1863004 with more details.

**Comment by mflatt** [comment]
It looks like the problem here is `-Werror` combined with imprecise compiler analysis. The analysis can't determine that `S_threads` will be `Snil` in the startup case where `Svoid` is passed as `p_tc`.

The Racket configure script allows `-Werror` for compiling Chez Scheme when the compiler name is `gcc`. So, one way around the problem is to configure with `CC=cc` (which is a hack).

I've always been reluctant to make `-Werror` the default due to this kind of problem, but it was part of the Chez Scheme configuration that we started with, and and leaving it seemed worth a try... Probably the right change is to remove `-Werror` from the default flags but add it specifically to the CI builds.

**Comment by juhp** [comment]
Thank you, this can probably be closed then when you wish :+1:

**Comment by jbclements** [comment]
@juhp We're looking at including this repair and the other one you prompted in our upcoming 8.2 release. Do you have time to try compiling the current git HEAD on Fedora 34?

**Comment by juhp** [comment]
I successfully ran `make` on 2e1756adf7 on Fedora Rawhide x86_64.

My current interest in Racket is actually due to idris2. :-)

**Comment by mflatt** [comment]
@juhp Thanks for checking!

**Comment by juhp** [comment]
BTW I built 8.2 for Fedora and EPEL8 in https://copr.fedorainfracloud.org/coprs/petersen/racket/
