### ISSUE TITLE
FFI problem with libserialport: scheme_make_fd_output_port

### ISSUE THREAD

**Issue by rferrante** [racket/racket#3916]
**What version of Racket are you using?**
Racket 8.1, Mac OS 11.4

**What program did you run?**
Please include a short example that triggers the bug
(define (list-ports)
  (display "listing of ports...\n")
  (for ([pname (serial-ports)])
       (displayln pname)))

**What should have happened?**
serial ports should be fetched. The "serial-ports" function is in the libserialport racket library

**If you got an error message, please include it here.**
ffi-obj: could not find export from foreign library
  name: scheme_make_fd_output_port
  library: [all opened]
  system error: dlsym(0x7febccd044c0, scheme_make_fd_output_port): symbol not found
  context...:
   /Applications/Racket v8.1/collects/ffi/unsafe.rkt:255:20
   /Applications/Racket v8.1/collects/ffi/unsafe.rkt:249:2: get-ffi-obj*
   body of "/Users/rferrante/Library/Racket/8.1/pkgs/libserialport/libserialport/private/ffi.rkt"

**Please include any other relevant details**
Mac OS 11.4
libserialport requires an external library libserialport.0.dylib, which was copied over from the 7.9 ~/Library/Racket 7.9 tree, and aslo freshly downloaded from libserialport's project page. No difference.
The program has run correctly on all of the 7.X revs, and reverting to 7.9 fixes the issue. Going back to 8.1 causes it again.

**Comment by sorawee** [comment]
I don't think this is Racket's bug. The default variant of Racket 8.x is CS, which intentionally doesn't support `scheme_make_fd_output_port`. If you download Racket 8.1 BC , there should be no problem. The library `libserialport` could also be updated so that it works correctly on Racket CS, but that's an issue you should report at https://github.com/mordae/racket-libserialport.

**Comment by rferrante** [comment]
Thank You,

I will do that.

**Comment by sorawee** [comment]
To be fixed by https://github.com/mordae/racket-libserialport/pull/5. Closing.
