### ISSUE TITLE
backporting aa2e814a02 or equivalent to 7.9 [bc]

### ISSUE THREAD

**Issue by bremner** [racket/racket#3923]
**What version of Racket are you using?**  7.9 [bc]

**Problem description** It is late in the release cycle for Debian 11 / Bullseye and I don't think I can convince the release team to upgrade from 7.9 to 8.2.  I would like to mitigate at least some of https://github.com/racket/racket/security/advisories/GHSA-cgrw-p7p7-937c, so I'm interested in backporting aa2e814a02 (or something similar).  

**Questions**

1) Since we're currently shipping racket [bc], I guess we can ignore changes to `racket/src/cs/schemified/expander.scm`, correct?
2) Do the changes to `racket/src/bc/src/startup.inc` correspond to the changes to `racket/src/expander/namespace/module.rkt` ?
3) Assuming the answer to 2 is yes, would a reasonable strategy be to apply the changes to `module.rkt` and regenerate `startup.inc`?

**Comment by mflatt** [comment]
Yes on all: It should work to change `module.rkt` and run `make` in `racket/src/expander`, which will generate `startup.inc`.

**Comment by bremner** [comment]
Matthew Flatt ***@***.***> writes:

> Yes on all: It should work to change `module.rkt` and run `make` in `racket/src/expander`, which will generate `startup.inc`.
>
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/racket/racket/issues/3923#issuecomment-885186067

Thanks for the feedback. I think I managed it [1], but I would really
appreciate a simple test to make sure the rebuilt version of racket is
using the modified expander.  

[1]: https://salsa.debian.org/bremner/racket/-/commits/debian/bullseye/

**Comment by mflatt** [comment]
Here's the test from that commit as a stand-alone file (reports no output for passing, reports "failed" for failing): https://gist.github.com/mflatt/f4231d8b9f2418f189d839e587235f04

**Comment by bremner** [comment]
Perfect, the test works as expected on my patched version. I think the issue can be closed now, thanks again for your help.
