### ISSUE TITLE
dynamic-rerequire does not always reload a module if the module's dependencies are modified

### ISSUE THREAD

**Issue by djholtby** [racket/racket#3925]
**What version of Racket are you using?**
8.2 [cs], 8.1 [cs], 7.9 [bc]

**What program did you run?**
`dir/one.rkt`
```
#lang racket/base
(require "two.rkt")
(provide alpha)
(define alpha beta)
```

`main.rkt`
```
#lang racket/base

(require racket/rerequire)
(module+ test (require rackunit))

(define (get-alpha)
  (dynamic-rerequire "dir/one.rkt")
  (dynamic-require "dir/one.rkt" 'alpha))

(define (set-beta! v)
   (with-output-to-file "dir/two.rkt" #:exists 'replace
     (lambda ()
      (printf "#lang racket/base\n(provide beta)\n(define beta ~v)\n" v))))

(module+ test
  (set-beta! 2)
  (check-eqv? (get-alpha) 2)
  (set-beta! 3)
  (check-eqv? (get-alpha) 3))
```

Results: second check fails (alpha is still 2)

**What should have happened?**

The second call to `dynamic-rerequire` by way of `get-one` should have triggered a reload of "two.rkt" and "one.rkt", resulting in `alpha` being equal to 3.

**Other Details**

This happens in Dr.Racket but not when invoking `racket main.rkt` 

Looking into it, there was a "beta.zo" being created when running in Dr.Racket (8.2 [cs]) and the issue ends up being due to compiled files and their interaction with the loader.  

It also happens if the dependency is in a submodule (looks to be reported as #971) in which case it happens from command line also.

**Comment by sorawee** [comment]
This is fixed, IIUC. Closing.
