### ISSUE TITLE
megaparsack documentation confusing regarding backtracking

### ISSUE THREAD

**Issue by bobduff** [racket/racket#3928]
**What version of Racket are you using?**
Racket v8.2 [cs]

**What program did you run?**
None (it's a documentation bug).

**What should have happened?**

(I'm new to racket and to megaparsack. Both look very interesting.
Please let me know if I'm sending this bug report in a wrong way.)

I think there are bugs in the megaparsack documentation,
regarding backtracking.

"2.1.2 Backtracking with caution" says:

    > (parse-result! (parse-string try-labeled/p "the integer: false"))
    string:1:13: parse error
      unexpected: f
      expected: integer

And then says that message is "useless".  In fact, that error message
is crystal clear.  It then shows how to factor out "the ", and shows
a supposedly better error.  But the better message is identical to
the one above.

This leaves me confused about what backtracking in Megaparsack
actually does.

"5.1 Primitives" says:

    (or/p parser ...+) → parser?

      parser : parser?

    Tries each parser in succession until one either succeeds or consumes
    input, at which point its result will be returned as the result of the
    overall parse. Parsers that consume input but fail will halt further
    parsers from being tried and will simply return an error; if
    backtracking is desired, the parser should be wrapped with try/p.

    Changed in version 1.5 of package megaparsack-lib: Changed to always
    return the first successful result, rather than continuing to try
    parsers until one consumes input. The new behavior is more predictable
    and more consistent with existing Parsec implementations, though the old
    behavior was more consistent with the presentation in the original
    paper.

First, it seems strange to document the old behavior first, and then say
it changed.  Why not document the behavior of the latest version, and
then say, "This changed in version 1.5 of package megaparsack-lib;
before version 1.5, it did so-and-so..."?  (I see that "many+/p" is
documented that way.)

Second, the description of the new behavior is incomplete -- it doesn't
say what happens if all alternatives of "or/p" fail.  Does it return
the first successful, but if there is no such, the first unsuccessful
(i.e. the first)?  That would explain my confusion about section 2.1.2.

"5.1 Primitives" says:

    void/p : (parser/c any/c void?)

    A parser that always succeeds and always returns #<void>.

"...and does not consume input", right?

"5 API Reference" is missing "into":  "syntax objects" should be
"syntax objects into".

**If you got an error message, please include it here.**

**Please include any other relevant details**
I'm on linux, x86_64 (but that's irrelevant to a doc bug).

**Comment by sorawee** [comment]
Please report the issue at https://github.com/lexi-lambda/megaparsack. This repo is for the Racket programming language, not for a specific Racket package.

**Comment by bobduff** [comment]
> Please report the issue at https://github.com/lexi-lambda/megaparsack. This repo is for the Racket programming language, not for a specific Racket package.

OK, sorry about that, and thanks for the info.

But can you please tell me how I could have figured that out
on my own?  I don't see anything about it in the package docs.

Someday, I might want to report a bug in some other package,
and I'd like to know how to find the right place.

**Comment by samth** [comment]
If you look here: https://pkgs.racket-lang.org/package/megaparsack there a multiple links to the GitHub page for megaparsack, and you can find the bug reporting info there.

**Comment by sorawee** [comment]
The easiest way is to click at the title of the documentation. There should be a link to where the documentation resides.

For example, here's a screenshot of https://docs.racket-lang.org/megaparsack/index.html

<img width="1003" alt="Screen Shot 2021-07-22 at 8 55 43 AM" src="https://user-images.githubusercontent.com/9099577/126669990-6f9fe856-a230-46d9-99e3-02860395d439.png">

By clicking at the title, you will see a link to the document source (https://github.com/lexi-lambda/megaparsack/tree/master/megaparsack-doc/scribblings/megaparsack.scrbl).

<img width="993" alt="Screen Shot 2021-07-22 at 8 56 08 AM" src="https://user-images.githubusercontent.com/9099577/126670053-c7b80102-c73f-4a95-a9e5-ccd70c19c71a.png">

So you should report the bug at https://github.com/lexi-lambda/megaparsack.

You can also use https://pkgs.racket-lang.org/ to search for a package and see where its source is.

**Comment by bobduff** [comment]
Thank you both.  Very helpful!

And again, sorry for the noise here.

- Bob
