### ISSUE TITLE
raco make silently discards --disable-constant flag when using parallel build tasks

### ISSUE THREAD

**Issue by djholtby** [racket/racket#3929]
**What version of Racket are you using?**
8.2 [cs]

**What program did you run?**
`raco make -j 4 --disable-constant *.rkt`

**What should have happened?**

*.rkt files were compiled with constant enforcement disabled

**What does happen?**

`--disable-constant` is ignored when using `-j` with 2 or more tasks

Can be tested by attempting to `dynamic-rerequire` the compiled modules.  Without disabling constant enforcement, subsequent reloading of the module will result in an error.

**Please include any other relevant details**

It looks like the issues are

* raco make does not pass along the option for --disable-constant to `parallel-compile-files`
* `parallel-compile-files` doesn't pass its options to the workers 
* the workers don't recognize an option for disabling constants

**Comment by mflatt** [comment]
Closed by #3930
