### ISSUE TITLE
Downloads fail

### ISSUE THREAD

**Issue by tim-lebedkov** [racket/racket#3931]
**What version of Racket are you using?**
8.2

**What program did you run?**
Downloading Racket via Npackd fails.

**What should have happened?**
Download succeeds

**If you got an error message, please include it here.**
ERROR: Error installing: Downloading Racket 8.2: Error downloading https://download.racket-lang.org/installers/8.2/racket-8.2-i386-win32.exe: Error 12029: A connection with the server could not be established

**Please include any other relevant details**
Windows,
https://ci.appveyor.com/project/tim-lebedkov/npackd/builds/40095784/job/25yx9e3maaem3jfk#L919

**Comment by tim-lebedkov** [comment]
Are you maybe disallowing requests from unknown HTTP user agents?

**Comment by samth** [comment]
download.racket-lang.org is hosted on cloudflare, and redirects that URL to https://mirror.racket-lang.org/installers/8.2/racket-8.2-i386-win32.exe

Does the latter URL work for downloading from npackd? Are there known problems for npackd with cloudflare?

**Comment by tim-lebedkov** [comment]
I will try the new URL. No known problems with Cloudflare.

**Comment by tim-lebedkov** [comment]
Changing the URL to mirror.racket-lang does not help: https://ci.appveyor.com/project/tim-lebedkov/npackd/builds/40109585/job/e28xbi78hjohndhi#L134

**Comment by samth** [comment]
I think your virtual machine doesn't support TLS 1.2. See https://docs.microsoft.com/en-us/skypeforbusiness/troubleshoot/server-meetings/cannot-connect-you-to-this-meeting

**Comment by sorawee** [comment]
I assume that @samth's comment addressed the issue. If that's not the case, feel free to reopen the issue.
