### ISSUE TITLE
make-export: contract violation

### ISSUE THREAD

**Issue by pmatos** [racket/racket#3932]
Commit https://github.com/racket/racket/commit/6901f8d5511fd45516aa0a85ae070292e64226cc

is causing these:
https://github.com/racket/racket/runs/3117530632?check_suite_focus=true#step:8:25

```
ERROR: make-export: contract violation
  expected: phase+space?
  given: '(0 . soup)
```

**Comment by samth** [comment]
I think this was fixed by https://github.com/racket/racket/commit/2779c48173d8ce51de4f5d28d2cb4ff8ece8ac8d

**Comment by mflatt** [comment]
I don't think that's related. I also don't understand how that error happens, so I'm trying a Windows BC build.

**Comment by samth** [comment]
It also seems to happen on Linux BC: https://github.com/racket/racket/runs/3135807630?check_suite_focus=true

**Comment by mflatt** [comment]
Good to know about Linux BC. Looks like it's a BC JIT bug, probably related to `symbol-interned?`.

**Comment by mflatt** [comment]
This should be fixed by 32e8b65303799ba39c34ec0971efc984f7197d85, but let's wait for CI to check.

**Comment by shhyou** [comment]
Do you intend to point to 4118c8d3?

**Comment by mflatt** [comment]
Yes — and it looks like it worked.
