### ISSUE TITLE
[Feature Request] of a built-in function for easily finding the value of an element in a list by its order in it

### ISSUE THREAD

**Issue by marek-lach** [racket/racket#3966]
A built-in function for quickly finding, or getting an element in a list by its order in that list, and returning its value?

Somewhat similar to:

`(member 2 (list 1 2 3 4)) [1]`, but something that would in this case instead return  _2_ and NOT `true`, because the value of a second member in that list is 2 (maybe it could be called `membervalue`, or something...

**Comment by sorawee** [comment]
I'm kinda confused. Can you elaborate more?

> A built-in function for quickly finding, or getting an element in a list by its order in that list, and returning its value?

That sounds like `list-ref` to me. `(list-ref (list 42 -42 100) 2) => 100`.

> Somewhat similar to:
>
> `(member 2 (list 1 2 3 4)) [1]`, but something that would in this case instead return 2 and NOT true,

`(member 2 (list 1 2 3 4)) [1]` is not a valid Racket code. Do you mean just `(member 2 (list 1 2 3 4))`? FWIW, this expression evaluates to `'(2 3 4)`, which is not `true`.
