### ISSUE TITLE
When install a package gregor with command "raco pkg install gregor", encountered non-stoppable errors ((WORKER RECEIVE MESSAGE ERROR: internal error: tried to deschedule a descheduled thread). 

### ISSUE THREAD

**Issue by madeinquant** [racket/racket#3970]
**What version of Racket are you using?** 
version : 8.2

**What program did you run?** 
When install a package gregor with command "raco pkg install gregor", encountered non-stoppable errors ((WORKER RECEIVE MESSAGE ERROR: internal error: tried to deschedule a descheduled thread). 

**What should have happened?**
I don't expect non-stoppable errors ((WORKER RECEIVE MESSAGE ERROR: internal error: tried to deschedule a descheduled thread). 

**If you got an error message, please include it here.**
a non-stoppable errors ((WORKER RECEIVE MESSAGE ERROR: internal error: tried to deschedule a descheduled thread). 

**Please include any other relevant details**
OS version : os x 11.5.2
racket version : installed version 8.2 with brew "brew install racket"

**Comment by sorawee** [comment]
@madeinquant got it working, according to https://benknoble.github.io/racket-slack-archive/dev/2021-08-22.html, and it doesn't seem like there's any actionable thing to do for us. Closing.

**Comment by benknoble** [comment]
Hey, glad the archive was actually useful.
