### ISSUE TITLE
raco ctool: --runtime flag broken

### ISSUE THREAD

**Issue by Bogdanp** [racket/racket#3977]
**What version of Racket are you using?**
CS HEAD on macOS 11.4

**What program did you run?**

Given an empty Racket module:

```racket
#lang racket/base
```

Building a `zo` with

    raco ctool --mods test.zo test.rkt 

works fine. However, when I try to collect the runtime files with

    raco ctool --runtime res --mods test.zo test.rkt

the process fails with

```
mach-o: unrecognized #x38077e23
  context...:
   /Users/bogdan/sandbox/racket/racket/collects/compiler/distribute.rkt:20:2: assemble-distribution
   /Users/bogdan/sandbox/racket/racket/share/pkgs/cext-lib/compiler/commands/ctool.rkt:252:0
   body of "/Users/bogdan/sandbox/racket/racket/share/pkgs/cext-lib/compiler/commands/ctool.rkt"
   /Users/bogdan/sandbox/racket/racket/collects/raco/raco.rkt:41:0
   body of "/Users/bogdan/sandbox/racket/racket/collects/raco/raco.rkt"
   body of "/Users/bogdan/sandbox/racket/racket/collects/raco/main.rkt"
```

The failure occurs in `add-plt-segment` in `compiler/private/mach-o.rkt` when removing the signature from the generated `.zo` file (attached).

[ctool16302478601630247860344.zip](https://github.com/racket/racket/files/7072695/ctool16302478601630247860344.zip)

It seems like the fix in this case is probably for `assemble-distribution` to not attempt to sign the `.zo`.

**What should have happened?**

The `.zo` should be generated, and the runtime files should be collected in a folder called `res`.

**Comment by mflatt** [comment]
Thanks for the report!
