### ISSUE TITLE
Racket aborts in Google Cloud Run

### ISSUE THREAD

**Issue by cayhorstmann** [racket/racket#3980]
**What version of Racket are you using?**
7.2 

**What program did you run?**
`racket`
Please include a short example that triggers the bug
```
echo "(writeln 42)" | racket
```
**What should have happened?**
I should have seen an output of 42

**If you got an error message, please include it here.**
The message is: 
```
Aborted
```

**Please include any other relevant details**
e.g., the operating system used or how you are running the code.

This is on a 512M Google Cloud Run machine, executing a Docker container with Ubuntu 20.04 and the `racket` package installed with `apt`. When I run the same Docker container locally, there is no problem. Sadly, there is no other error message. The Google Cloud log has: `Uncaught signal: 6, pid=39, tid=39, fault_addr=0`

**Comment by sorawee** [comment]
7.2 is quite old (two years ago). If you use the PPA (https://launchpad.net/~plt/+archive/ubuntu/racket), which has Racket 8.2, do you still see the same error? FWIW, I have been using Racket 8.2 in Docker with Ubuntu 20.04 too, and it runs just fine.

**Comment by cayhorstmann** [comment]
More memory didn't solve it. I ran strace and saw that the crash was caused by a bad pointer dereference. But it works with the version from the PPA, so I guess that's what I'll have to do.
