### ISSUE TITLE
Error in comment/uncomment in DrRacket 8.2 on Gnome on Fedora 34 

### ISSUE THREAD

**Issue by hblazeviczx6r** [racket/racket#3986]
I reported this originally half a year ago. But I have not been using Racket since then. Just now I noticed that there is a new version out (8.2) so I tried it, and surely commenting is fixed, but now uncomment does nothing! 
This is even worse than before, because if I commented out with a box, I'm stuck with this box forever. 

Hrvoje Blazevic

**Comment by shhyou** [comment]
Closing as racket/drracket#587 now tracks this issue too.
