### ISSUE TITLE
check-expect in drracket doesn't display rationals (for a failing unit-test)

### ISSUE THREAD

**Issue by ibarland** [racket/racket#3988]
**What version of Racket are you using?**
8.2 [cs]

**What program did you run?**
; in beginning-student:
`(check-expect  1  3/4)`

**What should have happened?**
a message saying "Actual value `1` differs from `0.75`" 
(or similar -- however rationals should get displayed in the error-message)

**If you got an error message, please include it here.**
the message actually reads "Actual value `1` differs from `#<image>`"
(that is, it literally says "`#<image>`").

![check-expect-bad-message](https://user-images.githubusercontent.com/287051/132575757-e488611c-c58f-461c-ac12-31681fd57535.png)

**Please include any other relevant details**
both macOS and Windows

**Comment by rfindler** [comment]
@mikesperber fixed this bug with [this commit](https://github.com/racket/htdp/commit/ed0ed3b9e12393f6f1aad4596514c82a6dede258), sadly after 8.2 was released.

**Comment by bwbecker** [comment]
Can we get version 8.3 released immediately with this fix?  I'm prepping an assignment for my students and got:
![screenshot_731](https://user-images.githubusercontent.com/1038662/132907579-652e216d-8311-4fd5-9ad4-156897383e6f.png)
That isn't helpful to me, the instructor, and will confuse the hell out of students.  I can adapt, they're going to be challenged.

**Comment by rfindler** [comment]
The next release process is scheduled to start in October, so would complete in November. @jbclements is the release manager so probably has the best opinion on whether or not we can get something out faster that fixes this bug.

**Comment by mfelleisen** [comment]
We discussed the fix and moving up the release.  Our conclusion is that a rushed release is a bad idea. 

[[ You are lucky that your school/university would update from 8.2 to 8.3 immediately. ]]
