### ISSUE TITLE
Trouble opening DrRacket 

### ISSUE THREAD

**Issue by NqteTheGreqt** [racket/racket#3992]
I am having trouble opening DrRacket after installing it, when I open it I get this message saying “This app can’t run on your PC, To find a version for your OC, check with the software publisher.”

**Comment by otherjoel** [comment]
It sounds like you're using Windows. Can you confirm which version number and build of Racket you installed — 32-bit or 64-bit?

![image](https://user-images.githubusercontent.com/1553115/133127987-d30466e5-675c-4672-abf9-a9ce24fc4b0a.png)

Also can you confirm which exact version of Windows you’re running? Specifically this information (supposing you use Windows 10):

![image](https://user-images.githubusercontent.com/1553115/133127455-e905bafa-6d16-4856-99eb-dbc49fc01090.png)

**Comment by otherjoel** [comment]
I see a similar thread was opened on Racket’s Google Groups list at the same time as yours. Assuming you are the same person who started that thread, [your replies][1] indicate that you’re running an ARM CPU. The Windows downloads of Racket are compiled for x86, not ARM, which would explain why you are seeing this error message.

[1]: https://groups.google.com/g/racket-users/c/WVSMb2uKQjo
