### ISSUE TITLE
The Optimizer Shares Mutated Variable Across Modules

### ISSUE THREAD

**Issue by shhyou** [racket/racket#3998]
**What version of Racket are you using?**

Welcome to Racket v8.2.0.8 [cs].
commit 80dafee8db4e1c4224b2456dab1a89b9e2de1285

Racket v8.2 BC is not affected.

**What program did you run?**

The module with a mutated variable:

```racket
;; mutated.rkt
#lang racket/base

(provide (all-defined-out))

(define X '())
(define (change-X!)
  (set! X (cons 'shouldnt-be X)))
```

The module that uses the mutated variable:

```
#lang racket/base

(require "mutated.rkt")

(let ([copy-of-X X])
  (change-X!)
  copy-of-X)
```

**What should have happened?**

`copy-of-X` is empty.

**Actual behavior**

`copy-of-X` is `'(shouldnt-be)`.

**Comment by mflatt** [comment]
Thanks for the report. It's surprising that we haven't hit this schemify bug earlier!

**Comment by shhyou** [comment]
Thanks for the instant fix! Indeed, it's surprising that this bug had been alive and well for two years.
