### ISSUE TITLE
glob.rkt fails unit test on Windows

### ISSUE THREAD

**Issue by Danl2620** [racket/racket#4000]
**What version of Racket are you using?**

8.2 [cs]

**What program did you run?**

Load the file `racket/racket/collects/file/private/glob.rkt` from the Racket distribution into Dr Racket on Windows. Run it (you can also eval the same file including the `test` submodule).

**What should have happened?**

It should complete without error.

**If you got an error message, please include it here.**

`check-equal?: path-string->glob:unambiguous [645:8:23] actual value C:\a\b\c differs from expected /a\b\c`

**Please include any other relevant details**

Windows only.

**Comment by Danl2620** [comment]
All the tests referring to an absolute path fail at the moment. 

Also, I originally investigated this because the `**` glob wasn't working for me on Windows (see slack thread: https://racket.slack.com/archives/C06V96CKX/p1632241928389300)

**Comment by sorawee** [comment]
I will assign this to @bennn, since he said he will fix it.
