### ISSUE TITLE
Package regressions for 8.3 release

### ISSUE THREAD

**Issue by jbclements** [racket/racket#4024]
Currently, the following packages either fail to build, or have test failures, regressing from 8.2.

8.2 build: https://pkg-build.racket-lang.org
8.3 pre-release build: https://plt.eecs.northwestern.edu/release-pkg-build/

Use check-boxes to indicate "IMO not a release blocker (anymore)"

- [x] ("graph-test" . (no-docs test-fail)) : https://plt.cs.northwestern.edu/release-pkg-build/server/built/test-fail/graph-test.txt

One test fails, after a timeout of 180 seconds. Emailed Stephen Chang to ask about it.

He adjusted the timeout (though ... this may not have had an effect? not sure?) Either way, the current pkg-build does not show it failing tests as of now (2021-10-24 11:54EST)

- [X] ("repltest" . (success test-fail))

Looks like this package depends on the output of Typed Racket which has apparently gotten more precise, might just be a case of updating test cases.

emailed listed email to see what's up.

```
--------------------
FAILURE
name:       check-equal?
location:
  /home/root/user/.local/share/racket/8.2.900/pkgs/repltest/private/run-interactions.rkt:43:10
actual:
  "- : (values Integer (List Positive-Byte Any)) [more precisely: (Values Zero (List Positive-Byte Any))]\n0\n'(3 2)\n"
expected:
  "- : (values Integer (Listof Any)) [more precisely: (Values Zero (List Positive-Byte Any))]\n0\n'(3 2)\n"
--------------------
--------------------
FAILURE
name:       check-equal?
location:
  /home/root/user/.local/share/racket/8.2.900/pkgs/repltest/private/run-interactions.rkt:43:10
actual:     "- : (Pairof Positive-Index (Listof Positive-Index))\n'(2 3 4 5)\n"
expected:
  "- : (Listof Positive-Index) [more precisely: (Pairof Positive-Index (Listof Positive-Index))]\n'(2 3 4 5)\n"
--------------------
```

not waiting any more, not a release blocker IMO.

- [x] ("rodot" . (success build-fail))

- [x] ("satore" . (success build-fail))

- [x] ("video-v0-0" . (test-fail install-conflict))

**Comment by jbclements** [comment]
Okay, Stephen doesn't see any obvious problem with graph-test, bumped up the timeout a bit and we'll see what happens.

**Comment by stchang** [comment]
Awesome, I didn't know that was available. Thanks!
