### ISSUE TITLE
cs: pre-release installers fail on Windows

### ISSUE THREAD

**Issue by Bogdanp** [racket/racket#4037]
The installers at http://pre-release.racket-lang.org/installers/racket-current-x86_64-win32-cs.exe started failing in CI about three or four weeks ago. When I try to run the installer on a Windows 10 VM, I get:

<img width="436" alt="Screenshot 2021-10-31 at 08 36 38" src="https://user-images.githubusercontent.com/43347/139571393-60142f6e-6d9f-437b-979e-c54fe10a8924.png">

The pre-release installer for BC [works](https://github.com/Bogdanp/setup-racket/runs/4058661237?check_suite_focus=true).

**Comment by mflatt** [comment]
There has been an issue with the build machine creating an incomplete archive — possibly running out of disk space. (The distro-build driver should have noticed the failure, but it didn't. We've fixed that problem for the future.) @jbclements has freed up some space on the machine, so hopefully it will work on the next round.

**Comment by Bogdanp** [comment]
Looks like that fixed it: https://github.com/Bogdanp/setup-racket/runs/4077088450?check_suite_focus=true

Thanks!
