### ISSUE TITLE
`lookup-errno` does not work on Apple Silicon Installer (but works on Intel Installer)

### ISSUE THREAD

**Issue by lihebi** [racket/racket#4039]
**What version of Racket are you using?**
- 8.1/8.2 [cs] *Apple Silicon Installer*: does **not** work
   - But 8.2 [cs] *Intel Installer*: works

**What program did you run?**
Please include a short example that triggers the bug

```racket
(require ffi/unsafe)
(lookup-errno 'EAGAIN)
```

**What should have happened?**

Return 35

**If you got an error message, please include it here.**

ERROR: lookup-errno: unsupported

**Please include any other relevant details**
M1 Macbook Air, MacOS Monterey, 12.0.1, using both racket command and Dr. Racket

**Comment by mflatt** [comment]
Thanks for the report! This has been fixed for the upcoming v8.3 release (pre-release candidates at https://pre-release.racket-lang.org/).
