### ISSUE TITLE
Dr Racket Help Desk

### ISSUE THREAD

**Issue by TylerSchaefer4** [racket/racket#4045]
For some reason when I press "Search in Help Desk for '____'" it just opens up the Search Manuals section of the racket documentation and when I search something it doesn't give me any results. It used to bring me to the exact section I needed in the right Language too and I'm not sure how to get it to do that again.

**Comment by samth** [comment]
What operating system and browser are you using? What version of Racket do you have?

**Comment by TylerSchaefer4** [comment]
> What operating system and browser are you using? What version of Racket do you have?

I'm using Mac OS and the browser that opens is Google. And it's version 8.2. 
I feel like there was something wrong with my computer yesterday and it asked me to decide between two choices and that may have been what changed it. I'm not great with the tech stuff though so I don't really know what I did.

**Comment by shhyou** [comment]
I think it's expected that "Search in Help Desk" opens the search page and displays the search result. To open the the documentation directly, click the "View documentation" item from the right-click context menu.

(The latter is not available for student languages unless you click Check Syntax.)
