### ISSUE TITLE
pidigits.rkt benchmark slowdown

### ISSUE THREAD

**Issue by samth** [racket/racket#4049]
The pidigits.rkt benchmark (https://github.com/racket/racket/blob/master/pkgs/racket-benchmarks/tests/racket/benchmarks/shootout/pidigits.rkt) has slowed down about 3x on Racket CS from 8.0 to 8.3 (in particular to 8.1). From initial investigation by @mflatt it appears that the Burnikel-Zeigler division implementation is what's slow (even slower than schoolbook division for this benchmark).

**Comment by samth** [comment]
The relevant gambit code, which we might want to look at, is here: https://github.com/gambit/gambit/blob/ead2ba415b5c4cae9bb0f4505e3e359a97f00ad7/lib/_num.scm#L10087-L10407

**Comment by mflatt** [comment]
Addressed by adf096e75f8dc3a555dc3f1d2900fa287a6a9d42
