### ISSUE TITLE
8.3 error when using hash-union to merge a mutable table onto an immutable base.

### ISSUE THREAD

**Issue by djholtby** [racket/racket#4055]
**What version of Racket are you using?**
 8.3 [cs]

**What program did you run?**

```
#lang racket/base
(require racket/hash)

(define h1 (make-immutable-hash '((a . 2))))
(define h2 (make-hash '((a . 1) (b . 2))))

(hash-union h1 h2 #:combine (λ (old new) new))
```

**What should have happened?**
```
'#hash((a . 1) (b . 2))
```

**If you got an error message, please include it here.**

```
hash-clear!: contract violation
  expected: (and/c hash? immutable?)
  given: '#hash((a . 1) (b . 2))
```

**Please include any other relevant details**

The above call is allowed by the contract for hash-union, which says that only h0 must be immutable.

#3967 is breaking the contract of `hash-clear` when it should use `hash-copy-clear`

It also appears that the contract applied to `hash-clear` incorrectly labels it as `hash-clear!`

**Comment by mflatt** [comment]
The `hash-clear` function doesn't have an externally imposed contract. The error message comes from the use of `raise-argument-error`. It would be better for these functions to use `define/who` with `who` in error messages, but the simpler repair is to change `'hash-clear!` in the `raise-argument-error` call.

**Comment by orreksu** [comment]
Thank you for details! I will go with better approach.
Should I also do a separate issue for other functions to be rewritten using `define/who` in hash module?

Also, is `define/who` documented somewhere? I assume it introduces the name of the function into it's scope with identifier `who`. I am just curious who it works, but can't find where it's introduced.
