### ISSUE TITLE
`trace-define` fails in `local`

### ISSUE THREAD

**Issue by jasonhemann** [racket/racket#4066]
I thought I could use `trace-define` in place of any `define`. Should I expect this ASL program to work? Right now it signals an error.

```
(require racket/trace)

(define (foo xs) 
    (local [(trace-define (inner xs)
              (if (null? xs) #t (inner (cdr xs))))]
      (inner xs)))
```

I do require the `racket/trace` module here. Using `trace-define` in `local` in `#lang racket` is also an error. 

```
; /Applications/Racket v8.2/collects/racket/trace.rkt:323:63: local: not a definition
;   at: (trace inner)
;   in: (local ((trace-define (inner xs) (if (null? xs) #t (inner (cdr xs))))) (inner xs))
```

**Comment by michaelballantyne** [comment]
It looks like `(trace-define (inner xs) ...)` expands to:

```
(begin
  (define (inner xs) ...)
  (trace inner))
```

This works in definition contexts that allow a mix of definitions and expressions, like `let`. But `local` only allows definitions, so it raises an error at the `(trace inner)` expression.

I think it could work to modify the `trace-define` macro to instead expand to:

```
(begin
  (define (inner xs) ...)
  (define _ (trace inner))) 
```

**Comment by sorawee** [comment]
Fixed. Closing.
