### ISSUE TITLE
`in-list` returns a stream, but not `in-vector`

### ISSUE THREAD

**Issue by zyrolasting** [racket/racket#4071]
Full disclosure: Not sure if this is a bug.

**What version of Racket are you using?**
e.g., 8.2 [cs]

**What program did you run?**
```racket
> (stream? (in-list '()))
#t
> (stream? (in-vector #()))
#f
```

**What should have happened?**

Print `#t` in both cases, if my expectations are normative.

**Comment by mflatt** [comment]
That's as intended. The `in-...` functions return sequences. Some sequences are streams, which have a `first` operation that always returns the same thing for the same stream and a `rest` operation that returns the rest of the stream without retaining the first. A vector sequence doesn't support stream operations.

**Comment by zyrolasting** [comment]
Understood, thanks.
