### ISSUE TITLE
assets at https://github.com/racket/racket/releases all refer to 8.0

### ISSUE THREAD

**Issue by spdegabrielle** [racket/racket#4095]
assets at https://github.com/racket/racket/releases all refer to 8.0

![image](https://user-images.githubusercontent.com/108047/146057857-fe6a3a3c-c839-4c00-9647-a6a6201d2bb4.png)

**Comment by sorawee** [comment]
I don't see any problem. Perhaps someone already fixed it? 

FWIW, it looks like you are viewing the Racket 8.0 release (Walter H. Yang is a contributor in Racket 8.0 but not 8.1, 8.2, nor 8.3), so assets referring to 8.0 is totally expected.

**Comment by samth** [comment]
Those are the assets for release 8.0. Other releases have their own assets. There are more for 8.0 because I experimented with adding all the release artifacts.
