### ISSUE TITLE
ASL request

### ISSUE THREAD

**Issue by morazanm** [racket/racket#4116]
Can ASL be extended with while syntax or a teachpack for while syntax?

I am thinking something along these lines:

#lang racket
(provide while)

(define-syntax while
  (syntax-rules ()
    ((while condition body ...)
     (let loop ()
       (if condition
           (begin
             body 
             ...
             (loop))
           (void))))))

**Comment by mfelleisen** [comment]
This looks about right to me. 

I recommend writing the teachpack on GitHub, and then turning it into a package on pkgs.racket-lang.org for your courses. (I have done this for other special-purpose syntax features at NU in the past.)
