### ISSUE TITLE
:do-in results in an ambiguous binding at top-level

### ISSUE THREAD

**Issue by sorawee** [racket/racket#4124]
**What version of Racket are you using?**
8.3

**What program did you run?**

```
#lang racket/load

(define-sequence-syntax in-digits
  (lambda () #'values)
  (lambda (stx)
    (syntax-case stx ()
      [[(d) (_ nat)]
       #'[(d)
          (:do-in
           ([(n) nat])
           values
           ([i n])
           (not (zero? i))
           ([(j d) (quotient/remainder i 10)])
           #t
           #t
           [(- i 1)])]]
      [_ #f])))

(println (for/list ([i (in-digits 12)]) i))
```

**What should have happened?**

It should run fine, just like how it runs fine in a module.

**If you got an error message, please include it here.**

```
i: identifier's binding is ambiguous
```

**Please include any other relevant details**

Reported by @soegaard last month.

**Comment by mflatt** [comment]
This is not just specific to the top level. Replace `println` by `void` to see the same effect in `#lang racket`.

A `void` lets `#lang racket` know that it won't have anything to print, so it avoids wrapping a `lambda` around the `for` form as part of `call-with-values` and `(current-print)`. When you don't use `void`, the added `lambda` print printing happens to hide a problem with `for`.
