### ISSUE TITLE
Slow web page: png used instead of jpeg

### ISSUE THREAD

**Issue by soegaard** [racket/racket#4135]
This image is a png and ought to be a jpeg. 
The page is slow to load.

![image](https://user-images.githubusercontent.com/461765/150652670-7a0596d0-183a-4ec1-8bc1-c71d1243bdf0.png)

**Comment by winny-** [comment]
Is this related to content in https://github.com/racket/racket-lang-org ?

**Comment by soegaard** [comment]
Yes. It is this file:

https://github.com/racket/racket-lang-org/blob/6f5f26e2e33dca8c2232390662835685888da94c/www/index.html.pm

**Comment by sorawee** [comment]
Since this is now reported at https://github.com/racket/racket-lang-org/issues/208, which is a more appropriate place, I will close the issue.

Generally, it would be better to ask maintainers to transfer the issue, instead of creating a new, duplicate one.
