### ISSUE TITLE
Conflicts with additional exports from `(chezscheme)`

### ISSUE THREAD

**Issue by LiberalArtist** [racket/racket#4151]
Mostly this is a "do we consider this a bug?" sort of question.

With the upstream Chez Scheme 9.5.6 release, the value of:
```scheme
(memq 'string->uninterned-symbol
      (library-exports '(chezscheme)))
```
is `#f`, but with Racket 8.3.900's Chez Scheme 9.5.7.3, the `(chezscheme)` library does export `string->uninterned-symbol`.

This breaks <https://github.com/fedeinthemix/chez-mit>, a MIT/GNU Scheme compatibility library for Chez Scheme (for `scmutils`), because its `(mit core)` library exports `string->uninterned-symbol` (defined as `(define string->uninterned-symbol gensym)`), and [`(mit hash-tables)`](https://github.com/fedeinthemix/chez-mit/blob/68f3d7562e77f694847dc74dabb5ecbd106cd6be/mit/hash-tables.sls#L17-L20), for example, contains:
```scheme
  (import (except (chezscheme) error assert sort)
          (mit core)
          (mit curry)
          )
```

Of course, it is quite feasible to work around this difference as long as you're willing to patch `(mit core)` to use `meta-cond`. The question is, should this sort of (in a very strict sense) incompatibility with upstream Chez Scheme be considered a bug from the Racket variant's perspective? Of course, one consideration is that there's nothing comparable to running a Racket package build to detect this kind of problem.

For context, Nix recently (in https://github.com/NixOS/nixpkgs/pull/131833) packaged Racket's variant of Chez Scheme in addition to the upstream package, and I'm proposing to add it to Guix and use it on platforms that aren't supported upstream. From the dozen Guix packages that depend on Chez Scheme, this was the only error when building against Racket's variant.

**Comment by mflatt** [comment]
I'm ambivalent.

Historically, Chez Scheme hasn’t made any promises about the evolution of `(chezscheme)`, and adding things there is consistent with its design. It's not difficult to imagine a world where upstream Chez Scheme continues to evolve, and then a library implementation like `(mit core)` could run into the same sort of trouble.

But upstream Chez Scheme isn't growing in that way. We could emphasize compatibility and move the 106 additions (more than I would have guessed) to a separate library. Note that the additions would still be in `(chezscheme)`, but with a prefix like `rkt:`, since that's how `(chezscheme)` is implemented.

At the moment, I lean toward continuing to add to `(chezscheme)`, but I'm open to the case for compatibility.

**Comment by LiberalArtist** [comment]
That all makes sense to me, and I don't have a strong view myself (especially given that my interest is primarily in Racket).

Actually, I think these results are ultimately encouraging about compatibility. Looking at Debian and Nix, it appears that Guix has all of the packages in either of them that use Chez Scheme (and a few that aren't elsewhere) with two exceptions:

- Idris 2, both upstream and as packaged by Nix, uses Racket's Chez Scheme variant for its Chez Scheme backend (as opposed to its Racket backend) for platform support (https://github.com/idris-lang/Idris2/pull/2219). (There is a [patch](https://issues.guix.gnu.org/46124) to add it to Guix, but I'm not sure where it stands.)
- Debian's [`slib`](https://packages.debian.org/bullseye/slib) package has a build dependency on `chezscheme` and generates a "catalog file" for it. (Guix's `slib` package doesn't generate any catalogs: it seems to be used only as a build input to SCM and Gauche. The `chez.init` file says that it is for version 8.4 (though the comments in the header seem to say it was last updated for 6.0a in 1999), but I have successfully generated the catalog file as Debian does, at least, with both the current upstream release and the Racket release candidate. (For comparison, `mzscheme.init` includes a check for `(string<? (version) "200")`.)

So I think the issue with `(mit core)` may be the only problem in all of the Chez Scheme code that can be installed by a package manager.

**Comment by mflatt** [comment]
Racket's Chez Scheme and upstream are now the same, so I think we can close this.
