### ISSUE TITLE
sandbox: access disallowed by code inspector to protected variable from kw usage

### ISSUE THREAD

**Issue by sorawee** [racket/racket#4165]
**What version of Racket are you using?**
8.4

**What program did you run?**

```
#lang racket

(require racket/sandbox)

(define e (make-evaluator 'racket/base))

(e '(module test racket
      (provide t)
      (define (t #:a [a "12345678"]) (list a))))
(e '(require 'test))
(e '(t))
```

**What should have happened?**

The program should run.

**If you got an error message, please include it here.**

```
access disallowed by code inspector to protected variable
  from module: '#%unsafe in: unsafe-undefined
```

**Please include any other relevant details**

Switching keyword argument to optional positional argument could be used to workaround the problem.

The problem occurs for a default value that is a string of length at least 8. A string of length 7 does not trigger the bug.

**Comment by sorawee** [comment]
The issue seems to be that the expanded program has `unsafe-undefined`, and the sandbox doesn't like that.

It looks like either it should not expand to `unsafe-undefined`, or `unsafe-undefined` should be whitelisted (not sure if this will compromise the the system's safety though).

**Comment by samth** [comment]
Since I originally had this suspicion, note that changing the language of the test module to `racket` does not change the error.

**Comment by mflatt** [comment]
This turns out to be a bug in keyword-application expansion, instead. An `unsafe-undefined` reference was changed to a symbol and then back to an identifier. The conversions happened in the same context, so the binding worked out, but  permission was lost along the way.
