### ISSUE TITLE
The new 8.4 REPL does not work in the new way on Ubuntu (PPA installation)

### ISSUE THREAD

**Issue by haijinSk** [racket/racket#4169]
I like DrRacket, but for a "low-resource work" I use command-line REPL, so I was happy to read: "Command-line Racket [8.4] provides a new expression editor by default ..."

Unfortunately, at least in my case, there in no "language-sensitive syntax coloring" and **even the command history via the up arrow key is missing**. In other words, it works much like the REPL of some old programming language when I forget write "rlwrap" before I run it on the command-line, except I can write an expression on more than one line and press "tab" for indentation.

I have Ubuntu 20.04.4 LTS with GNOME Terminal and Racket 8.4 installed via Ubuntu PPA.

I'm not a professional programmer (though as a teenager I owned Commodore 64 with its "human scale" 6502 assembly), I don't know low-level things like programming in C or the architecture of operating systems and I'm relatively new to GNU/Linux. So maybe I did not get something. 

Please, don't get me wrong. I love Racket and all you guys working on it (thank you very much!) and I can use the old readline REPL with no problem (via ",input readline"). And I'm painfully aware there are more important things... still Covid and the war in my neighbour country, Ukraine (the catastrophic Russian attack/invasion of the country), for example.

Again, thank you for Racket, the programming language one can love.

**Comment by mflatt** [comment]
@takikawa Is the Ubuntu PPA maybe built without the `ncurses-dev` package installed? Racket needs that at `configure` time to enable the expression editor.

**Comment by haijinSk** [comment]
Thank you sir, but now I've tried "sudo apt install libncurses-dev" and  it writes: "libncurses-dev is already the newest version (6.2-0ubuntu2)."

**Comment by mflatt** [comment]
Hi @haijinSk - Thanks for checking, but`libncurses-dev` would need to be installed at the time that Racket is compiled to create the PPAs. So, you could build Racket from source or install from https://download.racket-lang.org/, but I think @takikawa will need to update the PPA to make that installation work (if I'm guessing right about the problem).

**Comment by haijinSk** [comment]
Sir, thank you very much for the explanation, for your response I for your fantastic work on Racket...

**Comment by haijinSk** [comment]
Now, I'd removed the PPA installation and I've tried the "sudo sh racket-8.4-x86_64-linux-cs.sh" installation and it seems that the new REPL/expression editor now works, works great in the new, announced way (color, indentation). So I think I can confirm that the problem is in the PPA installation.

**Comment by takikawa** [comment]
Thanks for the bug report on the PPA!

@mflatt Thanks for the info about ncurses, I think there's a good chance that's the problem as neither Ubuntu nor Debian list it in the build dependencies. I'll test it out and issue an update for the PPA if it works.

**Comment by haijinSk** [comment]
[takikawa](https://github.com/takikawa), sir, thank you very much.
