### ISSUE TITLE
expr/c fails with an internal error when imported through a module path containing a literal path

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#4174]
Here are two modules, `a.rkt` and `b.rkt`:

```racket
;; a.rkt
#lang racket/base
(require (for-syntax racket/base)
         syntax/parse/define)

(provide m)

(define-syntax-parse-rule (m e)
  #:declare e (expr/c #'string?)
  e.c)
```
```racket
;; b.rkt
#lang racket/base
(require (for-syntax racket/base))

(define-syntax (require-a-via-path stx)
  #`(#%require #,(datum->syntax stx (string->path "a.rkt"))))

(require-a-via-path)
(m "hello")
```

Compiling `b.rkt` on succeeds on Racket v8.4, but it fails on HEAD with the following error:

```
module-path-index-split: contract violation
  expected: module-path-index?
  given: #f
  context...:
   /home/alexis/code/racket/racket/master/racket/collects/syntax/contract.rkt:204:38: loop
   [repeats 1 more time]
   /home/alexis/code/racket/racket/master/racket/collects/syntax/contract.rkt:181:0: get-source-expr
   /home/alexis/code/racket/racket/master/racket/collects/syntax/contract.rkt:130:0: wrap-expr/c
```

The error arises from the following code, which was introduced in https://github.com/racket/racket/commit/ba2a44f33b4b62cc2e87d4402ac3d23a3fb76bae:

https://github.com/racket/racket/blob/a6e5ce526dbd25d893bd92235b3852948e447ce0/racket/collects/syntax/contract.rkt#L204-L209

The issue is that sometimes the second result of `module-path-index-split` can be `#f` even though the first result is not. In particular, module path indexes created from an embedded literal path have this property:

```racket
> (module-path-index-split
   (module-path-index-join
    (string->path "foo.rkt")
    (module-path-index-join #f #f)))
#<path:foo.rkt>
#f
```

To be honest, I do not really understand the value of such module path indexes. It seems like it would be simpler but otherwise equivalent to return a “self” module path index for the second result of the above expression. Regardless, it seems like `wrap-expr/c` needs to be adjusted to handle this case.

**Comment by mflatt** [comment]
Thanks for doing all of the work here! I just added a check for `#f`, which seems like the right local change (i.e., without trying to reconsider how module paths are represented more globally).

**Comment by lexi-lambda** [comment]
Thanks!
