### ISSUE TITLE
[Feature Request] ...

### ISSUE THREAD

**Issue by subdudu** [racket/racket#4191]
**Is your feature request related to a problem? Please describe.**

When I use "in-directory", it will traverse all directories including symlink directories. But I don't want to traverse symlink directories. It's possible to use directory-list to bypass this problem, but it's a little tedious.

**Describe the solution you'd like**

Can "in-directory" add an option "follow-symlink-directory?", so that it will not follow symlink directories?

**Describe alternatives you've considered**

Sorry, I don't have any alternative.

**Do you want to contribute to this feature**

Yes, I'm interested.

**[Optional] Additional context**

**Comment by LiberalArtist** [comment]
Here's a way to use `in-directory` but not traverse directories that are symlinks:

```
philip@bastet:/tmp/4191$ tree -l
.
├── real
│   └── baz
└── symlink -> /tmp/4191-aux/
    └── foo

2 directories, 2 files
philip@bastet:/tmp/4191$ racket
Welcome to Racket v8.4 [cs].
> (for/list ([pth (in-directory #f (lambda (dir)                
                                     (not (link-exists? dir))))])
    pth)
'(#<path:real> #<path:real/baz> #<path:symlink>)
> 
```

**Comment by subdudu** [comment]
Thanks, it works.
