### ISSUE TITLE
[Feature Request] `~if` for syntax templates

### ISSUE THREAD

**Issue by jackfirth** [racket/racket#4199]
**Is your feature request related to a problem? Please describe.**

I've got a syntax class that exposes a boolean-valued attribute, and I'd like to conditionally produce either one syntax object or another depending on that attribute. For example:

```scheme
(begin-for-syntax
  (define-syntax-class condition-expression
    #:attributes (negated? base-condition)
    #:literals (not)
    (pattern (not base-condition:expr) #:attr negated? #true)
    (pattern base-condition:expr #:attr negated? #false)))

(define-syntax-parse-rule (check! [condition:condition-expression message:str] ...)
  (begin
    ((~if condition.negated? unless when) condition.base-condition
      (error message))
    ...))
```

**Describe the solution you'd like**

I'd like `(~if condition true-template false-template)` to be something like a template metafunction where it checks if `condition` (which should be an attribute) is false, and if it is then `false-template` is used and otherwise `true-template` is used. It should cooperate with ellipsis too, so that `(~if condition a b) ...` works correctly. As a side note, this would make `(~? template1 template2)` equivalent to `(~if template1 template1 template2)`.

**Describe alternatives you've considered**

Today, there are two possible solutions. I can either take the templates I would use in the true and false branches of `~if` and compute them within the syntax class directly, like this:

```scheme
(begin-for-syntax
  (define-syntax-class condition-expression
    #:attributes (base-condition when-or-unless)
    #:literals (not)
    (pattern (not base-condition:expr) #:with when-or-unless #'unless)
    (pattern base-condition:expr #:with when-or-unless #'when)))

(define-syntax-parse-rule (check! [condition:condition-expression message:str] ...)
  (begin
    (condition.when-or-unless condition.base-condition
      (error message))
    ...))
```

Or I can use a `#:with` clause in the macro combined with `for/list`, like this:

```scheme
(begin-for-syntax
  (define-syntax-class condition-expression
    #:attributes (negated? base-condition)
    #:literals (not)
    (pattern (not base-condition:expr) #:attr negated? #true)
    (pattern base-condition:expr #:attr negated? #false)))

(define-syntax-parse-rule (check! [condition:condition-expression message:str] ...)
  #:with (when-or-unless ...)
  (for/list ([negated? (in-list (attribute condition.negated?))])
    (if negated? #'unless #'when))
  (begin
    (when-or-unless condition.base-condition
      (error message))
    ...))
```

The problem with the first approach is that it makes it difficult to reuse syntax classes in different macros. Each macro that needs to compute something conditionally based on the attributes of the syntax class needs to add that computation into the class, and that might not be relevant to other macros that use the class. The problem with the second approach is that as the ellipsis depth increases, more and more busywork has to be done to turn the attribute into a list of lists of lists and then back into syntax objects again.

**Do you want to contribute to this feature**

I tried to make it myself with `define-template-metafunction`, but my attempt failed. This might be too deep in the guts of the syntax template system for me to understand.

**Additional context**

The macro I used in these examples is a bit silly, but it's a simplified form of several macros in my [Resyntax](https://github.com/jackfirth/resyntax/) project. The macros use these sorts of conditionals to produce much tidier code than you'd expect a macro to produce because they're used by Resyntax to refactor code, rather than generating code that's hidden from users and sent off to the optimizer to have these sorts of redundancies cleaned up.

**Comment by LiberalArtist** [comment]
Since all of the [currently allowed uses](https://docs.racket-lang.org/reference/stx-patterns.html#%28form._%28%28lib._racket%2Fprivate%2Fstxcase-scheme..rkt%29._syntax%29%29) of `~?`:
```racket
(~? template template)
(~? head-template head-template)
(~? head-template)
```
have either 1 or 2 subforms, it seems like there's room for a `(~? test consequent alternative)` variant. That could avoid the potential for name conflicts à la https://github.com/racket/racket/issues/2031#issuecomment-379064463.

It looks like the `test` subform in your `~if` is a syntax pattern. I could also imagine it being an expression. I don't know what the pros and cons would be.

**Comment by jackfirth** [comment]
I lean towards letting it be a pattern, like in `~?`. That makes it easy to combine with `~@`.

**Comment by LiberalArtist** [comment]
I guess I didn't say so, but I've also wanted something like this.

I think I also agree about having the test be a pattern:

- All of the other subforms for `~?` and `~@` are patterns, whereas `unsyntax` and `unsyntax-splicing` are the only escapes from patterns/templates to expressions. In particular, it seems like introducing the possibility that subforms of `syntax` (as opposed to `quasisyntax`) might be expressions might have unintended consequences.
- If you want to program in the world of expressions, you already have `unsyntax` and `unsyntax-splicing`. So it seems like big benefit of this feature is for the times when you want to stay in the world of patterns and templates.

**Comment by rmculpepper** [comment]
I'd prefer not to add another template form, and I'd especially prefer not to add a template form that permits attributes whose values are not `(U #f Syntax)`. Note that if the attribute x.a has the value `#t`, then `(~? x.a template2)` raises an error; it does not produce the second template.

If you change your syntax class's attributes to be syntax booleans instead of booleans, you can write `~if` as a template metafunction that does case analysis on the first argument. (It's still a meta*function*, though: it's strict in the instantiation of its subtemplates.)

**Comment by jackfirth** [comment]
Oh, fantastic! With that advice I was able to write this:

```scheme
#lang racket/base


(require syntax/parse
         syntax/parse/experimental/template)


(define-template-metafunction (~if stx)
  (syntax-parse stx
    #:track-literals
    [(_ condition true false)
     (if (syntax-e #'condition) #'true #'false)]))


(with-syntax ([(condition ...) #'(#true #false #false)]
              [a #'foo]
              [b #'bar])
  #'((~if condition a b) ...))
```

And that evaluates to `#'(foo bar bar)` as I expect it to. I'll close this issue then since template metafunctions work for my purposes. Thank you Ryan!
