### ISSUE TITLE
New tab icon next to tabs doesn't do anything

### ISSUE THREAD

**Issue by millennialcel** [racket/racket#4209]
**What version of Racket are you using?**
8.4 on Windows

**What should have happened?**
Should create a new tab.

**Please include any other relevant details**
e.g., the operating system used or how you are running the code.
![Screenshot 2022-04-16 144841](https://user-images.githubusercontent.com/92554157/163687685-e3c37b93-c3ba-4367-a923-8e83f241db8f.png)

**Comment by gus-massa** [comment]
I think this should be reposted as a feature request.

**Comment by rfindler** [comment]
Okay, I've added the callback to it. If we don't like it, we can remove it, no problem.

**Comment by sorawee** [comment]
The tab bar on Mac doesn't have this "+" button, right?

**Comment by rfindler** [comment]
Only if you set `PLT_FLAT_PORTABLE_TAB_PANEL` before starting up DrRacket. It may be possible to get it in the macos-implemented control, but the GUI libraries right now don't support it. The racket-implemented control and the windows control both do, tho.
