### ISSUE TITLE
Strange interaction between delimited continuations and parameterize

### ISSUE THREAD

**Issue by Bogdanp** [racket/racket#4216]
This feels like a bug, but may just be some sort of misunderstanding on my part regarding how these pieces are expected to interact. The same behavior is present on both BC and CS.

This program:

```racket
#lang racket/base

(define param-a (make-parameter #f))
(define param-b (make-parameter #f))
(define prompt (make-continuation-prompt-tag))

(define k #f)
(parameterize ([param-a "a"])
  (call-with-continuation-prompt
   (lambda ()
     (parameterize ([param-b "b"])
       (call-with-continuation-prompt
        (lambda ()
          ((call-with-composable-continuation
            (lambda (k0)
              (set! k k0)
              (abort-current-continuation
               prompt
               (lambda ()
                 (println `(abort ,(param-a) ,(param-b))))))
            prompt)))
        prompt)))
   prompt))

(k (lambda ()
     (println `(k ,(param-a) ,(param-b)))))
```

Prints:

```
'(abort "a" "b")
'(k #f #f)
```

Which seems right to me because the captured continuation only extends up to the second prompt, so when it gets invoked, the two parameters are unset. If I change that code to introduce an _unrelated_ parameterization between the second prompt and the `call/comp`:

```racket
#lang racket/base

(define param-a (make-parameter #f))
(define param-b (make-parameter #f))
(define param-c (make-parameter #f))
(define prompt (make-continuation-prompt-tag))

(define k #f)
(parameterize ([param-a "a"])
  (call-with-continuation-prompt
   (lambda ()
     (parameterize ([param-b "b"])
       (call-with-continuation-prompt
        (lambda ()
          (parameterize ([param-c "c"])
            ((call-with-composable-continuation
              (lambda (k0)
                (set! k k0)
                (abort-current-continuation
                 prompt
                 (lambda ()
                   (println `(abort ,(param-a) ,(param-b) ,(param-c))))))
              prompt))))
        prompt)))
   prompt))

(k (lambda ()
     (println `(k ,(param-a) ,(param-b) ,(param-c)))))
```

I get the following output:

```
'(abort "a" "b" #f)
'(k "a" "b" "c")
```

The first line is correct, but I am baffled by the second, and would have expected to see `(k #f #f "c")` instead.

**Comment by rmculpepper** [comment]
This behavior is known, but probably not widely.

The continuation does not contain independent continuation-marks mapping parameters to thread cells; there is one continuation-mark key that is mapped to an entire "parameterization" value, and a parameter acts as a key in a parameterization to look up a thread cell. So when you capture parts of the continuation with `parameterize` forms, you capture the entire parameterizations that they computed and installed. (See also the docs for "parameterization" in the reference.)

You can use Jay's "mark-parameters" library (https://docs.racket-lang.org/markparam/) to get the behavior you expected. Or you can use continuation marks directly.

**Comment by Bogdanp** [comment]
That makes sense. Thanks for the explanation!
