### ISSUE TITLE
Environment Variables different in DrRacket

### ISSUE THREAD

**Issue by Connor-XY** [racket/racket#4217]
**What version of Racket are you using?**
e.g., 8.3

**What program did you run?**
(system "nasm ...")

**What should have happened?**
On the command line, it works well. But inside the DrRacket, there is an error: "/bin/sh: nasm: command not found". I tried to print the $PATH. In DrRacket, the PATH is the default: /usr/bin:/bin:/usr/sbin:/sbin. I installed my nasm in /usr/local/bin and the environment on the command line is set well.

**If you got an error message, please include it here.**
I printed out the environment variables by calling (system "printenv") in DrRacket:

SHELL=/bin/zsh
TMPDIR=/var/folders/3z/bpgf6f4x7kscxhfl9zb51v5r0000gp/T/
USER=xy
COMMAND_MODE=unix2003
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.StDdlHOSNd/Listeners
__CF_USER_TEXT_ENCODING=0x1F6:0x0:0x0
PATH=/usr/bin:/bin:/usr/sbin:/sbin
LaunchInstanceID=827EAAE4-8EB6-490E-8F6A-73E79AA85CA5
__CFBundleIdentifier=org.racket-lang.DrRacket
PWD=/Users/xy/Documents/
XPC_FLAGS=0x0
XPC_SERVICE_NAME=application.org.racket-lang.DrRacket.41771784.41771790
SHLVL=1
HOME=/Users/xy
LOGNAME=xy
SECURITYSESSIONID=186a7
_=/usr/bin/printenv

This is different from the result when I call  (system "printenv") in Racket on the command line.

**Please include any other relevant details**
I am running it on macOS.

**Comment by capfredf** [comment]
I think if you start drracket from the command line, you will get the same result as you do at the repl.

When you launch apps in your gui environment,  the environment variables are in general different from the ones you see at the command line in a terminal

**Comment by Connor-XY** [comment]
Thank you. That solves the problem
