### ISSUE TITLE
struct-type-property guard inspector check, CS vs BC

### ISSUE THREAD

**Issue by rmculpepper** [racket/racket#4225]
When producing the "info" list given to a struct type property's guard procedure, Racket CS includes the super type descriptor, even if the current inspector does not control it, whereas BC does not.

The CS behavior seems more useful, since it allows the property guard to check whether the super struct type also implements the property and access the super type's property value. And the super struct type must be accessible in order to create the new struct type anyway, so the stricter check doesn't seem useful. The docs do say the stricter check is performed, but I'm not sure what the rationale was.

The following program demonstrates the difference by printing the info given to the struct type property guard:

    #lang racket/base
    (define-values (prop has-prop? prop-ref)
      (make-struct-type-property
       'prop
       (lambda (v info)
         (printf "guard got ~v, ~v\n" v info)
         v)))
    (struct a (x) #:property prop 1)
    (struct b a (y) #:property prop 2)

With CS, the second output line ends with `#<struct-type:a> #f`; with BC, it ends with `#f #t`.

Tested with Racket 8.5 CS and BC.

**Comment by mflatt** [comment]
Although the super type must be accessible to create a subtype using `make-struct-type`, I don't think it's necessarily the case that a use of `make-struct-type` plus some property means to give that property's implementation access to the super type. I don't have a concrete example offhand, but given the BC precedent and documentation, it seems like a case where CS should be fixed.

**Comment by mflatt** [comment]
Looking at the docs for [prop:auto-equal+hash](https://docs.racket-lang.org/scramble/index.html#%28def._%28%28lib._scramble%2Fstruct..rkt%29._prop~3aauto-equal%2Bhash%29%29), I see why you'd like to have the super type available, and so maybe just changing CS isn't the right idea. I can see the argument that using a structure-type property means trusting it to know about a super type.

**Comment by mflatt** [comment]
It would make a kind of sense to provide the super type when the property is already associated to the super type. That wouldn't expose any new structure types to properties, and it would work for `prop:auto-equal+hash`, but it's maybe too specific to someting like `prop:auto-equal+hash`.

**Comment by rmculpepper** [comment]
Yes, `prop:auto-equal+hash` is the immediate example I have in mind.

The `struct-type-info` procedure and most other operations involving struct types are still guarded by an inspector check. The main operations I can think of that are not covered by an additional inspector check are creation of new struct types and `{chaperone,impersonate}-struct` using the struct type as a witness. Another possibility would be to chaperone the super struct type (if it is not accessible by the current inspector) to remove those capabilities.

If the property's guard does not get the super struct type, then I think there's no reliable workaround; it cannot ask the user the include the super struct type in the property value, because it has no way of checking whether that is the correct super type.

This seems like an example where an insufficiently flexible security policy leads to less security overall. I think that most people who write `#:transparent` aren't actually contemplating the consequences of disabling the access control checks to reflective operations; they just want printing, equality, and hashing to work automatically. We should make it possible to separate the two.

**Comment by mflatt** [comment]
Ok, I'll push the change.
