### ISSUE TITLE
racket style guide contract-out example missing a require

### ISSUE THREAD

**Issue by HeladoDeBrownie** [racket/racket#4228]
the example [starting here](https://github.com/racket/racket/blob/448b77a6629c68659e1360fbe9f9e1ecea078f9c/pkgs/racket-doc/scribblings/style/unit.scrbl#L111) is missing a `(require racket/contract)` or `(require racket/contract/base)` preceding the `provide`, without which racket would complain that `contract-out` is not a provide sub-form

**Comment by mfelleisen** [comment]
See be6ea6d

**Comment by HeladoDeBrownie** [comment]
thank you for the examples. i wasn't 100% on the style to use since it's more important to get the style correct in the style guide. i've made a couple of tweaks to this fix in #4230
