### ISSUE TITLE
Crash on windows when calling directory-exists? or file-exists? on symlinks where target path has > 127 chars

### ISSUE THREAD

**Issue by tgbugs** [racket/racket#4233]
**What version of Racket are you using?**
8.5 [cs], also happens on 8.4 [cs].

**What program did you run?**
Run `racket` and paste the following, or you can run it from a file, but it is harder to observe the crash since it appears only as a missing print statement.
```racket
(define (test-break len)
  (define lstr (~a len #:align 'right #:pad-string "0" #:min-width 3))
  (let ([base (string->path (format "target-~a" lstr))]
        [target (string->path (string-append (format "target-~a\\" lstr) (make-string len #\a)))]
        [source (string->path (format "link-to-~a" lstr))])
    (unless (directory-exists? base)
      (make-directory base))
    (unless (directory-exists? target)
      (make-directory target))
    (unless (link-exists? source)
      (make-file-or-directory-link (path->directory-path target) source))
    (println (string-length (path->string (path->complete-path target))))
    (println (format "target dir exists: ~a" (directory-exists? target)))
    (println (format "source sym exists: ~a" (link-exists? source)))
    (println (format "source dir exists: ~a" (directory-exists? source)))))

(let* ([current-directory-length (string-length (path->string (current-directory)))]
       [offset (+ current-directory-length (string-length "target-000\\"))])
  (test-break (- 127 offset)) ; ok
  (test-break (- 128 offset)))
```

**What should have happened?**
Return #t and not crash. Sometimes #t will actually print and racket will crash shortly thereafter, not entirely sure how that happened but I did see it once.

**If you got an error message, please include it here.**
No error is printed, racket simply dies.

**Please include any other relevant details**
This only happens on Windows. Possibly relevant is the fact that the systems run with win32 long paths enabled ([docs](https://github.com/SciCrunch/sparc-curation/blob/master/docs/setup.org#long-paths)).

**Comment by mflatt** [comment]
I haven't yet been able to replicate the crash. Does it matter which directory you run in? NTFS, right?

**Comment by tgbugs** [comment]
If you know in advance that you are working with symlinks, a workaround is to use `link-exists?` which does not trigger the issue, and then call `resolve-path` in combination with `path->complete-path` or `simple-form-path`.

**Comment by tgbugs** [comment]
Confirming fixed on my end in this case and another related case as of the 20220511-ea80ad2 snapshot. Many thanks!
