### ISSUE TITLE
Case study? Broken pipe on serving this exact content over a vanilla TCP connection

### ISSUE THREAD

**Issue by zyrolasting** [racket/racket#4241]
Consider this simple TCP server for 8.4 [cs]. It endlessly serves the same HTTP response, with a body from standard input.

```
(module wiki racket/base
  (require (for-syntax racket/base) racket/port)
  (module+ main
    (require racket/tcp racket/cmdline)
    (define custodian (make-custodian))
    (define listener (tcp-listen 3000))
    (define html (port->bytes))
    (displayln "Listening on port 3000. ^C to stop.")
    (flush-output)
    (with-handlers ([exn:break? (λ (e) (custodian-shutdown-all custodian))])
      (parameterize ([current-custodian custodian])
        (let loop ()
          (define-values (i o) (tcp-accept listener))
          (thread
           (lambda ()
             (with-handlers
               ([exn:fail?
                 (λ (e) ((error-display-handler) (exn-message e) e)
                   (close-output-port o))])
               (close-input-port i)
               (write-bytes #"HTTP/1.1 200 OK\r\n" o)
               (write-bytes #"Content-Type: text/html; charset=UTF-8\r\n" o)
               (write-bytes (string->bytes/utf-8 (format "Content-Length: ~a\r\n" (bytes-length html))) o)
               (write-bytes #"Connection: close\r\n" o)
               (write-bytes #"\r\n" o)
               (write-bytes html o)
               (flush-output o)
               (close-output-port o))))
          (loop))))))
```

e.g. `racket serve.rkt < html`. Works as expected, except with, uh, just this file? [denxi.txt](https://github.com/racket/racket/files/8703988/denxi.txt). The text file is just an HTML payload. You do not need to open it in a browser, since that's not relevant here.

**What should have happened?**

Serve the payload without issue.

**If you got an error message, please include it here.**

Broken pipe, errno 32.

**Please include any other relevant details**

https://user-images.githubusercontent.com/1312121/168700887-9517895f-5c72-4c88-bff1-4240f743bed7.mp4

`curl` shows how the TCP server always encounters a broken pipe at the same points in the response. Sometimes the Racket runtime prints the broken pipe error, but it also sometimes doesn't. To make sure this was Racket and not an OS bug, I tried the same file with `nc -l 3000 <denxi.txt`. It always returns a complete payload.

When I pipe the same curl commands to `wc -c`, I always get `36763`, `69531`, and `84553` (the complete payload length).

If I'm understanding this correctly, the TCP server somehow cares about the content on the pipe. If it were an issue of length, I assume there wouldn't be broken pipes at positions far before the end of a payload that exists entirely in memory.

The issue persists after rebooting. I suspect the output port has special behavior I would not expect it to have in this context.

**Comment by zyrolasting** [comment]
Data point: I deleted the code at position `69531` to see if a change in the content changed the positions where a broken pipe occurs. It does not. If I delete the code around that position, the pipe still breaks at that exact position.

**Comment by zyrolasting** [comment]
Looks like this might be an example of hitting the maximum TCP packet size.

**Comment by zyrolasting** [comment]
Last thing before I back off. This was in the docs.

> Note that the TCP protocol does not support a state where one end is willing to send but not read, nor does it include an automatic message when one end of a connection is fully closed. Instead, the other end of a connection discovers that one end is fully closed only as a response to sending data; in particular, some number of writes on the still-open end may appear to succeed, though writes will eventually produce an error.

I responded by moving `close-input-port` after `close-output-port` appears. The error still reproduces.

**Comment by samdphillips** [comment]
The program doesn't read the request.  Could it be tripping up the TCP congestion controls?

**Comment by mflatt** [comment]
I agree that not reading the request is likely a problem. If you don't read the request, then there's a race between the client writing a request (even while the response has already been sent) and the server closing the connection. Since it's a race, changes in details like the data size can affect who wins, and sometimes in complicated ways. I'm sure that's all that's going on here, but it's likely a big part.

The "More" tutorial includes `(regexp-match #rx"(\r\n|^)\r\n" in)` to make sure it reads a request, and I vaguely remember having to get some other similarly subtle things just right when faking HTTP in that tutorial.

**Comment by zyrolasting** [comment]
Verified that reading the request with `(regexp-match #rx"(\r\n|^)\r\n" in)` solves the problem. Thank you!
