### ISSUE TITLE
[bc & linux] object-name produces "1/"

### ISSUE THREAD

**Issue by sorawee** [racket/racket#4249]
**What version of Racket are you using?**
8.5.0.2 [bc] (current snapshot) for Linux (https://www.cs.utah.edu/plt/snapshots/current/installers/racket-minimal-current-x86_64-linux-bc.sh)

**What program did you run?**
```
(object-name string->number)
```

**What should have happened?**

```
'string->number
```

Instead, it outputs:

```
'1/string->number
```

BC on Mac doesn't seem to have this problem.

**Comment by mflatt** [comment]
Can you still replicate this problem?

I think I was able to replicate it around the time of the report, but now I can't. If you still have a build that behaves this way, though, I wonder what the first line of `racket/src/build/bc/phase2/cstartup.inc` says.

**Comment by sorawee** [comment]
Yes, I can still replicate the problem in the latest snapshot (which is on https://github.com/racket/racket/commit/dd66f194c9144aed70bb5c23dabe2cda189cf05c). See https://github.com/sorawee/sorawee-test/runs/7079418294?check_suite_focus=true#step:4:5.

I noticed this problem because `htdp-test`'s GHA has a test that `(object-name string->number)` is `'string->number`. The test passes in CS, but has been failing in BC for several months now.

I am not sure how to peek at the file `racket/src/build/bc/phase2/cstartup.inc`. The problem doesn't occur on Mac and I don't have a Linux machine, so I need to rely on @Bogdanp's `setup-racket` to install Racket on a GitHub machine. I suppose snapshot installation doesn't come with `cstartup.inc`?

**Comment by mflatt** [comment]
I think the problem is an issue with the state of the snapshot's BC build directory. Removing an old file should fix the problem, but I'll update the build script to remove it, so we don't have to worry about whether there are other old build states.

**Comment by sorawee** [comment]
This is now fixed. Thanks!
