### ISSUE TITLE
[ChezScheme] buggy fraction simplification

### ISSUE THREAD

**Issue by sorawee** [racket/racket#4253]
**What version of Racket are you using?**
8.5 [cs] on Linux i386

**What program did you run?**

```
#lang racket

(for/or ([i 1000000])
  (define prgen (make-pseudo-random-generator))
  (define init-pregen-vec (pseudo-random-generator->vector prgen))
  (cond
    [(for/or ([x init-pregen-vec]) (not (integer? x)))
     (println init-pregen-vec)
     #t]
    [else #f]))
```

**What should have happened?**

Should result in `#f`. Instead, it outputs:

```
'#(1770666438 2134841233 1455898849 5177441341407232/1073741824 3900732546 1596181684)
#t
```

Note the fraction in the vector.

**Comment by gus-massa** [comment]
In case it's useful, note that
 
    2^30 = 1073741824 

and 

    5177441341407232 / 1073741824 = 4821868
    5177441341407232 - 1073741824 * 4821868 = 0

so it may be a bug in the fraction simplification code.

Can you print the fractions in a few examples and check if they are a bad representation of integers?

**Comment by sorawee** [comment]
Yep. Random testing seems to indicate that it's a problem with fraction simplification.

```
#lang racket

(for ([i (in-range 2 35)])
  (for ([j 100])
    (define a (* (expt 2 i) (random 10000000)))
    (define b (expt 2 i))
    (println (list a b (/ a b))))
  (newline))
```

outputs lines containing:

```
'(3738820570775552 536870912 233676285673472/33554432)
'(2610240604340224 536870912 5098126180352/1048576)
 '(2946832896360448 536870912 2946832896360448/536870912)
 '(989751591043072 536870912 1843556)
 '(4093556415266816 536870912 7624843)

 '(6150844139438080 1073741824 6150844139438080/1073741824)
'(9415375766683648 1073741824 2353843941670912/268435456)
'(6611131489583104 1073741824 3305565744791552/536870912)
 '(3033347496345600 1073741824 2825025)
 '(4288338013978624 1073741824 3993826)

'(2878650290536448 2147483648 1439325145268224/1073741824)
'(9758251595857920 2147483648 2439562898964480/536870912)
'(17067585853980672 2147483648 17067585853980672/2147483648)
'(1274701196296192 2147483648 593579)
```

Interestingly, by inputting some of these outputs as code and running them, we get a different result!

```
'(3738820570775552 536870912 6964096)
'(2610240604340224 536870912 4861952)
'(2946832896360448 536870912 2946832896360448/536870912)

'(6150844139438080 1073741824 6150844139438080/1073741824)
'(9415375766683648 1073741824 8768752)
'(6611131489583104 1073741824 3305565744791552/536870912)

'(2878650290536448 2147483648 1439325145268224/1073741824)
'(9758251595857920 2147483648 2439562898964480/536870912)
'(17067585853980672 2147483648 17067585853980672/2147483648)
```

Some observations based on these 100 data points for each exponent:

- It's only a problem when `b` = 2^29, 2^30, or 2^31.
- The simplification might partially succeed, and if this partial success reduces `b` to below 2^29, then writing + reading would reduce the fraction to a whole number.
- For `b` = 2^31, all successful simplifications result in odd numbers. There are no results that are even.

**Comment by sorawee** [comment]
This is also a problem on x86_64!

```
> (define a 5880287055120467478183936)
> (define b 1152921504606846976)
> (~a (/ a b))
"1369111019913216/268435456"
> (remainder a b)
0
```

**Comment by samth** [comment]
This is almost certainly because of optimizations to numeric operations by @mflatt and me. If you can come up with a Chez reproducer that would be helpful, or even run a bisection on the Chez repo.

**Comment by mflatt** [comment]
It looks like the problem is specifically in `integer-gcd`. It incorrectly uses `$bignum-trailing-zero-bits` as an exact count of zero bits, but that function provides only a lower bound.
