### ISSUE TITLE
[Feature Request] Easier interop with Keras weights

### ISSUE THREAD

**Issue by gus-massa** [racket/racket#4257]
I'll copy a request from https://news.ycombinator.com/item?id=31498039

> [...] One thing Racket is missing is great Python interop to mix in deep learning and other libraries. Common Lisp and Clojure have this support. Years ago I tried saving trained Keras weights and using them in Racket with the Matrix support: it works, but not very fun to use.

I don't use Keras, so I'm not sure what is the problem (or the solution), but it would be nice to have a package that simplifies this.

**Comment by alex-hhh** [comment]
Some internet search reveals a bit more information about this (judging by the HN user name, I suspect it the same person who made the comment):

* Blog post: https://mark-watson.blogspot.com/2019/01/using-trained-keras-weights-in-racket.html
* The actual code: https://github.com/mark-watson/racket_neural_net_from_keras

Looking at [neural.rkt](https://github.com/mark-watson/racket_neural_net_from_keras/blob/master/neural.rkt), the code, it could be improved by loading the CSV files into a `math/matrix` or `math/array`, so the matrix multiplication operations don't have to be implemented by the user...

**Comment by gus-massa** [comment]
In that post, @soegaard recomended to use `flomat` in the `sci` pakage https://docs.racket-lang.org/manual-flomat/index.html

I agree that using any of these pakages would make the program eaiser. He has to drop the last row/colum of the matrix, but it can be done with `submatrix` or something similar. 

I think it's better to close this, but it would be nice if someone can meke a blog post with the recomended/faster version.
