### ISSUE TITLE
behavior of top-level (define-values ...) is inconsistent with comment in expander source

### ISSUE THREAD

**Issue by symingz** [racket/racket#4265]
**What version of Racket are you using?**
8.5 [cs]

**What program did you run?**
The comment in the source file expander/expand/bind-top.rkt states that:

```
;; When compiling `(define-values (x) ...)` at the top level, we'd
;; like to bind `x` so that a reference in the "..." will point back
;; to the definition, as opposed to being whatever `x` was before.
```

However, when I ran the following at the top level, I got the opposite behavior:

```
> (module mx racket (provide fib) (define fib "fib"))
> (require 'mx)
> (define (fib n)                        
    (if (< n 2)  
        1      
        (+ (fib (- n 1)) (fib (- n 2)))))
> (fib 10)
application: not a procedure;
 expected a procedure that can be applied to arguments
  given: "fib"
 [,bt for context]
>
```
**What should have happened?**
`(fib 10)` should have returned `89`.

**Comment by mflatt** [comment]
Thanks for the report, and I'll fix the comment there.

My memory is fuzzy, but I think the comment reflects an iteration of the design that tried to hide top-level hopelessness just a little more, but it didn't work out.

**Comment by symingz** [comment]
Out of curiosity, [`top-level-bind-scope`](https://github.com/racket/racket/blob/be8140a045adb08c2bf527cf66b60251e78160e1/racket/src/expander/expand/bind-top.rkt#L24) appears to be introduced for the purpose of implementing the behavior in the comment (it corresponds to the [`distinct scope`](https://github.com/racket/racket/blob/be8140a045adb08c2bf527cf66b60251e78160e1/racket/src/expander/expand/bind-top.rkt#L16) in the comment).  If the behavior is no longer relevant, does it mean that `top-level-bind-scope` and its uses can be removed?

**Comment by mflatt** [comment]
Here's the new comment that I have staged:

```
;; When compiling `(define-values (x) ...)` at the top level, we need
;; `x` to have a binding to give the definition an expand-time meaning.
;; We don't want that binding to take effect outside of evaluation,
;; however; the permanent binding should happen when the
;; `define-values` for is evaluated. So, we use a distinct scope that
;; effectively hides the binding from tasks other than expansion.
;;
;; Note that the `x` binding for `(define-values (x) ...)` is not
;; meant to bind in `...`, even at expansion time. An earlier version
;; of the expander tried to do that on the grounds that it seemed
;; useful, but it didn't work out. (See "the top level is hopeless".)
;;
;; See also "def-id.rkt".
```

**Comment by symingz** [comment]
Minor suggestions: should `We don't want that binding to take effect outside of evaluation` be `We don't want that binding to take effect outside of expansion`? Also, ``when the `define-values` for is evaluated`` should be ``when the `define-values` form is evaluated``.

I'm still a bit confused about the necessity of `top-level-bind-scope`. Given that `...` is expanded without the binding of `x` in `top-level-bind-scope`, then either `x` has a real binding already and the expansion and compilation of `...` will just use that, or `x` has no binding and will be expanded to `(#%top . x)` when `...` is expanded. And `(#%top . x)` can be compiled even when `x` is unbound. So either way, `top-level-bind-scope` is not needed to finish the expansion and compilation of `(define-values (x) ...)`.

**Comment by mflatt** [comment]
The "outside of evaluation" part is as intended. That is, `eval` can create new top-level bindings, but `expand` by itself shouldn't do that. That `for` should indeed be `form`.

The goal is to make sure that the left-hand-side `x` has a binding, not one that might be in the right-hand-side `...`. It's a kind of technicality in the expander, where the left-hand side needs an identity in terms of binding, so we force one.

**Comment by symingz** [comment]
Got it, thanks for the explanation.
