### ISSUE TITLE
Match documentation and implementation for pregexp are not in agreement

### ISSUE THREAD

**Issue by endobson** [racket/racket#4281]
I'm trying to use match and realized that I needed pregexps to get the regexp features I needed.

Example:
```
> (match "12" [(regexp "\\d+") 'matched])
string:1:0
match: no matching clause for "12" [,bt for context]
> (match "12" [(pregexp "\\d+") 'matched])
'matched
```

But during my attempts to get the right code I wrote the following:

```
> (match "12" [(regexp #rx"\\d+") 'matched])
string:1:0
match: no matching clause for "12" [,bt for context]
> (match "12" [(pregexp #rx"\\d+") 'matched])
pregexp: contract violation
  expected: string?
  given: #rx"\\d+"
 [,bt for context]
```

That error message seem strange to me, since I wasn't calling pregexp directly. And so I tried to read the documentation on match.

https://docs.racket-lang.org/reference/match.html

This has examples of `regexp` working with `#rx` literals, and then documents `pregexp` as:

> like the regexp patterns, but if rx-expr produces a string, it is converted to a pattern using pregexp.

But the implementation checks if the expression produces a pregexp, and if not converts it into a pregexp

https://github.com/racket/racket/blob/448b77a6629c68659e1360fbe9f9e1ecea078f9c/racket/collects/racket/match/parse.rkt#L92-L97

My guess is the desired behavior is that  `pregexp? => #f` but `regexp? => #t` values should error out when used with the `pregexp` matcher, but probably with a better error and the documentation should be reworded to not imply that regular regexps would be accepted.

There is also interesting behavior with regards to byte-regexps and how `regexp` accepts them but `pregexp` doesn't even for `byte-pregexp? => #t` values.
```
> (match #"12" [(regexp #rx#"\\d+") 'matched])
string:1:0
match: no matching clause for #"12" [,bt for context]
> (match #"12" [(regexp #px#"\\d+") 'matched])
'matched
> (match #"12" [(pregexp #px#"\\d+") 'matched])
pregexp: contract violation
  expected: string?
  given: #px#"\\d+"
 [,bt for context]
```

**Comment by sorawee** [comment]
I missed the part about byte regexp in this bug report, which is not fixed. Sigh.
