### ISSUE TITLE
building failure due to some paths are not found

### ISSUE THREAD

**Issue by wargrey** [racket/racket#4282]
**What version of Racket are you using?**
8.5 [cs] pulled from git repository

**What program did you run?**
It doesn't want to be built

```
mkdir -p build;
cd build && ../configure --prefix=/opt/PLTracket --enable-csonly --enable-racket=auto --enable-origtree --enable-macprefix
make -C build -j$(CPUS);
```

**If you got an error message, please include it here.**

Followed the `bin/zuo . all`, after checking, it failed with

```
configure: creating ./config.status
config.status: creating Makefile
config.status: creating rktio_config.h
#f -O info'@'compiler/cm -l- setup --chain ../setup-go.rkt cs/c/compiled/rktboot ignored cs/c/ignored.d ../ChezScheme/rktboot/main.rkt --scheme-src ../ChezScheme --dest cs/c/ChezScheme --machine ta6osx
process: not a path string: #f
 in process/wait {2}
 in build-one
 in loop
 in module->hash
make[1]: *** [all] Error 1
make: *** [racket] Error 2
```

**Please include any other relevant details**
macOS 12.0.1
xcode

**Comment by mflatt** [comment]
The issue here is that `configure` is confused by `--enable-racket=auto` for a non-cross build. I'll push a change to the configure script.
