### ISSUE TITLE
Racket 8.5-Apple-Homebrew code signing?

### ISSUE THREAD

**Issue by jasonhemann** [racket/racket#4297]
I don't know if there's something you can do about it. When I installed 8.5 via `brew install --cask racket` on my MacOS 10.15.7 machine and ran `racket` at the terminal, I got the following: 

![Screen Shot 2022-06-12 at 07 56 05](https://user-images.githubusercontent.com/1329370/173232341-d35e38ef-314d-4989-aab6-5edacfda6d10.jpg)

I went into Settings & Privacy and explicitly allow it, but that wasn't obvious from the error message itself. After hitting the 'allow' button, Apple gave a second prompt that I then had to click to actually get Racket to open. I'm used to seeing this second one, but the first is new to me. Is this a complaint about code signing?

**Comment by winny-** [comment]
This isn't a solution, but might work as a temporary workaround.  I no longer have a Mac, but used this as recently as April on a locked down Mac.

```
brew install --cask --no-quarantine racket
```

**Comment by soegaard** [comment]
FWIW the script "racket.rb" which fetches Racket is here:

https://github.com/Homebrew/homebrew-cask/commits/master/Casks/racket.rb

The Racket 8.5 update consisted only of a updating the file name.
