### ISSUE TITLE
problematic advice in the documentation of syntax-local-lift-require

### ISSUE THREAD

**Issue by symingz** [racket/racket#4298]
**What version of Racket are you using?**
8.5 [cs]

**Please include any other relevant details**
The documentation of [syntax-local-lift-require](https://docs.racket-lang.org/reference/stxtrans.html#%28def._%28%28quote._~23~25kernel%29._syntax-local-lift-require%29%29) says

> If raw-require-spec and stx are part of the input to a transformer, then typically [syntax-local-introduce](https://docs.racket-lang.org/reference/stxtrans.html#%28def._%28%28quote._~23~25kernel%29._syntax-local-introduce%29%29) should be applied to each before passing them to [syntax-local-lift-require](https://docs.racket-lang.org/reference/stxtrans.html#%28def._%28%28quote._~23~25kernel%29._syntax-local-lift-require%29%29), and then [syntax-local-introduce](https://docs.racket-lang.org/reference/stxtrans.html#%28def._%28%28quote._~23~25kernel%29._syntax-local-introduce%29%29) should be applied to the result of [syntax-local-lift-require](https://docs.racket-lang.org/reference/stxtrans.html#%28def._%28%28quote._~23~25kernel%29._syntax-local-lift-require%29%29). Otherwise, marks added by the macro expander can prevent access to the new imports.

My understanding is that  `stx` is not needed for the lifting, and is only passed to `syntax-local-lift-require` to be combined with the fresh require scope to produce the syntax object to be returned. So `(syntax-local-introduce (syntax-local-lift-require (syntax-local-introduce raw-require-spec) (syntax-local-introduce stx)))` and `(syntax-local-lift-require (syntax-local-introduce raw-require-spec) stx)` are equivalent. I think the documentation of `syntax-local-lift-require` should recommend the latter instead of the former, as the later is shorter and has no wasteful operations.

**Comment by mflatt** [comment]
Thanks! I made this change as part of 8083b2d86c7b2b1c6bf59017e456bb193e6c8fbc.
