### ISSUE TITLE
inconsistency in documentation of (begin ...) and internal-definition context

### ISSUE THREAD

**Issue by symingz** [racket/racket#4299]
**What version of Racket are you using?**
8.5 [cs]

**Please include any other relevant details**
The documentation of [`begin`](https://docs.racket-lang.org/reference/begin.html#%28form._%28%28quote._~23~25kernel%29._begin%29%29) says

> in an internal-definition position (before any expression in the internal-definition sequence) ... the [begin](https://docs.racket-lang.org/reference/begin.html#%28form._%28%28quote._~23~25kernel%29._begin%29%29) form is equivalent to splicing the forms into the enclosing context

But according to the documentation of [internal-definition context](https://docs.racket-lang.org/reference/syntax-model.html#%28part._intdef-body%29), the splicing of `(begin ...)` in an internal-definition context is not conditioned on "before any expression in the internal-definition sequence".

I think the documentation of internal-definition context is the correct one, so the documentation for `begin` should be fixed.

**Comment by mflatt** [comment]
Fixed - thanks!
