### ISSUE TITLE
Zlib make failure when building from source

### ISSUE THREAD

**Issue by LiberalArtist** [racket/racket#4318]
When building from source with a very clean Git repository (`make cs-in-place PKGS="racket-lib"`), I am sometimes getting the following error:
```
config.status: creating rktio_config.h
cd racket/src/build/cs/c/ChezScheme/pb/zlib && ./configure
Checking for shared library support...
Building shared library libz.so.1.2.12 with gcc.
Checking for size_t... Yes.
Checking for off64_t... Yes.
Checking for fseeko... Yes.
Checking for strerror... Yes.
Checking for unistd.h... Yes.
Checking for stdarg.h... Yes.
Checking whether to use vs[n]printf() or s[n]printf()... using vs[n]printf().
Checking for vsnprintf() in stdio.h... Yes.
Checking for return value of vsnprintf()... Yes.
cd racket/src/build/cs/c/ChezScheme/pb/zlib && static
/bin/sh: 1: static: not found
zlib make failed
 in build-one
 in loop
 in build-base
 in in-place
 in build-one
 in loop
child Zuo process failed
 in build-racket
 in build-one
 in loop
make: *** [Makefile:5: all] Error 1
```
After doing some build steps by hand, so the repository is somewhat less clean, the build somehow starts working again—but I haven't yet figured out exactly what needs to be present for the build to work.

I would have guessed the problem would have been somewhere like this:
https://github.com/racket/racket/blob/439a12e9a6debb3baf7e7cb8c4096582bb4b2245/racket/src/ChezScheme/c/build.zuo#L303-L312
but that code seems to correctly run `make static`, rather than just `static`.

**Comment by mflatt** [comment]
Adjusting the `cs-in-place` rule to

```
cs-in-place: $(ZUO)
	echo x"$(MAKE)"x
	$(RUN_ZUO) in-place $(BUILD_VARS) VM=cs
```

might help pin down whether it's something about the initial value of `$(MAKE)` or the way it's propagated.

**Comment by LiberalArtist** [comment]
Ah, more precisely, I'm getting here via:
```racket
    (shell/wait
     (string->shell (ensure-path zuo)) "." "cs-in-place" "PKGS=\"racket-lib\""
     (hash 'dir (at-source "racket")
           'desc "child Zuo process"))
```
where `zuo` is `(hash-ref (runtime-env) 'exe)`. I'm trying to build Racket as a subproject and use Zuo to also build the parent project.

But I can try adding an `alert` in the Zuo code later. In the mean time, I've pushed my attempt to https://github.com/Aeva/tangerine/pull/3.

**Comment by mflatt** [comment]
In that case, I think I see the problem, and I've pushed a repair.

**Comment by LiberalArtist** [comment]
Yes, 3b0a99b4e1abf69857b3882d05a438a88197873e seems to have fixed it—thanks!
