### ISSUE TITLE
Problems with special comments

### ISSUE THREAD

**Issue by sorawee** [racket/racket#4345]
**What version of Racket are you using?**
1aa1cbbdad758

**What program did you run?**

Consider the following readtable:

```
#lang racket

(current-readtable
 (make-readtable #f
                 #\* 'terminating-macro (lambda args
                                          (make-special-comment #f))))
```

## Issue 1

```
;; A
(read (open-input-string "(1 2 *)"))
;; '(1 2)
```
```
;; B
(read (open-input-string "(1 . = . 2 *)"))
;; '(= 1 2)
```

```
;; C
(read (open-input-string "(1 * . 2)"))
;; '(1 . 2)
```

```
;; D
(read (open-input-string "(1 . 2 *)"))
;; read: illegal use of `.`
```

- Program A demonstrates that special comments work at the end of the list notation, and they will be discarded. 
- Program B shows that they work at the end of the infix notation
- Program C shows that they work on some positions in dotted pair.
- However, program D fails reading. Considering A, B, and C, I think it probably should not.

## Issue 2

```
;; E
(read (open-input-string "#hash(* [1 . 2])"))
;; '#hash((1 . 2))
```

```
;; F
(read (open-input-string "#hash([1 * . 2])"))
;; read: expected `.` and value for hash
```

- Program E shows that special comments work on some positions in the hash literal.
- However, program F fails reading. Considering C and E, I think it probably should not.

## Issue 3

```
;; G
(read (open-input-string "(1 . * = . 2)"))
;; '(= 1 2)
```

```
;; H
(read (open-input-string "(1 * . = . 2)"))
;; '(= 1 2)
```

```
;; I
(read (open-input-string "(1 . = * . 2)"))
;; read: illegal use of `.`
```

- Program G shows that special comments work inside double dots in the infix notation.
- Program H shows that they work before dots in the infix notation.
- Program I fails reading. Considering B, C, G, and H, I think it probably should not.

## Issue 4

```
;; J
(read (open-input-string "#hash([1 . 2 *])"))
;; read: expected `]` after value within a hash
```

- Program J fails reading. Probably should work, just like D in Issue 1.

## Issue 5

```
;; K
(read (open-input-string "#hash([1 . 2] *)"))
;; read: unexpected `)`
```

- Program K fails reading. Considering A, B, and E, I think it probably should work.

**Please include any other relevant details**

Issue 2 and 4 are potentially fixed by #4339.

**Comment by mflatt** [comment]
The general problem seems to be that various places expect `read-char/skip-whitespace-and-comments` to skip comments, but it can't skip readtable-based special comments. I'll make changes that are more like #4339, after all, but with additional fixes for other places that use `read-char/skip-whitespace-and-comments`.
