### ISSUE TITLE
dynamic-wind does not behave as documented

### ISSUE THREAD

**Issue by symingz** [racket/racket#4352]
**What version of Racket are you using?**
8.5 [cs]

**What program did you run?**

```
#lang racket

(define cx #f)

(define tag (make-continuation-prompt-tag))

(define (f)
  (dynamic-wind
   (lambda () (displayln (list 'wind
                               (continuation-mark-set->list #f 'deadbeef))))
   (lambda ()
     (call/cc (lambda (k) (set! cx k)) tag))
   (lambda () (displayln 'unwind))))

(with-continuation-mark 'deadbeef "deadbeef"
  (call-with-continuation-prompt f tag))

(call-with-continuation-prompt cx tag)
```
with output:

```
(wind (deadbeef))
unwind
(wind ())
unwind
```

**What should have happened?**

The documentation of  [`dynamic-wind`](https://docs.racket-lang.org/reference/cont.html#%28def._%28%28quote._~23~25kernel%29._dynamic-wind%29%29) says:

>When pre-thunk is called due to a continuation jump, the continuation of pre-thunk
>- jumps to a more deeply nested pre-thunk, if any, or jumps to the destination continuation; then
>- continues with the context of the pre-thunk’s [dynamic-wind](https://docs.racket-lang.org/reference/cont.html#%28def._%28%28quote._~23~25kernel%29._dynamic-wind%29%29) call.
>
>...
> the second part is relevant because ... it means that the continuation marks (see [Continuation Marks](https://docs.racket-lang.org/reference/contmarks.html)) and parameterization (see [Parameters](https://docs.racket-lang.org/reference/parameters.html)) for pre-thunk correspond to those of the [dynamic-wind](https://docs.racket-lang.org/reference/cont.html#%28def._%28%28quote._~23~25kernel%29._dynamic-wind%29%29) call that installed pre-thunk.

So, either the output of the program should be:

```
(wind (deadbeef))
unwind
(wind (deadbeef))
unwind
```

or the documentation should be updated to reflect the actual behavior of `dynamic-wind`. Based on my understanding of the source code of `dynamic-wind`, it should be something like this:

> ...
> **the application of `value-thunk` records not only `pre-thunk` and `post-thunk`, but also the continuation of the `dynamic-wind` call, up to the nearest enclosing continuation prompt**
> ...
>
>When pre-thunk is called due to a continuation jump, the continuation of pre-thunk
>- jumps to a more deeply nested pre-thunk, if any, or jumps to the destination continuation; then
>- continues with **a continuation built by extending the nearest enclosing continuation prompt with the recorded `dynamic-wind` call continuation**.
>
>...
> the second part is relevant because ... it means that the continuation marks (see [Continuation Marks](https://docs.racket-lang.org/reference/contmarks.html)) and parameterization (see [Parameters](https://docs.racket-lang.org/reference/parameters.html)) for pre-thunk correspond to those of the [dynamic-wind](https://docs.racket-lang.org/reference/cont.html#%28def._%28%28quote._~23~25kernel%29._dynamic-wind%29%29) call that installed pre-thunk, **up to the nearest enclosing continuation prompt at the time of the `dynamic-wind` call**.

**Comment by mflatt** [comment]
Thanks for pointing out the issue and for the suggestion! I've opted for a revision phrased in terms of the destination and originating continuations, which I think is more like the (now cited) formal model, instead of in terms of recording continuations.
