### ISSUE TITLE
Error cross-compiling Zuo

### ISSUE THREAD

**Issue by LiberalArtist** [racket/racket#4370]
From a build subdirectory of `racket/src/zuo`, having configured with `../configure --build=x86_64-linux-gnu --host=powerpc64le-linux-gnu` (on an appropriate build machine), running `make` fails with this output:
```
powerpc64le-linux-gnu-gcc  -g -O2 -DZUO_LIB_PATH='"'"../lib"'"' -o zuo ../zuo.c  
./zuo . zuos-to-run-and-install
./zuo: 1: Syntax error: Unterminated quoted string
make: *** [Makefile:24: zuos-to-run-and-install] Error 2
```
In a different build environment, with these `configure` flags:

```scheme
configure flags: ("CC_FOR_BUILD=gcc" "CONFIG_SHELL=/gnu/store/4y5m9lb8k3qkb1y9m02sw9w9a6hacd16-bash-minimal-5.1.8/bin/bash" "SHELL=/gnu/store/4y5m9lb8k3qkb1y9m02sw9w9a6hacd16-bash-minimal-5.1.8/bin/bash" "--prefix=/gnu/store/ldjkknahc9hl6vzc6mqxa5zga4qd4lmf-zuo-1.0-racket8.5.900-guix1" "--enable-fast-install" "--build=x86_64-unknown-linux-gnu" "--host=powerpc64le-linux-gnu" "--prefix=/gnu/store/ldjkknahc9hl6vzc6mqxa5zga4qd4lmf-zuo-1.0-racket8.5.900-guix1" "CPPFLAGS=-DGUIX_RKTIO_PATCH_BIN_SH=/gnu/store/q9pidl3hg9l0qga88gsgjs8brv82qy0v-bash-minimal-5.1.8/bin/sh")
```

`make` fails with the more informative output:
```
powerpc64le-linux-gnu-gcc -DGUIX_RKTIO_PATCH_BIN_SH=/gnu/store/q9pidl3hg9l0qga88gsgjs8brv82qy0v-bash-minimal-5.1.8/bin/sh -g -O2 -DZUO_LIB_PATH='"'"../zuo/lib"'"' -o zuo ../zuo/zuo.c  
./zuo . zuos-to-run-and-install
./zuo: ./zuo: cannot execute binary file
make: *** [Makefile:24: zuos-to-run-and-install] Error 126
```

In both cases, `./zuo` is an executable for the host rather than the build platform.

**Comment by LiberalArtist** [comment]
I didn't find this earlier because I'd been trying on a system that had QEMU's `binfmt_misc` handler installed, so it ran the cross-compiled Zuo anyway via emulation.

**Comment by mflatt** [comment]
I added `CC_FOR_BUILD` support in 798a989ba6d1a30c491a3120b2c2f1570ecab911.

**Comment by LiberalArtist** [comment]
Thanks! I think `FLAGS_FOR_BUILD` is a typo here (vs. `CFLAGS_FOR_BUILD`):
https://github.com/racket/racket/blob/e20022ccfad40d0ba2e77aa75bc4f775018c781f/racket/src/zuo/Makefile.in#L32
What would you think of also supporting `CPPFLAGS_FOR_BUILD` here? I've been using `CPPFLAGS` as part of a patch to deal with Guix's lack of `/bin/sh`. I think it would be find to put the flag in `CFLAGS_FOR_BUILD`, instead, here, but IIRC the distinction may matter elsewhere if `xform` gets involved, and it seems slightly nicer to have a `_FOR_BUILD` options for every plain option.

**Comment by mflatt** [comment]
Ok, added.

**Comment by LiberalArtist** [comment]
Thanks, that seems to have fixed it!
