### ISSUE TITLE
[Feature Request] support errortrace in raco test

### ISSUE THREAD

**Issue by sorawee** [racket/racket#4375]
`raco test` should support `--errortrace`.

See also https://github.com/shhyou/raco-test-with-errortrace. The difficulty in the integration to `raco test` is: "It's just that... raco test also uses processes and places, so I'm not sure how to pass the configuration" (from @shhyou)

**Comment by capfredf** [comment]
>  I'm not sure how to pass the configuration"

does `dynamic-require` work for that purpose?
