### ISSUE TITLE
Command key not working in Racket on Mac

### ISSUE THREAD

**Issue by Cathrineee** [racket/racket#4398]
**What version of Racket are you using?**
8.6

**What program did you run?**
Please include a short example that triggers the bug:

I opened a file in a new window and tried to open another new window using the shortcut command+n, but it didn't work. Any shortcut using the command key doesn't work (e.g. copy/paste, open a new tab). The command key works in all other applications.

**Please include any other relevant details**
MacOS 12.4, Macbook Pro with M1 Chip

**Comment by jasonhemann** [comment]
FWIW, on my 8.6 DrRacket in MacOS 2019 Intel 10.15.7 machine, `⌘+n` and all the other ⌘-based keyboard shortcuts work as expected. Did you only start to experience this behavior after upgrading to 8.6?

**Comment by shenlebantongying** [comment]
Those Preferences will change the behaviour of ⌘ and other shortcuts. I don't want to explain further.
<img width="600" alt="Screenshot 2022-08-21 at 12 53 35 AM" src="https://user-images.githubusercontent.com/20123683/185776161-42487860-865d-4a40-a187-88a7936bbf49.png">

**Comment by Cathrineee** [comment]
Got it, thanks!
