### ISSUE TITLE
add a `usability` label to racket/racket issues 

### ISSUE THREAD

**Issue by spdegabrielle** [racket/racket#4405]
**Is your feature request related to a problem? Please describe.**
I wanted to label racket/drracket#584 as a usability issue

**Describe the solution you'd like**
add label in GitHub repo issue configuration

**Describe alternatives you've considered**

**Do you want to contribute to this feature**
yes

**[Optional] Additional context**
<img width="787" alt="image" src="https://user-images.githubusercontent.com/108047/186167312-4035cf8b-3bdd-4985-bb13-6a3bdb211261.png">

**Comment by sorawee** [comment]
Done.
