### ISSUE TITLE
expression (- 23 19.98) cannot be calculated correctly in DrRacket

### ISSUE THREAD

**Issue by Kyle-Jehring** [racket/racket#4406]
**What version of Racket are you using?**
version 8.6

**What program did you run?**
Please include a short example that triggers the bug
<img width="497" alt="截屏2022-08-23 21 38 10" src="https://user-images.githubusercontent.com/39212395/186172721-a8ac54ec-a2b8-492f-bd72-1f2bae81e210.png">

<img width="489" alt="截屏2022-08-23 21 40 57" src="https://user-images.githubusercontent.com/39212395/186173423-f80890bb-fcaf-41db-875b-ba55df9fd38d.png">
I was really confusing why would this happen. Is there anyone who could explain this?

**Comment by samth** [comment]
This is an example of how "floating point numbers" (which is the default representation used when you write numbers with a decimal point like 19.98) can be confusing. Here's an article on it: https://docs.python.org/3/tutorial/floatingpoint.html

If you want an exact number, you can write `#e19.98`.

**Comment by olopierpa** [comment]
Il giorno 23 agosto 2022, alle ore 15:48, Sam Tobin-Hochstadt ***@***.***> ha scritto:

>This is an example of how "floating point numbers" ... can be confusing. 

*Binary* floating point numbers. It's only the *binary* part which creates this particular confusion.

I wish more programming languages offered the choice between binary and decimal floats.

Pedagogical PLs could use decimal as default then.

**Comment by samth** [comment]
Many pedagogical languages that build on Racket use exact rationals (eg, the HtDP languages), which would solve the problem.

**Comment by sorawee** [comment]
It looks like @Kyle-Jehring is using `#lang sicp`, which I would consider a pedagogical language. But the main goal of `#lang sicp` is to provide compatibility with existing Scheme (MIT Scheme I think?). The implementation follows the specification that decimals with a decimal point will be read as inexact. To quote R5RS:

>  If the written representation of a number has no exactness prefix, the constant may be either inexact or exact. It is inexact if it contains a decimal point, an exponent, or a "#" character in the place of a digit, otherwise it is exact. 

https://groups.csail.mit.edu/mac/ftpdir/scheme-reports/r5rs-html/r5rs_8.html#SEC50

**Comment by Kyle-Jehring** [comment]
Look at this screenshot:
<img width="275" alt="截屏2022-08-24 10 54 11" src="https://user-images.githubusercontent.com/39212395/186310067-2026f3ab-e25b-45cf-9dee-8d47ef7bbf0c.png">
I tried some other expressions similar to the original one.
Some of them can calculate right, some wrong.
Why did this happen? If 0.98 cannot be preciously converted to binary form, why does it sometimes work?

**Comment by shhyou** [comment]
The values are actually not exact, but the printer happens to have rounded them when printing the output. The function `inexact->exact` shows that the actual values are just approximations:

```
Welcome to Racket v8.6.0.5 [cs].
> (exact? (- 2 0.98))
#f
> (inexact->exact (- 2 0.98))
2296835809958953/2251799813685248
> (- 2 #e0.98)
51/50
> 
```

In comparison, the exact arithmetic `(- 2 #e0.98)` produces the precise number, `51/50`.

**Comment by soegaard** [comment]
@Kyle-Jehring 

Floating points are stored in 64 bits. 
That means there is only 2^64 different numbers that can be stored exactly using floating point.
It also means there is infinitely many numbers that can't be stored exactly as floating point.
Even if two numbers are stored exactly, there is no guarantee that the difference of two such numbers can be stored exactly.

If you are interested in how floating point work and why seemingly simple computations 
give inexact results, then check out "What Every Computer Scientist Should Know About Floating-Point Arithmetic" by David Goldberg. By now that article has become a classic.

https://www.itu.dk/~sestoft/bachelor/IEEE754_article.pdf

**Comment by mfelleisen** [comment]
30 years ago this was still research: 
 
How to read floating point numbers accurately
https://dl.acm.org/doi/10.1145/93542.93557 

How to print floating-point numbers accurately. 
https://lists.nongnu.org/archive/html/gcl-devel/2012-10/pdfkieTlklRzN.pdf

It is unsurprising that this is a topic that causes problems for beginners. 
Go to the Language menu in drracket, switch to Beginning Student Language, 
run the expressions there.

**Comment by mfelleisen** [comment]
> On Aug 23, 2022, at 10:03 AM, olopierpa ***@***.***> wrote:
> 
> Pedagogical PLs could use decimal as default then.


And indeed, __our__ teaching languages do. (I am not sure why you use the SICP language.)
