### ISSUE TITLE
sqlite with racket 8.6

### ISSUE THREAD

**Issue by jeff29t** [racket/racket#4419]
Hello,

The following code work on 8.5 version 👍 
#lang racket
(require db)
(define dbfile "test.sqlite3")
(define dbcon 
  (if (file-exists? dbfile)
      (sqlite3-connect #:database dbfile #:mode 'read/write)
      (sqlite3-connect #:database dbfile #:mode 'create)
      ))

(query dbcon "select * from sqlite_schema e ")
But on 8.6 version it answer:
query: no such table: sqlite_schema
  error code: 1

**Comment by Jean-FrancoisTrevien** [comment]
In Sqlite database, this table must exist because in contain the schema of the database.
In version 8.6 the resulting size of the file was zero!

**Comment by Bogdanp** [comment]
On x86 and x86_64 Windows 10 and up, you could also try installing my `libsqlite3` package (`raco pkg install libsqlite3`), which distributes version 3.92.2.

**Comment by jeff29t** [comment]
thanks for your answer mflatt. 
What  is the avantage to use libsqlite3?

**Comment by mflatt** [comment]
> What is the avantage to use libsqlite3?

Installing the `libsqlite3` package has a similar effect as replacing `sqlite3.dll` in the Racket installation, but installing `libsqlite3` would normally put the new `sqlite3.dll` in a user-specific place instead of overwriting the one in the main Racket installation. Also, the library provided by `libsqlite3` is an even newer version.

**Comment by Bogdanp** [comment]
In this case it would be that you don't have to manually move the files
around.  In general, it would be that I keep the package more up to date
with upstream SQLite.  One disadvantage is that it gets built in GitHub
Actions, which only supports recent versions of Windows, so
compatibility with older operating systems likely isn't as good.
