### ISSUE TITLE
invalid memory reference, may be TR / Shallow TR bug

### ISSUE THREAD

**Issue by bennn** [racket/racket#4421]
cc @samth 

**What version of Racket are you using?**
8.6.0.9 Snapshot: 20220829-422e3a6

**What program did you run?**

A condensed version of a test that fails on DrDr: http://drdr.racket-lang.org/61493/cs/racket/share/pkgs/typed-racket-test/succeed/shallow/accessors.rkt

This program should raise a contract error because `list0` contains `String` values, not `Symbol` values.

```
#lang typed/racket/shallow #:no-optimize

(module untyped racket
  (define list0 (list "A" "B" "C"))
  (define vector0 (vector "A" "B"))
  (define box0 (box "A"))
  (provide list0 vector0 box0))

(require typed/racket/random)
(require/typed 'untyped
  (list0 (Listof Symbol))
  (vector0 (Vectorof Symbol)) ;; unused but important
  (box0 (Boxof Symbol))) ;; unused but important

(random-ref list0) ;; expect shape-check error
```

**What should have happened?**

This program should error:

```
shape-check: value does not match expected type
  value: "C"
  type: Symbol
  ....
```

On BC, it gives the right error.

On CS, it gives an `invalid memory reference`

**Please include any other relevant details**

- Removing either of the unused imports from the `require/typed` form makes the error go away on CS.
- Note that `typed/racket/random` unsafely requires and provides `random-ref`
- I have no idea if this is a Racket bug, a Typed Racket bug, or a Shallow Typed Racket bug. Will try to reduce further!
- Inlining the `unsafe-require/typed ... random-ref` makes the error go away on CS. See below.

<details><summary><b>OK on CS: Inlining  `unsafe-require/typed ... random-ref`</b></summary>

```
#lang typed/racket/shallow #:no-optimize

(module untyped racket
  (define list0 (list "A" "B" "C"))
  (define vector0 (vector "A" "B"))
  (define box0 (box "A"))
  (provide list0 vector0 box0))

(require (only-in typed/racket/unsafe unsafe-require/typed))
(unsafe-require/typed racket/random
  (random-ref (All (X) (->* ( (Sequenceof X) ) (Pseudo-Random-Generator) X))))

(require/typed 'untyped
  (list0 (Listof Symbol))
  (vector0 (Vectorof Symbol))
  (box0 (Boxof Symbol)))

(random-ref list0)
```
</details>

<details><summary><b>Smaller program by samth</b></summary>
(Unclear if helpful.) This one gives `invalid mem ref` or CS and no error on BC, and doesn't use `typed/racket/random`

```
#lang typed/racket/shallow #:no-optimize

(module untyped racket/base
  (define list0 (list "A" "B" "C"))
  (define box0 'A)
  (provide list0 box0))

(module m typed/racket/shallow #:no-optimize
  (require (only-in typed/racket/unsafe unsafe-require/typed))
  (unsafe-require/typed racket/random (random-ref (-> (Sequenceof Number) Any)))
  (provide random-ref))

(require 'm)

(require/typed 'untyped
  (list0 (Listof Number))
  (box0 Symbol))

(random-ref list0)
```
</details>

**Comment by bennn** [comment]
Here's a version with simpler types that doesn't depend on `racket/random`. The `contract-out` is important.

- CS = invalid memory reference
- BC = no error, prints `"A"`

Maybe a problem with many layers of rename transformers in CS?
(I've been looking on the TR side with no luck.)

```
#lang typed/racket/shallow #:no-optimize

(module untyped racket/base
  (define list0 (list "A" "B" "C"))
  (define box0 "A")
  (provide list0 box0))

(module random racket/base
  (require racket/contract/base)
  (define random-ref car)
  (provide
    (contract-out [random-ref (-> any/c any/c)])))

(module m typed/racket/shallow #:no-optimize
  (require (only-in typed/racket/unsafe unsafe-require/typed))
  (unsafe-require/typed (submod ".." random) (random-ref (-> Any Any)))
  (provide random-ref))

(require 'm)

(require/typed 'untyped
  (list0 (Listof Number))
  (box0 String))

(random-ref list0)
```

**Comment by mflatt** [comment]
This appears to be a bug in the compiler where it becomes convinced that the imported `random-ref` will be a Chez Scheme procedure and compiles `(random-ref list0)` that way, but `random-ref` is actually a chaperone. I haven't yet figured out where cross-module known-value information goes wrong.
