### ISSUE TITLE
Using -r/--script with 8.x CS implementation gives a fatal error rather than running the file

### ISSUE THREAD

**Issue by jdjohnston** [racket/racket#4424]
**What version of Racket are you using?**
8.2, 8.5, & 8.6 [cs]
(NB. 8.6 [bc] doesn't have this problem)

**What program did you run?**
Please include a short example that triggers the bug
File: hello.rktl
(println "Hello, World!")

Command line:
`racket -r hello.rktl`

`racket -f hello.rktl -N hello.rktl --`, which is supposed to be the equivalent, works fine

**What should have happened?**
Should have printed `"Hello, World!"`

**If you got an error message, please include it here.**
hello.rktl:1:0: #%top-interaction: unbound identifier;
 also, no #%app syntax transformer is bound
  at: #%top-interaction
  in: (#%top-interaction println "Hello, World!")
  location...:
   hello.rktl:1:0

**Please include any other relevant details**
e.g., the operating system used or how you are running the code.
Windows 7 & Linux (Xubuntu 22.04.1 and EndeavourOS)

**Comment by mflatt** [comment]
Thanks for the report!
