### ISSUE TITLE
`regexp-match` returned an unexpected result.

### ISSUE THREAD

**Issue by Antigen-1** [racket/racket#4441]
**What version of Racket are you using?**
Racket v8.6 [cs].

**What program did you run?**
`(regexp-match #px"^([A-Z][a-z])+$" "AbCd")`

**What should have happened?**
`'("AbCd" "Ab" "Cd")` should have been returned.

**If you got an error message, please include it here.**
None.

**Please include any other relevant details**
I got `'("AbCd" "Cd")` instead.

**Comment by jbclements** [comment]
What you're observing appears to be the documented behavior. From the manual:

"When a single sub-expression occurs within a * “zero or more” pattern or other multiple-match positions, then the rightmost match associated with the sub-expression is returned in the list."

I'm going to close this, but feel free to re-open it if I've misunderstood your report!

**Comment by sorawee** [comment]
FWIW, some other regex engines appear to have the same behavior.

CPython 3.9.12

```
>>> import re
>>> re.search("^([A-Z][a-z])+$", "AbCd").group(1)
'Cd'
```
