### ISSUE TITLE
Problem using custodian-limit-memory

### ISSUE THREAD

**Issue by Cazra** [racket/racket#4444]
I'm trying to use custodians in Racket to set a limit to memory usage within a given scope and raise an out-of-memory error if it exceeds that limit.

Following examples for how to use custodians, I put together this simple program:

```
#lang racket/base

(with-handlers
  ([exn:fail:out-of-memory? (λ (err)
    (println "Caught out-of-memory error! :D"))])
  
  (parameterize ([current-custodian (make-custodian)])
    (custodian-limit-memory (current-custodian) (* 2 1024 1024))
    (make-bytes (* 4 1024 1024)))
  (println "Should have raised OoM. :("))
```

I expect to see the output "Caught out-of-memory error! :D", but instead I am seeing "Should have raised OoM. :(".

Any idea why my code isn't raising the out-of-memory error when I call make-bytes here?

I'm using Racket v8.4 [cs].

**Comment by mflatt** [comment]
When you call `make-bytes`, the result is not owned by the current custodian. It's owned by the custodian of the thread that is running, and that custodian is determined when you create the thread. 

Here's a variant of your example to illustrate:

```
#lang racket/base

(with-handlers
  ([exn:fail:out-of-memory? (λ (err)
    (println "Caught out-of-memory error! :D"))])
  
  (parameterize ([current-custodian (make-custodian)])
    (thread-wait
     (thread
      (lambda ()
        (custodian-limit-memory (current-custodian) (* 2 1024 1024))
        (make-bytes (* 4 1024 1024))
        (println "Should have raised OoM. :("))))))
```
