### ISSUE TITLE
Help Desk

### ISSUE THREAD

**Issue by Buzzard96** [racket/racket#4454]
**What version of Racket are you using?**
 version 8.6
 Once I control click and try to open the help desk it sends me to a link that does not open. At first Racket completely froze and then it took me to this page. Every time after that it takes me to a page that says click here and then it does nothing.

**Comment by gus-massa** [comment]
Do you have an screenshot?

**Comment by LiberalArtist** [comment]
What operating system are you using? What is your default web browser?
