### ISSUE TITLE
Release Regressions for Racket v8.7

### ISSUE THREAD

**Issue by jbclements** [racket/racket#4464]
Here are the current results for checking release regressions:

- [x] russian-lang : https://plt.cs.northwestern.edu/release-pkg-build/server/built/deps/russian-lang.txt (easy dep fix?)
- [x] video-v0-0 : sigh... all I remember here is that this one always fails and it's okay for some reason that I don't currently recall.

And here's one that didn't get fixed last time:

- [x] unlike-assets-test https://plt.cs.northwestern.edu/pkg-build/server/built/test-fail/unlike-assets-test.txt (but wait... maybe it's been deleted?)

**Comment by mfelleisen** [comment]
If Video 0-0 is Leif's, it's essentially a package that should be removed (if I recall this properly).

**Comment by samth** [comment]
I think neither video-v0-0 nor unlike-assets-test reflect a problem with the release. It would be good if the authors fixed the issues but it doesn't block anything. 

The failure for russian-lang is odd since the dependencies should be the same in both builds.

**Comment by samth** [comment]
It looks like russian-lang changed recently (between when the two pkg builds ran) so probably that is also not a regression.

**Comment by samth** [comment]
The only current issue is with `video-v0-0`. I don't think this reflects an actual problem so I'm checking it off. cc @LeifAndersen
