### ISSUE TITLE
Racket regexp `[:word:]` class lacks decimal digits

### ISSUE THREAD

**Issue by hcs64** [racket/racket#4465]
**What version of Racket are you using?**
8.6 [cs]

**What program did you run?**
```
(println
    (regexp-match? #px"[[:word:]]" "7"))
```

**What should have happened?**

`#t`

**If you got an error message, please include it here.**

`#f`

**Please include any other relevant details**

`#t` is output on 8.6 [bc] ([3m]?), I guess it's using the old C implementation of regexp, which [implemented](https://github.com/racket/racket/blob/cc06a5e2523ae3049b69d15cd2548eed5a887100/racket/src/racket/src/regexp.c#L1655-L1661) `[:word:]` with `\w`. The [Racket implementation](https://github.com/racket/racket/blob/0e7d68ef81a146bf66ec346fcca97aab652ce0c6/racket/src/regexp/parse/class.rkt#L94-L100) is missing `(range-add-span ... (chyte #\0) (chyte #\9)))`.

**Comment by mflatt** [comment]
Thanks for the report and the repair!
