### ISSUE TITLE
(procedure-rename apply 'name) yields an error

### ISSUE THREAD

**Issue by joskoot** [racket/racket#4471]
**What version of Racket are you using?**
Welcome to DrRacket, version 8.6 [cs].

**What program did you run?**
#lang racket/base
(procedure-rename apply 'aap)

**What should have happened?**
Should yield: ````#<procedure:aap>````

**If you got an error message, please include it here.**
procedure-reduce-arity-mask: arity mask of procedure does not include requested arity mask
  procedure: #<procedure:...rivate/pre-base.rkt:28:5>
  requested arity mask: -8

**Please include any other relevant details**
e.g., the operating system used or how you are running the code.
DrRacket cs, windows
No error with Racket BC.

**Comment by mflatt** [comment]
Thanks for the report!
