### ISSUE TITLE
Repl (expeditor) couldn't accept a line over width on Windows

### ISSUE THREAD

**Issue by Hamayama** [racket/racket#4479]
**What version of Racket are you using?**
8.6 [cs]

**What program did you run?**
Repl (expeditor) couldn't accept a line over width on Windows.

**What should have happened?**
Repl (expeditor) should be able to accept a line over width on Windows.

**If you got an error message, please include it here.**
```
car: contract violation
  expected: pair?
  given: '()
append: contract violation
  expected: list?
  given: #<void>
 [,bt for context]
```

**Please include any other relevant details**
OS: Windows 10 21H2

Workaround is to input `,input readline` and restart Racket (first comma is important).
(Default seems to be `,input expeditor` .)

**Comment by Hamayama** [comment]
Image capture of this issue:
![editor_NG](https://user-images.githubusercontent.com/4497079/198908381-8ccedeba-74bb-4fe0-b61b-526eb4e9ba36.gif)

**Comment by Hamayama** [comment]
Racket 8.7 [cs] has the same problem.

OS: Windows 10 21H2

I can also reproduce it in Windows Terminal.

![editor_NG2](https://user-images.githubusercontent.com/4497079/204243595-1fd0fb37-aad9-48f0-a1d7-673c41b3fd30.gif)

**Comment by mflatt** [comment]
Thanks for the report!

**Comment by mflatt** [comment]
Repair completed by racket/expeditor@9b2d54a97a4f17a75d3198630a978b3eb2b4d1af.
