### ISSUE TITLE
drracket crashes on MacOS Ventura.

### ISSUE THREAD

**Issue by eddierucker** [racket/racket#4482]
**What version of Racket are you using?**
e.g., 7.7 [cs]

8.7.0.5 from git

**What program did you run?**
Please include a short example that triggers the bug

No program. Crashes opening DrRacket.

**What should have happened?**

drracket should have opened to allow entry of a program.

**If you got an error message, please include it here.**

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               DrRacket [11818]
Path:                  /Users/USER/*/DrRacket.app/Contents/MacOS/DrRacket
Identifier:            org.racket-lang.DrRacket
Version:               8.7.0.5 (8.7.0.5)
Code Type:             ARM-64 (Native)
Parent Process:        zsh [11612]
Responsible:           Terminal [11610]
User ID:               501

Date/Time:             2022-11-01 13:12:08.8575 -0500
OS Version:            macOS 13.0 (22A380)
Report Version:        12
Anonymous UUID:        9484355C-F57C-8595-F437-07B890B5241F

Sleep/Wake UUID:       D924446B-CC95-4265-8CB7-E7819969CAF1

Time Awake Since Boot: 32000 seconds
Time Since Wake:       5359 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
abort() called

Application Specific Backtrace 0:
0   CoreFoundation                      0x00000001859cc418 __exceptionPreprocess + 176
1   libobjc.A.dylib                     0x0000000185516ea8 objc_exception_throw + 60
2   Foundation                          0x000000018690ca60 -[NSCalendarDate initWithCoder:] + 0
3   AppKit                              0x000000018915bf98 -[_NSTrackingAreaAKViewHelper removeTrackingRect:] + 200
4   ???                                 0x000000011c5770c0 0x0 + 4770459840
5   Racket                              0x00000001003b96b8 Scall2 + 120
6   Racket                              0x00000001003287bc racket_boot + 1528
7   DrRacket                            0x0000000100173408 DrRacket + 13320
8   dyld                                0x0000000185547e50 start + 2544

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x18583b224 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x185871cec pthread_kill + 288
2   libsystem_c.dylib             	       0x1857ab2c8 abort + 180
3   libc++abi.dylib               	       0x18582bb18 abort_message + 132
4   libc++abi.dylib               	       0x18581ba0c demangling_terminate_handler() + 336
5   libobjc.A.dylib               	       0x18551f764 _objc_terminate() + 144
6   libc++abi.dylib               	       0x18582aeb4 std::__terminate(void (*)()) + 20
7   libc++abi.dylib               	       0x18582dc2c __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) + 36
8   libc++abi.dylib               	       0x18582dbd8 __cxa_throw + 140
9   libobjc.A.dylib               	       0x185517008 objc_exception_throw + 412
10  Foundation                    	       0x18690ca60 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 188
11  AppKit                        	       0x18915bf98 -[_NSTrackingAreaAKViewHelper removeTrackingRect:] + 200
12  ???                           	       0x11c5770c0 ???
13  Racket                        	       0x1003b96b8 S_call + 20 (schlib.c:204) [inlined]
14  Racket                        	       0x1003b96b8 Scall2 + 120 (schlib.c:158)
15  Racket                        	       0x1003287bc racket_boot + 1528 (boot.c:216)
16  DrRacket                      	       0x100173408 0x100170000 + 13320
17  dyld                          	       0x185547e50 start + 2544

Thread 1:
0   libsystem_pthread.dylib       	       0x18586ce18 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x18586ce18 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x18586ce18 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x18586ce18 start_wqthread + 0

Thread 5:: com.apple.CFSocket.private
0   libsystem_kernel.dylib        	       0x18583da74 __select + 8
1   CoreFoundation                	       0x18597b360 __CFSocketManager + 636
2   libsystem_pthread.dylib       	       0x18587206c _pthread_start + 148
3   libsystem_pthread.dylib       	       0x18586ce2c thread_start + 8

Thread 6:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x185832df0 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1858448d8 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x18583b638 mach_msg_overwrite + 540
3   libsystem_kernel.dylib        	       0x18583316c mach_msg + 24
4   CoreFoundation                	       0x185951bdc __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1859504c8 __CFRunLoopRun + 1232
6   CoreFoundation                	       0x18594f8a4 CFRunLoopRunSpecific + 612
7   AppKit                        	       0x188cd2248 _NSEventThread + 172
8   libsystem_pthread.dylib       	       0x18587206c _pthread_start + 148
9   libsystem_pthread.dylib       	       0x18586ce2c thread_start + 8

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x000000018582f0f5   x5: 0x000000016fc8d8e0   x6: 0x000000000000006e   x7: 0x0000000000000001
    x8: 0xdeb885189b5cb5d8   x9: 0xdeb885197bafd0d8  x10: 0x0000000000000200  x11: 0x000000000000000b
   x12: 0x000000000000000b  x13: 0x00000000001ff800  x14: 0x00000000000007fb  x15: 0x000000009ac24830
   x16: 0x0000000000000148  x17: 0x00000001e5d849c8  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x00000001e0f36500  x21: 0x0000000000000103  x22: 0x00000001e0f365e0  x23: 0x0000600000721c20
   x24: 0x00000001029fd228  x25: 0x00000001071f7f00  x26: 0x000000011c708e8d  x27: 0x00000001003fa619
   x28: 0x00000001003fa614   fp: 0x000000016fc8d850   lr: 0x0000000185871cec
    sp: 0x000000016fc8d830   pc: 0x000000018583b224 cpsr: 0x40001000
   far: 0x0000000100534940  esr: 0x56000080  Address size fault

Binary Images:
       0x185832000 -        0x18586affb libsystem_kernel.dylib (*) <6d6644d3-3db3-34c4-b1e3-c675ec5360f0> /usr/lib/system/libsystem_kernel.dylib
       0x18586b000 -        0x185877ffb libsystem_pthread.dylib (*) <886caca0-5762-3640-8db2-3fa3b911c062> /usr/lib/system/libsystem_pthread.dylib
       0x185732000 -        0x1857b2ff3 libsystem_c.dylib (*) <a3869999-0792-3e09-b3fb-5e87ae4639be> /usr/lib/system/libsystem_c.dylib
       0x18581a000 -        0x185831ffb libc++abi.dylib (*) <bec775ba-9513-3b66-8f2f-be8d2a817269> /usr/lib/libc++abi.dylib
       0x1854fc000 -        0x185541d9f libobjc.A.dylib (*) <e20fe24e-bbda-3944-9cfc-8e43a463400b> /usr/lib/libobjc.A.dylib
       0x1867fb000 -        0x187233fff com.apple.Foundation (6.9) <52b2f83f-586d-32a2-8b66-ce651400ac8c> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
       0x188b6f000 -        0x189a76fff com.apple.AppKit (6.9) <af9f6891-70ad-3c26-af08-b747344892d2> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x100324000 -        0x100403fff Racket (*) <708ee92c-8e3b-351b-b29a-0a75ee2058d4> /Users/USER/*/Racket.framework/Versions/8.7.0.5_CS/Racket
       0x100170000 -        0x100173fff org.racket-lang.DrRacket (8.7.0.5) <6f1a9bb9-2ece-34a0-9341-d638622c94d5> /Users/USER/*/DrRacket.app/Contents/MacOS/DrRacket
       0x185542000 -        0x1855cc4af dyld (*) <1f56ab4e-f398-3a9c-bfba-fbbd17808963> /usr/lib/dyld
       0x1858d0000 -        0x185da7fff com.apple.CoreFoundation (6.9) <f4ff83fc-e62c-30b4-b3a9-876c8a1fd595> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=986.1M resident=0K(0%) swapped_out_or_unallocated=986.1M(100%)
Writable regions: Total=1.3G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.3G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               128K        1 
Activity Tracing                   256K        1 
CG image                            48K        3 
ColorSync                          560K       25 
CoreAnimation                       96K        6 
CoreGraphics                        32K        2 
CoreUI image data                  736K        5 
Foundation                          16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                           235.3M       39 
MALLOC guard page                  192K       10 
MALLOC_MEDIUM (reserved)         480.0M        4         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.1M        7 
Stack                             11.2M        7 
VM_ALLOCATE                      173.2M      122 
__AUTH                             645K      163 
__AUTH_CONST                      11.2M      311 
__CTF                               756        1 
__DATA                            4059K      319 
__DATA_CONST                      14.8M      334 
__DATA_DIRTY                       708K      108 
__FONT_DATA                        2352        1 
__LINKEDIT                       764.2M       24 
__OBJC_CONST                      1332K      136 
__OBJC_RO                         65.1M        1 
__OBJC_RW                         1981K        1 
__TEXT                           222.0M      348 
dyld private memory                256K        1 
mapped file                      346.1M       20 
shared memory                      864K       15 
===========                     =======  ======= 
TOTAL                              2.7G     2018 
TOTAL, minus reserved VM space     1.9G     2018 

-----------
Full Report
-----------

{"app_name":"DrRacket","timestamp":"2022-11-01 13:12:09.00 -0500","app_version":"8.7.0.5","slice_uuid":"6f1a9bb9-2ece-34a0-9341-d638622c94d5","build_version":"8.7.0.5","platform":1,"bundleID":"org.racket-lang.DrRacket","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.0 (22A380)","roots_installed":0,"name":"DrRacket","incident_id":"FBC4DEB2-CCA8-473F-B018-F1E0B708A282"}
{
  "uptime" : 32000,
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,1",
  "coalitionID" : 890,
  "osVersion" : {
    "train" : "macOS 13.0",
    "build" : "22A380",
    "releaseType" : "User"
  },
  "captureTime" : "2022-11-01 13:12:08.8575 -0500",
  "incident" : "FBC4DEB2-CCA8-473F-B018-F1E0B708A282",
  "pid" : 11818,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2022-11-01 13:12:08.0940 -0500",
  "procStartAbsTime" : 772998049350,
  "procExitAbsTime" : 773016301325,
  "procName" : "DrRacket",
  "procPath" : "\/Users\/USER\/*\/DrRacket.app\/Contents\/MacOS\/DrRacket",
  "bundleInfo" : {"CFBundleShortVersionString":"8.7.0.5","CFBundleVersion":"8.7.0.5","CFBundleIdentifier":"org.racket-lang.DrRacket"},
  "storeInfo" : {"deviceIdentifierForVendor":"7E36A736-CBA0-5762-B279-CF6C5234A140","thirdParty":true},
  "parentProc" : "zsh",
  "parentPid" : 11612,
  "coalitionName" : "com.apple.Terminal",
  "crashReporterKey" : "9484355C-F57C-8595-F437-07B890B5241F",
  "responsiblePid" : 11610,
  "responsibleProc" : "Terminal",
  "wakeTime" : 5359,
  "sleepWakeUUID" : "D924446B-CC95-4265-8CB7-E7819969CAF1",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "asi" : {"libsystem_c.dylib":["abort() called"]},
  "asiBacktraces" : ["0   CoreFoundation                      0x00000001859cc418 __exceptionPreprocess + 176\n1   libobjc.A.dylib                     0x0000000185516ea8 objc_exception_throw + 60\n2   Foundation                          0x000000018690ca60 -[NSCalendarDate initWithCoder:] + 0\n3   AppKit                              0x000000018915bf98 -[_NSTrackingAreaAKViewHelper removeTrackingRect:] + 200\n4   ???                                 0x000000011c5770c0 0x0 + 4770459840\n5   Racket                              0x00000001003b96b8 Scall2 + 120\n6   Racket                              0x00000001003287bc racket_boot + 1528\n7   DrRacket                            0x0000000100173408 DrRacket + 13320\n8   dyld                                0x0000000185547e50 start + 2544"],
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "lastExceptionBacktrace" : [{"imageOffset":1033228,"symbol":"__exceptionPreprocess","symbolLocation":164,"imageIndex":11},{"imageOffset":110248,"symbol":"objc_exception_throw","symbolLocation":60,"imageIndex":4},{"imageOffset":1120864,"symbol":"-[NSCalendarDate initWithCoder:]","symbolLocation":0,"imageIndex":5},{"imageOffset":6213528,"symbol":"-[_NSTrackingAreaAKViewHelper removeTrackingRect:]","symbolLocation":200,"imageIndex":6},{"imageOffset":4770459840,"imageIndex":7},{"symbol":"S_call","inline":true,"imageIndex":8,"imageOffset":612024,"symbolLocation":20,"sourceLine":205,"sourceFile":"schlib.c"},{"imageOffset":612024,"sourceLine":158,"sourceFile":"schlib.c","symbol":"Scall2","imageIndex":8,"symbolLocation":120},{"imageOffset":18364,"sourceFile":"boot.c","symbol":"racket_boot","symbolLocation":1528,"imageIndex":8},{"imageOffset":13320,"imageIndex":9},{"imageOffset":24144,"symbol":"start","symbolLocation":2544,"imageIndex":10}],
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":309828,"threadState":{"x":[{"value":0},{"value":0},{"value":0},{"value":0},{"value":6534918389},{"value":6170400992},{"value":110},{"value":1},{"value":16048723612867016152},{"value":16048723616630558936},{"value":512},{"value":11},{"value":11},{"value":2095104},{"value":2043},{"value":2596423728},{"value":328},{"value":8151124424},{"value":0},{"value":6},{"value":8069014784,"symbolLocation":0,"symbol":"_main_thread"},{"value":259},{"value":8069015008,"symbolLocation":224,"symbol":"_main_thread"},{"value":105553123744800},{"value":4338995752},{"value":4414471936},{"value":4772105869},{"value":4299138585},{"value":4299138580}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6535191788},"cpsr":{"value":1073745920},"fp":{"value":6170400848},"sp":{"value":6170400816},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6534967844,"matchesCrashFrame":1},"far":{"value":4300425536}},"queue":"com.apple.main-thread","frames":[{"imageOffset":37412,"symbol":"__pthread_kill","symbolLocation":8,"imageIndex":0},{"imageOffset":27884,"symbol":"pthread_kill","symbolLocation":288,"imageIndex":1},{"imageOffset":496328,"symbol":"abort","symbolLocation":180,"imageIndex":2},{"imageOffset":72472,"symbol":"abort_message","symbolLocation":132,"imageIndex":3},{"imageOffset":6668,"symbol":"demangling_terminate_handler()","symbolLocation":336,"imageIndex":3},{"imageOffset":145252,"symbol":"_objc_terminate()","symbolLocation":144,"imageIndex":4},{"imageOffset":69300,"symbol":"std::__terminate(void (*)())","symbolLocation":20,"imageIndex":3},{"imageOffset":80940,"symbol":"__cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*)","symbolLocation":36,"imageIndex":3},{"imageOffset":80856,"symbol":"__cxa_throw","symbolLocation":140,"imageIndex":3},{"imageOffset":110600,"symbol":"objc_exception_throw","symbolLocation":412,"imageIndex":4},{"imageOffset":1120864,"symbol":"-[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]","symbolLocation":188,"imageIndex":5},{"imageOffset":6213528,"symbol":"-[_NSTrackingAreaAKViewHelper removeTrackingRect:]","symbolLocation":200,"imageIndex":6},{"imageOffset":4770459840,"imageIndex":7},{"symbol":"S_call","inline":true,"imageIndex":8,"imageOffset":612024,"symbolLocation":20,"sourceLine":204,"sourceFile":"schlib.c"},{"imageOffset":612024,"sourceLine":158,"sourceFile":"schlib.c","symbol":"Scall2","imageIndex":8,"symbolLocation":120},{"imageOffset":18364,"sourceLine":216,"sourceFile":"boot.c","symbol":"racket_boot","imageIndex":8,"symbolLocation":1528},{"imageOffset":13320,"imageIndex":9},{"imageOffset":24144,"symbol":"start","symbolLocation":2544,"imageIndex":10}]},{"id":309879,"frames":[{"imageOffset":7704,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":309880,"frames":[{"imageOffset":7704,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":309893,"frames":[{"imageOffset":7704,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":309895,"frames":[{"imageOffset":7704,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":309907,"name":"com.apple.CFSocket.private","frames":[{"imageOffset":47732,"symbol":"__select","symbolLocation":8,"imageIndex":0},{"imageOffset":701280,"symbol":"__CFSocketManager","symbolLocation":636,"imageIndex":11},{"imageOffset":28780,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":7724,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":309918,"name":"com.apple.NSEventThread","frames":[{"imageOffset":3568,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":75992,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":38456,"symbol":"mach_msg_overwrite","symbolLocation":540,"imageIndex":0},{"imageOffset":4460,"symbol":"mach_msg","symbolLocation":24,"imageIndex":0},{"imageOffset":531420,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":11},{"imageOffset":525512,"symbol":"__CFRunLoopRun","symbolLocation":1232,"imageIndex":11},{"imageOffset":522404,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":11},{"imageOffset":1454664,"symbol":"_NSEventThread","symbolLocation":172,"imageIndex":6},{"imageOffset":28780,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":7724,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6534930432,
    "size" : 233468,
    "uuid" : "6d6644d3-3db3-34c4-b1e3-c675ec5360f0",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6535163904,
    "size" : 53244,
    "uuid" : "886caca0-5762-3640-8db2-3fa3b911c062",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6533881856,
    "size" : 528372,
    "uuid" : "a3869999-0792-3e09-b3fb-5e87ae4639be",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6534832128,
    "size" : 98300,
    "uuid" : "bec775ba-9513-3b66-8f2f-be8d2a817269",
    "path" : "\/usr\/lib\/libc++abi.dylib",
    "name" : "libc++abi.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6531563520,
    "size" : 286112,
    "uuid" : "e20fe24e-bbda-3944-9cfc-8e43a463400b",
    "path" : "\/usr\/lib\/libobjc.A.dylib",
    "name" : "libobjc.A.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6551482368,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.Foundation",
    "size" : 10719232,
    "uuid" : "52b2f83f-586d-32a2-8b66-ce651400ac8c",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Versions\/C\/Foundation",
    "name" : "Foundation",
    "CFBundleVersion" : "1953.1"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6588657664,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15761408,
    "uuid" : "af9f6891-70ad-3c26-af08-b747344892d2",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2299"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4298260480,
    "size" : 917504,
    "uuid" : "708ee92c-8e3b-351b-b29a-0a75ee2058d4",
    "path" : "\/Users\/USER\/*\/Racket.framework\/Versions\/8.7.0.5_CS\/Racket",
    "name" : "Racket"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4296474624,
    "CFBundleShortVersionString" : "8.7.0.5",
    "CFBundleIdentifier" : "org.racket-lang.DrRacket",
    "size" : 16384,
    "uuid" : "6f1a9bb9-2ece-34a0-9341-d638622c94d5",
    "path" : "\/Users\/USER\/*\/DrRacket.app\/Contents\/MacOS\/DrRacket",
    "name" : "DrRacket",
    "CFBundleVersion" : "8.7.0.5"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6531850240,
    "size" : 566448,
    "uuid" : "1f56ab4e-f398-3a9c-bfba-fbbd17808963",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6535577600,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5079040,
    "uuid" : "f4ff83fc-e62c-30b4-b3a9-876c8a1fd595",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1953.1"
  }
],
  "sharedCache" : {
  "base" : 6531203072,
  "size" : 3403612160,
  "uuid" : "5667eb2d-1398-3b38-afff-a929572d4b88"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=986.1M resident=0K(0%) swapped_out_or_unallocated=986.1M(100%)\nWritable regions: Total=1.3G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.3G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               128K        1 \nActivity Tracing                   256K        1 \nCG image                            48K        3 \nColorSync                          560K       25 \nCoreAnimation                       96K        6 \nCoreGraphics                        32K        2 \nCoreUI image data                  736K        5 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           235.3M       39 \nMALLOC guard page                  192K       10 \nMALLOC_MEDIUM (reserved)         480.0M        4         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                       56.1M        7 \nStack                             11.2M        7 \nVM_ALLOCATE                      173.2M      122 \n__AUTH                             645K      163 \n__AUTH_CONST                      11.2M      311 \n__CTF                               756        1 \n__DATA                            4059K      319 \n__DATA_CONST                      14.8M      334 \n__DATA_DIRTY                       708K      108 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       764.2M       24 \n__OBJC_CONST                      1332K      136 \n__OBJC_RO                         65.1M        1 \n__OBJC_RW                         1981K        1 \n__TEXT                           222.0M      348 \ndyld private memory                256K        1 \nmapped file                      346.1M       20 \nshared memory                      864K       15 \n===========                     =======  ======= \nTOTAL                              2.7G     2018 \nTOTAL, minus reserved VM space     1.9G     2018 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "63582c5f8a53461413999550",
      "factorPackIds" : {
        "PROACTIVE_MAIL_INTELLIGENCE_SALIENCY" : "63582cdd892de80b72cc9bde"
      },
      "deploymentId" : 240000001
    },
    {
      "rolloutId" : "6112e3d2fc54bc3389840661",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "635966b0892de80b72cc9d46"
      },
      "deploymentId" : 240000212
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro18,1, BootROM 8419.41.10, proc 10:8:2 processors, 16 GB, SMC 
Graphics: Apple M1 Pro, Apple M1 Pro, Built-In
Display: Color LCD, 3456 x 2234 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5, Samsung
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: Sep  3 2022 02:35:52 version 20.10.965.9.8.7.129 FWID 01-b0e84a9b
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: Laptop, Apple Inc.
Thunderbolt Bus: Laptop, Apple Inc.
Thunderbolt Bus: Laptop, Apple Inc.

**Please include any other relevant details**
e.g., the operating system used or how you are running the code.

MacOS Ventura 13.0

**Comment by mflatt** [comment]
Thanks for the report!
