### ISSUE TITLE
Should we export `get_self_path` and friends?

### ISSUE THREAD

**Issue by LiberalArtist** [racket/racket#4483]
In the "Inside" manual, we document ways to embed files (particularly bootfiles) as executable segments or equivalent on various platforms, including finding the path to the running executable:

https://github.com/racket/racket/blob/8743229eaa88a4ca808dd74f89780cd57a1633f8/pkgs/racket-doc/scribblings/inside/appendix.scrbl#L131-L137

(Rendered at https://docs.racket-lang.org/inside/segment-ideas.html)

Racket also implements these ideas for its own use:

https://github.com/racket/racket/blob/8743229eaa88a4ca808dd74f89780cd57a1633f8/racket/src/start/self_exe.inc#L3-L14

Would it make sense for Racket to export these functions in `racketcs.h` (and `scheme.h` for BC)?

Someone in another context asked today about embedding files in executables and finding the path to the running program, and I pointed them to what Racket does. The implementations in the "Inside" manual for Windows, Mac, and Linux are reasonably concise, but I remembered there are more issues on the BSDs and other Unix-like systems without `/proc/self/exe`, and Racket handles these in `self_exe.inc`.

**Comment by LiberalArtist** [comment]
[Someone on IRC](https://logs.guix.gnu.org/guile/2022-11-03.log#201423) told me that:

> the freebsd version is ... suboptimal
> for why, see https://github.com/llvm/llvm-project/blob/38f34e587d10fcd7d18fd240e41248006faa639e/llvm/lib/Support/Unix/Path.inc#L209-L214
> (the reason why is that KERN_PROC_PATHNAME is obtained by looking up the process text vnode in the namecache, which (a) might not return anything, and (b) will return _a_ name for the executable, not necessarily the one actually used

I have no BSD experience myself, but using the ELF auxiliary vectors sounds like good advice.

They also pointed out that, on Linux, `/proc/self/exe` "does break if `/proc` is not mounted within the applicable root or namespace". Currently, Racket calls `exit(1)` in that case:

https://github.com/racket/racket/blob/8743229eaa88a4ca808dd74f89780cd57a1633f8/racket/src/start/self_exe.inc#L42-L43

It might be better to fall back.

**Comment by mflatt** [comment]
I've made these changes, except for exporting from BC (which doesn't seem worth the extra effort).
