### ISSUE TITLE
Syntax sugar for nested procedure definitions and period (to indicate a rest-parameter of formal parameter list) in R5RS language produce a list-like object

### ISSUE THREAD

**Issue by chiguri** [racket/racket#4488]
**What version of Racket are you using?**
8.6 [cs]

**What program did you run?**
In R5RS language:
```
(define ((test . l)) l)
((test 1 2))
(list? ((test 1 2)))
```

**What should have happened?**
If it runs correctly, the results of the latter two cases are `(1 2)` and `#t`, respectively.
In R5RS language mode, `(1 2)` is displayed, but the next result is `#f`.
The result of `(pair? ((test 1 2)))` is also `#f`.

On the other hand, the resullt of `((test))` is displayed as `()` and is judged as null (`(null? ((test)))` is evaluated to `#t`).

(In Racket language, it runs as we expected.)

**Please include any other relevant details**
This type of codes (syntax sugar for nested lambda) is not described in R5RS (only single lambda is described), but described in RRRS (R2RS).
I'm not sure whether the bug is the result, or allowing the notation.

**Comment by sorawee** [comment]
It's a Racket list, which is immutable, unlike regular lists in R5RS which are mutable.

```
#lang r5rs

(#%require (only racket list?))

(define ((test . l)) l)
(display (list? ((test 1 2)))) ;=> #t
```

I think it makes sense to prohibit this syntactic sugar, since it is not in R5RS.

**Comment by mflatt** [comment]
Probably we can't remove it without breaking a use of `#lang r5rs` somewhere, since currying `define` has always been there and is a somewhat common R5RS extension (if I remember correctly). But the behavior can be made sensible.
