### ISSUE TITLE
Racket is not provided through the PPA for the Ubuntu 22.10

### ISSUE THREAD

**Issue by prnsml** [racket/racket#4494]
Hey, 
I'm not able to install the latest Racket through provided PPA repository as the release file is missing.

**What program did you run?**
```sudo add-apt-repository ppa:plt/racket```

**What should have happened?**
I should be able to install Racket after adding PPA repository.

**If you got an error message, please include it here.**
```
<...>
Ign:7 https://ppa.launchpadcontent.net/plt/racket/ubuntu kinetic InRelease       
Err:8 https://ppa.launchpadcontent.net/plt/racket/ubuntu kinetic Release
  404  Not Found [IP: 185.125.190.52 443]
Reading package lists... Done
E: The repository 'https://ppa.launchpadcontent.net/plt/racket/ubuntu kinetic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
**Please include any other relevant details**
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.10
Release:	22.10
Codename:	kinetic
```

**Comment by sorawee** [comment]
Could you report the problem at https://github.com/takikawa/racket-ppa?

**Comment by prnsml** [comment]
Thanks, created: https://github.com/takikawa/racket-ppa/issues/19
