### ISSUE TITLE
`resolve-module-path` doesn't load the module

### ISSUE THREAD

**Issue by shhyou** [racket/racket#4498]
**What version of Racket are you using?**

v8.7

**What program did you run?**

`resolve-module-path` doesn't load the module.

```racket
(require syntax/modresolve)
(resolve-module-path 'errortrace)
(module-declared? 'errortrace)
;=> #f
```

**What should have happened?**

The [doc](https://docs.racket-lang.org/syntax/module-helpers.html#%28def._%28%28lib._syntax%2Fmodresolve..rkt%29._resolve-module-path%29%29) says:

> When `module-path-v` refers to a module using a collection-based path, resolution invokes the current [module name resolver](https://docs.racket-lang.org/reference/Module_Names_and_Loading.html#%28tech._module._name._resolver%29) and loads the module if it is not declared.

In other words `(module-declared? 'errortrace)` should be `#t`. However, the implementation of `resolve-module-path` doesn't ask `module-path-index-resolve` to load the module.

https://github.com/racket/racket/blob/848d2a5db2f7523ea6d9d7c4d3a3a18485dd59a7/racket/collects/syntax/private/modresolve-noctc.rkt#L60-L72

---

Should I fix the code or should I fix the doc?

**Comment by mflatt** [comment]
I think probably the documentation should change, since it's difficult to predict the effect on existing code of changing the behavior.

If loading is needed, it would make sense to add an optional keyword argument to `resolve-module-path`.
