### ISSUE TITLE
Racket not properly recognizing non-constant define

### ISSUE THREAD

**Issue by paschlie** [racket/racket#4500]
**What version of Racket are you using?**
8.7

**What program did you run?**

--- with "Enforce constant definitions" selected within "Choose Language ..."
--- In definition window enter:

#lang scheme

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; utils from SRFI-1 (tweaked)

(define (1st obj) (if (pair? obj) (car obj) #f))
(define (2nd obj) (if (pair? obj) (cadr obj) #f))
(define (3rd obj) (if (pair? obj) (caddr obj) #f))
(define (append-map f ls)
  (apply append (map f ls)))
(define (filter f ls)
  (cond ((null? ls) '())
        ((f (1st ls)) (cons (car ls) (filter f (cdr ls))))
        (else (filter f (cdr ls)))))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; the world

(define *objects*
  '(whiskey-bottle bucket frog chain))

(define *map*
  '((living-room (you are in the living-room of a wizards house. there is a wizard snoring loudly on the couch.)
                 (west door garden)
                 (upstairs stairway attic))
    (garden (you are in a beautiful garden. there is a well in front of you.)
            (east door living-room))
    (attic (you are in the attic of the wizards house. there is a giant welding torch in the corner.)
           (downstairs stairway living-room))))

(define *object-locations*
  '((whiskey-bottle living-room)
    (bucket living-room)
    (chain garden)
    (frog garden)))

(define *location* 'living-room)

(define *chain-welded* #f)

(define *bucket-filled* #f)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; functions

(define (describe-location location map)
  (2nd (assoc location map)))

(define (describe-path path)
  `(there is a ,(2nd path) going ,(1st path)from here.))

(define (describe-paths location map)
  (append-map describe-path (cddr (assoc location map))))

(define (is-at? obj loc obj-loc)
  (eq? (2nd (assoc obj obj-loc)) loc))

(define (describe-floor loc objs obj-loc)
  (append-map (lambda (x) `(you see a ,x on the floor.))
              (filter (lambda (x) (is-at? x loc obj-loc))
                      objs)))

(define (look)
  (append (describe-location *location* *map*)
          (describe-paths *location* *map*)
          (describe-floor *location* *objects* *object-locations*)))

(define (walk-direction direction)
  (let ((next (assoc direction (cddr (assoc *location* *map*)))))
    (cond (next (set! *location* (3rd next)) (look))
          (else '(you cant go that way.)))))

(define (pickup-object object)
  (cond ((is-at? object *location* *object-locations*)
         (set! *object-locations*
               (cons (list object 'body) *object-locations*))
         `(you are now carrying the ,object))
        (else '(you cannot get that.))))

(define (inventory)
  (filter (lambda (x) (is-at? x 'body *object-locations*))
          *objects*))

(define (have? object)
  (member object (inventory)))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; spels!

(define-syntax defspel
  (syntax-rules ()
    ((defspel (name args ...) body ...)
     (define-syntax name
       (syntax-rules ()
         ((name args ...) body ...))))))

(defspel (walk direction)
  (walk-direction 'direction))

(defspel (pickup object)
  (pickup-object 'object))

(defspel (game-action command subj obj place rest ...)
  (defspel (command subject object)
    (cond ((and (eq? *location* 'place)
                (eq? 'subject 'subj)
                (eq? 'object 'obj)
                (have? 'subj))
           rest ...)
          (else '(i cant command like that)))))

(game-action weld chain bucket attic
             (cond ((have? 'bucket)
                    (set! *chain-welded* #t)
                    '(the chain is now securely welded to the bucket.))
                   (else '(you do not have a bucket.))))

(game-action dunk bucket well garden
             (cond (*chain-welded*
                    (set! *bucket-filled* #t)
                    '(the bucket is now full of water))
                   (else '(the water level is too low to reach.))))

(game-action splash bucket wizard living-room
             (cond
              ((not *bucket-filled*)
               '(the bucket has nothing in it.))
              ((have? 'frog)
               '(the wizard awakens and sees that you stole his frog. 
                     he is so upset he banishes you to the 
                     netherworlds- you lose! the end.))
              (else
               '(the wizard awakens from his slumber and greets you warmly. 
                     he hands you the magic low-carb donut- you win! the end.)
               )))

;; begin game

(look)

--- within Interaction Window enter, after the result of (look) is displayed:

> (set! *chain-welded* #f)

--- yielding:

*chain-welded*: cannot modify a constant

**What should have happened?**

the set! expression should have been allowed to modify *chain-welded*,
but as it wasn't recognized as a variable, it was presumed to be a constant.

**If you got an error message, please include it here.**

chain-welded*: cannot modify a constant

Although there is code which conditionally set!'s its value.

**Please include any other relevant details**

The problem appears to be that the set! of the variable is not recognized,
because it's apparently embodied within a synthetic code fragment defined
by a nested "defspel".

I can fix the problem by deselecting "Enforce constant definitions", but
would like to think it should have been detected as a variable at compile time?

Thanks.

**Comment by sorawee** [comment]
Here's a minimal program that shows the same "issue".

```
#lang racket

(define v 0)

(define-syntax-rule (test)
  (set! v 1))
```

Then in the REPL:

```
> (set! v 2)
v: cannot modify a constant
```

The issue is that while `(set! v ...)` is "apparently embodied within a synthetic code fragment", it is in a macro that is never invoked. So after macro expansion, the program is essentially:

```
#lang racket

(define v 0)
```

So Racket can't detect any `set!`, and thus enforces the constant definition. This is an expected behavior.

One possible solution for your issue is to simply `set!` after `define` right away:

```
#lang racket

(define v 'uninit)
(set! v 0)

(define-syntax-rule (test)
  (set! v 1))
```

This would now allow `(set! v 2)` in the REPL.

**Comment by paschlie** [comment]
Please consider, the addition of a state-variable or similar means, to indicate to the compiler that an interactive window/session will follow; and thereby should presume all otherwise uninvoked methods/macros may be invoked, and thereby only “in-line” only those variables not otherwise reachable.

Thereby also making the intent explicit, as could also be used to invoke a user interaction window, rather than presume all (or no) code may be further interacted with subsequently 

As just a thought.

Thanks and best regards -paul-

**Comment by sorawee** [comment]
It looks to me then that unticking "Enforce constant definitions" is exactly what you want. But it also seems like you don't want to do it. What's wrong with doing that?

FWIW, Racket can detect `set!` in uninvoked function fine, since you can examine `set!` in the expanded program straightforwardly. 

```
#lang racket

(define v 0)
(define (foo)
  (set! v 1))
;; (set! v 2) is fine in the REPL
```

However, accurately detecting potential `set!` in uninvoked macro is probably undecidable, since syntax transformation can do arbitrary computation. So instead, Racket offers you with two sensible options: detecting `set!` from from the result of macro expansion and enforcing constant definitions based on that, or not enforcing constant definitions at all.

**Comment by paschlie** [comment]
I acknowledge I can circumvent the problem by explicitly telling the compiler to not-inline any potential constants, as the current constant identification analysis is apparently restricted to only being capable of recognizing ’set!’s in code reachable from the control-flow present and invoked at the time of compilation.

I find this analogous to it being acceptable for the compiler simply exclude code not reachable at the time of compilation; which would be fine, as long as a REPL session was not to potentially follow; but in cases where such procedural definitions were presented for compilation with the intention to make them available for use in a subsequent REPL session, obviously the code should be complied, with its definitions made available in a subsequent REPL session.

Overall the formal root of the problem appears to be that the language has no means to procedurally identify an intent to enter a REPL session, which would then serve as a semantic indication that all defined (although potentially not yet invoked) code may in fact be subsequently invoked/reachable, and thereby should be complied, and correspondingly optimized to only inline defines which have no ’set!’s associated with them in potentially reachable code.

I suspect the best solution (shy of introducing and requiring a "(REPL)” call to explicitly invoke a REPL session) would be to: either assume a REPL session will follow, forcing the compilation and corresponding optimizations of all code, and to only inline constants identified as having no potentially reachable set! associated with them; or a REPL session will not follow, allowing all code not reachable at the time of compilation, to simply be ignored, as it would them be unreachable.

Thanks for your consideration, -paul-

**Comment by shhyou** [comment]
> should the language be extended to formally specify a (REPL) function call to make it semantically clear that as yet unspecified code may subsequently modify variables otherwise presumed to be constant.

In Racket, this can just be implemented as yet another new language. For example, just replace the `define` in `#lang scheme` with a version that defaults to `set!` every definition with itself, so all definitions will now be mutable. And both kinds of languages can coexist.
