### ISSUE TITLE
The description is missing

### ISSUE THREAD

**Issue by Antigen-1** [racket/racket#4512]
**What version of Racket are you using?**
8.7 [cs]

**Please include any other relevant details**
[expeditor-open](https://docs.racket-lang.org/expeditor/Expeditor_API.html#%28def._%28%28lib._expeditor%2Fmain..rkt%29._expeditor-open%29%29)

![图片](https://user-images.githubusercontent.com/93880182/205481583-96f63370-3f49-4b5c-9e0c-392e9120822a.png)

**Comment by gus-massa** [comment]
I agree. The second half of the explanation of `expeditor-open` is missing.

[/racket/expeditor/.../expeditor.scrbl#L569-L577](https://github.com/racket/expeditor/blob/86bad7e267e6a1e894fb4dbc4ade8032f507d084/expeditor-doc/expeditor.scrbl#L569-L577)


I can somewhat guess what is missing, but I'm not sure. It's better to wait until @mflatt can fix the docs.
