### ISSUE TITLE
(procedure-rename apply 'name)  goes wrong

### ISSUE THREAD

**Issue by joskoot** [racket/racket#4524]
**What version of Racket are you using?**

8.7 cs

**What program did you run?**

((procedure-rename apply 'aap) list '()) 

**What should have happened?**
Should return ( )

**If you got an error message, please include it here.**
 procedure-reduce-arity-mask: arity mask of procedure does not include requested arity mask
   procedure: #<procedure:...rivate/pre-base.rkt:28:5>
   requested arity mask: -8

**Please include any other relevant details**
No problem with version 8.7 BC

**Comment by samth** [comment]
I believe this is already fixed in current Racket, by 8969b6009584748e2e9b7c2d14bd8d251ba6de77. See also #4471.

**Comment by joskoot** [comment]
Ok, thanks

**Comment by sorawee** [comment]
Closing as duplicate
