### ISSUE TITLE
[CI Feature Request] Implement pull request preview environments

### ISSUE THREAD

**Issue by waveywaves** [racket/racket#4529]
**Is your feature request related to a problem? Please describe.**
Racket does not have full stack previews on their PRs, so I would like to support Racket by implementing [Uffizzi](https://github.com/UffizziCloud/uffizzi) preview environments.
Disclaimer: I work on [Uffizzi](https://github.com/UffizziCloud/uffizzi).

**Describe the solution you'd like**
Uffizzi is a Open Source full stack previews engine and our platform is available completely free for Racket (and all open source projects). This will provide maintainers with preview environments of every PR in the cloud, which enables faster iterations and reduces time to merge. You can see the open source repos which are currently using Uffizzi over [here](https://uffizzi.notion.site/)

**Describe alternatives you've considered**
-

**Do you want to contribute to this feature**
YES ! 

**[Optional] Additional context**
-

**Comment by samth** [comment]
I don't really understand what Uffizzi does. Can you explain more, and maybe give an example?
