### ISSUE TITLE
another continuation error found with randomized testing

### ISSUE THREAD

**Issue by rfindler** [racket/racket#4531]
Following hot on the heels of #4515, a [recent drdr run](http://drdr.racket-lang.org/62400/racket/share/pkgs/redex-examples/redex/examples/delim-cont/randomized-tests.rkt) seems to have found another error. 

This is the best I can do to shrink it (which doesn't seem very shrunken to me!):

```
(<>
 ()
 ()
 (wcm
  ()
  (%
   (%
    #f
    (%
     (list)
     (wcm () #t)
     (wcm
      ()
      ((cont
        #f
        (% #f
           (wcm () (dw j
                       (wcm () 0.33)
                       (wcm () (% hole (wcm () first) (wcm () -1)))
                       (wcm ((call/cc cons) (#t #f)) 1)))
           (list)))
       +)))
    (comp (dw A
              +
              (dw p
                  (wcm () print)
                  hole
                  (wcm () zero?))
              (wcm () current-marks))))
   (wcm () call/cm)
   abort)))
```

In the model this returns a procedure but in the implementation it raises an error, trying to apply the empty list.

I'm not 100% sure this is an error, tho, as it may be that this term violates an invariant (so the fixing algorithm is wrong).

**Comment by mflatt** [comment]
Maybe an issue in generating random terms. Here's a hand-shrunk version that I think preserves the interesting middle part of the above version:

```
  (<>
   ()
   ()
   (% #f
      ((cont
        #f
        (% #f
           hole
           (λ (x) 100)))
       +)
      8))
```

This is not a possible evaluation state. There's a continuation value with prompt tag `#f`, but the body of that continuation has a prompt with tag `#f` wrapped around the hole. That can't happen, because the inner prompt would have delimited the continuation capture.

**Comment by rfindler** [comment]
Turns out that there was already a function that does this fixing, [`proper-conts`](https://github.com/racket/redex/blob/master/redex-examples/redex/examples/delim-cont/randomized-tests.rkt#L374-L417)! I'm still not 100% sure I've got the right fix, but the bug was reproducible with 
```
racket randomized-tests.rkt --seed 1008328485 --size 3 --rules 2250
```

which eventually calls `fix-prog` like this, producing the wrong result:

```
> (fix-prog
   (term
    (<>
     ()
     (2)
     (wcm
      ()
      (%
       (%
        #f
        (%
         (list)
         (wcm () #t)
         (wcm
          ()
          ((cont
            #f
            (%
             #f
             (wcm
              ()
              (dw
               j
               (wcm () (set! d (wcm () M)))
               (wcm () (% hole (wcm () first) (wcm () QL)))
               (wcm ((call/cc cons) (#t #f)) (% cons P (wcm () Y)))))
             (list)))
           +)))
        (comp (dw A + (dw p (wcm () N) hole (wcm () zero?)) (wcm () Oj))))
       (wcm () g)
       abort)))))
'(<>
  ()
  ()
  (wcm
   ()
   (%
    (%
     #f
     (%
      (list)
      (wcm () #t)
      (wcm
       ()
       ((cont
         #f
         (%
          #f
          (wcm
           ()
           (dw
            j
            (wcm () print)
            (wcm () (% hole (wcm () first) (wcm () print)))
            (wcm ((call/cc cons) (#t #f)) (% cons #t (wcm () call/cm)))))
          (list)))
        +)))
     (comp
      (dw A + (dw p (wcm () -inf.0) hole (wcm () zero?)) (wcm () current-marks))))
    (wcm () 0.33)
    abort)))
```

and with the fix I pushed that closes this PR, we don't see the `(cont #f (% #f ....` anymore.
