### ISSUE TITLE
Raco can´t install a package in Windows 10 certificate Issue

### ISSUE THREAD

**Issue by RafaelBenitezMozos** [racket/racket#4535]
**What version of Racket are you using?**
8.7 [cs]

**What program did you run?**
I ran the following command:

`raco pkg install pollen`

**What should have happened?**

It should have installed the package pollen. Instead, a problem appeared. The program says that it is related to the certificates.

**If you got an error message, please include it here.**

C:\Users\DELL>raco pkg install pollen
Resolving "pollen" via https://download.racket-lang.org/releases/8.7/catalog/
Resolving "pollen" via https://pkgs.racket-lang.org
Downloading repository https://git.matthewbutterick.com/mbutterick/pollen.git commit c182a30f57ea5096440aea3d097f5fe3b78bb236
ssl-connect: connect failed (error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed)
  context...:
   C:\Program Files\Racket\collects\openssl\mzssl.rkt:368:0: error/network
   C:\Program Files\Racket\collects\openssl\mzssl.rkt:1388:0: wrap-ports
   C:\Program Files\Racket\collects\racket\contract\private\arrow-val-first.rkt:555:3
   C:\Program Files\Racket\collects\net\http-client.rkt:67:0: http-conn-open!
   C:\Program Files\Racket\collects\net\http-client.rkt:274:0: http-conn-open
   C:\Program Files\Racket\collects\racket\contract\private\arrow-val-first.rkt:555:3
   C:\Program Files\Racket\collects\net\url.rkt:202:0: http://getpost-impure-port
   C:\Program Files\Racket\collects\net\url.rkt:305:0: get-pure-port/headers
   C:\Program Files\Racket\collects\racket\contract\private\arrow-val-first.rkt:555:3
   C:\Program Files\Racket\collects\net\git-checkout.rkt:245:0: initial-connect
   C:\Program Files\Racket\collects\net\git-checkout.rkt:55:2: retry-loop
   C:\Program Files\Racket\collects\pkg\private\download.rkt:102:2: download!
   C:\Program Files\Racket\collects\file\cache.rkt:63:2: fetch-and-continue
   C:\Program Files\Racket\collects\racket\contract\private\arrow-val-first.rkt:555:3
   C:\Program Files\Racket\collects\pkg\private\download.rkt:94:0: download-repo!
   C:\Program Files\Racket\collects\pkg\private\stage.rkt:319:11
   ...

**Please include any other relevant details**
Windows 10

**Comment by SinaMobasheri** [comment]
+1 Same Problem!

**Comment by otherjoel** [comment]
> +1 Same Problem, Fedora Workstation 37

Is your error also for trying to install the `pollen` package? That package is hosted on Butterick’s own server (not on GitHub) which uses Let’s Encrypt SSL certs. Your system/library may have an outdated CA cert bundle, which would cause it to run into this issue: https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/

**Comment by SinaMobasheri** [comment]
> > +1 Same Problem, Fedora Workstation 37
> 
> Is your error also for trying to install the `pollen` package? That package is hosted on Butterick’s own server (not on GitHub) which uses Let’s Encrypt SSL certs. Your system/library may have an outdated CA cert bundle, which would cause it to run into this issue: https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/

actually it's racket-langserver.
but i guess my problem is related to restriction on the internet by iran goverment, so it's probably not related to this issue.

**Comment by SinaMobasheri** [comment]
Unfortunately, I'm stuck with this line `Resolving "racket-langserver" via https://download.racket-lang.org/releases/8.7/catalog/` and `racket-lang.org` is filtered in my country! \
is there any way that I can skip this step in `raco pkg install` process? like provide catalog locally for it?

**Comment by otherjoel** [comment]
You might be able to point your Racket installation at a snapshot of the official package catalog?

https://racksnaps.defn.io

**Comment by SinaMobasheri** [comment]
no unfortunately this site is also not working!

**Comment by otherjoel** [comment]
Perhaps download a snapshot of Racket from https://www.cs.utah.edu/plt/snapshots/ or https://plt.cs.northwestern.edu/snapshots/ ?

**Comment by shhyou** [comment]
> Unfortunately, I'm stuck with this line `Resolving "racket-langserver" via https://download.racket-lang.org/releases/8.7/catalog/` and `racket-lang.org` is filtered in my country! is there any way that I can skip this step in `raco pkg install` process? like provide catalog locally for it?

You can locally download the source code of all required packages and do `(cd THE_PACKAGE && raco pkg install)`

**Comment by SinaMobasheri** [comment]
Thanks for responding @otherjoel and @, fortunately I found a good VPN and problem solved!

**Comment by otherjoel** [comment]
@RafaelBenitezMozos time to close this issue? since you [reported elsewhere][1] that it’s resolved for you also.

[1]: https://forums.matthewbutterick.com/t/raco-can-t-install-pollen-help/102

**Comment by RafaelBenitezMozos** [comment]
Yes. The problem was solved. Thank you for your interest.

Enviado desde Correo para Windows

De: Joel Dueck
Enviado: miércoles, 4 de enero de 2023 22:39
Para: racket/racket
CC: RafaelBenitezMozos; Mention
Asunto: Re: [racket/racket] Raco can´t install a package in Windows 10 certificate Issue (Issue #4535)

@RafaelBenitezMozos time to close this issue? since you reported elsewhere that it’s resolved for you also.
