### ISSUE TITLE
fixnumness of bitwise-and is wrong

### ISSUE THREAD

**Issue by sorawee** [racket/racket#4552]
**What version of Racket are you using?**
8.8 [cs]

**What program did you run?**

```
#lang racket
(require racket/fixnum)
(define (f a)
  (fixnum? (bitwise-and a (add1 (most-positive-fixnum)))))
(f (- (random 1) 1)) ;=> #t
```

**What should have happened?**

It should return `#f`, as `(bitwise-and ......)` = `1152921504606846976`, which exceeds `(most-positive-fixnum)` = `1152921504606846975`.

**If you got an error message, please include it here.**
N/A

**Please include any other relevant details**
`(random 1)` is intentionally used to prevent CP0 from inlining and reducing the whole function call to `#f`.

After CP0, the above program is transformed to:

```
  (letrec ([f.440 (lambda (a_1.441)
                    (#2%bitwise-and 1152921504606846976 a_1.441)
                    #t)])
    (variable-set!/define f5.439 f.440 'consistent)
    (call-with-module-prompt
      (lambda ()
        (#%call-with-values
          (lambda ()
            (#2%bitwise-and 1152921504606846976 (#2%- (random 1) 1))
            #t)
          print-values4.438)))
    (#2%void)))
```

We can see that an optimization pass somewhere reduces `(fixnum? (bitwise-and ....))` to `#t`, though this is unsound.

Originally discovered by @AlexKnauth

**Comment by samth** [comment]
I'm suspicious that the bug is a missing `and` in the body of the `lambda` here: https://github.com/racket/racket/blob/master/racket/src/ChezScheme/s/cptypes.ss#L1038-L1039 (and in the definition of `bitwise-ior` below that). The relevant code was added by @gus-massa in https://github.com/racket/racket/commit/250fd3a6405ab43e281507ee0ee851e33f50ddc6

**Comment by gus-massa** [comment]
I agree.

**Comment by AlexKnauth** [comment]
The analogous wrong behavior for `bitwise-ior` is
```racket
(define (g a)
  (fixnum? (bitwise-ior (sub1 (most-negative-fixnum)) a)))
(g (random 1))
```
which produces `#true` where it should produce `#false`.
