### ISSUE TITLE
make install-cgc fails for racket 8.8 built from release sources 

### ISSUE THREAD

**Issue by tgbugs** [racket/racket#4575]
**What version of Racket are you using?**
8.8 [cgc]
https://download.racket-lang.org/releases/8.8/installers/racket-8.8-src-builtpkgs.tgz

**What program did you run?**
https://github.com/tgbugs/tgbugs-overlay/blob/master/dev-scheme/racket/racket-8.7.ebuild
(except run to build 8.8, the 8.8 ebuild has not been pushed since it is currently broken)

**What should have happened?**
Running `make install-cgc` should have succeeded.

**If you got an error message, please include it here.**
```
raco setup: --- building documentation ---                         [14:37:32]
raco setup: running: <pkgs>/racket-doc/scribblings/reference/reference.scrbl
failed
 in build-one
 in loop
 in module->hash
```

**Please include any other relevant details**
This might be an issue with `DESTDIR`?

**Comment by tgbugs** [comment]
We are actively trying to finish porting a old codebase off cgc so that we can stop using it. Officially dropping support for cgc would probably make sense so that a final "if you need to port from cgc to a modern version" release can be documented.

**Comment by mflatt** [comment]
(Looks like I forgot to push the repair yesterday — now done.)

I am not sure how many users CGC still has, but my best guess is that there isn't anyone else.

**Comment by tgbugs** [comment]
Confirming fixed on my end. The patch against the release sources is here https://github.com/tgbugs/tgbugs-overlay/blob/master/dev-scheme/racket/files/8.8-cgc-thread.patch. Thanks!
