### ISSUE TITLE
Reading from an SSL port sometimes blocks for seemingly no reason

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#4587]
The following program spawns a small TLS echo server, connects to it, and sends it 256 bytes of data:

```racket
#lang racket

(require openssl)

(define test.pem (collection-file-path "test.pem" "openssl"))
(define server-context (ssl-make-server-context
                        (ssl-max-server-protocol)
                        #:certificate-chain test.pem
                        #:private-key (list 'pem test.pem)))
(define listener (ssl-listen 0 5 #f #f server-context))
(match-define-values [_ server-port _ _] (ssl-addresses listener #t))

(define (server-loop)
  (define-values [in out] (ssl-accept listener))
  (thread
   (λ ()
     (let conn-loop ()
       (write-byte (read-byte in) out)
       (flush-output out)
       (conn-loop))))
  (server-loop))

(void (thread server-loop))

(let ()
  (define-values [in out] (ssl-connect "localhost" server-port))
  (time (for ([i (in-range 256)])
          (write-byte i out)
          (flush-output out)
          (time (read-byte in)))))
```

`time` is used to report how long each client-side `read-byte` takes, as well as an overall time. On my machine, the last line printed by this program is as follows:

```
cpu time: 49 real time: 675 gc time: 4
```

Shockingly, echoing just 256 bytes has taken well over half a second! The individual `time` results hint at why. They look something like this:

```
...
cpu time: 0 real time: 41 gc time: 0
cpu time: 0 real time: 0 gc time: 0
cpu time: 0 real time: 0 gc time: 0
cpu time: 0 real time: 0 gc time: 0
cpu time: 0 real time: 0 gc time: 0
cpu time: 0 real time: 0 gc time: 0
cpu time: 0 real time: 43 gc time: 0
cpu time: 0 real time: 0 gc time: 0
...
```

Strangely, most `read-byte` calls return immediately, but some take about 40ms of wall clock time. This is rather strange. Removing all uses of `openssl` and replacing them with their plain TCP equivalents results in a program that prints the following as its last line:

```
cpu time: 6 real time: 6 gc time: 0
```

That is closer to what I’d expect. So something is wrong in the implementation of SSL ports.

I don’t think the issue is caused by `ssl-listen` because I have observed the same behavior when connecting over TLS to a server not implemented in Racket (specifically, a local instance of PostgreSQL). I have not tested whether this issue occurs on other systems, so here is my system information in case it proves to be system-specific:

* Operating system: Ubuntu 22.04.2 LTS
* Racket version: 8.8.0.7
* OpenSSL version: 3.0.2 (15 Mar 2022)

It seems plausible to me that the issue is in `openssl/mzssl`. It appears to do quite a delicate dance to attempt to make progress without blocking, and I haven’t taken the time to understand what’s going on.

**Comment by lexi-lambda** [comment]
Here’s a slightly simpler way to reproduce the issue, which isolates the problem to the client side. First, start a server with the following command:

```
openssl s_server -accept 8080 -rev -cert <path to test.pem>
```

Then run the following Racket program:

```racket
#lang racket/base

(require openssl)

(define-values [in out] (ssl-connect "localhost" 8080))
(time (for ([i (in-range 256)])
        (newline out)
        (flush-output out)
        (time (read-byte in))))
```

This still takes about half a second on my machine.

**Comment by mflatt** [comment]
Trying TCP directly was a good idea. Unfortunately, I don't think it really rules out TCP and the OS's scheduling of TCP communication as it interacts with the system calls that Racket/rktio happens to use, because scheduling heuristics depend on specific communication patterns.

I'm able to replicate this behavior on a Linux installation (and not on macOS) using the original program. Here's a section of output from `strace -T -r` where I've set `current-output-port` to line-buffered. The section starts with `time` output and ends with another `time` output where the second one was slow, so the trace section is meant to capture the action that took a while. Note that a `poll` halfway through seems to be the slow step, and that's where Racket is waiting on input from the TCP socket inside the SSL port:

```
     0.000019 write(1, "cpu time: 0 real time: 0 gc time"..., 36cpu time: 0 real time: 0 gc time: 0
) = 36 <0.000010>
     0.000024 fcntl(1, F_SETFL, O_WRONLY|O_LARGEFILE) = 0 <0.000006>
     0.000032 recvfrom(8, 0x442c4008, 8000, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable) <0.000007>
     0.000021 epoll_ctl(6, EPOLL_CTL_ADD, 8, {EPOLLIN, {u32=8, u64=8}}) = 0 <0.000007>
     0.000028 sendto(8, "\27\3\3\0\31\236\326`l", 9, 0, NULL, 0) = 9 <0.000016>
     0.000037 recvfrom(8, 0x442c4008, 8000, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable) <0.000006>
     0.000022 sendto(8, "t\322\374=\233Z\261\26`\0224+RT\245\312\306Aeh=", 21, 0, NULL, 0) = 21 <0.000009>
     0.000027 recvfrom(8, 0x442c4008, 8000, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable) <0.000007>
     0.000029 recvfrom(8, 0x442c4008, 8000, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable) <0.000006>
     0.000023 clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {0, 888122071}) = 0 <0.000007>
     0.000035 recvfrom(8, 0x442c4008, 8000, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable) <0.000007>
     0.000032 poll([{fd=8, events=POLLIN}], 1, 0) = 0 (Timeout) <0.000007>
     0.000029 poll([{fd=3, events=POLLIN}, {fd=7, events=POLLIN}], 2, 0) = 0 (Timeout) <0.000007>
     0.000028 poll([{fd=3, events=POLLIN}, {fd=7, events=POLLIN}], 2, 0) = 0 (Timeout) <0.000007>
     0.000028 epoll_wait(6, [{EPOLLIN, {u32=9, u64=9}}], 1, 0) = 1 <0.000006>
     0.000021 epoll_ctl(6, EPOLL_CTL_DEL, 9, NULL) = 0 <0.000007>
     0.000019 epoll_wait(6, [], 1, 0)   = 0 <0.000006>
     0.000038 recvfrom(9, "\27\3\3\0\31\236\326`l", 8000, 0, NULL, NULL) = 9 <0.000007>
     0.000030 recvfrom(9, 0x442c5f98, 8000, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable) <0.000006>
     0.000021 epoll_ctl(6, EPOLL_CTL_ADD, 9, {EPOLLIN, {u32=9, u64=9}}) = 0 <0.000007>
     0.000033 poll([{fd=9, events=POLLIN}], 1, 0) = 0 (Timeout) <0.000006>
     0.000030 poll([{fd=3, events=POLLIN}, {fd=7, events=POLLIN}], 2, 0) = 0 (Timeout) <0.000006>
     0.000027 poll([{fd=3, events=POLLIN}, {fd=7, events=POLLIN}], 2, 0) = 0 (Timeout) <0.000007>
     0.000025 epoll_wait(6, [], 1, 0)   = 0 <0.000007>
     0.000023 poll([{fd=3, events=POLLIN}, {fd=7, events=POLLIN}, {fd=6, events=POLLIN}, {fd=4, events=POLLIN}], 4, -1) = 1 ([{fd=6, revents=POLLIN}]) <0.041557>
     0.041713 read(4, 0x7fff8e213230, 10) = -1 EAGAIN (Resource temporarily unavailable) <0.000117>
     0.000293 epoll_wait(6, [{EPOLLIN, {u32=9, u64=9}}], 1, 0) = 1 <0.000116>
     0.000281 epoll_ctl(6, EPOLL_CTL_DEL, 9, NULL) = 0 <0.000106>
     0.000176 epoll_wait(6, [], 1, 0)   = 0 <0.000012>
     0.000106 recvfrom(9, "t\322\374=\233Z\261\26`\0224+RT\245\312\306Aeh=", 8000, 0, NULL, NULL) = 21 <0.000036>
     0.000193 recvfrom(9, 0x442c5f98, 8000, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable) <0.000015>
     0.000051 epoll_ctl(6, EPOLL_CTL_ADD, 9, {EPOLLIN, {u32=9, u64=9}}) = 0 <0.000012>
     0.000047 sendto(9, "\27\3\3\0\31\33323\205\331\"`<4\f\254\305;\235GQl#W\327;\243\374\216\301", 30, 0, NULL, 0) = 30 <0.000030>
     0.000068 recvfrom(9, 0x442c5f98, 8000, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable) <0.000010>
     0.000046 recvfrom(9, 0x442c5f98, 8000, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable) <0.000009>
     0.000062 recvfrom(9, 0x442c5f98, 8000, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable) <0.000010>
     0.000057 poll([{fd=9, events=POLLIN}], 1, 0) = 0 (Timeout) <0.000011>
     0.000047 poll([{fd=3, events=POLLIN}, {fd=7, events=POLLIN}], 2, 0) = 0 (Timeout) <0.000010>
     0.000044 poll([{fd=3, events=POLLIN}, {fd=7, events=POLLIN}], 2, 0) = 0 (Timeout) <0.000010>
     0.000038 epoll_wait(6, [{EPOLLIN, {u32=8, u64=8}}], 1, 0) = 1 <0.000010>
     0.000034 epoll_ctl(6, EPOLL_CTL_DEL, 8, NULL) = 0 <0.000010>
     0.000029 epoll_wait(6, [], 1, 0)   = 0 <0.000010>
     0.000062 recvfrom(8, "\27\3\3\0\31\33323\205\331\"`<4\f\254\305;\235GQl#W\327;\243\374\216\301", 8000, 0, NULL, NULL) = 30 <0.000013>
     0.000054 clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {0, 889281570}) = 0 <0.000011>
     0.000048 fcntl(1, F_GETFL)         = 0x8001 (flags O_WRONLY|O_LARGEFILE) <0.000010>
     0.000030 fcntl(1, F_SETFL, O_WRONLY|O_NONBLOCK|O_LARGEFILE) = 0 <0.000010>
     0.000029 write(1, "cpu time: 1 real time: 43 gc tim"..., 37cpu time: 1 real time: 43 gc time: 0
) = 37 <0.000019>
```

(The relevant file descriptor is 9, and 9 is not in that poll call. That's because it has been added to an epoll file descriptor 6 using `epoll_ctl`, and 6 is the result of the `poll`.)

There are all sorts of ways that rktio might use the system API differently that maybe would produce a better schedule, and probably any improvement requires work at that level.

**Comment by lexi-lambda** [comment]
Thanks for investigating this—I was worried that might be the case. It is obviously to be expected that some reads will block—that is unavoidable—but the delays are quite significant, surprisingly so. Unfortunately, I don’t know enough about how Linux behaves at this level to say how this might be improved, but I can investigate.

**Comment by rmculpepper** [comment]
The delay vanishes for me if I enable `TCP_NODELAY` on the output TCP port.

I replaced the call to `ssl-connect` with the following:

    (require ffi/unsafe
             ffi/unsafe/port)

    (define IPPROTO_TCP 6)
    (define TCP_NODELAY 1)

    (define setsockopt_tcp_nodelay
      (get-ffi-obj "setsockopt" #f
                   (_fun (socket enabled?) ::
                         (socket : _int)
                         (_int = IPPROTO_TCP)
                         (_int = TCP_NODELAY)
                         (enabled-ptr : (_ptr i _int) = (if enabled? 1 0))
                         (_int = (compiler-sizeof 'int))
                         -> (result : _int)
                         -> (if (zero? result)
                                (void)
                                (error 'set-tcp-nodelay! "failed")))))

    ; set-tcp-nodelay! : tcp-port boolean -> void
    (define (set-tcp-nodelay! port enabled?)
      (let ([socket (unsafe-port->socket port)])
        (setsockopt_tcp_nodelay socket enabled?)))

    (define-values (in0 out0) (tcp-connect "localhost" 8080))
    (set-tcp-nodelay! out0 #t)
    (define-values (in out)
      (ports->ssl-ports in0 out0 #:hostname "localhost"))

I think it might be a good idea to automatically set `TCP_NODELAY` on TCP ports whenever the port's buffer mode is block-buffered (the default).

**Comment by lexi-lambda** [comment]
Ryan beat me to the punch: I asked some friends about this, and one of them pointed me to `TCP_NODELAY`.

Ryan’s suggestion to set it whenever the port is block buffered makes sense to me. Since I ran into this when using `db/postgresql`, I also took a look at what libpq does, and it seems like it sets `TCP_NODELAY` unconditionally whenever it’s available, so it would make sense for `db-lib` to arrange for `TCP_NODELAY` to be set, however Racket chooses to expose the option.

**Comment by lexi-lambda** [comment]
afdc14b80ec4ae37366880f8ef6d4853cc959cdb resolves the issues with the programs in this issue, and I’ve confirmed that it also resolves the issues I was running into when using `db/postgresql`. I’m happy to call this fixed, but feel free to reopen if you feel there’s something left to be done.

Thanks to both of you for your help!
