### ISSUE TITLE
[Feature Request] Guaranteed `eq?` hash tables for failed `hash-remove`s

### ISSUE THREAD

**Issue by MartianMoorGrove** [racket/racket#4595]
I've been writing a graph library that uses immutable hash tables to represent edges. It keeps track of the size (number of edges) in a graph by incrementing or decrementing a `size` struct field when `hash-set` sets new edge mappings or `hash-remove` removes existing ones, respectively.

Currently in Racket v8.8.0.8, `hash-remove` returns a result `eq?` to its hash table argument value if the mapping removal fails due to the nonexistence of that mapping. In theory, to determine when to decrement a graph's size I could use code similar to this:

```
...

(define new-or-current-edge-table (hash-remove current-edge-table v))

(define edge-removed-and-need-to-decrement-size?
  (if (eq? new-or-current-edge-table current-edge-table)
      #f
      #t))

...

```

The problem is that there is no documented guarantee that `hash-remove` will return a result `eq?` to its hash table argument value (it's not an explicit feature), creating uncertainty in the stability of that functionality. In practice I have to use code similar to this:

```
...

(define new-or-current-edge-table (hash-remove current-edge-table v))

(define edge-removed-and-need-to-decrement-size?
  (if (= (hash-count new-or-current-edge-table)
         (hash-count current-edge-table))
      #f
      #t))

...

```

Having to use more operations is not a real problem there because those ones are fast, but it would still be better to use the previous block of code. Can the previously mentioned guarantee be added to Racket?

**Comment by mflatt** [comment]
I agree that this guarantee makes sense. I'll push that change to the documentation and tests.
