### ISSUE TITLE
Misleading concepts about binding introducing in the language model of racket reference

### ISSUE THREAD

**Issue by FallenSky2077** [racket/racket#4597]
In the latest racket documentation, section ([syntax-model](https://docs.racket-lang.org/reference/syntax-model.html) ) introduces concepts in the racket syntax model, where I find some misleading concepts.

In  [Introducing Bindings](https://docs.racket-lang.org/reference/syntax-model.html#%28part._intro-binding%29) , the documentation says:

> When a [let-values](https://docs.racket-lang.org/reference/let.html#%28form._%28%28quote._~23~25kernel%29._let-values%29%29) form is encountered, the body of the [let-values](https://docs.racket-lang.org/reference/let.html#%28form._%28%28quote._~23~25kernel%29._let-values%29%29) form is extended (by creating new [syntax objects](https://docs.racket-lang.org/reference/syntax-model.html#%28tech._syntax._object%29)) with a fresh [scope](https://docs.racket-lang.org/reference/syntax-model.html#%28tech._scope%29). The [scope](https://docs.racket-lang.org/reference/syntax-model.html#%28tech._scope%29) is added to the identifiers themselves so that the identifiers in binding position are [bound-identifier=?](https://docs.racket-lang.org/reference/stxcmp.html#%28def._%28%28quote._~23~25kernel%29._bound-identifier~3d~3f%29%29) to **uses in the fully expanded form**. So they are not [bound-identifier=?](https://docs.racket-lang.org/reference/stxcmp.html#%28def._%28%28quote._~23~25kernel%29._bound-identifier~3d~3f%29%29) to other identifiers. The new bindings are at the [phase level](https://docs.racket-lang.org/reference/syntax-model.html#%28tech._phase._level%29) at which the [let-values](https://docs.racket-lang.org/reference/let.html#%28form._%28%28quote._~23~25kernel%29._let-values%29%29) form is expanded.

However, two identifiers `a,b` are [bound-identifier=?](https://docs.racket-lang.org/reference/stxcmp.html#%28def._%28%28quote._~23~25kernel%29._bound-identifier~3d~3f%29%29)   if they have **the same** scope set in implementation (This description is present in [the syntax model section](https://docs.racket-lang.org/reference/syntax-model.html#%28part._stxobj-model%29)  but not in [bound-identifier=?](https://docs.racket-lang.org/reference/stxcmp.html#%28def._%28%28quote._~23~25kernel%29._bound-identifier~3d~3f%29%29), which is also confusing). It implies that [bound-identifier=?](https://docs.racket-lang.org/reference/stxcmp.html#%28def._%28%28quote._~23~25kernel%29._bound-identifier~3d~3f%29%29)  is a transitive relation at least in the same phase level. And one can deduce that every use in the **full expanded form**  [let-values](https://docs.racket-lang.org/reference/let.html#%28form._%28%28quote._~23~25kernel%29._let-values%29%29) body will be [bound-identifier=?](https://docs.racket-lang.org/reference/stxcmp.html#%28def._%28%28quote._~23~25kernel%29._bound-identifier~3d~3f%29%29) . 

Consider the following code:
```racket
(let-values ([(x) 1])
    (define id1 (quote-syntax x #:local))
    (let-values ([(y) 2])
      (define id2 (quote-syntax x #:local))
      (list id1 id2 (bound-identifier=? id1 id2))))
```

Both `id1` and `id2`  is a bound identifier that refers to the binding created by the out-most let-values form. It is obvious that they are not [bound-identifier=?](https://docs.racket-lang.org/reference/stxcmp.html#%28def._%28%28quote._~23~25kernel%29._bound-identifier~3d~3f%29%29). The problem is that in a fully expanded form, a bound identifier may refer to a binding identifier with a smaller scope-set, not the same. 

Please clarify this statement.  
1. What does it mean "by creating new [syntax objects](https://docs.racket-lang.org/reference/syntax-model.html#%28tech._syntax._object%29)"?
2. What is exactly a "use"?
3. When and where a binging identifier should be [bound-identifier=?](https://docs.racket-lang.org/reference/stxcmp.html#%28def._%28%28quote._~23~25kernel%29._bound-identifier~3d~3f%29%29) to uses in the body?

**Comment by shhyou** [comment]
I think `bound-identifier=?` are intended for identifiers that will be placed in _binding_ positions, not checking if an identifier is supposed to refer to a binding. For example, when `idX` and `idY` are two `bound-identifier=?` syntax objects, `(quasisyntax (let ([#,idX expr1]) expr2))` and `(quasisyntax (let ([#,idY expr1]) expr2))` have the same meaning. Thus `bound-identifier=?` are useful for checking if there are two _duplicate_ bindings as in if `(let ([,idX expr1] [,idY expr2]) ...)` would be a syntax error.

**Comment by FallenSky2077** [comment]
> I think `bound-identifier=?` are intended for identifiers that will be placed in _binding_ positions, not checking if an identifier is supposed to refer to a binding. For example, when `idX` and `idY` are two `bound-identifier=?` syntax objects, `(quasisyntax (let ([#,idX expr1]) expr2))` and `(quasisyntax (let ([#,idY expr1]) expr2))` have the same meaning. Thus `bound-identifier=?` are useful for checking if there are two _duplicate_ bindings as in if `(let ([,idX expr1] [,idY expr2]) ...)` would be a syntax error.
> 
> I am not sure what this sentence intends to express
> 
> > so that the identifiers in binding position are [bound-identifier=?](https://docs.racket-lang.org/reference/stxcmp.html#%28def._%28%28quote._~23~25kernel%29._bound-identifier~3d~3f%29%29) to uses in the fully expanded form

In my humble opinion, it may be an oversight on the writer's part. By intuition, this sentence should be something like "so the bound identifiers will refer to this binding (instead of other binding variable with the same name) ".

However, it would be useful for the documentation to clarify how this newly added scope affects the subsequent expanding process. For example, what is meant "by creating new syntax object"; and when or how the lexical information of the syntax object in body is updated.

**Comment by shhyou** [comment]
Documentation aside, I hope [Binding as Sets of Scopes](https://www-old.cs.utah.edu/plt/scope-sets/pattern-macros.html#%28part._.Scope_.Sets%29) better answers your question. The example in Section 2.1 illustrates how `let(-values)` adds a fresh scope (`{a_let}` in the example) to everything in its body and the identifiers in the binding position.

I think "creating new syntax objects" means that when expanding `let-values`, the expander constructs a new copy of the original syntax object to add the new scope (`a_let`) instead of mutating the original syntax object.

**Comment by FallenSky2077** [comment]
> Documentation aside, I hope [Binding as Sets of Scopes](https://www-old.cs.utah.edu/plt/scope-sets/pattern-macros.html#%28part._.Scope_.Sets%29) better answers your question. The example in Section 2.1 illustrates how `let(-values)` adds a fresh scope (`{a_let}` in the example) to everything in its body and the identifiers in the binding position.
> 
> I think "creating new syntax objects" means that when expanding `let-values`, the expander constructs a new copy of the original syntax object to add the new scope (`a_let`) instead of mutating the original syntax object.

Thank you very much!  This document is much clearer than official Reference.

**Comment by mflatt** [comment]
The intent here really is to talk about scopes on variables that reference bindings, not the identifiers for the bindings themselves.

As the original question suggests, one problem is that "use" is unclear. It's meant to refer to expressions that are *variables*, and not `quote-syntax` forms. A `quote-syntax` form can have *identifiers*, but not *variables* in the sense of an identifier that has been parsed as a reference to a binding.

When the macro expander encounters an identifier that refers to a bound variable, then the expanded form of the identifier removes extra scopes that are not present on the binding. This action is not really necessary for macro expandsion (it was more necessary with the binding model before scope sets), but it is helpful for consumers of expanded forms, which are then free to use either `free-identifier=?` or `bound-identifier?` to compare bindings and references. Inside of a `quote-syntax` form, however, scopes are left intact, because a quoted identifier might be used in some way other than a reference to a binding.

I'll adjust the cited text at a minimum, but there's certainly room for clarification at more points.

**Comment by FallenSky2077** [comment]
> The intent here really is to talk about scopes on variables that reference bindings, not the identifiers for the bindings themselves.
> 
> As the original question suggests, one problem is that "use" is unclear. It's meant to refer to expressions that are _variables_, and not `quote-syntax` forms. A `quote-syntax` form can have _identifiers_, but not _variables_ in the sense of an identifier that has been parsed as a reference to a binding.
> 
> When the macro expander encounters an identifier that refers to a bound variable, then the expanded form of the identifier removes extra scopes that are not present on the binding. This action is not really necessary for macro expandsion (it was more necessary with the binding model before scope sets), but it is helpful for consumers of expanded forms, which are then free to use either `free-identifier=?` or `bound-identifier?` to compare bindings and references. Inside of a `quote-syntax` form, however, scopes are left intact, because a quoted identifier might be used in some way other than a reference to a binding.
> 
> I'll adjust the cited text at a minimum, but there's certainly room for clarification at more points.

Thank you.

So, when a bound identifier parsed as a variable there is extra non-trivial work to be done by the expander. This is a quite unobtrusive link between evaluation model and syntax model.

**Comment by shhyou** [comment]
> The intent here really is to talk about scopes on variables that reference bindings, not the identifiers for the bindings themselves.
> ...
> When the macro expander encounters an identifier that refers to a bound variable, then the expanded form of the identifier removes extra scopes that are not present on the binding. This action is not really necessary for macro expandsion (it was more necessary with the binding model before scope sets), but it is helpful for consumers of expanded forms, which are then free to use either `free-identifier=?` or `bound-identifier?` to compare bindings and references. Inside of a `quote-syntax` form, however, scopes are left intact, because a quoted identifier might be used in some way other than a reference to a binding.
> 
> I'll adjust the cited text at a minimum, but there's certainly room for clarification at more points.

Now I see this paragraph in [1.2.3.1 Fully Expanded Programs](https://docs.racket-lang.org/reference/syntax-model.html#%28part._fully-expanded%29):

> A reference to a [local binding](https://docs.racket-lang.org/reference/syntax-model.html#%28tech._local._binding%29) in a fully expanded program has a [scope set](https://docs.racket-lang.org/reference/syntax-model.html#%28tech._scope._set%29) that matches its binding identifier exactly. Additional [scopes](https://docs.racket-lang.org/reference/syntax-model.html#%28tech._scope%29), if any, are removed. As a result, [bound-identifier=?](https://docs.racket-lang.org/reference/stxcmp.html#%28def._%28%28quote._~23~25kernel%29._bound-identifier~3d~3f%29%29) can be used to correlate local binding identifiers with reference identifiers, while [free-identifier=?](https://docs.racket-lang.org/reference/stxcmp.html#%28def._%28%28quote._~23~25kernel%29._free-identifier~3d~3f%29%29) must be used to relate references to [module bindings](https://docs.racket-lang.org/reference/syntax-model.html#%28tech._module._binding%29) or [top-level bindings](https://docs.racket-lang.org/reference/syntax-model.html#%28tech._top._level._binding%29).

**Comment by soegaard** [comment]
Is this issue ready to close?
