### ISSUE TITLE
Dead link in pollen Section 9

### ISSUE THREAD

**Issue by rebcabin** [racket/racket#4604]
**What version of Racket are you using?**
8.8 [cs]

**What program did you run?**
Reading the manuals here https://docs.racket-lang.org/pollen/mini-tutorial.html#%28part._pygments-with-pollen%29

**What should have happened?**
This link is dead: http://unitscale.com/mb/technique/styles.css.pp.html

**If you got an error message, please include it here.**
GoDaddy reports the domain is for sale

**Please include any other relevant details**
NA

**Comment by sorawee** [comment]
Please report this issue at https://git.matthewbutterick.com/mbutterick/pollen. This repository is for reporting issues of the Racket language, not packages in Racket.
