### ISSUE TITLE
Incorrect (possibly internal) error values from `stencil-vector-update`

### ISSUE THREAD

**Issue by MartianMoorGrove** [racket/racket#4611]
**What version of Racket are you using?**
v8.8.0.10 [cs]

**What program did you run?**
```
#lang racket

(define sv (stencil-vector #b0))

(stencil-vector-update sv #b1 #b1 1)
```

**If you got an error message, please include it here.**
```
stencil-vector-update: mask of stencil vector does not have all bits in removal mask
  stencil vector: #0vs()
  removal mask: 1
```

**What should have happened?**
It seems like it should have displayed `#<stencil 0>` as the stencil vector error value.
It instead looks like the display string of an internal representation.

It does basically the same thing with this code:
```
#lang racket

(define sv (stencil-vector #b1 1))

(stencil-vector-update sv #b0 #b1 1)
```

**Comment by mflatt** [comment]
Thanks for the report!
