### ISSUE TITLE
Cannot install the snapshot version of racket

### ISSUE THREAD

**Issue by Antigen-1** [racket/racket#4615]
**What version of Racket are you using?**
[Racket CS 8.8.0.10 on ARM](https://users.cs.utah.edu/plt/snapshots/current/installers/racket-8.8.0.10-arm-linux-cs.sh)

**What should have happened?**
Racket should have been successfully installed.

**If you got an error message, please include it here.**

An error was raised:

`./racket-8.8.0.10-arm-linux-cs.sh: 527: /usr/racket-8.8.0.10-tmp-install/bin/racket: not found`

**Please include any other relevant details**

I used the unix-style install. Besides, the script was run on Ubuntu Server 22.04.2(64-bit), Raspberry Pi 4.

**Comment by mflatt** [comment]
That  Racket for ARM is a 32-bit build. Did you mean to run a 32-bit version, and if so, do you have 32-bit libraries installed?

In Docker on macOS, I was able to start an `ubuntu:20.04` container and use
```
dpkg --add-architecture armhf
apt update
apt install libc6:armhf
```
and then `racket` ran afterward, but I'm not sure the result would be the same on a Pi 4.

We don't currently have a 64-bit Arm (aarch64) build for Linux. Racket should run in that configuration, but you'd have to build from source, which takes a while on a Pi 4.
