### ISSUE TITLE
resolve-path-spec documented incorrectly

### ISSUE THREAD

**Issue by benknoble** [racket/racket#4622]
https://github.com/racket/racket/blob/35b84b86e4a76670c0c7e4b2fcfe3aaf41c173bf/pkgs/racket-doc/syntax/scribblings/path-spec.scrbl#L11

It does not accept a 4th argument.

**Comment by shhyou** [comment]
Whoa, how did you spot it!
https://github.com/racket/racket/commit/eab8008c4f62d8561c57d8642860f0c5061ddbc7

**Comment by benknoble** [comment]
> Whoa, how did you spot it!
> [eab8008](https://github.com/racket/racket/commit/eab8008c4f62d8561c57d8642860f0c5061ddbc7)

Er, [I actually used `syntax/path-spec` in a program](https://github.com/drym-org/dia/pull/2/commits/f7c2f997e01c7efac50157fc10efa0c89bcaf1e3) by following the docs and it arity errored, so I checked the source.
