### ISSUE TITLE
When run mzscheme from racket 8.8, may fail as free(): invalid pointer.

### ISSUE THREAD

**Issue by sxzzsf** [racket/racket#4627]
https://github.com/racket/racket/blob/4754c35a92f8b243ebc3e160d43bcd36e1bc2923/racket/src/start/self_exe.inc#L351
When free(path) in lookup_exe_via_path(), the path variable may be not the same pointer returned from copy_string(getenv("PATH")).

Following is the patch to fix this issue.
[racket-8.8-free-invalid-pointer.txt](https://github.com/racket/racket/files/11207548/racket-8.8-free-invalid-pointer.txt)

**Comment by mflatt** [comment]
Thanks!
