### ISSUE TITLE
`~r` ignores `#:decimal-sep` for `#:notation 'exponential`

### ISSUE THREAD

**Issue by sschwarzer** [racket/racket#4635]
**What version of Racket are you using?**
8.8 [cs]

**What program did you run?**

```
$ racket
Welcome to Racket v8.8 [cs]
> (~r 12345678.123456 #:notation 'exponential #:decimal-sep ",")
"1.234568e+07"
```

"Positional" notation for comparison:
```
> (~r 12345678.123456 #:notation 'positional #:decimal-sep ",")
"12345678,123456"
```

**What should have happened?**
The output should be "1,234568e+07" (decimal _comma_ because it was specified with `#:decimal-sep ","`.

**If you got an error message, please include it here.**
n.a.

**Please include any other relevant details**
Fedora Linux 37, Racket from Racket download page

If the behavior is intended, it should be explained in the documentation. However, I can't imagine why the behavior should be intentional. :-)

**Comment by otherjoel** [comment]
This has been fixed in #4637  (cc @mflatt)
