### ISSUE TITLE
On Windows `file-or-directory-modify-seconds` fails to change directories' mtime

### ISSUE THREAD

**Issue by formalizm** [racket/racket#4636]
**What version of Racket are you using?**
8.8 [cs]

**What program did you run?**
```racket
(define dir "c:\\test123")
(make-directory* dir)
(define t (file-or-directory-modify-seconds dir))
(file-or-directory-modify-seconds dir (- t 10))
; file-or-directory-modify-seconds: error setting file/directory time
;  path: c:\test123
;  system error: Permission denied; errno=13
```

**What should have happened?**
The directory's modification time should have changed

**If you got an error message, please include it here.**
; file-or-directory-modify-seconds: error setting file/directory time
;  path: c:\test123
;  system error: Permission denied; errno=13

**Please include any other relevant details**
Operating system: Windows 10.
`file-or-directory-modify-seconds` changes mtime of files OK.
`file-or-directory-modify-seconds` reads mtime of directories OK.
Changing directories' mtime via other means (than Racket) is OK on my system.

**Comment by qingzhu521** [comment]
same problem
