### ISSUE TITLE
raco demod displays an error when a file requires net/http-easy

### ISSUE THREAD

**Issue by rinfz** [racket/racket#4642]
**What version of Racket are you using?**
8.8 [cs]

**What program did you run?**
```
#lang racket/base
(require net/http-easy)
```

**What should have happened?**
The program completes without an error.

**If you got an error message, please include it here.**
```
invalid syntax #[#{keyword dhghafpy3v03qbye1a9lwf-0} direct]
  context...:
   /Applications/Racket v8.8/share/pkgs/compiler-lib/compiler/demodularizer/main.rkt:25:0: demodularize
   body of "/Applications/Racket v8.8/share/pkgs/compiler-lib/compiler/demodularizer/batch.rkt"
   /Applications/Racket v8.8/collects/raco/raco.rkt:41:0
   body of "/Applications/Racket v8.8/collects/raco/raco.rkt"
   body of "/Applications/Racket v8.8/collects/raco/main.rkt"
```

**Please include any other relevant details**
MacOS M1, running `raco demod file.rkt`. The program does output a .zo file, but the error causes me to lose confidence in the result.

**Comment by mflatt** [comment]
Thanks for the report!
