### ISSUE TITLE
Recursive contracts blame different party base on where `recursive-contract` is written

### ISSUE THREAD

**Issue by shhyou** [racket/racket#4648]
**What version of Racket are you using?**
Welcome to Racket v8.8.0.9 [cs].

**What program did you run?**

When a recursive contract appears in negative positions, the party being blamed is affected by where `recursive-contract` is specified. More precisely, these two contracts blame different partys:

- dyn1/c: `(-> (recursive-contract dyn1/c) #t)`
- dyn2/c: `(recursive-contract (-> dyn2/c #t))`

When given bad arguments, the contract `dyn1/c` correctly blames the caller whereas `dyn2/c` asserts that the callee breaks the contract. I think the behavior of `dyn1/c` is more desirable. However, it is unclear why `dyn2/c` blames the callee.

```racket
#lang racket

(module DynCtc racket
  (provide dyn1/c dyn2/c)
  (define dyn1/c (-> (recursive-contract dyn1/c) #t))
  (define dyn2/c (recursive-contract (-> dyn2/c #t))))

(module Lib racket
  (require (submod ".." DynCtc))
  (provide (contract-out [f1 dyn1/c] [f2 dyn2/c]))
  (define (f1 dyn1) #t)
  (define (f2 dyn2) #t))

(require 'Lib)

;; Seems ok
;; f1: contract violation
;;   expected: a procedure
;;   given: 'bad
(f1 'bad)

;; Blames Lib
;; f2: broke its own contract
;;   promised: a procedure
;;   produced: 'bad
(f2 'bad)
```

**Comment by rfindler** [comment]
Thanks!
