### ISSUE TITLE
Recent syntax/parse changes break rerequire

### ISSUE THREAD

**Issue by Bogdanp** [racket/racket#4656]
**What version of Racket are you using?**

0abb98f922

**What program did you run?**

The repro for this is large. I'll try to minimize it if I can find the time, but for now:

1. Clone https://github.com/marckaufmann/congame
2. Install the `congame-core/` and `congame-web/` packages.
3. Run the following program in the root of the repo:

```racket
#lang racket/base

(require racket/rerequire
         raco/invoke)

(raco "make" "congame-web/dynamic.rkt") ;; from the raco-invoke package
(void (dynamic-rerequire 'congame-web/dynamic))
(dynamic-require 'congame-web/dynamic 'start)
```

**What should have happened?**

The dynamic require should succeed. This worked fine before the recent changes to syntax/parse. (EDIT: Just checked out 19fbb4e39c and it works there.)

**If you got an error message, please include it here.**

```
$ racket repro.rkt
0
define-values: assignment disallowed;
 cannot re-define a constant
  constant: struct:sim:dots
  in module:(submod "/Users/bogdan/sandbox/racket/racket/collects/syntax/parse/private/rep-patterns.rkt" simple)
  context...:
   body of (submod "/Users/bogdan/sandbox/racket/racket/collects/syntax/parse/private/rep-patterns.rkt" simple)
   /Users/bogdan/sandbox/racket/racket/collects/racket/rerequire.rkt:20:0: rerequire
   body of "/Users/bogdan/work/congame/repro.rkt"
```

**Comment by mflatt** [comment]
Here's a smaller example to show the problem with `dynamic-rerequire`.

Call this module `m.rkt` and compile it (e.g., `raco make m.rkt`):

```
#lang racket/base
(module sub racket/base
  (define v 'dont-try-to-replace-me))
```

Load the submodule `sub` before loading the module with `dynamic-rerequire`:

```
> (require (submod "m.rkt" sub))
> (require racket/rerequire)
> (dynamic-rerequire "m.rkt")
define-values: assignment disallowed;
 cannot re-define a constant
  constant: v
  in module:(submod "/tmp/m.rkt" sub)
 [,bt for context]
```

The problem could be characterized as a mismatch between `dynamic-rerequire` working at the file level and `require` working at the (sub-)module level. Probably the repair is to change `dynamic-rerequire` to not try to replace submodules that are already declared, and I'll work on that.
