### ISSUE TITLE
[Feature Request] Add `raco pkg uninstall`/`raco pkg add` synonym(s)

### ISSUE THREAD

**Issue by benknoble** [racket/racket#4662]
**Is your feature request related to a problem? Please describe.**

The choice of `install`+`remove` seems odd to me; I would rather remember `[un]install` or `add`/`remove`.

**Describe the solution you'd like**

I would like either or both of:
- `raco pkg uninstall` is a synonym of `raco pkg remove`
- `raco pkg add` is a synonym of `raco pkg install`

**Describe alternatives you've considered**

None.

**Do you want to contribute to this feature**

Happily; the question is essentially "how much effort should I put it into _reducing_ the amount of effort it takes to declare a synonym".

**[Optional] Additional context**

samth agreed this would not be too difficult/too much extra maintenance.

**Comment by capfredf** [comment]
It just occurred to me that a few linux distros' package managers use `install` and `remove`: zypper` on openSUSE's package manager, `dnf` on Fedora, `apt` on Debian and etc.
