### ISSUE TITLE
armv7l cross build: immutable-string? et al. "not required" from the specified module '#%kernel

### ISSUE THREAD

**Issue by liamdiprose** [racket/racket#4663]
**What version of Racket are you using?**
master branch https://github.com/racket/racket/commit/c1efe916e992f3be071f50d0ef782cb1fa677984

**What program did you run?**
Cross-compile armv7l from x86_64, using Nix to supply the build and host dependencies. 

Building is successful:
```sh
cs/c/configure --prefix=$out \
  --enable-shared --enable-lt=$lt/bin/libtool \
  --enable-pb --disable-pbchunk \
  --enable-scheme=$chez-from-tree/bin/scheme \
  --enable-racket=$system/bin/racket \
  --enable-portable \
  --enable-mach=tpb32l \
  --build=x86_64-unknown-linux-gnu \
  --host=armv7l-unknown-linux-gnueabihf

zuo .
```

But when it comes time to install, raco coughs up this error:
```sh
zuo . install-cs
# ... snip ...
$system/bin/racket -MCR cs/c/compiled: --cross-compiler tpb32l cs/c -X $out/share/racket/collects -G $out/etc/racket -N raco -l- setup --no-user
 raco setup: ignoring compiled files, rebuilding from source...
  triggered by use of non-".zo" file
   path: $out/share/racket/collects/compiler/private/cm-minimal.rkt
$out/share/racket/collects/racket/private/pre-base.rkt:229:30: provide: excluded identifier was not required from the specified module
   at: immutable-string?
```

https://github.com/racket/racket/blob/c1efe916e992f3be071f50d0ef782cb1fa677984/racket/collects/racket/private/pre-base.rkt#L229

I'm having trouble understanding the error "excluded identifier was not required from the specified module". Wouldn't this make more sense: "excluded identifier was not *provided by* the specified module"?

Anyway, I hope you get a sense for how green I am to Racket's build process. If someone could help me figure out why the `immutable-string?` symbol is fine in a standard build, but problematic in this cross-build, I would really appreciate it.

**Comment by mflatt** [comment]
Does `$system/bin/racket` match the version that you are trying to build? The `--enable-racket` flag requires a host Racket that matches the target build version exactly. In this case, that means a Racket built from commit c1efe916e992f3be071f50d0ef782cb1fa677984.

Also, just to make sure, the flags `--enable-pb --disable-pbchunk` and `--enable-mach=tpb32l` will build Racket for purely interpreted mode, as opposed to generating Arm7 machine code. Is that the intent?

**Comment by liamdiprose** [comment]
Hey Mathew, thanks for your work with Racket on Chez. I enjoyed watching your ICFP talk.

`$system/bin/racket` was v8.8, so I'm building from the same commit now. I'll report back on the results when it completes. 

Thanks for checking I meant interpreted mode. I was under the belief Chez doesn't support machine code for Arm7 and still getting used to the fact it wasn't going to be as fast. Are you saying all I have to do is remove those options?

**Comment by mflatt** [comment]
Thanks!

It's possible that I'm confused about 32-bit Arm flavors, but I'm pretty sure that things should work, because the 32-bit Arm backend should work for Arm6 and up (with hardware floats). So, yes, leave out `--enable-pb --disable-pbchunk` and `--enable-mach=tpb32l`. If the configure scripts don't figure out the right platform, it's possible that `--enable-mach=tarm32le` will help, but you shouldn't need even that.

**Comment by liamdiprose** [comment]
You were onto it, cross compiling with an older racket was causing the issue. I'm sorry I didn't read the docs harder.

https://github.com/racket/racket/blob/c1efe916e992f3be071f50d0ef782cb1fa677984/racket/src/cs/README.txt#L54

With the correct build racket version, compiling with `--enable-pb --disable-pbchunk` (for both build racket and host racket) now gives this error during `raco setup`.

```
Exception: incompatible fasl-object machine-type ta6le found in /build/source/src/build/cs/c/compile-xpatch.tpb32l
 integer-bytes->integer: contract violation
   expected: bytes?
   given: #<eof>
```

HOWEVER, compiling without those options, the build correctly detects `tarm32le`, builds successfully and runs on my device. Consider this issue resolved.

If you want to pursue this new issue, I will be happy to help you debug it further.
