### ISSUE TITLE
`read-syntax`: span is inconsistent, not counting characters within parens

### ISSUE THREAD

**Issue by dvanhorn** [racket/racket#4681]
**What version of Racket are you using?**
8.8 [cs]

**What program did you run?**
```
#lang racket 
(syntax-span
  (with-input-from-string "(λ)"
    (λ () (read-syntax #f))))
```

**What should have happened?**

Should produce 3, but produces 4.

**Please include any other relevant details**

This seems to be an issue with multi-byte characters in general.  Things work fine when not in parens (you get the correct *character* count, but once inside of parens you get a byte count:
```
(syntax-span
  (with-input-from-string "↑"
    (λ () (read-syntax #f)))) ; => 1, correct
(syntax-span
  (with-input-from-string "(↑)"
    (λ () (read-syntax #f)))) ; => 5, should be 3    
```

**Comment by mflatt** [comment]
Ports count in bytes by default (because that's much cheaper), so you have to ask for character counting by using `port-count-lines!`:

```
(syntax-span
  (with-input-from-string "(↑)"
    (λ ()
      (port-count-lines! (current-input-port))
      (read-syntax #f))))
```

**Comment by dvanhorn** [comment]
OK, thanks.  I'm confused why this returns 1 then.
```
(syntax-span
  (with-input-from-string "↑"
    (λ () (read-syntax #f))))
```

**Comment by mflatt** [comment]
I think it's because the span of an identifier is based on the number of characters read, while the span of a syntax list is based on `port-next-location` before and after.

**Comment by dvanhorn** [comment]
It seems strange to me that I have to know what kind of syntax was read in order to interpret the span.  The `port-next-location` difference would be more consistent, IMO.

I wonder if the docs for `syntax-span` should say "Returns the span (non-negative exact integer) in bytes (by default)" instead of "in characters", with a link to `port-count-lines!`?

**Comment by mflatt** [comment]
I was guessing wrong about the reason for a span of 1 on the identifier. It turns out to be a limitation of the reader's implementation more generally, where it assumes that reading a character for the reader's dispatch has advanced the port by one position. I'll look into fixing that. And I agree that the documentation should be improved.

**Comment by dvanhorn** [comment]
Thanks for looking into this and adjusting the reader and docs.  I think it can be closed unless you think there's more to it.
