### ISSUE TITLE
define-title+link fails on page 23.3 Teaching of Racket Guide.

### ISSUE THREAD

**Issue by spdegabrielle** [racket/racket#4688]
23.3 teaching of Racket Guide https://docs.racket-lang.org/guide/teaching-langs.html 

The scribble `See @HtDP-doc[].` in pkgs/racket-doc/scribblings/guide/dialects.scrbl#L140 

is rendering as 
<img width="988" alt="See theHow to Design Programs languagedocumentation." src="https://github.com/racket/racket/assets/108047/2e61b521-6752-4d2c-bd4b-59cad567a8b4">
(note missing spaces) 

instead of `See the How to Design Programs language documentation.`

the simple macro at https://github.com/racket/racket/blob/89a8b08f111f5cd52eb11829603f62431cda89c2/pkgs/racket-doc/scribblings/private/docname.rkt#L9 appears to be failing.

<https://github.com/racket/racket/blob/89a8b08f111f5cd52eb11829603f62431cda89c2/pkgs/racket-doc/scribblings/guide/dialects.scrbl#L140>

**Comment by sorawee** [comment]
Already fixed in https://github.com/racket/racket/commit/5da4dc7e3eecaf4e5c3d12e1d9b0f1c9e13382c7
