### ISSUE TITLE
Inconsistent `(system-type 'arch)` on BC x86_64 FreeBSD?

### ISSUE THREAD

**Issue by LiberalArtist** [racket/racket#4691]
This is Racket BC's definition for `SCHEME_ARCH` on FreeBSD:
https://github.com/racket/racket/blob/89a8b08f111f5cd52eb11829603f62431cda89c2/racket/src/bc/sconfig.h#L346-L359
It appears to be the only circumstance when `amd64` is used instead of `x86_64` for `(system-type 'arch)` and `(system-library-subpath)`. In particular, Racket CS uses `x86_64` on `ta6fb`:
https://github.com/racket/racket/blob/89a8b08f111f5cd52eb11829603f62431cda89c2/racket/src/cs/rumble/system.ss#L74-L83
I think the BC definition should probably changed, but I'm not a BSD user myself.

**Comment by LiberalArtist** [comment]
I just came across this in the docs, which, while it doesn't strictly promise *not* to return `'amd64`, does give a stronger implication to expect `'x86_64` than I'd realized:
https://github.com/racket/racket/blob/89a8b08f111f5cd52eb11829603f62431cda89c2/pkgs/racket-doc/scribblings/reference/runtime.scrbl#L34-L36

**Comment by mflatt** [comment]
I agree that it should be `x86_64`.
