### ISSUE TITLE
`(system-type 'word)` on `'pb` always reports 64

### ISSUE THREAD

**Issue by LiberalArtist** [racket/racket#4692]
The [documentation for `system-type`](https://docs.racket-lang.org/reference/runtime.html#%28idx._%28gentag._440._%28lib._scribblings%2Freference%2Freference..scrbl%29%29%29) says:

> In `'word` mode, the result is either `32` or `64` to indicate whether Racket is running as a 32-bit program or 64-bit program.

The implementation for CS is: https://github.com/racket/racket/blob/89a8b08f111f5cd52eb11829603f62431cda89c2/racket/src/cs/rumble/system.ss#L168

But, on `pb` and `tpb` machine types, fixnums may be larger than the word size at the OS level.

**Comment by mflatt** [comment]
I'm not sure what the result should be. It's accurate in the sense that it reflects the size of addresses within Racket. Meanwhile, to use Racket's FFI — and therefore, to much much of anything with Racket besides maybe bootstrapping Racket — you'll need to have a more specific machine type, like `pb64l`.

Is there some case where the result from `(system-type 'word)` would matter for `pb` or `tpb`?

**Comment by LiberalArtist** [comment]
> (Is it even possible to build Racket as `pb` or `tpb`, as opposed to just Chez Scheme? I've lost track.)

It seems it is not, which is fine with me! An attempt just now with `../configure --enable-csonly --enable-pb --disable-pbchunk --enable-mach=pb --enable-scheme=scheme` failed at the point of:
```
gcc -g -O2 -Wall -o cs/c/raw_racketcs cs/c/main.o cs/c/boot.o cs/c/ChezScheme/pb/boot/pb/libkernel.a cs/c/ChezScheme/pb/lz4/lib/liblz4.a cs/c/rktio/librktio.a -rdynamic -ldl -lm  -lrt  -lncurses -lz -lffi
cs/c/ChezScheme/pb/bin/pb/scheme -B cs/c/ChezScheme/pb/boot/pb/petite.boot -B cs/c/ChezScheme/pb/boot/pb/scheme.boot --script ../cs/c/to-vfasl.ss cs/c/ChezScheme/pb/boot/pb/petite.boot cs/c/petite-v.boot
Exception in vfasl: cannot vfasl with unknown endianness
failed
 in build-one
 in loop
 in module->hash
make: *** [Makefile:18: all] Error 1
```
The question came up while I was revisiting https://github.com/racket/racket/issues/3948 (an especially improbable situation to be in with a `pb` Racket), and I was trying to determine whether:
```
(format "tpb~a~a"
        (system-type 'word)
        (if (system-big-endian?)
            "b"
            "l"))
```
would produce the right pbarch machine type for the current system.
