### ISSUE TITLE
subprocess doesn't include correct value in contract error

### ISSUE THREAD

**Issue by endobson** [racket/racket#4693]
The subprocess code references the wrong variable at line 73 in:

https://github.com/racket/racket/blob/365b92f17269b09af46a018c48308c79cccaaa59/racket/src/io/subprocess/main.rkt#L68-L73

This should be `group/command` instead of `command` at this point because the body of the define hasn't run yet to define `command`.

```
$ racket -v
Welcome to Racket v8.9.0.5 [cs].
$ racket -e '(subprocess #f #f #f 42)'
subprocess: contract violation
  expected: path-string?
  given: #<unsafe-undefined>
  context...:
   body of top-level
```

This shouldn't be about `#<unsafe-undefined>` but instead 42.

I failed to get the build system to work to pick up changes to this file so don't have a PR, as all of this is using my head to evaluate the racket code (and I don't trust that too well).

**Comment by mflatt** [comment]
Thanks for the report and repair!

To build a change like this, the simplest way is `make derived` in the Git checkout root, then `make`. That works if you have a build in place to bootstrap from.
