### ISSUE TITLE
Crash from `hash-map` sorting w/ contract

### ISSUE THREAD

**Issue by LiberalArtist** [racket/racket#4699]
The following program crashed both Racket 8.8 on ta6le and the Utah 20230715-cb0719d5b7 snapshot on ta6nt:
```racket
#lang racket

(define/contract (proc name value)
  (-> symbol? any/c any)
  'ok)

(hash-map #hasheq([a . "apple"])
          proc
          #t)
```
The program doesn't crash if `hash-map` is called with two arguments or an explicit `#f`. It also doesn't crash if `symbol?` in the contract is replaced with `any/c`. I've tried simple uses of `chaperone-procedure`, but I haven't put the pieces together to reproduce without contracts.

**Comment by mflatt** [comment]
It looks like this is yet another missing `|#%app|` in `racket/src/cs/rumble`.
