### ISSUE TITLE
`syntax-parse` regression involving `...+`

### ISSUE THREAD

**Issue by camoy** [racket/racket#4700]
**What version of Racket are you using?**
e.g., 8.10.0.1 [cs]

**What program did you run?**

```rkt
#lang racket/base

(require (for-syntax racket/base
                     syntax/parse))

(define-syntax (hello stx)
  (syntax-parse stx
    [(_ (~describe "thing" e) ...+)
     #'(void)]))

(hello)
```

**What should have happened?**
Error expected more terms.

**If you got an error message, please include it here.**
No error! (This was reduced from a failing unit test in one of my libraries, so this must have been a somewhat recent change).

cc @rmculpepper

**Comment by shhyou** [comment]
Probably related to the new syntax/parse interpreter from #4605

**Comment by jbclements** [comment]
candidate for release blocker?

**Comment by rfindler** [comment]
I think so.

Robby
