### ISSUE TITLE
string-locale-downcase: bytes->string/utf-8: byte string is not a well-formed UTF-8

### ISSUE THREAD

**Issue by Kalimehtar** [racket/racket#4715]
**What version of Racket are you using?**
8.9 [cs]

**What program did you run?**
```
#lang racket

(displayln (string-downcase "ΧΑΟΣΣ"))
(displayln (string-locale-downcase "ΧΑΟΣΣ"))
(parameterize ([current-locale #f])
  (displayln (string-downcase "ΧΑΟΣΣ"))
  (displayln (string-locale-downcase "ΧΑΟΣΣ")))
```

**What should have happened?**
When current-locale is #f, I expect `(string=? (string-downcase "ΧΑΟΣΣ") (string-locale-downcase "ΧΑΟΣΣ"))`

**If you got an error message, please include it here.**
When the program run, I get
```
χαοσς
χαοσσ
χαοσς
. . bytes->string/utf-8: byte string is not a well-formed UTF-8 encoding
  byte string: #"\356\247\356\221\356\237\356\274\356\274"
```

**Please include any other relevant details**
Windows 10, x64.

**Comment by gus-massa** [comment]
I'm not sure if this is obvious or relevant (or correct), but `Σ` is transformed in the middle of a word to `σ` but at the end of a word to `ς`, so Chez Scheme has some weird code just to handle that case.

**Comment by soegaard** [comment]
FWIW Here are links to the CS and BC implementations:

CS:  https://github.com/racket/racket/blob/171547e08023200a81ee7ca502eaa0ac33ef329c/racket/src/io/locale/recase.rkt#L16

BC:
https://github.com/racket/racket/blob/171547e08023200a81ee7ca502eaa0ac33ef329c/racket/src/bc/src/string.c#L3451

**Comment by gus-massa** [comment]
Just an example:
* Uppercase
* Bytes in the error message
* Lowercase

```
#lang racket

(string->bytes/utf-8 "ΧΑΟΣΣ")
#"\356\247\356\221\356\237\356\274\356\274"
(string->bytes/utf-8 "χαοσς")

(bytes->list (string->bytes/utf-8 "ΧΑΟΣΣ"))
(bytes->list #"\356\247\356\221\356\237\356\274\356\274")
(bytes->list (string->bytes/utf-8 "χαοσς"))

(bytes->list (string->bytes/utf-8 "A"))
(bytes->list (string->bytes/utf-8 "a"))

(bytes->string/latin-1 (string->bytes/utf-8 "ΧΑΟΣΣ"))
(bytes->string/latin-1 #"\356\247\356\221\356\237\356\274\356\274")
(bytes->string/latin-1 (string->bytes/utf-8 "χαοσς"))

; Output:

;#"\316\247\316\221\316\237\316\243\316\243"
;#"\356\247\356\221\356\237\356\274\356\274"
;#"\317\207\316\261\316\277\317\203\317\202"

;'(206 167 206 145 206 159 206 163 206 163)
;'(238 167 238 145 238 159 238 188 238 188)
;'(207 135 206 177 206 191 207 131 207 130)

;'(65)
;'(97)

;"Î§Î\u0091Î\u009FÎ£Î£"
;"î§î\u0091î\u009Fî¼î¼"
;"Ï\u0087Î±Î¿Ï\u0083Ï\u0082"
```

It looks like some internal part is adding 32 to the first byte (like in ascii) and then skipping the second byte, but the rule is broken in the last two. It almost makes sense in a naive `uft8->latin1` conversions, except the two `£` (pounds) at the end. Looking in an ascii table I see a `ú` (u with acute) transformed into a `╝` (double corner) but I guess I'm looking at the wrong code page.

**Comment by gus-massa** [comment]
Fixed in https://github.com/racket/racket/commit/6d6857383211a9b27f91ad90473536157702c740
