### ISSUE TITLE
Uninstall Beautiful Racket package

### ISSUE THREAD

**Issue by AGoh2019** [racket/racket#4717]
Version 8.9

Ran install "Beautiful Racket".  Don't wish to use it now.  How do I uninstall it.  And I haven't found much resources on the web regarding AI programming with Racket, even if it is a Lisp/Scheme dialect.

**Comment by sorawee** [comment]
Please ask questions at [Discourse](https://racket.discourse.group/) or [Discord](https://discord.gg/6Zq8sH5). GitHub issues are only for issue reporting.

But for your specific question, you can uninstall it with `raco pkg remove beautiful-racket`.

**Comment by AGoh2019** [comment]
raco is not a command that is understood by Microsoft Windows.  Any other hints?
--- Andrew Goh
 

    On Saturday, 12 August 2023 at 04:05:34 pm SGT, sorawee ***@***.***> wrote:  
 
 


Closed #4717 as completed.

**Comment by rfindler** [comment]
This command is available in `command.com` in the directory where your Racket installation is, so you might try to "cd" there. 

If you can open DrRacket, you can also try using the "File|Package Manager..." menu item. Select the "Currently Installed" tab and type "beauti" (or similar) into the search bar. Then you can click on the package and click the "Remove" button near the bottom of the window.

**Comment by soegaard** [comment]
@AGoh2019 

> raco is not a command that is understood by Microsoft Windows.  Any other hints?

This means the directory containing Racket executables is not in your path
(the list of directories where the system searches after commands).

The path is stored in an "environment variable" called PATH.
You can set this manually in Windows [1], but there is an easier option.
In the DrRacket menu "Help" there is a menu item "Configure command line for Racket ...".
This will add the directory to your path.


[1] https://www.mathworks.com/matlabcentral/answers/94933-how-do-i-edit-my-system-path-in-windows

**Comment by AGoh2019** [comment]
Hi Jens,
Beautify-racket removed, and I learnt something about the Package Manager.
Do you think anybody is interested in writing a Lisp/Racket tutorial on how to use Racket as a AI tool?
--- Andrew Goh
 

    On Saturday, 12 August 2023 at 05:41:49 pm SGT, Jens Axel Søgaard ***@***.***> wrote:  
 
 


@AGoh2019


raco is not a command that is understood by Microsoft Windows. Any other hints?


This means the directory containing Racket executables is not in your path
(the list of directories where the system searches after commands).

The path is stored in an "environment variable" called PATH.
You can set this manually in Windows [1], but there is an easier option.
In the DrRacket menu "Help" there is a menu item "Configure command line for Racket ...".
This will add the directory to your path.

[1] https://www.mathworks.com/matlabcentral/answers/94933-how-do-i-edit-my-system-path-in-windows

**Comment by soegaard** [comment]
> Do you think anybody is interested in writing a Lisp/Racket tutorial on how to use Racket as a AI tool?

This is not the right forum. Ask at https://racket.discourse.group/ instead.

**Comment by gus-massa** [comment]
> Do you think anybody is interested in writing a Lisp/Racket tutorial on how to use Racket as a AI tool?

Definitively yes. 
Definitively you should post it at https://racket.discourse.group/ instead of here.
