### ISSUE TITLE
[Feature Request] `open-input-nowhere`

### ISSUE THREAD

**Issue by LiberalArtist** [racket/racket#4730]
We have `open-output-nowhere` to discard unwanted output &aacute; la `/dev/null`. I often want an analogous way to create empty input ports.

One concrete use-case is running a process with `system*`, e.g.:

```
#lang racket

(parameterize ([current-input-port (open-input-string "")])
  (system* (find-executable-path "ping")
           "-c" "1" "racket-lang.org"))
```

Without `parameterize`ing the `current-input-port`, the program you run will inherit `current-input-port`, which it might not understand, might unexpectedly consume, or might not be supposed to have access to. DrRacket will display a widget in the interactions window for typing input.

As workarounds, `(open-input-string "")` and `(open-input-bytes #"")` aren't bad, but `(open-input-nowhere)` would more clearly communicate intent. It might also provide an opportunity for a more efficient implementation.

**Comment by sorawee** [comment]
The documentation for `make-input-port` actually already gave an implementation for `open-input-nowhere`. Someone who wants to work on this should benchmark how it performs against `(open-input-bytes #"")`.
