### ISSUE TITLE
`module-path?` and `#%require` are stable in intent, but not in fact

### ISSUE THREAD

**Issue by zyrolasting** [racket/racket#4731]
> This issue repeats details I posted in a security advisory on Aug 21st by my calendar. I did not adequately distinguish operational security for volunteers, resource security for services, and implementation security for Racket as a model. The first two are my concern, and are the focus of this particular thread. @mflatt and @samth are already aware of this behavior, and the issue was patched in https://github.com/racket/racket/commit/40d57b0eed0269087a5f481d5019eb96c85284fc

## What version of Racket are you using?
All from 5.3 to the initial release of 8.10

## What program did you run?
```
> (module-path? '...)
#t
> (module-path? 'redex..........)
#t
> (module-path? "x.../...x")
#t
> (module-path? '(lib "...x" "x..."))
#t
> (module-path? '(lib "x..." "x..."))
#f
```

## What should have happened?

[archive]: http://web.archive.org/web/20230521080650/https://docs.racket-lang.org/reference/require.html

I expected this bit from the docs to hold: https://docs.racket-lang.org/reference/require.html ([archive][])

> [...] path elements before than [sic] the last one cannot include a file suffix (i.e., a . in an element other than . or ..) [...]

This is incorrect for most (all?) non-patched Rackets. After the patch, `module-path?` and `#%require` will not accept inputs previously accepted. Before the patch, a path element may end with at least three dots, _except_ the last element.

## Details

**`x...` is not the same as `x___`, or any non-dot substitute for `_`**.

Dots are quantified differently. You can write `x__` but not `x..`, because the latter is not a valid module path. But as long as you have a sequence of allowed characters ending with `...`, you can always append dots to "scope" the natural numbers under any prefix you want, including the empty string. The `...` is conceptually `0` for the purposes of starting a new number line.

Put another way, these are all `0`-equivalent.

* `redex_...`
* `redex__...`
* `redex___...`
* `...`
* `anythinggggggg...`

If you omit the dots, then you cannot know if the author meant to start a number line with another allowed character. But exactly three dots at the suffix cannot help but start a length-based encoding of the natural numbers as dots.

These are also valid `id`-form module paths for expressing ordered pairs of natural numbers.

* `2........`
* `9243..........................................`

I can always add an orthogonal number line by appending dots, but I cannot always prepend an allowed character to do the same. Any existing dots might make that choice invalid.

While this isn't so much a security concern for the purposes of breaking a sandbox, it is a security concern for moderators reviewing user-submitted code for the purposes of package catalog implementations, or `raco setup`. It's not hard to use the dots for a loop invariant that generates hidden directories full of junk during `raco setup`. You could do the same with non-dots, but the abuse becomes less stable. I suggest all moderators or administrators sanitize their user-defined module paths to prevent abuses by appending dots.

p.s. Adding a dimension seems more useful than appending a `2` to a collection name for a breaking change. In fact, this seems like a genuinely useful trick for indexing library collections for the sake of different conventions. But since the behavior is not intended, I report it as an issue.

**Comment by zyrolasting** [comment]
Mods: Since the patch is out, this issue can close after folks in the community had a chance to discuss it.

**Comment by samdphillips** [comment]
Hi @zyrolasting,

Do you have a sequence of steps an end user would need to perform (and maybe a tainted package) to explain the vulnerability?

Cheers,
Sam

**Comment by zyrolasting** [comment]
I wrote an attack on a Racket installation in the security advisory attached to the repository. It's not in a tainted package, but I am willing to write one if that's better for your purposes.

Are you able to see the Security tab at the top of this page?

**Comment by samth** [comment]
I shared the code you posted with @samdphillips privately.

**Comment by samth** [comment]
8.11 includes the fix here, so I'm going to close this now.
