### ISSUE TITLE
[Zuo] `build/command-line*` breaks its own contract

### ISSUE THREAD

**Issue by LiberalArtist** [racket/racket#4732]
This is the documented contract for Zuo's `build/command-line*`:

https://github.com/racket/racket/blob/06f10d51d11ded84df9805578245bfd80391b96a/racket/src/zuo/zuo-doc/zuo-build.scrbl#L499-L502

It promises that the `at-dir` procedure can be called with zero arguments, but the default value, `build-path`, requires at least one argument.

I think a better default would be:
```racket
(lambda args
  (if (null? args)
      "."
      (apply build-path args)))
```

**Comment by mflatt** [comment]
I think this is specifically a documentation bug, because the actual default is `(make-at-dir ".")`.

**Comment by LiberalArtist** [comment]
> the actual default is `(make-at-dir ".")`

In that case, I'm even more confused about this behavior:
```
philip@bastet:/tmp/z$ cat main.zuo 
#lang zuo
(provide-targets targets-at)
(define (targets-at at-dir vars)
  ((make-at-dir "."))
  (alert "Gets here.")
  (at-dir)
  (error "Doesn't get here!"))
philip@bastet:/tmp/z$ zuo 
Gets here.
build-path: wrong number of arguments: [no arguments]
 in targets-at
 in loop
```

**Comment by mflatt** [comment]
Ah, that's an issue with `targets-at`. It's implemented as documented, using `build-path` explicitly, but probably that should be changed to drop the `build-path` argument.

**Comment by LiberalArtist** [comment]
Thanks!
