### ISSUE TITLE
Configure scripts wrongly hard-code statically linked /usr/pkg/lib/libncurses.a on NetBSD

### ISSUE THREAD

**Issue by riastradh** [racket/racket#4734]
**What version of Racket are you using?**
8.10

**What program did you run?**
```
./configure CPPFLAGS=-I/home/riastradh/pkgsrc/current/include\ -I/home/riastradh/pkgsrc/current/include/ncurses LDFLAGS=-L/home/riastradh/pkgsrc/current/lib\ -Wl,-R/home/riastradh/pkgsrc/current/lib
gmake
```

**What should have happened?**
The relevant executables (and libraries) should be dynamically linked against /home/riastradh/pkgsrc/current/lib/libncurses.so, not statically linked against /usr/pkg/lib/libncurses.a (which does not exist here).

**Please include any other relevant details**
NetBSD 9

Fix: Change `/usr/pkg/lib/libncurses.a` to `-lncurses` everywhere.  pkgsrc will automatically supply the correct -L and -Wl,-R flags.

Similar issue for mdinclude in src/ChezScheme/configure -- this should not hard-code `-I/usr/X11R7/include -I/usr/pkg/include -I/usr/pkg/include/ncurses -I/usr/X11R6/include`; this causes trouble and should just be deleted.

**Comment by mflatt** [comment]
I switched the build to use curses instead of ncurses, and that involved `-lterminfo` in addition to `-lcurses`. I think that could be the right change overall, but I'm not certain.
