### ISSUE TITLE
[Feature Request] Sequence contract fast path for vectors, strings, and bytes

### ISSUE THREAD

**Issue by jackfirth** [racket/racket#4744]
**Is your feature request related to a problem? Please describe.**

I have some code that works for any single-valued (as in arity, not length) sequence. I'd like to add some optimized fast paths for common types of sequences, like lists, vectors, strings, and bytes. I don't want callers of the function to have to know about these fast paths. So I'd like something like this:

```scheme
(provide
 (contract-out
  ;; contract uses (sequence/c any/c) to disallow multivalued sequences
  [foo (-> (sequence/c any/c) void?)]))

(define (foo seq)
  (cond
   ;; fast paths for some common sequence types
   [(list? seq) (list-foo seq)]
   [(vector? seq) (vector-foo seq)]
   [(string? seq) (string-foo seq)]
   [(bytes? seq) (bytes-foo seq)]
   ;; slow but works for all sequences
   [else (generic-foo seq)]))
```

But this *only* works for lists. The `(sequence/c any/c)` contract has a fast path for lists to avoid wrapping the sequence, but for other common sequence types, it falls back to just wrapping the sequence with an opaque wrapper. This prevents my code from being able to properly dispatch to the optimized implementations.

**Describe the solution you'd like**

I'd like `(sequence/c any/c)` to have similar special cases for vectors, strings, and bytes as it does for lists since in those cases, there's no need to wrap the input at all.

**Describe alternatives you've considered**

I could avoid using `(sequence/c any/c)` instead of `sequence?`, but then my function has to implement good error messages for multivalued sequences which is irritating. I could also expose the special-case versions of the function directly to users, but that explodes the API surface. It's much simpler for users if they just have one function and it picks a fast implementation automatically.

I could also write `(or/c list? string? vector? bytes? (sequence/c any/c))` instead of just `(sequence/c any/c)`. But then I have to list out every single-valued sequence type manually. It also introduces the possibility of writing an incorrect contract like `(orc/ list? string? hash? vector? (sequence/c any/c))`, since hashes aren't single-valued sequences.

**Do you want to contribute to this feature**

I could give it a shot, if @rfindler doesn't get to it first. I'm pretty sure [this code](https://github.com/racket/racket/blob/e2964e246243f0ab56595c92462f6dbd576c48eb/racket/collects/racket/sequence.rkt#L205-L307) is where the changes would go.

**Additional context**

There are tons of functions in my [rebellion](https://github.com/jackfirth/rebellion) package that accept `(sequence/c any/c)` arguments, so this has a lot of potential to speed things up there.

**Comment by rfindler** [comment]
Thanks for the clearly written, comprehensive issue. With this head start, I should be able to push something soon.
