### ISSUE TITLE
broken error message context in 'rest' underneath '(in-list ...)' suggests deeper problem

### ISSUE THREAD

**Issue by jbclements** [racket/racket#4780]
**What version of Racket are you using?**
 8.10.0.4--2023-09-15

**What program did you run?**
#lang racket/base

(for/list ([x (in-list '())])
  rest)

**What should have happened?**

Should have gotten the error message

rest: unbound identifier in: rest

**If you got an error message, please include it here.**

rest: unbound identifier
  context...:
  other binding...:
  common scopes...: in: rest

Also, in the error ribbon at the bottom:

zz.rkt:4:2: rest: unbound identifier
  in: rest
  context...:
   #(697320 module) #(697323 module anonymous-module) #(697335 local)
   #(697336 intdef) #(697338 intdef-outside) #(697339 intdef)
   #(697359 intdef) #(697364 local) #(697365 intdef) #(697368 local)
   #(697369 intdef) #(697371 local) #(697372 intdef) [common scopes]
  other binding...:
   local
   #(-684 use-site) #(-384 module for) #(-381 module) #(697343 macro)
   [common scopes]
  common scopes...:
   #(697346 local) #(697347 intdef) #(697353 local) #(697355 local)
   #(697356 intdef) #(697358 local)
  #(52 4)

**Please include any other relevant details**
e.g., the operating system used or how you are running the code.

**Comment by usaoc** [comment]
This seems to be the expected error to me.  For comparison, consider this minimal program:

```racket
#lang racket/base
(require (for-syntax racket/base))

(define-syntax (some-macro stx)
  (syntax-case stx ()
    [(_ expr)
     #'(let ([some-introduced-id #f])
         expr)]))

(some-macro some-introduced-id)
```

which leads to a similar error (with less scopes, so less confusing?):

```racket
; /tmp/test.rkt:10:12: some-introduced-id: unbound identifier
;   in: some-introduced-id
;   context...:
;    #(17716 use-site) #(17722 intdef) [common scopes]
;   other binding...:
;    local
;    #(17715 macro) [common scopes]
;   common scopes...:
;    #(17666 module) #(17669 module test) #(17719 local) #(17720 intdef)
;    #(17721 local)
```

The reason for such an error is that a `rest` identifier is introduced by the expansion of `in-list`, which has an incompatible set of scopes than the use-site `rest`.

**Comment by mfelleisen** [comment]
@jbclements did you expect an unbound-id error not to show up because the loop never iterates? Or did you mean to include `(require racket/list)` and bind `rest`?

**Comment by shhyou** [comment]
A guess: an unbound error without the scopes part that exposes internal implementation. Something like
```diff
  #lang racket/base
- (require (for-syntax racket/base))
+ (require (for-syntax racket/base syntax/parse))

  (define-syntax (some-macro stx)
-   (syntax-case stx ()
+   (syntax-parse stx
      [(_ expr)
+      #:with (some-introduced-id) (generate-temporaries '(some-introduced-id))
       #'(let ([some-introduced-id #f])
           expr)]))

  (some-macro some-introduced-id)
```
