### ISSUE TITLE
Unable to Type Square Brackets in DrRacket on Windows 11 Home Version 21H2

### ISSUE THREAD

**Issue by a-srij** [racket/racket#4785]
**What version of Racket are you using?**
e.g., 7.7 [cs]

Version 8.10. (current version as of typing).

**What program did you run?**
Please include a short example that triggers the bug

I was running the program called "DrRacket", and the output does work for the following Racket/Racklog code, but after the `()` just after `%rel`, I am unable to type the square brackets [] when I pressed either the [ or ] on my keyboard. Note: my keyboard (itself) may have nothing to do with this as I can type them in Notepad, URL bar, Google searches, etc. I also don't know if it's either DrRacket or my operating system that I'm on:

![image](https://github.com/racket/racket/assets/147218847/0acf7bd3-22cf-49d7-b452-9329a9283d1f)

**What should have happened?**

I would have expected the square brackets to appear after I pressed that key on my keyboard.

**If you got an error message, please include it here.**

There is no error message.

**Please include any other relevant details**
e.g., the operating system used or how you are running the code.

Windows 11 Home Version 21H2 (OS Build 22000.1817).

My issue persists, even with "Enable automatic parentheses, square brackets, and quotes" enabled or disabled.

**Comment by rfindler** [comment]
What kind of keyboard do you have (from which country)? Relatedly, are modifier keys required to type [] on your keyboard?

Do you have the preference enabled that turns [] into () in a context-sensitive way? It is called "Automatically adjust opening square brackets" and can be found at the bottom of the "Square Bracket" pane inside the "Editing" pane, inside the preferences window (which should be found near the bottom of the "Edit" menu).

**Comment by a-srij** [comment]
I'm using a Microsoft keyboard from and in New Zealand. I'm unsure about 'modifier keys'. I found the setting 'Automatically adjust opening square brackets' was enabled in DrRacket. Disabling it solved my problem only regarding the Racklog. It works well with the Racket language when enabled. Thank you.

**Comment by rfindler** [comment]
Glad it is fixed! 

When that preference is enabled, the thought is that you don't need to use the shift key to code. As most of the time you're doing `()`, those `[]` turn into `()`. But, it is context sensitive, so sometimes, it'll change them into `[]` for you, eg, if you typed `[let [[x [+ 1 1]]] [+ x x]]`, you'll get `(let ([x (+ 1 1)]) (+ x x))`. But maybe you know that already!

Anyway, to override it, you can type control-[ (or maybe it is alt-[ on windows? I'm not sure but you can find out by going to Edit|Keybindings|Show Active Keybindings and searching.

As for modifier keys, on some non-US keyboards, there are additional keys like shift and control and alt that get used to enter what are unshifted keys on a US keyboard. Sometimes that's caused problems in the past for folks under windows. Sounds like that wasn't the issue this time, tho!
