### ISSUE TITLE
SSL test failure

### ISSUE THREAD

**Issue by samth** [racket/racket#4787]
The `tests/openssl/test-secure` test recently started failing. http://drdr.racket-lang.org/64811/cs/pkgs/racket-test/tests/openssl/test-secure.rkt

It also fails locally for me, with a similar error. The relevant websites still behave as expected in Firefox for me.

**Comment by sorawee** [comment]
This is no longer failing, so it seems like a temporary failure, perhaps from the site configuration. OK to close?
