### ISSUE TITLE
Release Regressions for v8.11

### ISSUE THREAD

**Issue by jbclements** [racket/racket#4791]
Current Release vs Next Release
--------------------------------------------

### Test Failures
- [x] quickscript-test https://plt.cs.northwestern.edu/release-pkg-build/server/built/test-fail/quickscript-test.txt
- [x] sci https://plt.cs.northwestern.edu/release-pkg-build/server/built/test-fail/sci.txt
- [x] zeromq-r https://plt.cs.northwestern.edu/release-pkg-build/server/built/test-fail/zeromq-r.txt
### Other Failures
- [x] video-v0-0

**Comment by usaoc** [comment]
All listed build failures have been resolved after the update to Typed Racket.

**Comment by samth** [comment]
I've updated the description with the current status. There are 3 test failures:
- `sci` I believe is because libgfortran is not available on the release pkg build machine
- `zeromq-r` is a timeout we've seen before
- `quickscript-test` is a failure I have not previously seen. @Metaxal any thoughts?

**Comment by Metaxal** [comment]
Re. quickscript-test, I can't find a commit that matches the checksum 87e0f0e4d9a74124b15228af16e231154cbc4c8d as reported from the log file above. I there a way to find this out?

I've been trying a few different things to attempt to fix the recurring `poll-until` failures (without success). I think this error has appeared at some point, but should have been fixed.

**Comment by Metaxal** [comment]
It's okay to remove quickscript-test from the release, as I'm not sure I'll be able to fix the race conditions in time, but can we keep it on DrDr so I can continue to try things out? (since I can't reproduce the issues on my machine)

**Comment by soegaard** [comment]
Sam:
- sci I believe is because libgfortran is not available on the release pkg build machine

Is the environment for the release build different from the standard one?
Currently, the docs for sci/flomat looks fine:

    https://docs.racket-lang.org/manual-flomat/index.html

Are there VMs for download for the standard/release build to experiment on?
[Maybe there is a newer libgfortran now?]

**Comment by samth** [comment]
I don't think there's any need to remove anything from the release. It's just good to confirm that those particular test failures are not regressions that imply a problem somewhere else.

**Comment by Metaxal** [comment]
Okay. The problems are only in the tests AFAICT, not in Quickscript per se.

**Comment by jbclements** [comment]
To add some context: the script here notices when something goes from good to bad. quickscript-test went from passing-tests to not-passing-tests here. The only consequence of this is that if quickscript-test is failing tests in the next release, we/you won't get any notice of it. If quickscript-test is passing all its tests in the next release, it will "go back to" being in the good books and if it then starts failing again we'll get a notice of it.

**Comment by samth** [comment]
Two of the three test failures are now gone.

**Comment by soegaard** [comment]
@samth 
>  sci I believe is because libgfortran is not available on the release pkg build machine

I looked at sci (flomat) again. The info file has:
```
(define deps       '("base"
                     ; The shared libraries
                     ("linux-shared-libraries"  #:platform "x86_64-linux-natipkg")))
```
and `linux-shared-libraries"` has the shared libraries that the build server needs:

https://github.com/soegaard/linux-shared-libraries/tree/master/flomat-x86_64-linux-natipkg
https://github.com/soegaard/sci/blob/master/flomat/info.rkt

**Comment by jbclements** [comment]
@soegaard I'm probably confused here, but it looks to me like the `sci` failure is no longer occurring. It appears to me you're observing that `sci` was not failing due to a missing gfortran library, which is (I believe) consistent with the fact that it's no longer failing tests. I don't have any idea what *was* causing the failure... but it's checked off now, so I'm not going to worry about it. Does that sound reasonable?

**Comment by jbclements** [comment]
Also, per the earlier conversation with @Metaxal , I'm going to check the box for quickscript-test; it's not passing, but I don't believe it should hold up the release.

**Comment by jbclements** [comment]
Also, the only thing that's stored in my brain vis a vis the video-0-0 failure is that it always occurs, and ... maybe gets fixed after the release with an exception? ... so it shouldn't block the release. @LeifAndersen , does that sound right to you?

**Comment by samth** [comment]
I believe nothing ever gets fixed about `video-0-0` and @LeifAndersen has not responded about it.

**Comment by soegaard** [comment]
@jbclements I am the one that's confused. I didn't realize that the problem went way.

**Comment by jbclements** [comment]
I'm checking off `video-0-0`, not letting it block the release. also closing this issue, feel free to re-open.
