### ISSUE TITLE
something that should not match ... 

### ISSUE THREAD

**Issue by n-ai-up8-edu** [racket/racket#4792]
**What version of Racket are you using?**
8.7

**What program did you run?**
(match '(1) ['() "nok"][_ "ok"])
(match '() [empty "nok"][_ "ok"])
(match '(1) [empty "nok"][_ "ok"])
(match '(1 2) [empty "nok"][_ "ok"])

**What should have happened?**
"ok"
"nok"
"nok"
"nok"

**If you got an error message, please include it here.**

**Please include any other relevant details**
seems that empty as pattern is matching with everything... is it normal ?

**Comment by capfredf** [comment]
the way you use `empty` in your example(s) introduces a variable named `empty` in each clause. As a pattern, it matches anything. 
If you want to check if something is **equal** to `empty`, you need to do something like
```
(match '(1 2) [(? (lambda (x) (eq? x empty))) "nok"][_ "ok"])
```

**Comment by n-ai-up8-edu** [comment]
Of course ! Not a bug. Sorry. Thx.
