### ISSUE TITLE
Contracts break pattern matching

### ISSUE THREAD

**Issue by Tuplanolla** [racket/racket#4799]
**What version of Racket are you using?**
I used every version from `8.3 [cs]` to `8.6 [cs]`.

**What program did you run?**
I ran the following program.

``` racket
#lang racket/base

(require racket/contract)
(require racket/match)

(define (explain obj)
  (match obj
    ((box int) (format "just ~a" int))
    (#f "nothing")
    (_ "something else")))

(define/contract (explain/contract obj)
  (-> (or/c #f (box/c exact-integer?)) string?)
  (explain obj))

(displayln (explain (box 3)))
(displayln (explain #f))
(newline)
(displayln (explain/contract (box 3)))
(displayln (explain/contract #f))
```

**What should have happened?**

The program should have printed

```
just 3
nothing

just 3
nothing
```

but it actually printed

```
just 3
nothing

just #&3
nothing
```

violating the expected invariant `(not (equal? obj int))`
in the first clause of `match` in the body of `explain`.

**Comment by sorawee** [comment]
The problem is https://github.com/racket/racket/blob/master/racket/collects/racket/match/compiler.rkt#L103. It uses `unsafe-unbox*`, which doesn't work on impersonators.

@samth, is there anything better than changing it to regular `unbox`?

**Comment by samth** [comment]
Yes, the fix is just removing the *. (note the small error in the return type in the docs for unsafe-unbox).
