### ISSUE TITLE
[Feature Request] Trailing `cond` statements are confusing

### ISSUE THREAD

**Issue by abhillman** [racket/racket#4822]
**Is your feature request related to a problem? Please describe.**

<img width="606" alt="cond-syntax" src="https://github.com/racket/racket/assets/1097794/ed91c7f2-564c-42fb-81f2-3bb24d4665ff">

[Link to `cond` documentation](https://docs.racket-lang.org/reference/if.html#%28form._%28%28lib._racket%2Fprivate%2Fletstx-scheme..rkt%29._cond%29%29)

I find the implementation a bit confusing:
  * a trailing `cons` is strictly evaluated, but all other expressions are lazily evaluated
```
> (cond [#f 1] (cons #t 10) (else 9))
10
> (cond [#f 1] ((lambda () (pair (#t 2)))))
#<procedure:c1>
```
  * a trailing `cons` is allowed, but a pair literal is not
  * trailing expressions can be provided, but neither an `id` nor a literal can
  * when evaluation of `test-exprs` is exhausted, the first trailing expression is returned, which differs from the behavior of non-special forms

Here is a cursory study of `cond` behavior:

**I. `cond` with a trailing literal**
```racket
> (cond [(not #f) 1] 2)
string:1:19: cond: bad syntax (clause is not a test-value pair)
  at: 2
  in: (cond ((not #f) 1) 2)
 [,bt for context]
```

**II. `cond` with a trailing expression**
```racket
> (cond [(not #f) 1] (display 1))
1
```

**III. `cond` with a trailing `cons` expression that produces a `pair`**
```racket
> (cond [#f 1] (cons #t 1))
1
```

**IV. `cond` with a trailing expression that also produces a `pair`**
```racket
> (define (make-cond-pair) (cons #t "from cond pair"))
> (make-cond-pair)
'(#t . "from cond pair")
> (cond [#f 1] (make-cond-pair))
#<procedure:make-cond-pair>
```

**V. `cond` with a trailing literal that produces a `pair`**
```racket
> (cond [#f 1] '(#t 1))
string:1:13: quote: bad syntax
  in: quote
 [,bt for context]
```

**VI. `cond` with an `id`**
```racket
> (define a-test-pair (cons #t "test pair right sie"))
> (cond [#f 1] a-test-pair)
string:1:13: cond: bad syntax (clause is not a test-value pair)
  at: a-test-pair
  in: (cond (#f 1) a-test-pair)
 [,bt for context]
```

**VII. `cond` with >1 trailing expression**
```
> (define t 1)
> (cond [#t 1] (+ t 9) (display 123))
1
> (cond [#f 1] (+ t 9) (display 123) (+ t 1000))
9
> (cond [#f 1] (+ t 9) (+ t 1000))
9
```

**Describe the solution you'd like**
I'd have to think about it more. I'm not really sure right now.

**Describe alternatives you've considered**
There are certain things that one "just needs to learn" in the early days of learning a language. Moreover, changes  could break existing code (but could perhaps be considered in a future major release).

**Do you want to contribute to this feature**
Sure, I would love to

**[Optional] Additional context**

```
$ racket --version
Welcome to Racket v8.9 [cs].
```

Some of Common Lisp's `cond` behavior, which has similarities:
```
[3]> (cond ((> 3 4) "variant 1")
      12)

*** - COND: clause 12 should be a list
The following restarts are available:
ABORT          :R1      Abort main loop
Break 1 [4]> ABORT
[5]> (cond ((> 3 4) "variant 1")
      (+ 1 2))
2
[6]> (cond ((> 3 4) "variant 1")
      (+ 1 2) (+ 3 4))
2
```

My guess of the rough current algorithm:
1. during compile phase
  * check that no literals are provided to `cond`
2. during evaluation phase
  * eagerly evaluate all `cons`
  * evaluate all _`test-exprs`_; if exhausted, return the first trailing s-expr

**Comment by abhillman** [comment]
Ah -- I see this now, which does in fact document this behavior:

<img width="565" alt="image" src="https://github.com/racket/racket/assets/1097794/81449b46-cfbf-42f6-ba80-cd897c2cfed9">

Source: https://docs.racket-lang.org/reference/if.html#%28form._%28%28lib._racket%2Fprivate%2Fletstx-scheme..rkt%29._cond%29%29

**Comment by sorawee** [comment]
In Racket, parentheses and brackets are interchangeable. So your "trailing expression" is actually not treated as an expression. Consider one of your examples:

```
(cond [#f 1] ((lambda () (pair (#t 2)))))
```

is equivalent to:

```
(cond [#f 1] [(lambda () (pair (#t 2)))])
```

which matches the `[test-expr]` clause. Since the first conditional is false, the second branch is considered. `(lambda () (pair (#t 2)))` is evaluated, resulting in a function value, which is truthy. It is therefore the evaluation result of the whole `cond`.

Does this clarify your confusion? If so, I will close the issue.

**Comment by abhillman** [comment]
Yes! That does in fact solve the riddle of "why does this seem inconsistent." That said, it still can be a bit tricky.

Perhaps the fact that `[` _does_ have a connotation but does not have a _meaning from the POV of the compiler_ is kind of confusing.

I would suggest that Clojure's way here may be less confusing; perhaps it could be adopted in a future major release? That said, I could imagine this could be a big discussion.

```
Clojure 1.11.1
user=>        (let [x 1] x)
1
user=>        (let (x 1) x)
Syntax error macroexpanding clojure.core/let at (REPL:1:1).
(x 1) - failed: vector? at: [:bindings] spec: :clojure.core.specs.alpha/bindings
```

**Comment by abhillman** [comment]
Probably the best solution I can think of is actually using a linter like https://github.com/Bogdanp/racket-review -- if that is considered idiomatic; which would have warned about the above potential issue.

**Comment by sorawee** [comment]
Yes, I think this is best addressed by linting. Alternatively, you can use a Racket code formatter, which converts parens to brackets for `cond` clauses, to help spotting the issue:

```
$ cat test.rkt
#lang racket

(define (do-thing) 123)
(cond [...] (do-thing) (error "bla bla"))
$ raco fmt -i test.rkt
$ cat test.rkt
#lang racket

(define (do-thing)
  123)
(cond
  [...]
  [do-thing]
  [error "bla bla"])
```

**Comment by sorawee** [comment]
One note on bracket vs paren: in Scheme, `cond` clauses are usually written with all parens. Racket diverges from Scheme by encouraging people to use brackets instead. Since a Scheme program is kind of a Racket program, we don't want to _mandate_ that users need to use brackets in the language itself. 

But a linter could warn that a `cond` clause uses parens, which is not Racket-y. Or if the linter wants to support Scheme code, it might only report problems when there's a mix of parens and brackets. Perhaps @Bogdanp might have more thoughts.

**Comment by abhillman** [comment]
Thank you!
