### ISSUE TITLE
Inconsistent behavior of `error-value->string-handler`

### ISSUE THREAD

**Issue by usaoc** [racket/racket#4828]
I have some confusion regarding the behavior of `error-value->string-handler`, or more precisely the way it is used across implementations.  For example, the docs seems to imply that `error-value->string-handler` is always called with `print-unreadable` parameterized to true, but this is not the case.

```racket
#lang racket/base
(define unreadable
  (let ()
    (struct unreadable ())
    (unreadable)))

(parameterize ([error-value->string-handler
                (lambda (v _)
                  (format "~s" v))]
               [print-unreadable #f])
  (with-handlers ([exn:fail:contract? exn-message])
    (raise-arguments-error 'test "unreadable"
                           "value" unreadable)))
```

This program fails with “`format`: printing disabled for unreadable value” on CS, but *not* on BC.  Upon closer inspection, BC also behaves differently regarding the result of `error-value->string-handler` (it accepts a byte string, somehow?).  For example,

```racket
#lang racket/base
(define unreadable
  (let ()
    (struct unreadable ())
    (unreadable)))

(parameterize ([error-value->string-handler
                (lambda (v _)
                  (string->bytes/utf-8 (format "~s" v)))]
               [print-unreadable #f])
  (with-handlers ([exn:fail:contract? exn-message])
    (raise-arguments-error 'test "unreadable"
                           "value" unreadable)))
```

this program very mysterious gives “`string-append`: contract violation” as the exception message on CS (it also comes from `fail-unreadable`, I think), but *not* on BC.  This is very wild.  What is even wilder is that the CS behavior disappears if the parameterization of `print-unreadable` is removed.

What I think is that maybe a guard should be attached to `error-value->string-handler` (through `make-derived-parameter`), so that user-supplied `error-value->string-handler` can be checked and protected in the specified manner.  Moreover, the behavior should be unified, probably with CS as the main priority.

**Comment by mflatt** [comment]
I can see how a guard on the parameter could make sense, but I think sufficient to just bring CS in line with BC, which mostly means fixing the calls to the parameter value from built-in functions like `error`.
