### ISSUE TITLE
OpenBSD 8.11: Copying with merge collects. Error: undoing changes... copy-file: destination exists

### ISSUE THREAD

**Issue by juanfra684** [racket/racket#4838]
I'm trying to update the OpenBSD-current port to 8.11 using the usual options but it fails with an error in `make install`:

```plain
Copying share -> /usr/ports/pobj/racket-minimal-8.11/fake-amd64/usr/local/share/racket
Copying doc -> /usr/ports/pobj/racket-minimal-8.11/fake-amd64/usr/local/share/doc/racket
  missing source path "doc", skipping...
Copying etc -> /usr/ports/pobj/racket-minimal-8.11/fake-amd64/etc/racket
Copying with merge collects -> /usr/ports/pobj/racket-minimal-8.11/fake-amd64/usr/local/share/racket/collects
*** Error: undoing changes...
copy-file: destination exists
  source path: /usr/ports/pobj/racket-minimal-8.11/racket-8.11/src/cs/c/compiled/usr/ports/pobj/racket-minimal-8.11/racket-8.11/collects/acks/compiled/acks_rkt.dep
  destination path: /usr/ports/pobj/racket-minimal-8.11/fake-amd64/usr/local/share/racket/collects/acks/compiled/acks_rkt.dep
  context...:
   /usr/ports/pobj/racket-minimal-8.11/racket-8.11/collects/setup/unixstyle-install.rkt:172:2: loop
   [repeats 2 more times]
   /usr/ports/pobj/racket-minimal-8.11/racket-8.11/collects/setup/unixstyle-install.rkt:219:0: cp*
   /usr/ports/pobj/racket-minimal-8.11/racket-8.11/collects/setup/unixstyle-install.rkt:481:5: loop
   /usr/ports/pobj/racket-minimal-8.11/racket-8.11/collects/setup/unixstyle-install.rkt:469:0: move/copy-tree
   /usr/ports/pobj/racket-minimal-8.11/racket-8.11/collects/setup/unixstyle-install.rkt:583:2
   body of (submod "/usr/ports/pobj/racket-minimal-8.11/racket-8.11/collects/setup/unixstyle-install.rkt" main)
   body of "/usr/ports/pobj/racket-minimal-8.11/racket-8.11/collects/setup/main.rkt"
failed
 in build-one
 in loop
 in module->hash
gmake: *** [Makefile:23: install] Error 1

```
[This is the full log](https://github.com/racket/racket/files/13453842/racket-811.txt). Racket 8.10 builds fine with the same options.

**Comment by shhyou** [comment]
I believe a patched release, v8.11.1, is on its way. Meanwhile, you can temporarily work around the issue using the commit linked in #4825.

**Comment by LiberalArtist** [comment]
I thought #4825 was specific to the "source with built packages" release distribution, but I would guess the OpenBSD port would be building from source without pre-built packages.

**Comment by LiberalArtist** [comment]
> @LiberalArtist we use the builtpkgs tarball. When I started to maintain the port, the builtpkgs tarball or racket-minimal didn't exists, so everything was built from source. I changed the port to builtpkgs when it was available and it saved like 3 hours on our faster amd64 machines. And then I moved the port from a full racket distribution to just racket-minimal, so the users don't need to install all the dependencies if they just want a server or a cli program.

You may find that the difference in compile time from "built packages" is less significant with the minimal distribution, since there is much less Racket code. ("Built packages" is somewhat of a misnomer for minimal Racket: essentially all of the what's pre-built is the `racket/collects` directory in this repo.)
