### ISSUE TITLE
Printing of extflonum differs between Racket CS and BC

### ISSUE THREAD

**Issue by sorawee** [racket/racket#4859]
**What version of Racket are you using?**
8.11

**What program did you run?**

```
1.0t2
```

**What should have happened?**

- In Racket CS, this outputs: `1.0t2`
- In Racket BC, this outputs: `100.0t0`

**If you got an error message, please include it here.**

N/A

**Please include any other relevant details**

N/A

**Comment by AlexKnauth** [comment]
I thought Racket CS didn't support extflonums

**Comment by shhyou** [comment]
What is the value of [`(extflonum-available?)`](https://docs.racket-lang.org/reference/extflonums.html#%28def._%28%28lib._racket%2Fextflonum..rkt%29._extflonum-available~3f%29%29)?

**Comment by sorawee** [comment]
Ah, I see. So this is the expected behavior.
