### ISSUE TITLE
[bc] (banner) produces an internal value

### ISSUE THREAD

**Issue by sorawee** [racket/racket#4870]
**What version of Racket are you using?**
8.11.1.7-20231216-396fa983c4 [bc]

**What program did you run?**

```
(banner)
```

with Racket installed from https://users.cs.utah.edu/plt/snapshots/current/installers/racket-8.11.1.7-x86_64-macosx-bc.dmg

**What should have happened?**

It should produce a string. Instead, it produces: `#<unary-application-code>`.

**If you got an error message, please include it here.**

N/A

**Please include any other relevant details**

Interestingly, I cannot reproduce this problem when building Racket BC from source. But commit 396fa983c4 is indeed the latest version that touches the banner change.

CC: @jryans and @mflatt

**Comment by mflatt** [comment]
I think the issue is that the banner is created at a point where allocation is place-local, but the string is recorded in a place-spanning root. I didn't detect this on my machine, because it BC builds without places on AArch64.

**Comment by jryans** [comment]
Ah hmm, I will try to work out what's happening here. I didn't notice this while working on `banner` from my Intel Mac, but perhaps there are further conditions involved in triggering this...?

**Comment by sorawee** [comment]
Matthew fixed it in 2f0f7657967b327590873404e9057bd9174a2eb7, I think. So this can be closed now.
