### ISSUE TITLE
Release Regressions for v8.12

### ISSUE THREAD

**Issue by jbclements** [racket/racket#4898]
Current Release vs Next Release
========================================
>>> fetching https://pkg-build.racket-lang.org/summary.rktd 
>>> fetching https://plt.cs.northwestern.edu/release-pkg-build/summary.rktd

### Build Failures
- [x] redex-etc https://plt.cs.northwestern.edu/release-pkg-build/server/built/fail/redex-etc.txt

#### Network failure 
- [x] cbor https://plt.cs.northwestern.edu/release-pkg-build/server/built/fail/cbor.txt
- [x] r16 https://plt.cs.northwestern.edu/release-pkg-build/server/built/fail/r16.txt
- [x] racket-glossary https://plt.cs.northwestern.edu/release-pkg-build/server/built/fail/racket-glossary.txt 
- [x] raco-exe-multitarget https://plt.cs.northwestern.edu/release-pkg-build/server/built/fail/raco-exe-multitarget.txt
- [x] sudoku-solver https://plt.cs.northwestern.edu/release-pkg-build/server/built/fail/sudoku-solver.txt
- [x] todo-txt https://plt.cs.northwestern.edu/release-pkg-build/server/built/fail/todo-txt.txt
- [x] unmozlz4 https://plt.cs.northwestern.edu/release-pkg-build/server/built/fail/unmozlz4.txt
- [x] zstd https://plt.cs.northwestern.edu/release-pkg-build/server/built/fail/zstd.txt

### Test Failures
- [x] rascas https://plt.cs.northwestern.edu/release-pkg-build/server/built/test-fail/rascas.txt
- [x] crypto-test https://plt.cs.northwestern.edu/release-pkg-build/server/built/test-fail/crypto-test.txt
- [ ] process-queue https://plt.cs.northwestern.edu/release-pkg-build/server/built/test-fail/process-queue.txt
- [x] timable https://plt.cs.northwestern.edu/release-pkg-build/server/built/test-fail/timable.txt

### Other Failures
- [ ] video-v0-0

**Comment by rfindler** [comment]
Assuming I found [the right repo](https://github.com/Metaxal/rascas/tree/HEAD), it hasn't changed in 10 months but I'm confused because the checksum in the build failure transcript is `9df641129d04f750ae9f511ff8125d9aca7e2279` but that's not the latest commit nor the checksum on pkgs.racket-lang.org (which are both `f575e5a63b02358e80bfde53c7cb3eaae396e41a`)

**Comment by samth** [comment]
Most of these are because SourceHut is down because of a DDOS. The redex-etc one is odd; does it really pass on 8.11?

**Comment by jbclements** [comment]
Okay, so it turns out that many of the failing packages here are hosted at sourcehut, which is in the midst of a *really major* three-day DDOS attack. https://fosstodon.org/@drewdevault/111738819188358936

**Comment by shhyou** [comment]
> Most of these are because SourceHut is down because of a DDOS. The redex-etc one is odd; does it really pass on 8.11?

It might be related to racket/redex@1744e8c7c905c99c8846b59e505f35ef80685a3f

**Comment by rfindler** [comment]
It looks like folks were requiring private parts of the redex implementation (I really wish that wasn't possible) to use the parameter that I removed. I've brought it back so hopefully that'll solve that.

**Comment by samth** [comment]
@rfindler that checksum is from the archiving process, I believe, so I think it won't usually be the same as the one on pkgs.

**Comment by sorawee** [comment]
The problem with rascas is due to `for/fold`'s change (#4845):

https://github.com/Metaxal/rascas/blob/master/letstar.rkt#L95-L97

Prior 8.12, `new-bindings` in the for clause refers to the variable outside `for/fold`. After 8.12, it refers to the accumulator.

**Comment by sorawee** [comment]
```
#lang racket

(define a '(1 2 3))

(for/fold ([a '()]
           #:result (reverse a))
          ([x (in-list a)])
  (println 'hello)
  (cons x a))
```

prints no "hello", and results in `'()`.

But without `#:result`:

```
#lang racket

(define a '(1 2 3))

(for/fold ([a '()])
          ([x (in-list a)])
  (println 'hello)
  (cons x a))
```

prints "hello" three times, with `'(3 2 1)` as the result.

**Comment by sorawee** [comment]
> It looks like folks were requiring private parts of the redex implementation (I really wish that wasn't possible) to use the parameter that I removed. I've brought it back so hopefully that'll solve that.

I think that if a package depends on a private part of Racket, and it's broken due to a change in the private part, there should be no need to "support" it. Of course, we could use our own judgment to support it in some cases as we see fit, but this should not be a general policy. In the case where we won't support it, we obviously should try to contact the package authors to let them know of the upcoming change.

**Comment by samth** [comment]
@camoy is the author of redex-etc so maybe he has some input.

**Comment by rfindler** [comment]
I don't think that parameter does anything. Its value is always 0. So he
could just remove it from the addition expression it is in.

(Or maybe explain why I am wrong about it!)

**Comment by samth** [comment]
@camoy's code looks like it was copied and adjusted from the redex code, which is probably why it ended up referencing compact-vertical-min-width.

**Comment by camoy** [comment]
A lot of the code in `redex-etc` is old stuff that I needed to adjust the typography for a specific paper. Most of the stuff that relies on private identifiers was undocumented and probably should've been quite in a separate repo in the first place... I've just removed it.

**Comment by samth** [comment]
Almost everything is fixed now, but there's a new test failure in `crypto-test`.

**Comment by jbclements** [comment]
@Metaxal any chance you can check to see that the rascas test failure is addressed by the repair to for/fold? I'm glad to hear that the system is working the way it should. It would be awesome to figure out what the issue is with crypto-test is, too.

**Comment by samth** [comment]
Is there a new build with the for/fold fix already? I presume when that happens we will get a new pkg build run as well.

**Comment by sorawee** [comment]
> Is there a new build with the for/fold fix already? I presume when that happens we will get a new pkg build run as well.

I don't think so. Even the current snapshots don't include the repair commit yet.

> @Metaxal any chance you can check to see that the rascas test failure is addressed by the repair to for/fold? I'm glad to hear that the system is working the way it should. It would be awesome to figure out what the issue is with crypto-test is, too.

Not @Metaxal, but I have my Racket built from source, and can confirm that with the fix, all tests in rascas passed.

**Comment by jbclements** [comment]
started build... it's going to be days before we get a pkg-build-diff result, though. @sorawee your checking is good enough for me.

**Comment by Metaxal** [comment]
I'm away from my laptop, but I trust @sorawee 's test :) Thank you!

Tangentially, I find it surprising that rascas is the only package that caught this bug :thinking: 
IIUC, probably a test for [define/for/fold](https://github.com/Metaxal/bazaar/blob/master/loop.rkt#L31) should have caught it, but that's what I get for not writing proper tests…
Apparently, mischief also has a [define/for/fold](https://github.com/carl-eastlund/mischief/blob/stable/mischief/for.rkt#L426) which presumably should have caught the failure but I also can't find the tests for this form. (pfew, that's not only me :sweat_smile: )

**Comment by jbclements** [comment]
I think I like this change, but I'm definitely not unbiased. And now that I think about it, I have a question. IIUC, the pkg-build-diff code looks for things that "worked in the old release, but don't work in the new release." So my question is this: crypto-test is currently in the "Failing Tests" category. Suppose I pushed a change to this library that broke it so badly that it no longer compiles in either the previous release or the candidate release? Would it disappear from the pkg-build-diff list entirely?

**Comment by samth** [comment]
Yes, it would disappear entirely. 

Also, the diff computed here does not look at the snapshot pkg-build. The tool also computes that and we might want to look at it sooner but the release process doesn't use it.

**Comment by samth** [comment]
With the newest build, rascas now succeedes but there's a new test failure for process-queue by @LLazarek

**Comment by rfindler** [comment]
> I think I like this change, but I'm definitely not unbiased.

Let's keep it. But I think I need a little more help from the release manager. Currently, the predicate for whether or not we're in "release mode" is (in bash notation):

```
if [ `git branch -r | grep origin/release | wc -l` = "1" ]
```

but this is probably going to be turned on too long since, once we have sorted out the pkg regressions, we'll want penghu to switch back out of release mode.

Would it be possible to have some other mechanism to know that penghu should be in release mode?

**Comment by jbclements** [comment]
I can't think of an existing signal that indicates that we're in testing rather than free-merging mode. It would be easy to create one, e.g. by creating a priority-testing branch and then deleting it, for instance. Thoughts?

**Comment by rfindler** [comment]
Now that I think about, at what step do we stop looking at the release pkg build results? I guess I don't know how that part of the release works.

As to your actual question, there is, of course, the "email robby" signal. Or if you wanted to just put a file on the web somewhere that I can query that would also work if that's easier. A dummy branch is also fine, of course.

**Comment by jbclements** [comment]
A dummy branch seems easier than having you write code to check for a file at a URL, no? 

WRT your first question:
(1) the checklist only currently suggests that we look at the diff *once*, just after the initial build.
(2) In this release, we've definitely looked repeatedly, in order to see whether the problems have gone away.
(3) Even when we turn the signal (whatever it winds up being) off, this just means that it drops back to standard priority, right? I think the problem we're trying to solve is just the potentially long gap between the initial build and the first run of the pkg build, and (secondarily) the potentially long wait to see whether a given fix is reflected in the pkg-build-diff results. Honestly, I think that the second one is not nearly as important as the first.

**Comment by sorawee** [comment]
Re process-queue: it's very weird in my testing.

With Racket 8.11.1, the tests always passed with `raco test --jobs 1 --drdr .`. However, there are a lot of failures in non drdr mode, and these failures are flaky (sometimes they occurred, and sometimes they didn't).

With the release candidate, `raco test --jobs 1 --drdr .` surfaces flaky tests and there are more failures as well. Non drdr mode also see these flaky failures.

**Comment by jbclements** [comment]
FWIW, I don't see the crypto-test error when i run "raco test -p crypto-test" on my machine. Also, the link above to the log "https://plt.cs.northwestern.edu/release-pkg-build/server/built/test-fail/crypto-test.txt" is now a 404, because in the latest build apparently it succeeded... and in fact, so did process-queue. And, ugh, there's a new failure for the "sci" tests... but I'm also unable to duplicate that one locally. What's going on here?

**Comment by jbclements** [comment]
Given what I'm seeing now, I feel that the errors we're seeing appear to be ... something transient? I'm going to go ahead and move into testing.

**Comment by rfindler** [comment]
> A dummy branch seems easier than having you write code to check for a file at a URL, no? 
> 

I can just wget or something. I am happy either way. 

> 
> WRT your first question:
> 
> (1) the checklist only currently suggests that we look at the diff *once*, just after the initial build.
> 
> (2) In this release, we've definitely looked repeatedly, in order to see whether the problems have gone away.
> 
> (3) Even when we turn the signal (whatever it winds up being) off, this just means that it drops back to standard priority, right? 

Before this release cycle the way it worked was that it did the snapshot and pkg-build or it did the snapshot and two pkg-builds (the extra one being based on the release build).

I think it makes sense to, during this specific phase of the release to skip the snapshot and regular pkg build, and do only the release pkg-build. 

> I think the problem we're trying to solve is just the potentially long gap between the initial build and the first run of the pkg build, and (secondarily) the potentially long wait to see whether a given fix is reflected in the pkg-build-diff results. Honestly, I think that the second one is not nearly as important as the first.

This should help with that, as the release pkg build used to run third of the three things. 

But maybe a simpler fix would be to keep the way it was before, but just reorder the three steps so that the release pkg build goes first? I can also have it send email right when it finishes the release pkg build to both of us so we know.

**Comment by rfindler** [comment]
> But maybe a simpler fix would be to keep the way it was before, but just reorder the three steps so that the release pkg build goes first? I can also have it send email right when it finishes the release pkg build to both of us so we know.

Actually I'm not sure this helps. If there are three things going then the order in which they happen probably doesn't matter since, once we start on one, we're committed to it until it finishes. I think the suggestion quoted above is basically equivalent to the fix that's already pushed, namely evaluating the predicate "are we going to do the release pkg build?" right before starting it (or not). Before this release cycle, that predicate was evaluated at the start of the script, which means we might be 1.5 days later before the predicate's result is acted on and so the value might be very stale. I seems hard to be more nimble than that unless we're willing to abort things in the middle.

Overall, there are three time-consuming activities that the machine does: snapshot build, pkg build, release pkg build. I'm happy to add whatever guards at the start of each of these to do them in any particular order, if anyone has any suggestion on how to improve on the status quo.

**Comment by samth** [comment]
The current status is that `process-queue` did not fail, `crypto-test` failed, and `timable` (newly) failed.

**Comment by sorawee** [comment]
Both `crypto-test` and `timable` no longer failed.

**Comment by jbclements** [comment]
@LLazarek , did you see @sorawee 's discussion above of the delicious flaky crust on the testing for process-queue? Or ... maybe it was some other kind of flakiness. Either way, I think we're going to move ahead with the release, but I wanted to make sure that you saw the thread.

**Comment by LLazarek** [comment]
Thanks @jbclements and @sorawee - I've seen it, just haven't had time to investigate myself yet. I have some idea of what's likely causing issues in those tests though and I'm planning to revise them!
