### ISSUE TITLE
Confusing error message from `flat-or/c`

### ISSUE THREAD

**Issue by LiberalArtist** [racket/racket#4900]
Consider the following buggy program:
```racket
#lang racket
(define/contract (file i j [ogg 'ogg])
  (-> [natural-number/c natural-number/c] [(or/c 'ogg 'mp3)] string?)
  "irrelevant")
```
The fundamental bug is that I wrote `->` when I meant `->*`. Unfortunately, many things one might hope would raise an error are actually allowed: for example, applying `natural-number/c` to itself returns `#f`, which is a valid contract. The error the program finally produces is:
```
flat-or/c: arity mismatch;
 the expected number of arguments does not match the given number
  expected: 1
  given: 0
```
It confused me that the error named `flat-or/c`, which does not appear in my program. Initially (in part because I am using a snapshot) I thought one of the optimizations for `->` or `or/c` had encountered an internal error. An error naming `or/c` would be only slightly better, since `or/c` is actually applied to 2 arguments: the arity error is really from the function returned by `or/c`.

If it's not too expensive, I think the ideal solution would be to include the name of the contract in the error message somehow.

**Comment by rfindler** [comment]
Turns out there was a hook there that the contract system just wasn't using, so now you'd get this:

```
> (-> [natural-number/c natural-number/c] [(or/c 'ogg 'mp3)] string?)
(or/c 'ogg 'mp3): arity mismatch;
 the expected number of arguments does not match the given number
  expected: 1
  given: 0
```
