### ISSUE TITLE
asm-conditional-jump: '%+ branch type is currently unsupported

### ISSUE THREAD

**Issue by Antigen-1** [racket/racket#4905]
**What version of Racket are you using?**
```Welcome to Racket v8.11.1 [cs].```

**What program did you run?**
I'm writting programs using emacs, with racket-mode and racket-xp-mode enabled. racket-xp-mode reports an error which is hard to comprehend.

**If you got an error message, please include it here.**
```asm-conditional-jump: '%+ branch type is currently unsupported```

**Please include any other relevant details**
```
uname -a
Linux fedora 6.6.11-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jan 10 19:25:59 UTC 2024 x86_64 GNU/Linux
```

**Comment by sorawee** [comment]
That appears to be an error from Chez Scheme. Could you provide more information? What did you do exactly to trigger this error? What program are you running? Etc.

**Comment by sorawee** [comment]
Racket Mode doesn't run until you open a Racket file, though. Can you provide the content of that file?

**Comment by LiberalArtist** [comment]
How did you install Racket? Did you use an RPM package, or the installer from https://download.racket-lang.org, or something else?
