### ISSUE TITLE
`rename-contract` interferes with some contracts ability to generate random values.

### ISSUE THREAD

**Issue by dented42** [racket/racket#4908]
**What version of Racket are you using?**
e.g., 8.11.1 [cs]

**What program did you run?**
```racket
#lang racket

(contract-random-generate integer?)
; => -132 ; (or any other integer)

(contract-random-generate
 (rename-contract integer? 'thing))
; => 214.0 ; (or any other integer)


(define (stream/c c)
    (or/c null?
          (cons/c c (recursive-contract (stream/c c)))
          (promise/c (recursive-contract (stream/c c)))))

(contract-random-generate (stream/c integer?))
; => '(10.0) ; or some list of integers.

(contract-random-generate
 (rename-contract (stream/c integer?) 'integer-stream))
; => contract-random-generate: unable to construct any generator for contract: #<contract: integer-stream>
```

**What should have happened?**
`rename-contract` seems to prevent some more complicated contracts from generating random values, whereas for simple contracts such as `integer?` it works fine.

**If you got an error message, please include it here.**
In the above example we get "contract-random-generate: unable to construct any generator for contract: #<contract: integer-stream>" as an exception message.

**Please include any other relevant details**
The problem seems to be happening with the `or/c` contract combinator not playing nice with `rename-contract`. Commending out both the `cons/c` and `promise/c` clauses does not change the error.

**Comment by rfindler** [comment]
One thing that's not fixed is that this doesn't work:

```
#lang racket/base
(require racket/contract racket/promise)

(define (a-stream/c c)
  (or/c null?
        (cons/c c (recursive-contract (a-stream/c c)))
        (promise/c (recursive-contract (a-stream/c c)))))

(define not-really-a-stream-of-integers
  (contract (a-stream/c integer?)
            (cons 1 (delay (cons "two" '())))
            'pos 'neg))

(contract-exercise not-really-a-stream-of-integers)
```

Not sure why, exactly.
