### ISSUE TITLE
Crash with flonum maths

### ISSUE THREAD

**Issue by bdeket** [racket/racket#4937]
**What version of Racket are you using?**
tried on: 8.12.0.7 [3m] (DrRacket and commandline)
              8.12.0.9-2024-02-21-a0424377ca [3m]
 on windows 10

**What program did you run?**
```
#lang racket/base

(require racket/flonum)

(define (FCT1 x)
  (fl* (flexp -740.) (fl+ 740. (fl* -739. (fl- x 740.)) (fl* 369. (flexpt (fl- x 740.) 2.)))))
;(FCT1 745.) ;; crashes

(define (FCT3 x)
  (fl* (flexp -740.) (fl+ 740. (fl* -739. (fl- x 740.)))))
;(FCT3 745.) ;; crashes

(define (FCT8 x)
  (fl* 4.1995579896506e-322 (fl+ 740. (fl* -739. (fl- x 740.)))))
;(FCT8 745.)  ;; crashes
;(FCT8 1.)    ;; crashes
;(FCT8 -800.) ;; crashes

;;***********************************************************************************************
(let ([x 745.]) ;; this is fine
  (fl* (flexp -740.) (fl+ 740. (fl* -739. (fl- x 740.)) (fl* 369. (flexpt (fl- x 740.) 2.)))))

;; these are also fine
(define (FCT2 x) ;; no product
  (fl+ 740. (fl* -739. (fl- x 740.)) (fl* 369. (flexpt (fl- x 740.) 2.))))
(FCT2 745.) ;; OK

(define (FCT4 x) ;; no 2nd and 3th term
  (fl* (flexp -740.) (fl+ 740. #;(fl* -739. (fl- x 740.)) #;(fl* 369. (flexpt (fl- x 740.) 2.)))))
(FCT4 745.) ;; OK

(define (FCT5 x) ;; filling out 745. in 2nd term
  (fl* (flexp -740.) (fl+ 740. (fl* -739. (fl- 745. 740.)) #;(fl* 369. (flexpt (fl- x 740.) 2.)))))
(FCT5 745.) ;; OK

(define (FCT6 x) ;; no 1st term
  (fl* (flexp -740.) (fl* -739. (fl- 745. 740.))))
(FCT6 745.) ;; OK

(define (FCT7 x) ;; no 1st term (but with fl+)
  (fl* (flexp -740.) (fl+ (fl* -739. (fl- 745. 740.)))))
(FCT7 745.) ;; OK

(define (FCT9 x) ;; make 1st mult just within subnormal; limit for crash seems to be around 2e-315
  (fl* 2.225073858507201e-314 (fl+ 740. (fl* -739. (fl- x 740.)))))
(FCT9 745.) ;; OK
```

**If you got an error message, please include it here.**
No error message, Racket just crashes/exits when one of the first functions are called

**Please include any other relevant details**
also tried 8.7.0.5 [cs] (windows 10) where it worked fine
 and on  8.11.1.8-20231223-43104c4e8 [3m] (linux) where it crashed, including with FCT4 to 7 but not 9

**Comment by bdeket** [comment]
With the latest snapshot of CS it doesn't crash either.
What can I do to help narrowing down the reason?

**Comment by sorawee** [comment]
Did you mean BC? I think we can safely rule out that CS has no issue.

**Comment by bdeket** [comment]
No I meant CS: I just downloaded the latest snapshot, to see if that would make a difference. With the latest CS there is no problem, with the latest BC it does crash on my windows laptop. And for my desktop (linux) it crashed on 11.1.8. Didn't try the latest there.

**Comment by bdeket** [comment]
I made a mistake in the sample, filling out 745. inf FCT6 & 7.

The smallest problem I can make is:
```
(require racket/flonum)
(define (FCT x) (fl* 4.1995579896506e-322 x))
(FCT 1.)
```

**Comment by bdeket** [comment]
It also seems to be related to the REPL, I think.
Saving to a file and executing `.\Racket.exe" file.rkt` goes without a problem.
Evaluating in the racket prompt, or in DrRacket or just:
`".\Racket.exe" -e "(require racket/flonum) ((lambda (x) (fl* 4.1995579896506e-322 x)) 1.)"`
crashes.

**Comment by sorawee** [comment]
I confirm that I can reproduce the crash on Mac M2, with the BC variant, by evaluating

```
(require racket/flonum)
(define (FCT x) (fl* 4.1995579896506e-322 x))
(FCT 1.)
```

in the REPL of DrRacket.

**Comment by samth** [comment]
I also see the crash on Linux.

**Comment by mflatt** [comment]
The example doesn't fail in a module because `(FCT 1.)` gets constant-folded that way. Throwing in `(set! FCT FCT)` defeats inlining and folding.

The relevant detail about the example is that `4.1995579896506e-322` has all 0s in the high half of its representation. That causes the BC x86_64 JIT to choose the wrong instruction encoding, and it generates

```
      19: bb55000000                     (mov ebx #x55)
      1e: 66490f6ec3                     (movq xmm0 r11)
      23: 488b83f8ffffff                 (mov rax (mem64+ rbx #x-8))
```

which makes no sense. The register `ebx`/`rbx` (whose number is 3) is used when `r11` (whose number is 8 more than 3) was intended. Reaching `r11` requires a REX prefix, but the JIT incorrectly uses an encoding without it.

With a repair, the generated code is

```
      19: 49bb5500000000000000           (mov r11 #x55)
      23: 66490f6ec3                     (movq xmm0 r11)
      28: 488b83f8ffffff                 (mov rax (mem64+ rbx #x-8))
```

I'll push the repair soon.

**Comment by bdeket** [comment]
Thanks for explaining and for fixing.
