### ISSUE TITLE
Issue when compiling simple program in Windows 10 Home

### ISSUE THREAD

**Issue by mbennette68** [racket/racket#4941]
**What version of Racket are you using?**
e.g., 7.7 [cs]

 **_DrRacket, version 8.12_**

**What program did you run?**
Please include a short example that triggers the bug

_#lang racket
(define welcome-msg
  "Welcome to Racket Weekend!")
(define cheers "Cheers!")
(define course-num-days 2)
(define (explanation num-days)
  (format "Racket Weekend is a ~a-day course on Racket." num-days))
(define (welcome)
  (displayln welcome-msg))
(define (cheer)
  (displayln cheers))
(define (explain num-days)
  (displayln (explanation num-days)))

(module+ main
  (welcome)
  (explain course-num-days)
  (cheer))_

**What should have happened?**
An executable, "test.exe" should have been generated in the source directory.

**If you got an error message, please include it here.**

![image_2024-02-26_092806824](https://github.com/racket/racket/assets/16678277/db9ba204-d140-40a9-acb4-bb80bbbf9cb8)

**Please include any other relevant details**
e.g., the operating system used or how you are running the code.
DrRacket created executables when I started experimenting with it using the default, "Racket," Base setting.
I decided to experiment by switching the Base to, "GRacket," then I started getting the errors as shown above.
I switched the Base back to, "Racket," but still get the same errors. Also note the same error occurs with or without 
the (module+ main... section and the source file is not open in another application or DrRacket instance.

Update: 
I tried to compile using Base, "Racket," in another directory and this time the executable was created. 
From a command prompt I was able to run it but no output was generated, as opposed to using 
racket test.rkt which executes the file and generates the output.

I tried to recompile using Base, "GRacket," in the other directory and this time it worked as the exe 
got created but upon executing the program, no output is generated from the executable. 
Somehow, the original source directory got flagged by DrRacket as inaccessible after using the 
Base, "GRacket," option and no exe's can be generated there. 

Just thought I'd mention it.

Any thoughts would be appreciated.

Thank you,
MB

**Comment by neteroster** [comment]
Try disabling the real time protection of Windows Defender and try again. I've met the same issue and this works for me.

**Comment by mbennette68** [comment]
Ok thank you. I will try that :)
