### ISSUE TITLE
Dead link on Racket Reference Bibliography

### ISSUE THREAD

**Issue by PabloReszczynski** [racket/racket#4959]
[Danvy90](https://docs.racket-lang.org/reference/doc-bibliography.html#%28cite._.Danvy90%29) paper pdf link is dead (returns a msg saying a token is needed)

Would be nice to obtain another link with the pdf file.

**Comment by PabloReszczynski** [comment]
ACM.org has a working link: https://dl.acm.org/doi/pdf/10.1145/91556.91622

**Comment by sorawee** [comment]
https://dl.acm.org/doi/pdf/10.1145/91556.91622 from ACM DL seems like a good replacement.
