### ISSUE TITLE
mzscheme not usable

### ISSUE THREAD

**Issue by olopierpa** [racket/racket#4961]
**What version of Racket are you using?**
8.12

**What program did you run?**
mzscheme, in a standard windows terminal

Please include a short example that triggers the bug
anything typed at the prompt is shown in dark unreadable colors.
I mean, not colors that I don't like. Really barely readable with a great effort.
Highlighted text is even worse.

**What should have happened?**
show text typed as white on black, or black on white.

**Please include any other relevant details**
Windows 10 with a just installed Racket.
![Cattura](https://github.com/racket/racket/assets/3459553/2fc9e421-67f1-4fcb-8f74-f644dad8b588)
![Cattura](https://github.com/racket/racket/assets/3459553/09b26ed3-c735-48c9-b3df-5f92764d28d1)

**Comment by rfindler** [comment]
Not a real fix, but in the meantime, it might work to do `mzscheme -q` (which should disable the fancy coloring but also other useful things in the repl).

**Comment by olopierpa** [comment]
Thank you (I had searched for "color" in the output of "mzscheme --hep" without result).  btw, racket.exe behaves the same.

**Comment by mflatt** [comment]
Another option is to use the command `,color off` after starting MzScheme or Racket. That option is provided by the xrepl layer, and it's saved as a preference for the next time you start MzScheme or Racket.

**Comment by olopierpa** [comment]
Perfect. Thank you.

**Comment by olopierpa** [comment]
Correction: much better but still not perfect :)
After ,color off, the expeditor still uses colors:

![Cattura](https://github.com/racket/racket/assets/3459553/bd1baece-6eb7-4b85-aceb-630394ae3c3a)

**Comment by sorawee** [comment]
Good catch. https://github.com/racket/expeditor/blob/master/expeditor-lib/main.rkt#L408 should be wrapped in `(when (current-expeditor-color-enabled) ...)`.

**Comment by sorawee** [comment]
It is also possible to just make `set-fg-color` itself consult `current-expeditor-color-enabled`. Is there a reason against that?

**Comment by rfindler** [comment]
It may also make sense to have a default set of colors that are reasonable on a black background that can be easily turned on and maybe default to that turned on, under windows, as using command.com is usually a black background?

**Comment by olopierpa** [comment]
On Sun, Mar 31, 2024 at 4:12 AM sorawee ***@***.***> wrote:

> Good catch.
> https://github.com/racket/expeditor/blob/master/expeditor-lib/main.rkt#L408
> should be wrapped in (when (current-expeditor-color-enabled) ...).
>
I confirm that this fixes the problem. Thank you.

**Comment by olopierpa** [comment]
should I close or keep it open?

**Comment by sorawee** [comment]
Let's keep this open until we actually make a change

**Comment by mflatt** [comment]
> It is also possible to just make set-fg-color itself consult current-expeditor-color-enabled. Is there a reason against that?

It looks like there's one place where a `(current-expeditor-color-enabled)` check guards both the `set-fg-color` call and a flush action. But I agree that putting the check in `set-fg-color` makes sense — and even if the guard is removed at that one place so that it doesn't skip a flush, an extra flush shouldn't cause any issues.
