### ISSUE TITLE
racket/serialize: deserialization fails in exe

### ISSUE THREAD

**Issue by Bogdanp** [racket/racket#4967]
**What version of Racket are you using?**

HEAD

**What program did you run?**

```racket
#lang racket/base

(require gregor
         racket/serialize)

(deserialize (serialize (now)))
```

Converted to an executable via `raco exe`:

```
$ raco exe -o test test.rkt
```

**What should have happened?**

Running the executable should print the current date and time. Instead, it fails with a `dynamic-require` error.

**If you got an error message, please include it here.**

```
dynamic-require: name is not provided
  name: 'deserialize-info:DateTime
  module: #<resolved-module-path:'#%embedded:gregor/private/datetime:>
  context...:
   .../private/serialize.rkt:705:2: deserialize
   body of '#%mzc:test
```

When run normally (i.e. `racket test.rkt`), everything works as expected. It seems likely that this is an issue with `raco exe` instead of `racket/serialize`, but I'm not sure. Gregor provides the deserialization info from a submodule in the right place:

https://github.com/97jaz/gregor/blob/2d20192e8795e01a1671869dddaf1984f0cbafee/gregor-lib/gregor/private/datetime.rkt#L77-L78

**Comment by Bogdanp** [comment]
It looks like the issue is ultimately a bad interaction between `raco exe` and the way `racket/serialize` looks up the deserialize info via a submodule, and the fact that gregor doesn't also provide the deserialize-info from the toplevel module (in which case the `racket/serialize` fallback would've worked). This is already mentioned by the `raco exe` documentation:

> The relative lack of specification for module names can be a problem for language constructs that are sensitive to module names, such as serialization. To take more control over a module’s symbolic name, use the ++named-lib or ++named-file argument to specify a prefix that is appended before the module’s base name to generate a symbolic name.

Rather than use `++named-lib`, I was able to work around the issue in the end by installing a custom module guard to rewrite the module paths at runtime:

```racket
#lang racket/base

(require (for-syntax racket/base)
         gregor
         racket/match
         racket/runtime-path
         racket/serialize)

(define-runtime-module-path-index datetime.rkt/deserialize-info
  '(submod (lib "gregor/private/datetime.rkt") deserialize-info))
(define-runtime-module-path-index moment-base.rkt/deserialize-info
  '(submod (lib "gregor/private/moment-base.rkt") deserialize-info))

(deserialize-module-guard
 (let ([old (deserialize-module-guard)])
   (lambda (mod-path sym)
     (match mod-path
       [`(lib ,(regexp #rx"gregor/private/([^.]+).rkt" (list _ mod-name)))
        (define submod-path
          (case mod-name
            [("datetime") datetime.rkt/deserialize-info]
            [("moment-base") moment-base.rkt/deserialize-info]
            [else (error 'deserialize-module-guard "unexpected mod-name ~s" mod-name)]))
        (cons (module-path-index-resolve submod-path) sym)]
       [_
        (old mod-path sym)]))))

(deserialize (serialize (now/moment)))
```

And that works fine, so I don't think there's anything to be done here. Sorry for the noise!

**Comment by rfindler** [comment]
Very cool that you sorted this all out! I wonder if there is a change to gregor that'd prevent the next person from running into this?

**Comment by Bogdanp** [comment]
> Very cool that you sorted this all out! I wonder if there is a change to gregor that'd prevent the next person from running into this?

It looks like [providing](https://github.com/97jaz/gregor/pull/59) the `deserialize-info` values from the toplevel modules where the structs are declared fixes the issue.
