### ISSUE TITLE
Release Regressions for 8.13

### ISSUE THREAD

**Issue by samth** [racket/racket#4978]
### Build Failures
- [x] **clang** https://plt.cs.northwestern.edu/release-pkg-build/server/built/fail/clang.txt
   Caused by racket/typed-racket#1367. 
   Can be fixed by merging https://github.com/wargrey/digimon/pull/3
- [x] **digimon** https://plt.cs.northwestern.edu/release-pkg-build/server/built/fail/digimon.txt Caused by racket/typed-racket#1367. Can be fixed by merging https://github.com/wargrey/digimon/pull/3
- [x] **odysseus** https://plt.cs.northwestern.edu/release-pkg-build/server/built/fail/odysseus.txt Caused by #4917. Could be addressed by merging https://github.com/prozion/odysseus/pull/2 or by reverting the change by merging #4973. 
### Test Failures
- [x] **crypto-test** https://plt.cs.northwestern.edu/release-pkg-build/server/built/test-fail/crypto-test.txt Error is perhaps caused by different C libraries.
- [x] **peg-parser** https://plt.cs.northwestern.edu/release-pkg-build/server/built/test-fail/peg-parser.txt Test timeout, likely unrelated to changes in Racket.
- [x] **struct-defaults** https://plt.cs.northwestern.edu/release-pkg-build/server/built/test-fail/struct-defaults.txt Perhaps caused by an error message change. Can be fixed by merging https://github.com/tonyg/racket-struct-defaults/pull/1

### Other Failures
- [x] **video-v0-0** This is a continuing issue caused by the way the `video-*` packages are structured and not a regression.

**Comment by sorawee** [comment]
The odysseus failure is addressed by #4973. OK to merge?

**Comment by samth** [comment]
@rmculpepper Can you look into the `crypto-test` issue?

**Comment by jbclements** [comment]
marking odysseus/hash-filter as resolved for this release. I've also sent email to the author of odysseus, we'll see if he responds, I'm worried this will get forgotten again.

**Comment by jbclements** [comment]
Checking box associated with struct-defaults. Based on conversation on that pull request, it appears to me that there's no current evidence to suggest that this regression is associated with a problem with the release candidate. I left a message to this effect on that PR as well.

**Comment by prozion** [comment]
Ok, author of odysseus is here, thank you for pinging me about the issue.  :-) 
Honestly, I was thinking to migrate my Racket and Clojure libs towards codeberg.org, as I am not very fond of big corps like Microsoft. So I just lost focus a bit on what is happening on github, beg your pardon.

**Comment by jbclements** [comment]
I'm marking the `clang` and `digimon` packages as not blocking the release. As far as we know, the existing pull requests should fix these problems, and it seems likely that there are not other problems with the release that would break these packages.

**Comment by jbclements** [comment]
I'm also going to say that I think the `peg-parser` failure should not block the release, though I would welcome information from the package's author. I filed an issue here: https://github.com/lives-group/peg-parser/issues/1 .

**Comment by jbclements** [comment]
closing this issue now, I don't think that any of these should block the 8.13 release.

**Comment by emcardoso** [comment]
The peg-parser had some large experiments in the test folder. The experiments were removed. The remaining tests are passing within reasonable time.
