### ISSUE TITLE
Memory exhaust and performance problem with multiple `call-with-composable-continuation`

### ISSUE THREAD

**Issue by Trung0246** [racket/racket#4987]
**What version of Racket are you using?**
e.g., 8.12

**What program did you run?**
```racket
#lang racket/base
(let ([tag (make-continuation-prompt-tag)])
	(println "111")
	(println (string-append "222"
		(call-with-continuation-prompt
			(lambda ()
				(let ([data 0])
					(println (string-append "333"
						(call-with-composable-continuation
							(lambda (k)
								(println "---")
								(println (string-append "444" (k "555")))
								"666")
							tag)))
					(println (string-append "zzz"
						(call-with-composable-continuation
							(lambda (k)
								(println "+++")
								(println (string-append "xxx" (k "ccc")))
								"ddd")
							tag)))
					(println (string-append "qwe"
						(call-with-composable-continuation
							(lambda (k)
								(println "===")
								(println (string-append "wer" (k "ert")))
								"ddd")
							tag)))
					;(println data)
					(set! data (+ data 1))
					(if (= data 56)
						(abort-current-continuation tag "bbb")
						"777")))
			tag
			(lambda (k)
				(println (string-append "888" k))
				"aaa"
				)))))
	(println "999")
```

**What should have happened?**
The program should run smoothly without exhausting all memories.
Honestly I'm not sure if it's a bug or not and not even sure if tail call are applied here.

**If you got an error message, please include it here.**
Ran out of memory.

**Please include any other relevant details**
e.g., Windows 11, using DrRacket.

**Comment by jackfirth** [comment]
Could you say more about why you expect this program not to exhaust memory? It doesn't appear to be making tail calls, and it builds an exponentially large stack, so at first glance it doesn't seem unusual to me that it runs out of memory.

**Comment by Trung0246** [comment]
After looking a bit and double checking looks like it is probably intended behavior to be ran out of memory.
