### ISSUE TITLE
`(file-or-directory-modify-seconds time)` returns #t instead of <void>

### ISSUE THREAD

**Issue by formalizm** [racket/racket#4995]
**What version of Racket are you using?**
8.12 [cs]

**What program did you run?**
```racket
(define f (make-temporary-file))
(define s (file-or-directory-modify-seconds f))
(file-or-directory-modify-seconds f (add1 s))
; #t
```

**What should have happened?**
According to documentation, this function must return `(void)`.

**Please include any other relevant details**
Operating system: Windows 10.
This bug also contaminates `(copy-directory/files f t #:keep-modify-seconds? #t)` call. It also returns #t instead of (void) per documentation.

**Comment by sorawee** [comment]
Couldn't be reproduced on Racket BC, so this is probably a Racket CS specific bug.
