### ISSUE TITLE
Is raco `exe` command supported across all platforms?

### ISSUE THREAD

**Issue by barracuda156** [racket/racket#5031]
**What version of Racket are you using?**
8.13 [cs]

**What program did you run?**
I have tried to build `idris2` with `racket` instead of `chez-scheme` (the latter build works).
It failed, complaining about `exe`.

**What should have happened?**
I hope it can build `idris2` successfully.

**If you got an error message, please include it here.**
```
/bin/sh ./bootstrap-stage1-racket.sh
Bootstrapping IDRIS2_VERSION=0.7.0
Building idris2-boot from idris2-boot.rkt
/opt/local/bin/raco: Unrecognized command: exe

Usage: raco <command> <option> ... <arg> ...

Frequently used commands:
  setup   install and build libraries and documentation
  pkg     manage packages

A command can be specified by an unambiguous prefix.
See `raco help' for a complete list of commands.
See `raco help <command>' for help on a command.
make: *** [bootstrap-racket] Error 1
```

**Please include any other relevant details**

The issue with Idris2: https://github.com/idris-lang/Idris2/issues/3343

Portfile used to build `racket`: https://github.com/barracuda156/macports-ports-powerpc/commit/9639f58c8aba705fb4fb5204d5a43a409178da37
(_this may have issues, it is WIP_).

**Comment by sorawee** [comment]
It looks like you installed minimal racket, which doesn't have raco exe installed by default. To make raco exe available, run raco pkg install compiler-lib.

**Comment by barracuda156** [comment]
@sorawee Got it, thank you for a clarification. I will try that.
