### ISSUE TITLE
Renaming in only-in results in wrong/unintuitive scope

### ISSUE THREAD

**Issue by sorawee** [racket/racket#5035]
**What version of Racket are you using?**
8.13

**What program did you run?**

```
#lang racket/base

(require syntax/parse/define
         (for-syntax racket/base))

(define-syntax-parse-rule (req)
  #:with racket (datum->syntax this-syntax 'racket)
  ;; #:with new-const (datum->syntax this-syntax 'new-const)
  (module+ test
    (require (only-in racket
                      identity
                      #;[const new-const]))))

(req)

(module+ test
  identity
  #;new-const)
```

**What should have happened?**

The above program runs fine. This is the expected behavior.

Now, remove two `#;`s. I expect the program to continue to run without an error as well.

**If you got an error message, please include it here.**

```
new-const: unbound identifier
```

**Please include any other relevant details**

This could be workaround by remove `;;` to set lexical context to `new-const`, but that doesn't seem correct according to the documentation: 

- "The lexical context of the module-path form determines the context of the introduced identifiers" seems to indicate that the lexical context of `racket` is the only thing that matters.
- There's no mentioning of lexical context in the `only-in` sub form, so it seems to indicate that the lexical context of `new-const` should not matter.

**Comment by mflatt** [comment]
I'll repair the docs, since `only-in` and `rename-in` are definitely intended to use the context of a `bind-id` when one is provided as a renaming.

I think a good case can be made that context should be kept for a `id` named by itself in those forms. But, of course, the only plausible choice at this point is to preserve the existing behavior.
