### ISSUE TITLE
Docs describe `equal?` extflonums incorrectly

### ISSUE THREAD

**Issue by rocketnia** [racket/racket#5039]
**What version of Racket are you using?**
Racket 8.12 64-bit x86-64 BC, downloaded today from the releases page.

**What program did you run?**
```racket
Welcome to Racket v8.12 [bc].
> (require racket/extflonum)
> (extflonum-available?)
#t
> (define a -0t0)
> (define b 0t0)
> (eq? a b)
#f
> (equal? a b)
#f
> (extfl= a b)
#t
```

I believe the behavior exhibited here is correct. It makes extflonums behave similarly to numbers, where `(= -0.0 0.0)` but `(not (equal? -0.0 0.0))`.

However, [the documentation](https://docs.racket-lang.org/reference/extflonums.html) states something that's inconsistent with this:

> Two extflonums are `equal?` if `extfl=` produces `#t` for the extflonums.

**What should have happened?**
I believe the documentation should be revised to correct this inconsistency with the exhibited `equal?` behavior.

If `equal?` for extflonums is intended to be like `equal?` for numbers, then the documentation could be more informative if it also described the NaN case:

```racket
> (define c (extfl/ 0t0 0t0))
> (define d (extfl/ 0t0 0t0))
> (eq? c d)
#f
> (equal? c d)
#t
> (extfl= c d)
#f
```

**Comment by mflatt** [comment]
Thanks for the report!
