### ISSUE TITLE
Possible unenforced `chaperone-vector*` contract

### ISSUE THREAD

**Issue by rocketnia** [racket/racket#5041]
**What version of Racket are you using?**
8.12 [cs]

**What program did you run?**

```racket
Welcome to Racket v8.12 [cs].
> (chaperone-vector* (vector->immutable-vector (vector 1)) #f #f)
'#(1)
```

**What should have happened?**

I don't know which contract is correct here.

* The [documented contract in the `chaperone-vector*` reference](https://docs.racket-lang.org/reference/chaperones.html#%28def._%28%28quote._~23~25kernel%29._chaperone-vector%2A%29%29) says _`vec`_ should be an `(and/c vector? (not/c immutable?))`. It's possible the actual contract being enforced here in practice, `vector?`, was erroneously copied from the `chaperone-vector` implementation.
* However, the body of the `chaperone-vector*` reference says it's like `chaperone-vector` in most respects, and `chaperone-vector` allows _`vec`_ to be any `vector?`, which is consistent with the behavior I see here. It's possible the documentation's `(and/c vector? (not/c immutable?))` was erroneously copied from the `impersonate-vector*` documentation.

...Well, if I look at the big picture, I think this is probably the latter situation, a simple mistake in the docs. I don't see a reason `chaperone-vector*`'s more expressive interposition capabilities should be unavailable to people who are interposing on an immutable vector.

**Comment by mflatt** [comment]
I agree that it's the latter situation, and I'll push a repair.

Thanks for the report!
