### ISSUE TITLE
constructor contract fail produces "broke its own contract" msg

### ISSUE THREAD

**Issue by jbclements** [racket/racket#5043]
**What version of Racket are you using?**
8.13.900

**What program did you run?**

```racket
#lang racket

(module my-mod racket
  (provide (contract-out
            (struct osc-message ([args (listof integer?)]))))

  (struct osc-message (args)))

(require 'my-mod)

(osc-message 1234)
```

**What should have happened?**

I expected a message that looks like a negative-position failure: "contract violation" or similar.

**If you got an error message, please include it here.**

osc-message: broke its own contract
  promised: list?
  produced: 1234
  in: the 1st argument of
      (-> (listof integer?) osc-message?)
  contract from: /private/tmp/b.rkt
  blaming: /private/tmp/b.rkt
   (assuming the contract is correct)
  at: /private/tmp/b.rkt:7:10

**Please include any other relevant details**
e.g., the operating system used or how you are running the code.

MacOS sonoma 14.5

could be related to  c29c4a3fd0e4 ?

**Comment by samth** [comment]
Here's the different messages from HEAD and from 8.13:

```
raco cross -q --version 8.13 racket /tmp/c.rkt
osc-message: contract violation
  expected: list?
  given: 1234
  in: the 1st argument of
      (-> (listof integer?) osc-message?)
  contract from: (/tmp/c.rkt my-mod)
  blaming: /tmp/c.rkt
   (assuming the contract is correct)
  at: /tmp/c.rkt:7:10
  context...:
   /home/samth/sw/plt/add-on/raco-cross/8.13/x86_64-linux-cs/collects/racket/contract/private/blame.rkt:346:0: raise-blame-error
   /home/samth/sw/plt/add-on/raco-cross/8.13/x86_64-linux-cs/collects/racket/contract/private/arrow-val-first.rkt:486:18
   body of "/tmp/c.rkt"
raco cross: command failed
racket /tmp/c.rkt
osc-message: broke its own contract
  promised: list?
  produced: 1234
  in: the 1st argument of
      (-> (listof integer?) osc-message?)
  contract from: /tmp/c.rkt
  blaming: /tmp/c.rkt
   (assuming the contract is correct)
  at: /tmp/c.rkt:7:10
  context...:
   /home/samth/sw/plt/racket/collects/racket/contract/private/blame.rkt:350:0: raise-blame-error
   /home/samth/sw/plt/racket/collects/racket/contract/private/arrow-val-first.rkt:486:18
   body of "/tmp/c.rkt"
```

**Comment by mfelleisen** [comment]
I am seeing Sam’s message in my dr, updated on Sunday.

**Comment by rfindler** [comment]
yes, this is definitely the refactoring I did to support `contract-out`.

**Comment by rfindler** [comment]
Thanks for narrowing this down, @jbclements !
