### ISSUE TITLE
Requiring a rel-path file with a dot in a directory path part

### ISSUE THREAD

**Issue by jnboehm** [racket/racket#5050]
**What version of Racket are you using?**
Racket v8.13 [cs]

**What program did you run?**
```racket
(require "dir.dot/x.rkt")
```

**What should have happened?**
I would have expected that it would `require` the file without an error.

**If you got an error message, please include it here.**
```
string:1:9: require: bad module-path string
  at: "dir.dot/x.rkt"
  in: (require "dit.dot/x.rkt")
 [,bt for context]
```

**Please include any other relevant details**

I'm aware that it's possible to include the file via `(require (file ...))` (as has been [pointed out to me](https://racket.discourse.group/t/requiring-a-file-that-is-in-a-directory-containing-a-dot/3062)).  What I am surprised about is that this behavior is not really documented and I don't quite understand why it happens, leading me to believe that this is a bug.

Probably not relevant, but from the forum post above, this also seems to happen on Windows.  I am running Linux, where I also encounter the problem.

**Comment by mflatt** [comment]
It looks like this has been covered by later answers in the forum, but to summarize for the record:

* The syntax allowed for a relative path without `file` is intentionally limited to avoid portability problems. The restriction is documented at https://docs.racket-lang.org/reference/require.html in the description of what is allowed for a `rel-string`.

* The restrictions are intended to avoid portability problems, in various ways. In the case of `.` within a directory name, Windows can do weird things. (I forget exactly how it goes, but it may be related to inconsistencies around `.` at the end of a directory path.)
