### ISSUE TITLE
[Feature Request] ffi / foreign procedure with zeroed-atomic buffer

### ISSUE THREAD

**Issue by acarrico** [racket/racket#5074]
Every once in a while I use the Racket ffi, and I remember how pleasant it is to use!

One small improvement would be support for arguments of type ```(buffer : (_ptr o _type-expr_ zeroed-atomic))``` in which ```buffer``` is zeroed before the foreign procedure call. See [```_ptr```](https://docs.racket-lang.org/foreign/foreign_procedures.html?q=echo#%28form._%28%28lib._ffi%2Funsafe..rkt%29.__ptr%29%29) / [```malloc```](https://docs.racket-lang.org/foreign/foreign_pointer-funcs.html?q=echo#%28def._%28%28quote._~23~25foreign%29._malloc%29%29).

The existing ```atomic``` mode is explicitly uninitialized, which is normally fine, but occasionally the buffer needs to be zeroed, such as when an API specifies a ```struct``` with padding _reserved for future use_. As far as I can tell, you currently need to use the ```io``` mode and explicitly zero ```buffer``` in that case.

Feel free to close this issue if you have no plans to revisit the interface.

**Comment by mflatt** [comment]
This seems worthwhile to me, so I'll add it.

**Comment by acarrico** [comment]
Nice. Thanks Matthew
