### ISSUE TITLE
Cannot enable the expeditor

### ISSUE THREAD

**Issue by Antigen-1** [racket/racket#5076]
**What version of Racket are you using?**
```
$ racket -v
Welcome to Racket v8.14 [cs].
```

**What program did you run?**
`racket`

**What should have happened?**
The expeditor should have been enabled by default.

**If you got an error message, please include it here.**

**Please include any other relevant details**
The racket installation was built using [Unix Source + built packages](https://download.racket-lang.org/installers/8.14/racket-8.14-src-builtpkgs.tgz), with commands listed as follows.

```
$ ./configure --prefix=$HOME/racket
$ make
$ make install
```

And I've re-setup the `expeditor` collection multiple times.

Tested on fedora silverblue 40.

```
$ uname -a
Linux fedora 6.10.9-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Sep  8 17:23:55 UTC 2024 x86_64 GNU/Linux
```

I wonder if there's dependencies I need to install before I use the expeditor.

**Comment by mflatt** [comment]
Expeditor needs a curses library (often ncurses) to be found at `configure` time, so maybe that's the missing dependency?
