### ISSUE TITLE
(require racket/gui) cause error when I run as a script.

### ISSUE THREAD

**Issue by junogura** [racket/racket#5085]
**What version of Racket are you using?**
8.14 [cs] 

**What program did you run?**

require_gui.rkt
> #lang racket
> 
> (require racket/gui)

and

gui.rkt
> #lang racket/gui

**What should have happened?**
When I run these files as script. I got error.

Commands are like bellow.

> racket require_gui.rkt 
> racket gui.rkt 

**If you got an error message, please include it here.**

This. 
> post-dummy-event: undefined;
>  cannot reference an identifier before its definition
>   in module: "/Applications/Racket v8.14/share/pkgs/gui-lib/mred/private/wx/cocoa/queue.rkt"
>   context...:
>    /Applications/Racket v8.14/share/pkgs/gui-lib/mred/private/wx/cocoa/queue.rkt:87:2
>    body of "/Applications/Racket v8.14/share/pkgs/gui-lib/mred/private/wx/cocoa/queue.rkt"
>    body of "/Applications/Racket v8.14/share/pkgs/gui-lib/mred/private/wx/platform.rkt"

**Please include any other relevant details**
macOS sequoia 15.0.1 Apple Silicon M1

**Comment by junogura** [comment]
Thank you. I will use a latest snapshot.

**Comment by LiberalArtist** [comment]
Can this be closed?

**Comment by junogura** [comment]
Should I close this?

**Comment by jbclements** [comment]
@junogura , I'm interpreting your comment as indicating that you're approving of its being closed. I'm therefore going to close it; if I'm misinterpreting you, let me know and I will re-open it.
