### ISSUE TITLE
[Feature Request] Define a Specific Exception Type to Identify Empty Sequences in for Loops

### ISSUE THREAD

**Issue by NoahStoryM** [racket/racket#5099]
**Is your feature request related to a problem? Please describe.**
I am working with a sequence that theoretically stores all possible values of a
certain type. When accessing elements within this sequence, if there are no
possible values available, a specific exception is raised. From this perspective,
such a sequence should logically be considered "empty" if it raises this exception
when accessed.

However, in the current Racket implementation, there’s no straightforward way for
a for loop to recognize this behavior as an indication of an empty sequence,
making it challenging to handle such cases cleanly and intuitively.

**Describe the solution you'd like**
I would like the for loop in Racket to recognize a sequence as empty when it
raises a specific type of exception upon accessing its elements. A possible
approach would be to define a dedicated exception type to signal an empty
sequence, similar to the strategy used by `stream-empty?`, which appears to rely
on a similar approach to determine if a stream is empty.

**Describe alternatives you've considered**
Another approach would be to introduce a new break-clause for for loops. This
break-clause could allow the programmer to define custom handlers for exceptions
raised during element access. These handlers should receive the accumulated result
of the for loop up to the current point.

**Do you want to contribute to this feature**
Yes.

**[Optional] Additional context**
If we pursue the first solution, it might also make sense to define a
`sequence-empty?` predicate similar to `stream-empty?`.

**Comment by sorawee** [comment]
If I understand correctly, what you want is for Racket to recognize an exception from _element access_ as a signal for the end of sequence. Is that correct?

(It is not clear to me at all until I read "Describe alternatives you've considered")

What you want can kind of already be implemented in Racket. Here's one possible implementation.

```
#lang racket

(require racket/generic)

(struct exn:end-of-sequence exn:fail ())

(define (raise-end-of-sequence)
  (raise (exn:end-of-sequence "end of sequence reached" (current-continuation-marks))))

(define my-sequence (stream 'A 'E 'I 'O 'U (raise-end-of-sequence) 1 2 3 4))

;; this would cause the exn:end-of-sequence exception
#;
(for/list ([i my-sequence])
  i)

;; trim-end-of-sequence :: sequence? -> sequence?
(define (trim-end-of-sequence seq)
  (struct wrapper (s)
    #:methods gen:stream
    [(define/generic super-empty? stream-empty?)
     (define/generic super-first stream-first)
     (define/generic super-rest stream-rest)
     (define (stream-empty? ws)
       (define st (wrapper-s ws))
       (or (super-empty? st)
           (with-handlers ([exn:end-of-sequence? (λ (_e) #t)])
             (super-first st)
             #f)))
     (define (stream-first ws)
       (super-first (wrapper-s ws)))
     (define (stream-rest ws)
       (wrapper (super-rest (wrapper-s ws))))])
  (wrapper (sequence->stream seq)))

(for/list ([i (trim-end-of-sequence my-sequence)])
  i)
```

Another possible implementation is to use `make-do-sequence` + `initiate-sequence`, with a similar trick.

If this behavior is what you want, the next question is, does it still make sense to add this to core Racket? I think the answer would depend on the use cases outside of your library. Are you aware of any? Also, we should keep in mind that sequences are used heavily in many Racket programs, and any change to core Racket should not significantly impact the performance. 

> A possible approach would be to define a dedicated exception type to signal an empty
sequence, similar to the strategy used by stream-empty?, which appears to rely
on a similar approach to determine if a stream is empty.

Could you elaborate a bit more? I don't think `stream-empty?` has any "dedicated exception type".

**Comment by NoahStoryM** [comment]
Thank you very much for the clarification and the detailed example!

> If I understand correctly, what you want is for Racket to recognize an exception from element access as a signal for the end of sequence. Is that correct?

Yes, you understood correctly—this is exactly the behavior I was looking for.

> What you want can kind of already be implemented in Racket. Here's one possible implementation.

I appreciate the solution you provided. This approach looks like it should address my needs.

> If this behavior is what you want, the next question is, does it still make sense to add this to core Racket? I think the answer would depend on the use cases outside of your library. Are you aware of any? Also, we should keep in mind that sequences are used heavily in many Racket programs, and any change to core Racket should not significantly impact the performance.

Previously, I was unsure how to handle sequences like these and found it challenging to write concise code for such cases. With your suggested approach, I think I can wrap this functionality in my library’s interface so that other programmers won’t even notice this underlying issue. As for applications beyond my library, I haven't thought of broader scenarios yet—I initially raised this as I didn’t see a clear way to handle this behavior with existing constructs.

> Could you elaborate a bit more? I don't think stream-empty? has any "dedicated exception type".

I noticed that Racket's for loops handle `(in-list '())` correctly and `(stream-empty? (in-list '()))` returns `#t`. To understand how this works internally, I looked at the implementation in `racket/private/for.rkt`, specifically this part:

```racket
(define (stream-empty? v)
  (or (null? v)
      (if (stream? v)
          (if (pair? v)
              #f
              ((unsafe-vector-ref (stream-ref v) 0) v))
          (raise-argument-error 'stream-empty?
                                "stream?"
                                v))))
```

It seems that `stream-empty?` uses the `unsafe-vector-ref` operation to check if an exception is triggered when trying to access a value, which then signals the end of the stream. This solution was similar to what I had in mind. Given that both my library and stream face this scenario, I wondered if a dedicated exception type could be defined specifically for this purpose, allowing for loops to handle it more seamlessly.

If we had such an exception type, it might make sense to define a more general `sequence-empty?` predicate as well. This predicate could then serve as a test to ensure that this approach works as intended.

Thank you again for your time and insights!

**Comment by NoahStoryM** [comment]
> Another possible implementation is to use make-do-sequence + initiate-sequence, with a similar trick.

I'd like to explore this approach further. I’m not very familiar with `gen:stream`, my current understanding is that the for loop iterates over streams using methods associated with `gen:stream`, so that we could customize `stream-empty?` to signal the termination condition for the loop.

However, I’m not sure how to implement this specifically using `make-do-sequence` and `initiate-sequence`. Could you clarify how these functions could be used to define a sequence with a custom end condition, so that for would recognize it correctly?

**Comment by sorawee** [comment]
> It seems that stream-empty? uses the unsafe-vector-ref operation to check if an exception is triggered when trying to access a value, which then signals the end of the stream.

`stream?` in Racket is internally implemented as a [struct-type-property](https://github.com/racket/racket/blob/master/racket/collects/racket/private/for.rkt#L488-L508). Under the hood, a stream type is really a vector of length 3: 
- a function that indicates whether the stream is empty or not
- a function to get the first element from the stream, and 
- a function to get the rest of the stream

These corresponds to the methods that you have to implement when you use `gen:stream`.

So there is no special exception in `((unsafe-vector-ref (stream-ref v) 0) v)`. It's an expression to access the function that indicates whether the stream is empty or not, and then apply it to the stream value.

> Could you clarify how these functions could be used to define a sequence with a custom end condition, so that for would recognize it correctly?

Here's my quick implementation. Not sure if it's buggy or not.

```
#lang racket

(struct exn:end-of-sequence exn:fail ())

(define (raise-end-of-sequence)
  (raise (exn:end-of-sequence "end of sequence reached" (current-continuation-marks))))

(define my-sequence (stream 'A 'E 'I 'O 'U (raise-end-of-sequence) 1 2 3 4))

;; this would cause the exn:end-of-sequence exception
#;
(for/list ([i my-sequence])
  i)

;; trim-end-of-sequence :: sequence? -> sequence?
(define (trim-end-of-sequence seq)
  (make-do-sequence
   (lambda ()
     (define init-pos
       (with-handlers ([exn:end-of-sequence? (λ (_e) #f)])
         (call-with-values (λ () (sequence-generate* seq)) cons)))
     (cond
       [init-pos
        (initiate-sequence
         #:init-pos init-pos
         #:pos->element (λ (pos) (apply values (car pos)))
         #:next-pos (λ (pos) (call-with-values (cdr pos) cons))
         #:continue-with-pos? car
         #:continue-after-pos+val?
         (λ (pos _v)
           (with-handlers ([exn:end-of-sequence? (λ (_e) #f)])
             ((cdr pos))
             #t)))]
       [else
        (initiate-sequence
         #:init-pos #f
         #:pos->element void
         #:next-pos void
         #:continue-with-pos? (λ (_pos) #f))]))))

(for/list ([i (trim-end-of-sequence my-sequence)])
  i)
```

One thing that I didn't attempt to do at all (in both `make-do-sequence` and `gen:stream` variants) is to avoid calling e.g. `super-first` or `((cdr pos))` twice. It's probably doable by keeping track of more states, but I'm too lazy to do that.

**Comment by NoahStoryM** [comment]
Thank you very much for the detailed explanation and for providing the implementation example!

I’ll take some time to go through the example code and fully digest how these functions work, as well as test the approach to ensure it can be applied effectively in my library. Once I confirm everything works as expected, I'll go ahead and close this issue.

Thanks again for your guidance and support!

**Comment by NoahStoryM** [comment]
Thank you once again for all your help! I was able to solve the problem by implementing a version of `trim-end-of-sequence` using `sequence-generate`, as shown below:

```racket
;; trim-end-of-sequence :: sequence? -> sequence?
(define (trim-end-of-sequence seq)
  (define-values (more? get) (sequence-generate seq))
  (define (pos->element pos) (pos))
  (define (continue-with-pos? _)
    (with-handlers ([exn:end-of-sequence? (λ (_) #f)])
      (more?)))
  (make-do-sequence
   (λ ()
     (initiate-sequence
      #:init-pos           get
      #:pos->element       pos->element
      #:next-pos           values
      #:continue-with-pos? continue-with-pos?))))

```
