### ISSUE TITLE
Overlapping libs get deleted from racket libs directory

### ISSUE THREAD

**Issue by jbclements** [racket/racket#5100]
**What version of Racket are you using?**
8.15

**What program did you run?**

EDIT: see below, this is totally reproducible: set the library path and run `raco setup`.

Sadly, I have no idea what specifically triggers this, but it has been happening for quite some time.

The problem is that 18 of the 36 files in /Applications/Racket v8.15/lib/ are being deleted.

Some time after this happens, DrRacket crashes quite hard, with an internal error and then a lockup, that looks like this on the terminal:

```terminal
ENG-CLEMENTS-1:~ clements> cairo_quartz_get_cg_context_with_clip: implementation not found
  arguments...:
   #<cpointer>
  context...:
   /Applications/Racket v8.15/share/pkgs/draw-lib/racket/draw/private/emoji.rkt:168:10: draw-loop
   /Applications/Racket v8.15/share/pkgs/draw-lib/racket/draw/private/dc.rkt:1461:4: do-text method in dc%
   /Applications/Racket v8.15/share/pkgs/draw-lib/racket/draw/private/dc.rkt:1319:4: draw-text method in dc%
   /Applications/Racket v8.15/share/pkgs/draw-lib/racket/draw/private/record-dc.rkt:451:15: draw-text method in record-dc-mixin
   .../private/arrow-higher-order.rkt:375:33: ...row-higher-order.rkt:375:33
   /Applications/Racket v8.15/share/pkgs/gui-lib/mred/private/wxme/text.rkt:5599:22: process-snips
   /Applications/Racket v8.15/share/pkgs/gui-lib/mred/private/wxme/text.rkt:5569:16: lloop
   /Applications/Racket v8.15/share/pkgs/gui-lib/mred/private/wxme/text.rkt:5348:2: refresh method in text%
   /Applications/Racket v8.15/share/pkgs/gui-lib/mred/private/wxme/editor-canvas.rkt:648:2: redraw method in editor-canvas%
   /Applications/Racket v8.15/share/pkgs/gui-lib/mred/private/wxme/editor-canvas.rkt:557:2: on-paint method in editor-canvas%
   /Applications/Racket v8.15/collects/racket/private/more-scheme.rkt:148:2: call-with-break-parameterization
   /Applications/Racket v8.15/collects/ffi/unsafe/atomic.rkt:73:13
   /Applications/Racket v8.15/share/pkgs/gui-lib/mred/private/wxme/editor-canvas.rkt:1308:2: do-needs-update method in canvas-editor-admin%
   /Applications/Racket v8.15/share/pkgs/gui-lib/mred/private/wxme/editor-canvas.rkt:1295:4: all-in-chain method in canvas-editor-admin%
   /Applications/Racket v8.15/share/pkgs/drracket/drracket/private/module-language.rkt:2677:6: after-scroll-to method in mk-module-language-text-mixin241
   /Applications/Racket v8.15/share/pkgs/drracket/drracket/private/syncheck/blueboxes-gui.rkt:306:4: after-scroll-to method in docs-text-gui-mixin
   ...
internal error: attempt to deschedule the current thread in atomic mode
  context...:
   /Applications/Racket v8.15/share/pkgs/gui-lib/mred/private/wxme/editor.rkt:1394:2: wait-sequence-lock method in editor%
   /Applications/Racket v8.15/share/pkgs/gui-lib/mred/private/wxme/text.rkt:769:2: begin-edit-sequence method in text%
   /Applications/Racket v8.15/share/pkgs/gui-lib/framework/private/coroutine.rkt:20:33
   /Applications/Racket v8.15/share/pkgs/gui-lib/framework/private/coroutine.rkt:47:20
   /Applications/Racket v8.15/share/pkgs/gui-lib/framework/private/coroutine.rkt:56:0: coroutine-run
   /Applications/Racket v8.15/collects/racket/contract/private/arrow-val-first.rkt:486:18
   
```

The problem is almost certainly related to my lib path, which I set in racket/etc/config to be

`(lib-search-dirs . (#f "/opt/local/lib"))`

I do this in order to be able to use libraries (specifically glpk) that are installed in /opt/local/lib by macports. I put the #f first, so that Racket preferentially uses the libraries installed in racket/libs instead of those in /opt/local/lib, which ... might be older? 

Unfortunately, what periodically happens is that every library in racket/libs with a name that also appears in /opt/local/lib is deleted. There are 18 overlaps, and these are precisely the files that are deleted somehow during the operation of racket or drracket. 

I don't know what triggers it, but the solution AFAICT is to re-copy these files from a freshly downloaded copy of the racket bundle. 

This appears to happen ... every couple of months? As I said, I don't know what triggers it, but I may start with a cron job or something similar to see when they get deleted. 

This was discussed as part of this thread on discourse:

https://racket.discourse.group/t/mysterious-library-deletion/2456/6

My general experience with problems like this is that it turns out to be something foolish that I'm doing, but if it's something that could be done foolishly by me, it's probably also something that could be done foolishly by others. 

**What should have happened?**

The libs in the /Applications/Racket v8.15/lib/ directory should not be deleted.

**If you got an error message, please include it here.**

see above

**Please include any other relevant details**

macOS 14.7.1, Mac M1.

**Comment by jbclements** [comment]
Okay, actually, this is now extremely reproducible (for me, anyway): running `raco setup` deletes the overlapping libs.

**Comment by jbclements** [comment]
Aaand, I'm now embarrassed (as usual) that I didn't read the whatever it was. In this case, it's the log of `raco setup`, which states very clearly that it's deleting these files:

```
Grossvogel:~/git-work/pkgs/badger (git)-[master]- clements> raco setup
raco setup: version: 8.15
raco setup: platform: aarch64-macosx [cs]
raco setup: target machine: tarm64osx
raco setup: installation name: 8.15
raco setup: variants: cs
raco setup: main collects: /Applications/Racket v8.15/collects/
raco setup: collects paths: 
raco setup:   /Users/clements/Library/Racket/8.15/collects
raco setup:   /Applications/Racket v8.15/collects/
raco setup: main pkgs: /Applications/Racket v8.15/share/pkgs
raco setup: pkgs paths: 
raco setup:   /Applications/Racket v8.15/share/pkgs
raco setup:   /Users/clements/Library/Racket/8.15/pkgs
raco setup: links files: 
raco setup:   /Applications/Racket v8.15/share/links.rktd
raco setup:   /Users/clements/Library/Racket/8.15/links.rktd
raco setup: main docs: /Applications/Racket v8.15/doc
raco setup: --- updating info-domain tables ---                    [9:18:34]
raco setup: --- pre-installing collections ---                     [9:18:34]
raco setup: --- installing foreign libraries ---                   [9:18:34]
raco setup: deleting: foreign library <lib>/libgio-2.0.0.dylib
raco setup: deleting: foreign library <lib>/libglib-2.0.0.dylib
raco setup: deleting: foreign library <lib>/libedit.0.dylib
raco setup: deleting: foreign library <lib>/libpng16.16.dylib
raco setup: deleting: foreign library <lib>/libpangocairo-1.0.0.dylib
raco setup: deleting: foreign library <lib>/libgobject-2.0.0.dylib
raco setup: deleting: foreign library <lib>/libgthread-2.0.0.dylib
raco setup: deleting: foreign library <lib>/libcairo.2.dylib
raco setup: deleting: foreign library <lib>/libgmp.10.dylib
raco setup: deleting: foreign library <lib>/libpangoft2-1.0.0.dylib
raco setup: deleting: foreign library <lib>/libgmodule-2.0.0.dylib
raco setup: deleting: foreign library <lib>/libharfbuzz.0.dylib
raco setup: deleting: foreign library <lib>/libexpat.1.dylib
raco setup: deleting: foreign library <lib>/libfreetype.6.dylib
raco setup: deleting: foreign library <lib>/libpixman-1.0.dylib
raco setup: deleting: foreign library <lib>/libfontconfig.1.dylib
raco setup: deleting: foreign library <lib>/libpango-1.0.0.dylib
raco setup: deleting: foreign library <lib>/libfribidi.0.dylib
raco setup: updating: foreign library list
raco setup: --- installing shared files ---                        [9:18:34]
raco setup: --- compiling collections ---                          [9:18:34]
raco setup: making: <collects>/racket
raco setup: --- parallel build using 8 jobs ---                    [9:18:34]
...
```
continuing to investigate.

It seems like a safe bet that this is related to my use of `#f` in a location other than the last in my lib-search-path.

**Comment by jbclements** [comment]
Okay, did a bit more investigation, and I confirmed that the problem occurs only when I set `(lib-search-dirs . (#f "/opt/local/lib"))` in `racket/etc/config`. Moreover, it's pretty clear that the deletion is being caused by this code:

```racket
(define (tidy-libs user? target-dir receipt-dir installed-libs ccs-to-compile)
      (clean-previous-delete-failures receipt-dir path->relative-string/*)
      (define receipt-path (build-path receipt-dir receipt-file))
      (define ht (read-receipt-hash receipt-path))
      (define ht2 (for/fold ([ht (hash)]) ([(k v) (in-hash ht)])
                    (define coll-path (and (pair? v)
                                           (list? v)
                                           (andmap path-string? v)
                                           (apply collection-path v #:fail (lambda (s) #f))))
                    (cond
                     [(hash-ref installed-libs k #f)
                      ;; just installed it, so keep it
                      (hash-set ht k v)]
                     [(and coll-path
                           ;; If we set up this collection, then the lib
                           ;; must be in the installed list if it's to be kept:
                           (let ([coll (map string->path v)])
                             (not
                              (for/or ([cc (in-list ccs-to-compile)])
                                (equal? coll (cc-collection cc))))))
                      ;; keep the lib
                      (hash-set ht k v)]
                     [else
                      ;; remove the lib
                      (define lib-path (build-dest-path target-dir (bytes->path-element k)))
                      (when (or (file-exists? lib-path)
                                (directory-exists? lib-path))
                        (setup-printf "deleting" (string-append what " ~a")
                                      (path->relative-string/* lib-path))
                        (delete-directory/files/hard lib-path))
                      ht])))
      (unless (equal? ht ht2)
        (setup-printf "updating" (format "~a list" what))
        (write-receipt-hash receipt-path ht2)))
```

It looks to me like ... actually, I'm not sure under what circumstances this library deletion makes sense. I'm guessing there's some kind of a baked-in assumption that the final directory is the target location for libraries?

I guess I should clarify why it is that I'm not putting `#f` last; I want to use libraries installed by macports, but I don't want them to override the libraries that come with DrRacket, which are (I believe) newer and needed.

I should probably experiment with different settings here, just to make sure that I'm understanding the role of this setting correctly.

**Comment by mflatt** [comment]
I think the problem is on line 1867 of "collects/setup/set-core.rkt" as added in 97e96cdba5a28e7efba06ca3ccbc7d5cc6dd4041. The main intent of that commit was `(same-content? src p)`, but then it also needed to handle the case that a library comes from a package in "move" mode, there there's maybe not a copy of the library at `src` in the installed package. But it looks like that attempt to handle "move" mode is just wrong, and it ends up deleting the library merely because it was previously installed in "move" mode.

I think the repair is to replace

```
(or (and moving?
         (not (file-exists? src))
         (not (directory-exists? src)))
    (same-content? src p))
```

with just

```
(same-content? src p)
```

and not try to do anything special for "move" mode.

If a library in "move" mode has already been moved, then `same-content?` will produce `#f`, and so the library will stick around. If a library in "move" mode hasn't been moved, then it's sitting in the installed package, and the `(same-content? src p)` check will compare as intended; that is, if the libraries match, the library won't be moved, but it also won't be discarded and could get moved by a future `raco setup` if the other library goes away or changes to that it doesn't match.

**Comment by jbclements** [comment]
Many thanks! I had not yet made the time to read the docs to understand what "move" mode means in this context, and I'm grateful to you for fixing this.
