### ISSUE TITLE
[Feature Request] transparent lambdas for debugging purposes

### ISSUE THREAD

**Issue by omentic** [racket/racket#5102]
**Is your feature request related to a problem? Please describe.**
In the interpreters course I'm taking right now, several data structures are implemented using lambdas. This has led to difficulties in debugging for many students. It would be nice if lambdas, too, supported something like the `#:transparent` marker on `structs`: some way to keep around the body of the lambda at runtime, to be able to print it out in debug statements rather than the opaque `#<procedure>` marker currently used.

**Describe the solution you'd like**

I'd like the `(lambda ...)` and `(λ ...)` forms to take an optional `#:transparent` option somewhere in their declaration: probably between `lambda` and the start of their parameters. When present, this would keep around an s-exp corresponding to the body of the lambda at runtime, and overwrite the display methods to print it instead.

**Describe alternatives you've considered**
This is easily implementable as a macro.

```racket
(require syntax/parse/define)

(struct transparent-function (implementation code)
  #:methods gen:custom-write
  [(define (write-proc this out mode)
     (define code (transparent-function-code this))
     (case mode
       [(#true) (write code out)]
       [(#false) (display code out)]
       [(0 1) (print code out mode)]))]
  #:property prop:procedure 0)

(define-syntax-parse-rule (transparent-lambda (arg:id ...) body:expr ...+)
  (transparent-function
   (lambda (arg ...) body ...)
   '(transparent-lambda (arg ...) body ...)))
```
(code adapted from something @ notjack once wrote)

The main reason why I think this would be useful to have in core Racket, rather than as a macro in a library somewhere, is for **easier debugging for students**. Students learning Racket are less likely to be willing to install libraries - it's just an extra step, that requires some knowledge of how their environment is configured, that may not be worth it. And putting it in core Racket means that teaching resources can adapt their resources to use it accordingly.

The main reason I see against doing this is that lambdas don't seem to have options specified in their syntax in the same way structs do. Revising their syntax just for one option seems possibly not worth it, and I also don't know if that would break anything.

This is also probably not very performant. I can't imagine keeping around an s-exp at runtime that's just used for pretty printing to be great. But, one would likely only be using `#:transparent` for debugging purposes.

**Do you want to contribute to this feature**
I'm interested in working on this feature, if it's wanted! But I don't have a lot of time right now. It is far from important, though.

**Comment by mfelleisen** [comment]
This really sounds like an argument for a teaching language, something like `#lang interpreters`, which is mostly Racket but with functions in general replaced by transparent versions. The instructor (William?) should supply this teaching language for this PL course and show students how to install this teaching language during the first lab/lecture.

**Comment by jackfirth** [comment]
> Students learning Racket are less likely to be willing to install libraries - it's just an extra step, that requires some knowledge of how their environment is configured, that may not be worth it.

You can install packages from within DrRacket, which lets you avoid dealing with the terminal. Does that work for your use case?

**Comment by omentic** [comment]
Hmm, I'm not really sure. I'm not sure how many people are using DrRacket vs. another editor and the language server. I guess if anyone is using another editor, it's reasonable to think they have Racket installed well enough to run `raco pkg install whatever`.

This is for Ron's interpreter course, actually! It used to use `#lang plai`. I think it moved to `#lang racket` because the non-standard Racket features it uses are so minimal (only exceptions, exception checkers, and `...` for holes) but I'm not entirely sure why. I might collect other things I've found to make debugging easier and pitch that or a bigger helper library to him at the end of term, then.

**Comment by shhyou** [comment]
@omentic If the file is saved to the disk, the lambdas should have source locations are their names.

```racket
#lang plai

    (lambda (x y z)
      (* x (+ y z)))
```

```plain
Welcome to DrRacket, version 8.15.0.4 [cs].
Language: plai, with debugging; memory limit: 256 MB.
#<procedure:...s7/name-lambdas.rkt:3:4>
> 

●[Nov11 19:23:47] $ racket name-lambdas.rkt 
#<procedure:...s7/name-lambdas.rkt:3:4>
```
