### ISSUE TITLE
Case does not work correctly

### ISSUE THREAD

**Issue by Tuplanolla** [racket/racket#5105]
**What version of Racket are you using?**

I used every version from `8.3 [cs]` to `8.6 [cs]`.

**What program did you run?**

I ran the following program.

``` racket
#lang r5rs

(case 'x
  ((x (y z)) 'a)
  (else 'b))
```

**What should have happened?**

The program should have produced `'a`,
but it actually produced `'b`.
This violates section 4.2.1 of R5RS,
which says that the previous program should be equivalent
to the following program.

``` racket
#lang r5rs

(if (or (eqv? 'x 'x)
        (eqv? 'x '(y z)))
  'a 'b)
```

**Any other relevant details?**

This issue also concerns `r6rs`,
where the program violates section 11.4.5 of R6RS.
However, this issue does not apply to `racket`,
since its `case` is based on `equal?` instead of `eqv?`,
as stated in section 3.13 of The Racket Reference.

**Comment by samth** [comment]
This is caused by an extra pair of parens in the expansion; I will push a fix later today.

**Comment by soegaard** [comment]
As a workaround you can use (from R5RS):

```
(define-syntax case
  (syntax-rules (else)
    ((case (key ...)
       clauses ...)
     (let ((atom-key (key ...)))
       (case atom-key clauses ...)))
    ((case key
       (else result1 result2 ...))
     (begin result1 result2 ...))
    ((case key
       ((atoms ...) result1 result2 ...))
     (if (memv key '(atoms ...))
         (begin result1 result2 ...)))
    ((case key
       ((atoms ...) result1 result2 ...)
       clause clauses ...)
     (if (memv key '(atoms ...))
         (begin result1 result2 ...)
         (case key clause clauses ...)))))
```

**Comment by benknoble** [comment]
Interesting: `#lang r5rs` and `#lang racket` differ in how they expand `case`:

```
(module temp r5rs
  (#%plain-module-begin
   (module configure-runtime racket/base
     (#%module-begin
      (module configure-runtime '#%kernel
        (#%module-begin
         (#%require racket/runtime-config)
         (#%app configure '#f)))
      (#%require r5rs/init)))
   (let-values (((v) 'x))
     (if (#%app memv v '((x (y z)))) (let-values () 'a) (let-values () 'b)))))
```

```
(module temp racket
  (#%module-begin
   (module configure-runtime '#%kernel
     (#%module-begin (#%require racket/runtime-config) (#%app configure '#f)))
   (#%app
    call-with-values
    (lambda ()
      (let-values (((tmp) 'x))
        (if (if (#%app equal? tmp 'x) '#t (#%app equal? tmp '(y z)))
          (let-values () 'a)
          (let-values () 'b))))
    print-values)))
```

The latter uses what looks like an expanded `or` while the former uses `memv` (with extra parens, as noted).

**Comment by soegaard** [comment]
The R5RS `case` checks whether `eqv?` and `equal?` will give the same results for all datums.
If so, the standard `case` from Racket is used.
Otherwise, the `case` expression is converted to a `cond` where each clause corresponds to
an `memv` test.

https://github.com/racket/r5rs/blob/master/r5rs-lib/r5rs/main.rkt#L418

The problem Sam alluded to is `(memv v '(datums))` which should have been `(memv v 'datums)`.
