### ISSUE TITLE
Infinite Loop in `for/stream` with `(in-naturals)` and `#:unless #t`

### ISSUE THREAD

**Issue by NoahStoryM** [racket/racket#5120]
**What version of Racket are you using?**
8.15 [cs]

**What program did you run?**
I ran the following code in Racket:

```racket
(stream->list (for/stream ([i (in-naturals)] #:unless #t) i))
```

This causes the program to enter an infinite loop.

Here are some similar examples that behave as expected:
```racket
Welcome to Racket v8.15 [cs].
> (stream->list (for/stream ([i (in-naturals)]) #:break #t i))
'()
> (stream->list (for/stream ([i 10] #:unless #t) i))
'()
```

Additionally, I have other code using `(for/stream ([i (in-naturals)] #:unless #t) expr ...)` that does not enter an infinite loop. However, I haven't been able to simplify those examples to create a minimal reproducible example. As a result, I'm uncertain about the specific conditions that trigger the infinite loop.

**What should have happened?**
```racket
> (stream->list (for/stream ([i (in-naturals)] #:unless #t) i))
'()
```

**If you got an error message, please include it here.**
```racket
> (stream->list (for/stream ([i (in-naturals)] #:unless #t) i))
^Cuser break [,bt for context]
> ,bt
user break
  context...:
   /usr/share/racket/collects/racket/private/stream-cons.rkt:58:45: body of top-level
   /usr/share/racket/collects/racket/private/stream-cons.rkt:66:0: stream-force
   /usr/share/racket/collects/racket/private/stream-cons.rkt:46:30
   /usr/share/racket/collects/racket/private/for.rkt:552:2: unsafe-stream-not-empty?
   /usr/share/racket/collects/racket/stream.rkt:113:0: stream->list
   /usr/share/racket/pkgs/xrepl-lib/xrepl/xrepl.rkt:1573:0
   /usr/share/racket/collects/racket/repl.rkt:11:26
```

**Comment by AlexKnauth** [comment]
Looks like expected, intended behavior to me.

If you want it to stop iterating, use `#:break` or `#:final` instead of `#:unless`. Like you already do in your `#:break #t` similar example.
