### ISSUE TITLE
Compiling racket-mode/racket/define-fallbacks.rkt causes rhombus to be compiled

### ISSUE THREAD

**Issue by samth** [racket/racket#5130]
To reproduce:

1. Change some parts of rhombus without recompiling it (`git pull` usually works for me :)
2. go to the `racket-mode/racket` directory
3. remove the `compiled/` subdirectory
4. run `raco make -v define-fallbacks.rkt`
5. Observe output about rhombus

Note that [that file] or its [one non-base dependency] use rhombus at all.

[that file]: https://github.com/greghendershott/racket-mode/blob/master/racket/define-fallbacks.rkt
[one non-base dependency]: https://github.com/greghendershott/racket-mode/blob/master/racket/safe-dynamic-require.rkt

cc @greghendershott

**Comment by samdphillips** [comment]
Looks like https://github.com/greghendershott/racket-mode/blob/master/racket/safe-dynamic-require.rkt#L31 dynamic requires rhombus and runs `for-syntax`.  Shouldn't that cause a recompile?

**Comment by greghendershott** [comment]
I'm not sure why I did the `dynamic-require` eagerly, there. There's no justification. This is only used once, and only to decide whether to run some rackunit tests.

IOW I could/should:

```diff
-(define rhombus-installed?
-  (let ([v (module-installed? 'rhombus)])
-    (λ () v)))
+(define (rhombus-installed?)
+  (module-installed? 'rhombus))
```
