### ISSUE TITLE
cross-compilation: cross-compiling to Linux fails on 8.14 and 8.15

### ISSUE THREAD

**Issue by Bogdanp** [racket/racket#5133]
**What version of Racket are you using?**
8.14 CS and 8.15 CS. I haven't tried cross-compiling to Linux from HEAD yet, but I frequently cross compile from HEAD for other platforms, so this might be an issue with the released cross-compilers.

**What program did you run?**

```
$ echo "#lang racket/base' > test.rkt
$ raco cross --target x86_64-linux --version 8.15 exe -o test test.rkt
$ raco cross --target x86_64-linux --version 8.15 dist dist test
```

I then shipped the result to a Linux machine and tried to run it.

**What should have happened?**

It should run successfully.

**If you got an error message, please include it here.**

```
fasl-read: incompatible fasl-object machine-type 'tarm64osx found in #<binary input port bytevector>
  context...:
   body of data
```

Using release 8.13, everything seems to work fine.

**Comment by mflatt** [comment]
It looks like I got this line backwards:

https://github.com/racket/racket/commit/336e78ebd1d9e769501c1ede1713b381c46e2084#diff-a40a04285d3ca3db269357d8c60fdbb2464dc302831b3d9079f540a56fc79340R529

That commit was meant to make things work more often without `raco cross make`, but the effect of getting the test backwards is that it made things work *less* often without `raco cross make`. If that's right, it's not clear why I thought the changed worked in the first place.

I'm still trying to convince myself that I'm reading things correctly now, but a workaround could be to use `raco cross make` before `raco cross exe`.

**Comment by Bogdanp** [comment]
Thanks for looking into it! I can confirm that running `make` before `exe` works around the problem.
