### ISSUE TITLE
Aliases of `raco pkg` do not forward keyword arguments

### ISSUE THREAD

**Issue by shhyou** [racket/racket#5140]
**What version of Racket are you using?**

Racket v8.15, as reported in racket/drracket#702.

**Please include any other relevant details**

Introduced by racket/racket@e71ca3929871 at L175 (and racket/racket@7d51e0dcba36)

**What program did you run?**

```racket
#lang racket/base

(require pkg)

(displayln 'pkg-uninstall-command)
(procedure-keywords pkg-uninstall-command)
(displayln 'pkg-remove-command)
(procedure-keywords pkg-remove-command)
```

**What should have happened?**

The accepted keywords should be the same, but they are not: 

```
pkg-uninstall-command
'()
'(#:auto
  #:batch
  #:demote
  #:dry-run
  #:force
  #:installation
  #:jobs
  #:no-docs
  #:no-setup
  #:no-trash
  #:recompile-only
  #:scope
  #:scope-dir
  #:user)
pkg-remove-command
'()
'()
> 
```

**If you got an error message, please include it here.**

From racket/drracket#702, or `gui-pkg-manager-lib/pkg/gui/private/by-installed.rkt`:

```racket
                          (apply
                           pkg-remove-command
                           #:batch #t
                           #:scope scope
                           names)
```

**Comment by benknoble** [comment]
Thanks for catching this!
