### ISSUE TITLE
Crash in ffi_do_callback

### ISSUE THREAD

**Issue by Ahti** [racket/racket#718]
I am trying to create racket bindings for [libdispatch](http://libdispatch.macosforge.org/).

One of the functions i am trying to get to work in racket takes, among other things, a function as an argument which it will execute later on.

When this function tries to call back to the racket function i passed in, racket crashes with EXC_BAD_ACCESS (trying to access memory addres 0x8) in `ffi_do_callback`.

You can see the code I currently have here: http://pastebin.com/TWjSqSxX.

The curious thing is: If I comment out the dispatch_async call, and instead insert a dispatch_sync call on another queue (commented out currently) that works just fine, so the callback mechanism itself seems to work fine, just not when the asynchronous version is used.

**Comment by mflatt** [comment]
Closing because the issue seems likely to be concurrency-related and could be solved by `#:async-apply`. We can reopen if further info suggests that something else needs to be fixed.
