### ISSUE TITLE
build failed on armv7hl

### ISSUE THREAD

**Issue by mordae** [racket/racket#748]
According to [build log in Fedora Koji](https://kojipkgs.fedoraproject.org/work/tasks/3300/7243300/build.log):

```
lt-racketcgc: ./unwind/libunwind.c:2711: _ULARM_dwarf_search_unwind_table:
              Assertion `ip >= di->start_ip && ip < di->end_ip' failed.
```

**Comment by shamansir** [comment]
Same for me

**Comment by shamansir** [comment]
This link contains the patch with a fix: https://groups.google.com/forum/#!msg/racket-users/j7buyPoSwUE/fhTeHk8LAAAJ

The patch and recommendations from Juan Francisco Cantero Hurtado (a copy from the mentioned) thread:

> Install also libffi and use "--enable-libffi". 

```patch
diff --git a/racket/src/racket/sconfig.h b/racket/src/racket/sconfig.h
index ca5cce6..f80ef04 100644
--- a/racket/src/racket/sconfig.h
+++ b/racket/src/racket/sconfig.h
@@ -259,9 +259,6 @@
 #endif
 # if defined(__arm__)
 # define MZ_USE_JIT_ARM
-# ifndef __ANDROID__
-#  define MZ_USE_DWARF_LIBUNWIND
-# endif
 #endif
 
 #endif
```

> Steps, if still failed to work:

> - Remove the old git repo. 
> - Delete every file installed by racket within `~/.local`. 
> - `rm -rf "~/.racket/6.*"` 
> - `mkdir -p "~/.local/bin"` 
> - `export PATH="$PATH:~/.local/bin" `
> - `git clone --depth 1 --single-branch https://github.com/racket/racket.git racket-git`
> - `cd racket-git` 
> - copy the patch 
> - `patch -p1 -i racket-arm-unwind.patch` 
> - `cd racket/src` 
> - `./configure --enable-shared --prefix="~/.local" --enable-libffi` 
> - `make` 
> - `make install` 
> - `raco pkg install --auto main-distribution (or any other raco package)`

**Comment by stamourv** [comment]
@mflatt @jeapostrophe: Should we apply this patch?

**Comment by jeapostrophe** [comment]
I think so.
