### ISSUE TITLE
make install failed

### ISSUE THREAD

**Issue by mitchellwills** [racket/racket#769]
wget http://mirror.racket-lang.org/installers/6.1/racket-6.1-src-builtpkgs.tgz
tar zxvf racket-6.1-src-builtpkgs.tgz
cd racket-6.1
cd src
./configure --prefix=~/.local
make
make install

When running the commands above I get the following error.
Redhat 5.10
make plain-install runs successfully, but does not install raco
Any suggestions

...
raco setup: launcher: <gui-bin>/plt-games                                                                                                                                                                           [70/1962]
raco setup: launcher: <console-bin>/mzc
raco setup: launcher: <console-bin>/setup-plt
raco setup: launcher: <console-bin>/mzpp
raco setup: launcher: <console-bin>/mztext
raco setup: launcher: <console-bin>/plt-r5rs
raco setup: launcher: <console-bin>/plt-r6rs
raco setup: launcher: <console-bin>/scribble
raco setup: launcher: <console-bin>/slatex
raco setup: launcher: <console-bin>/pdf-slatex
raco setup: launcher: <gui-bin>/slideshow
raco setup: launcher: <console-bin>/swindle
raco setup: launcher: <console-bin>/plt-web-server
raco setup: --- installing man pages ---
raco setup: installing: man page <man>/man1/racket.1
raco setup: installing: man page <man>/man1/raco.1
raco setup: installing: man page <man>/man1/drracket.1
raco setup: installing: man page <man>/man1/mred.1
raco setup: installing: man page <man>/man1/gracket.1
raco setup: installing: man page <man>/man1/mzc.1
raco setup: installing: man page <man>/man1/mzscheme.1
raco setup: installing: man page <man>/man1/setup-plt.1
raco setup: installing: man page <man>/man1/plt-help.1
raco setup: --- building documentation ---
raco setup: docs failure: sqlite3_clear_bindings: implementation not found; arguments: #<cpointer:sqlite3_statement>
raco setup: --- installing collections ---
raco setup: --- post-installing collections ---
raco setup: post-installing: <pkgs>/gui-lib/mred
raco setup: post-installing: <pkgs>/gui-lib/racket/gui
raco setup: post-installing: <pkgs>/mzcom
raco setup: post-installing: <pkgs>/mzscheme-lib/mzscheme
raco setup: post-installing: <pkgs>/racket-doc/help
raco setup: --- checking package dependencies ---
call-with-file-lock/timeout: contract violation
  expected: (>=/c 0.0)
  given: -1546188227.0
  context...:
   /home/mwills/.local/share/racket/collects/racket/file.rkt:298:0: call-with-file-lock/timeout35
   /home/mwills/.local/share/racket/collects/pkg/lib.rkt:794:0: pkg-directory**52
   /home/mwills/.local/share/racket/collects/racket/contract/private/arrow-val-first.rkt:255:18
   /home/mwills/.local/share/racket/collects/setup/private/pkg-deps.rkt:107:2: get-immediate-pkg-info!
   /home/mwills/.local/share/racket/collects/setup/private/pkg-deps.rkt:189:2: register-pkg!
   /home/mwills/.local/share/racket/collects/setup/private/pkg-deps.rkt:225:2: init-pkg-internals!
   /home/mwills/.local/share/racket/collects/setup/private/pkg-deps.rkt:425:2: for-loop
   /home/mwills/.local/share/racket/collects/setup/private/pkg-deps.rkt:25:0: check-package-dependencies
   /home/mwills/.local/share/racket/collects/setup/setup-core.rkt:65:0: setup-core
   /home/mwills/.local/share/racket/collects/setup/setup-go.rkt: [running body]
   /home/mwills/.local/share/racket/collects/setup/main.rkt: [running body]
make[1]: *** [install-3m] Error 1
make[1]: Leaving directory `/isihome/mwills/.dotfiles/src/racket/racket-6.1/src'
make: *** [install] Error 2

**Comment by harrisi** [comment]
On Fedora 23 trying to compile 6.1-src-builtpkgs leads to this error (for me):

```
ranlib libracket.a
make[5]: Leaving directory '/home/ian/racket-6.1/src/racket'
make[4]: Leaving directory '/home/ian/racket-6.1/src/racket'
make racketcgc 
make[4]: Entering directory '/home/ian/racket-6.1/src/racket'
gcc -I. -I./include -g -O2  -Wall   -pthread   -DINITIAL_COLLECTS_DIRECTORY='"'"`cd ./../../collects; pwd`"'"' -DINITIAL_CONFIG_DIRECTORY='"'"`cd ./../..; pwd`/etc"'"' -c ./main.c -o main.o
gcc -o racketcgc main.o  libracket.a libmzgc.a  -pthread -ldl -lm  -ldl -lm -rdynamic 
make[4]: Leaving directory '/home/ian/racket-6.1/src/racket'
make[3]: Leaving directory '/home/ian/racket-6.1/src/racket'
cd gc2; make all
make[3]: Entering directory '/home/ian/racket-6.1/src/racket/gc2'
mkdir xsrc
make xsrc/precomp.h
make[4]: Entering directory '/home/ian/racket-6.1/src/racket/gc2'
env XFORM_PRECOMP=yes ../racketcgc  -cqu ./xform.rkt --setup . --cpp "gcc -E -I./.. -I./../include -pthread    "  --keep-lines -o xsrc/precomp.h ./precomp.c
mprotect for generate-code page failed; aborting
mprotect for generate-code page failed; aborting
mprotect for generate-code page failed; aborting
mprotect for generate-code page failed; aborting
Makefile:202: recipe for target 'xsrc/precomp.h' failed
make[4]: *** [xsrc/precomp.h] Segmentation fault (core dumped)
make[4]: Leaving directory '/home/ian/racket-6.1/src/racket/gc2'
Makefile:172: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/home/ian/racket-6.1/src/racket/gc2'
Makefile:95: recipe for target '3m' failed
make[2]: *** [3m] Error 2
make[2]: Leaving directory '/home/ian/racket-6.1/src/racket'
Makefile:57: recipe for target '3m' failed
make[1]: *** [3m] Error 2
make[1]: Leaving directory '/home/ian/racket-6.1/src'
Makefile:51: recipe for target 'all' failed
make: *** [all] Error 2
```

However, I can install Racket 6.4 just fine on Fedora 23 (provided I have enough memory and storage).

**Comment by apaprocki** [comment]
Getting the same error in 6.4-src-builtpkgs on RHEL5:

```
...
raco setup: --- building documentation ---
raco setup: docs failure: sqlite3_clear_bindings: implementation not found; arguments: #<cpointer:sqlite3_statement>
raco setup: --- installing collections ---
raco setup: --- post-installing collections ---
raco setup: post-installing: <pkgs>/gui-lib/mred
raco setup: post-installing: <pkgs>/gui-lib/racket/gui
raco setup: post-installing: <pkgs>/mzcom
raco setup: post-installing: <pkgs>/mzscheme-lib/mzscheme
raco setup: post-installing: <pkgs>/racket-doc/help
raco setup: --- checking package dependencies ---
call-with-file-lock/timeout: contract violation
  expected: (>=/c 0.0)
  given: -1546188227.0
  context...:
   /prefix/share/racket/collects/racket/file.rkt:313:0: call-with-file-lock/timeout33
   /prefix/share/racket/collects/pkg/private/pkg-db.rkt:176:2: for-loop
   /prefix/share/racket/collects/racket/contract/private/arrow-val-first.rkt:335:3
   /prefix/share/racket/collects/setup/private/pkg-deps.rkt:110:2: get-immediate-pkg-info!
   /prefix/share/racket/collects/setup/private/pkg-deps.rkt:238:2: init-pkg-internals!
   /prefix/share/racket/collects/setup/private/pkg-deps.rkt:457:2: for-loop
   /prefix/share/racket/collects/setup/private/pkg-deps.rkt:26:0: check-package-dependencies
   /prefix/share/racket/collects/setup/setup-core.rkt:70:0: setup-core
   /prefix/share/racket/collects/setup/setup-go.rkt: [running body]
   /prefix/share/racket/collects/setup/main.rkt: [running body]
make[2]: *** [install-3m] Error 1
make[2]: Leaving directory `/build'
make[1]: *** [install] Error 2
make[1]: Leaving directory `/build'
```
