### ISSUE TITLE
Can't build from Git

### ISSUE THREAD

**Issue by DemiMarie** [racket/racket#832]
After

```
mkdir build
cd build
../configure --prefix=/usr/local
```

`make` fails with 

```
../../../racket/src/file.c: In function ‘do_directory_list’:
../../../racket/src/file.c:5396:13: error: ‘struct dirent’ has no member named ‘d_namlen’
     nlen = e->d_namlen;
```

Platform: Fedora 20 Linux

**Comment by samth** [comment]
Seems like this should be handeld by the `DIRENT_NO_NAMLEN` configure variable, but I guess it didn't find it correctly.

**Comment by mflatt** [comment]
Is this still a problem? I was not able to observe the problem on a fresh Fedora 20 installation for x86_64 with sources as old as v6.1.

As of v6.4, Racket headers to detect `__linux__` instead of `linux`. There's some chance that fixed the problem in the environment for the original report.

**Comment by pmatos** [comment]
I don't see this happen anymore. Certainly not in HEAD, or recent Fedora 27 following OP command line. Should we close?

**Comment by pmatos** [comment]
No point in keeping these open. Reopen if necessary.
