### ISSUE TITLE
TR-related error while building for RHEL 7

### ISSUE THREAD

**Issue by mordae** [racket/racket#846]
H! For some reason the `epel-7-x86_64` build of `racket-6.1.1` fails. See the [full build log](http://copr-be.cloud.fedoraproject.org/results/mordae/racket/epel-7-x86_64/racket-6.1.1-4.fc21/build.log).

```
...1.1-4.el7.centos.x86_64/usr/share/racket/pkgs/typed-racket-more/typed/private/framework-types.rkt:235:2: Type Checker: parse error in type;
 class member type not a subtype of parent member type
  member: read
  type: (-> (Instance Editor-Stream-In%) (Instance Editor-Snip:Decorated<%>))
  parent type: (-> (Instance Editor-Stream-In%) (U False Snip%-Instance))
  in: (Class #:implements Snip-Class% (make-snip ((Instance Editor-Stream-In%) -> (Instance Editor-Snip:Decorated<%>))) (read ((Instance Editor-Stream-In%) -> (Instance Editor-Snip:Decorated<%>))))
```

**Comment by harrisi** [comment]
I don't know if I can run RHEL7, but it seems like this can be closed (based on @samth's last comment). Racket 6.4 works fine for newer versions of Fedora, and I can only hope this would hold true for RHEL.

**Comment by mordae** [comment]
I have no idea, but I don't really have the time to track or solve this. Sorry. :-(

**Comment by samth** [comment]
This was a bug in TR, which has been fixed, so closing this is the right thing.
