### ISSUE TITLE
Compile/Install segfaults on openSUSE:Factory

### ISSUE THREAD

**Issue by sfalken** [racket/racket#856]
Attempting to package up 6.1.1 for openSUSE Factory/Tumbleweed, and I keep getting the following error:

raco setup: 3 rendering: <pkgs>/typed-racket-doc/typed-racket/scribblings/ts-reference.scrbl
Seg fault (internal error) at 0x7f519ff78000
Makefile:155: recipe for target 'install-3m' failed

Please let me know what information you need, so far, I've had *zero* luck tracking it down myself.

**Comment by mflatt** [comment]
I never investigated this combination of version of platform. We used to get a handful of reports like this, and repairs for GC and places (for parallel builds) made during 2015 seem to have taken care of the problems. So, I'll close this issue for now, but we can certainly reopen if v6.4 or later still have a problem.
