### ISSUE TITLE
The for clause [i (#%datum <integer>)]

### ISSUE THREAD

**Issue by soegaard** [racket/racket#883]
Currently (for/list ([i 100]) i) and (for/list ([i (in-range 100)]) i) doesn't produce the same code.
I suggest special casing the clause [i (#%datum <integer>)].

```
(require racket/pretty)
(pretty-print (syntax->datum (expand #'(for ([j 100]) j))))
(pretty-print (syntax->datum (expand #'(for ([j (in-range 100)]) j))))

(equal? (syntax->datum (expand #'(for ([j 100]) j)))
         (syntax->datum (expand #'(for ([j (in-range 100)]) j))))
```

**Comment by gus-massa** [comment]
I think this is a good idea, but it's necessary to be careful with the details, just in case someone redefined `#%datum`. 

    #lang racket
    (require (only-in racket (#%datum #%old-datum)))
    (define-syntax-rule (#%datum . x) (#%old-datum . 7))
    (for/list ([i 10]) i)

Perhaps wait until it's expanded to `(quote 10)`.
