### ISSUE TITLE
Better error message for matching structs

### ISSUE THREAD

**Issue by soegaard** [racket/racket#888]
I just got this error message:

space-invaders.rkt:90:16: match: wrong number for fields for structure invader: expected 5 but got 3 at: (x y size) in: (invader x y size)
  #(2642 18)

Here I forgot the fields patrol-x and speed-x. It would be helpful to get the names of the forgotten fields in the error message.

**Comment by harrisi** [comment]
This should be closed thanks to racket@8615b2b6fcc88fd27562867afb3168300412a39f, I believe.
