### ISSUE TITLE
Phantom bytes cause strange GC behavior

### ISSUE THREAD

**Issue by quantum1423** [racket/racket#962]
This piece of code here: https://gitlab.com/snippets/5769 causes Racket to continually do major GCs, with no minor GCs in between. Racket also estimates a very implausible heap size for itself; PLTSTDERR=debug spams out this line repeatedly:

````
GC: 0:MAJ @ 468,782,238K(+-468,730,046K)[+1,108K]; free 468,762,239K(-468,762,239K) 40ms @ 7960
````

This problem seems to also manifest when allocating a large number of `bitmap%`s, which I presume are backed by some sort of C array with a phantom bytestring to trigger GC? When allocating `bitmap%`s in a loop, the same behavior of frequent major GCs with no minor GCs occur, and of course that's horrible in a GUI animation.

**Comment by mflatt** [comment]
I'll repair reporting so that it always includes phantom bytes, so "+-" won't appear in the GC log.

I'm not sure I understand the rest of the issue. Triggering a garbage collection is very much the intent of phantom-byte allocation. In particular, a large bitmap in a loop creates garbage that must be cleaned up relatively frequently, if the bitmap is large, and phantom bytes trigger that clean up. It's a bug if phantom bytes are not lined up with actual bitmap allocation, though.

**Comment by quantum1423** [comment]
The issue seems to be that phantom bytes trigger major collections, but never minor collections. So using phantom bytes to trigger GCs can sometimes instead greatly increase GC latency since minor collections don't happen before major collections are triggered. A thread in a loop allocating phantom bytes can freeze up the entire VM because the phantom short-lived garbage cannot be efficiently dealt with by the generational GC, instead it thrashes the major GC (which is very slow for equivalent heap sizes compared to major GCs from other VMs, but that's another issue)

**Comment by mflatt** [comment]
Thanks for the clarification! I've adjusted the collector to better take into account phantom-byte counts for triggering GCs.

Your original example still triggers only major GCs when run by itself, but it now triggers minor GCs when run in a context with a larger overall footprint.

**Comment by quantum1423** [comment]
If you wouldn't mind, what adjustments exactly were made?

**Comment by quantum1423** [comment]
It still seems to be the case that minor GCs don't "collect" the phantom bytes. So even though phantom-byte allocation would trigger collection of other data, the phantom bytes themselves aren't collected, and thus allocating phantom bytes in a loop (which, say, to malloc'd memory in the FFI) would still cause embarassingly long pauses.

That is, FFI memory still can't be collected in a generational manner by simply freeing them in a will of some phantom byte string. Animations using bitmaps still trigger frequent major GCs. On the other hand, using actual byte strings does the trick, and reduces GC latency.

If this is impossible/unreasonably hard to fix, at least there should be some parameter to make all the phantom-byte functions actually do nothing. GCs would probably run at inconvenient times and cause memory usage to be overly high, but I would think that pauses could be reduced. A 10 fps animation has no reason to not be smooth (almost) all of the time with a modern GC, and shouldn't pause every two seconds.

**Comment by mflatt** [comment]
I think that phantom bytes were being double-counted, and I've pushed a change along those lines.

Sorry if It seems like I'm not giving this enough attention. Actually, I've spent the last several days on the GC with the goal of better supporting interactive programs. (I've tried to talk other people into working on the GC, but it doesn't look like that's going to happen.)

**Comment by samth** [comment]
I think there are still some issues with GC of phantom bytes causing more major GCs than necessary.

Consider:

```
[samth@huor:~/tmp plt] cat pb.rkt
#lang racket/base

(define t
  (thread (lambda ()
            (let loop()
              (make-phantom-bytes (* 1 1000 1000))
              (loop)))))
(sleep 2)

(kill-thread t)

[samth@huor:~/tmp plt] cat b.rkt
#lang racket/base

(define t
  (thread (lambda ()
            (let loop()
              (make-bytes (* 1 1000 1000))
              (loop)))))
(sleep 2)

(kill-thread t)
```

Running these with my `gcstats` tool:

```
[samth@huor:~/tmp plt]  r -l gcstats -t  pb.rkt


 51,445,910,528 bytes allocated in the heap
 51,444,501,720 bytes collected by GC
     79,647,080 bytes max heap size
     47,715,920 bytes max slop
    127,207,616 bytes peak total memory use

Generation 0:   1,141 collections,      218ms,   188.30ms elapsed
Generation 1:     375 collections,    1,719ms, 1,762.02ms elapsed

INIT  time        24 ms
MUT   time        86 ms (     87.74 ms elapsed)
GC    time     1,937 ms (  1,950.31 ms elapsed)
TOTAL time     2,047 ms (  2,062.06 ms elapsed)

Max pause time:      15.05 ms
%GC time             95.75 %   ( 95.69 % elapsed)

Alloc rate     598,208,261,953 bytes per MUT second
```

Whereas:
```
[samth@huor:~/tmp plt]  r -l gcstats -t  b.rkt


  3,245,420,472 bytes allocated in the heap
  3,244,016,736 bytes collected by GC
     75,715,784 bytes max heap size
    129,515,544 bytes max slop
    134,078,464 bytes peak total memory use

Generation 0:     567 collections,       96ms,   120.49ms elapsed
Generation 1:     105 collections,      470ms,   472.45ms elapsed

INIT  time        18 ms
MUT   time     1,460 ms (  1,433.07 ms elapsed)
GC    time       566 ms (    592.94 ms elapsed)
TOTAL time     2,044 ms (  2,044.01 ms elapsed)

Max pause time:       8.01 ms
%GC time             27.94 %   ( 29.27 % elapsed)

Alloc rate     2,222,890,734 bytes per MUT second
```

Racket is getting about 1/4th the allocation rate with phantom bytes, and spending 95% of its time in GC.

This is with the most recent commits.

**Comment by samth** [comment]
Actually, I read that wrong. Racket is allocating many more phantom bytes than regular ones. I suppose that's to be expected since they're fake.

**Comment by mflatt** [comment]
I think we've sorted out problems with phantom bytes along the way to v6.4.
