### ISSUE TITLE
string->url doesn't parse literall IPv6 addresses

### ISSUE THREAD

**Issue by tim-brown** [racket/racket#980]
The following URL: `ldap://[2001:db8::7]/c=GB?objectClass=one&objectClass=two` does not parse correctly. The `host` should be `[2001:db8::7]`. Instead the URL parses as:
```
URL: "ldap://[2001:db8::7]/c=GB?objectClass=one&objectClass=two"
scheme:         "ldap"
host:           "[2001"
path-absolute?: #f
path  bits:     ("db8::7]" "c=GB")
query:          ((objectClass . "one") (objectClass . "two"))
```
I'm sure it's simple enough to change, but there are a number of pull requests around this area (e.g. https://github.com/plt/racket/pull/948); so maybe this should be done when things settle down.

(Issue arose because I've just tried to implement: http://rosettacode.org/wiki/URL_parser)

**Comment by Blaisorblade** [comment]
:+1:
Any chance things did settle down?
-- A fellow Racket user

**Comment by Phlosioneer** [comment]
This is still an issue. The URL parser should look for square brackets. There are currently no pull requests involving the URL parser. The string->url function is defined [here] (https://github.com/racket/racket/blob/e6a0caa1471820ae1f8a76985858b197a35763a3/racket/collects/net/url-string.rkt). I'll try and see if I can learn enough racket to fix it, but I'm still rather new to the language.
